### ISSUE TITLE
Disable Ace

### ISSUE THREAD

**Issue by gregbanner** [ajaxorg/ace#1014]
Can Ace be disabled so that if I resize it or apply any other 2d/3d transforms it doesn't try to adjust to the new changes?

I've tried editor.setReadOnly(true); but that doesn't solve it

**Comment by AndrewPratley** [comment]
The internet is just amazing. I was having the exact same problem (text resizing on ace editor flip effect) and just cannot believe there was someone else out there that did (and asked about) the exact same thing! And this fixed it for me too! So great! Thank you!
