### ISSUE TITLE
Add indention for wrapped lines

### ISSUE THREAD

**Issue by jviereck** [ajaxorg/ace#1019]
I have some text that looks like this:

```
Foo bar
    Foo bar foo bar foo bar foo bar foo bar foo bar foo bar foo bar foo bar foo bar foo bar foo bar
```

when line breaking activated, I want the broken line to be indented as well to make it easier to read. Is this possible already with ace? 

Would you accept a pull request that adds this feature?

**Comment by victorel-petrovich** [comment]
+100!! when??
