### ISSUE TITLE
C++ highlighting bug?

### ISSUE THREAD

**Issue by niXman** [ajaxorg/ace#1170]
In the attached screenshot is shown the highlighting for three lines with the use of the directive '#include' in C++ mode.
I have two questions:
1. Why the first two lines are highlighting differently? Why in the first case the angle brackets are not highlighted and in the second - are highlighted?
2. Why the file name in angle brackets is not highlighted in the same color as the brackets themselves?

Thanks.

![1](https://f.cloud.github.com/assets/518474/29746/0762589a-4dbd-11e2-8526-9abe0ed527dd.png)

**Comment by himanshu010** [comment]
what is the code for c++ language, I tried "c++", "cpp" but both of them doesn't work.
