### ISSUE TITLE
Background color of the editor

### ISSUE THREAD

**Issue by serghd** [ajaxorg/ace#1199]
Hi all! Please tell me, how can I take a background color of the editor? Thanks for recommendations!

**Comment by slidenerd** [comment]
I am getting white everytime as the bg color unless i setTimeout, is there an event fired after which I can set the editor color, perhaps like an onReady?
```
let panelElement = document.getElementById("panel")
let editorElement = document.getElementById("editor")
let consoleElement = document.getElementById("console")

if (editorElement) {
    let editor = ace.edit("editor");
    let mode = document.getElementById("mode").value
    editor.session.setMode("ace/mode/" + mode);
    editor.setTheme("ace/theme/tomorrow_night_blue");
    editor.getSession().setUseWrapMode(true);
    editor.setShowPrintMargin(false);

    // enable autocompletion and snippets
    editor.setOptions({
        enableBasicAutocompletion: true,
        enableSnippets: true,
        enableLiveAutocompletion: true
    });

    setTimeout(()=>{
        editorElement.style.fontSize = '16px';
        editorElement.style.lineHeight = '1.6em';
        let bgColor = getComputedStyle(editor.renderer.scroller).backgroundColor
        console.log(bgColor)
        $('#console').css('background-color', bgColor)
        $('#panel').css('background-color', bgColor)
    }, 100)
}

```
If i remove the setTimeout it sets the background color as white, any suggestions are super appreciated

**Comment by nightwing** [comment]
use themeLoaded event from editor.renderer

**Comment by ldijkman** [comment]
is it possible to get the gutter color like this
i change the vertical search pos scrollbar visualizer now to backgraund of a theme like above example
but maybe the gutter color is nicer

greet luberth
https://ldijkman.github.io/Ace_Seventh_Heaven/Hell.html
