### ISSUE TITLE
Feature proposal: cut/copy current line when selection is empty.

### ISSUE THREAD

**Issue by danyaPostfactum** [ajaxorg/ace#1229]

**Comment by gavinr** [comment]
Trying to resurrect this old issue. Would prefer when you cut/copy while a selection is empty, if should put the current line into the clipboard. This is standard behavior in most modern code editors like VS Code and SublimeText. 

Would a PR that makes this change be accepted?

**Comment by nightwing** [comment]
This was [added](https://github.com/ajaxorg/ace/pull/3452/files) as an option some time ago, and can be used with `editor.setOption("copyWithEmptySelection", true)`

**Comment by gavinr** [comment]
Ah perfect. I think this issue can be closed then. Thank you very much for the reply @nightwing!
