### ISSUE TITLE
Copy-paste from editor to native apps on Windows removes newlines

### ISSUE THREAD

**Issue by ivarpruijn** [ajaxorg/ace#1283]
All newlines are removed when copy-pasting from Cloud9 IDE to a native app on Windows.

I could reproduce this issue on Cloud9 IDE, using Windows 7 & Chrome 25.

@nightwing Could you have a look if this has to do with ACE or Cloud9 itself?

**Comment by mpfz0r** [comment]
Not sure if this of any help, but I noticed that the Windows mode is only autodetected,
if I past something into Ace (e.g. from Notepad).
Just entering stuff manually with IE11 and Edge, stayed in Unix mode.
