### ISSUE TITLE
More about the workers

### ISSUE THREAD

**Issue by tucnak** [ajaxorg/ace#1341]
Hello.

It looks like Ace's documentation is not absolutely clear with workers. As far as I understood, workers are syntax checkers (or smth like that). But, it looks like I am not sure, how to install worker for JS, if current mode is set, and it's JavaScript.

So, can anyone describe how to use them in a while?

Thanks in advance!

**Comment by zxc0312** [comment]
> session.setUseWorker(false)

请问站点域是哪个？
