### ISSUE TITLE
How do I get error/warning annotations working properly when serving an app with ace editor

### ISSUE THREAD

**Issue by thlorenz** [ajaxorg/ace#1380]
I'm talking about [this app](http://thlorenz.github.io/scriptie-talkie/).
I noticed that annotations are working for the ace editor when I just open the index.html file and serve the ace.js file from my filesystem.

However when I serve the page and load the ace editor via a script tag, annotations break. Instead I see this error in the console:

```
DOMException
code: 18
message: "SecurityError: DOM Exception 18"
name: "SecurityError"
stack: "Error: An attempt was made to break through the security policy of the user agent.↵    at new g (http://d1n0x3qji82z53.cloudfront.net/src-min-noconflict/ace.js:1:262767)↵    at createWorker (http://d1n0x3qji82z53.cloudfront.net/src-min-noconflict/mode-javascript.js:1:1649)↵    at $startWorker (http://d1n0x3qji82z53.cloudfront.net/src-min-noconflict/ace.js:1:77728)↵    at setMode (http://d1n0x3qji82z53.cloudfront.net/src-min-noconflict/ace.js:1:77029)↵    at http://d1n0x3qji82z53.cloudfront.net/src-min-noconflict/ace.js:1:76911↵    at i (http://d1n0x3qji82z53.cloudfront.net/src-min-noconflict/ace.js:1:75960)↵    at e (http://d1n0x3qji82z53.cloudfront.net/src-min-noconflict/ace.js:1:1024)↵    at i (http://d1n0x3qji82z53.cloudfront.net/src-min-noconflict/ace.js:1:1630)↵    at HTMLScriptElement.<anonymous> (http://d1n0x3qji82z53.cloudfront.net/src-min-noconflict/ace.js:1:76296)"
```

I'm not sure if this is due to some cross domain issue, but would like to know what I can do to fix it.
I don't think this is a problem with the ace editor in general since I have seen this work elsewhere, I'm basically just looking for advice on how to change my setup to make this work.

The above mentioned app is setting the editor up [here](https://github.com/thlorenz/scriptie-talkie/blob/gh-pages/examples/browser/main.js#L79)

**Comment by mortalis13** [comment]
Have the problem in Firefox 36. I use the `mode-css.js` When I type a letter the error isn't showing and the **Browser Console** prints:
`TypeError: c.range is undefined`
And I don't know why it shows the file number **1**:
`worker-css.js:1:0`
And when I click on this filename it opens the source as if it were minified (in one line). It starts with this text:
```
function initBaseUrls(a){require.tlns=a}function initSender...
```
which is not from the beginning of the `real` worker-css.js:  

```js
"no use strict";
;(function(window) {
if (typeof window.window != "undefined" && window.document) {
    return;
}
```
