### ISSUE TITLE
Brace pairing behaviours don't always take affect

### ISSUE THREAD

**Issue by mnpenner** [ajaxorg/ace#1393]
Here are my settings:

``` javascript
var editor = ace.edit('editor');
var session = editor.getSession();
editor.setTheme('ace/theme/ambiance');
session.setMode('ace/mode/css');
session.setUseWrapMode(true);
editor.setShowPrintMargin(false);
editor.setBehavioursEnabled(true); // auto-pairing of special characters, like quotation marks, parenthesis, or brackets
editor.commands.addCommand({
    name: 'Start New Line',
    bindKey: {
        win: 'Shift+Enter',
        mac: 'Shift+Enter'
    },
    readOnly: false,
    exec: function(editor) {
        editor.navigateLineEnd();
        editor.insert('\n');
    }
});
```

In an empty editor, when I type `td {` it does _not_ add a closing `}`. If I add it manually, and then type `td {` for a second time it works as expected (adding the closing `}`).

It seems behaviours don't work for the first style tag in a CSS document, but after that it does.

Using `src-min-noconflict` from rev `1d8a5a3b39dde30c3f652c8c9f3f26a9b4016e70`.

**Comment by everdev** [comment]
I'm noticing this issue in Golang as well.   Although, the Behavior code appears to be in the JS file:
https://github.com/ajaxorg/ace-builds/blob/master/src/mode-golang.js#L200:L554

And `console.log(editor.getBehavioursEnabled());` is outputting `true`

I still don't get the auto-pairing functionality in the editor.  Everything else seems to work fine though.

I noticed the same behavior in the Kitchen Sink demo: http://ace.c9.io/kitchen-sink.html

Here are a few of the languages I tested:
* **Works:** JavaScript, Ruby, CSS, JSON, PHP
* **Doesn't Work:** Go, R, MySQL

**Comment by nightwing** [comment]
Looks like go mode includes [`CstyleBehaviour`] (https://github.com/ajaxorg/ace/blob/v1.1.8/lib/ace/mode/golang.js#L7) but doesn't use it.  
Actually are there languages that do not need pairing brackets? it might be better to move this into general behavior, and let modes disable pairing for bracket types they don't want.

**Comment by everdev** [comment]
I can't think of any languages that wouldn't benefit from it besides maybe HTML

**Comment by Epoch2** [comment]
Is there any way to force the `golang` mode to use `cstyleBehaviour`? As previously mentioned, it seems that it is [already included](https://github.com/ajaxorg/ace/blob/master/lib/ace/mode/golang.js#L7) but not used.

**Comment by thorst** [comment]
I was able to add this to tcl by looking at the javascript mode and looking at the tcl mode. You need to:

- http://jsbeautifier.org/ the minified cod

- copy  ace.define("ace/mode/behaviour/cstyle" section from javascript into your mode

- at the bottom ace.define("ace/mode/tcl" section 

modify:

-  tt = e("./behaviour/cstyle").CstyleBehaviour,

- and then in the function this.$behaviour = new tt;

**Comment by nightwing** [comment]
this have been fixed some time ago https://github.com/ajaxorg/ace/pull/2936
