### ISSUE TITLE
Issues list for Chinese input

### ISSUE THREAD

**Issue by haoder** [ajaxorg/ace#1401]
OS: Windows 8
Chinese IME:
NO1.  QQ Wubi IME, download link:http://dl_dir.qq.com/invc/qqwubi/QQWubi_Setup_2.0.313.400.exe
NO2.  Sogou Pinyin IME, download link: http://pinyin.sogou.com/softdown.php?v=6.6&type=c

Test case:
Input Chinese Pinyin ni'hao two times, the editor should display "你好你好"。

Result:
1. IE 10
   ![ime iussue1](https://f.cloud.github.com/assets/4288286/437784/8622c530-b0ae-11e2-9068-c4646607614f.JPG)
2. Chrome
   ![ime issue2](https://f.cloud.github.com/assets/4288286/437787/bb07fca2-b0ae-11e2-92f0-ad524b2e7250.JPG)
3. Firefox
   ![ime issue3](https://f.cloud.github.com/assets/4288286/437793/f32fc376-b0ae-11e2-9b77-32de2611d275.JPG)

**Comment by zyxue** [comment]
Was this bug fixed before? I am seeing it again on https://ace.c9.io/#nav=about. Chrome on OS X EI Capitan. It doesn't happen with Firefox.

**Comment by purejs** [comment]
I reproduced this issue on v1.2.3, and have the same question like above: Was this bug fixed before?

**Comment by iamwelk** [comment]
I have the same question
![image](https://cloud.githubusercontent.com/assets/6983075/19920052/60d8b74c-a111-11e6-8473-ace1207b196c.png)

chrome54
ace V1.2.5

**Comment by linsmalldragon** [comment]
same issue with chrome54 and mac os sierra with the newest version in https://ace.c9.io/#nav=about while typing Chinese.

**Comment by linsmalldragon** [comment]
@nightwing Could you help to see that ?

**Comment by iamwelk** [comment]
https://github.com/ajaxorg/ace/pull/3116
may be help

**Comment by lc-soft** [comment]
@nightwing  

Why I can't directly input text by IME ?
![editor-bug2](https://cloud.githubusercontent.com/assets/1730073/20131134/861022a4-a696-11e6-993a-0652a1a8859c.gif)

**Comment by chenkehxx** [comment]
it seem that there something wrong with latest version chrome. this [demo](https://ace.c9.io/#nav=about) works fine in safari, but it doesn't work in chrome.
