### ISSUE TITLE
Is the tmlanguage convertion tool supposed to work?

### ISSUE THREAD

**Issue by derekchiang** [ajaxorg/ace#1458]
I've used the tool to convert the [Elixir tmlanguage rules ](https://github.com/elixir-lang/elixir-tmbundle).  I've built Ace on my local machine and verified that the file `mode-elixir.js` has been created.  However, when testing, I still can't get any syntax-highlighting for Elixir.  I'm simply using the snippet found [here](http://ace.ajax.org/#nav=embedding), except that I've changed the code to use my local ace build and also set the mode to `ace/mode/elixir`.

Is that all I need to do to get Ace working with Elixir?  If so, what could possibly be wrong?

**Comment by igauravsehrawat** [comment]
I have tmLanguage file but the converter doesn't produce any `HighlightRules` i.e
```
var MyLangHighlightRules = function() {

    this.$rules = {
        start: []
    }
    
    this.normalizeRules();
};
```
It produces some HighlightRules.metaData and I keep getting `ace.js:5191 Uncaught TypeError: Cannot read property 'onMatch' of undefined ` on devtools.
I got into issue #3062 also.
It seems like I have to do the hard part of writing HighlightRules. Am I right? 

Thanks
