### ISSUE TITLE
Add Razor syntax support

### ISSUE THREAD

**Issue by Dreamwalker666** [ajaxorg/ace#1478]
I would expect 2 modes listed Razor (C#), Razor (VB.NET)

The rules from the C#/VB.NET and HTML mode could be reused or used here.  The new mode would just need to detect the switch between the modes.

**Comment by pmdevers** [comment]
Any news on this???

**Comment by rcollina** [comment]
I'd be interested in this as well. Thanks.

**Comment by pmdevers** [comment]
I have found https://github.com/ashmind/ace/tree/razor-wip-shelf as the branch name indicates it is a "work in progress". im trying to add completions and templates. but basic highlighting works

**Comment by pmdevers** [comment]
I have a pull request open see #2635

**Comment by brainwipe** [comment]
+1 for this. Razor in C# used here.

**Comment by iJungleboy** [comment]
+1 razor in c# / html

**Comment by iJungleboy** [comment]
I believe this was just added with the pull request https://github.com/ajaxorg/ace/pull/2635 - but I think it's not working yet. 

I have ace running (bound in angular with ui-ace) and set the mode to razor. 
BUT: it doesn't load mode-razor or anything. If I set mode "cshtml" it tries to load "mode-cshtml" and fails. 

I also tried the kitchen sink and can't tell a difference. I was expecting the `@` to show up differently - typically with a yellow highlight. This doesn't happen.

**Comment by iJungleboy** [comment]
Note to all: I figured out that Razor-detection does really work now :)!

BUT: the styling isn't in - at least it isn't in the themes I found. I'm currently using the theme sqlserver, and I added these styles to make it glow yellow:
```
<style>
     /* helper to ensure that razor (which is correctly detected by ACE) is also highlighted */
     .ace_razor {
         background-color: yellow;
     }

     /* make sure the highlighted text is also black, otherwise it a kind of gray */
    .ace_punctuation.ace_short.ace_razor {
        color: black;
    }
</style>
```

So by adding this to the CSS you should be good to go :). 

Note that the razor detection is great, but not 100% yet. For example, it detects

- @{ ...}
- @( ...)
- @value

but it only marks the @ and not the included character on these: 

- @* comment *@
- @:<invalid html without closing tag>

So: cool, but not quite done yet. thanks for everybody's work though, I love it.

**Comment by iJungleboy** [comment]
And here a print-screen with the above CSS added

![image](https://cloud.githubusercontent.com/assets/5321186/13055366/358cf406-d40f-11e5-80f1-f85d5472f916.png)
