### ISSUE TITLE
SmartCompletion support

### ISSUE THREAD

**Issue by blucas** [ajaxorg/ace#1514]
I've just tried out the autocompletion / snippet functionality and think it is a great addition thanks guys!

It got me thinking about what I call smart completion and if that is a possibility in ace.
What I mean by SmartCompletion is the ability for the autocomplete popup to show method/functions of a given object.

As an example.  Lets say we are using Java as the editor language.  Java has a class called `Math` and that class has methods defined such as `min` `max` `pow` `round`. So if I typed `Math.` and then pressed `ctrl + space` to open the autocomplete popup the autocompletion would load the list of defined methods for the `Math` class.

Do you think this is even possible?

Kotlin seems to have a semi-working demo of this functionality (http://kotlin-demo.jetbrains.com/)

In the main function type `Math.` and the press `ctrl + space` and it'll display a list of methods for the `Math` object.

**Comment by slidenerd** [comment]
How do you do auto complete without pressing control space like Android Studio?

**Comment by Displee** [comment]
Is this "SmartCompletion" implemented yet?
