### ISSUE TITLE
Cannot make ACE detect or use unix newlines

### ISSUE THREAD

**Issue by docwhat** [ajaxorg/ace#1515]
Hi!

I use GitLab and when using ACE to edit files in git, it keeps saving with windows-style newlines.

This makes the git history nearly useless as well as breaking things that don't know what do with the `\r` character (e.g. Augeas).  See gitlabhq/gitlabhq#3982 for the history.

I know it is ACE but I don't know _why_ it is happening.

I've tried (via the console in chrome) things like:
- `editor.session.setNewlineMode('unix')`
- `editor.session.getDocument().setNewlineMode('unix')`

... but it still sends it back to GitLab with `\r\n` as the line ending.

I've read through the API docs and googled a bunch but cannot find a solution to this problem.

Is this a bug in ACE or is gitlab misusing ACE?

Ciao!

**Comment by aalvarado** [comment]
for us we need to modify the content of the parameter that's going in.

```ruby
params[:file][:content].tr!("\r","")
```
and it solves any line ending issues.
