### ISSUE TITLE
Add Slim (template language) syntax highlighting support

### ISSUE THREAD

**Issue by wjbuys** [ajaxorg/ace#1516]
Please add syntax highlighting support for the [Slim template language](http://slim-lang.com/)

Existing implementations:
- Textmate: https://github.com/slim-template/ruby-slim.tmbundle
- Vim: https://github.com/slim-template/vim-slim/blob/master/syntax/slim.vim
- Emacs: https://github.com/slim-template/emacs-slim

**Comment by abitdodgy** [comment]
Is this at least being considered? It could be a deal breaker for us.

**Comment by AndrewHannigan** [comment]
Seconded, slim support is critical for me

**Comment by djudji** [comment]
Me too bros. Slim is way to go. Cheers for a development team.

**Comment by codem4ster** [comment]
Hey I need this support too. :(

**Comment by spilist** [comment]
Any news yet?

**Comment by tasssik** [comment]
Hey, cloud9. Any news?

**Comment by DrenBx** [comment]
Hey, Any news?

**Comment by taglia** [comment]
This would really help me too.

**Comment by DimitryDushkin** [comment]
+1

**Comment by DimitryDushkin** [comment]
lots of rails devs use slim btw

**Comment by cireficc** [comment]
Oh gosh, it's almost a 2-year-old issue... that makes me think that this will never get done... Slim is a popular templating language for Rails, it would be really nice to have correct syntax highlighting in c9. The syntax that works the best in the meantime is Jade (in my opinion), as they're pretty similar. It's not perfect, but doable for now.

**Comment by defaye** [comment]
+1

**Comment by taglia** [comment]
I ended up using vim in a maximized terminal window, mostly to improve the readability of my Slim files. Given that I use c9 in SSH mode, I start wondering if it's worth paying just to have my dev environment in the browser instead of directly in a terminal...

**Comment by gxbe** [comment]
+1

**Comment by the-varlog** [comment]
2.5 year-old issue. c9, plz

**Comment by harshal2802** [comment]
Please update c9

**Comment by ryskin** [comment]
+100

**Comment by jdrake-30** [comment]
+1

**Comment by rodcl** [comment]
+1

**Comment by dborovsky** [comment]
any news?

**Comment by AknEp** [comment]
+1

**Comment by neolite** [comment]
+++

**Comment by harapeko** [comment]
+1

**Comment by nbolt** [comment]
+1

**Comment by michaelfeihstel** [comment]
This is pretty much the only (though very significant) issue stopping me from using cloud9 full time.

**Comment by wflanagan** [comment]
+1

**Comment by polarbear2010** [comment]
It is 2017! Cloud9!

**Comment by nbolt** [comment]
it's just some syntax highlighting why is this taking years

**Comment by wflanagan** [comment]
It doesn’t seem to me that the Ruby ecosystem is a priority. Since the
acquisition, given AWS I’d doubt that they’d put any more emphasis on it.

I work in sublime, and then cut and paste.  Ridiculous, but workable
solution.

**Comment by Hubro** [comment]
Nearing 4 years and not even a comment from the c9 team? Yeah, there's no way I can use c9.
