### ISSUE TITLE
Multiple Cursor Selection Doesn't Work in Chrome OS

### ISSUE THREAD

**Issue by pizzapanther** [ajaxorg/ace#1581]
Both the mouse and keyboard commands don't work.  It may be impossible to get the Keyboard commands to work unless you change the keys because ctrl-alt and an arrow have special meaning in Chrome OS.  However, it would be nice for at least the mouse selection to work.

**Comment by johnkershaw** [comment]
In 2024 the chord search-ctrl-alt-up/down adds multicursors (for anyone coming here from the #1 google search result for 'chromebook multicursor ace editor not working').
