### ISSUE TITLE
Code in snippets doesn't work

### ISSUE THREAD

**Issue by ManUtopiK** [ajaxorg/ace#1606]
I enabled markdown mode and snippets tools.
In snippets/markdown.js there is snippet like :

```
snippet ===
    `repeat('=', strlen(getline(line(".") - 1)))`

    ${1}
```

If I wrote in the editor :

```
A title for exemple
===
```

and when I triggered snippet with tab key, I got :

```
A title for exemple
`repeat('=', strlen(getline(line(".") - 1)))`
```

I think it should be :

```
A title for exemple
===================
```

Code in snippets is implemented ? I saw the regex in SnippetManager > snippetVar but  it seems there is no line to triggered code's snippets. Also var Stack is not filled by code...

**Comment by generic-user** [comment]
The issue is still not fixed.
