### ISSUE TITLE
Uncaught TypeError: Cannot read property 'cssClass' of undefined 

### ISSUE THREAD

**Issue by s-a** [ajaxorg/ace#1611]
Hello ,
I get the js error `Uncaught TypeError: Cannot read property 'cssClass' of undefined`

Any idea what I am doing wrong here?

```javascript
			// Initialize your Ace Editor
			var editor =  function(id, mode, data) {
				var aceEditor = ace.edit(id);
				// default theme
			 	aceEditor.setTheme("theme/monokai");
				aceEditor.getSession().setMode("ace/mode/" + mode); 
				aceEditor.getSession().setValue(data);
				return aceEditor;
			};  

			$.get("/mvc/home.html", function(html) {
				editor("editor1", "html", html);
			});

			$.get("/assets/js/app_events.js", function(code) {
				var e =  editor("editor2", "javascript", code);
				
			});
```

It loads `theme/monokai.js` and the editor is working fine.

**Comment by patroy** [comment]
I am seeing the same error but just on Windows 7 Chrome

I have editor.setTheme("ace/theme/monokai");

**Comment by ZachSaucier** [comment]
^^ I'm seeing the same thing in Windows 10 Chrome. It loads the file just fine but doesn't apply it to the current page

**Comment by nightwing** [comment]
@ZachSaucier, @patroy if you give me a page demonstrating the error, i can check why it happens.

**Comment by ZachSaucier** [comment]
@nightwing (Here's a minimal demo](http://zachsaucier.com/ace-test/test.html) using the latest build from [the repo](https://github.com/ajaxorg/ace-builds/tree/e94cb3c7ffccfb2e565cc857f07a988c0989e527)

**Comment by nightwing** [comment]
@ZachSaucier in your demo you have `editor.setTheme("crimson")` instead of `editor.setTheme("ace/theme/crimson_editor");`

**Comment by ZachSaucier** [comment]
@nightwing Yes, that is because I changed the document structure so that `test.html` and the Ace files are on the same level (except the CSS snippet file). Is that not allowed?

**Comment by nightwing** [comment]
If you rename/move files around, you also need to change `define("ace/theme/crimson_editor"` in the file, so it's better to keep that as is.

**Comment by ZachSaucier** [comment]
Even when I change the document structure to match that of the repo and the JS to the following below, I'm still getting the same error. See for yourself at [the same test page](http://zachsaucier.com/ace-test/test.html)

```
var editor = ace.edit("css-editor");
editor.setTheme("ace/theme/crimson");
editor.getSession().setMode("ace/mode/css");
```

**Comment by nightwing** [comment]
the folder where you put built files doesn't matter, but changing filenames, or relative paths between theme does, the theme name is crimson_editor and the file name should be [theme-crimson_editor.js]( https://github.com/ajaxorg/ace-builds/blob/e94cb3c7ffccfb2e565cc857f07a988c0989e527/src/theme-crimson_editor.js). If you really want to change that you need to change `define("ace/theme/crimson_editor"` to `define("ace/theme/crimson"` as well.

**Comment by jazdw** [comment]
@nightwing There seems to have been a regression with the loader between 1.2.3 and 1.2.4, I'm using the src-min-noconflict builds and I get the same "Uncaught TypeError: Cannot read property 'cssClass' of undefined" error in 1.2.4 but not in 1.2.3.

I'm doing the following and can see the theme JS file being loaded but the loader is not getting the returned module for some reason, that's as far into it as I have looked.
editor.setTheme("ace/theme/chrome");
editor.getSession().setMode("ace/mode/html");

**Comment by nightwing** [comment]
@jazdw could you please create a demo showing the issue it doesn't happen in http://plnkr.co/edit/fGqwUnaVndzVavi5JCu3?p=preview

**Comment by kahanit** [comment]
I have the same issue, is this taken care of.

**Comment by nightwing** [comment]
@kahanit this was not a bug but a configuration error, see https://github.com/ajaxorg/ace/issues/1611#issuecomment-25826736 and https://github.com/ajaxorg/ace/issues/1611#issuecomment-236233890

**Comment by philrykoff** [comment]
I have copy and pasted the code from the website (also using noconflict build) and I am getting the same error, though it works in plunker.

The files are loaded as seen in Network tab properly, but syntax highlighting and theme are not applied, instead the console shows the mentioned error. 👿

**Comment by philrykoff** [comment]
Both `editor.setTheme('ace/theme/monokai');` as well as `editor.setTheme('ace/theme/chrome');` fail with the mentioned error (only locally, I did not get to reproduce this in plunker. I copied the version from the cdn to my local environment, just to make sure that there are no differences... didn't help.

For `editor.setTheme('ace/theme/textmate');`, no error shows up, yet the theme is not changed. Similarly, `editor.getSession().setMode('ace/mode/javascript');` does not change syntax highlighting or folding.

@kahanit Is it the same for you?

**Comment by nightwing** [comment]
@philrykoff sounds like you didn't copy some of the files, like mode-monokai.js

**Comment by jazdw** [comment]
@nightwing

Re-read my comment, it's nothing to do with missing files.

**Comment by philrykoff** [comment]
Here is proof ;-) The files are loaded nicely.

http://imgur.com/a/UTBzJ

I am using Ember CLI, which registers a very slim AMD loader (requirejs, require, define globals), which cannot be used to load additional JS files, only precompiled ones. That's why I have another instance of Require JS registered into my own namespace (Elements.requireJs, Elements.define, ...) - but it is my understanding ACE noconflict build uses it's very own AMD loader so that cannot be the reason, or? Reproducing it on plunker would take some hours :-| @jazdw Do you have a similar weird setup?

**Comment by jazdw** [comment]
I'm just using require JS, hardly an exotic setup

**Comment by philrykoff** [comment]
It seems textmate is set as $options.theme.initialValue, so that observation does not help us.

**Comment by philrykoff** [comment]
This seems like a possible root cause (at least for my setup):

https://github.com/ajaxorg/ace-builds/blob/e94cb3c7ffccfb2e565cc857f07a988c0989e527/src-noconflict/ace.js#L3706

Here, the function globally registered to "require" is being called instead of the ace-internal mini-require. This causes the module variable to be undefined (as the Ember JS loader mentioned before does not know that module, which was rightfully loaded by the ACE loader before), which in turn causes the exception.

**Comment by philrykoff** [comment]
Maybe it's too late here, but it seems that ace.define is being overwritten by either Require JS or the Ember CLI loader, depending on wether I load ace.js with Require JS or with a plain old <script ...> tag, thus not registering with the ace loader, resulting in the exception. Will continue investigation...

**Comment by philrykoff** [comment]
I did not find out why ace.define get's overriden either way I include ace.js, but this is my work around:
- Save the define function into another global variable in the loader module within ace.js (right after `exportAce(ACE_NAMESPACE);`)
- Resetting ace.define to that global variable after calling `ace.edit`
- PROFIT! 🎉

**Comment by nightwing** [comment]
There indeed was a regression between 1.2.3 and 1.2.4, and i missed it because didn't think to check no-conflict + global require combination.
The attached commit will fix the issue, thanks for the help!
