### ISSUE TITLE
jsDoc comment closing not working as expected

### ISSUE THREAD

**Issue by pstjvn** [ajaxorg/ace#1615]
To close the comment  one needs `*/` . When editor is in block comment pressing enter creates a new row with \* and space after it. Pressing `/` should delete the extra space and put the slash right behind the `*`. Right now one have to manually delete the extra space. Would be great if this worked as it would save a lot of time for code that requires very detailed comments.

**Comment by mitchellsimoens** [comment]
What I would like to see is when you type `/**` and press enter, it then adds that additional line but also automatically closes the block comment.

**Comment by mkslanc** [comment]
Fixed by #5109
