### ISSUE TITLE
Error when precompiling Ace

### ISSUE THREAD

**Issue by arikrak** [ajaxorg/ace#1665]
Ace editor works fine, but when I try to precompile the javascript files in Rails it throws an error. This happened with all 4 Ace builds. I'm not sure if there's a bug in Ace, but I don't get an error from other javascript files. This is the error message:

```
Unexpected token: punc (() (line: 1, col: 113042, pos: 113042)

Error
    at new JS_Parse_Error 

 at js_error...   at croak...  at token_error... at unexpected... at as_name... at as_property_nam...  at object_... at maybe_unary...  
 (in pathToApp/javascripts/ace-src/worker-javascript.js).../execjs-1.4.0/lib/execjs/external_runtime.rb:68:in `extract_result'
```

So something in [worker-javascript](https://github.com/ajaxorg/ace-builds/blob/master/src-noconflict/worker-javascript.js) seems to be causing an issue.

**Comment by nightwing** [comment]
there is no way to not load worker dynamically since it needs to be loaded into a web worker.
