### ISSUE TITLE
Adding '.' character to prefix matching for completers   Ref- 'ace/autocomplete/util'

### ISSUE THREAD

**Issue by mccainz** [ajaxorg/ace#1670]
For consideration,

The module, 'ace/autocomplete/util', in file ext-language_Tools.js, defines a regEx that is used to determine prefix matches for defined completers.

var ID_REGEX = /[a-zA-Z_0-9\$-]/;
used in , exports.retrievePrecedingIdentifier

As we defined a custom completer to support our object structures (Person.Name.First etc...) this caused a problem in that ID_REGEX will not match on the dot character. This can be overridden in our custom completer but it causes the completers defined in ace/ext/language_tools to pollute our matches with the entire scope of the document.

The modification seems trivial ...
var ID_REGEX = /[a-zA-Z_0-9\$-\.]/;

**Comment by antonpod** [comment]
@nightwing it works (using the first item in the results array to pass the regex)

**Comment by rsmith31415** [comment]
@antonpod Can you describe what you did to make it work? I opened [this](https://github.com/ajaxorg/ace/issues/2532) issue a couple of months ago.

**Comment by antonpod** [comment]
@rsmith31415 in my case I didn't need to know the prefix **before** sending the Ajax request. I just needed to adjust the regex for correct matching after the keywords were fetched.

**Comment by rsmith31415** [comment]
@antonpod Thank you for your response. Maybe @nightwing can share an update on the support for this feature.

**Comment by GNSubrahmanyam** [comment]
@nightwing any updates on this?

**Comment by andrewnester** [comment]
Now as a solution for this issue custom `identifierRegexps` can be provided by authors of custom code completers 
https://ajaxorg.github.io/ace-api-docs/interfaces/Ace.Completer.html#identifierRegexps
