### ISSUE TITLE
R mode should respect dollars not dots

### ISSUE THREAD

**Issue by rubenarslan** [ajaxorg/ace#1695]
Alt + Arrow key left/right on Mac should bring me to the next word boundary. It's extremely useful, but unfortunately the behaviour is broken in Ace. I think it's due to a mis-specified mode, but I may be wrong. Textmate 2 does it correctly.

It _should_ take me to word boundaries so when my cursor is at the point marked with |:
|rpqa.unions$mdate pressing alt->right should lead to rpqa.unions|$mdate , but _instead_ it leads to
rpqa.|unions$mdate.

Similary when I'm at rpqa.unions$mdate| and I press alt-backspace, I of course _want_ to delete the variable name, _instead_ I get rpqa|

Also confer the [issue at Rstudio](http://support.rstudio.org/help/discussions/problems/9607-alt-delete-arrow-key-behaviour-broken-on-mac) that I opened regarding this.

**Comment by ilario** [comment]
Another [bug](https://support.rstudio.com/hc/en-us/community/posts/200634308/comments/201270893) spotted using RStudio and related to this one:
variable highlighting does not work when selecting a variable with a period in the name.
