### ISSUE TITLE
Add SQF Scripting Language (ArmA 3)

### ISSUE THREAD

**Issue by docrinehart** [ajaxorg/ace#1718]
Just a simple request to add SQF to the available languages. The official documentation for the API is at:
http://community.bistudio.com/wiki/Category:Scripting_Commands_Arma_3

And a decent plugin for Notepad++ that adds SQF support can be found at:
http://www.armaholic.com/page.php?id=8680

It'd be nice to utilize a tool such as Cloud 9  that allows collaborative editing for some of the larger projects rather than relying on Dropbox, Drive, or SVN. Real-time would rock.

Regards,
~Sean R.

**Comment by DardoTheMaster** [comment]
+1
