### ISSUE TITLE
Arrow key jump tabsize spaces.

### ISSUE THREAD

**Issue by sunglim** [ajaxorg/ace#1721]
Hi. 

I pressed space 4 times,  and press left arrow key.

I expect only cursor goes 1 space back. but cursor goes 4 space back.

Is this expected? even I set Softtab as true, the result is same.

**Comment by masad-frost** [comment]
+1 on not changing behavior of the Arrow Keys like Sublime. 

One of the main reasons I prefer soft-tabs is that I can go move one space with arrow key. Navigating through tabs/white-spaces should be done through token-left and token-right (i.e. ctrl-left, ctrl-right).
