### ISSUE TITLE
Allow no semicolons in JavaScript

### ISSUE THREAD

**Issue by xfix** [ajaxorg/ace#1754]
I really like code without semicolons. Ace is great, but the error reporting for JavaScript complains about my perfectly fine code without semicolons. Would it be possible to disable warnings about semicolons. All I'm interested in are real syntax errors, without style errors.

Sample code (JavaScript):

``` javascript
alert("Hello, world!")
```

**Comment by tiaod** [comment]
Any update of this?

**Comment by flawiddsouza** [comment]
This worked for me
```js
editor.session.on('changeMode', function(e, session) {
    if('ace/mode/javascript' === session.getMode().$id) {
        if(!!session.$worker) {
            session.$worker.send('changeOptions', [{
                asi: true // disable "Missing semicolon." warning in editor for JavaScript
            }])
        }
    }
})
```
Doing this didn't:
```js
editor.session.$worker.send("changeOptions", [{asi: true}]);
```
as `.$worker` was `null`

**Comment by andrewnester** [comment]
This is the default behaviour of JS linter we use, as indicated above it's possible to pass custom linting options to change that behaviour
