### ISSUE TITLE
Duplicated characters when using accent menu in OSX

### ISSUE THREAD

**Issue by benweet** [ajaxorg/ace#1756]
As stated in https://github.com/benweet/stackedit/issues/261, when long press keyboard character and select an accent, the character is inserted twice.

As reported by @rbondi, in Chrome:

> the menu appears in the top left corner of the document instead of where the cursor is, and when you type an integer, you don't get the optional character, just a "c".

**Comment by nightwing** [comment]
This should be fixed by https://github.com/ajaxorg/ace/pull/3635, please let us know if you still can reproduce this on http://ace.c9.io. Thanks.
