### ISSUE TITLE
Can optimize Chinese, East Asian language input experience?

### ISSUE THREAD

**Issue by Houfeng** [ajaxorg/ace#1797]
Hello
When the input Chinese, textarea display is very ugly. When change some elements of the padding, the input window has the dislocation problem. Be like codemirror? Can optimize Chinese, East Asian language input experience?
Thanks a million.

**Comment by naivefun** [comment]
any updates here?

**Comment by nightwing** [comment]
https://github.com/ajaxorg/ace/pull/3635 fixes the issue with textinput, the issue with varying width fonts is separate.
