### ISSUE TITLE
Selection text incorrect for RTL langauges

### ISSUE THREAD

**Issue by syakhmi** [ajaxorg/ace#182]
Ace does not work correctly with RTL languages. For example, when viewing a file with Arabic/Persian/Urdu text, if you select a chunk of the text containing RTL text, and copy the selection to the clipboard or make a call to the copyText() function, the wrong text will be copied or returned. For example, if you select the first three RTL characters between <p></p> tags and copy them, instead the last three will be copied.
@gissues:{"order":84.47204968944106,"status":"backlog"}

**Comment by TarepSH** [comment]
we still wating for RTL support.

**Comment by nightwing** [comment]
implemented in https://github.com/ajaxorg/ace/pull/3137
