### ISSUE TITLE
support for .litcoffee files

### ISSUE THREAD

**Issue by bodhiBit** [ajaxorg/ace#1821]
I very much like that Ace supports syntax highlighting and linting for coffeescript files, but would it be possible to add support for [Literate CoffeeScript](http://coffeescript.org/#literate) files as well..? :)

**Comment by fyoualix** [comment]
Wanna say some thing am hier to have fun talk making  frinds meteening new peopel  not  for mony is my frirt day day om this site you kan add me on twitter if i dint  answr am doing best
