### ISSUE TITLE
set keybinding via setOption

### ISSUE THREAD

**Issue by varemenos** [ajaxorg/ace#1872]
I've tried but I couldn't find how to set keyBinding via editor.setOption. If it's implemented yet, could you add it?

I tried the following:
```js
editor.setOption('keyBinding', 'vim');
editor.setOption('keybinding', 'vim');
editor.setOption('keyboard', 'vim');
editor.setOption('keyboardHandler', 'vim');
```

**Comment by nightwing** [comment]
Good point. Added keyboardHandler option in https://github.com/ajaxorg/ace/commit/d1809d83aa01b8d0657021bd10fc6081f1d3a0a0
can be used as `editor.setOption("keyboardHandler", "ace/keyboard/vim");`
