### ISSUE TITLE
editor.getSession().setValue(data);  Cursor goes to position 1

### ISSUE THREAD

**Issue by poulakidask** [ajaxorg/ace#1886]
when I set new data to the editor with the command editor.getSession().setValue(data); 

the cursor goes to position 1.. How do I make it to remain in the current position or move accordingly eg.. if I added 1 char the cursor should move one position to the right.

**Comment by AILINGANGEL** [comment]
How to solve this issue?

**Comment by effectivecui** [comment]
I got answer:
```
const cursor = this._editor.getCursorPosition();
this._editor.session.setValue(value);
this._editor.moveCursorTo(cursor.row, cursor.column);
```
