### ISSUE TITLE
Backspace/Delete keys are unreliable on Chrome for Android

### ISSUE THREAD

**Issue by wizzard0** [ajaxorg/ace#1917]
On numerous occasions, user is required to hit Backspace 3-4 times before text actually starts being erased.
Delete key works like Backspace.

Issue manifests itself more often when Auto-Capitalization is enabled.

I'm happy to provide additional details (e.g. log files)

Tested on Xperia Go, Xperia Z1 with latest stable Chrome.

**Comment by Miha-x64** [comment]
How much time has passed…
When one presses backspace 2-3 times, shift is being pressed.
Ace 1.2.3.
Nexus 7, Android 5, Firefox Beta 46 and Firefox 47, Cyanogen Mod 12, standard AOSP keyboard.
HTC Evo 3D, Android 4.4, Firefox Beta 45, Cyanogen Mod 11
In Built-in browser all works correctly.
Considering that I cannot select code with long tap or in another way and delete it, this makes Ace almost unusable from some Android devices.

I've been facing quite similar issue in a native app: Android keyboard may not send backspace event if there is nothing to erase, so if you are using dummy input field to capture events, ensure it has at least one character before the cursor.
[tl;dr about Android IME](http://stackoverflow.com/questions/18581636/android-cannot-capture-backspace-delete-press-in-soft-keyboard)

**Comment by nightwing** [comment]
This should be fixed by https://github.com/ajaxorg/ace/pull/3635, please let us know if you still can reproduce this on http://ace.c9.io. Thanks.
