### ISSUE TITLE
ChromeOS hijacks keys

### ISSUE THREAD

**Issue by broomdodger** [ajaxorg/ace#1953]
acer c720 chromebook

Ace defines:
Ctrl-Shift-U -- tolowercase

**BUT** on ChromeOS that shortcut will initiate unicode entry.
Can Ace get that shortcut before ChromeOS?
Or can the shortcut be changed?

Also this can be inconvenient if accidentally typed.
Ctrl-Shift-L -- lock screen
Can this shortcut be disabled in Ace?

**Comment by felicienfrancois** [comment]
That's also the case on Ubuntu #2448 and maybe also other linux distro
