### ISSUE TITLE
chrome apps forbid use of `prompt()`

### ISSUE THREAD

**Issue by broomdodger** [ajaxorg/ace#1958]
chrome apps forbid use of `prompt()`

Is there another way this can be implemented so as to work in chrome apps?

`Ctrl-L -- gotoline`

Reference:
https://github.com/ajaxorg/ace/blob/master/lib/ace/commands/default_commands.js

```
{
  name: "gotoline",
  bindKey: bindKey("Ctrl-L", "Command-L"),
  exec: function(editor) {
    var line = parseInt(prompt("Enter line number:"), 10);
    if (!isNaN(line)) {
      editor.gotoLine(line);
    }
  },
  readOnly: true
},
```

**Comment by felicienfrancois** [comment]
Now there are also emmet extension and vim key bindings that uses native prompt.

Maybe a first step would be to define an async prompt method globally:
```
ace.prompt = function(title, default, callback) {
  callback(prompt(title, default));
}
```

and makes it used by all current uses of the sync prompt:
```
{
  name: "gotoline",
  bindKey: bindKey("Ctrl-L", "Command-L"),
  exec: function(editor) {
    prompt("Enter line number:", function(value) {
      var line = parseInt(value, 10);
      if (!isNaN(line)) {
        editor.gotoLine(line);
      }
    }
  },
  readOnly: true
},
```

This is a simple step and this way we would be able to override ace.prompt with any dialog lib.

I can do a PR but I don't know where I should put the definition of `ace.prompt`.
