### ISSUE TITLE
Ace for East Asian language input experience has not been friendly

### ISSUE THREAD

**Issue by Houfeng** [ajaxorg/ace#1961]
Ace for East Asian language input experience has not been friendly, some of the input method window always position is not accurate, whether we can draw on the implementation way of CodeMirro?

ace 对于东亚语言的输入体验一直都不友好，有些输入法的窗口总是位置不准确，是否可以借鉴一下 CodeMirro 的实现方式？

**Comment by nightwing** [comment]
With https://github.com/ajaxorg/ace/pull/3635, setting useTextareaForIME option to false will produce behavior similar to CodeMirror, and bug with that option set to true should be fixed too.
