### ISSUE TITLE
Long lines display glitch

### ISSUE THREAD

**Issue by ghost** [ajaxorg/ace#1974]
[![s1](http://static.md/e0fcb3d60aedc0baf8aa22d995897bca.png)](http://static.md/e0fcb3d60aedc0baf8aa22d995897bca.png)

And after a long scroll to the right, they begin to appear

[![s2](http://static.md/7d04d1020a2bea30592d3aea12d60f14.png)](http://static.md/7d04d1020a2bea30592d3aea12d60f14.png)

[Example](http://plink.link/91de0351bc0edaf19029c36cb788a976/html) from images

Also the bug appears on [demo](http://ace.c9.io/build/kitchen-sink.html) using the text from [example](http://plink.link/91de0351bc0edaf19029c36cb788a976/html)

_Browser: Chrome 34.0.1847.137 | OS: Ubuntu 14.04_

**Comment by ayende** [comment]
Any updates on this?
