### ISSUE TITLE
Wrong cursor position after scrolling and losing focus in autoresized editor

### ISSUE THREAD

**Issue by TouchyPunchy** [ajaxorg/ace#1983]
I have a problem with cursor positioning after scrolling and losing focus with an "autoresized" editor, in all major browsers (latest IE, chrome, firefox and opera 12.17).
- Load the "autoresize" example : https://github.com/ajaxorg/ace/blob/master/demo/autoresize.html
- In the third editor, add enough lines of text to obtain an editor bigger than your screen (for example 100 lines)
- Click on the first line of the text
- Scroll down to the bottom 
- Click outside the editor (on the background) 
- Click somewhere on line 50

**(Bad) Result :**
The text will be highlighted from line 50 to the line 25 (or 18 or another random line...) and the cursor will be on line 25 (...) instead of on line 50.

Is there a way to fix this (without removing the autoresizing) ?

**Comment by BramVanroy** [comment]
Hm, the link provided to focus is dead. Has `focus` been moved?

**Comment by nightwing** [comment]
It was merged and the old branch is deleted, you can use master now
