### ISSUE TITLE
is there a support for Jinja2 template?

### ISSUE THREAD

**Issue by newtechfellas** [ajaxorg/ace#1992]
Is this support available? or any plans of supporting jinja2 templates syntax?

**Comment by paulbijancoch** [comment]
> Assuming django mode worked. If it didn't please tell!, we can convert textmate syntax [definition](https://github.com/mitsuhiko/jinja2-tmbundle/blob/master/Syntaxes/Jinja%20Templates.tmLanguage)

@nightwing are you still able to generate the Moses? It would be totally awesome to have a ace mode for https://github.com/ronnidc/vscode-nunjucks/blob/master/syntaxes/nunjucks.tmLanguage!
