### ISSUE TITLE
Word left / right inconsistent

### ISSUE THREAD

**Issue by Kos** [ajaxorg/ace#1999]
Since a few versions of Ace, the "go to word left" and "go to word right" keyboard commands (`ctrl+left` and `ctrl+right`) work inconsistently with any other editor I've tried.

I'm used to `ctrl+left` meaning "go back to nearest word beginning" and `ctrl+right` meaning "go forward to nearest word ending". In Ace, however, both word left and word right stop at both word starts and word ends, which instantly makes my muscle memory super-confused (and my users likewise). You need twice as many keypresses to reach a given place.

Is this change intentional as the new default behaviour? Is it a bug? Is it configurable?

**Comment by simonzack** [comment]
I'm having the same problem.

`$.editorSession.$selectLongWords = true;` behaves correctly when moving left, but doesn't behave the same way when moving right compared to most editors. Moving right after `|abc def` should become `abc |def`, but in ace the cursor is set at  `abc| def`. Is there another option for this behavior?

**Comment by nightwing** [comment]
There is no other option yet. The behavior of $selectLongWords = true is same as sublimes behavior.
But since different editors have different moveByWord behavior and not getting the one you expect is quite frustrating, i agree that adding options for other behaviors is good.

**Comment by jimbo1qaz** [comment]
Is this workaround still relevant to current versions of Ace Editor? How do I enable that mode in random websites (where I don't host the code)?
