### ISSUE TITLE
In chrome for Android, the shift key acts like backspace

### ISSUE THREAD

**Issue by voidc** [ajaxorg/ace#2038]
If you press the shift key in chrome for Android while using the ace editor, it will delete the last character just like pressing backspace.

**Comment by faloi** [comment]
This is still an issue, happens to me on a Nexus 7 tablet running Android 6.0.1 and the default keyboard.

**Comment by flbulgarelli** [comment]
Hi! Same poblem here. You can reproduce by entering http://alloyui.com/examples/ace-editor/real-world/, on Chrome, Android 4.4 Moto E.

**Comment by vanillajonathan** [comment]
@nightwing this happens with the default keyboard which is the [Google Keyboard](https://play.google.com/store/apps/details?id=com.google.android.inputmethod.latin) (Latin).

It happens both in Chrome and WebView.

**Comment by rodri042** [comment]
Using SwiftKey - Android 4.4 - Chrome, I have the same problem.

**Comment by gobstones-admin** [comment]
I have experimented the problem in Android 6.0.1.
Will there be a solution soon?

**Comment by vanillajonathan** [comment]
Using Google Keyboard 5.1 this has gotten worse and now actually erases text when typing using swipe gestures.

**Comment by adamjimenez** [comment]
I have the same issue. Also pressing enter seems to backspace before creating a new line.

**Comment by nightwing** [comment]
This should be fixed by https://github.com/ajaxorg/ace/pull/3635, please let us know if you still can reproduce this on http://ace.c9.io. Thanks.

**Comment by vanillajonathan** [comment]
This seems to be fixed.
