### ISSUE TITLE
getUndoManager() doesn't return a proper UndoManager object

### ISSUE THREAD

**Issue by brannondorsey** [ajaxorg/ace#2045]
It appears as if using `editor.getSession().getUndoManager()` with a session that has been set with `editor.setSession()` returns an `UndoManager` object that contains only empty functions for `undo()`, `redo()`, and `reset()`. It does not return an UndoManager with methods like `hasUndo()`, or `hasRedo()`, or any of the other [documented methods](http://ace.c9.io/#nav=api&api=undomanager). In the source, it looks like my the session must not have an `$undoManager` and is forced to use an empty (and incomplete) `$defaultUndoManager`: 

``` javascript
   this.$defaultUndoManager = {
        undo: function() {},
        redo: function() {},
        reset: function() {}
    };

    this.getUndoManager = function() {
        return this.$undoManager || this.$defaultUndoManager;
    };
```

Why would a session that was set with editor.setSession() have an `$undoManager` that is `undefined` like that?

**Comment by matthew-dean** [comment]
Ohh this must be why I have no undo / redo. Btw, this is what I've always referenced for embedding. It says nothing of the mythical createEditSession: https://github.com/ajaxorg/ace/wiki/Embedding-API

**Comment by matthew-dean** [comment]
I'd like to add: considering this functionality is present in pretty much any environment, I can't imagine a scenario in which someone would not need undo/redo. Why not just create / attach an undo manager by default when creating an edit session, unless someone opts out?
