### ISSUE TITLE
Nginx mode

### ISSUE THREAD

**Issue by rvgate** [ajaxorg/ace#2049]
Would be great to have Nginx config support. Apache was already there and Nginx is gaining popularity.

The tricky part would be supporting all the different different directives from all the modules, but starting with the Nginx Core and Standard HTTP modules would be amazing. http://wiki.nginx.org/Modules (maybe even generate the mode from these pages)

VIM supports Nginx config highlighting already and the .vim file could be used as a great example: http://www.vim.org/scripts/script.php?script_id=1886 (idea for .vim to mode converter?)

**Comment by fwartner** [comment]
:+1:

**Comment by rvgate** [comment]
@nightwing I just noticed this is labeled as a mode-issue and not a mode-request... Is Nginx already supported?

**Comment by fwartner** [comment]
@rvgate No.. It isn´t supported yet.. :/
