### ISSUE TITLE
Ready event

### ISSUE THREAD

**Issue by ShootingStarr** [ajaxorg/ace#2082]
Hey guys, ace editor have event when it ready?

**Comment by emkamal** [comment]
I want to execute my script after everything is initially setup by ace, is there any way I could do that? Maybe something like a callback function on ace.edit?

**Comment by kgrosvenor** [comment]
Yeah i have a similar issue, i want to set the value of ace and then resize it since content seems to miscalculate, if i have a timeout of 50ms or more it executes in the correct order, it seems things need to initialise before i can set the value

**Comment by sd-godaddy** [comment]
Apparently there is undocumented method: https://stackoverflow.com/a/37796568/5560682
But when I checked how does it work I found it's fired many times per editor, so I used debounce and it's good enough for my needs.
(Btw it's really sad that no one have thought to provide onLoad event in such powerful editor, sometimes I really can't understand people)

```js
function debounce(fn, delay) {
  var timer = null;
  return function () {
    var context = this,
      args = arguments;
    clearTimeout(timer);
    timer = setTimeout(function () {
      fn.apply(context, args);
    }, delay);
  };
}

const editor = ace.edit(div);

const event = debounce(() => {
  console.log('ready');
}, 50);

editor.renderer.on("afterRender", event);

```
