### ISSUE TITLE
How to: completely remove editor from DOM and JS

### ISSUE THREAD

**Issue by belyanskii** [ajaxorg/ace#2085]
Hi guys!
I search for some good practices to completely remove editor from page. I need to create many instances of editor and delete them, but delete only DOM node is wrong, because i still have event-listeners and JS instances of editors. I try to use destroy method `ace.editor('id').destroy()`, but they leave DOM node and i don't understand what they do, because my editor still works.

**Comment by ldong** [comment]
What I did was,
1. using editor to destroy itself to avoid memory leak
2. using jQuery to get the ace editor and remove form the DOM

```
editor.destroy();

$editor = $('ACE_ID');
$editor.remove();
```
