### ISSUE TITLE
Keyboard shortcuts: ctrl+T, ctrl+L, ctrl+R stolen by editor

### ISSUE THREAD

**Issue by bvibber** [ajaxorg/ace#210]
When setting up keyboard shortcuts in a web app, there's always a delicate balance between providing features and interfering with the hosting browser's own keyboard shortcuts.

In a couple days of usage embedding Ace into MediaWiki, I've found that the most problematic key conflicts for me are:

ctrl+T -- normally does 'new tab'; in Ace this appears to swap two adjacent characters. Not a feature I'd expect to want, and it impedes ability to pop off to a new tab to look up documentation etc.

ctrl+R -- normally 'reload page': starts a text search in Ace. (I expected ctrl+F for that? ah... ctrl+R starts 'Find/Replace' but doesn't mention the replacement until you've gone through the first dialog :)

ctrl+L -- normally 'go to location', popping into the URL bar so you can type a new URL to go to. Opens 'go to line' dialog in Ace.

@gissues:{"order":79.5031055900622,"status":"backlog"}

**Comment by LianaHus** [comment]
editor.commands.bindKeys({
      'Ctrl-T': null,
      'Command-T', null
      'ctrl-L': null,
      'Command-L': null
    })
 will remove mapping
