### ISSUE TITLE
Externalize texts to allow translations

### ISSUE THREAD

**Issue by kylekatarnls** [ajaxorg/ace#2118]
There some texts in English displayed to the user:
"Enter line number" https://github.com/ajaxorg/ace/blob/97d39e2912929e16d5b405e04dd65328004ecbb1/lib/ace/commands/default_commands.js
Search / Replace / All

I will need to translate it in French. If there are other people interested, I will propose a pull request to allow translation in any language.

**Comment by Ugoku** [comment]
I would be interested in this as well, and would gladly translate Ace into Dutch.

**Comment by AStoker** [comment]
Is there any localization/internationalization available with Ace? We're in the process of localizing out product now, and would love to be able to have a code editor that can respond to different languages (spoken languages, not code languages 😉 ).

**Comment by akoreman** [comment]
Support for translating user-facing texts was added in PR #5153 and will be included in the next Ace release.

**Comment by akoreman** [comment]
[Ace 1.20.0](https://github.com/ajaxorg/ace/releases/tag/v1.20.0) has been released which includes this change.
