### ISSUE TITLE
Middle click pastes '\x01' character in Chrome Linux

### ISSUE THREAD

**Issue by pwmarcz** [ajaxorg/ace#2124]
To reproduce:
Press right mouse button, close context menu, and press middle button; This pastes invalid ASCII 01 character, represented as a red dot.

Reproduced in Chrome 36 under Linux, at http://ace.c9.io/.

**Comment by clickstefan** [comment]
This is still affecting Ace, including c9
I'm using Ubuntu & Chrome

**Comment by enricoberti** [comment]
I have the same problem, I found a "hacky" workaround though that works for the time being :smile: 

in our specific code (but I'm sure you will find a proper place for it)
```javascript
editor.middleClick = false;
    editor.on("mousedown", function (e) {
      if (e.domEvent.which == 2) { // middle click
        editor.middleClick = true;
        var tempText = editor.getSelectedText();
        if (e.$pos) {
          editor.session.insert(e.$pos, tempText);
        }
        window.setTimeout(function () {
          editor.middleClick = false;
          if (e.$pos) {
            editor.moveCursorTo(e.$pos.row, e.$pos.column + tempText.length);
          }
        }, 200);
      }
    });
```
and here
https://github.com/ajaxorg/ace/blob/master/lib/ace/keyboard/textinput.js#L266

```javascript
var handleClipboardData = function(e, data) {
        if (typeof host.middleClick != "undefined" && host.middleClick){
          return host.getSelectedText() || " ";
        }
       ....
```
I know it's not the best but it works ;)
