### ISSUE TITLE
Swift Language support

### ISSUE THREAD

**Issue by skipallmighty** [ajaxorg/ace#2152]
Is anyone working on highlighting for the Swift language and if they are not can I contribute?

**Comment by mAAdhaTTah** [comment]
:+1:

**Comment by aldendaniels** [comment]
:+1:

**Comment by nightwing** [comment]
I've added a simple swift mode in https://github.com/ajaxorg/ace/pull/2585, it probably needs some reworking since i am not very familiar with swift. Any bug reports and suggestions for improvement are welcome.

**Comment by aldendaniels** [comment]
@nightwing - Very cool. Thank you!

**Comment by jarrodparkes** [comment]
Have there been any updates on this? Would love to see support for Swift :+1: !

**Comment by jarrodparkes** [comment]
It appears that Swift has been added, but it is not included in the kitchen-sink demo.
