### ISSUE TITLE
Add Laravel Blade syntax highlighting

### ISSUE THREAD

**Issue by neon64** [ajaxorg/ace#2194]
It would be great to at a new mode for Laravel's Blade templating engine. It would be quite trivial to implement (I imagine), as it is merely just PHP with extra `@` tags (eg: `@if` and `@lang`) as well as `{{` and `}}`.

You can look at Blade's syntax at the Laravel docs here: http://laravel.com/docs/4.2/templates#blade-templating

Thanks very much if this would be possible.

**Comment by mizukagetobi** [comment]
Please Do IT!

**Comment by ArtemProkopenko** [comment]
+

**Comment by BlueAnchorite** [comment]
+1

**Comment by larve** [comment]
+1 :D

**Comment by stasoft91** [comment]
Still +1

**Comment by SlyDeath** [comment]
+1
