### ISSUE TITLE
Live Autocomplete Delay

### ISSUE THREAD

**Issue by jaredbroad** [ajaxorg/ace#2209]
Hello,

It would be nice to have a liveAutocompletionDelay option to make the popup appear after 100ms of not typing. When you're typing quickly it flashes open and closed which can give you a head ache after a while.

Thanks
Jared

**Comment by ThorbenQuast** [comment]
Hello,

fyi, I just encountered the very same problem and the following code added to the source code works perfectly for me: 

https://github.com/ajaxorg/ace/pull/2414/files

Cheers,
Thorben

**Comment by jaredbroad** [comment]
Thanks Thorben!
