### ISSUE TITLE
feature request for option to replace tokens with another symbol

### ISSUE THREAD

**Issue by operand** [ajaxorg/ace#2233]
In Codemirror, they have a method called markText() described here: http://codemirror.net/doc/manual.html#api_marker

One of the options for that method allows you to collapse the marked text and replace it with something else. So, for example I can find all instances of "foo" and replace them with say, an underscore, but the internal value for the text remains "foo". And when a user deletes the underscore, the entire token "foo" is deleted, under the hood.

I've played around with code folding, and roughly achieved what I want, but it's a bit of a kludge. I also tried replacing values in 'editor.session.bgTokenizer.lines' whenever the document changes, but that doesn't seem to work very well, despite my efforts. Maybe you guys know of a "right" way to do this?

For reference I had also asked about this on StackOverflow here: http://stackoverflow.com/questions/26812580/any-way-to-collapse-marked-text-in-ace-editor

**Comment by yellow1912** [comment]
Is there any update to this issue? It has been 2 years and now we run into the same requirement :)
