### ISSUE TITLE
Python syntax not fully implemented.

### ISSUE THREAD

**Issue by c19** [ajaxorg/ace#2251]
First i notice themes didn't highlight python's function name and function params like it would in other editor say sublime.

then i read through `python_highlight_rules.js` and compared `javascript_highlight_rules.js`
realized that python syntax isn't fully implemented.

**And are other languages' parser written manually ?** JS seems to be. and i tried the `tmLanguage.js` convert sublimes' `Python.tmLanguage`. and all regexp contain `(?<=)` eg positive lookbehind fails for JS doesn't support lookbehind.

**Comment by PangeaCake** [comment]
It would be nice to have this (and maybe python live syntax checking someday, but that would mean python2/3 split).

**Comment by nightwing** [comment]
https://github.com/MagicStack/MagicPython/tree/master/grammars/src Might be easier to use than old textmate grammar.
