### ISSUE TITLE
Changing key-bindings tot Sublime in options menu will try to load keybinding-sublime.js but this file does not exist

### ISSUE THREAD

**Issue by mohsen1** [ajaxorg/ace#2255]
Hi,

I see there is an option for Sublime Text key-bindings in settings menu but when it's selected it will not work and in console it will throw a 404 error for keybinding-sublime.js.

If work for Sublime Text key-bindings is not done yet, I'm interested in contributing if you can guide me.

**Comment by varemenos** [comment]
@nightwing any news on this? Did cloud9 decide not to open source the part of their code that include sublime mode?

**Comment by nightwing** [comment]
@varemenos is is open sourced in https://github.com/c9/c9.ide.ace.keymaps/blob/master/sublime/keymap.js but unfortunately i didn't have time to create ace keymap based on that

**Comment by jimbo1qaz** [comment]
still broken

**Comment by jimbo1qaz** [comment]
progress?

**Comment by wmantly** [comment]
+1

**Comment by andrewnester** [comment]
Has been addressed in this PR https://github.com/ajaxorg/ace/pull/3890
