### ISSUE TITLE
Ctrl+ArrowKey does not behave as expected

### ISSUE THREAD

**Issue by ayng** [ajaxorg/ace#2257]
When attempting to traverse between words ('w' and 'b' command in vim, 'M-f' and 'M-b' in emacs, 'Ctrl-ArrowLeft' etc. in most other places) the editor appears to see a group of spaces as word and will only traverse from the end of one word to the beginning of the next word. It effectively takes one more keystrokes to perform in Ace what can be performed in most other editors. Is this behavior intentional?

**Comment by jimbo1qaz** [comment]
todo fix this!

**Comment by spacetag** [comment]
Hello all! If one were to add @nightwing 's `$selectLongWords = true` snippet to https://github.com/ajaxorg/ace/blob/master/lib/ace/edit_session.js#L150, one might find that one may get one's desired behavior about Ctrl-Left, Ctrl-Right jumping the expected amount. Dare I say, perchance someone would adopt this into master, for the benefit of all downstream?

**Comment by fractos** [comment]
Any word on this? It makes for really annoying behaviour in dillinger.io
