### ISSUE TITLE
Selection Ranges returning character position instead of column/row

### ISSUE THREAD

**Issue by balupton** [ajaxorg/ace#226]
Hey,

I'm doing some pretty nifty stuff with ACE and I need it so that `editor.getSelectionRange` and `editor.getSession().selection.setSelectionRange` use a single character index, rather than a combination of column and row.

I'd really like to not have to wrap my stuff around a conversion process, but will do if it is necessary.

For instance when working with a textarea element, element.selectionStart is a character index, not a row, column combination. I need the same.

The use case is: http://nowpad.nodester.com/ - I need to be able to update the cursor positions when a sync occurs, we store cursor positions as character indexes - this cannot change.

**Comment by iangilman** [comment]
I too want to be able to set a selection based on a character count rather than row/column. I'd even be happy if there were conversion functions between the two. I'll use the example code here, but figured since it's been a few years I'd add this comment to see if anyone knows of a built in way now.

**Comment by nightwing** [comment]
you can use `indexToPosition` and `positionToIndex` methods on `editor.session.doc`

```js
editor.selection.setRange({
    start: editor.session.doc.indexToPosition(5),
    end: editor.session.doc.indexToPosition(15) 
})
```

But this should be used carefully, since its running time grows linearly with index.

**Comment by iangilman** [comment]
Awesome! That's exactly what I was hoping for! I looked through the selection and editor documentation, but I guess I didn't dig deep enough! Thanks as well for the heads up on the speed.
