### ISSUE TITLE
Cannot copy or paste on Android

### ISSUE THREAD

**Issue by bunnybreaker** [ajaxorg/ace#2265]
So far only tested with Chrome but had the same issues on other sites using the same code with multiple browsers.

**Comment by balping** [comment]
Any updates on this? It's still a problem

**Comment by polyzen** [comment]
Same issue with Fennec (Firefox for Android) 50.1.0 on CM13 (Android 6.0.1).

Too many related issues to reference. :p

**Comment by Serranya** [comment]
Paste still does not work on android with firefox
