### ISSUE TITLE
Provide API for keeping annotations and markers in sync with the text

### ISSUE THREAD

**Issue by nightwing** [ajaxorg/ace#2279]

**Comment by flxw** [comment]
Relevant information here: https://groups.google.com/forum/#!topic/ace-discuss/_SsC09KnzeQ

**Comment by flxw** [comment]
@nightwing: You write *make annotation cache in gutter lazy, and modify editSession to move annotations with text by default*

Which editSession and which annotation cache (this.$annotations?). Either I am understanding cache in this sense wrong or I am not looking in the correct file. Is is not inside the (file you pointed to?)[https://github.com/ajaxorg/ace/blob/master/lib/ace/layer/gutter.js#L103]

**Comment by nightwing** [comment]
I meant session.$annotations in https://github.com/ajaxorg/ace/blob/master/lib/ace/edit_session.js#L727 should update row, column values of annotations when text is changed, and the gutter should update this.$annotations https://github.com/ajaxorg/ace/blob/master/lib/ace/layer/gutter.js#L80-L100 only for rendered lines

**Comment by flxw** [comment]
Thank you so much for this info. I'll probably have a fix ready by next week!

**Comment by flxw** [comment]
What do I have to provide for this to get merged?

**Comment by ahirschberg** [comment]
Any updates on the possibility of this getting fixed/merged? Without region locations updating with the text, they are useless when used with an interactive editor.

**Comment by flxw** [comment]
I just discovered that I never followed up on my PR. Is this issue still a thing? If so, I would like to follow through with it.
