### ISSUE TITLE
add useless characters when inputing chinese

### ISSUE THREAD

**Issue by caseylai** [ajaxorg/ace#2288]
Hi,

When i was inputting chinese character, the editor was adding many Pinyin characters at the same time (attached images). At first I thought something wrong with my IME, but soon I found that the editor was working fine in kitchen sink. I tried to change the browser and enable some options but no luck.

finally I change the code from "new ace.EditSession" to "ace.createEditSession" and it is fixed. I look through the source code and find there is a undoManager to be set (v1.1.8, ace.js, line 18189). So, is it okay to put different implementations in the same interfaces? When instantiate a new EditSession, maybe it is better to set the undo manager as well. Thanks.

![1](https://cloud.githubusercontent.com/assets/1893528/5545974/c2748cd8-8b6f-11e4-9ddf-c1dc10620d15.png)
![2](https://cloud.githubusercontent.com/assets/1893528/5545973/c2724ec8-8b6f-11e4-9a42-90e5a2b01378.png)
![3](https://cloud.githubusercontent.com/assets/1893528/5545975/c2bac5e0-8b6f-11e4-8e8b-cafc18fd3a01.png)
![4](https://cloud.githubusercontent.com/assets/1893528/5545976/c2f46a70-8b6f-11e4-8f65-db12e62683e0.png)

**Comment by nightwing** [comment]
This should be fixed by https://github.com/ajaxorg/ace/pull/3635, please let us know if you still can reproduce this on http://ace.c9.io. Thanks.
