### ISSUE TITLE
LineWidgets is broken in recent builds

### ISSUE THREAD

**Issue by tetsuo** [ajaxorg/ace#2291]
1. Open inline editor (f3 or fn+f3)
2. Hit enter
3. Hit backspace
4. Get following errors:
`Uncaught TypeError: Cannot read property 'getTokens' of null`
`Uncaught TypeError: Cannot read property 'getState' of null`
5. Editor is dead now

http://recordit.co/Tc3y6s8rng

**Comment by nightwing** [comment]
It was calling destroy on wrong editor, will be fixed by https://github.com/ajaxorg/ace/pull/2309
