### ISSUE TITLE
Autocomplete Loses Focus on JSON Requests (Live Autocompletion)

### ISSUE THREAD

**Issue by jaredbroad** [ajaxorg/ace#2293]
Using the latest build and a JSON web request for auto-complete the editor looses focus on the auto-complete dropdown. Sadly the error is fairly difficult to repeat, but we can repeat in even basic demonstrations with enough time.

e.g. http://plnkr.co/edit/6MVntVmXYUbjR0DI82Cr?p=preview 
 Keep writing and pressing the down arrow to select options. It may take 1-2 minutes typing to repeat.

Once it has lost focus its impossible to close by keyboard, and clicking on one of the options will cause substitution in the wrong location/substitute the wrong text. 

We *think* it is some sort of timing issue, caused by delays in the JSON response.

**Comment by nightwing** [comment]
It was showing a popup from older request, will be fixed by #2309
