### ISSUE TITLE
Install via npm?

### ISSUE THREAD

**Issue by tmcw** [ajaxorg/ace#2295]
Right now it looks like [ace has a package.json with the name 'ace'](https://github.com/ajaxorg/ace/blob/master/package.json#L2) but [ace on npm is a different project](https://www.npmjs.com/package/ace). Is ace published under a different name?

**Comment by nightwing** [comment]
Ace is not published on npm yet. You can install it with `npm i git+https://github.com/ajaxorg/ace#master` or `npm i git+https://github.com/ajaxorg/ace-builds#master` for built version

**Comment by thealjey** [comment]
but will it ever be published on npm, do you have any plans for that?
would be awesome :smile:

**Comment by DenisKolodin** [comment]
Builds already exists: https://www.npmjs.com/package/ace-builds
If you want sources I don't think it's a good idea to get them as npm dependency.

**Comment by tmcw** [comment]
Okay, we can use builds - thanks!

**Comment by adius** [comment]
It should definitely be possible to just `npm install ace`

**Comment by adius** [comment]
Btw: I have the package name `ace-code-editor`. I'd be happy to give it to you should you decide to publish ace on npm.

**Comment by adrian-moisa** [comment]
I have installed `ace-code-editor`. How do I use it together with typescript `@types/ace` ? I'm stuck at the importing inside the es6 class step.

**Comment by vedmant** [comment]
Any updates on this? Can't believe there is no official ace npm package...

**Comment by trevorhreed** [comment]
This would be particularly useful in combination with webpack's tree-shaking.

**Comment by nightwing** [comment]
@trevorhreed this is already possible using the ace-builds npm package https://github.com/ajaxorg/ace/tree/master/demo/webpack https://github.com/nightwing/ace-webpack-demo

**Comment by kuchaguangjie** [comment]
It's here: https://www.npmjs.com/package/ace-builds

Could install via：

> yarn add ace-builds

or 

> npm install ace-builds

Then import via:

>  import ace from 'ace-builds'

**Comment by kungfooman** [comment]
Another way to import:

```html
<script src="./node_modules/ace-builds/src/ace.js"></script>
```
