### ISSUE TITLE
Search (find) is broken

### ISSUE THREAD

**Issue by sevin7676** [ajaxorg/ace#2297]
The development [Kitchen Sink](https://github.com/ajaxorg/ace/blob/master/kitchen-sink.html) is not working properly with the `Ctrl-F` hotkey (find). Using it doesn't open find, instead it logs a warning `Automatically scrolling cursor into view after selection change this will be disabled in the next version set editor.$blockScrolling = Infinity to disable this message`. I believe its due to two commands being bound to `Ctrl-F`

![image](https://cloud.githubusercontent.com/assets/5360920/5605770/da210422-93dc-11e4-8548-b7ad41b69620.png)

I had to change the binding for [Incremental Search](https://github.com/ajaxorg/ace/blob/master/lib/ace/commands/incremental_search_commands.js#L41) in my work to allow me to work on the search box (I'm adding search in selection)

**Comment by nightwing** [comment]
There is a checkbox for enabling/disabling incremental search mode on the left side.

**Comment by sevin7676** [comment]
I don't think I understand what the desired functionality of this incremental search is. Is it documented anywhere?

**Comment by nightwing** [comment]
It is mainly used by emacs mode, but other editors have incremental search too. Visual studio and Sublime use `ctrl-i` for it.
