### ISSUE TITLE
PHP Chaining Syntax Error

### ISSUE THREAD

**Issue by staabm** [ajaxorg/ace#2299]
Valid multi-line PHP code is recognized as php-syntax-error

```php
$finder = Symfony\Component\Finder\Finder::create()
    ->in('/tmp')
    ->depth(0)
    ->files()
    ->name('*.json')
;
```

**Comment by nightwing** [comment]
Where do you see this? I cannot reproduce it on http://ace.c9.io/build/kitchen-sink.html

**Comment by staabm** [comment]
@nightwing thanks for your feedback. you are right, I am not able to reproduce it at the kitchen-sink
