### ISSUE TITLE
Matching brace highlighting behaviour might be tweaked with Vim + normal mode

### ISSUE THREAD

**Issue by kevinushey** [ajaxorg/ace#2302]
See the attached gif:

![matching-highlight](https://cloud.githubusercontent.com/assets/1976582/5656059/16483a18-968c-11e4-917c-e0c63d0c4e1d.gif)

I would expect that the accompanying brace would be highlighted when the Vim (normal mode) cursor is on top of a brace, not following it.

**Comment by nightwing** [comment]
Would it be ok if it highlighted matching brace both when on top and after the brace?

**Comment by kevinushey** [comment]
Yes, I think that would be sensible -- IMO, it would make sense when not using Vim as well -- ie, the matching brace could be highlighted whether the cursor is 'before' or 'after' the associated brace.

Would this also entail having `CTRL + P` move to the matching brace in both cases as well? (which would be nice!)

**Comment by kevinushey** [comment]
It looks like this is being looked at upstream: https://github.com/codemirror/CodeMirror/issues/2934

**Comment by kevinushey** [comment]
For posterity, it looks like this issue has indeed been fixed. Thanks!

<img width="156" alt="Screen Shot 2022-05-09 at 12 01 52 PM" src="https://user-images.githubusercontent.com/1976582/167479289-295635a0-2bda-46c4-a3ed-f44d66fe5ae3.png">

**Comment by andrewnester** [comment]
1.5+
