### ISSUE TITLE
Ruby 2.1.5 syntax support

### ISSUE THREAD

**Issue by abitdodgy** [ajaxorg/ace#2304]
Ruby 2.1.5 introduced required named arguments, which causes a syntax error in in the editor. For example:

```ruby
def greet(name:, greeting: "Hello")
  puts "#{greeting}, #{name}"
end
```

Which produces.

```
syntax error, unexpected tLABEL, expecting ')'
```

**Comment by nightwing** [comment]
This is not related to Ace. To check ruby syntax cloud9 uses `ruby -w`.
