### ISSUE TITLE
toggleCommentLines & toggleBlockComments doesn't work for ace/mode/php

### ISSUE THREAD

**Issue by alexbarnsley** [ajaxorg/ace#2306]
The commands mentioned above don't work when in php mode of the ace editor. Commands `Ctrl + /` or `Ctrl + Shift + /` both do nothing, even though I can see they are there using `editor.commands.commandKeyBinding`

No errors are coming up in Developer Console. Experienced in Google Chrome 39.0.2171.95.

**Comment by nightwing** [comment]
For which version of Ace? Master seems to work fine http://ace.c9.io/build/kitchen-sink.html

**Comment by alexbarnsley** [comment]
Apologies, it was 1.1.8. But you are right, it's working for me on Kitchen Sink. Will re-pull master in case it differs in any way.
Thanks

**Comment by alexbarnsley** [comment]
Tested with latest version of Master. Seems to be working - not sure if there was a problem with CDN version I used before. Working now, so a non-issue. Thanks!
