### ISSUE TITLE
Occasional uncaught exception:  this.$highlightTags 'token is null'

### ISSUE THREAD

**Issue by cubiclesoft** [ajaxorg/ace#2307]
```javascript
    this.$highlightTags = function() {
        if (this.$highlightTagPending)
            return;
        var self = this;
        this.$highlightTagPending = true;
        setTimeout(function() {
            self.$highlightTagPending = false;
            
            var session = self.session;
            if (!session || !session.bgTokenizer) return;
            
            var pos = self.getCursorPosition();
            var iterator = new TokenIterator(self.session, pos.row, pos.column);
            var token = iterator.getCurrentToken();
            
            if (!token || !/\b(?:tag-open|tag-name)/.test(token.type)) {
                session.removeMarker(session.$tagHighlight);
                session.$tagHighlight = null;
                return;
            }
            
            if (token.type.indexOf("tag-open") != -1)
                token = iterator.stepForward();

            var tag = token.value;
```

Sometimes 'token' is null.  It seems to happen mostly with an empty document that receives its first character when ACE is loaded asynchronously.  Whenever token is null, the browser raises an exception:  "Uncaught TypeError: Cannot read property 'value' of null".

The error then seems to cause syntax highlighting to not happen in some browsers that refuse to execute code that caused an earlier uncaught exception.

A possible fix could be to do:

```javascript
...

            if (token.type.indexOf("tag-open") != -1)
                token = iterator.stepForward();

            if (!token)
               return;

            var tag = token.value;
```

**Comment by nightwing** [comment]
Thank you for the report, this will be fixed by Will be fixed by https://github.com/ajaxorg/ace/pull/2309

> The error then seems to cause syntax highlighting to not happen in some browsers that refuse to execute code that caused an earlier uncaught exception.

just curious, which browsers do this?

**Comment by cubiclesoft** [comment]
I've seen that behavior happen in Firefox.  Not sure about other browsers.
