### ISSUE TITLE
Worker errors remain when switching modes

### ISSUE THREAD

**Issue by cubiclesoft** [ajaxorg/ace#2308]
Can be seen on the Kitchen Sink demo.  Steps to reproduce:

1.  Start with a PHP document in PHP mode.
2.  Enter in some code that raises a syntax error notification from the worker.
3.  Switch to another mode that does not have a worker (e.g. Text).

The syntax error remains regardless of what happens in the document.  The only way to get rid of the error requires switching back to the original mode where the error occurred.  This is a problem if a server selects a mode with a worker that isn't suitable for the content and the user switches it to the correct mode via a dropdown select box similar to the one in the kitchen sink demo - the errors won't go away.

I noticed this bug a long time ago but decided that workers were too heavy to use in Barebones CMS, so I ended up disabling them altogether with setUseWorker(false).

**Comment by nightwing** [comment]
Will be fixed by https://github.com/ajaxorg/ace/pull/2309
