### ISSUE TITLE
In vim keybinding, `^` and `I` is not correct

### ISSUE THREAD

**Issue by farnoy** [ajaxorg/ace#2310]
It depends where the cursor is on the line.

Example (`^` is the cursor):

```
  some indented text
^
```

Pressing `^` or `I` now will move to the first non-blank character of the line, which is the same as in Vim:

```
  some indented text
  ^
```

Repeating it again will move to the first character of the line, like `0` should:

```
  some indented text
^
```

Source: <http://vimdoc.sourceforge.net/htmldoc/motion.html#^>

Originally found in zed, https://github.com/zedapp/zed/issues/478.

**Comment by nightwing** [comment]
This is fixed in the latest version, try http://ace.c9.io/build/kitchen-sink.html

**Comment by farnoy** [comment]
It works, thanks.
