### ISSUE TITLE
Chrome display issue

### ISSUE THREAD

**Issue by loomtronic** [ajaxorg/ace#2312]
If put this text in the editor

`<a href="<#[system.referring_page_url as html]#>?cloudward_snippet_id=<# snippet "member restricted" #>&extra_param=test123">request a page restricted to members appended with &extra_param=test123 </a>`

![image](https://cloud.githubusercontent.com/assets/1706404/5723210/24dcc4e4-9af7-11e4-8a5c-51965fa78163.png)

the “>” gets moved to the next line, but there really isn’t a newline, even though it’s showing a new line number.

the cursor is on the left as shown above:  “|>”  but if i push the right arrow, the cursor doesn’t go anywhere… it should go to the right of the carat like “>|”

when you go back to the previous line it looks like this:
![image](https://cloud.githubusercontent.com/assets/1706404/5723183/f41df260-9af6-11e4-9185-cf3689b937ec.png)

so the cursor is after a space after the “</a |”… but when i try to delete that space, it delete the “a” instead so it looks like “</ | “

This issue only occurs in Chrome

**Comment by nightwing** [comment]
Seems to be caused by https://code.google.com/p/chromium/issues/detail?id=373502, when i add 
```css
.ace_line { word-wrap: normal; }
```
the bug goes away
