### ISSUE TITLE
XML mode auto-indenting after self-closing tags

### ISSUE THREAD

**Issue by inclinetechnical** [ajaxorg/ace#2314]
In XML mode, I noticed typing a self-closing tag and then hitting ENTER would cause an extra indent to be added on the line below the tag.

For example, the behavior I saw was this:

```xml
<OuterTag>
    <SelfClosingTag />
        |<-- (new insertion point after hitting ENTER, 4 spaces right of where I expected)
</OuterTag>
```

But I expected this:

```xml
<OuterTag>
    <SelfClosingTag />
    |<-- (expected new insertion point after hitting ENTER)
</OuterTag>
```

The issue appears to be in the xml.js file in the behaviour folder:
https://github.com/ajaxorg/ace/blob/master/lib/ace/mode/behaviour/xml.js

Not sure if this is the best fix, but I worked around it on my end by editing the auto-indent behavior as shown below:

```javascript
var token = iterator.getCurrentToken();
// I added this line just under the one above
var selfClosing = (token && token.type.indexOf("tag-close") !== -1 && token.value == "/>");

// Then, for the "if" statement that prevents indenting after closing tags, I changed it to:
if (!token || token.type.indexOf("end-tag") !== -1 || selfClosing) {
```

**Comment by nightwing** [comment]
Thanks! I've used your fix, just moved `.value` check into main if block https://github.com/ajaxorg/ace/commit/135b9e5baf7e89549a8bfa339310ff39961a253e
