### ISSUE TITLE
Vim mode ':write' command gives an error

### ISSUE THREAD

**Issue by zefhemel** [ajaxorg/ace#2317]
When I execute `:w` or `:write` in vim mode it gives a type error. Maybe the ex commands that vim mode supports should extensible from the outside so that new commands can be added and existing ones (like `:w`) can be given "real" meaning?

**Comment by julien** [comment]
+1
I have the same issue, looking at the source I think this could be a good start
https://github.com/ajaxorg/ace/blob/master/lib/ace/keyboard/vim.js#L5158

**Comment by julien** [comment]
I actually found a "patch" although it's pretty ugly ...

Say you have your editor 

```
  var editor = ace.edit('editor');
  editor.setKeyboardHandler('ace/keyboard/vim');

  editor.commands.addCommand({
    name: 'saveFile',
    bindKey: {
      win: 'Ctrl-S', mac: 'Command-S',
      sender: 'editor|cli'
    },
    exec: function (env, argv, request) {
       console.log('saving ...');
    }
  });
```

I edited the keybinding-vim.js file 

```
   write: function(cm) {
        if (CodeMirror.commands.save) {
          CodeMirror.commands.save(cm);
        } else {
          if (cm.ace.commands.commands.saveFile) {
            cm.ace.commands.commands.saveFile.exec();
          }
        }
```

As I said, it's really an ugly solution but it triggers the same "saveFile" command defined above.

I'd like to know what the "ace" team thinks about this cause I'd be happy to contribute but there has to be a cleaner way, I was going to get into the code but I have not much time over the next few days.

**Comment by nightwing** [comment]
ex commands are not fully integrated with Ace yet. Zed can use defineEx to overwrite the default behavior
```js
var VimApi = require("ace/keyboard/vim").CodeMirror.Vim
VimApi.defineEx("write", "w", function(cm, input) {
    // do stuff with cm.ace here...
})
```

**Comment by julien** [comment]
@nightwing Thanks exactly what I was looking for, we can probably close this issue.

**Comment by zefhemel** [comment]
Not really, :w shouldn't give a JS error, ever.

**Comment by nightwing** [comment]
@zefhemel https://github.com/ajaxorg/ace/commit/64eaf47c4d5f625e6294eee9215295bcdfd806af fixes the error
