### ISSUE TITLE
ACE in node-webkit

### ISSUE THREAD

**Issue by PeterA1** [ajaxorg/ace#2319]
Hi,

If you use ACE editor within node-webkit it seems as if Carriage Return / enter are not handled correctly.

If content is loaded with .setValue() then all content appears on the first line.

If a single line is loaded it appears OK, and new content can be typed in, but of you hit enter then all subsequent text is written to the first line.....but the cursor is correctly positioned.

All works fine in Chrome/

Best Regards
Peter

**Comment by PeterA1** [comment]
Hi Again,

OK, I think I now know what was causing the issue....if I have 
<style> div { position: absolute } </style>
( thats's the default for all div's then I have the problem).

It's still a problem, just not related to node-webkit (now NW.js)

Please advise.

Best Regards
Peter

**Comment by nightwing** [comment]
Ace cannot work if you add `div { position: absolute }` rule to your css. Try using something more specific that doesn't change behavior of all div elements on the page
