### ISSUE TITLE
Scroller issue

### ISSUE THREAD

**Issue by matthew-dean** [ajaxorg/ace#2320]
I have Ace integrated into a Chromium frame (so it should behave the same as recent versions of Chrome). For some reason, my basic setup of Ace doesn't ever show a scrollbar. The text area scrolls as normal, but no scrollbar appears. I've compared it to the kitchen sink demo, and I haven't been able to figure out what forces the scrollbar to appear.

~~Also weird on the kitchen sink demo: sometimes a custom scrollbar appears, and sometimes Chrome's native scrollbar appears over the custom one (in Chrome on OS X). And checking "Animate scrolling" or "Persistent HScroll" or "Persistent VScroll" seems to have no effect.~~

Any ideas what might cause the scrollbar to never show? Ideally, I'd love to just have the default Chrome scroller, especially if (once it works), it will occasionally conflict with the custom scroller anyway.

**Comment by matthew-dean** [comment]
Also of note: scrollbars appear in other overflow containers in my Chromium frame, just not Ace's.

**Comment by nightwing** [comment]
> Also weird on the kitchen sink demo: sometimes a custom scrollbar appears, and sometimes Chrome's native scrollbar appears over the custom one (in Chrome on OS X)

which custom scrollbar? kitchen sink demo shouldn't have any custom scrollbars.

**Comment by matthew-dean** [comment]
Sorry, I think what I was seeing is that Chrome switches scrollbar appearance if the mouse cursor is closer to the edge (to show the draggable region).

Ignore that part. The first question is what's important to me: figuring out why I can't get a scrollbar to appear.

**Comment by nightwing** [comment]
If you have some reproducible testcase, where Ace doesn't work, i can help you to find the issue. But your bug report doesn't give any information for that. E.g. What is 'Chromium frame', how did you 'integrate' Ace into it?

**Comment by matthew-dean** [comment]
Chromium is essentially the core of Chrome. So for all intents and purposes it's Chrome, although individual builds of Chromium may turn off / on some flags that Google Chrome has off / on by default. More specifically, the context is in node-webkit (https://github.com/nwjs/nw.js). I'll try to get you a test-case, although since it's a desktop app, it might take me a while to extract something that could be posted accessibly. That's why I was hoping you might be able to point me in the direction of ways to debug the scroll component. But fair enough that you want something easier to work with.

**Comment by matthew-dean** [comment]
I got this to work by customizing webkit's scrollbars via CSS, which makes scrollbars visible all the time instead of fading on OS X (Yosemite). The problem was that setting scrollTop / scrollHeight for the inner scroll element didn't trigger a visible scroll on Chrome / OS X. The only time a visible scroll appeared is when it was related to a user action.

**Comment by matthew-dean** [comment]
That may happen on some systems if you are stopping propagation of mousewheel events, which looks like it may be the case here.

**Comment by nightwing** [comment]
https://github.com/ajaxorg/ace/pull/3987 fixes this
