### ISSUE TITLE
Typing "}" character using Ctrl-Alt-0 triggers "fold all"

### ISSUE THREAD

**Issue by demilja** [ajaxorg/ace#2321]
In German (and others) keyboard layout, the "}" character is on the 0 key and can be be typed by Ctrl-Alt-0 (or AltGr-0).
In Ace Editor, when trying to type the "}" character using Ctrl-Alt-0, the "fold all" action is triggered which is bound to the "Alt-0" short cut.
It would be good if the Ace Editor distinguished between Alt-0 and Ctrl-Alt-0

**Comment by nightwing** [comment]
This used to be a problem in old versions but should be fixed in newer ones.
On https://ace.c9.io when pressing `rightAlt-0` the "}" character is inserted and when pressing `leftCtrl-leftAlt-0` keybinding for `ctrl-alt-0` is [triggered](https://github.com/ajaxorg/ace/blob/master/lib/ace/commands/default_commands.js#L122)

**Comment by demilja** [comment]
Hm – what you describe as the fix is exactly what I reported as the issue, apart from that I thought Alt-0 should trigger “fold all”, as it is documented in the wiki<https://github.com/ajaxorg/ace/wiki/Default-Keyboard-Shortcuts> (which should be updated then).

Anyway – I understand that the behavior I described actually now is the intended behavior.
However I don’t agree that this is a good idea, because it conflicts with many programmer’s habit of using Ctrl-At-0 for typing the } character.

**Comment by nightwing** [comment]
Hmm, i see, based on older issue reports i thought most people were using right alt. 
The shortcut for ctrl-alt-0 was added when alt-0 was changed to not fold code around the cursor. I think it might be ok to remove ctrl-alt-0 shortcut since it doesn't add much over alt-0, but there are other commands bound to ctrl-alt-<something>, and removing all of them is not possible.

**Comment by demilja** [comment]
Maybe it's true that most people are using right alt, I  don't know. Personally, I use both, right-alt-0 and Ctrl-Alt-0.
Concerning the other ctrl-alt shortcuts I don't think they are a problem, as these shortcuts don't normally insert characters (apart from Ctrl-Alt-E, which inserts the € character, but I don't think it's commonly used as it is much easier in this case to use right-alt-E instead of Ctrl-Alt-E).

**Comment by demilja** [comment]
Now I noticed that even when using right-alt-0 it happens every now and then that "fold all" is executed. I did not find a way to reproduce this reliably. It even happens when I type a row of } characters. It might happen with the first, it might happen with the 30th character.
It also happens in the online kitchen-sink demo (http://ace.c9.io/build/kitchen-sink.html).

This occurs at least in IE9 and IE10 (IE11 not tested). I did not see it in Firefox so far. In Chrome I saw it once (right on the very first try) not not again up to now.

Should I log another issue for that?

**Comment by nightwing** [comment]
> Should I log another issue for that?

let's continue with this issue.

What values of `dt` you get at https://github.com/ajaxorg/ace/blob/master/lib/ace/lib/event.js#L249

**Comment by demilja** [comment]
Ok, I used a conditional breakpoint to do some logging:
Last time: 1422017483791
 Current time:1422017483791
 Delta: 0
 Last time: 1422017484256
 Current time:1422017484256
 Delta: 0
 Last time: 1422017484707
 Current time:1422017484707
 Delta: 0
 Last time: 1422017485134
 Current time:1422017485134
 Delta: 0
 Last time: 1422017485562
 Current time:1422017485578
 Delta: 16
 Last time: 1422017486020
 Current time:1422017486020
 Delta: 0


At the point where I see dt equals 16, the fold all is triggered.

**Comment by nightwing** [comment]
https://github.com/ajaxorg/ace/pull/2322 should fix this issue.
It detects pressing left ctrl and right alt as altgr in more cases, but i think that way of invoking ace shortcuts like ctrl-alt-a is not used often

**Comment by demilja** [comment]
Thank yo very much for your quick response and help!
