### ISSUE TITLE
on change event message include property for apply delta

### ISSUE THREAD

**Issue by cp16net** [ajaxorg/ace#2326]
I've been playing with this and i have not found a way to determine if a change event was caused by the keyboard or by applying a delta to the document. Could there be a property i'm either missing or added to the change event message so that it can be handled differently depending on the how the document was changed?

**Comment by nightwing** [comment]
Currently there is no clean way to add that metadata to  the change event, and in the next version most likely there won't be an event but handler will get delta directly https://github.com/ajaxorg/ace/commit/525fe1ffe306a6258578c238b17114a00f71888a

You can get origin of the delta by using `editor.curOp` instead

**Comment by cp16net** [comment]
@nightwing I think `editor.curOp` is exactly what i was looking for. Looks like i can check it for for `args` and it should tell me if there was an arg entered from the keyboard or nothing if applying a delta. Maybe checking `command.name` might be a little safer for `insert*`. 

Looks like getting the delta will more logical in the next version.
Thanks!
