### ISSUE TITLE
Typing '<' in Markdown mode throws exception

### ISSUE THREAD

**Issue by kevinushey** [ajaxorg/ace#2328]
Repro:

1. Open The [kitchen sink](http://ace.c9.io/build/kitchen-sink.html),
2. Clear the document,
3. Set the mode to 'Markdown',
4. Type a `<`.

I see this in the developer tools output:

![screen shot 2015-01-27 at 2 29 49 pm](https://cloud.githubusercontent.com/assets/1976582/5928547/f773efec-a630-11e4-8c8d-57ef2ef21afc.png)

**Comment by kevinushey** [comment]
My guess -- the success of `iterator.setForward()` needs to be checked?

**Comment by nightwing** [comment]
This was fixed in https://github.com/ajaxorg/ace/commit/e1a5492a7fc8cf27b9b7d6d9ba06700030a2e449 will be in the next release
