### ISSUE TITLE
Code coloring stops in very long lines

### ISSUE THREAD

**Issue by matthew-dean** [ajaxorg/ace#2330]
See screenshot:
![screen shot 2015-01-27 at 8 46 14 pm](https://cloud.githubusercontent.com/assets/414752/5932666/58889ef0-a667-11e4-9308-bee80983da1c.png)

Regardless if a single line or the line is wrapped in wrap mode, the coloring seems to sputter out at some point. I've seen this with JS and CSS modes, so I assume more modes have this issue.

**Comment by nightwing** [comment]
This is done for performance reasons
You can increase it if you want. see https://github.com/ajaxorg/ace/blob/e1933043dc0941da3922b5c3efb2c51f6fa9fc56/lib/ace/tokenizer.js#L136
Default value for max tokens can be increased to ~20000 when text_layer is updated to draw only visible part of the line

**Comment by matthew-dean** [comment]
Thanks! Out of curiosity, wouldn't the number of tokens be the same if this file wasn't minified? It still has all the same characters.

**Comment by matthew-dean** [comment]
Oh oh oh, I see, the minification means way more tokens in the DOM since the number of tokens per line is a lot higher and you only insert visible lines in the DOM.
