### ISSUE TITLE
Possible autocompletion bug here.....

### ISSUE THREAD

**Issue by RockyMyx** [ajaxorg/ace#2335]
![error](https://cloud.githubusercontent.com/assets/4414158/5972793/421ef45e-a89a-11e4-8980-2356cbed54f6.png)

As we can see from the picture that the chinese in autocompletion looks a little unclear.

Is anybody who can tell me why?  Thanks...

plus:  I change the charset, but the problem remains.

**Comment by nightwing** [comment]
Probably text-shadow rule from https://github.com/ajaxorg/ace/blob/master/lib/ace/autocomplete/popup.js#L326 doesn't work well for chinese text, we may need to change highlighting to underline instead

**Comment by RockyMyx** [comment]
ok, I'd like to be informed if the bug is fixed...
