### ISSUE TITLE
The horizontal scrollbar isn't updated properly after pasting text.

### ISSUE THREAD

**Issue by seftur** [ajaxorg/ace#2336]
This issue is reproducible using the editor on http://ace.c9.io/#nav=about

Clear the text in the editor (ctrl+a and then backspace), and paste the following in it (including quotes):
"
SELECT ATTRIBUTE1, ATTRIBUTE2, ATTRIBUTE3, ATTRIBUTE4, ATTRIBUTE5, ATTRIBUTE6, ATTRIBUTE7, ATTRIBUTE8, ATTRIBUTE9, ATTRIBUTE10, ATTRIBUTE11, ATTRIBUTE12, ATTRIBUTE13, ATTRIBUTE14, ATTRIBUTE15, ATTRIBUTE16, ATTRIBUTE17, ATTRIBUTE18, ATTRIBUTE19
FROM TABLE1
"

A scrollbar does appear, but is not the correct scrollbar. After you use the scrollbar, it updates to a correct scrollbar. If you paste without the quotes, no scrollbar appears at all.
I've tested this in the following browsers:
-Chrome 40.0.2214.93 m
-FireFox 35.0
-IE 11.0.15

You can also see the issue below:

wrong scrollbar:
![wrongscroll](https://cloud.githubusercontent.com/assets/10047000/5974480/0b4c5518-a875-11e4-942d-60a5c33b5eb6.png)

the correct scrollbar that appears after scrolling:
![correctscroll](https://cloud.githubusercontent.com/assets/10047000/5974479/0b4b3da4-a875-11e4-8073-6c2a7b3e4d84.png)

**Comment by Martii** [comment]
Just experienced a similar event to this. The horizontal scroll bar handle disappeared. The use case is when I start out in wrapped mode then toggle to unwrapped. I am also pasting some JSON and text into two Ace input boxes too soon. I had to delay the click event until Ace was finished doing it's thing in the background.

*ace-builds* package 30.09.15 b082bcb
SeaMonkey 2.35 64 bit Moz build
Firefox 39.0.3 64 bit Distro build
