### ISSUE TITLE
how to realize line remove listener?

### ISSUE THREAD

**Issue by 281494498** [ajaxorg/ace#2337]
I searched the API document, and have not found a method like "onLineRemove(String text)";

Is there any method could realize that function?

Since I am try to realize a real-time interpreter which could interpret the code when user add or delete line. For add line, I could listen to the "enter" button, but for deleting line, I have no idea at the moment.

**Comment by nightwing** [comment]
You can use 
```js
editor.session.on('change', function(e) { 
     var range = e.data.range; 
     if (range.start.row  == range.end.row) ...
})
```

note that change event is dispatched sync, so if you need to run code that might take long, use timeout from that event.

**Comment by 281494498** [comment]
I see, Thanks!

**Comment by 281494498** [comment]
Sorry to reopen this question again, is there a internal method to change the event timeout? I checked the usage of this onChange event but not found yet, or I will build a external buffer for doing that.

**Comment by nightwing** [comment]
onChange itself doesn't have a timeout, you can use editor input event or add a buffer similar to https://github.com/ajaxorg/ace/blob/v1.1.8/lib/ace/editor.js#L95-L103, this depends on what exactly you are going to do in the handler.

**Comment by 281494498** [comment]
thanks!
