### ISSUE TITLE
Got an exception after typing "<" character

### ISSUE THREAD

**Issue by fedulovivan** [ajaxorg/ace#2339]
Steps to reproduce:
- Initialize editor in "xml" or "html" mode
- Clean editor area
- Type single character "<"
Actual result:
Exception **Uncaught TypeError: Cannot read property 'value' of null** is thrown in line 11479 of ace.js
Expected:
No exception

This is reproduced on http://ajaxorg.github.io/ace-builds/kitchen-sink.html also.

Browser: Chrome Version 40.0.2214.93 m

![image](https://cloud.githubusercontent.com/assets/752105/6003473/1d060016-ab0d-11e4-8216-832f498a385a.png)

**Comment by nightwing** [comment]
This issue is fixed in the master branch, https://github.com/ajaxorg/ace/blob/master/lib/ace/editor.js#L550. which will be released soon.

**Comment by fedulovivan** [comment]
Ok, thank you!  Closing this one then.
