### ISSUE TITLE
Allow anchors to be left-(in/ex)clusive, and right-(in/ex)clusive

### ISSUE THREAD

**Issue by kevinushey** [ajaxorg/ace#2345]
Motivation: I'm using anchored ranges to highlight / underline words in a document (e.g. lint errors), and I would prefer these ranges to be 'sticky' when the user edits the document. This works very well with the advice from this thread: https://groups.google.com/forum/#!topic/ace-discuss/WsL-ZATvKQQ.

However, if the user places the cursor at the end of an anchored selection, and then starts typing (entering new text), that selection is extended to include the new text, e.g.

![ace-anchor](https://cloud.githubusercontent.com/assets/1976582/6055580/41ccf35e-acb7-11e4-8fc0-49d2c7a6815e.gif)

Is it possible to make these anchors to be right-exclusive, or 'locked', so that they don't accept new text, or even are removed upon an action that modifies the text within that range?

**Comment by nightwing** [comment]
Right now anchor supports experimental `$insertRight` option for this, but i want to rename it to `bias` instead.
Also see https://github.com/ajaxorg/ace/blob/385a285c58/lib/ace/keyboard/vim.js#L326-L361 for another approach, which seems to be cleaner and faster than using anchors

**Comment by kevinushey** [comment]
Excellent! That's exactly what I need -- thanks!

**Comment by kevinushey** [comment]
It looks like support for a range "bias" was added here:

https://github.com/ajaxorg/ace/commit/c8c826466a1e04f96f5e0e597ecc0bbb537a34c5

Thanks!
