### ISSUE TITLE
Range constructor conflict

### ISSUE THREAD

**Issue by MarkIvanowich** [ajaxorg/ace#2346]
Trying to use Ace's Range constructor, I have discovered that there is another Range constructor, that has been causing me much headache:
https://developer.mozilla.org/en-US/docs/Web/API/Range.Range

Can someone also offer me a quick fix, to make sure I use Ace's?

**Comment by kevinushey** [comment]
Something like:

    var AceRange = require("ace/range").Range;
    var aceRange = new AceRange(...);

?

**Comment by MarkIvanowich** [comment]
After some fiddling, I got it. 
That more or less worked, however the "ace/range" also contains the start and end objects, so:
'var AceRange = require("ace/range")'
Did what I needed. Thanks!
