### ISSUE TITLE
Ace doesn't work under nw.js(node-webkit)

### ISSUE THREAD

**Issue by astoilkov** [ajaxorg/ace#2348]
Tried linking to the ace editor in the HTML but it throws error:
```html
<script src="lib/ace/ace.js"></script>
```

Also tried to include it using require but again error is thrown:
```javascript
var ace = require('../lib/ace/ace');
```

**Comment by nightwing** [comment]
Which error? Most likely the file you are trying to load is in another location.

**Comment by astoilkov** [comment]
I am sure the file is in this location because when I intentionally changed to another location the error was different.

While I was debugging I found out the reason it is not working. Ace overrides the require function which is available from Node and further calls to require do not work. I workaround the issue by including Ace as a last script on the page and not using require from that point on. I am not sure if this problem could be fixed...maybe specifically checking if the global object is not Node?

**Comment by nightwing** [comment]
You can use noconflict version https://github.com/ajaxorg/ace-builds/tree/master/src-noconflict
which doesn't modify require and creates global variable ace

But could you please tell me which error did you see? The code at https://github.com/ajaxorg/ace/blob/master/build_support/mini_require.js#L92 is meant to forward require calls to the native require.

**Comment by astoilkov** [comment]
It fails on my first require with "Cannot read property 'fs' of undefined":
```javascript
var fs = require('fs');
```
This could easily be reproduced by making a node-webkit project including ace.js as a script tag and then calling require('any package you want'). I could not debug it because it does not want to step into the function (which I think is a node-webkit regression bug).

**Comment by nightwing** [comment]
https://github.com/ajaxorg/ace/pull/2355 should fix the issue. Thank you for the bug report
