### ISSUE TITLE
How to support easylanguage rules and syntax highlighting in the editor

### ISSUE THREAD

**Issue by Cryhelyxx** [ajaxorg/ace#2349]
`EasyLanguage` is the exclusive language program developed by TradeStation Securities Inc., and built on the TradeStation trading platform.How do I extend `ace` editor that supports easylanguage rules and syntax highlighted in the editor?

**Comment by nightwing** [comment]
see http://ace.c9.io/#nav=higlighter

**Comment by Cryhelyxx** [comment]
That is exactly what I need, I will try next. Thanks.
