### ISSUE TITLE
Wrong font family used on some Chrome's, resulting in misplaced cursor

### ISSUE THREAD

**Issue by pamelafox** [ajaxorg/ace#2353]
Students have been sporadically reporting this with the khanacademy.org/cs/new coding editor, which uses ACE. I asked them to replicate on the ACE site and they were able to do so:

![afterbackspace](https://cloud.githubusercontent.com/assets/297042/6151914/fb40c43a-b1cd-11e4-9603-7a279657febb.jpg)

This is the user agent of that reporter:
"Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.94 Safari/537.36"

It seems to be the wrong font-family, but I haven't been able to figure out why it's the wrong font-family via my back and forth with them. Do you have any ideas about what's wrong, or additional info I could ask them for? Thanks!

**Comment by nightwing** [comment]
looks like the computer misses monospace fonts, or default monospace font is misconfigured
Chrome font settings can be changed using chrome://settings/fonts
![chromemonospace](https://cloud.githubusercontent.com/assets/341801/6152339/ccb9c220-b235-11e4-9cae-7ed206adb101.PNG)

I also found this question http://superuser.com/questions/695635/windows-8-1-missing-font-files-after-restart/698885#698885, which might be relevant

**Comment by sharpfuryz** [comment]
I would like to notice that css-code:
```css
* { font-family: 'customfont';}  
body,html { font-family: 'customfont';}  
```
causes same issue - misplaced cursor.
