### ISSUE TITLE
misspelled option "useWrapMode"

### ISSUE THREAD

**Issue by 57even** [ajaxorg/ace#2358]
I set the `useWrapMode` option as follows

    var editor = ace.edit("editor");

    editor.setOptions({
        showPrintMargin: false,
        useWrapMode: true,
        useSoftTabs: true,
    });

but I get the error `misspelled option "useWrapMode"`. According to the docs it is the correct way to do it so I can't figure out why I get the error.

This works all fine:

    editor.session.setUseWrapMode(true);

**Comment by nightwing** [comment]
The correct way is to use `wrap: true` .
Which page says that `useWrapMode` is the correct way?

**Comment by Aybee** [comment]
This page does tell it https://ace.c9.io/#nav=howto
