### ISSUE TITLE
editor.curOp.command.name is not set when deleting lines with Vim keybinding

### ISSUE THREAD

**Issue by ylian** [ajaxorg/ace#2364]
I am using `editor.curOp.command.name` in my change event handler and it works quite well. There is only one issue: if I use Vim keybinding and delete lines with `dd`, somehow `editor.curOp.command` returns an empty object.

I am reading through the source code but would appreciate some pointers. Thanks.

**Comment by nightwing** [comment]
Vim mode doesn't use ace commands so it doesn't set any name on `curOp.command`.
What information do you want to get from command name? Vim mode sets `isVimOp = true` at https://github.com/ajaxorg/ace/blob/master/lib/ace/keyboard/vim.js#L1559 so can set other properties too.

**Comment by ylian** [comment]
Thanks. I am using `editor.curOp.command.name` to separate user changes from API changes, as suggested in #503.

**Comment by ylian** [comment]
I switched to the method in https://github.com/ajaxorg/ace/issues/1547#issuecomment-22257510 to separate user changes from API changes. This works fine with the Vim mode changes. Thanks.
