### ISSUE TITLE
Insert method triggers change before pushing changes to the undo stack

### ISSUE THREAD

**Issue by MrGuiMan** [ajaxorg/ace#2368]
Hi,

I'm trying to let my users handle undo / redo changes for the ace editor.

One of the means for them to actually change the content is to drag and drop element from the web page to the editor. 
However it seems that when i use the insert method of the ace editor (to insert content depending on what has been dropped on it), my changes are not pushed to the undoStack when the change event is triggered.

For that reason I can't really base the enabling / disable of my undo  button to the hasUndo() method.

Is there any specific reason why this behaves like this ? If so, what would you recommand ? 
My temporary fix was to force the enabling of the undo button  when a change is made, or check the undo stack if no state was forced.

**Comment by nightwing** [comment]
The timeout was needed before for managing when deltas are merged.
It is not needed anymore, and i am working on a patch to remove it.

**Comment by MrGuiMan** [comment]
Alright, I'll keep an eye out for a build including that change. 

Thanks a lot !

**Comment by sun2rise** [comment]
any news about this?

**Comment by monsieur42** [comment]
Hi there!

I found the same issue at cut event. Undo stack doesn't updated before cut event is triggered. Is there any workaround or solution?

**Comment by nightwing** [comment]
Hi 
the pull request for marking undo/redo button state is at https://github.com/ajaxorg/ace/pull/2966, however merging it was delayed, since it is not fully backward compatible.

If you want this for updating state of undo/redo/save buttons, use the editor input event instead

```js
    editor.on("input", function() {
        saveButton.disabled = editor.session.getUndoManager().isClean();
        undoButton.disabled = !editor.session.getUndoManager().hasUndo();
        redoButton.disabled = !editor.session.getUndoManager().hasRedo();
    });
```

and when saving call `editor.session.getUndoManager().markClean();`

**Comment by monsieur42** [comment]
Great! It works fine! Thanks a lot!
