### ISSUE TITLE
Relative position instead of absolute to fit in div

### ISSUE THREAD

**Issue by piller187** [ajaxorg/ace#2377]
I'm using this in a node-webkit project where I'm making an IDE. I'm trying to fit this inside the center div of http://layout.jquery-dev.com/demos/complex.html#

However it doesn't show up if I make it relative. It only shows on absolute. How can I make this work with relative? What would I need to change?

Thanks,
Rick

**Comment by nightwing** [comment]
Could you create a demo page demonstrating problem you see?
Recent versions of Ace use relative position by default.
So if your code works for a div it should work for Ace too, if you call editor.resize() when size of the div changes.

**Comment by piller187** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
<title>ACE in Action</title>
<style type="text/css" media="screen">
    #editor { 
        top: 0;
        right: 0;
        bottom: 0;
        left: 0;
		height: 100px;
    }
</style>
</head>
<body>
<div style="background-color: red; height: 800px; width: 100%;">
<div id="editor">function foo(items) {
    var x = "All this is syntax highlighted";
    return x;
}</div>
</div>
    
<script src="ace-builds/src-noconflict/ace.js" type="text/javascript" charset="utf-8"></script>
<script>
    var editor = ace.edit("editor");
    editor.setTheme("ace/theme/monokai");
    editor.getSession().setMode("ace/mode/javascript");
	
	editor.resize();
</script>
</body>
</html>


The outer div is much higher than the editor div, but the editor only keeps 100px as I defined in the css, which I have to give it an initial height with relative positioning or it doesn't show up at all. I would expect calling editor.resize() would size it to the outer div, but clearly I'm doing something wrong and not understanding.

Thanks for helping with this.

**Comment by nightwing** [comment]
Resize doesn't change height of the container element of the editor, it notifies editor that size of container have changed, to allow ace to update rendered text.

You need to set size of `<div id="editor"` to whatever you want same way as you would do for a normal div without editor.

E.g. add height 100% for inner div, use flexbox layout, set height with javascript, use position: absolute with `top:0; bottom:0` (note you don't need this if position is not absolute), use outer div as a container for the editor.

**Comment by piller187** [comment]
Ah I have a ton of nested div's so looks like I had to set height: 100% on html, body, and like 5 other parent divs and it seems to work now. Thank you.

**Comment by nightwing** [comment]
It might be better to set position relative only on the parent div that have correct height.

**Comment by piller187** [comment]
So I notice it only shows 36 lines total. So I added the following and then the height being 100% went away.

editor.setOptions({
			maxLines: Infinity
		});

If I'm not max screen the scroll bar doesn't go all the way down with the mouse wheel. It's like it's only scrolling for 36 lines even though there are more.

**Comment by nightwing** [comment]
maxLines is for automatically changing height of editor to match it's contents, it isn't useful with a layout you showed in the first comment.

Not matching number of visible lines and scrolling lines means size of the container was changed without calling `editor.resize()`

You can use http://jsbin.com/telatepawe/2/edit?html,output to experiment with ace and be able to show your code when asking questions.

**Comment by piller187** [comment]
"Not matching number of visible lines and scrolling lines means size of the container was changed without calling editor.resize()"

That makes sense because where the line numbers stop is about the height of when the node-webkit window opens but I have the below code and I get the alert so I would expect ace to resize correctly.

```var editor = ace.edit("editor");
var window = nw.Window.get();
		
window.window.addEventListener("resize", function(){
	alert("resize");
	editor.resize();
});
```

**Comment by nightwing** [comment]
I can't help you to debug it, without seeing it.
Overriding the global window looks like something that can cause problems, also please double check that container itself is resized correctly.

**Comment by piller187** [comment]
I used a jquery ui addin called layout to get an IDE look. Doesn't seem like it's an option on that JS Bin that I can see. So hard to duplicate it on that. I will play around with some stuff. The resize of ace was the biggest issue so thanks for that.

**Comment by nightwing** [comment]
You don't need option to include a library, using a script tag works
something like http://jsbin.com/dedinucaso/1/edit
Note that ace tracks window resize events by itself, you need to call resize only for size changes from your layout library

**Comment by piller187** [comment]
http://jsbin.com/hekoqupuso/1/

Open this with a smaller browser window. Then just hit enter a bunch of
times (like 50+). Then maximize the window and scroll and you'll see the
issue. Since yours works it must be something with the tabs I'm using.
However, in this the tabs aren't showing but in mine they are. But the same
bug is happening so maybe you can see why?

**Comment by nightwing** [comment]
There are two issues with your demo
1. you didn't add `onresize_end:function () { editor.resize(); }` to center element, as i showed in http://jsbin.com/dedinucaso/1/edit
2. you do not set the size of the container element correctly, try not calling ace.edit and see the element size is wrong

I've updated your jsbin to fix this issues. see http://jsbin.com/pipat/2/edit.
Note that this issue was not really about Ace but about other libraries you used

**Comment by piller187** [comment]
You are correct, I didn't see that. Between all these lines of code it was
hard to point out that one difference I guess. It is working now but I see
you changed to absolute and dropped the relative. I noticed if I go
relative when the scroll bar comes out by hitting enter a bunch of times it
pushes the tabs off which is odd. I'll use this for now but was thinking
relative would  better fit to the div container it's in 100%.

**Comment by nightwing** [comment]
You already had position absolute in the second style tag, so i kept it. You can't use height 100% on editor div, since you need it to leave 50px on top for the tabs. Ideally you should use jquery ui layout for the tabs too.

**Comment by piller187** [comment]
<div id="App.lua.content" style="padding: 0; margin-left: 0px;">
<div class="editor"></div>
</div>

Since the editor div is inside the tab content div I expected it to ONLY
play within that tab content div itself when 100%. But it bleeds into the
ul tab list as well. That's not what I would have expected I guess.

I didn't know ui layout had tabs. I'll check those out to see which I
prefer.

Thanks
