### ISSUE TITLE
vim mode substitution (find and replace)

### ISSUE THREAD

**Issue by gsf** [ajaxorg/ace#2378]
Really enjoying vim mode with the landing of everything in #2219. Great stuff.

One feature I think is still missing is substitution: `%s/foo/bar/g`. At least on Cloud9 I get "Vim command not implemented". This does work in CodeMirror.

**Comment by nightwing** [comment]
In cloud9 we had to modify vim mode to make it work with cloud9 cli and s is indeed not implemented yet.
Code for it, with changes not yet merged to Ace, is  at https://github.com/c9/core/blob/master/node_modules/ace/lib/ace/keyboard/vim.js and https://github.com/c9/c9.ide.ace.keymaps/tree/master/vim

**Comment by episodeyang** [comment]
Hi, is there any update on this? I just want to know if this is a bug of is just not implemented yet.

Thanks!

**Comment by altusgerona** [comment]
+1

**Comment by flotos** [comment]
Same here

**Comment by NikolasMelui** [comment]
Hey, guys, is anybody here?)
Does they fix the probloem?
very want to use :s in my container!

**Comment by pleshevskiy** [comment]
I add pull request with command "sed" :) https://github.com/c9/core/pull/468
