### ISSUE TITLE
CFML syntax highlighting issue

### ISSUE THREAD

**Issue by thdoan** [ajaxorg/ace#2382]
It's awesome that Caret supports syntax highlighting for ColdFusion, but it's not working when the CFML snippet is inside a JS script tag, e.g.:

```
<script>
<cfif 1>
alert(1);
</cfif>
</script>
```

Both the CF comment and the `cfif` tag are not highlighted correctly.

**Comment by nightwing** [comment]
Are tags like `<cfif 1>` allowed only in top level js or anywhere (e.g strings, comments)?
which other tags besides cfif are allowed inside script tag?

**Comment by thdoan** [comment]
CF tags like `<cfif>` can be embedded anywhere (inside HTML, HTML comments, JavaScript, JavaScript comments, and CF comments, which look like `<!--- ... --->`). You can escape the `<` using the standard HTML entity (`&lt;`), but then it wouldn't be a valid CF tag anymore. Since CF tags always start with "<cf...>", can you use that in the syntax highlighting rules?

**Comment by nightwing** [comment]
Thanks, that was helpful. Attached patch should fix this issue.

**Comment by thdoan** [comment]
@nightwing thanks a lot for fixing this so fast. I will test and close this soon.

**Comment by thdoan** [comment]
@nightwing I can confirm that PR #2626 fixes this issue, but there is still a minor syntax highlighting issue: the `<script>` tag is highlighted as if it were a CF tag, which is incorrect and can be confusing because CF has its own script tag (`<cfscript>`).

Ideally, the syntax highlighting should look something like this (screenshot taken from Notepad++ with [nppColdFusion](https://bitbucket.org/bbluemel/nppcoldfusion/wiki/Home) plugin):

![NPP screenshot](http://i.imgur.com/bpUAy9A.png)

This is what it looks like in Ace:

![Ace screenshot](http://i.imgur.com/n2OJKgw.png)

When you open a .cfm file in Notepad++, it's aware that .cfm files can have a mixture of HTML and CF tags, so all `<cf...>` tags such as `<cfif>` get highlighted using the ColdFusion lexer, and all HTML tags such as `<script>` get highlighted using the HTML lexer. If Ace is not able to use a combination of lexers in the same file, then I think it would be better to not hightlight non-CF tags such as `<script>` at all.

**Comment by nightwing** [comment]
>  the `<script>` tag is highlighted as if it were a CF tag

ace highlights all tags same way giving them meta.tag class, do you mean you want cf... tags to get another class, e.g keyword?

**Comment by thdoan** [comment]
@nightwing If it allows CF tags and HTML tags to be highlighted in different colors, then yes, I think it would be preferrable to classify CF tags under a different class.

**Comment by nightwing** [comment]
pushed a fix to #2626 .

**Comment by thdoan** [comment]
Thanks for the quick patch, @nightwing -- I confirmed that HTML and CF tags have different classes now.
