### ISSUE TITLE
Provide facility to 'throttle' autocompletions

### ISSUE THREAD

**Issue by kevinushey** [ajaxorg/ace#2383]
It would be useful if, instead of immediately displaying autocompletions after a keypress (for live completions), the popup display is instead delayed a number of milliseconds before display. This timer could be reset on each keypress as well, so as to avoid popping up (and potentially annoying the user) while they are typing.

FWIW, in RStudio we are currently using a very simple patch for this, with a little timer:

https://github.com/rstudio/ace/commit/b813945d5657c356054a1461e74239636728591a

Would it make sense to add something like this back into Ace, with an option to control throttling / the time before the popup is shown?

**Comment by nightwing** [comment]
Yes, it would be useful. I think there are several issues requesting this feature e.g https://github.com/ajaxorg/ace/issues/2209

**Comment by kevinushey** [comment]
It looks like this + https://github.com/ajaxorg/ace/issues/2209 are still open, if there's any appetite for adding this still.
