### ISSUE TITLE
Autocompletion-snippets bug?

### ISSUE THREAD

**Issue by arcassar** [ajaxorg/ace#2388]
Hi everyone,

I'm working on a project of web IDE using Ace editor for a DSL. I created a custom mode and syntax highlighting rules. Now i'm working on autocompletion.

So i created a new file for my snippets in my DSL. Everything works fine except one thing.

When I use a snippet with parameters in which I call another snippet, I have a strange behaviour. If the second snippet has parameters too, the first one is ignored. For your comprehension, here is an example : 

my snippets (part of my file) :

    ...
    snippet fi\n\
	    FirstSnip ${1} {\n\
		   ${2}\n\
	    }\n\
    snippet se\n\
	    SecondSnip ${1} {\n\
		      ${2}\n\
	     }\n\
    ....

and my code example : 

    ...
    FirstSnip ID {
           SecondSnip /*ignored*/ {
                     /*cursor comes here directly*/
                   }
    }
    ...

explanation  : I have two snippets with parameters. I call FirstSnip by typing "fi" and then pressing tab. So my cursor is in place to enter the first parameter (${1}) of FirstSnip. Then I press tab again and the cursor goes to the second parameter (${2}) of FirstSnip.
 Now here is the problem. In this ${2}, I enter "se" and press tab to generate SecondSnip. But the cursor DOES'NT go to the ${1} of SecondSnip. He goes directly to the ${2}.

So, my questions are : 
1) Is it a normal behaviour? Have I made a mistake in my snippet declaration? I took example on the javascript and html files to create my file.
2) Is it a real bug? I discover the same problem in the live demo in html here :
 http://ace.c9.io/demo/autocompletion.html
If you try with the snippet "article#" you'll see that you can't express a "ul" with parameters (snippet ul#) without the problem.
![code](https://cloud.githubusercontent.com/assets/11421609/6594135/d0cdcf6e-c7de-11e4-927a-ac8863c91acb.png)

About Ace, i'm working with the pre-built "src-noconflict" version available here : 
https://github.com/ajaxorg/ace-builds

I'm available to give extra information if needed. I hope someone has an answer to this beahviour of ace.

**Comment by nightwing** [comment]
This is indeed a bug, i'll try to fix it as soon as possible. Thank you for detailed bug report!
