### ISSUE TITLE
Broken search on Safari

### ISSUE THREAD

**Issue by asmforce** [ajaxorg/ace#2390]
Search function is broken on Safari 5.1.7 on a Mac.
There are several results, say, in Firefox, but there is no result in Safari.

**Comment by nightwing** [comment]
What exactly do you search?
Do you see any errors in console, i couldn't reproduce this on Safari 5.1.9 (the oldest version i could find on SauceLabs vm)

**Comment by asmforce** [comment]
The customer who reported me an issue just told that everything works fine on the new site layout (probably an actual version of the Ace Editor). So I'am going to close an issue.
Thank you for reply anyway.
