### ISSUE TITLE
Incorrect Rust highlighting when lifetimes are involved.

### ISSUE THREAD

**Issue by cjwelborn** [ajaxorg/ace#2394]
Ace highlights everything because of a lifetime.

Example code (where the ending `'t` is the lifetime causing the problem):
```rust
fn main()
{
    
    fn red_code<'t,T>(a:&'t T) where T:'t
    {
        println!("Let me be red!");
    }
    
    red_code(&3);
}
```

Example on rust-playpen (where it was noticed): http://is.gd/0BZZ2o

The issue was originally [reported to rust-lang](https://github.com/rust-lang/rust-playpen/issues/77).

**Comment by nightwing** [comment]
Should be fixed by https://github.com/ajaxorg/ace/pull/2397

**Comment by cjwelborn** [comment]
Thanks :)
