### ISSUE TITLE
Ace editor context menu missing copy paste options in Firefox

### ISSUE THREAD

**Issue by ajith** [ajaxorg/ace#2395]
Hi,
It seems the context menu on Firefox (tested on Both Mac and Ubuntu) is missing the copy / paste options. There is a well-known fact of firefox context menu event firing after the context menu is displayed but  https://github.com/ajaxorg/ace/issues/2081 implies that this should be taken care of, in the current Ace codebase.

As of now, if you load the ace kitchen sink (http://ace.c9.io/build/kitchen-sink.html) in Chrome vs Firefox  (I've tested on Chrome Version 41.0.2272.89 (64-bit) on Mac and Firefox ESR 31.5.0 on Mac), the context menu on Chrome presents the copy/paste options and Firefox does not.

**Comment by nightwing** [comment]
will be fixed by  https://github.com/ajaxorg/ace/pull/2397

**Comment by ajith** [comment]
Hi nightwing,
Thanks for this quick fix. It seems to have solved the issue for firefox, both on Mac and Linux. I noticed though that the behavior in IE is slightly weird now - the text momentarily moves to the cursor position and then comes back.

Perhaps the behavior change can be limited to Firefox using the userAgent?
