### ISSUE TITLE
emmet.js external resource is down

### ISSUE THREAD

**Issue by sevin7676** [ajaxorg/ace#2396]
https://nightwing.github.io/emmet-core/emmet.js

![image](https://cloud.githubusercontent.com/assets/5360920/6655701/aed404a2-cade-11e4-9dad-ae77863a9af9.png)

![image](https://cloud.githubusercontent.com/assets/5360920/6655704/bda2c34c-cade-11e4-850f-2f06e79a8fbc.png)

**Comment by nightwing** [comment]
Thanks for noticing, was broken when moving repository to cloud9ide org.
Old one is up now, and  https://github.com/ajaxorg/ace/commit/a78bf8e5efe88c81812e3e883c500ab209d1f9e5 updates links to the new repo
