### ISSUE TITLE
ES6 tagged template support missing (jshint update needed?)

### ISSUE THREAD

**Issue by wolframkriesing** [ajaxorg/ace#2400]
This http://tddbin.com/#?kata=es6/language/template-strings/tagged uses ACE (v1.1.8) from the CDN, and it seems that the jshint is outdated, since it warns about ES6 tagged templates (as you can see in TDDBin). I tried it on http://jshint.com/ with `// jshint esnext=true` and it seems to be supported.
Would be awesome if this gets updated, thanks a lot!

**Comment by nightwing** [comment]
updated in https://github.com/ajaxorg/ace/commit/bb16d65cbb78d8e04db0ce5d084e98bca5f46bd2

**Comment by wolframkriesing** [comment]
awesome, thank you!

**Comment by wolframkriesing** [comment]
Sorry if I may ask questions that are documented, I couldnt find it thoug :( ... how do your release cycles work? When will this change be in a build, or even better on a CDN?
