### ISSUE TITLE
Enable disabling of cross hair cursor on pressing the alt key (in multi select)

### ISSUE THREAD

**Issue by xixixao** [ajaxorg/ace#2401]
Multiselect implements block selection and [adds](https://github.com/ajaxorg/ace/blob/master/lib/ace/multi_select.js#L923) the behavior of showing a crosshair cursor when the user presses Alt. The way it's written it's not possible to disable it without disabling multiselect. There should be a way to disable this (at least via monkey-patching).

If you give me a pointer on how this should be done I'll make a PR.

The motivation is simple: I won't be using block select and want to reuse Alt-click for a different behavior.

**Comment by nightwing** [comment]
I am not sure how to best make configurable or generalize this feature.
We could add a way to set cursor for combination of modifier keys but maybe moving it to renderer and having a function to enable/disable it would be enough. [event.getModifierString](https://github.com/ajaxorg/ace/blob/master/lib/ace/lib/event.js#L225) function might be useful

**Comment by xixixao** [comment]
Alternatively we could have an option for enabling block select? This would mirror closer what I'm trying to achieve - I can imagine I would like to remove this particular cursor behavior but maybe add a different one, in which case I'm not sure how well the option in renderer would work.

**Comment by nightwing** [comment]
Option to disable block select is indeed better. 
We can add something similar to mousemaps in sublime allowing to bind to actions like 'Ctrl-Shift-MouseLeft-down'
Cloud9 similarly replaces action of ctrl key but in a hacky way https://github.com/ajaxorg/ace/blob/master/lib/ace/mouse/multi_select_handler.js#L83

**Comment by xixixao** [comment]
I use listener on 'click' and check for modifiers manually, that's fine enough for me.
