### ISSUE TITLE
Cannot disable showInvisibles when init Ace

### ISSUE THREAD

**Issue by lealife** [ajaxorg/ace#2402]
Line: https://github.com/ajaxorg/ace/blob/6a07619ad202a3e2752024f73c8cd7405c932158/lib/ace/layer/text.js#L348
If the code has space, it will run
```
 return "<span class='ace_invisible ace_invisible_space ace_invalid'>" + self.SPACE_CHAR + "</span>";
```
and will show invisible space.

In this line, it must judge whether showInvisibles is true or not:
```
return self.showInvisibles
                    ? "<span class='ace_invisible ace_invisible_space ace_invalid'>" + self.SPACE_CHAR + "</span>" :
                    lang.stringRepeat("\u00a0", c.length);
```

**Comment by nightwing** [comment]
Spaces are handled in the first if at [text.js#L328](https://github.com/ajaxorg/ace/blob/6a07619ad202a3e2752024f73c8cd7405c932158/lib/ace/layer/text.js#L328)

[text.js#L348](https://github.com/ajaxorg/ace/blob/6a07619ad202a3e2752024f73c8cd7405c932158/lib/ace/layer/text.js#L348) is for handling invalid characters like \xa0, \x00 etc
