### ISSUE TITLE
The copped text contains "\xA0" (not space, it's a another charactor)

### ISSUE THREAD

**Issue by lealife** [ajaxorg/ace#2403]
When copy the selected text, it will contains "\xA0", which is not the space " ". But when paste the copped text on Terminal, a error will be occurred because the "\xA0" is not a space.

solution:
https://github.com/ajaxorg/ace/blob/master/lib/ace/keyboard/textinput.js#L280
```
data = data.replace(/\xA0/g, ' ');
```

**Comment by nightwing** [comment]
How is `\xa0` added to the editor? If user pastes text with `\xa0` automatically changing it to space is an unexpected behavior.

**Comment by lealife** [comment]
"How is \xa0 added to the editor?", please see: https://github.com/ajaxorg/ace/search?utf8=%E2%9C%93&q=%5CxA0 , ace replace indent to "\xa0", I think it's not a good method.

**Comment by nightwing** [comment]
It is only for rendered text, not the text copied in [textinput.js#L280](https://github.com/ajaxorg/ace/blob/master/lib/ace/keyboard/textinput.js#L280)

I am not able to reproduce this issue on http://ace.c9.io/#nav=about.
Could you please give a link to a demo where spaces are replaced with \xA0 in copied text?

**Comment by lealife** [comment]
Thanks, I test it on http://ace.c9.io, it has fixed.
