### ISSUE TITLE
Where the source code ?

### ISSUE THREAD

**Issue by moodz** [ajaxorg/ace#2415]
when syncing or download zip file there is nothing in the build directory ???  that's where the source lives right ?

**Comment by nightwing** [comment]
Source lives in lib/ace directory, you can use that directly with require.js.
If you need built version you can run `git submodule update --init` to download ace-builds repository, or build ace yourself https://github.com/ajaxorg/ace/wiki/Building-ace

**Comment by nightwing** [comment]
Please comment if https://github.com/ajaxorg/ace/issues/2415#issuecomment-85612426 didn't answer your question.
