### ISSUE TITLE
What's the use of the Snippet file?

### ISSUE THREAD

**Issue by hanwencheng** [ajaxorg/ace#2422]
Hey, 

Thanks for the great editor!

I am trying to create a new mode according to some documents on [Ace API](http://ace.c9.io/#nav=higlighter) and [Ace Wiki](https://github.com/ajaxorg/ace/wiki/Creating-or-Extending-an-Edit-Mode), I have already build the mode file and the highlight_rule file, when I start to test it, the console give the error that the snippet file can't be found.

* I know the error could be solved by setting the `enableSnippets` attribute to false, but what exactly it does for ace editor? Do I need to implement my own?

* One other question is the I have found some test file in "mode" folder, e.g.`python_test.js`, how could I use these test file? Because the my syntax highlight rules does not function well, I am seeking a way to test it.

**Comment by nightwing** [comment]
Snippets file provides textmate like code snippets for the language, they are shown in autocomplete popup and can be expanded with tab key.
For testing see adding automated tests section of ace api page. files like python_test.js are tedious to write, and with automated test you need only to write some text and check if generated tokens are what you want

**Comment by hanwencheng** [comment]
Thanks!
