### ISSUE TITLE
Autom. fold html tag on open

### ISSUE THREAD

**Issue by klwemu** [ajaxorg/ace#2423]
Can i fold for example the "style" tag automatically on open?

![image](https://cloud.githubusercontent.com/assets/3965097/6850546/188be96a-d3da-11e4-82b6-d4df67e5cbf3.png)

**Comment by nightwing** [comment]
You can do something like [mode_creator.js#L77-L81](https://github.com/ajaxorg/ace/blob/a2e05ac438e9021d0858f3dffb51fbc2b719d812/tool/mode_creator.js#L77-L81), there are also other methods to [fold text](https://github.com/ajaxorg/ace/blob/a2e05ac438e9021d0858f3dffb51fbc2b719d812/lib/ace/edit_session/folding.js#L636) which might be more useful depending on what exactly you want to achieve.

**Comment by nightwing** [comment]
Please reopen if suggested solution didn't work or you have more questions.
