### ISSUE TITLE
Highlight both matching opening/closing bracket/tag

### ISSUE THREAD

**Issue by mortalis13** [ajaxorg/ace#2424]
Hi. Is it possible to perform this action when I place the cursor near the opening tag so that the editor highlights not only the opposite closing tag but also the current one?

Thanks.

**Comment by klwemu** [comment]
With keybord  Ctrl+Shift+P  - but i dont know (find) the right function call.

**Comment by mortalis13** [comment]
You mean Ctrl+P to go to the matching tag?

**Comment by mortalis13** [comment]
I guess it has relation to the `drawTextMarker()` function in `marker.js` line `104` or complied `ace.js` on `13305`.  
It prints one marker with class `ace_start`. And just should add the second one for the opposite html tag.

**Comment by nightwing** [comment]
highlighting matched brackets is done by https://github.com/ajaxorg/ace/blob/master/lib/ace/editor.js#L497, which calls https://github.com/ajaxorg/ace/blob/master/lib/ace/edit_session/bracket_match.js#L41

**Comment by klwemu** [comment]
@nightwing: how can i call $highlightBrackets. I want to highlight like Ctrl+Shift+P

**Comment by nightwing** [comment]
@klwemu Ctrl+Shift+P is not related to this issue, it is done by [jumpToMatching function](https://github.com/ajaxorg/ace/blob/a2e05ac438e9021d0858f3dffb51fbc2b719d812/lib/ace/editor.js#L2024). And [here](https://github.com/ajaxorg/ace/blob/a2e05ac438e9021d0858f3dffb51fbc2b719d812/lib/ace/commands/default_commands.js#L409) is the code which calls it.

**Comment by klwemu** [comment]
@nightwing Thank you very much! Your perfekt support helps a lot!!!

**Comment by mkslanc** [comment]
Fixed by #4947
