### ISSUE TITLE
Wishlist: Syntax highlighting for Template Toolkit

### ISSUE THREAD

**Issue by tombreit** [ajaxorg/ace#2426]
Any chance you package syntax highlighting for Template Toolkit? Some (standalone) editors already know about TT, perhaps an existing pattern could be converted for ace-editor?

**Comment by tombreit** [comment]
... forgot to mention "some" TT-enabled editors: http://template-toolkit.org/download/index.html#editors

**Comment by MattDees** [comment]
This would be extremely useful for me as well.

**Comment by RonKass** [comment]
Yep. Would be most desirable.

**Comment by nightwing** [comment]
The linked site has textmate grammars for tt2 tt3 and html+tt2/3 are all 4 of these used?
https://github.com/abw/Template-TT3 seems to be abandoned. Could you show some Template Toolkit files on github, that i can use for testing the highlighter?
