### ISSUE TITLE
ESC exits fullscreen

### ISSUE THREAD

**Issue by gsf** [ajaxorg/ace#2427]
See zedapp/zed#455 and dart-lang/chromedeveditor#3163. Is there a way to handle this in Ace so each of the wrappers don't have to solve the same problem?

**Comment by nightwing** [comment]
This is a security "feature" of chrome and cannot be handled by ace.
These chrome extensions will have to request permission for 

```json
        "app.window.fullscreen",
        "app.window.fullscreen.overrideEsc",
```
in their manifests and add code like

```js
window.onkeydown = window.onkeyup = function(e) { 
     if (e.keyCode == 27) e.preventDefault();
};
```
see https://code.google.com/p/chromium/codesearch#chromium/src/extensions/common/api/app_window.idl&q=app.window.fullscreen.overrideEsc&type=cs&sq=package:chromium&l=300

**Comment by gsf** [comment]
I was afraid that was the case. Thanks for the response.
