### ISSUE TITLE
setPolling(false) cannot turn off polling

### ISSUE THREAD

**Issue by nbdd0121** [ajaxorg/ace#2432]
Perhaps the code mean
```
 if (this.$pollSizeChangesTimer) {
    clearInterval(this.$pollSizeChangesTimer);
    this.$pollSizeChangesTimer = 0;
}
```
instead of
```
 if (this.$pollSizeChangesTimer)
    this.$pollSizeChangesTimer;
```
Since the latter one makes no sense at all.

What's more, probably we can use MutationObserver to replace the polling if supported

**Comment by nightwing** [comment]
Thanks for the bug report, i've added suggested fix to https://github.com/ajaxorg/ace/pull/2459.
> What's more, probably we can use MutationObserver to replace the polling if supported

Does MutationObserver allow to detect when size of element is changed due to zoom or font style change? AFAIK it should be only for attribute or children modifications.

**Comment by nbdd0121** [comment]
> Does MutationObserver allow to detect when size of element is changed due to zoom or font style change? AFAIK it should be only for attribute or children modifications.

MutationObserver can be used to detect inline style change, ex. the style attribute or setting of style via JavaScript. However style sheet changes and zoom will not be detected. So you are right, we shouldn't use it.

**Comment by felicienfrancois** [comment]
[CSS Element queries](https://github.com/marcj/css-element-queries) uses a event based approach for size change detection
```
new ResizeSensor(jQuery('#myElement'), function() {
    console.log('myelement has been resized');
});
```

It uses a invisible new element as an overlay on the desired target and utilize the "scroll" event on the overlay to trigger changes

Could be a solution ...
