### ISSUE TITLE
invalid file generated by dryice build when given a browserified file

### ISSUE THREAD

**Issue by chmontgomery** [ajaxorg/ace#2433]
I'm attempting to add a new worker js file, in this case for gherkin.

Specifically, I ran browserify against this set of files: https://github.com/cucumber/gherkin3/tree/master/javascript/lib/gherkin

Then, I took the browserify bundle, put it under `\lib\ace\mode\gherkin\` and ran the ace build like so: `node ./Makefile.dryice.js full --target ../ace-builds`. After doing so, the build finishes with no errors and outputs invalid `worker-gherkin.js` files.  For example, `src-noconflict/worker-gherkin.js` has the following invalid lines: `function ace.define(name, deps, m) {`. When I try to load it in the browser, I get these failures:
![screen shot 2015-04-01 at 8 57 05 am](https://cloud.githubusercontent.com/assets/232356/6942954/8a735a02-d850-11e4-9ee9-4fbf50cfdd76.png)

`src/worker-gherkin.js` does not load in the browser either. It throws the following errors:
![screen shot 2015-04-01 at 8 55 48 am](https://cloud.githubusercontent.com/assets/232356/6942972/9f47df2a-d850-11e4-9e11-c91ed5b4a845.png)

Is this simply a limitation with dryice or how you've implemented it? I noticed the other worker files (csslint, json_parse, jshint, etc) are pre-wrapped with amd syntax. Is this an expectation? The strange thing is, if I wrap my browserified bundle with amd it still doesn't work. The only way I was able to get dryice to build my files properly was to have them as their original src files, wrapped with amd syntax, as seen in this PR: https://github.com/ajaxorg/ace/pull/2429.

At the end of the day, I would prefer to provide a browserify bundle instead of the loose src files.

**Comment by nightwing** [comment]
You can use derequire to make browserify to work in the second case.
The first issue is a bug in https://github.com/ajaxorg/ace/blob/master/Makefile.dryice.js#L474

**Comment by chmontgomery** [comment]
@nightwing thanks for the response. Ya that's what I was seeing.
