### ISSUE TITLE
Release 1.1.9 tag

### ISSUE THREAD

**Issue by mstorus** [ajaxorg/ace#2434]
I'm waiting on a 1.1.9 tag to fix an issue with an external library that has Ace as a dependency.

Ace had an issue where it was using a reserved JavaScript keyword as a variable name, which was fixed here:
https://github.com/ajaxorg/ace/pull/2275
but is not included in any tagged version yet.

A library called Brace uses Ace by referencing a tag number:
https://github.com/thlorenz/brace/blob/886d4ba0804a048c3f5cfb540c660e034adc496f/build/update.js#L22

Publishing 1.1.9 would include the https://github.com/ajaxorg/ace/pull/2275 fix, enabling me to update brace to fix this issue: https://github.com/thlorenz/brace/pull/16

**Comment by thlorenz** [comment]
[Ditto](https://github.com/thlorenz/brace/pull/16#issuecomment-88997314)

**Comment by nightwing** [comment]
Sorry for the long delay, added tags for v1.1.9 just now.
https://github.com/ajaxorg/ace/releases/tag/v1.1.9 
https://github.com/ajaxorg/ace-builds/releases/tag/v1.1.9

**Comment by mstorus** [comment]
for reference, brace was updated here
https://github.com/thlorenz/brace/pull/28
