### ISSUE TITLE
Text selector/selection off to the right

### ISSUE THREAD

**Issue by lauritzt** [ajaxorg/ace#2436]
I've made a 1 minute video demonstrating this: http://youtu.be/d61ko-D6wE4
I use Firefox 39.0a2 (2015-04-04) on Windows 8.1.
This bug is also present in Chrome 40.0.2214.111 m with all extensions disabled.
I have no idea what causes the bug, and it is present as soon as Ace is loaded.

**Comment by nightwing** [comment]
Currently ace works only with monospace fonts, but the font in the video is not monospace.
Try finding which css rule on that page changes the font to non-monospace one.

**Comment by LauritzT** [comment]
Okay, thanks.
