### ISSUE TITLE
Auto Complete with the same caption

### ISSUE THREAD

**Issue by hanwencheng** [ajaxorg/ace#2437]
Hi, 

I am implementing a customed auto completer, here I have some words with same caption but with different meta information, how could I make them popping up together?

for  example, the words array I give is something like 

    {
        name: "centralStreet", value :"centralStreet", score:100, meta:"berlin"
        name: "centralStreet", value :"centralStreet", score:100, meta:"amsterdam"
    }

**Comment by nightwing** [comment]
Completions inserting same thing are filtered in https://github.com/ajaxorg/ace/blob/master/lib/ace/autocomplete.js#L440

there is no simple way to disable that, but you can set insertmatch hook on completer like this
```js
editor.completers[0] = ({
    getCompletions: function(a, b, c, d, e) {
        e(null, [{
            caption: "centralStreet",
            snippet: "centralStreet berlin",
            score: 100,
            meta: "berlin",
            completer: this
        }, {
            caption: "centralStreet",
            snippet: "centralStreet amsterdam",
            score: 100,
            meta: "amsterdam",
            completer: this
        }])
    },
    insertMatch: function(editor, data) {
        editor.forEachSelection(function() {
            editor.insert(data.caption)
        })
    }
})
```

**Comment by hanwencheng** [comment]
Hi, Harutyun,

Thanks a lot. Now I see where the filter is.

I add a snippet property as you said, without overriding the insertMatch, and it works!

    editor.completers[0] = ({
        getCompletions: function(a, b, c, d, e) {
            e(null, [{
                caption: "centralStreet",
                snippet: "centralStreet:berlin",
                score: 100,
                meta: "berlin"
            }, {
                caption: "centralStreet",
                snippet: "centralStreet:amsterdam",
                score: 100,
                meta: "amsterdam"
            }])
        }
    })

**Comment by nightwing** [comment]
That change will break other completers, because caption is a string to display in the popup and snippet is a textmate style snippet. So that won't work as you expect if caption is anything with `$` e.g `$1foo`
> Because the insertMatch hook is not simple to implement, 

Why is it not simple? it's only 3 lines

**Comment by hanwencheng** [comment]
Because the insert function is just insert the whole word.

for example. if I input "centra", then choose the first pop up word "centralStreet", it will show "centracentralStreet" in the editor.

Here is my code

```javascript
    function enableAutoComplete(){
        var completer = {
            getCompletions : function(editor,session,pos,prefix,callback){
                if (prefix.length === 0) { callback(null, []); return }
                var result = editor.autoCompleter.searchWord(prefix);//get the pop up elements array
                var that = this;
                result = result.map(function(element){
                    element["completer"] = that;
                    return element;
                });
                console.log("prefix is" , prefix, "pos is : " , pos);
                callback(null, result); 
            },

            insertMatch: function(editor, data) {
                editor.forEachSelection(function() {
                    editor.insert(data.caption);
                })
            }
        };
        langTools.addCompleter(completer);
    }
```

**Comment by nightwing** [comment]
You are right, it is more complex than i thought.
But you can use defualt insertMatch implementation from your custom one, like this:
```js
insertMatch: function(editor, data) {
    editor.completer.insertMatch({value: data.caption})
})
```

**Comment by nightwing** [comment]
@hanwencheng please comment if suggested method doesn't work for you.
