### ISSUE TITLE
Text is cut off

### ISSUE THREAD

**Issue by zwhitchcox** [ajaxorg/ace#2438]
I don't know if anyone else has this problem. Seems pretty glaring to me, which usually means I'm doing something wrong. Anyway, the text is cut off, and there's no horizonal scroll in the editor. On the plus side, vertical scroll works great :+1:. The editor also adjusts to the right size, but it just cuts off the text and doesn't wrap it or anything.

Anyway, this is the code I'm using:
```js
    editor = ace.edit("editor")
    editor.setValue(mycode,1)
    editor.getSession().setMode("ace/mode/python")
    editor.setTheme("ace/theme/eclipse");
    editor.setKeyboardHandler("ace/keyboard/vim")

**Comment by nightwing** [comment]
Most likely cause of this is that editor is not notified about a change of it's containers size.
If you are changing size of the container element after creating the editor you should call `editor.resize() `

**Comment by zwhitchcox** [comment]
You were right. I did call it when I resized the editor, but I didn't call it upon typing which caused the editor to expand. It would be great if there were some type of wrap function though. I tried set wrap mode and stuff, but it didn't work

**Comment by nightwing** [comment]
> but I didn't call it upon typing which caused the editor to expand.

could you show me the app you are working on or a demo? it only needs to be called after resizing.

>  I tried set wrap mode and stuff, but it didn't work

what did you try? if `editor.setOption("wrap", true)` doesn't work, then editor size is still wrong.

**Comment by zwhitchcox** [comment]
Ok, well, that probably would have worked, but I just didn't know you had to do editor.getSession().setUseWrapMode(true), and I just did editor.setUseWrapMode(true). I don't really know why, but that totally fixed my problem. Thank you!

**Comment by zwhitchcox** [comment]
Ok, and I also tried ```editor.setOption("wrap",true)```, and that also worked.
