### ISSUE TITLE
Incorrect syntax highlighting for Rust function declaration

### ISSUE THREAD

**Issue by niconii** [ajaxorg/ace#2441]
To reproduce, it's as simple as typing:
```rust
fn main() {}
```
The problem is not visible in a few styles (including the default), but in e.g. Chaos, Cobalt, Terminal, and many others, the `(` is shown in a different color from the `)`.

**Comment by niconii** [comment]
Also, highlighting doesn't work on one-character function names.
```rust
fn a() {}
```

**Comment by nightwing** [comment]
Thank you for the bug report. 
This will be fixed by https://github.com/ajaxorg/ace/pull/2461
