### ISSUE TITLE
Changing themes overrides font-size setting

### ISSUE THREAD

**Issue by mohsen1** [ajaxorg/ace#2442]
When I change the theme, the font-size setting is being reset to theme's default. 

This issue was raised here: 
https://github.com/swagger-api/swagger-editor/issues/399

**Comment by nightwing** [comment]
You have a css rule `.ace-atom-dark {  font-size: 16px; }` which is obviously applied only to ace-atom-dark theme.
Either set style for `.ace_editor` class or use `setOption("fontSize", 16)`

**Comment by mohsen1** [comment]
Thanks @nightwing that was it!
