### ISSUE TITLE
Bold and italic together don't work in asciidoc

### ISSUE THREAD

**Issue by victorel-petrovich** [ajaxorg/ace#2443]
According to http://asciidoctor.org/docs/user-manual/#bold-and-italic, if one writes  `*_word_*` then it renders as **_word**_ . However, that fails to be highlighted accordingly in ace editor, per my try in Caret, Ra, Zed editors (all based on ace).  
(I also tried other orders of the `*` and `_` markers  around the word, none worked. )

**Comment by RickStrahl** [comment]
Same is true in the Markdown editor...

if you have:

```markdown
* ***bold and italic*** the editor will only show this as bold.
```
Looking at the generated HTML we can see that only `ace_strong` has been applied.

![image](https://user-images.githubusercontent.com/1374013/67259302-c7d8ea00-f430-11e9-8bc4-2ba6e3424a80.png)

It's a minor thing honestly, but a number of people using the editor I've created have commented on that particular issue. 

This likely comes from the regEx here in `mode-markdown`, but after looking this over for a bit I don't see a good way to fix this:

```js
 { // strong ** __
            token : "string.strong",
            regex : "([*]{2}|[_]{2}(?=\\S))(.*?\\S[*_]*)(\\1)"
        }, { // emphasis * _
            token : "string.emphasis",
            regex : "([*]|[_](?=\\S))(.*?\\S[*_]*)(\\1)"
        },
```

**Comment by RickStrahl** [comment]
On second thought this works, but it's probably not a very reliable way to do this:

```js
 { // strong ***
            token : "string.strong.emphasis",
            regex : "([*]{3}|[_]{3}(?=\\S))(.*?\\S[*_]*)(\\1)"
            },
```
