### ISSUE TITLE
Mac OS, select some text, right click, services > Search with Google

### ISSUE THREAD

**Issue by tylerlong** [ajaxorg/ace#2446]
Mac OS, Open http://ace.c9.io/build/kitchen-sink.html , select some text, right click, services > Search with Google

![screen shot 2015-04-12 at 3 56 22 pm](https://cloud.githubusercontent.com/assets/733544/7104817/84b24ac6-e12c-11e4-9b8b-56dc0fbbcbc2.png)

No matter what you select, a qestion mark '?' is searched instead.

The issue was originally reported here: https://github.com/tylingsoft/markdown-plus/issues/30

**Comment by nightwing** [comment]
This have been fixed by https://github.com/ajaxorg/ace/pull/3635
