### ISSUE TITLE
The editor is inaccessible to screen reader users

### ISSUE THREAD

**Issue by sukiletxe** [ajaxorg/ace#2447]
I am finding that more and more sites areswitching to the ACE editor for its features; however, as I am a screen reader user, I can't use it. According to my screen reader, which is [nvda](www.nvaccess.org), the editor's text doesn't appear in the edit field, the edit field appears blank and the text appears just below it, rendering the edit field unusable.

**Comment by nightwing** [comment]
merging into https://github.com/ajaxorg/ace/issues/2164
