### ISSUE TITLE
Ctrl+Shift+U (to lower case) don't work on linux Ubuntu

### ISSUE THREAD

**Issue by felicienfrancois** [ajaxorg/ace#2448]
Ctrl+Shift+U is a already binded key on ubuntu (Unicode hotkey) and so it breaks ace bindings.

I don't know what should be done
- Change the default shortcut ?
- Document the issue and workarounds ?
  http://superuser.com/questions/358749/how-to-disable-ctrlshiftu-in-ubuntu-linux
- Find a fix to make it working (don't know if it's really possible)

**Comment by nightwing** [comment]
Should we add a special set of keybindings for linux?
There are other keybindings that are often unavailable there like alt click, or ctrl-alt-arrow https://github.com/ajaxorg/ace/issues/2150

**Comment by felicienfrancois** [comment]
@nightwing that's probably the best option considering the number of shortcuts that don't work on linux.

**Comment by bharat-kishnani** [comment]
Do we have a solution for this?
