### ISSUE TITLE
change event triggered multiple times when pasting a mulitline string

### ISSUE THREAD

**Issue by BuildingJarl** [ajaxorg/ace#2450]
When pasting a sting containing a new line character the change event is fired multiple times. Is this normal?

e.g. when pasting this: 
```
"Hello
my name is 
Jimmy" 
```

the change event get triggered 4 times.

**Comment by nightwing** [comment]
This is partially intentional, change event is not guaranteed to fire only once per user action.
What are you trying to do, there might be another event better suited for your usecase.

**Comment by BuildingJarl** [comment]
Oh ok I see. I was able to fix my issue using another event. Just wanted to make sure that this behaviour was intentional. Thanks

**Comment by rtorcato** [comment]
which event is better to use in this case? I would like to paste text without having multiple change events. I don't see an event to let me know when the entire document has changed.

**Comment by nightwing** [comment]
`editor.on("input"` might be better

**Comment by rtorcato** [comment]
i didn't see this on the documentation. I'll try it out thanks
