### ISSUE TITLE
Web Worker's path setting

### ISSUE THREAD

**Issue by hanwencheng** [ajaxorg/ace#2451]
Hi, 

As my ace folder is under `js/vendor/ace`, but I can't access some grammar file in `js/vendor/antlr` in the worker file `myLang_worker.js`. Even though I disable the Chrome's same domain security with `--disable-web-security`

        var Compiler = require("../../antlr/compiler");

it always locate to `ace/worker/antlr/compiler.js` or `ace/antlr/compiler.js`

I checked this [Syntax Validation Page](https://github.com/ajaxorg/ace/wiki/Syntax-validation), and set the workerPath to "vendor" or "js" or "vendor/js/ace", it seems that make no difference. What exactly does this workerPath do ? Is it related to this problem?

Thanks in advanced

Hanwen

**Comment by nightwing** [comment]
when creating worker pass `vendor` as one of top level namespaces see https://github.com/ajaxorg/ace/blob/master/lib/ace/worker/worker_client.js#L55
ace will call require.toUrl and use result to load files from that path

**Comment by hanwencheng** [comment]
Thanks, I see, I am still confused about this statement

> In packaged version path to the folder with worker-* files can be configured with

    require("ace/config").set("workerPath", "path/to/ace");

The function works correctly even though I did not set this.

**Comment by nightwing** [comment]
By default ace searches for ace.js script on the page and uses it's path as workerPath https://github.com/ajaxorg/ace/blob/master/lib/ace/config.js#L181, setting it explicitely is only required if workerPath is different or scrip is missing (e.g when loading ace as a part of a larger bundle)

**Comment by hanwencheng** [comment]
Thanks, I added the explanation to [Syntax Validation Page](https://github.com/ajaxorg/ace/wiki/Syntax-validation).
