### ISSUE TITLE
Error "Cannot read property 'document' of undefined" when uglifying src-noconflict

### ISSUE THREAD

**Issue by petesaia** [ajaxorg/ace#2468]
It seems as though when using the default configurations while minfying (attempting the already minified as well) the noconfict-src ace.js this error is thrown. I'm using the #master version via bower.

The issue is here at `global.document`:

```javascript
init(true);function init(packaged) {

    options.packaged = packaged || require.packaged || module.packaged || (global.define && define.packaged);

    if (!global.document)
        return "";
```

Update:

This only happens when minfied with other libraries. I imagine there is some sort of leaking var (global) that doesn't play nice. However, it works when I include it seprately.

**Comment by nightwing** [comment]
Uglifier probably adds a gloabl use strict which breaks https://github.com/ajaxorg/ace/blob/master/lib/ace/config.js#L41, I'll add a fallback similar to https://github.com/ajaxorg/ace/blob/master/build_support/mini_require.js#L42
