### ISSUE TITLE
[Snippets] [Unfinished] Multiple choice variables not working in snippets.

### ISSUE THREAD

**Issue by Tyf0x** [ajaxorg/ace#2471]
I don't know how feasible but I think it would be a great addition to the snippet language tool.

Something like:

```
snippet color
    Color.${1|red,green,blue|}
```

would give:

![shot 27-04-2015 10 20 09](https://cloud.githubusercontent.com/assets/6980921/7340055/d79e2b46-ecc7-11e4-9d31-09cd0f0d8e7e.png)

You can see the description on the [chapter 6.9](http://manual.textmate.org/snippets.html#multiple-choices) of the textmate manual.

**Comment by Tyf0x** [comment]
Looking into the code, it seems there is traces of support of the above behavior [here](https://github.com/ajaxorg/ace/blob/master/lib/ace/snippets.js#L100).

But nothing happens in my tests.
Did I do something wrong or is it a bug (or maybe an unfinished feature)?

**Comment by nightwing** [comment]
Yes this is an unfinished feature, parser understands the syntax, but code to trigger autocomplete popup is missing

**Comment by Tyf0x** [comment]
Thanks for your clarification.

Is there any chance of this being implemented?

I'm very unfamiliar with the code base but it seems that the needed popup is in the autocomplete section/folder. Does this mean that including a popup in the snippet code would require making dependencies across modules? Is there a clean way to do this?

Thank you

**Comment by Tyf0x** [comment]
I've hacked my way through this and got something somehow working. 

It's quick and dirty, but I still post a link to my changes just in case anybody is interested in it.

https://github.com/Tyf0x/ace/tree/snippet/multiple_choices_placeholder

**Comment by SAnDAnGE** [comment]
Any feedback on implementing this ?
