### ISSUE TITLE
Ace doesn't work well with CSS zoom

### ISSUE THREAD

**Issue by dharesign** [ajaxorg/ace#2475]
Steps to reproduce (In Chrome):
1. Go to http://ace.c9.io/build/kitchen-sink.html
2. Bring up the Chrome inspector
3. Add `zoom: 1.5;` to the `body` element.
4. Try to select a word in the editor.

**Comment by nightwing** [comment]
This is somewhat related to #1859 and #2406.
When zoom is different from 1, values from `MouseEvent.clientX` and `getBoundingClientRect().left` differ by a factor and something like https://github.com/nightwing/ace/commit/2e83080e1225c0381f0fdc4310ff420b0cc1ea34 is required. However i don't know if there is a good way to find zoom value for an element.

**Comment by frutiger** [comment]
Perhaps this function could help?

```js
function getZoom(element) {
  if (!element) return 1;
  return window.getComputedStyle(element).zoom * getZoom(element.parentElement);
}
```

**Comment by Gottox** [comment]
offset[XY] and layer[XY] are translated through the matrix. switching from clientX to one of those would fix not only zoom but all css translations.

**Comment by dharesign** [comment]
Any chance of getting a fix for this?

**Comment by Gottox** [comment]
@dharesign: I worked around this issue by moving ace into an iframe.

**Comment by jm-developer** [comment]
I worked around this by setting 0.8 zoom not on the body but on an div. ace editor seems to work fine when zoom is not set on body element.

**Comment by ashitvora** [comment]
Looks like this issue still persists. Any solution for this except for moving it to iframe?

**Comment by nightwing** [comment]
We can add a cssZoom setting to ace like this https://github.com/ajaxorg/ace/compare/zoom,
but it won't check for zoom changes automatically, and will require setting the option every time value  of zoom property changes.
Would that be useful?

**Comment by Gottox** [comment]
how is the performance impact if the zoom property would be calculated in the listeners directly?

**Comment by Gottox** [comment]
Also this proposal fixes only zoom with `transform-origin: left top;` if I understand it correctly.

**Comment by nightwing** [comment]
Impact on mousedown is small, but on mousemove is more noticeable on slow hardware.

This only fixes css zoom attribute as described in the issue report.
Which is a non-standard property and requires special handling even with offset[XY]

Supporting transforms requires either using a matrix instead of single zoom value, or offset[XY], but offset[XY] doesn't work well when dragging mouse outside of the editor where position relative to editor can not be recovered from the offset of the target node.

**Comment by gchallen** [comment]
Sorry to bump this old thread, but is there any intention of supporting this at some point in Ace? It looks like there's an unmerged zoom branch, so I'm curious about whether that's headed for master at some point.

My use case is integrating code writing exercises into the [slides for my introductory CS course](https://cs125.cs.illinois.edu/learn/moreconstructs/). I'm using bespoke.js as the base slide framework, and it uses CSS zoom (or transform) to scale the slides. Which works brilliantly for everything except the code editor, necessitating a nasty workaround.

I'm using CodeMirror at the moment, but would happily switch to Ace if this feature is every supported. Our current approach just scales the font size and line height for editor slides, which works but still leaves the CodeMirror mouse pointer a bit ganky at first. Somehow this settles out once you start interacting with the examples. But anyway, I'm someone who is eagerly awaiting one of the in-browser code editors to support this feature 😄.

**Comment by Gottox** [comment]
@gchallen I worked around the issues and wrote a small reveal plugin that allows including ace. Maybe this helps:

https://github.com/Gottox/reveal.js-ace

[demo](http://gottox.de/reveal.js-ace/)

**Comment by gchallen** [comment]
@Gottox: thanks! I already have a way to include CM, but it would be nice if zoom was explicitly supported. What did you do to work around this? (I'm not using reveal.js, so can't use your plugin directly...)

**Comment by Gottox** [comment]
@gchallen I just put the editor in its own iframe. Then the translations of events/positions are working correctly.

**Comment by gchallen** [comment]
@Gottox: OK, thanks. At least I know that's possible. I have some concerns about that approach, since the whole point of what we're doing is not just live editing but also being able to run code live and inspect the results. I'm sure I could accomplish this with an iframe-based solution, but it would require splitting out the functionality that's currently present in a single page in a way that I'd find somewhat ugly. I'd also be worried that this would affect performance. We use a lot of these examples, and loading them into separate iframes means that they can't share required state and libraries.

Anyway, thanks for the tip 👍

**Comment by nightwing** [comment]
@gchallen are you planning to use css zoom or transform, support for css zoom relatively simple, but that property is deprecated and not implemented on firefox. Support for transform is a bit more complicated and takes the most of the code in https://github.com/ajaxorg/ace/compare/zoom

**Comment by gchallen** [comment]
@nightwing: OK, I hadn't realized that zoom was deprecated. (This is why my slides don't work on Firefox.) bespoke claims to also support transform, which I'll transition to. So I'm planning to move to transform as soon as possible, but would stick with zoom if I could get support for it faster. (My students have figured out that only Chrome works, which is sadness but also the result of a tiny and overstretched web development "team". 🙂)

**Comment by nightwing** [comment]
It turns out you can already use css zoom with ace,  by applying a tiny bit of monkeypatching:

```js
function override(object, prop, replacer) { 
    var old = object[prop]; object[prop] = replacer(old)  
}
function getZoom(element) {
   if (!element) return 1;
   return window.getComputedStyle(element).zoom * getZoom(element.parentElement);
}
override(editor.renderer, "screenToTextCoordinates", function(old) {
    return function(x, y) {
        var zoom = getZoom(this.container)
        return old.call(this, x/zoom, y/zoom)
    }
})
```

thanks to @frutiger for the idea about getZoom

**Comment by Whadup** [comment]
I still need the monkeypatch today?

Furthermore, besides zoom, there is also transform: scale() that is not covered by the monkey patch.

**Comment by mattwilson888** [comment]
Found a minimal solution. You can scale the whole web page with `zoom` in an html tag. Scaling the ace editor by the inverse will cancel out the effects, and fix the mouse tracking error; finally,  scaling down the font size of the editor by the same amount of the overall zoom makes everything (at least in my case) appear normal, scaled down, and without any mouse misplacement glitches. 

```css
html {
    zoom: 80%;
    / 100% * (4/5)
}

 .ace_editor {
     font-size: 12px!important;
     / 15px * (4/5)
}

.ace_container {
    zoom: 125%;
    / 100% * (5/4)
}```
