### ISSUE TITLE
I created an extension: Image/video URL previews within Ace. What do you think?

### ISSUE THREAD

**Issue by akumpf** [ajaxorg/ace#2478]
Hi there,

I've been experimenting with adding URL previews for recognized file types within Ace. I'm calling it **FreeSpace Previews** since it's really about taking advantage of the unused space around text/code to show useful visual content -- the code itself remains unaltered.

Right now the extension just detects images and youtube URLs (just for testing; of course there could be lots of preview types eventually), but I can imagine it'd be super handy for all kinds of editors. For example, imagine you want to see a diagram or embed a video to explain something without adding bloat to the code by just copying in a URL and giving it a few blank lines to display? 

Currently the extension I've been working on adds a preview layer to ace's rendering layer stack to show embedded visual information in the free space below a link (if available). Links are assumed to be anything that the tokenizer labels as "link" (which not many support, but it'd be pretty easy to add to common editing modes if there's interest).

I've posted a super basic example so you can see for yourself and play with it here.
http://fs_previews.kumpf.cc/

And here's a quick screenshot.
![fs_previews](https://cloud.githubusercontent.com/assets/243480/7440959/f1f3fcce-f0d1-11e4-98ed-c68eb2e75744.png)

What do you think? Any interest is bringing something like this into the codebase? 

I'm happy to fork and submit a pull request if that's helpful.

**Comment by victorel-petrovich** [comment]
Hi Adam,

this is wonderful! ("FreeSpace preview" is not very clear to me from title what it does: maybe you can call it "FreeSpace URL preview")

I'm all for it! So, do you think it will work with Markdown, Asciidoc modes, that do recognize links?

Victor

**Comment by nightwing** [comment]
This is quite interesting, though i am not sure if we should add it to the core, or find some solution for making it easy to use and maintain independent extensions.
@akumpf do you want to add the ONB mode or general extension for rendering previews?

**Comment by imShadow** [comment]
Cool ! mark

**Comment by rocketinventor** [comment]
Would it be possible to make it on hover only?
I like the concept but, I can't help but feel that it is a gimmicky feature for the most part.
It could be an option or, a view mode. Maybe it should just be a plugin.
It seems like it it would be really awesome for markdown, though. If it could support github style markdown (and create space for the images even if there is no empty lines), that would be super rad.
Also, I noticed a bug that if the url isn't visible, the image disappears from the blank space.

**Comment by fastorga** [comment]
Excellent work! How I can implement this in my Ace Editor?
