### ISSUE TITLE
Corrupt output on long minified code

### ISSUE THREAD

**Issue by prettydiff** [ajaxorg/ace#2480]
Demo:

http://prettydiff.com/ignore/testlocation/index.php?s=http://prettydiff.com/api/dom.js&m=minify

The sample code can be found at http://prettydiff.com/api/dom.js

The setValue method appears to normally convert &, <, and > characters to entities, but here is a case where this does not occur. I can manually adjust the editor to convert the characters in question, but this breaks the output when dealing with smaller input that does not have this problem.

**Comment by nightwing** [comment]
Strangely `document.body.innerHTML="]]>"` throws an error in in xml documents, but works for html documents. Could you convert prettydiff.com to html or serving it as xml have some advantages?

**Comment by prettydiff** [comment]
My tool is most popular among XML enthusiasts. Serving the actual tool itself as XML allows me to identify corrupted output so that I can reverse engineer the problem if I know the user's input. If I served the tool as HTML many potential problems would slip through unnoticed.

If the problem is isolated to "]]>" then I can manually convert it as follows:

    editor.setValue(output.replace(/\]\]>/g, "]]&gt;"));
    if (editor.getValue().indexOf("]]&amp;gt;")) {
        editor.setValue(output.replace(/\]\]&amp;gt;/g, "]]&gt;"));
    }

This seems really hacky though.

**Comment by prettydiff** [comment]
If you point to the general area of the source code where this logic is performed I could work on it and submit a pull request.

**Comment by nightwing** [comment]
The trick with replaceing ]]> on setValue won't work since people copying or editing text will get escaped > which can lead to data loss.
https://github.com/ajaxorg/ace/commit/b7cd1e9d4c9cef3789363bb741ee9f4180d47ab6 can fix this issue, but i am not convinced that it is the right way to solve the issue. E.g a way to turn off weird xml mode for ace container element would be a much better solution.

**Comment by prettydiff** [comment]
b7cd1e9 does not work.

Consider this input:

    <json:agent type="Interstitial" var="interstitialAgent" />
		<url:link style="medium" cmsNode="airResultsCard.selectLink" useQueryString="true" agent="${interstitialAgent}" dataContext="selectButton">
			<url:linkAddParam name="selectKey" value="${renderParam.priceContainer.key}" />
			<url:linkAddParam name="userRate.price" value="${renderParam.priceContainer.userDisplayedRate.price}" />
		</url:link>

You can try it on http://prettydiff.com/

**Comment by nightwing** [comment]
You are talking about b7cd1e9 with the typo fixed right? I am not seeing any of the issues you describe with the demo/xml.xml added in  https://github.com/ajaxorg/ace/commit/7a8f20383dbb8fa0b3b02842051d49a8f128b5b8

**Comment by prettydiff** [comment]
Try using the *exact* contents of this file: http://prettydiff.com/aceTest.txt

I can now reproduce this on both OSX and Windows in Firefox.  It has something to do with the whitespace. This bug cannot be reproduced if the white space is altered.

**Comment by nightwing** [comment]
In ace.js script you are using on prettydiff.com you have added `if(">")return"&#62;";` which is different from https://github.com/ajaxorg/ace/commit/7a8f20383dbb8fa0b3b02842051d49a8f128b5b8#diff-5f7daffa9ef63e3751f46e374df96831R335 and obviously is a typo.

**Comment by prettydiff** [comment]
Looking at: https://github.com/ajaxorg/ace/commit/b7cd1e9d4c9cef3789363bb741ee9f4180d47ab6#diff-5f7daffa9ef63e3751f46e374df96831R336

The difference is in b7cd1e9:

    return ">";

Compared to my code:

    return "&#62;"

The former did not solve the original problem of the long minified code.  I just presumed it was a typeo from something converting the entity reference into the entity literal. The later did solve the original problem. Both forms continue to demonstrate the current problem described in https://github.com/ajaxorg/ace/issues/2480#issuecomment-102055443

**Comment by nightwing** [comment]
also  `else if (c == ">") {` vs `if(">")`

**Comment by prettydiff** [comment]
Yep, that is my problem.  b7cd1e9 does work so long as https://github.com/ajaxorg/ace/commit/b7cd1e9d4c9cef3789363bb741ee9f4180d47ab6#diff-5f7daffa9ef63e3751f46e374df96831R336 is `return "&#62;"`
