### ISSUE TITLE
Hard-coded characterWidth in static_highlight.js

### ISSUE THREAD

**Issue by lwr** [ajaxorg/ace#2484]
Take a look at this
https://github.com/ajaxorg/ace/blob/9905267e4deedda4fc4e15458a2f6cbfeb391dfc/lib/ace/ext/static_highlight.js#L154

https://github.com/ajaxorg/ace/blob/08de8b4aa1a0acf56fba18a82cc955cd4a4a00ca/lib/ace/ext/static_highlight.js#L61

The textLayer created by highlight process is just for temporary using and destroy in the same method

There is no way to control the `characterWidth` 

Here is my workaround for this issue.

```javascript
// a dirty hack for ace/ext/static_highlight.js, which hardcode a characterWidth
(function (editor, characterWidth) {
    var $renderLine = editor.renderer.$textLayer.__proto__.$renderLine;
    editor.renderer.$textLayer.__proto__.$renderLine = function () {
        if (this.config) {
            this.config.characterWidth = characterWidth;
        }
        return $renderLine.apply(this, arguments);
    };
})(editor, 7);
```

**Comment by nightwing** [comment]
I think textLayer.config is not used for anything it's just dead code that should be removed, why do you need to configure it?

**Comment by lwr** [comment]
@nightwing TextLayer use `self.config. characterWidth * 2` to render all cjk characters

like this

```html
<span class="ace_cjk" style="width:20px">实</span>
<span class="ace_cjk" style="width:20px">际</span>
```

**Comment by nightwing** [comment]
right i missed that one, however setting width to ace_cjk is not needed in static highlighter, i'll update it to not use characterWidth there
