### ISSUE TITLE
Safari 8.06: Scrollbar disappears when horiz scrollbar is visible and canvas.getContext("2d").putImageData is called.

### ISSUE THREAD

**Issue by ZaneDubya** [ajaxorg/ace#2486]
Thanks for creating this great product! I've found something that might be a bug in Ace, but then again might be a bug in Safari, where the scroll bars disappear when (1) the horizontal scroll bar in ace is visible and (2) a canvas 2d context is updated.

Steps to reproduce this bug:
- Load http://zanedubya.github.io/safari_hscr_bug/ in Safari (I'm using 8.06).
- Reduce window width so that the horizontal scroll bar is visible.
- Click 'Run' button, which starts the javascript virtual machine. As part of the VM loop, this line is called:
  
  https://zanedubya.github.io/js/screen.js @ line 144
  this.screen.putImageData(this.image, 0, 0);
  ( this.screen is a canvas.getContext("2d") )
- BUG: When the canvas 2d context is updated, both the horizontal and vertical scrollbars disappear.
- This bug is tied up with the state of the horizontal scroll bar. The scrollbars will reappear when the visible portion of the Ace editor area is scrolled all the way to the right, or if the window is expanded so that all lines are nearly visible, or all lines are visible (and the horizontal scroll bar is unnecessary). 
- Further, the bug does not occur if lines are wrapped (thus, no horizontal scroll bar - this is the solution I'm choosing until I can get horizontal scroll bars working in safari).
- This bug only occurs in Safari, does not occur the latest versions of Firefox 37, IE11, or Spartan.

**Comment by ZaneDubya** [comment]
Before updating the canvas element:
![screen shot 2015-05-07 at 7 37 43 pm](https://cloud.githubusercontent.com/assets/7041719/7528624/a7e7a5ea-f4f0-11e4-8684-b153d05f6723.png)
After updating the canvas element:
![screen shot 2015-05-07 at 7 37 57 pm](https://cloud.githubusercontent.com/assets/7041719/7528630/b97d85e0-f4f0-11e4-95e2-3045cb7bed6f.png)

**Comment by nightwing** [comment]
This is fixed by adding https://github.com/ajaxorg/ace/pull/3987, it required adding some text to the scrollbar element.
