### ISSUE TITLE
In Vim mode, page down, page up keys dont work!

### ISSUE THREAD

**Issue by ShashankaNataraj** [ajaxorg/ace#2487]
https://github.com/thomaswilburn/Caret/issues/388

Im a user of Caret which uses the ace editor component. I see that when I turn on Vim mode, page up and page down keys dont work unless I go into insert mode by pressing I. Real Vim still navigates upwards and downwards when using page up and page down without entering insert mode.

**Comment by nightwing** [comment]
Caret seems to use ace version 1.1.8. This issue is fixed in v1.1.9

**Comment by nightwing** [comment]
This is fixed in caret now

**Comment by RamboWANG** [comment]
------------------ Original ------------------
