### ISSUE TITLE
How to bind ACE content to a model ? 

### ISSUE THREAD

**Issue by mc007** [ajaxorg/ace#2489]
Hi,
is there a slightest possibility to create a binding between text-dom-nodes created in ACE and an external model, so that I can setup a sync? For instance:
![aced_model_binding](https://cloud.githubusercontent.com/assets/1205100/7566970/5f7be020-f7fa-11e4-86be-48597a0548db.png)
 
shows a dual editor, when a user changes/selects a node in the upper editor, these changes would go into ACE without going over a brutal setValue.

I know there are other complications but I would be happy already to get a little glue where to start.

thank you!

g

**Comment by nightwing** [comment]
You can use `editor.session.insert({row, column}, text)` `editor.session.remove(range)` methods to modify only part of the text in the editor.
It mostly depends on what events you get from the graphical editor above. 
But the easiest solution might be to use diff and apply changes using insert,remove methods.

**Comment by mc007** [comment]
Ok, I think I will go the diff route. Thank you!
