### ISSUE TITLE
requesting a setTabString() method of editor session

### ISSUE THREAD

**Issue by prettydiff** [ajaxorg/ace#2490]
Currently there is a `getTabString` method of the editor session. I am requesting a setTabString method to arbitrarily set indentation by any sequence of characters.

Currently indentation is limited to a specified number of spaces or a single tab character. There are times when other characters are desired for indentation, particularly when white space is not trusted over a given transfer means or when posted to sites that do not preserve white space characters.

**Comment by nightwing** [comment]
>  There are times when other characters are desired for indentation, 

do you mean \xa0 or are there other characters too?

Do you know of any other editor that allows setting arbitrary sequences of characters as a tab string?
It looks like something that will require adding special handling in many places in the editor.

> when white space is not trusted over a given transfer means or when posted to sites that do not preserve white space characters.

If it's only needed for transfer, code before setValue could handle that, right?

**Comment by prettydiff** [comment]
That is exactly what I will do. I will modify the value using arbitrary sequences for indentation characters per the user's wishes.
