### ISSUE TITLE
Korean Input Error

### ISSUE THREAD

**Issue by Hanul** [ajaxorg/ace#2493]
Hi everyone, I found a bug and I tried to fix it, but I can't. ;(

When  <안녕하세요.> input,
![ScreenShot](https://raw.githubusercontent.com/Hanul/ace/master/error.png)
- OS : Windows 8.1
- Browser : Internet Explorer 11

**Comment by nightwing** [comment]
This should be fixed by https://github.com/ajaxorg/ace/pull/3635, please let us know if you still can reproduce this on http://ace.c9.io. Thanks.
