### ISSUE TITLE
Style `id` bug

### ISSUE THREAD

**Issue by kgryte** [ajaxorg/ace#2494]
In fixing issue #2341, this introduced another bug, as documented [here](https://github.com/ajaxorg/ace/commit/4bc34f4eae5a45c00e7e5d94f25ebe7439aa7ce3#diff-1d3adf2538ef07e28972236f3a26311a) and in this [issue](https://github.com/thlorenz/brace/issues/29).

Background: I found the need to select the style elements in order to clone them and apply the styles to shadow DOM elements. The primary method for selecting the elements was via `id`. The solution to #2341 introduced a bug such that `document.querySelector( '#ace_editor.css' )` does not work.

**Comment by nightwing** [comment]
The dot can be escaped like this: `document.querySelector('#ace_editor\\.css')`

**Comment by nightwing** [comment]
Closing. Please comment if you think suggested solution is not good.
