### ISSUE TITLE
Workers broken when using jsdelivr's concatenation feature

### ISSUE THREAD

**Issue by SjonHortensius** [ajaxorg/ace#2498]
When using jsdelivr like this everything works, except for the worker feature:

```html
<script src="http://cdn.jsdelivr.net/g/ace@1.1.9/(min/ace.js+min/theme-chrome.js+min/mode-php.js)"></script>
```

It works if you use separate urls:

```html
<script src="http://cdn.jsdelivr.net/ace/1.1.9/min/ace.js"></script>
<script src="http://cdn.jsdelivr.net/ace/1.1.9/min/theme-chrome.js"></script>
<script src="http://cdn.jsdelivr.net/ace/1.1.9/min/mode-php.js"></script>
```

If you want, I can provide online examples. I have tested this in both Chrome and Firefox. In both cases worker-php gets's loaded fine. I suspect some sort of timing issue but was unable to debug this properly

**Comment by nightwing** [comment]
To load worker ace tries to find a url where it is loaded from https://github.com/ajaxorg/ace/blob/master/lib/ace/config.js#L159 which doesn't work with concatenated urls.
You can use
`ace.config.set("basePath", "http://cdn.jsdelivr.net/g/ace@1.1.9/min")`
to set basePath explicitely.

**Comment by SjonHortensius** [comment]
Your comment pushed me in the right direction, I actually served worker-php.js from my own domain (and it loaded fine, but didn't work) like this:

```js
ace.config.set('workerPath', '/');
```

I have *replaced* this with your suggestion and that fixes it. It seems there is a bug if workers are loaded from a different domain (my own site) than the script itself (from the cdn).

Thanks!

**Comment by nightwing** [comment]
From which path was it trying to load worker-php file?
http://jsbin.com/hohizorawi/1/edit?html,output works fine with different domains

**Comment by SjonHortensius** [comment]
It successfully loads the file from my-domain.com/worker-php.js but somehow it wasn't functional. This can be observed @ http://3v4l.org/

**Comment by nightwing** [comment]
worker-php.js on your site is an old version. 1.1.9 must contain `sender.emit("annotate"` https://github.com/ajaxorg/ace/blob/master/lib/ace/mode/php_worker.js#L72

**Comment by SjonHortensius** [comment]
Ah; you're right. They must have diverged; the cdn always returns the newest version but my site wasn't updated.

Thanks a lot for helping out!
