### ISSUE TITLE
setValue() emits $blockScrolling = Infinity warning

### ISSUE THREAD

**Issue by bazineta** [ajaxorg/ace#2499]
When using setValue(), the following warning is issued:

```
Automatically scrolling cursor into view after selection change this will be disabled in the next version set editor.$blockScrolling = Infinity to disable this message
```

I'm a bit confused as to what this is trying to tell me, as I'm calling a documented API, and it's in turn telling me to call an undocumented one.

**Comment by dwelle** [comment]
I'm also interested in why it's being deprecated.

**Comment by gordonwoodhull** [comment]
For the curious, this seems to be the commit where it was deprecated: 8c1aa5c7723928283236efb358ac45f871ce219a.

Unclear, but I think I saw hints that it is getting replaced with another feature.

(We use this feature, but we have to monkey patch our own calculations because (horrors) .)

**Comment by jaschaio** [comment]
I am having the same problem, using `setValue()` shows the same error message to me, even if `$blockscrolling = Infinity` is set.

```Automatically scrolling cursor into view after selection change this will be disabled in the next version set editor.$blockScrolling = Infinity to disable this message```

```
            // Initiate ACE Editor
            var textarea = $(this);
            var mode = textarea.data('editor');
            var editDiv = $('<div>', {
                position: 'absolute',
                width: '100%',
                height: textarea.height(),
                'class': textarea.attr('class')
            }).insertBefore(textarea);
            textarea.css('display', 'none');
            var editor = ace.edit(editDiv[0]);
            editor.getSession().setValue(textarea.val());
            editor.getSession().setMode("ace/mode/" + mode);
            editor.setTheme("ace/theme/chrome");
            editor.setOptions({
                autoScrollEditorIntoView: false,
                wrapBehavioursEnabled: false,
                showLineNumbers: true,
            });
            editor.$blockScrolling = Infinity;

            // Copy ACE Editor Content into Textarea and trigger Change
            editor.getSession().on('change', function () {
                textarea.val(editor.getSession().getValue());
                textarea.trigger('change');
            });

            textarea.val( editor.getSession().getValue());
```

If I uncomment the `editor.getSession().setValue(textarea.val());` line, no error message is showing.

**Comment by nightwing** [comment]
This warning was removed several versions ago
