### ISSUE TITLE
foldAll() work not :(

### ISSUE THREAD

**Issue by PaykomanVll** [ajaxorg/ace#2505]
Hello,

i use an ACE Build version on my project, and i would implement a function for foldAll() and unfoldAll, so i have googled but this will not work :(

	// init editor
	var newEditor = ace.edit('editor_'+id);
	newEditor.setTheme("ace/theme/tomorrow");
	newEditor.session.setMode("ace/mode/"+syntax);
	newEditor.$blockScrolling = Infinity;
	newEditor.setAutoScrollEditorIntoView(true);
	
	// calculate first height of editor-plugin
	var containerHeight = $('#editorContainer').outerHeight() - $('#tabs').outerHeight(),
		lineHeight = newEditor.renderer.lineHeight;
	var lines = Math.floor(containerHeight/lineHeight);
	// set options
	newEditor.setOptions({
		minLines: lines,
		maxLines: lines
	});
	
	// load the file and put into the editor
	$.post(bg_processor,{ process: "loadFile", file: file.replace('#', '') }, function(data)
	{
		newEditor.setValue(data, 1); // put file to editor
		newEditor.focus(); // focus the editor
		newEditor.getSession().foldAll(); // <-- no error and no effect =(
	}, "html");

can help me please?

**Comment by nightwing** [comment]
Maybe mode is not loaded yet when you call foldAll?
Try using the callback like https://github.com/ajaxorg/ace/blob/v1.1.9/tool/mode_creator.js#L77-L80 does.

btw why do you use 
```
newEditor.setOptions({
    minLines: lines,
    maxLines: lines
});
```

if you want to set fixed height on editor, just set height on `editor.container` element and call editor.resize()

**Comment by nightwing** [comment]
I see it works now on your page
