### ISSUE TITLE
comment or uncomment marked lines???

### ISSUE THREAD

**Issue by PaykomanVll** [ajaxorg/ace#2506]
On Eclipse get the feature when pressing ctrl + 7 (/) will active line or marked lines comment or uncomment but ACE have no function for this or?

That i miss!

**Comment by adamjimenez** [comment]
ctrl + /

On 21 May 2015 at 20:36, PaykomanVll <notifications@github.com> wrote:

> On Eclipse get the feature when pressing ctrl + 7 (/) will active line or
> marked lines comment or uncomment but ACE have no function for this or?
>
> That i miss!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ajaxorg/ace/issues/2506>.
>



-- 
Best regards,
Adam Jimenez

**Comment by PaykomanVll** [comment]
This work  not or what think you i ask here? xD

**Comment by adamjimenez** [comment]
It work so on:
http://ajaxorg.github.io/ace/kitchen-sink.html

Chrome/ Win 7 / JS mode

On 21 May 2015 at 20:42, PaykomanVll <notifications@github.com> wrote:

> This work not or what think you i ask here? xD
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ajaxorg/ace/issues/2506#issuecomment-104399411>.
>



-- 
Best regards,
Adam Jimenez

**Comment by nightwing** [comment]
@PaykomanVll if the answer above didn't work for you please comment, and tell us which browser, OS, keyboard layout, and ace mode you use

**Comment by PaykomanVll** [comment]
Hello,

yes on my Editor work this not =(
I use Chrome, German default keyboard on Win8.1 and Editor mode: php + javascript.

Is an plugin required for this function?
You can test it self here: http://mde.illex-media.com/ws/ide/

**Comment by nightwing** [comment]
unfortunately browsers do not give correct keycode for some non english keyboard layouts.

As a workaround you can use `editor.commands.bindKey("ctrl-shift-7", "toggleComment")`

**Comment by PaykomanVll** [comment]
I hafe added this line and if show the key binding i will find this new bind on the list, so its correctly...
But work not, i press it but nothing happens, please check my link on latest post.
If you fae loaded testfile from explorer you can by rightklick on editor show keybindings.

And on english or german keyboard ist ctrl + / (7) the same...

**Comment by nightwing** [comment]
Sorry, `togglecomment` needs to be lowercase `newEditor.commands.bindKey("ctrl-shift-7", "togglecomment")`

**Comment by PaykomanVll** [comment]
okay, now work it!
Very great, thank you!

**Comment by grilly86** [comment]
i had the same problem with a german keyboard.
is there a way i can make it work with the numpad-slash? - otherwise you'd have three buttons to press.

**Comment by PaykomanVll** [comment]
hmm the answere is standing here ^^

From nightwing: Sorry, togglecomment needs to be lowercase newEditor.commands.bindKey("ctrl-shift-7", "togglecomment")

**Comment by grilly86** [comment]
yes, with this line oif code it does work with the keys CTRL + SHIFT + 7  
but not with the keys CTRL + NUMPAD-DASH

**Comment by PaykomanVll** [comment]
Die Antwort steht oben, es muss im Quellcode alles klein geschrieben sein....
