### ISSUE TITLE
Highlighting for opa lanqage

### ISSUE THREAD

**Issue by neurosoup** [ajaxorg/ace#2508]
Hi,

it would be great if we could have opa files highlighting / support.

Thanks

**Comment by nightwing** [comment]
Hi,
If there is a textmate syntax which can be easily converted to ace format I may try to convert it, otherwise we have to wait for someone who knows the language to contribute a mode.

**Comment by neurosoup** [comment]
Hi,

do you think the textmate definition made for Sublime Text 2/3  for the Opa langage is hard to convert  to Ace format ? 
https://github.com/MLstate/OpaSublimeText

**Comment by nightwing** [comment]
Here's the [highlighter](https://github.com/ajaxorg/ace/blob/highlight/opa/lib/ace/mode/opa_highlight_rules.js) converted  from sublime text, but it seems either it is not very good or there was something broken during conversion, perhaps modifying js mode would be easier.
