### ISSUE TITLE
require and use split !?!?

### ISSUE THREAD

**Issue by PaykomanVll** [ajaxorg/ace#2509]
Hello,

i will use the split function to split editor below or beside, we on this example:
http://ace.c9.io/build/kitchen-sink.html

But on documentation give not a sample code to load it on editor :(

This is my code:

     // make require available
     if (typeof ace == "undefined" && typeof require == "undefined") {
        document.body.innerHTML = "<p style='padding: 20px 50px;'>couldn't find ace.js file, <br>"
            + "to build it run <code>node Makefile.dryice.js full<code>"
    } else if (typeof ace == "undefined" && typeof require != "undefined") {
        require(["ace/ace"]);
    } else {
        require = ace.require;
    }

    function loadFile(id, file, type, syntax, name)
    {
    	// create Tab and Editor
    	var editor = ( type != 'css' && type != 'js' && type != 'php' && type != 'html' && type != 'tpl' ) ? 'other' : type;
    	
    	$("li.tab").removeClass("selected"); // If a tab active than remove class
    	$('#'+editor+'Tabs').append('<li id="tab_'+id+'" class="tab selected" title="'+file+'"><span>'+name+'</span><div class="closeTab floatRight"></div></li>'); // add an tab
    	if( $('#'+editor+'Tabs').hasClass('empty') ){ $('#'+editor+'Tabs').removeClass('empty') } // make tabrow visible
    	$("pre.editor").removeClass("active"); // make all editors are hidden
    	$('#editor').append('<pre id="editor_'+id+'" class="editor active" data-file="'+file.replace('#','')+'"></pre>');
    	
    	// init editor
    	var theme = 'ace/theme/tomorrow';
    	var newEditor = ace.edit('editor_'+id);
    	newEditor.setTheme(theme);
    	newEditor.session.setMode("ace/mode/"+syntax);
    	newEditor.$blockScrolling = Infinity;
    	newEditor.setAutoScrollEditorIntoView(true);
    	
    	// calculate first height of editor-plugin
    	var containerHeight = $('#editorContainer').outerHeight() - $('#tabs').outerHeight(),
    		lineHeight = newEditor.renderer.lineHeight;
    	var lines = Math.floor(containerHeight/lineHeight);
    	// set options
    	newEditor.setOptions({
    		minLines: lines,
    		maxLines: lines,
    		//enableBasicAutocompletion: true,
            //enableSnippets: true,
            //enableLiveAutocompletion: false
    	});
    	
    	
    	var workerModule = require("ace/worker/worker_client");
        if (location.href.indexOf("noworker") !== -1) {
            workerModule.WorkerClient = workerModule.UIWorkerClient;
        }
        var container = document.getElementById('editor_'+id);
        //var Split = require("ace/split").Split;
        
        console.log( require("ace/split").Split ); // returns undefined, why that ????
        
        /*
        var split = new Split(container, theme, 1);
        env.editor = split.getEditor(0);
        split.on("focus", function(editor) {
            env.editor = editor;
            updateUIEditorOptions();
        });
        env.split = split;
        window.env = env;
    	*/
    	
    	
    	
    	
    	// load the file and put into the editor
    	$.post(bg_processor,{ process: "loadFile", file: file.replace('#', '') }, function(data)
    	{
    		newEditor.setValue(data, 1); // put file to editor
    		newEditor.focus(); // focus the editor
    		newEditor.getSession().foldAll();
    	}, "html");
    }

So that my code, with own tab-handling etc. and it works find!
Now i will add the split function but bei require ace/split i get an undefined, the file ace/ext-split.js is exist.

I hope any body can help me =(

**Comment by nightwing** [comment]
You need to Include `ace/ext-split.js` via script tag to use it.

In the future please use [ace-discuss google group](https://groups.google.com/forum/#!forum/ace-discuss) or stackoverflow to ask questions, The issue tracker is for bug reports.
