### ISSUE TITLE
PureScript mode

### ISSUE THREAD

**Issue by michaelficarra** [ajaxorg/ace#2510]
A PureScript mode would be great. See https://github.com/purescript/purescript. This language is becoming very popular very fast. Just yesterday, it even had its first in-person conference in Boulder, CO.

/cc @paf31

**Comment by nightwing** [comment]
Is it too different from haskell syntax? I see http://try.purescript.org/ uses haskell mode.

**Comment by michaelficarra** [comment]
It has been growing quite a bit different. I will provide some poorly highlighting examples soon.

**Comment by michaelficarra** [comment]
Foreign import declarations and most record-related syntax seem to be the big offenders.
