### ISSUE TITLE
$worker's annotate event not emitted properly in javascript mode

### ISSUE THREAD

**Issue by mamboer** [ajaxorg/ace#2511]
![image](https://cloud.githubusercontent.com/assets/85879/7783294/ed46be88-016f-11e5-9576-f50ea9b87f59.png)

like the pic above,
annotate event stop emitting after i type the row `function(){}`

**Comment by nightwing** [comment]
jquery version we currently use get's into infinite loop on that code. Issue seems to be fixed in the newer version
