### ISSUE TITLE
Seems that "changeScrollTop" is triggered before the viewport actually changes

### ISSUE THREAD

**Issue by yingzhox** [ajaxorg/ace#2512]
Here is the sample code
```
editor.session.on("changeScrollTop", function (e) {
    console.log(editor.getFirstVisibleRow());
}
```
If you use keyboard(by pressing Up/Down) or scrollwheel to scroll,
getFirstVisibleRow() will return the visible row before scrolling.
For example, here is the viewport with 3 lines and the cursor is in line 2:
```
2 |
3
4
```
If you press Up key, the visible area becomes
```
1 |
2
3
```
However, you will see "1"(which means line 2) in the console log.
This deos not repro with dragging the scrollbar.
So is there any way to getFirstVisibleRow after scrolling takes effect?

**Comment by nightwing** [comment]
`visibleRow` is updated only after rendering, you can either add listener for `afterRender` event on renderer, or trigger recomputation of layer config, Which method is better depends on what you are trying to achieve

**Comment by yingzhox** [comment]
Thanks, I'm trying to do a syncScroll on another Div so I want to get the new ```firstVisibleRow``` after scrolling in the editor, how to trigger recomputation of layer config?

**Comment by nightwing** [comment]
You can either call `editor.renderer.$computeLayerConfig` or `editor.resize(true)` the later one updates editor dom as well.

```js
editor.session.setScrollTop(editor.session.getScrollTop() + 15)
console.log(editor.getFirstVisibleRow())
editor.renderer.$computeLayerConfig()
console.log(editor.getFirstVisibleRow())
```

And to use `afterRender` event do
```js
editor.renderer.on("afterRender", function(e) {
    if (editor.session.getScrollTop() != _self.scrollTop) {
        _self.scrollTop = editor.session.getScrollTop();
        // redraw other div
     }
})
```

**Comment by yingzhox** [comment]
Nice, thanks so much

**Comment by TimChinye** [comment]
> You can either call `editor.renderer.$computeLayerConfig` or `editor.resize(true)` the later one updates editor dom as well.
> 
> ```js
> editor.session.setScrollTop(editor.session.getScrollTop() + 15)
> console.log(editor.getFirstVisibleRow())
> editor.renderer.$computeLayerConfig()
> console.log(editor.getFirstVisibleRow())
> ```
> 
> And to use `afterRender` event do
> 
> ```js
> editor.renderer.on("afterRender", function(e) {
>     if (editor.session.getScrollTop() != _self.scrollTop) {
>         _self.scrollTop = editor.session.getScrollTop();
>         // redraw other div
>      }
> })
> ```

Where did the `_self` variable come from?
