### ISSUE TITLE
Gherkin syntax highlighting wrong for special characters table

### ISSUE THREAD

**Issue by chmontgomery** [ajaxorg/ace#2515]
![gherkin-special-characters](https://cloud.githubusercontent.com/assets/232356/7822319/59b47b86-03ba-11e5-8ae4-8d4a3c2df2e1.png)

As described in the gherkin3 spec, all special characters should be allowed in the examples table, e.g. `-`, `?`, `'`, etc: https://github.com/cucumber/gherkin3/issues/39

The ace editor highlighting is broken and should show special characters in the examples table as regular text.

**Comment by nightwing** [comment]
Could you please describe in a little more detail what is the table syntax. Should it just highlight everything after `|<space>` in green until `|` Is reached. If yes does it include new lines? Does it depend on indentation?

**Comment by chmontgomery** [comment]
Everything after `|` should be highlighted green until a matching `|` is reached on the same line. The table row cannot go beyond a single line; that is considered a syntax error. To represent new lines, `\n` should be used. Indentation shouldn't matter. You can have any amount of spaces after the pipe. For example, all the below is valid (albeit strange looking):

![screen shot 2015-05-27 at 8 45 28 am](https://cloud.githubusercontent.com/assets/232356/7837472/c2bf3796-044c-11e5-9081-d3c9f731eded.png)

@aslakhellesoy please correct me if I'm wrong

**Comment by nightwing** [comment]
which characters can be escaped anything `/\\./` or something like `/\\[\\nt|]/`?

**Comment by chmontgomery** [comment]
There should be no need to escape anything since everything between the `|` should be considered plain text. The only character needing to be escaped is `|`. Otherwise, no matter what they put in there, as long as it's on the same line, it's valid.

**Comment by nightwing** [comment]
I mean `\n` needs to be highlighted differently because it is not treated as literal `\` and `n` characters, same as `\|` and hopefully `\\`.
Are there any other character combinations which are similar to `\n`?

**Comment by chmontgomery** [comment]
actually, for the purposes of gherkin, I think everything between the `|` should be colored the same. `\n`, `\`, `n`, `\|` and `\\` would all be colored green and, as far as the syntax highlighting is concerned, be considered plain text.

**Comment by aslakhellesoy** [comment]
Re: 5 comments up @chmontgomery. Looks good!

**Comment by nightwing** [comment]
@chmontgomery please try https://github.com/ajaxorg/ace/pull/2516

**Comment by Hamid66** [comment]
How is it posible to use a Pipe as part of string in Examples table?
for example i habe a page title " title is | this"
If i try to use it in table like this:
Scenario outline:
Examples:
|pageTitle     |
|title is | this  |

**Comment by aslakhellesoy** [comment]
You need to escape it with a backslash:

```gherkin
Scenario Outline:
  Examples:
    | pageTitle        |
    | title is \| this |
```
