### ISSUE TITLE
Autocomplete dialog won't close when click outside the editor

### ISSUE THREAD

**Issue by kalski** [ajaxorg/ace#2517]
The easiest way to reproduce is this:
* Open http://ace.c9.io/#nav=about 
* Click in the editor
* Hit ctrl+space
* Click outside the editor

*Expected result:*
I think the autocomplete dialog should close in this case.

*Actual result:*
Dialog stays there. Furthermore if you scroll the dialog will still be on the same place on screen.

Maybe this could be a hint - I researched a similar issue and noticed that Autocomplete.blurListener has some logic which determines whether to call the Autocomplete.detach function.

**Comment by nightwing** [comment]
You are right logic of blur listener was broken in the case when both tooltipNode and relatedTarget were null.  #2518 should fix this

**Comment by kalski** [comment]
Thanks for the immediate response!
