### ISSUE TITLE
.ace_text-input should have min-width and min-height set to 0

### ISSUE THREAD

**Issue by iweindesmedt** [ajaxorg/ace#2525]
a css rule of for example:

```
textarea {
  min-width:100%;
  min-height:100%;
}
```

will otherwise overrule `.ace_text-input` causing this textarea to overflow the `.ace_editor`, potentially covering buttons or other input elements below the editor.

**Comment by nightwing** [comment]
There are too many ways to break editor by using too broad css selectors.
Is the rule with `min-width:`  commonly used?

**Comment by iweindesmedt** [comment]
sure, I get that. I think its quiet commonly used on textareas, but maybe not in such a broad form.
setting those properties to ```inherit``` or ```0``` fixes it. I got this issue very randomly, just thought to mention it.
