### ISSUE TITLE
Multiple snippets with same trigger

### ISSUE THREAD

**Issue by grit96** [ajaxorg/ace#2531]
If I have two snippets in my mode's `.snippets` file like so:

```
snippet >
description assignment
scope maze
	-> ${1}= ${2}

snippet >
description if
scope maze
	-> IF ${2:**} THEN %${3:L} ELSE %${4:R}
```

Pressing tab after typing `>` auto-completes to the second snippet which is understandable. The problem is that the auto-complete list (ctrl-space) only shows the second snippet.

**Comment by nightwing** [comment]
Why do you want to create two snippets with same tabtrigger?

**Comment by grit96** [comment]
Not the same tab trigger, but so they both show up in the autcomplete list.

**Comment by nightwing** [comment]
But then why to you set same tabTrigger on both of them?

Try using name instead 

```
name assignment
scope maze
    -> ${1}= ${2}
name if
scope maze
    -> IF ${2:**} THEN %${3:L} ELSE %${4:R}
```

https://github.com/ajaxorg/ace/blob/master/lib/ace/ext/language_tools.js#L60

**Comment by grit96** [comment]
Will they both show up in autocomplete for `>` then?

**Comment by grit96** [comment]
Not showing up in the auto-complete menu is to do with #2533.
Closing because it is not logical to have the same `tabTrigger` and setting the `name` parameter should get them to both show up.
