### ISSUE TITLE
Feature: change the line height

### ISSUE THREAD

**Issue by victorel-petrovich** [ajaxorg/ace#2534]
It would be nice to have. The way it is, it is harder for me to read, as I need bigger line height. Simply increasing font does not help much.

Thanks for consideration

**Comment by nightwing** [comment]
You can use `editor.container.style.lineHeight = 3`

**Comment by victorel-petrovich** [comment]
Where can I use that? I use Caret https://github.com/thomaswilburn/Caret

**Comment by nightwing** [comment]
you can select settings>custom theme menu and add `"line-height": "3!important"` 
something like
```json
{
  "dark": false,
  "editor": {
    "background-color": "#FFFFFF",
    "color": "black",
    "line-height": "2!important"
  },
```
and then select `caret custom` from themes dropdown menu
but this works only with one theme, maybe ask caret to allow adding any css to editor, e.g by using
```
styles: {
   ".ace_editor": {
    }
} 
```
in user preferences

**Comment by victorel-petrovich** [comment]
Thank you, it works!
