### ISSUE TITLE
After a certain amount of errors a "Too many errors. X% scanned" warning appears

### ISSUE THREAD

**Issue by ferkison** [ajaxorg/ace#2535]
It would be great to have an option that would actually display ALL the errors.

**Comment by nightwing** [comment]
This is the way jshint works.
You can try increasing it's maxerr options https://github.com/ajaxorg/ace/blob/master/lib/ace/mode/javascript_worker.js#L92, but setting it too high can cause performance issues.

**Comment by ferkison** [comment]
I have a project that requires a big amount of error displaying. That was really helpful, thank you

**Comment by X25guru** [comment]
In my case, this is caused by jquery calls; in strict mode it complains about $ not being defined. It would be pretty useful if there was a work-around for this, since jquery is fairly popular.
