### ISSUE TITLE
Provide more functionality attached to the TokenIterator class

### ISSUE THREAD

**Issue by kevinushey** [ajaxorg/ace#2536]
I'm actually doing this work separately; I'm just opening an issue to ask -- would Ace be interested in accepting a PR to add more functionality to the `TokenIterator` 'class'?

I am imagining things like:
### Token Walking
- `peek(offset)`: retrieve the token at some offset from the cursor
- `moveToMatchingToken()`: For moving `TokenIterator`s over matching pairs of brackets
### Line Movement
- `moveTo{Next/Previous}Line()`
- `moveTo{Start/End}OfCurrentRow()`

And potentially some others...

**Comment by nightwing** [comment]
Sorry i missed this issue earlier. Proposed methods seem useful. 
One problem for `moveToMatchingToken` is that brackets do not always have separate tokens and there can be several brackets in the same token.
Should line movement methods work on screen or document lines?
Would `moveByLine(offset)` be better?

**Comment by kevinushey** [comment]
For `moveToMatchingToken` -- ah, that's correct. Makes it more difficult, but certainly not impossible? For RStudio, we explicitly ensure that braces are tokenized separately (we're willing to take the performance hit for a bit more simplicity in token walking)

I think all methods should work with the document lines; if methods for moving by screen lines are included they should explicitly include that in the name, e.g.

     moveByLine(offset) // move by document lines
     moveByScreenLines(offset) // move by screen lines

At least in my use case, moving by document lines rather than screen lines is typically what's most useful...

(FWIW, some of the proposed methods have implementations here: https://github.com/rstudio/rstudio/blob/master/src/gwt/acesupport/acemixins/token_iterator.js; I think with some documentation plus extra work to handle merged tokens, it could be useful to have as part of Ace itself)
