### ISSUE TITLE
Searchbox: Number of matches

### ISSUE THREAD

**Issue by acrogenesis** [ajaxorg/ace#2539]
Is there a way to get the number of matches from a search similar to how to normal browser search function works.

![screen shot 2015-06-10 at 9 31 31 am](https://cloud.githubusercontent.com/assets/1312687/8084993/8973373c-0f53-11e5-9b71-c0064b4219a1.png)

**Comment by UmkaDK** [comment]
I'd love to know the answer to this one, too!

**Comment by nightwing** [comment]
Currently this is not implemented. 
[Findbar](https://github.com/c9/c9.ide.find.replace) on c9.io have a nice way to display number of matches but it's not trivial to port that code to ace.

**Comment by nightwing** [comment]
Implemented this in https://github.com/ajaxorg/ace/pull/3313
