### ISSUE TITLE
Broken polish text input in 1.1.9

### ISSUE THREAD

**Issue by nxtpl** [ajaxorg/ace#2541]
Some changes in 1.1.9 have broken text input, so it's impossible to enter national polish characters like ą, ę, ł.

The keystroke for them used is Poland is Right ALT + a, Right ALT + e, Right ALT + l.
There might be more of them, each one is typed with Right ALT/ALTGr key.

Everything _was_ working perfectly in 1.1.8.

**Comment by nightwing** [comment]
On which browser?
Altgr + a/e/s/l work on windows7 + chrome43 with polish programmers keyboard layout.

**Comment by nxtpl** [comment]
All - Firefox 38.0.5, Chrome 43, IE 11. Windows 7. Polish programmers keyboard layout, too. On different PC's of our programmers team.
Above keystrokes don't work at all - no characters appear.

Testing online on http://ace.c9.io and local setup of 1.1.9 loaded from CDN.

**Comment by nightwing** [comment]
You are right, this is indeed broken in 1.1.9 but works on the master https://rawgit.com/ajaxorg/ace/master/kitchen-sink.html, we'll release 1.2.0 soon.
