### ISSUE TITLE
Scrollbar styling depends on cursor location when scroll initiated

### ISSUE THREAD

**Issue by kevinushey** [ajaxorg/ace#2543]
See the attached screencast. This is in the Ace Kitchen Sink with Chrome Version 43.0.2357.81 (64-bit).

![scrollbar](https://cloud.githubusercontent.com/assets/1976582/8119468/8862c6d0-104a-11e5-9459-c266284e9fab.gif)

In the first case, the scrollbar is displayed with a very lightweight black (as desired); however, if the cursor lies over the region where the scrollbar is rendered, it is instead given default styling.

**Comment by nightwing** [comment]
This is the default scrollbar style on mac. Ace doesn't modify scrollbar styles at all.
But i agree it doesn't look very good, We probably should switch to using custom scrollbars by default.
