### ISSUE TITLE
by open a local file, focus() will not work 

### ISSUE THREAD

**Issue by PaykomanVll** [ajaxorg/ace#2545]
Hello,

i have build a function how can open local files but here will the focus function not work and i know not why =( Please help...

    function loadFile(domID, file, type, syntax, name, olf) // domID is the main ID from tree (without präfix 'editor_' or 'tab_')
    {
    	// create Tab and Editor
    	var editor = ( type != 'css' && type != 'js' && type != 'php' && type != 'html' && type != 'tpl' && type != 'olf' ) ? 'other' : type;
    	
    	$("li.tab").removeClass("selected"); // If a tab active than remove class
    	$('#'+editor+'Tabs').append('<li id="tab_'+domID+'" class="tab selected" title="'+file+'"><span>'+name+'</span><div class="closeTab floatRight"></div></li>'); // add an tab
    	if( $('#'+editor+'Tabs').hasClass('empty') ){ $('#'+editor+'Tabs').removeClass('empty') } // make tabrow visible
    	$(".editor").removeClass("active"); // make all editors are hidden
    	$('#editor').append('<div id="editor_'+domID+'" class="editor active cal"></div>');
    	
    	// init editor
    	var theme = 'ace/theme/tomorrow';
    	var newEditor = ace.edit('editor_'+domID);
    	newEditor.setTheme(theme);
    	newEditor.session.setMode("ace/mode/"+syntax);
    	newEditor.$blockScrolling = Infinity;
    	newEditor.setAutoScrollEditorIntoView(true);
    	newEditor.commands.bindKey("ctrl-7", "togglecomment")
    	
    	// calculate first height of editor-plugin
    	var containerHeight = $('#editorContainer').outerHeight() - $('#tabs').outerHeight(),
    		lineHeight = newEditor.renderer.lineHeight;
    	var lines = Math.floor(containerHeight/lineHeight);
    	// set options
    	newEditor.setOptions({
    		minLines: lines,
    		maxLines: lines,
    		//enableBasicAutocompletion: true,
            //enableSnippets: true,
            //enableLiveAutocompletion: false
    	});
    	
    	// load the file and put into the editor
    	if( olf === false ) // load a file from projects (from web)
    	{
        	$.post(bg_processor,{ process: "loadFile", file: file.replace('#', '') }, function(data)
        	{
        		newEditor.setValue(data, 1); // put file-content to editor
        		newEditor.focus(); // focus the editor
        		newEditor.getSession().foldAll();
        		
        		// track changes to disblay new version on Tabs
        		ideEditorTracker( $('#tab_'+domID), newEditor, data, false );
        		
        	}, "html");
    	}
    	else // open local file - olf is not bool(fals) this contains the content for editor
    	{
    	    newEditor.setValue(olf, 1); // put file-content to editor
        	newEditor.focus(); // focus the editor - here work not o.O
    		newEditor.getSession().foldAll();
    		
    		// track changes to disblay new version on Tabs
    		ideEditorTracker( $('#tab_'+domID), newEditor, olf, false );
    	}
    }

**Comment by nightwing** [comment]
Most likely something in your code calls focus on another element after you call focus on ace.
in the first case it works because focus is called after some time.
Closing since this doesn't seem to be a bug in ace. Feel free to comment and provide example page if you think otherwise.

**Comment by PaykomanVll** [comment]
Hello, thanks for your answer but i think of interesst is the newEditor var and on both functions hafe this the same element...

that is what i find curios =(
I will now update my editor then cane you check it out here http://mde.illex-media.com/ws/ide/

Give me 5 mins =)

Then you can from left side select a file and the editor will be focused but if you drag and drop a file from your local PC to the editor this will not focus ace :(

**Comment by nightwing** [comment]
As i said before, please do not use maxLines minLines for setting editor height, the editorHeight function you use should be something like this
```
function editorHeight(id) {
	var updateEditor = ace.edit(id);	
	var containerHeight = $('#editorContainer').outerHeight() - $('#tabs').outerHeight()		
	updateEditor.container.style.height = containerHeight + "px"		
	// set new height
	updateEditor.resize()
}
```
