### ISSUE TITLE
Feature Request: JSX support

### ISSUE THREAD

**Issue by boustanihani** [ajaxorg/ace#2546]
JS Beautifier v1.5.6 added JSX support 2 weeks ago:
https://github.com/beautify-web/js-beautify/blob/v1.5.6/CHANGELOG.md#v156

I hope this also gets into ACE/Cloud9 soon :bowtie:

**Comment by nightwing** [comment]
This is on c9.io now, but there seems to be a bug in beutify.js: indentation of jsx block is always increased by one level.

**Comment by boustanihani** [comment]
@nightwing I am still getting the message that JSX is not supported yet:

![c9 jsx beautify](https://cloud.githubusercontent.com/assets/4227548/13195892/383a151e-d7be-11e5-80b4-0fff58bb6822.png)

**Comment by nightwing** [comment]
JSX mode is for https://jsx.github.io/, not react jsx.
JavaScript mode handles react jsx well.

**Comment by boustanihani** [comment]
Oh, I didn't know this, do you know if **React-JSX** is supported?

**Comment by nightwing** [comment]
Yes, just use javascript mode, (which should be chosen by default). It has better highlighting and supports formatting.

**Comment by boustanihani** [comment]
Cool this works :+1:  Just one more question, do you know if it is possible to keep the curly brackets on the same line ```({name})``` ?? This is how the code is currently beautified:

![c9 jsx beautify 2](https://cloud.githubusercontent.com/assets/4227548/13195969/004aa92c-d7c1-11e5-9d91-bc5d7668a2e0.png)

**Comment by nightwing** [comment]
Unfortunately https://github.com/beautify-web/js-beautify doesn't seem to support that:(
