### ISSUE TITLE
Provide facilities allowing for lookahead / lookbehind in tokenizer

### ISSUE THREAD

**Issue by kevinushey** [ajaxorg/ace#2547]
Motivation: In Markdown documents, we want to support syntax highlighting for YAML sub sections contained between `---`, e.g.

```
---
this: "is yaml"
---

But This is a Header!
---
```

As you can imagine, the difficulty is in determining whether `---` denotes the start of a YAML block, or a (second-level) section.

It would be possible to fit this into the tokenizer by adding intermediate states, e.g. the state after a line containing text could be 'allowYaml'; that state would not be visited after simply a blank line.

However, it seems like it would be much nicer if the rules defined could accept generic rules for testing a match, e.g. (with pseudo-code defining how such a rule might be defined)

```
{
   regex: "^---$",
   match: function(session, parsePos) {
      if (<is YAML header>) {
         return {token: "support.function.codebegin", next: "yaml-start"};
      } else {
         return {token: "markdown.header.1", next: "start"}
      }
   }
}
```

The idea is that the `match` rule would encompass both the `token` and `next` rules, and also gain enough information (`session`, `row`) so that the tokenizer could perform lookaround if so desired.

Any thoughts on whether such a scheme would be feasible?

(Motivation: this is how `pandoc` allows people to embed metadata within Markdown documents, e.g. http://pandoc.org/demo/example9/pandocs-markdown.html)

**Comment by nightwing** [comment]
What `<is YAML header>` part will look like?
Having arbitrary lookahead / lookbehind won't work well with incremental tokenization.

e.g consider

```
|                   <-- state here is start
---                 <-- state still start
this: "is yaml"     <-- state yaml-start
```


```
x|                  <-- state here didn't change so match will not be called for the next line
---                       
this: "is yaml"      
```

**Comment by kevinushey** [comment]
Ah, good point. :/ I can't think of a simple way to encode invalidation into the rules, so I think that makes the proposal essentially not worth the effort.

Perhaps I'll look into modifying the Markdown rules to do as previously stated: have states of the form `allowYaml` which control whether `---` is interpreted as the start of a YAML header or not.

Thanks for the response.
