### ISSUE TITLE
Clicking on link creates new cursor

### ISSUE THREAD

**Issue by mlajtos** [ajaxorg/ace#2554]
When CTRL-clicking (CMD-clicking on mac) on a link, Ace creates a new cursor at that position.

Is there any way to prevent this behaviour?

**Comment by nightwing** [comment]
there is experimental hidden option to disable use of ctrl-click by multiselect and leave it for jumptodef `editor.$mouseHandler.$enableJumpToDef = true`. but that doesn't add any other handling for links.
