### ISSUE TITLE
Javascript - Auto Indent - Reformat

### ISSUE THREAD

**Issue by tomitrescak** [ajaxorg/ace#2557]
I tried to search everywhere but can't find a way of how to select several lines of code and reformat it. Is it possible?

**Comment by nightwing** [comment]
You can use beautify.js or esformat similar to the way cloud9 does https://github.com/c9/c9.ide.format/blob/master/formatters/jsbeautify.js.

**Comment by tomitrescak** [comment]
Great! That looks like what I need. Being a terrible noob, I tried to use it with my editor, but can't find a way of to activate this plugin. Is there any guide for how yo do this? Thanks a lot for your help'

**Comment by nightwing** [comment]
Sorry, it cannot be used directly since it depends on other parts of cloud9 code, but you can use it as an example.

**Comment by tomitrescak** [comment]
@nightwing  Ace comes packaged with Beautify, but I can't seem to activate it :/ https://github.com/ajaxorg/ace-builds/blob/master/src/ext-beautify.js

**Comment by nightwing** [comment]
ext-beautify.js is a very basic beautifier for php, we initially wanted to make it generic for all languages, but right now it is not very useful.
