### ISSUE TITLE
Why javacript worker is using eval?

### ISSUE THREAD

**Issue by n9** [ajaxorg/ace#2559]
In [javascript_worker.js#L108](https://github.com/ajaxorg/ace/blob/264923e4dfe0c0c82035be462af2a1c31e8c6b78/lib/ace/mode/javascript_worker.js#L108), `eval` with `throw` is used to check the validity of the source code. Is there a reason why is `eval` used instead of `new Function(...)`?

**Comment by nightwing** [comment]
Recently there was a bug in some browsers: `Function("};{alert(1)")` would call alert also `Function("return")` doesn't print error, is there a reason to prefer Function over eval?

**Comment by n9** [comment]
The code just looks hacky to me, I did not know bug. Thanks.
