### ISSUE TITLE
Adding command with special characters

### ISSUE THREAD

**Issue by rahmanusta** [ajaxorg/ace#2566]
Is it possible to add commands with a special character like below;

``` javascript
editor.commands.addCommand({
    name: 'comment-command',
    bindKey: {win: 'Ctrl-/', mac: 'Command-/'},
    exec: function (editor) {
        console.log("comment");
    },
    readOnly: true
});
```

**Comment by nightwing** [comment]
Which one is the 'special' character here? As far as i can tell the code snippet above works.

**Comment by rahmanusta** [comment]
@nightwing I mean slash ( / ) , with slash it is not working

**Comment by nightwing** [comment]
Which keyboard layout you use?
Ctrl-/ is already bound to toggle comment, and it works with us layout on http://ace.c9.io/#nav=about

**Comment by rahmanusta** [comment]
I'm using turkish layout keyword. It has no effect with /

**Comment by nightwing** [comment]
unfortunately for some keyboard layouts browsers return different keycodes when pressing key with ctrl. Use

```js
editor.keyBinding.addKeyboardHandler(function(data, hashId, keyString, keyCode) {
    console.log(require("ace/lib/keys").KEY_MODS[hashId] + keyString);
    return { command: "null" }
})
```

to see which keycode editor gets when you press ctrl-/

**Comment by rahmanusta** [comment]
```javascript
editor.keyBinding.addKeyboardHandler(function (data, hashId, keyString, keyCode) {
    console.log(hashId, keyString, keyCode);
    console.log(ace.require("ace/lib/keys").KEY_MODS[hashId] + keyString);
    return {command: "null"}
})
```

I tried that, it prints;

```javascript
1 o 111
ctrl-o
```

**Comment by nightwing** [comment]
i guess you could try binding to ctrl-o, but that will not work well on other keyboard layouts.
How other editors handle this does ctrl-/ work for you in sublime text?
