### ISSUE TITLE
Undefined handling in javascript_worker.js

### ISSUE THREAD

**Issue by n9** [ajaxorg/ace#2567]
In [lib/ace/mode/javascript_worker.js](https://github.com/ajaxorg/ace/blob/264923e4dfe0c0c82035be462af2a1c31e8c6b78/lib/ace/mode/javascript_worker.js#L159), message `"'{a}' is not defined."` is being handled, however it seems to me that [this message](https://github.com/ajaxorg/ace/blob/update-deps/lib/ace/mode/javascript/jshint.js#L9591) is passed not in `errors` collection in JSHINT but rather to `undefs` collection, which is not being read in javascript_worker.js. (I've searched all usages of W117, it is always passed to [isundef() function](https://github.com/ajaxorg/ace/blob/update-deps/lib/ace/mode/javascript/jshint.js#L2221).)

**Comment by nightwing** [comment]
What do you mean by `passed not in errors collection in JSHINT but rather to undefs collection`?
Could you show example of code snippet for which wrong error message is displayed?

**Comment by n9** [comment]
[Here you read](https://github.com/ajaxorg/ace/blob/264923e4dfe0c0c82035be462af2a1c31e8c6b78/lib/ace/mode/javascript_worker.js#L129) errors collection (`lint.errors`).
However, the undefined variables are store to (`lint.undefs`), which is not read by javascript_worker.
You can also try it by opening ace with javavascript mode a write there just `foo;` - ace will not show error that `'foo' is not defined`.
