### ISSUE TITLE
Wrong autocomplete popup position when gutter is hidden

### ISSUE THREAD

**Issue by gatufo** [ajaxorg/ace#2569]
Autocomplete popup positioning fails when gutter is hidden.

`showGutter: false`

**With gutter**
![](https://dl.dropboxusercontent.com/spa/h1svnkmb4cl5e2l/2r-v_gnb.png)

**Without gutter**
![](https://dl.dropboxusercontent.com/spa/h1svnkmb4cl5e2l/ri4v7ivr.png)

It behaves different depending on the browser (only macos tested):

* **Firefox**: it happens since the beginning.
* **Chrome**: It works ok the first time autocomplete is shown, but if you delete all editor text and start over the horizontal displacement appears. 

I think it may be related to gutter width calculation.

For now I solved it... by adding an additional div parent container with negative margin + transparent background color for the editor + hidding the `.ace_gutter` class via css

**Comment by nightwing** [comment]
This is fixed on master by https://github.com/ajaxorg/ace/commit/446e3e1bf9fa5346100324b1e870329493bda1ef#diff-6bb9a9b54ea218f237bd1a338ed893b2R103
