### ISSUE TITLE
Inappropriately automatically scrolling after replacing selection in Chrome

### ISSUE THREAD

**Issue by ppham27** [ajaxorg/ace#2572]
[JS Fiddle Example](http://jsfiddle.net/ppham27/e1w2hqdj/)

The steps to reproduce are as follows:
1. Scroll to the bottom of the page
2. Click the button that says "Click Me!" which selects the first few characters of the editor text.
3. Type a single letter 'a' or any letter for that matter.

You'll see that the page suddenly jumps to the top. If you continue to type the page scrolls back down, but it creates a very jarring experience for the user.

I'm using version 1.1.9 and Chrome 43. The issue appears on both a Mac and PC. The bug does not occur in Firefox, Safari, or IE, so it may be an issue with Chrome.

I'd be happy to look into the issue myself if someone can point me in the right direction.

Thanks!

**Comment by nightwing** [comment]
Should be fixed by https://github.com/ajaxorg/ace/pull/2573. Thanks for reporting.

**Comment by ppham27** [comment]
I confirm that the bug is fixed. I appreciate for the quick reply.
