### ISSUE TITLE
Add project to bower.io

### ISSUE THREAD

**Issue by bocharsky-bw** [ajaxorg/ace#2577]
Add to project dir `bower.json` file and publish project on http://bower.io/search/ for ability to use it in dependencies and install via `Bower`

**Comment by samkelleher** [comment]
@echoAlex is maintaining a bower project of ace-builds - see https://github.com/echoAlexey/ace-builds

**Comment by bocharsky-bw** [comment]
Why don't add it to official repository?

**Comment by nightwing** [comment]
We can merge a pull request adding bower.json if it helps people to use Ace.
However it's not clear if we should add bower.json to ace or ace-builds, and which files to put in `main` array. Is it used for anything?

**Comment by SamMousa** [comment]
Docs for bower.json: http://bower.io/docs/creating-packages/

Extracted:
Entry-point files have module exports and may use module imports. While Bower does not directly use main files, they are listed with the commands bower list --json and bower list --paths, so they can be used by build tools.

Note that you could add bower.json from the echoAlexey fork and update it later based on community feedback. AFAIK the only thing that you really should not change is the package name...
