### ISSUE TITLE
[Gherkin] Wrongly highlights text starting with the `@` character

### ISSUE THREAD

**Issue by danielpacak** [ajaxorg/ace#2580]
As you can see below

![screen shot 2015-06-29 at 20 18 44](https://cloud.githubusercontent.com/assets/1322923/8415028/495d9162-1e9c-11e5-95cf-4b8d019e4382.png)

something is wrong with the syntax highlighter. Apparently it treats everything that starts with the `@` character as a tag, whereas it's not always the case. Any ideas/hints how to fix it?

I'm using the latest version of Ace in my [FeatureBook](https://github.com/SOFTWARE-CLINIC/featurebook) project, but  it's also reproducible in [Ace Kitchen Sink](http://ace.c9.io/build/kitchen-sink.html). Pasting the source code for reference:

```gherkin
Feature: Metadata

  Background:
    Given a directory with Gherkin source files
    And  "featurebook.json" descriptor

  @functional @automated
  Scenario: Provide information about authors and contributors
    Given the "authors" property in "featurebook.json" contains the following authors
      | firstName | lastName    | email                  |
      | Henryk    | Sienkiewicz | hsienkiewicz@gmail.com |
      | Eliza     | Orzeszkowa  | eorzeszkowa@gmail.com  |
    And the "contributors" property in "featurebook.json" contains the following contributors
      | firstName | lastName | email               |
      | Juliusz   | Slowacki | jslowacki@gmail.com |
    When I serve the directory as a system specification
    And open it in my web browser
    Then the authors should be listed beneath the specification's title
    And the contributors should be listed beneath the authors
```

**Comment by nightwing** [comment]
>  whereas it's not always the case. Any ideas/hints how to fix it?

in which cases it is supposed to start a tag?

**Comment by danielpacak** [comment]
I added two tags: `@functional` and `@automated` to the sample scenario above. These are highlighted properly. However, `hsienkiewicz@gmail.com` which is just a value in the data table arg should not be highlighted as a tag. Currently, a part of it is highlighted as a tag (between @ and .).

**Comment by nightwing** [comment]
Well is there any specification for tag names in gherkin, e.g `<whitespace>@\w+`?
Btw it is better to report related issues with highlighting in the same thread instead of creating a new issue.

**Comment by danielpacak** [comment]
According to this [wiki](https://github.com/cucumber/cucumber/wiki/Tags) it's assumed that tags can be placed on `Feature`s, `Scenario`s, and `Scenario Outline`s. So I'm afraid that `<whitespace>@\w+` might not be enough. Is it possible to further constrain what you proposed? By saying for example:

1.  `<whitespace>@\w+` **preceding keywords** [Feature|Scenario|Scenario Outline]?
2. or **beginning of line** followed by 0 to n whitespaces followed by a tag, followed by 0 to n whitespaces, followed by tag, etc.?

Yet another example. IntelliJ vs Ace:
![screen shot 2015-06-29 at 22 25 47](https://cloud.githubusercontent.com/assets/1322923/8417614/fb398416-1ead-11e5-91cf-520633a217d1.png)

![screen shot 2015-06-29 at 22 26 03](https://cloud.githubusercontent.com/assets/1322923/8417637/14cc87fc-1eae-11e5-9b50-fe0dea297a10.png)

**Comment by nightwing** [comment]
lookahead is not supported, and usually it doesn't work well while typing
second suggestion was much easier to implement please try  https://github.com/ajaxorg/ace/tree/highlight/gherkin branch and
https://rawgit.com/ajaxorg/ace/highlight/gherkin/kitchen-sink.html online demo

**Comment by danielpacak** [comment]
Looks great now! And seems to solve both issues I opened today.

**Comment by nightwing** [comment]
Thanks.
Which color should tags have? should they be more visible or less visible?
Now they have same color as comments which seems to be wrong.

**Comment by danielpacak** [comment]
I'd say, it should be easy to distinguish them from keywords. As mentioned before, typically you put tags on `Feature`s and `Scenario`s so if they have similar colours everything is blurred. Otherwise I have no preferences.
