### ISSUE TITLE
add highlighting for "ifnull" for MySQL

### ISSUE THREAD

**Issue by iweindesmedt** [ajaxorg/ace#2588]
```coalesce``` is highlighted, ```ifnull``` is not but should

**Comment by nightwing** [comment]
fixed in v1.1.2

**Comment by iweindesmedt** [comment]
v1.1.2? It's not highlighted in the latest v1.2.0.
I think it's as easy as adding the ```ifnull``` keyword to ```mySqlKeywords``` in https://github.com/ajaxorg/ace/blob/6ebacf96f59182afe7c900b5cee927ba9491668c/lib/ace/mode/mysql_highlight_rules.js#L41

**Comment by nightwing** [comment]
Hmm we have too many sql dialect highlighters :( I had added it to https://github.com/ajaxorg/ace/blob/6ebacf96f59182afe7c900b5cee927ba9491668c/lib/ace/mode/sql_highlight_rules.js#L51 in v1.2.0 https://github.com/ajaxorg/ace/commit/6ebacf96f59182afe7c900b5cee927ba9491668c#diff-44f508564b4512644b61415fa5ae4190R50

**Comment by iweindesmedt** [comment]
Shouldn't it be added to the MySQL rules as well on top of the SQL rules?
It certainly is a very valid keyword: https://dev.mysql.com/doc/refman/5.7/en/control-flow-functions.html

**Comment by nightwing** [comment]
> Shouldn't it be added to the MySQL rules as well on top of the SQL rules?
It certainly is a very valid keyword:

sure, i just missed MySQL mode files, my bad.
Hopefully attached commit is better.
