### ISSUE TITLE
Remove all references to implicit globals of window, document

### ISSUE THREAD

**Issue by DelvarWorld** [ajaxorg/ace#2589]
In some places, Ace seems to do the right thing, by checking for the existence of the window global:  https://github.com/ajaxorg/ace/blob/0a3b002e285a41a4884ce42f94d2f68673e43b30/build_support/mini_require.js#L42 (although I have a feeling that overwriting "global" is bad)

But in dozens of other places, Ace expects the implicit `window` global to be present:
https://github.com/ajaxorg/ace/blob/de6f75f69b546bd00b2f44ebf03ae4246b950419/lib/ace/lib/event.js#L361

What this means in practice is that when using [brace](https://github.com/thlorenz/brace) to `require()` Ace in NodeJS, it will crash the NodeJS instance: https://github.com/thlorenz/brace/issues/30

The author of brace doesn't want to address this. Ideally including the presence of Ace itself shouldn't have side effects. It would be helpful to remove the implicit global references to allow for sever side rendering / unit testing where Ace is in the dependency tree, even (especially) if it's not rendered.

**Comment by nightwing** [comment]
https://github.com/ajaxorg/ace/pull/2590 should allow loading ace in node with
```
require("amd-loader")
require("ace/lib/ace/ace")
```
but calling ace.edit will still fail.

After the pull request is merged Brace will need to add `var window = global;` at the top of the index.js to get this to work.
