### ISSUE TITLE
Google Chrome Helper uses 100% cpu when entering a function.

### ISSUE THREAD

**Issue by saller** [ajaxorg/ace#2591]
CPU usage of the Google Chrome Helper rises to 100% (and stays like that) when the user enters a simple function into the editor (javascript mode / linting enabled). 

e.g.

```javascript

function foo() {
   return 'bar';
}

```

**Comment by nightwing** [comment]
This was a bug in jshint version used in ace v1.1.9, please update to ace v1.1.2
