### ISSUE TITLE
Get folds from editor

### ISSUE THREAD

**Issue by amlwwalker** [ajaxorg/ace#2592]
Is it possible to get the code from each of the code folds?
I want to be able to click on code and "do things" based on what code is in the current fold.
Ace editor can already fold the code, so its analysing it in some way and placing the buttons to activate the folds. Can I somehow retrieve whatever code is in it?

**Comment by nightwing** [comment]
See https://github.com/ajaxorg/ace/blob/master/lib/ace/mouse/fold_handler.js#L41
`session.getTextRange(fold.range)` will give text inside the fold
