### ISSUE TITLE
Multiple modes ?

### ISSUE THREAD

**Issue by abuhurairalakdawala** [ajaxorg/ace#2593]
Is it possible to set multiple modes at a time?

**Comment by nightwing** [comment]
No, what do you expect it to do?

**Comment by abuhurairalakdawala** [comment]
I want to write multiple language in same editor at a time.

for example i want to set mode="php, html5, javascript, ruby" and i write multiple language at a time

Now if i am coding in php
<?php
$a = 'value';
echo $a;
?>
and then when i get the autocomplete suggestion it should suggest me the correct language i.e. php language.

and then if i write javascript code below php code
<script>
var a = document.getElementById('demo')
console.log(a);
</script>
It should suggest me javascript language syntax.

**Comment by nightwing** [comment]
That can't work because editor won't know which language you are typing.
Php mode highlights text in `<?php` as php and text in `<script>` as javascript. In which case do you want it to highlight ruby?

**Comment by abuhurairalakdawala** [comment]
no i dont what to highlight ruby with php.
i just wanted atleast one programming language like php or ruby along with client side html and javascript and css.

Thanks.

**Comment by nightwing** [comment]
For html with php you can use php mode, for html with ruby erb mode.
Unfortunately there is no way to automatically create a mode for templating language like erb based on "html5, javascript, ruby" string so one have to use a mode name like "ace/mode/html_ruby" instead

**Comment by javatlacati** [comment]
What about for Java?
https://docs.oracle.com/javase/tutorial/uiswing/components/html.html

or asm in C?

In modern compilers you can see something like:

     void do_print(uint32_t dwSomeValue)
     {
        uint32_t dwRes;
     
        for (uint32_t x=0; x < 5; x++)
        {
           // Assumes dwSomeValue is not zero.
           asm ("bsfl %1,%0"
             : "=r" (dwRes)
             : "r" (dwSomeValue)
             : "cc");
     
           printf("%u: %u %u\n", x, dwSomeValue, dwRes);
        }
     }

on the elders I remember have seen soemthing like
main() {
printf("calling asm...");
asm{
 mov bx
 jmp
}
