### ISSUE TITLE
Multiple spaces rendered as one space

### ISSUE THREAD

**Issue by Jaaap** [ajaxorg/ace#2594]
Between version 03.03.15 (beb9ff6) and 03.04.15 (e3ccd2c) a bug was introduced where multiple spaces are shown as one single space.

Steps to reproduce:
Open the ace editor
Type some random text without spaces
Move the cursor to the middle of that text
hit the spacebar 2 or more times
Observe that only a single space is rendered but the cursor does move with every space.

**Comment by nightwing** [comment]
On which browser does this happen? Do you see it on https://ace.c9.io?
Most likely there is a css rule on your page that overrides https://github.com/ajaxorg/ace/blob/master/lib/ace/css/editor.css#L167

**Comment by Jaaap** [comment]
Ah you are right.
It was this line:
.ace_line {white-space: nowrap;}
