### ISSUE TITLE
Tokens for capture groups and lookahead assertions

### ISSUE THREAD

**Issue by nokome** [ajaxorg/ace#2602]
I am developing a language mode which uses lookahead assertions in several regexes. This works OK until I try to assign tokens to capture groups within the regex:

```js
token: ['keyword','text','support.function','text','keyword','text','support.function'],
regex: '\\b(for)( +)(.+?)( +)(in)( +)(.+?)(?= ~ | : |}|$)'
```

Produces this:

![image](https://cloud.githubusercontent.com/assets/1152336/8824840/b99c6ec4-30cd-11e5-9822-d704eb5d5a06.png)

If I remove the lookahead assertion (and add the extra token Ace asks for), I get the expected result (but it breaks subsequent parsing):

```js
token: ['keyword','text','support.function','text','keyword','text','support.function','text'],
regex: '\\b(for)( +)(.+?)( +)(in)( +)(.+?)( ~ | : |}|$)'
```

![image](https://cloud.githubusercontent.com/assets/1152336/8824860/dd9fedfa-30cd-11e5-9164-14801548b335.png)

**Comment by nightwing** [comment]
This is caused by `(.+?)` patterns which match different things in https://github.com/ajaxorg/ace/blob/master/lib/ace/tokenizer.js#L141 and https://github.com/ajaxorg/ace/blob/master/lib/ace/tokenizer.js#L250

the best solution would be `(\\w+)` or `([^ }:~]+)`

**Comment by nokome** [comment]
@nightwing , thanks for your help, will try your workaround, much appreciated.
