### ISSUE TITLE
[Gherkin] Support other languages than English

### ISSUE THREAD

**Issue by danielpacak** [ajaxorg/ace#2604]
A `# language:` header on the first line of a feature file tells Gherkin parser what [spoken language](https://github.com/cucumber/gherkin3/blob/master/gherkin-languages.json) to use – for example `# language: pl` for Polish. If you omit this header, the language defaults to English (`en`).

AFAIK, ace editor currently supports only the default English keywords. How hard would it be to support other languages?

![ace_gherkin_pl](https://cloud.githubusercontent.com/assets/1322923/8837668/c6d89974-30c7-11e5-8d4a-8a05e68037f7.png)

![idea_gherkin_pl](https://cloud.githubusercontent.com/assets/1322923/8837689/e440dd14-30c7-11e5-97d0-27465c20df7d.png)

**Comment by nightwing** [comment]
Keywords for other languages need to be added to the list at https://github.com/ajaxorg/ace/blob/master/lib/ace/mode/gherkin_highlight_rules.js#L49

**Comment by danielpacak** [comment]
I came up with the following regexp just to add Polish keywords.


```js
{
  token: "keyword",
  regex: "Właściwość:|Funkcja:|Aspekt:|Potrzeba biznesowa:|Założenia:|Scenariusz:|Szablon scenariusza:|Przykłady:|Zakładając|Mając|Zakładając, że|Jeżeli|Jeśli|Gdy|Kiedy|Wtedy|Oraz|I|Ale|Feature:|Background:|Scenario:|Scenario Outline:|Examples:|Given|When|Then|And|But|\\*"
}
```

However I'm not sure how it's gonna scale when we add support for other languages? Can we build keywords regexp programmatically by iterating a helper structure (as shown below) without big performance penalty?

```js
var languageToKeywordsRegext = {
  "pl": "Właściwość:|Funkcja:|Aspekt:|Potrzeba biznesowa:|Założenia:|Scenariusz:|Szablon scenariusza:|Przykłady:|Zakładając|Mając|Zakładając, że|Jeżeli|Jeśli|Gdy|Kiedy|Wtedy|Oraz|I|Ale",
  "en": "Feature:|Background:|Scenario:|Scenario Outline:|Examples:|Given|When|Then|And|But"
}
```

**Comment by nightwing** [comment]
This turned out harder to fix than i thought, since keywords from different languages interfere with each other: (Mainly `I` is getting in the way).
We'll need a way to create a separate state for each language on the fly.
