### ISSUE TITLE
[Gherkin] Wrongly highlights placeholders/variables in a scenario outline's step

### ISSUE THREAD

**Issue by danielpacak** [ajaxorg/ace#2605]
A Scenario Outline uses placeholders/variables, which are contained within `< >` in the Scenario Outline’s steps. For example:

![screen shot 2015-07-22 at 23 35 22](https://cloud.githubusercontent.com/assets/1322923/8838152/fb2ccfe4-30ca-11e5-9311-2cb95cea75f5.png)

As you can see above Ace editor **does not** highlight correctly 2 or more placeholders contained within the same step.

![screen shot 2015-07-22 at 23 35 44](https://cloud.githubusercontent.com/assets/1322923/8838322/1c6904e2-30cc-11e5-8251-2b01db35fd0d.png)

**Comment by nightwing** [comment]
> placeholders/variables, which are contained within < >

what characters are allowed in placeholders?

**Comment by danielpacak** [comment]
I'd go with `<[^>]+>` regexp to cater for non-English characters and different naming conventions.

![gherkin_placeholder_regexp](https://cloud.githubusercontent.com/assets/1322923/8845193/dd9cbe1a-311c-11e5-95f3-92db28c8bf21.png)

**Comment by mkslanc** [comment]
Fixed by https://github.com/ajaxorg/ace/pull/2607
