### ISSUE TITLE
React JSX mode

### ISSUE THREAD

**Issue by Gerhut** [ajaxorg/ace#2606]
Language Reference: https://facebook.github.io/jsx/

Since [Facebook announced their respective build system is Babel](http://facebook.github.io/react/blog/2015/06/12/deprecating-jstransform-and-react-tools.html), I tried to convert [tmLanguage of Babel's JavaScript](https://github.com/babel/babel-sublime/blob/master/JavaScript%20(Babel).tmLanguage) in [babel-sublime](https://github.com/babel/babel-sublime) to ace mode file but failed because it uses lots of RE syntax which is not supported by JavaScript such as backward assertions and once-only subpatterns. If I remove them all it cannot pass the test with an error (infinite loop in ace tokenizer).

Moreover, there already exists [an ace mode named JSX](https://github.com/ajaxorg/ace/blob/master/lib/ace/mode/jsx.js), which has no relation with React JSX. I suggest that name the React JSX mode "React JSX" or "JavaScript (Babel)" or something else.

Thank you for your fantastic work!

**Comment by nightwing** [comment]
I've started adding jsx support in https://github.com/ajaxorg/ace/commit/ec5a1227c43fccfb34a6a9c842d9c4b288d1bf12. 

You can test it online at https://rawgit.com/ajaxorg/ace/ec5a1227c43fccfb34a6a9c842d9c4b288d1bf12/kitchen-sink.html using javascript mode.

The jsx mode in ace was for https://github.com/jsx/JSX/ language, which seems to be abandoned now.

What do you think is the best way to handle errors in cases like

```jsx
<tag></typo>
// js here?
```

should the last line be highlighted as javascript or a string?

**Comment by davideweaver** [comment]
Has there been progress on this? Anyone want to share their implementation?

**Comment by nightwing** [comment]
@davideweaver jsx support is enabled by default in js mode

**Comment by davideweaver** [comment]
@nightwing Thanks. Is it React-style JSX and does it do syntax checking? I'm trying https://ace.c9.io/build/kitchen-sink.html with mode=JSX and I'm not seeing it do anything with the JSX.

**Comment by nightwing** [comment]
It is react-style jsx, it only does syntax highlighting, for syntax checking to work we need to switch to eslint.
