### ISSUE TITLE
snippets with /* */ content don't get their content built

### ISSUE THREAD

**Issue by Pike** [ajaxorg/ace#2610]
I've got a snippet like this:

    snippet comment
    	/* ${1:${SELECTED_TEXT}} */

which get's built via `node ./Makefile.dryice.js` into

    exports.snippetText = "snippet comment\n\
    ";
My .js in snippets is doing

    exports.snippetText = require("../requirejs/text!./l20n.snippets");
I've seen the same affect the javascript snippets file, too.

Compare https://github.com/ajaxorg/ace-builds/blob/0982db4853e3c967756b83b70638b9761d7f801d/src/snippets/javascript.js#L104 and https://github.com/ajaxorg/ace/blob/master/lib/ace/snippets/javascript.snippets#L101

**Comment by nightwing** [comment]
Was a bug in architect-build.
Should be fixed now.
