### ISSUE TITLE
can`t open Shortcut-menu =(

### ISSUE THREAD

**Issue by PaykomanVll** [ajaxorg/ace#2611]
Hello,

i know not why but i can´t open the shortcut-list (ctrl+alt+H) on kitchen sink work it.
What i must do for it?

I have seen on #1331 i can get a list for own Template over this function: aceGetKeybordShortcuts(editor);

But i become error: aceGetKeybordShortcuts is not defined.

Greetings, Stefan

**Comment by nightwing** [comment]
You need to load keybinding_menu extension first. See https://github.com/ajaxorg/ace/blob/master/demo/keyboard_shortcuts.html#L35

**Comment by PaykomanVll** [comment]
Perfect, work fine. Thank you!
