### ISSUE TITLE
Ace editor in a JS popup window?

### ISSUE THREAD

**Issue by joncoogan** [ajaxorg/ace#2613]
Hello.  I'm having a hard time getting Ace to work in a JS popup window.  Here is a very simple example:  http://jsfiddle.net/joncoogan/tm61jmxr/

For reference, here is the "equivalent" example without the popup window:  http://jsfiddle.net/joncoogan/1nmkw818/

Any insight would be appreciated!

**Comment by nightwing** [comment]
Ace can work only in the window in which it was created.
In the example above it doesn't work because of missing styles in the popup window, and use of setTimeout requestAnimationFrame of the original window.
To make the fiddle work, load ace.js in the popup window.

**Comment by joncoogan** [comment]
Very helpful. Thank you.

**Comment by Anymfah** [comment]
hello, i'm having the same problem.. i don't get how to load ace.js in the popup window, can you explain a bit more pls ?
