### ISSUE TITLE
Nested/Meta tokens

### ISSUE THREAD

**Issue by mlajtos** [ajaxorg/ace#2614]
Is it possible to have nested tokens? I found that meta tokens should be used exactly for this purpose, but I am not able use them the way I want.

The problem is following: I have a identifier that has 2 parts: head and tail. Head is special so I need it to be highlighted differently than the tail. At the same time, I need to access the identifier as a whole when doing autocompletion.

For now, I managed it to work by concatening token values together, but this is not optimal. Is there any clean solution to this problem?

Thank you for an ace editor! ;)

**Comment by nightwing** [comment]
There is no way to create nested tokens, and concatenating is used by modes that need that (e.g html)
The drawback of nested tokens is that they would use too much memory.
https://github.com/ajaxorg/ace/issues/1227#issuecomment-66869175 is one possible workaround.

**Comment by mlajtos** [comment]
Thank you.
