### ISSUE TITLE
Indication of syntax error, when using new notation for an array of symbols

### ISSUE THREAD

**Issue by s2k** [ajaxorg/ace#2615]
### Scenario: A literal `Array` of `Symbol`s ist assigned to a variable.

For example consider a `Gemfile`, which declares `sqlite` to be used in development and testing:

> gem 'sqlite3', group: %i[development test]

The "%+letter+delimiter notation" is used here, to describe the `Array` `[:development, :test]`.
#### Behaviour

The IDE shows an 'x' icon (white 'x' on red ground) as well as the error message 

> unknown type of %string
> syntax error, unexpected $end"

Also see screehshot: 

<img width="396" alt="screen shot 2015-07-29 at 14 10 47" src="https://cloud.githubusercontent.com/assets/118248/8957265/986c56d0-35fd-11e5-873a-467a98abf4e8.png">

Remark: If I remember correctly, this notation was introduced in with Ruby 2.0.
#### Expectation

Since this is working and supported Ruby code, no syntax error should be displayed.
Maybe even better: If the IDE can figure what what Ruby version is used (I'm using 2.2.1p85), then it could display the error for Ruby versios that do not yet support that notation.

**Comment by mkslanc** [comment]
Fixed by #4281
