### ISSUE TITLE
Vim mode: map esc to jk/kj 

### ISSUE THREAD

**Issue by Januzz** [ajaxorg/ace#2616]
In Vim I mapped esc to jk and kj using

```
inoremap jk <esc>
inoremap kj <esc>
```

Is this possible in ACE vim mode as well? I'm always getting confused when I write code in RStudio, inserting a lot of "jk"s :)

**Comment by Januzz** [comment]
I now found a work around in using Karabiner (https://pqrs.org/osx/karabiner/). For those interested, include in your private xml:

```
    <appdef>
        <appname>RSTUDIO</appname>
        <equal>org.rstudio.RStudio</equal>
    </appdef>

    <item>
        <name>RStudio: Simultaneous jk for Esc</name>
        <identifier>com.yourname.jk_to_esc</identifier>
        <only>RSTUDIO</only>
        <autogen>__SimultaneousKeyPresses__ KeyCode::J, KeyCode::K, KeyCode::ESCAPE</autogen>
    </item>
```
Would still be interested to know whether this is possible "natively"...

**Comment by nightwing** [comment]
It is possible to do `:imap jk <Esc>` in http://ace.c9.io/build/kitchen-sink.html. I think it should work in RStudio too, but Ace cannot handle saving the key mapping, it needs to be handled by embedding application.

**Comment by Januzz** [comment]
Alright, thanks! I'll ask the RStudio developers then...

**Comment by jubilatious1** [comment]
RStudio Version 0.99.441 – © 2009-2015 RStudio, Inc.

The above RStudio version allows "Command" mode (don't know what the underlying Ace version is). Typing the following two commands consecutively allows "jk" or "kj " act as  `<Esc>` from Insert -> Normal mode.  HTH.

```
:imap jk <Esc>
:imap kj <Esc>
```
