### ISSUE TITLE
Marko support

### ISSUE THREAD

**Issue by zwhitchcox** [ajaxorg/ace#2624]
The progress loading template engine for node

https://github.com/marko-js/marko

**Comment by javatlacati** [comment]
It has to be made with the same approach as HTML(Ruby) to reuse HTML highlighting; First define the marko syntax alone and then incorporate to a new file HTML(Markojs).

**Comment by nightwing** [comment]
I am unlikely to be able to find time for learning marco syntax to add a mode for it.
But if someone wants to work on that, i can help.
As @javatlacati said [html_ruby_highlight_rules](https://github.com/ajaxorg/ace/blob/master/lib/ace/mode/html_ruby_highlight_rules.js) is a good place to start. And with [tool/mode_creator.html](http://ace.c9.io/tool/mode_creator.html) it should be relatively easy for someone who knows marko syntax to add a mode.
