### ISSUE TITLE
[CFML] syntax highlighting issue with nested comments

### ISSUE THREAD

**Issue by thdoan** [ajaxorg/ace#2625]
Try entering this block in a ColdFusion (.cfm) file:

```
<!---
<cfif 1>
  <!--- Some comment --->
  <cfset str = "blahblahblah">
</cfif>
--->
```

The syntax highlighting gets messed up because of the nested comments.

**Comment by nightwing** [comment]
https://github.com/ajaxorg/ace/pull/2626 should fix this

**Comment by thdoan** [comment]
@nightwing could you please take a look at #2382 also?

**Comment by thdoan** [comment]
PR #2626 is confirmed to fix the issue -- thanks!
