### ISSUE TITLE
Markdown syntax highlighting leaks on syntax errors

### ISSUE THREAD

**Issue by gjtorikian** [ajaxorg/ace#2631]
Copy-paste this block of Markdown into the Ace editor:

``````
Edit this file in GitHub's UI.

The CSS code block below technically has a syntax error (a missing `}`).

```css
body {
  ...
  ... add a closing brace here to see the highlight difference in line 14
```

However, syntax errors should not spill into subsequent blocks. The block below should be highlighted         properly as JavaScript.

```js
if ('string') {  // 'string' should be red
  ...
```
``````

Because of the CSS syntax error, the `js` code does not properly highlight, even though the `css` code block is closed appropriately. 

I tried digging into the DOM a bit to see what was going on, but I couldn't remember if highlighting is handled by the marker layer or not.

/cc @nightwing assuming you're still the go-to Ace bug squasher. :v:

**Comment by nightwing** [comment]
@gjtorikian This is an Interesting issue. It happens because `pop` at https://github.com/ajaxorg/ace/blob/master/lib/ace/mode/markdown_highlight_rules.js#L209 removes only the last css state, but we need to remove all non markdown states.

**Comment by nightwing** [comment]
fixed in https://github.com/ajaxorg/ace/pull/3647/commits/a64719ed28c925ba8a0bd1a7c102c25e73d5ff03
