### ISSUE TITLE
Indentation presented with an angle brace

### ISSUE THREAD

**Issue by prettydiff** [ajaxorg/ace#2638]
![aceeditor](https://cloud.githubusercontent.com/assets/524902/9286806/eccf111a-42c1-11e5-94e3-d1c7ef20cf3d.png)

The angle braces are generated when copy pasting a particular file: http://prettydiff.com/unit_tests/beautification_css_less.txt  Each angle brace represents a tab character while the indentation at the front is from 4 spaces.  I am not enabling any option to allow this behavior.

For some reason I cannot reproduce the issue in my online tool, but I can consistently reproduce it on my local.  I have never seen this problem before and it is somehow related to the contents of that file.

**Comment by nightwing** [comment]
Which version of ace do you use? Is your local version and version on the site the same?

**Comment by prettydiff** [comment]
I am not sure how to determine a version number. I believe I am using the src-min build.  The local version and online version are the same.  I have no idea why I am able to produce this issue locally but not online.

**Comment by prettydiff** [comment]
The exact code I am using is available at http://prettydiff.com/ace/

**Comment by nightwing** [comment]
It appears to be a modified version of 1.1.9, please use https://github.com/ajaxorg/ace-builds/tree/v1.2.0

**Comment by prettydiff** [comment]
Thank you!
