### ISSUE TITLE
Hang on some Vim search-and-replace regular expressions

### ISSUE THREAD

**Issue by jmcphers** [ajaxorg/ace#2642]
Repro:
1. Open the Kitchen Sink
2. Switch key bindings to Vim
3. Select several lines 
4. Enter this command: `: '<, '>s/^/   /g`
5. Press Enter

This appears to trigger an infinite loop.

**Comment by kevinushey** [comment]
FWIW, I wasn't able to reproduce this with CodeMirror's vim (https://codemirror.net/demo/vim.html), so it might be a bug in the Ace patches / bindings around `vim.js`.
