### ISSUE TITLE
Issue for Chinese IME Input

### ISSUE THREAD

**Issue by danvim** [ajaxorg/ace#2648]
I came from : https://github.com/ajaxorg/ace/issues/1401

I've been working with web development this long, haven't even think of this happening. I don't even know how you people manage to write these delicate libraries.

Firefox Screenshot FF43.0a1

![untitled](https://cloud.githubusercontent.com/assets/5255292/9413133/9c9fca94-4862-11e5-82f4-e4c9566930d4.png)

I was typing away using IME, and when I try typing in IME, it added 2 Unicode char in front (they are both a square with 0001 written in it. I thought `\u0001` were invisible?) Anyway, **it is always 2 0001 chars in front**, though in this screenshot, the prior one is clipped outside the visible frame. **Also, you are sometimes unable to use the arrow keys after successful IME input.**

**Comment by danvim** [comment]
Hello?

**Comment by nightwing** [comment]
This should be fixed by https://github.com/ajaxorg/ace/pull/3635, please let us know if you still can reproduce this on http://ace.c9.io. Thanks.
