### ISSUE TITLE
editor resize doesn't work with knockout: if binding

### ISSUE THREAD

**Issue by karlp** [ajaxorg/ace#2651]
jsfiddle here: http://jsfiddle.net/j021p0rf/

If you use knockout's "if" binding to not show elements until your page is ready, ace's resizing gets very confused, and shows a blank editor.  calling editor.resize() doesn't fix things.

once you've clicked the button, and "ready" is true, the editor div appears, and using jquery on the same selectors "div#editor.ace_editor.ace-tm" to inspect the "el.clientHeight" (and width) properties, I can see that the real visible, non-zero values are available, but inside the this.renderer.onResize() function, "el.clientHeight" stays permanently at zero, even after the knockout model has updated.  No amount of physically resizing the window or calling editor.resize() helps.

**Comment by karlp** [comment]
using a knockout "visible" binding is a suitable workaround in many cases, but I think manually calling resize should still work if you want to use the if: style

**Comment by nightwing** [comment]
in the fiddle above knockout just removes the container node used by ace, and adds another node in its place so editor.container.parentNode is null

**Comment by karlp** [comment]
so what, I need to somehow recreate the editor?  Not just resize()?  Can I reparent the editor?

**Comment by nightwing** [comment]
add  `document.body.appendChild(editor.container)` before resize call to see that this is not caused by ace.

**Comment by karlp** [comment]
yes, that works.  but if editor.container still exists and is still valid, why can't editor.resize find it again?

I realize that at the time the editor was created, "#editor" was removed by knockout, but the "#editor" div _does_ exist when I call resize(),  why can't it look for it by id again, instead of assuming the one from the beginning is still relevant or valid?

**Comment by nightwing** [comment]
Calling getElementById from resize would be slow.
resize only updates size to match to the size of the container. It doesn't create a new editor.
Also passing id to ace.edit is only a shortcut, preferred way is to pass dom node instead, which might not have any id.

**Comment by karlp** [comment]
what about when force=true? maybe then?

Re shortcuts, if the preferred way is to pass a dom node, that should really be done in all the examples, which currently all just use a string id.

**Comment by nightwing** [comment]
Creating new editor isn't really related to resize, so i think even force=true shouldn't do that.

One can use 

```js
        if (!editor.container.parentNode) {
            var newNode = document.getElementById("editor")
            newNode.parentNode.replaceChild(editor.container, newNode)
        }
```
if needed.

> that should really be done in all the examples, which currently all just use a string id.

you are right, examples need to be updated.

**Comment by karlp** [comment]
Fine.  I would really like to see this sort of magic listed near the resize() docs, as the docs for resize() sounded like exactly what I needed.  "you changed stuff outside the normal way"

Now, sure, I'm clearly not enough of a DOM wizard to appreciate the differences between "removed the element from the dom" vs "modified things outside" but that's why I was tracing into resize to work out why it doesn't work.  Clearly, I'm just "doin it wrong" but what then are the cases where resize() _is_ useful?  It's painfully non-obvious to non-experts when you can use developer tools in chromium, see_ the editor elements in the right place, but with size 0, and then have resize() not fix that problem.

See the images at http://imgur.com/1iXsfP8,IilFl0F for why this looks like resize isn't working.

**Comment by nightwing** [comment]
i wish there was a way for ace to do some magic.
resize is useful in the case where hidden node becomes visible or when you set editor.style.height that is size of the editor container changes.
But when editor container is removed from the document, there is nothing resize can do.

to see what i mean, add
```js
p = document.querySelector(".panel.panel-default"); 
p.parentNode.replaceChild(p.cloneNode(true), p)
```
at the end of the js fiddle,
dom will look the same, but knockout button won't work because nodes are different, just like with ace
