### ISSUE TITLE
when used in a flexbox layout everything is broken

### ISSUE THREAD

**Issue by WesNetmo** [ajaxorg/ace#2659]
everything should be hardcoded/reset, from `display` to `transform`. currently i can't even start searching for what is causing it, it's entirely broken
thank you

**Comment by nightwing** [comment]
Could you create a page showing what is broken.
Everything seems to work fine in http://plnkr.co/edit/3GSCNtY9060FBslNRn2y?p=preview

**Comment by WesNetmo** [comment]
for instance div must be hardcoded with display:block, and span as display:inline. i don't know if other tags are used or if more reset is needed

**Comment by nightwing** [comment]
Ace creates only div span and textarea elements, but why do you change display of div and span in the first place?

**Comment by WesNetmo** [comment]
because if you want a 100% flexbox layout you want elements to default to display:flex/inline-flex rather than block/inline

**Comment by dagnelies** [comment]
Hi,
here is a variation of your example that is broken:
http://plnkr.co/edit/16c3ZotiFDmEFzQOxZH0?p=preview
