### ISSUE TITLE
Option to make editor disabled

### ISSUE THREAD

**Issue by ankit** [ajaxorg/ace#266]
Similar to the 'disabled' attribute of a textarea.

it will be similar to the readOnly mode, only no user interaction will be allowed with the editor. So, cursor and any line markers will be hidden.
@gissues:{"order":73.29192546583863,"status":"backlog"}

**Comment by Dvisacker** [comment]
Thanks, definitely need an option to make the editor disabled !

**Comment by frimdo** [comment]
Hi, did you implement the $mouseHandler destroyer? I am a little bit lost (newbie here). Or is there any way to disable it? Thanks for editor disabling btw :-)

**Comment by ILNILEY** [comment]
@nightwing  
editor.renderer.$cursorLayer.element.style.opacity=0
It seems that $cursorLayer is not an attribute of VirtualRenderer now.
I want to hide the cursor when my editor is in 'readOnly' state,and I try the method you had given,but it doesn't work for the reason that  $cursorLayer is not an attribute of VirtualRenderer ;Is there any other way to hide the cursor?

**Comment by ILNILEY** [comment]
I found there are two method in VirtualRenderer,hideCursor() and setCursorStyle(), and I try to use them in belowing way.But it dosen't work as well.  
 this._editor.renderer.hideCursor();
 this._editor.renderer.setCursorStyle("opacity: 0;");
Am I wrong in using?

**Comment by lcswillems** [comment]
Is it work in progress?

**Comment by jbolle** [comment]
Same here! I would like to use renderer.hideCursor() method but it doesn't seem to work. I tried to call it in my editor init block and in `changeCursor` event but I'm unable to make it work.

**Comment by Hasnayeen** [comment]
for people still want to disable cursor, use css3 property `pointer-events: none;` on the editor element.

**Comment by oseisaac** [comment]
How do I disable the editor, still just a new react developer? Please would appreciate any help

**Comment by oseisaac** [comment]
> for people still want to disable cursor, use css3 property `pointer-events: none;` on the editor element.

How do you disable the editor ?

**Comment by Hasnayeen** [comment]
> > for people still want to disable cursor, use css3 property `pointer-events: none;` on the editor element.
> 
> How do you disable the editor ?

```
editor.setOptions({
    readOnly: true,
})
```

**Comment by oseisaac** [comment]
Worked like a charm

**Comment by MR-Addict** [comment]
I think this works without any js:

```css
.ace_editor textarea:read-only ~ .ace_scroller .ace_cursor-layer,
.ace_editor textarea:read-only ~ .ace_scroller .ace_marker-layer .ace_bracket {
  display: none;
}
```
