### ISSUE TITLE
USE_IE_MIME_TYPE in Web Browser Control is returning NaN

### ISSUE THREAD

**Issue by RickStrahl** [ajaxorg/ace#2661]
I'm using ACE inside of a Windows WebBrowser control running in IE 11 mode. There are a few problems with the editor when loading content from disk and then using Copy or Cut to cut to the clipboard.

After tracing the code I found that 

```javascript
var USE_IE_MIME_TYPE =  useragent.isIE;
```

results in USE_IE_MIME_TYPE = NaN when running inside of the WebBrowser control. It works fine in full IE (which returns 11 for me).

This in turn causes problems when trying to copy content to the clipboard (Ctrl-C operation):

```javascript
        var mime = USE_IE_MIME_TYPE ? "Text" : "text/plain";
        if (data) {
            return clipboardData.setData("Text", data) !== false;
        } else {
            return clipboardData.getData(mime);
        }
```
which results in an error on the page because the value sent is `text/plain` instead of `text`.

For now I've hacked the code to get around this, but it be nice to get this fixed properly.

#### Update:
It looks like the problem is the user agent string in IE in the Web Browser control. If I manually override the user agent string in the headers passed to the control the errors go away.

This is the user agent string that fails from the WebBrowser:
**Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.2; WOW64; Trident/8.0)**

**Comment by nightwing** [comment]
Closing since https://github.com/ajaxorg/ace/issues/2913 fixed the ctrl-c issue
