### ISSUE TITLE
missing foldStyle in session options.

### ISSUE THREAD

**Issue by dskow** [ajaxorg/ace#2663]
When running getOptions() function, there is a missing foldStyle console log error.

The ace.js file needs some code added to config.defineOptions(EditSession.prototype, "session", {
function in ace.js older code or edit_session.js in latest code.

Here is the code.

foldStyle: {
       set: function(val) { this.setFoldStyle(val); },
       get: function() { return this.$foldStyle; }
    }

**Comment by brian-thornton** [comment]
+1
