### ISSUE TITLE
Cursor position very close to letters after using unicode characters.

### ISSUE THREAD

**Issue by rsmith31415** [ajaxorg/ace#2667]
Is there some solution for the issue of having the cursor position misaligned after using unicode characters? There is an open bug similar to this in #1666, but the suggestion there was to use another font, which is not applicable to most situations.

[Here](http://plnkr.co/edit/raZuUTyzFSoMPTmf2Yxx?p=preview) you have a plunkr. The issue here is that when I include an unicode character, then the cursor is very close to the following letters. For example:

![screenshot from 2015-09-14 16 49 20](https://cloud.githubusercontent.com/assets/599274/9862766/a3873ec2-5b00-11e5-8956-e6e684b63927.png)

**Comment by nightwing** [comment]
There is no solution for this yet, only monospace fonts are supported.

**Comment by rsmith31415** [comment]
Okay. Thanks for letting me know.

**Comment by apblack** [comment]
#3037 refers to the same problem.  It's easy to fix, since character widths are already floating point numbers, not integers.

**Comment by andrewnester** [comment]
Duplicate of https://github.com/ajaxorg/ace/issues/460
