### ISSUE TITLE
Shortcuts with double letters

### ISSUE THREAD

**Issue by rangrunera** [ajaxorg/ace#2669]
Right now, I'm working on key binds.

I have found, that I'm not able to make a key bind, which has two letters next to each other.
The key bind I'm trying to make, looks like this:
```js
            editor.commands.addCommands([{
                name: "test",
                bindKey: {
                    win: "Ctrl-K-D",
                    mac: "Command-K-D"
                },
                exec: function (editor, line) {
                    alert("test");
                },
                readOnly: true
            }])
```
It returns this error in the console: invalid modifier k in Ctrl-K-D 

It doesn't seem to work. However, if I bind a function to say, Ctrl-Shift-A It works fine.

Is there a way to have a key bind with two letters next to each other?
Thanks in advance!

**Comment by rocketinventor** [comment]
Nah, I don't think it's possible. That's why you are getting an error.
Try using a different keyboard shortcut.

**Comment by nightwing** [comment]
`"Ctrl-K-D"` would mean `K` and `D` must be pressed at the same time, you are probably  looking for `"Ctrl-K Ctrl-D"` instead.
