### ISSUE TITLE
Can not minify sax.js

### ISSUE THREAD

**Issue by msh-odoo** [ajaxorg/ace#2673]
Hi,

I am using version 1.2.0:
https://github.com/ajaxorg/ace/tree/v1.2.0/lib/ace

In my case I am collecting all needed scripts, creating a template for it, loading all script content(using python) and creating one minified file and returning to browser but while loading that minified version I am getting error.

After checking I found the issue is in sax.js:
https://github.com/ajaxorg/ace/blob/v1.2.0/lib/ace/mode/xml/sax.js#L6
There is semicolon missing at the end.

**Comment by nightwing** [comment]
This is an issue with the minifier, missing semicolons are valid javascript syntax, also xml/sax.js is meant to be loaded into web worker, so adding it with rest of the files will cause other problems too.
