### ISSUE TITLE
bug in this.$detectNewLine

### ISSUE THREAD

**Issue by prettydiff** [ajaxorg/ace#2677]
this.$detectNewLine=function(e){var t=e.match(/^.*?(\r\n|\r|\n)/m); and so on...

I am getting an error `e is undefined`

I can reproduce this error when I go to http://prettydiff.com/?m=beautify&l=csv and paste this code:

    first, second, third
    "cat""",dog,otherfdsas

I have verified the mode is set to "plain_text" which evaluates to "ace/mode/text".  You can easily access both editors from the browser console as `pd.ace.beauIn` and `pd.ace.beauOut`

**Comment by nightwing** [comment]
This can happen if you call insert with non string value.
When following steps you described above, I do not see this error with chrome 45

**Comment by snobu** [comment]
Getting the same error, i'll try to build a short repro, but i only replaced v1.1.9 with 1.2.2 and now i'm getting this.

**Comment by prettydiff** [comment]
For me the error was generated due to a defect in my own code where I was passing in an array instead of a string.

**Comment by snobu** [comment]
Nevermind, i was doing something silly.

```
    // Blank out the editor before fetching new content
            viewModel.editText(null);
```
It decided it's time to point fingers.
Replaced the `null` with an empty string and it's all fine and dandy.

**Comment by prettydiff** [comment]
It might be wise to have better error messaging associated with this issue to educate the user, so that the user realizes their code mistake implementing this awesome tool.

**Comment by snobu** [comment]
It looks like we've clearly hit the same bug here but we were passing in two different things. An array and a null.

PR proposal:
- Hammer input into a string no matter what and `console.error("setValue() expects a String")` - This has the advantage of not breaking current implementations
or
- `try-catch` around the input with a `console.error` explaining what has changed.

**Comment by snobu** [comment]
You see, sometimes i speak as if Javascript is strongly typed or as if Global Warming is fixed. But there's just enough capacity to fix one.

http://3.bp.blogspot.com/-5nZ5eWwNypw/TaTtzISLBdI/AAAAAAAAAbk/NQ2HgzC-Ep8/s1600/36520_sad_seal.jpg

I'll just leave this here.
