### ISSUE TITLE
emacs iSearch should quit on unrecognized keys

### ISSUE THREAD

**Issue by kevinushey** [ajaxorg/ace#2691]
A use case:

1. Open the [kitchen sink](http://ace.c9.io/build/kitchen-sink.html),
2. Enable Emacs keybindings,
3. Type `C-s` to initiate an `iSearch`,
4. Try pressing the arrow keys.

It seems like the `iSearch` state gobbles up the key presses, and does nothing -- I think it would be better to instead cancel the `iSearch` and let the keyboard handlers operate as normal.

**Comment by kevinushey** [comment]
A possible resolution: it looks like the handler attached to the `"exec"` event and basically disallows any non-iSearch commands.

https://github.com/ajaxorg/ace/blob/master/lib/ace/commands/incremental_search_commands.js#L178

Perhaps something like this would be a little better?

```js
if (!e.command.isIncrementalSearchCommand) {
    return iSearch.deactivate(true);
}
```

**Comment by nightwing** [comment]
the snippet above looks good, and matches with emacs behavior.
Could you make a pull request or do you prefer if i add it?
