### ISSUE TITLE
Go lang syntax highlighting is not satisfying ...

### ISSUE THREAD

**Issue by vinothwindows47** [ajaxorg/ace#2694]
In sublime text , go lang syntax highlighting is,
<img width="999" alt="sublime-go-syntaxhighlight" src="https://cloud.githubusercontent.com/assets/3929019/10391550/3bfa0eaa-6e9d-11e5-92f7-db1f871bf897.png">

In ace editor, go lang syntax highlighting is ,

<img width="1003" alt="ace-syntax-highlighting" src="https://cloud.githubusercontent.com/assets/3929019/10391564/599bed48-6e9d-11e5-86b2-a1a711a355b7.png">

go lang function name highlighting would be better .

**Comment by nightwing** [comment]
try with https://github.com/ajaxorg/ace/pull/2702

**Comment by vinothwindows47** [comment]
Thank you very much @nightwing
