### ISSUE TITLE
emacs: C-k should eat EOL when at end of line

### ISSUE THREAD

**Issue by kevinushey** [ajaxorg/ace#2695]
E.g. given the text (with `|` indicating the cursor position)

```
some text|
some other text
```

In Emacs, pressing `C-k` will eat the end of line character (thus joining the two lines); Ace does nothing. Note that the EOL should only be consumed when all of the text from the cursor position to the end of line is whitespace.

(Perhaps this behaviour should be adopted for the default Ace mode, as well?)

**Comment by nightwing** [comment]
https://github.com/ajaxorg/ace/commit/b4f5afbbefc55b1396a021adf50ba08cc2dc8c41 fixes this

**Comment by kevinushey** [comment]
Thanks!

**Comment by kevinushey** [comment]
Closing this as I can see the fixed behaviour available in the kitchen sink. Thanks!
