### ISSUE TITLE
no-conflict is... conflicting.

### ISSUE THREAD

**Issue by M-Porter** [ajaxorg/ace#2700]
Hey everyone,

Attempting to use ace editor's no-conflict library for some projects and I came across some problems.

`worker-html.js` rebinds `window.require` which conflicts with my current codebase. Is there a reason that the html worker files rebinds `window.require` rather than using the no-conflict `ace.require`?

**Comment by nightwing** [comment]
worker-html.js is not meant to be loaded into window scope, Ace loads it into a separate web worker.

**Comment by M-Porter** [comment]
Even if that is so, it is still conflicting with `window.require` even though it shouldn't because it is loaded in a separate web worker.

**Comment by nightwing** [comment]
Do you use a build tool that concatenates or wraps ace-build files in some way?
https://github.com/ajaxorg/ace-builds/blob/master/src-noconflict/worker-html.js#L3-L4 is supposed to not exit from the function modifying window.require when `this` passed from https://github.com/ajaxorg/ace-builds/blob/master/src-noconflict/worker-html.js#L218 is a real window

**Comment by M-Porter** [comment]
We have a lot of tools doing a lot of things at page-render. I was able to narrow down the search. Your response helped me determine that the worker wasn't the problem but something else is going on.

Thanks for the help.
