### ISSUE TITLE
emacs: consecutive C-k should append to last 'killed' text

### ISSUE THREAD

**Issue by kevinushey** [ajaxorg/ace#2701]
In Emacs, consecutive 'kills' of the line using `C-k` append to the last killed line. For example, given the text (with the cursor at the start, before `foo`)

```
foo
bar
baz
```

Pressing `C-k` four times will 'eat' the lines `foo\nbar\n` (including those EOL characters). Later pressing `C-y` will yank all of that text; however, in Ace we only see the last kill (in this case, the newline).

A couple thoughts on how this could be resolved:

The [`killRing`](https://github.com/ajaxorg/ace/blob/master/lib/ace/keyboard/emacs.js#L630-L650) implementation could gain an `append` method, which would be something like:

```js
append: function(str) {
    var idx = $data.length - 1;
    var text = $data[idx] || "";
    if (str) text += str;
    if (text) $data[idx] = text;
}
```

and the [`killLine`](https://github.com/ajaxorg/ace/blob/master/lib/ace/keyboard/emacs.js#L563) implementation could get something like (pseudo-ish code):

```js
if (commands.$lastCommand.isKillLine)
    exports.killRing.append(text);
else
    exports.killRing.add(text);
```

I'm not sure if there is a clean way of accessing the last executed command. Does Ace maintain something like a 'command execution' history?

**Comment by nightwing** [comment]
`editor.prevOp.command` can be used for this
