### ISSUE TITLE
Request to include a reference to ace-grammar add-on

### ISSUE THREAD

**Issue by foo123** [ajaxorg/ace#2704]
Hello, i suggest an included reference in ACE site and/or repository to the [ace-grammar add-on](https://github.com/foo123/ace-grammar) (author).

The add-on was created specificaly to handle highlighting arbitrary code and/or highlight alternatively from included modes. Since most of that work was found to be the same, a general grammar-based add-on was created with many important features, many of which not found in existing hard-coded highlight modes.

On top of that, the add-on solves the problem of transfering highlight-modes to text or another editor and vice-versa and also extending existing modes with new features in an optimum way.

i think the add-on is very usefull for all users of ACE and it would be nice to have a reference to it.

The code is open-source and free and anyone can use and contribute freely.

Thank you, keep up the good work

**Comment by nightwing** [comment]
Hi, i have added a link to https://github.com/ajaxorg/ace/wiki/Extensions#externally-hosted-extensions, feel free to edit that page if you want to add more info.
Not closing the issue since it would be good to add the list of extensions to https://ace.c9.io as well.

**Comment by foo123** [comment]
@nightwing, very nice, for more up-to-date info for the add-on can be found in the repo
Thanks

**Comment by foo123** [comment]
@nightwing 

As there was a reference to a common specification for highlight modes (which ace implements, and codemirror as well), take a look at [this part](https://github.com/foo123/editor-grammar/blob/master/grammar-reference.md#modularity-and-future-directions) for new common modular specification for highllighting
