### ISSUE TITLE
Copy paste appears in Context menu only with contenteditable="true"

### ISSUE THREAD

**Issue by abhishekgahlot** [ajaxorg/ace#2705]
I am using ace editor version 1.1.3 but copy/paste option in browser context menu only appears when I set the main div property to contenteditable true. 

Can anyone tell why this is happening or is it safe to add contenteditable into the editor div. I tried debugging but couldn't find why this is happening and this is the only fix I have.

Thanks!

**Comment by nightwing** [comment]
Do you see this issue on http://ace.c9.io? If yes on which browser?
I think adding contentEditable won't work very well.

**Comment by abhishekgahlot** [comment]
@nightwing I don't see this issue but in my app where I have added no copy/paste option are there. Adding contentEditable makes it work in every browser and I don't see any problem with the editor too. Can you tell if something can break in ace editor functionality if i go with this fix.

**Comment by nightwing** [comment]
It will be possible to tab into the contentediable element and delete parts of the editor, try using the new version of Ace (ace.c9.io uses v1.2.0)

**Comment by abhishekgahlot** [comment]
@nightwing Sorry for late reply. I did used ace 1.2.2 but that didn't helped. Using contenteditable true did added copy/paste options but that made whole editor selectable in IE 11.

**Comment by nightwing** [comment]
Adding contenteditable is not a good solution as it will break many things with the editor, If you can give me example of a page where context menu doesn't work, i can debug this.

**Comment by abhishekgahlot** [comment]
@nightwing Thanks again for saying so :) 
I will debug it myself because I think the issue could be related to other things in app where ace editor is used. I will raise the PR if in case its issue with ACE.
