### ISSUE TITLE
Highlighting comments

### ISSUE THREAD

**Issue by iDeBugger** [ajaxorg/ace#2706]
When I comment some string in XML file and then uncomment it — rest of text highlighting as comment.

http://files.idebugger.ru/stuff/2015-10-16_11-13-21-eec98f1dc7bc7f17835583be47b58a16.mp4

**Comment by nightwing** [comment]
This is caused by partial tokenization triggered by the tag highlighter.
Related to https://github.com/ajaxorg/ace/issues/2633
