### ISSUE TITLE
Adding a contextmenu item

### ISSUE THREAD

**Issue by ogdans3** [ajaxorg/ace#2712]
How do you add a contextmenu item, specificly for chrome apps?

I have tried using the chrome api to do this but it seems that it dosent work when right clicking on the ace div, but it works elsewhere. 

After looking through the code i found that you disable the "nativecontextmenu" but i were not able to add my own context menu item, tried doing it like the spellcheck.js but to no luck. Could someone give me an example of how to do this or point me to a few lines in a script that adds the context menu element

Thanks

**Comment by nightwing** [comment]
ace doesn't disable native context menu, it only moves textarea to the cursor position, if your code works with textarea it should work with ace too.

**Comment by ogdans3** [comment]
Alright, after doing some reading on the chrome docs i found the error. However now it works if I change the line:
text.style.top = Math.min(e.clientY - top - 2, maxTop) + "px";
to something like
text.style.top = Math.min(e.clientY - top - 15, maxTop - 15) + "px";

This is in textinput.js within this.moveToMouse
So i imagine that something is blocking part of the context menu and therefore not showing the new element? How would i show both my element and all the default ace elements?

Thanks for helping!

**Comment by nightwing** [comment]
probably your new element doesn't work for textareas and -15 moves ace text area too far leaving click on div element. try to find if there is some way to add context menu item for text area, or add new copy/cat/paste instead of native items.

**Comment by ogdans3** [comment]
But it works when i just return from that method

**Comment by nightwing** [comment]
by "works" do you mean all items are shown or only the custom one?
I can have a look if you give me an example of the chrome extension that adds context menu items.

**Comment by ogdans3** [comment]
When i return from the method then the element that i add shows and reload app, inspect element and all those show but the copy/paste and all those from ace do not show.

Code for creating the menu item:
chrome.contextMenus.create( {
                    id: guid(),
                    title: "Remove this pane"
                }, function(){
                    console.log( "Created" )
                })

Dont know of an extension that use this

**Comment by ogdans3** [comment]
My bad, found the problem

**Comment by nightwing** [comment]
see http://stackoverflow.com/a/28566440/1743328, most likely you need to use 'contexts': ['editable'],

> Dont know of an extension that use this  

aren't you working on a one?

**Comment by ogdans3** [comment]
Added the wrong piece of code when i found the answer

**Comment by ogdans3** [comment]
Yup. it works now, total derp moment from me. Sorry about that

Thanks man :D
