### ISSUE TITLE
Scrollbars disappear under different conditions

### ISSUE THREAD

**Issue by matthew-dean** [ajaxorg/ace#2713]
I've been trying to figure out scrollbar woes since #2320, and have revisited them to try to get them to work. I finally figured out that the scrollbars disappear permanently (usually) if I:

1. Call setSession() with a document that requires a vertical scrollbar
2. Call setSession() with a doc that does not require a vertical scrollbar 

After a scrollbar doesn't show, then it doesn't seem to reappear.

I went back to the kitchen sink to try to troubleshoot again. However, I noticed as I played around there, that scrollbars disappear there as well. (On Mac El Capitan / Chrome 46.0.2490.71). If I keep playing with them, scrolling up and down, then sometimes they'll disappear on some of the scroll actions for a while. If I start scrolling just as the scrollbar is fading out, the scrollbar remains "faded" as it moves up and down. If you wait for a bit and scroll again, then you'll get scrollbars. (All of which differs from normal scrollbar behavior.) In my case, once scrollbars disappear, it seems impossible to get them to appear again. But I wonder if the behavior in the kitchen sink demo is related, since they do stay hidden for some scroll actions.

**Comment by sami420** [comment]
this fixed it for me try this easy fix 
http://heresthethingblog.com/2015/03/10/mac-tip-macs-scroll-bars/

**Comment by matthew-dean** [comment]
I considered later that it's actually possible it's a Chrome + Mac bug. In fact, either the Mac had an update that fixed the bug, or I changed something which circumvented the bug. Which means that now, in most cases, the scrollbars work fine, so I'll close.
