### ISSUE TITLE
Setting a theme doesn't remove previous theme styles

### ISSUE THREAD

**Issue by matthew-dean** [ajaxorg/ace#2714]
I noticed when using ```setTheme()``` that the previous theme style block is not removed. In my case, the previous theme added styles that were not explicitly overwritten by the second theme, which resulted in a "mix" of styles from both themes.

**Comment by nightwing** [comment]
themes are supposed to prefix all their rules with their cssClass, so that they apply only to editors with that class
https://github.com/ajaxorg/ace/blob/v1.2.0/lib/ace/theme/ambiance.css#L1
https://github.com/ajaxorg/ace/blob/v1.2.0/lib/ace/theme/ambiance.js#L27

**Comment by matthew-dean** [comment]
I understand that. In this case, I wanted a few other parts of the UI (outside the editor) affected by the theme. Which is not necessarily a targeted use case. But I'm curious, why leave the unused scraps of other stylesheets in the DOM? It was just surprising that themes weren't "replaced" really, each new theme just continues to add to the page. Meaning if, for whatever reason, a person tried out 100 different themes before settling on one, there would be 99 unused stylesheets.

**Comment by nightwing** [comment]
There can be several editors on the page and they can use different themes at the same file, so styling elements outside of editor wouldn't work well.
Since unused stylesheets do not cause noticeable performance issues, and loading a stylesheet is usually slow, keeping them seems reasonable

**Comment by matthew-dean** [comment]
Okay, fair enough. I'll close and set a body class when themes change, which should work fine.
