### ISSUE TITLE
 UndoManager.isClean() is undocumented

### ISSUE THREAD

**Issue by vanillajonathan** [ajaxorg/ace#2715]
The `isClean` method in `UndoManager` is undocumented.

https://ace.c9.io/#nav=api&api=undomanager

**Comment by matthew-dean** [comment]
A lot of the methods in the API are undocumented or very sparsely documented. Maybe Ace documentation should be a separate repo with separate issues?

**Comment by vanillajonathan** [comment]
Or at least it needs to be documented that it is undocumented.

So developers can at least know that it exist, and not an internal that they can't rely on.

**Comment by kimlisa** [comment]
also, `isClean` is not exposed on the `interface UndoManager`: https://github.com/ajaxorg/ace/blob/master/ace.d.ts#L380

And it seems `isClean` is same as `isAtBookmark`? which IS exposed: https://github.com/ajaxorg/ace-builds/blob/53be42342df216d2d25dc60a12dfcb263c6f0592/src/ace.js#L14812

but `isAtBookmark` is less clear in meaning then `isClean`

**Comment by vanillajonathan** [comment]
Please improve the documentation!

**Comment by andrewnester** [comment]
Released in Ace 1.12.5
