### ISSUE TITLE
UndoManager.reset() does not exist

### ISSUE THREAD

**Issue by vanillajonathan** [ajaxorg/ace#2716]
According to the API documentation there should be a `reset` method in the `UndoManager`.
But it does not seem to exist.

`editor.getSession().getUndoManager().reset()` returns `undefined`.

https://ace.c9.io/#nav=api&api=undomanager

Edit: my bad. The function **is** defined but does not return anything.

**Comment by matthew-dean** [comment]
Shouldn't it just erase undo history and return undefined?

**Comment by vanillajonathan** [comment]
Yes, you are correct.

I noticed that after I reported the bug. I was erroneous. This works as intended, I was just momentarily confused. Hence why I edited my issue. Please close this issue.
