### ISSUE TITLE
Create multiple cursor

### ISSUE THREAD

**Issue by ghost** [ajaxorg/ace#2717]
Hi,
I have searched on Google for create multiple cursor with javascript, but all examples i've found doesn't work. I have read that need to take example on https://github.com/ajaxorg/ace/blob/master/lib/ace/search_highlight.js but I don't found which file use this SearchHighlight Object ?

Thank's by advance.

**Comment by nightwing** [comment]
use 

```js
var Range = require("ace/range").Range
editor.selection.addRange(new Range(0,0, 1,1))
```

or

```js
editor.selection.fromJSON([{
    start: {row: 0, column: 0}, end: {row: 1, column: 1}, isBackwards: true
}, {
    start: {row: 2, column: 0}, end: {row: 3, column: 1}
}])
```
