### ISSUE TITLE
Show info on marker :hover?

### ISSUE THREAD

**Issue by foo123** [ajaxorg/ace#2720]
Hello, i have some markers in editor (which mark errors), but i also want to show the error text (at least initialy) when user hovers over a marker (error is also displayed in gutter), but for multiple errors on same line, it is better to show the specific error on that marker as well.

Have found this issue https://github.com/ajaxorg/ace/issues/2179, but as far as i can tell, this is the same tooltip moving around the editor when user hovers. i want sth else (and if possible **without duplicating ace code** or requiring too much, as this is for an add-on, `ace-grammar`).

At least initialy a `title` attribute on marker would be good. Have added custom `renderer` on the markers (by duplicating unfortunately ace code from marker, just to add a  `title` attribute in marker `div`). This works, the title is added, but not displayed on `mouse-over` (ps the markers are background markers)

screeenshot:

![snap-2015-10-24-at-18 14 03](https://cloud.githubusercontent.com/assets/1263582/10711139/0c52e0fc-7a7b-11e5-9af7-cb1b083531a4.png)

ACE version 1.2.0 (latest build)

**Comment by nightwing** [comment]
For this we'd need to implement something similar to https://github.com/ajaxorg/ace/blob/master/demo/kitchen-sink/token_tooltip.js, but unfortunately i do not have time to work on that in near future.

Title attribute doesn't work because marker nodes have `pointer-events: none`

**Comment by foo123** [comment]
Ok i see, i will work around this for now, i dont know if you want this issue open so i'll just leave it.
But i would suggest to have an option to show some info on marker hover, rather easily (if this is sth like tokenTooltip its ok, but sth not requiring too much, just to set an attribute or sth)

Plus i would suggest to add version property on ace main referenbce to know which versioin of ace is loaded.  Thanks!

**Comment by groubis** [comment]
Hello everyone. foo123 did you managed to find a workarround? I am trying to achieve the same funcionality by implementing jquery ui tooltips and adding title attributes to the markers without success.

**Comment by foo123** [comment]
@groubis No did not pursue this further per nighwing's comment. But maybe changing the css attribute of a marker (with a custom marker renderer) so that `pointer-events` are not discarded and adding a `title` attribute on marker html mght work (havent tried, although i dont know if this would conflict with the editor, having marker receive pointer events, else tokenTooltip might be an option). In any case this should be a feature of the editor as markers should be able tol show some info on hover or sth

**Comment by akoreman** [comment]
Reopening this issue after community discussion https://github.com/ajaxorg/ace/discussions/5082.

**Comment by InspiredGuy** [comment]
after merging https://github.com/ajaxorg/ace/pull/5113 you should be able to add a [MarkerGroup](https://github.com/ajaxorg/ace/blob/master/src/marker_group.js#L8) for an edit session, which will display the markers, and use an instance of [HoverTooltip](https://github.com/ajaxorg/ace/blob/master/src/tooltip.js#L164) to display desired content in a tooltip - you provide a callback which would receive hover position as a parameter, and based on that you can decide what needs to be shown in a tooltip. see [demo source](https://github.com/ajaxorg/ace/blob/master/demo/kitchen-sink/demo.js#L167) for an example.
closing this issue as it is resolved with https://github.com/ajaxorg/ace/pull/5113, and will be available in next release
