### ISSUE TITLE
Add syntax highlighting for Swift 2.0

### ISSUE THREAD

**Issue by jublo** [ajaxorg/ace#2728]
https://developer.apple.com/swift/blog/?id=29

https://twitter.com/iosengineer/status/658394485265596416

**Comment by nightwing** [comment]
Is swift 2 syntax different from swift 1? We already have a mode for that one https://github.com/ajaxorg/ace/blob/master/lib/ace/mode/swift.js

**Comment by matthew-dean** [comment]
@nightwing I'm not a Swift developer but I believe so. Here's a few: https://www.hackingwithswift.com/swift2

**Comment by jublo** [comment]
@nightwing More info here, too: http://www.raywenderlich.com/108522/whats-new-in-swift-2

**Comment by nightwing** [comment]
Added two new keywords in https://github.com/ajaxorg/ace/commit/34380fb2589f5f2d4d2ef434a0de1de7b92c31d7

**Comment by jublo** [comment]
@nightwing Will be part of which next release to CDN?

**Comment by nightwing** [comment]
the two new keywords are in 1.2.2, swift mode is already available in v1.2.1
