### ISSUE TITLE
TypeError: "delta.range is undefined", ACE 1.2.0 worker-json.js

### ISSUE THREAD

**Issue by foo123** [ajaxorg/ace#2730]
Hi, im updating my ace build to latest `1.2.0` (from `ace-buils/`). Using it in an add-on (`ace-grammar`),
which does its own validation through worker and for this purpose, loads the `woker-json.js` (see related old issue https://github.com/ajaxorg/ace/issues/1766) to load the necessary `ace` defines for a worker.  This was working perfectly in  previous `ace` build i was using but now continously displays this error (which by the way exists nowhere in `worker-json.js` source code per-se, i.e there is no `delta.range` variable accessed).

This prevents from updating the add-on to latest version with latest `ace` build. As seen in `changelog` for `1.2.0`, there were some changes with `deltas` (for uniform handling), is this related?

Thanks.

**Comment by nightwing** [comment]
The format of delta have changed, instead of delta.range there are delta.start and delta.end.
Could be that you are using worker-json from older version with ace 1.2.0?

**Comment by foo123** [comment]
i dont think so, so after your comment, i copied the worker-json.js from ace-builds/src-noconflict to the test folder and tried again. Still the same (screenshot below) BTW, how would i know that a file is not up-to-date or an older version?


![snap-2015-10-28-at-11 17 27](https://cloud.githubusercontent.com/assets/1263582/10784241/b4649550-7d65-11e5-9f22-279ea301fcc5.png)

**Comment by nightwing** [comment]
I do not see any errors with https://github.com/foo123/ace-grammar/blob/master/test/grammar-xml.html
Also there is no delta.range on line 1300 in the new [version](https://github.com/foo123/ace-grammar/blob/master/test/ace/worker-json.js#L1300) but there was in the [old one](
https://github.com/foo123/ace-grammar/blob/bd829fcaea1ad88a6eebde08ecc8cd5b2f7ab819/test/ace/worker-json.js#L1300)

**Comment by foo123** [comment]
Hmm, what is going on, maybe the update on ace-builds was not complete or somehow the previous version is used. Will check it and get back to this issue if needed

**Comment by foo123** [comment]
Exactly as mentioned if first comment, there is **no such line of code** in `worker-json.js` that means i'm using indeed the latest version, yet i still get this error. i'm buffled, any ideas?

**Comment by nightwing** [comment]
Maybe it's cached in the browser, try with chrome

**Comment by foo123** [comment]
Yes it works in chrome fine with latest version and annotations and markers update as needed. it seems this is either a FF issue or some caching issue with workers. How can that be? Have you seen it before?  (latest FF v 41.0.2)

**Comment by foo123** [comment]
i consider this issue solved. Is it possible you can take alook in my other issue for showing title info on markers (https://github.com/ajaxorg/ace/issues/2720) so i can add it to the latest update?  In any case thanks for the effort.

**Comment by foo123** [comment]
For anyone who may have similar issue (as this happens in chrome as well, http://stackoverflow.com/questions/12124261/chrome-not-loading-latest-version-of-web-worker-script-runs-a-cached-version)  The solution was to compute a unique pes session `NOCACHE` token (once in every `ace-grammar` add-on loading) and use it along with the `workerUrl` to get the latest version (but also the cached version for multiple worker calls **in the same session**)

For example:

```javascript
ace_worker_base: this_path.base + '/' + config.moduleUrl("ace/worker/json") + NOCACHE;
```

**Comment by nightwing** [comment]
there is also a setting in devtools to disable cache.

**Comment by foo123** [comment]
i dont want to disable cache or empty the cache as i need some things cached (and not re-loaded), but selectively bypass or refresh the cache as needed. Maybe this is best option
