### ISSUE TITLE
How to bind scroll event ?

### ISSUE THREAD

**Issue by hojas** [ajaxorg/ace#2737]
How to bind scroll event to the editor ?

```js
editor.on('scroll', function() {
    //...
}) ?
```

or 

```js
editor.getSession().on('scroll', function() {
    //...
}) ?
```

**Comment by nightwing** [comment]
```js
editor.session.on("changeScrollTop", function() {})
editor.session.on("changeScrollLeft", function() {})
```

**Comment by hojas** [comment]
thx!

**Comment by rocketinventor** [comment]
@nightwing is there a way to get current, first _and_ last line number?

**Comment by prashant-saxena** [comment]
> 
> 
> ```js
> editor.session.on("changeScrollTop", function() {})
> editor.session.on("changeScrollLeft", function() {})
> ```

Once event is binded then how to unbind it again. I have tried
```
editor.session.off();
editor.session.off('scroll');
```

**Comment by nightwing** [comment]
```
var listener = function() {}
session.on("eventName", listener)
session.off("eventName", listener)
```

**Comment by prashant-saxena** [comment]
> 
> 
> ```
> var listener = function() {}
> session.on("eventName", listener)
> session.off("eventName", listener)
> ```

Actually I have tried using an empty function but it doesn't work.
```
session.off('changeScrollTop', function() {
});
session.off('changeScrollLeft', function() {
});
```

**Comment by nightwing** [comment]
you need to pass the same function to on and off methods
