### ISSUE TITLE
suspend ace ? 

### ISSUE THREAD

**Issue by gbaumgart** [ajaxorg/ace#2744]
is there a slight chance to suspend the editor? Suspending means: stop any event processing (if there are handlers for elements outside the container). If possible also workers or plugins.

just being careful and I hope somehow its already done (eg visible at all)

thanks!

**Comment by gbaumgart** [comment]
or it might be more clean to just share an instance from cache....dunno

**Comment by nightwing** [comment]
You could use

```js
editor.container.style.pointerEvents = "none"
editor.renderer.content.style.pointerEvents = "none"
editor.textInput.getElement().disabled = true
editor.renderer.freeze()
editor.session.$stopWorker()
```

But what are you trying to do?

**Comment by gbaumgart** [comment]
thanks! 
just doing some optimizations, making sure nothing runs as long necessary (being shown at least).
g
