### ISSUE TITLE
Strange line jumps when using arrow keys to move cursor

### ISSUE THREAD

**Issue by thomasbiesaart** [ajaxorg/ace#2750]
Sometimes when you move the cursor using the arrow keys it will make an unexpected jump. I tested this in the kitchen sink too and I find the same behaviour. It seems to be related to soft tabs.

Reproduce:

    Envirionment:
    - Site: https://ace.c9.io/build/kitchen-sink.html
    - Code: Math.konijn{s.db_host, tonumber{s.db_port}, s.db_name, s.db_user, s.db_pass, d, s.db_servicenameblablaa};
    - Tab Size: 3
    - Soft Tabs: on
    Steps:
    - Set the cursor to the start of the line
    - Hold the right arrow key and watch for the jump after `Math.k`

**Comment by nightwing** [comment]
I couldn't reproduce this issue.
maybe there was a hidden character in the code example, that got filtered out by github.

Could you try running to see  what characters there are in the editor.

```js
editor.getValue().replace(/[\x00-\x19\x7f-\uffff]/g, function(e) {
    return "\\u{"+e.charCodeAt(0).toString(16) + "}" 
})
```

**Comment by thomasbiesaart** [comment]
Make sure you set the tab size to 3.
It does not happen when it is set to the default 4.
It works for me if I copy the code from github

**Comment by nightwing** [comment]
I used `editor.session.setTabSize(3)` in the console.
For which language highlighter does this happen? Browser/OS might be relevant too.

**Comment by thomasbiesaart** [comment]
Tested in Chrome and Firefox.  Os was windows 10

**Comment by thomasbiesaart** [comment]
Tested on Firefox and chrome. On windows 10. The language setting in the kitchen sink was javascript


Sent from my Samsung device

-------- Original message --------

**Comment by thomasbiesaart** [comment]
The difference might be that I set the tab size using the ctrl + , menu

**Comment by Badbond** [comment]
I have this problem as well and I can reproduce with the steps given from @thomasbiesaart. 
The problem expands as pressing DELETE at that location results in deleting the rest of the line.

**Comment by nightwing** [comment]
This is a bug in `ctrl+,` menu which sets tabsize to a string instead of number

**Comment by thomasbiesaart** [comment]
Thank you very much. It seems that our software did the same
