### ISSUE TITLE
Can't find newlines when searching or replacing.

### ISSUE THREAD

**Issue by LucaScorpion** [ajaxorg/ace#2751]
Hi,

I was playing around with ace in the kitchen sink (https://ace.c9.io/build/kitchen-sink.html) and I noticed when finding or replacing text you can't search for newlines (\n or \r). This is the case when searching plain text but also when using regex. Is there a fix or at least a workaround for this?

Thanks, Luca.

**Comment by nightwing** [comment]
Unfortunately this is a known issue https://github.com/ajaxorg/ace/issues/2059#issuecomment-51692942, a possible solution is to search in whole text using a webworker, similar to what cloud9 does
