### ISSUE TITLE
Pressing CapsLock (to create uppercase) works as the delete button in android 

### ISSUE THREAD

**Issue by sdkcarlos** [ajaxorg/ace#2755]
For some reason when editing code in google chrome (android) pressing the CapsLock button (for example to write : var un = previousVar;) deletes the previous carácter of the uppercase (var un = previou) .

ISSUE: CapsLock button acts like the delete button.

Having issue editing with kitchen sink and all demos of ace in android.

**Comment by icflorescu** [comment]
+1

**Comment by nightwing** [comment]
With which keyboard do you see this? [Hacker's Keyboard](https://play.google.com/store/apps/details?id=org.pocketworkstation.pckeyboard&hl=en) usually works well on android

**Comment by sdkcarlos** [comment]
Yes you're right ! Hacker's keyboard works perfectamente with ace .

With the default android keyboard

**Comment by vanillajonathan** [comment]
I can reproduce this on a Nexus 5X running Android 6.0.1 using both Chrome 50 as well as WebView 49 using [Google Keyboard](https://play.google.com/store/apps/details?id=com.google.android.inputmethod.latin) 4.1.

This issue seems to be related to #2038.

**Comment by adamjimenez** [comment]
this is a dupe of #2038

**Comment by nightwing** [comment]
This should be fixed by https://github.com/ajaxorg/ace/pull/3635, please let us know if you still can reproduce this on http://ace.c9.io. Thanks.
