### ISSUE TITLE
Cursor position issues in touch screen windows 10 device

### ISSUE THREAD

**Issue by codehz** [ajaxorg/ace#2756]
like this,I do not know what word to use to describe this like a raindrop. . .
![image](https://cloud.githubusercontent.com/assets/13158903/11018197/e95b1db0-85f8-11e5-8ace-206b340ff61f.png)
the issues only occurs in the touch screen windows 10
This is a great influence on the touch-screen experience, because in touch windows, the only way to select a text.
![image](https://cloud.githubusercontent.com/assets/13158903/11018211/e0f4f794-85f9-11e5-8f83-15b941e27f18.png)

**Comment by sdkcarlos** [comment]
:+1:
