### ISSUE TITLE
ReadOnly disables commands?

### ISSUE THREAD

**Issue by ogdans3** [ajaxorg/ace#2757]
When i add a custom command to ace it seems to disable this command whenever it goes into readonly mode. How can i prevent it from disabling the commands? They do not try to change the session in any way, is there a reason to disable all commands when in readonly mode? 

Thanks

**Comment by nightwing** [comment]
Add `readOnly: true` to commands that should be allowed in readOnly mode. See https://github.com/ajaxorg/ace/blob/v1.2.0/lib/ace/commands/default_commands.js#L95
 https://github.com/ajaxorg/ace/blob/v1.2.0/lib/ace/commands/command_manager.js#L48-L49

**Comment by ogdans3** [comment]
Great that works, thanks man!
