### ISSUE TITLE
smart codedeletion deletes the wrong parenthesis

### ISSUE THREAD

**Issue by andrewsutjahjo** [ajaxorg/ace#2758]
in the following if:  
if(x == foo()) 
backspacing the first closing parenthesis with the intention of deleting foo() only deletes the closing parenthesis.
leaving you with:  
if(x == foo()  
backspacing one more to delete the second opening parenthesis deletes both the second opening parenthesis and the last remaining closing parenthesis. 
This leaves you with: 
if(x == foo  
This leaves the if function open and the programmer slightly annoyed.

**Comment by nightwing** [comment]
Do you know if there is an editor that handles this well?
Sublime text seems to behave same way as Ace.

**Comment by andrewsutjahjo** [comment]
Sorry, I don't know any editors that handle this well. I don't have a lot
of experience with editors though.


ᐧ
