### ISSUE TITLE
Composition style underline is wrong in dark themes

### ISSUE THREAD

**Issue by vanillajonathan** [ajaxorg/ace#2761]
Input composition is handled by the `.ace_text-input.ace_composition` class.

It seems the style is not handled so well by the dark themes, such as Pastel on dark, Terminal and Tomorrow Night, just to mention a few.

The underline is **black**, but it should be the same color as the text.
- https://github.com/ajaxorg/ace/blob/master/lib/ace/theme/pastel_on_dark.css
- https://github.com/ajaxorg/ace/blob/master/lib/ace/theme/terminal.css
- https://github.com/ajaxorg/ace/blob/master/lib/ace/theme/tomorrow_night.css

**Comment by nightwing** [comment]
The underline is handled by browser/os, same issue is present for a textarea with background:black and color:white

**Comment by vanillajonathan** [comment]
You are right.

I can confirm it on Chrome 46 running on Android 6.0: http://jsfiddle.net/os2xcmzL/

**Comment by nightwing** [comment]
https://github.com/ajaxorg/ace/pull/3635 added `useTextareaForIME` option, setting it to false will draw custom underline of correct color.
