### ISSUE TITLE
Toggling Comments in CoffeeScript

### ISSUE THREAD

**Issue by plmrry** [ajaxorg/ace#2763]
When toggling line comments using `⌘`–`/`, existing comments are *toggled* rather than being nested within a new comment.

This:
![screen shot 2015-11-12 at 11 53 43 am](https://cloud.githubusercontent.com/assets/688617/11126357/1fe4ebca-8934-11e5-86bf-23225c26e97e.png)

Becomes:
![screen shot 2015-11-12 at 11 53 57 am](https://cloud.githubusercontent.com/assets/688617/11126361/261a05e8-8934-11e5-9248-29d4423d04e0.png)

Notice that `dont_do_this()` is now un-commented.

Also, the comment token (`#`) is indented with each line of code, rather than being added at the first column of each line, which I find much more readable.

It should instead look like this, (which is the case in Sublime and Atom):
![screen shot 2015-11-12 at 11 54 14 am](https://cloud.githubusercontent.com/assets/688617/11126364/2c26c12e-8934-11e5-9527-2563b5a30b14.png)

**Comment by nightwing** [comment]
coffeescript was using old implementation for toggling 
Changed it to use new shared one which should work same as in atom.
Please test it using https://rawgit.com/ajaxorg/ace/master/kitchen-sink.html

**Comment by plmrry** [comment]
Works great, thank you!
