### ISSUE TITLE
global is undefined

### ISSUE THREAD

**Issue by stevehu** [ajaxorg/ace#2765]
I am using ace from react-ace in react-schema-form for schema editing but have to update the code a little bit to make it work with webpack. The following line in /lib/ace/config.js is not working as global is not defined.

```
    if (!global.document)
```

My workaround is to check global before checking global.document. 

```
 if (!global || !global.document)
```

Just wondering if you guys can have this fixed checked in. Let me know if you need a pull request for that. Thanks.

**Comment by nightwing** [comment]
`if (!global || !global.document) return`
before https://github.com/ajaxorg/ace/blob/master/lib/ace/config.js#L147 should be ok, i think.
Detecting ace load path won't work, but it's probably not needed  if ace is not loaded in packed mode.

Is your project open source? I'd be interested to see how do you use ace with webpack.

**Comment by stevehu** [comment]
Yes. It is open sourced and here is the link.

https://github.com/networknt/react-schema-form

Basically, it uses react-ace with brace and subsequently ace. I have my customized react-ace/brace for now installed from my own repo to workaround it. 

once you clone the project, 

npm install
npm start

To reproduce the issue, just installed the react-ace and brace from public npmjs. 

Thanks.

**Comment by andrewnester** [comment]
This has been fixed by this commit already https://github.com/ajaxorg/ace/commit/a496f5fa0bbfbc093707233db29f4f944308e653
