### ISSUE TITLE
Incorrectly highlighting 'isize' and 'usize' suffix in Rust.

### ISSUE THREAD

**Issue by Grazfather** [ajaxorg/ace#2766]
I reported it where I found it in rust-lang/rust-by-example#662

@mdinger Thinks it can be fixed here:
https://github.com/ajaxorg/ace/blob/master/lib/ace/mode/rust_highlight_rules.js#L129-L134

Here is where they changed it in rust: rust-lang/rust#22496

**Comment by mdinger** [comment]
To be precise, `is` and `us` are no longer valid suffixes on rust numbers. The new suffixes are `isize` and `usize`.

**Comment by nightwing** [comment]
https://github.com/ajaxorg/ace/commit/e8423ae1ba0a03ec9c6a4f4ce0a439865f389798 should fix this issue

**Comment by mdinger** [comment]
That looks so much better. That one regex was so messy before.

**Comment by Grazfather** [comment]
It does look better, and appears to work for me, but it looks like it breaks float suffixes.
![image](https://cloud.githubusercontent.com/assets/497310/11159466/9fcc8b00-8a14-11e5-83dc-e50afa0ce267.png)

**Comment by Grazfather** [comment]
This is what it looks like on master.
![screen shot 2015-11-13 at 2 43 51 pm](https://cloud.githubusercontent.com/assets/497310/11159508/fcb14ec8-8a14-11e5-9ec5-57be01db709c.png)

**Comment by mdinger** [comment]
Maybe:
```diff
- /(?:[0-9][0-9_]*\.)(?:[0-9][0-9_]*)(?:[Ee][+-][0-9][0-9_]*)?(?:f32|f64)?\b/
+ /(?:[0-9][0-9_]*)(?:\.[0-9][0-9_]*)(?:[Ee][+-][0-9][0-9_]*)?(?:f32|f64)?\b/
```

**Comment by nightwing** [comment]
Added that and also added `?` for  `(?:\.[0-9][0-9_]*)`, to highlight numbers like `1e+5`
https://github.com/ajaxorg/ace/pull/2770/files#diff-6e75d9c1f4e549bcdc128975b582889cR132

**Comment by mdinger** [comment]
Yeah, I meant to put that it but forgot.

**Comment by nightwing** [comment]
Ok, considering that as a review +1 for https://github.com/ajaxorg/ace/pull/2770
Thanks.

**Comment by Grazfather** [comment]
Quick work. Thanks a lot.
