### ISSUE TITLE
dom.toggleCssClass

### ISSUE THREAD

**Issue by shadowcodex** [ajaxorg/ace#2781]
When trying to implement the full screen options on the ace editor, I get the following error:

`Uncaught TypeError: dom.toggleCssClass is not a function`

However here is my code:

```javascript
var dom = require(['ace/lib/dom']);

function makeFullScreen() {
    var fullScreen = dom.toggleCssClass(document.body, "fullScreen")
    dom.setCssClass(editor.container, "fullScreen", fullScreen)
    editor.setAutoScrollEditorIntoView(!fullScreen)
    editor.resize()
};

// -- FullScreen -- //
editor.commands.addCommand({
    name: "Toggle Fullscreen",
    bindKey: "F10",
    exec: function(editor) {
        makeFullScreen();
    }
});
```

I'm fairly sure that the function does exists. Thoughts? Help?

**Comment by nightwing** [comment]
`require([...], function(m) {})` is the async version it doesn't return the module
you need to use `var dom = require('ace/lib/dom');` instead
