### ISSUE TITLE
Creating worker from Browserified file

### ISSUE THREAD

**Issue by niksy** [ajaxorg/ace#2782]
I’m trying to create worker for YAML linting via [js-yaml](https://github.com/nodeca/js-yaml) but I’m getting the same errors as #2433. I’ve tried to use derequire but to no avail. Here is the current worker file (built version) with the line which creates problem: https://github.com/niksy/ace-builds/blob/yaml-lint/src/worker-yaml.js#L1334. The original pre-build file is here: https://github.com/niksy/ace/blob/yaml-lint/lib/ace/mode/yaml/js-yaml.js

The plan is to use resulting file with [brace](https://github.com/thlorenz/brace) and it’s update script to create simplified require structure, but I don’t think this error has anything to do with this.

Am I doing something wrong here?

**Comment by nightwing** [comment]
the issue with `function ace.define(name, deps, m) {` should have been fixed by https://github.com/ajaxorg/ace/commit/6bc991d551d7fb30e64e6cc1b6947b80845f6609, try using master instead of 1.1.9.

**Comment by tsneed290** [comment]
Hi @niksy, I'm also interested in YAML linting with brace. Would you potentially open-source your worker?

**Comment by the-santosh** [comment]
@niksy did you get success in creating yaml-worker ?

**Comment by niksy** [comment]
@the-santosh @tsneed290 yeah, I did, you can see it in my forked repo. As for open-sourcing it, I didn’t think about that, I always thought this is ideal for original project, but as I recall, there was the issue of some legal/ownership nature, so it’s really not up to me to decide if this should go to core project or stay in the forked one.

**Comment by the-santosh** [comment]
Thanks @niksy :), good job! Could you please make a pull request to core project, so that it will get reviewed and merged with core project and will get be available to all.
