### ISSUE TITLE
Creating editors in a loop?

### ISSUE THREAD

**Issue by knod** [ajaxorg/ace#2785]
When I create editors in a loop, the earlier editors are overwritten by the later editors.

Here's an example showing the problem when the editors get created in a loop: http://jsfiddle.net/yvvpge14/11/
```
var ids = [ 'editor1', 'editor2' ];

var initial = '';

for ( var idi = 0; idi < ids.length; idi++ ) {
    var id = ids[ idi ];
    
    var editor = ace.edit( id );
    // Shows that initially they are unique
    initial = initial + editor.container.id + '<br>';
    $('#initial').html( initial );
    
    editor.setTheme( 'ace/theme/monokai' );
    editor.getSession().setMode( 'ace/mode/javascript' );
    
    // Shows how previous editor is being overwritten
    editor.on( 'input', function ( evnt ) {
        $('#after-loop').html( editor.container.id );
    });  // End editor on input
}
```

Here's an example with editors being created normally: http://jsfiddle.net/yvvpge14/12/
```
var ids = [ 'editor1', 'editor2' ];
var initial = '';

var createEditor = function ( id ) {
    
    var editor = ace.edit( id );
    // Shows that initially they are unique
    initial = initial + editor.container.id + '<br>';
    $('#initial').html( initial );
    
    editor.setTheme( 'ace/theme/monokai' );
    editor.getSession().setMode( 'ace/mode/javascript' );
    
    // In this non-loop version, editor is not being overwritten
    editor.on( 'input', function ( evnt ) {
        $('#after-not-loop').html( editor.container.id );
    });  // End editor on input
    
    return editor;
};  // End createEditor()

createEditor( ids[0] );
createEditor( ids[1] );
```

**Comment by nightwing** [comment]
You are changing editor variable on every iteration of the loop so it of course changes.This is not related to Ace in any way.
Take a look at https://jslinterrors.com/dont-make-functions-within-a-loop (just a link from top of the google search) if you need more info.

Also note that ace passes the event target as a second argument to event listener so `o.on("input", function (e, o) {` should work too.

**Comment by knod** [comment]
@nightwing: Thank you very much, I've never run into this aspect of js. I'm going to explain my solution for anyone else who runs into this.

I did a little more research and, from what I understand, it turns out that the event listener (I'm not sure if it's all functions, or just event listeners) is actually created after the for loop is done. The function holds onto the variable name, not the value, and waits to actually implement it later. "...by the time the event handlers are executed, the for-loop has completed its iterations and the value of [your variable has changed]" (from this article: http://www.mennovanslooten.nl/blog/post/62).

By creating a closure, inside which you return the function you actually want:
```javascript
(function ( iNewScope ) { 
    return function (iNewScope) {
        do something with iNewScope
    }
})( i );
```
you make sure the outer function gets called right away and doesn't wait for the for loop to end. It then returns a fully formed version of the function you actually want to use.

Here's the altered fiddle: http://jsfiddle.net/yvvpge14/14/
Here's my altered code:
```javascript
// ==========================
// Using a loop to create editors, the right way
// ==========================
var ids = [ 'editor1', 'editor2' ];
// The string that shows us the initial creation of the editors
var initial = '';

for ( var idi = 0; idi < ids.length; idi++ ) {
    // Get the id of the element we want to use for the editor
    var id = ids[ idi ];
    
    // Create the editor, placing the element
    var editor = ace.edit( id );
    
    // Just for us to prove we've made the editor
    initial = initial + editor.container.id + '<br>';
    $('#initial').html( initial );
    
    // Settings for the editor
    editor.setTheme( 'ace/theme/monokai' );
    editor.getSession().setMode( 'ace/mode/javascript' );
    
    // Create an event listener in a for loop
    // Check out http://www.mennovanslooten.nl/blog/post/62
    editor.on( 'input', function ( editorCopy ) {
        // !!: Not sure if we can really pass the event into here
        return function ( evnt ) {
            // Proving which editor has been assigned to this
            // event listener (Check the bottom box when
            // typing in an editor)
            $('#after-loop').html( editorCopy.container.id );
		}
    }( editor ));  // End editor on input
}  // End for each id
```

**Comment by knod** [comment]
@nightwing: Didn't see your not about what Ace passes into the event. It'll help a lot, thanks!

**Comment by knod** [comment]
@nightwing: Actually, I'm not sure how exactly how to get that working. First, the parameters seem to be handed in the other way around - elem.on("input", function (elem, editor) {. Secondly, I'm not sure exactly what I'm getting for elem, as usually I can log elements to the console just fine and here, they seem to come out as Object{} (just as a string): http://jsfiddle.net/yvvpge14/16/
