### ISSUE TITLE
Resize ace editor container width

### ISSUE THREAD

**Issue by ManojkumarV** [ajaxorg/ace#2787]
![screenshot from 2015-12-01 13 41 06](https://cloud.githubusercontent.com/assets/10399151/11495511/c1daa9b8-9831-11e5-91fd-8712c85c85f2.png)

I'm working on a minimap implemetation for ace editor. The minimap is attached to the div and moved right in which ace editor is loaded. 
Few characters in the right side of the file are hidden under the minimap div. 
Have to change the width of the text container with out changing the location of vertical scroll bar so that the contents won't get hidden under the div.

**Comment by nightwing** [comment]
Looks very cool, are you using canvas or dom for rendering it?

Right now there is no support for reserving space on right side,  but it is easy to add by adding it to `this.scrollBarV.getWidth()` in https://github.com/ajaxorg/ace/blob/v1.2.2/lib/ace/virtual_renderer.js#L414-L417

**Comment by ManojkumarV** [comment]
Thank you. I'm using DOM for rendering it.
