### ISSUE TITLE
Get TypeError when using ace with requirejs

### ISSUE THREAD

**Issue by tjwudi** [ajaxorg/ace#2796]
I am using ace with my own requirejs installation. I got a TypeError shown as below **sometimes (like 1 out of 20 loads)**.

![image](https://cloud.githubusercontent.com/assets/5257816/11638823/ed638bda-9cf6-11e5-8d3a-97f16c7db790.png)

However, when using built version, I won't have this issue. So I doubt there is an dependency issue?

My requirejs config (partial).

```
require.config({
  baseUrl: '/path/to/app',
  paths: {
    ace: '../vendor/ace/lib/ace',
  }
```

**Comment by nightwing** [comment]
which version of require.js did you use?

**Comment by tjwudi** [comment]
@nightwing ~2.1.22
