### ISSUE TITLE
Editor text doesn't resize after being wedged by dev tools vertically (inspect element tool in generic sense)

### ISSUE THREAD

**Issue by igauravsehrawat** [ajaxorg/ace#2797]
I feel this issue would make sense if i put some screenshots.

1. Normal text editor
![screen shot 2015-12-08 at 9 46 07 pm](https://cloud.githubusercontent.com/assets/3696327/11661080/1377c714-9df6-11e5-8e93-8b2410d715ce.png)

2. Text editor wedged by inspect element aka dev tools
![screen shot 2015-12-08 at 9 46 46 pm](https://cloud.githubusercontent.com/assets/3696327/11661102/34296526-9df6-11e5-9860-dfdc22cdba09.png)

3. Problem/issue : Editor text doesn't resize/flow to original 
![screen shot 2015-12-08 at 9 47 05 pm](https://cloud.githubusercontent.com/assets/3696327/11661127/5848e8aa-9df6-11e5-861b-0536d6bc3296.png)

As part of debugging I tried `editor.renderer.updateFull()`/`editor.renderer.updateText()` api on resize event and manually but they didn't helped much.

Thanks

**Comment by nightwing** [comment]
Did you try `editor.resize()`?
ace.edit calls that automatically when window is resized https://github.com/ajaxorg/ace/blob/master/lib/ace/ace.js#L107

**Comment by igauravsehrawat** [comment]
@nightwing Excellent!! That works. I thought it would be render's problem. 

Quick question :
Where would one use `editor.renderer.updateFull()`/`editor.renderer.updateText()` api, any peculiar use case?

Thanks for lightspeed response.

**Comment by igauravsehrawat** [comment]
Also @nightwing 
> ace.edit calls that automatically when window is resized

automatically doesn't solve this, it works if i put  `editor.resize()` in my resize event.

Thanks

**Comment by nightwing** [comment]
updateFull, and updateText are internal calls to schedule dom update on next animation frame. 
When something changes, editor calls one of these functions to schedule redraw https://github.com/ajaxorg/ace/blob/master/lib/ace/virtual_renderer.js#L789

**Comment by igauravsehrawat** [comment]
@nightwing 
Do you think there is bug in ace since
> ace.edit calls that automatically when window is resized
automatically doesn't solve this, it works if i put editor.resize() in my resize event

Thanks

**Comment by nightwing** [comment]
Automatic resizing works if the element for which editor was created is resized automatically, if it is resized with javascript after window resize event editor.resize() call is needed.

**Comment by igauravsehrawat** [comment]
Thanks. Learned slow way that resize doesn't work on div but on `window` element.
