### ISSUE TITLE
Error in keywordcompleter

### ISSUE THREAD

**Issue by adamjimenez** [ajaxorg/ace#2798]
In PHP enter this and try to complete after the n with ctrl - space:
```
<? $v['n
```

This gives the following error:
autocomplete.js:244 Uncaught TypeError: Cannot read property '0' of undefined

![image](https://cloud.githubusercontent.com/assets/573192/11665827/3ca3619e-9de1-11e5-824c-00b8d8a1e56b.png)

**Comment by nightwing** [comment]
https://github.com/ajaxorg/ace/pull/2771 should fix this

**Comment by adamjimenez** [comment]
looks good, thanks
