### ISSUE TITLE
Double click php var selects $

### ISSUE THREAD

**Issue by adamjimenez** [ajaxorg/ace#2799]
When you double click a PHP var (e.g. $foo) it now selects the $. It didn't used to do this.
Not sure if this is deliberate or a regression. I preferred how it worked before.

**Comment by nightwing** [comment]
I think this was broken when refactoring php mode we still have custom tokenRe in php.js but it is applied to the inline php mode only.
Should character class of $ change based on context (non word in php word in js html in the same file) or should it be a global config?

**Comment by adamjimenez** [comment]
I vote for global.

**Comment by adamjimenez** [comment]
I opened a PR that does it by context, please review.
