### ISSUE TITLE
How i can get context?

### ISSUE THREAD

**Issue by arshtepe** [ajaxorg/ace#2801]
I can`t find in the documentation the following. For example:
html:
````HTML
<body>
   <div>
    <span></span> <!--  i press in this place 'ctrl + space' and I want to get parent tags [div, body html]-->
   </div>
</body>
````
and how can I set my hint list  (not add elements)?

**Comment by nightwing** [comment]
Currently ace doesn't have any way for detecting parent tags, you'll need to parse html and find that in autocompleter.
You can set editor.completers=[myCompleter] instead of adding it to the array, so that only one completer is called.
Or do you want to decide this based on available completions?

**Comment by arshtepe** [comment]
yes, If it is possible

**Comment by nightwing** [comment]
It is not possible yet, https://github.com/ajaxorg/ace/blob/master/lib/ace/autocomplete.js#L237 would need to be modified to allow that.
How do you want to decide which completions to keep? Is that based on completions provided by your completer or other completers too?

**Comment by arshtepe** [comment]
@nightwing , I have solution already, it is quick test example for find parent tag by position is xml string http://jsfiddle.net/c9cws7au/3/ ,

**Comment by arshtepe** [comment]
@nightwing  Can i check where press "ctrl + space" in attribute value in tag value etc.. ?
