### ISSUE TITLE
Headless mode

### ISSUE THREAD

**Issue by Immortalin** [ajaxorg/ace#2807]
Is there a way to run it headlessly i.e. as a server, without any display. I need to use it to edit a file programmatically with a third party application that only has support for ace editor

**Comment by nightwing** [comment]
Use mockrenderer see if you want to create an editor without dom https://github.com/ajaxorg/ace/blob/master/lib/ace/editor_highlight_selected_word_test.js#L41

**Comment by Immortalin** [comment]
My code is something like this:
```JavaScript
var ace = require("ace/lib/ace/ace.js")
var MockRenderer = require("ace").MockRenderer

var editor = ace.edit(new MockRenderer())
```

I am getting the following error:
```JavaScript
..../node_modules/ace/lib/ace/ace.js:37
define(function(require, exports, module) {
^

ReferenceError: define is not defined
```

**Comment by nightwing** [comment]
did you get this to work?
You need to use the unpacked version isntead of the one from build, something like https://github.com/ajaxorg/ace/blob/master/demo/static-highlighter/server.js

```js
require("amd-loader");
var MockRenderer = require("ace/lib/ace/test/mockrenderer").MockRenderer
var Editor = require("ace/lib/ace/editor").Editor
var editor = new Editor(new MockRenderer)
``

**Comment by Immortalin** [comment]
@nightwing I figured that the build vs source version issue. To fix the `window.require` issue, I modified the source and change the 3 or so `window` instances to `global` instead. I will take a look again at the mockrender bit in a moment.
