### ISSUE TITLE
Vue.js single-file component support

### ISSUE THREAD

**Issue by jimutt** [ajaxorg/ace#2810]
I would love to see support for files using different languages in the same file. Especially the single-component files you often use when working with Vue.js. See this picture for an example: http://vuejs.org/images/vue-component-with-pre-processors.png. For more information: http://vuejs.org/guide/application.html#Single_File_Components

There is a highlighting plugin for .vue files available for Sublime: https://github.com/vuejs/vue-syntax-highlight

**Comment by boustanihani** [comment]
any updates on this ?

**Comment by tremendus** [comment]
I agree. Is anyone following this? Can we import our own syntax highlighting using the sublime/atom syntax highlighters? this is the missing link from me using the product, as I work in Vue all day, love to figure out if it will become supported or if not where its something we can customize in the back door?

**Comment by wwq-sgxy** [comment]
I agree also.

**Comment by Piterden** [comment]
Me too

**Comment by boustanihani** [comment]
:+1:

**Comment by web812** [comment]
me too!!!

**Comment by designbywilliam** [comment]
Agreed!

**Comment by asdred** [comment]
Will be awesome

**Comment by Piterden** [comment]
CodeMirror supports Vue @asdred

**Comment by boustanihani** [comment]
Any updates on this ?

**Comment by Piterden** [comment]
Ya, https://codemirror.net/

**Comment by boustanihani** [comment]
Is there a way to use CodeMirror inside Cloud9 ?

**Comment by Piterden** [comment]
If they don't want to implement vue syntax, maybe you should think about change it? Actually, they even not answering...

**Comment by boustanihani** [comment]
Very sad :( Vue is so popular and I am a premium user I. I hope this gets implemented soon.

**Comment by Piterden** [comment]
Well, happy waiting, thread started in Dec 14, 2015

**Comment by nightwing** [comment]
@boustanihani vue files seem to be simple html files with different extension, and cloud9 sets html extension for them by default https://github.com/c9/core/blob/master/node_modules/ace/lib/ace/ext/modelist.js#L94

Do you get a different mode, or does html mode not work as you are expecting?

**Comment by Piterden** [comment]
Does your HTML-mode support `lang` attributes in `<template>`, `<script>` and `<style>` tags?

**Comment by nightwing** [comment]
@Piterden, no, they support only html/js/css.
Id there a list of possible values for this lang attributes?

**Comment by boustanihani** [comment]
Code formatting is not working inside the `<template>` and the `<style>` tags.

**Comment by nightwing** [comment]
@boustanihani, code formatting is not related to this issue, since you are a premium customer, please open a support ticket, and show examples of files for which code formatting does not work as expected, this issue is about syntax highlighting.

**Comment by boustanihani** [comment]
I already did this month ago

**Comment by Piterden** [comment]
Here is the list, @nightwing :

https://github.com/vuejs/vue-syntax-highlight/blob/master/vue.YAML-tmLanguage#L67
https://github.com/vuejs/vue-syntax-highlight/blob/master/vue.YAML-tmLanguage#L83
https://github.com/vuejs/vue-syntax-highlight/blob/master/vue.YAML-tmLanguage#L99
https://github.com/vuejs/vue-syntax-highlight/blob/master/vue.YAML-tmLanguage#L116
https://github.com/vuejs/vue-syntax-highlight/blob/master/vue.YAML-tmLanguage#L132
https://github.com/vuejs/vue-syntax-highlight/blob/master/vue.YAML-tmLanguage#L148
https://github.com/vuejs/vue-syntax-highlight/blob/master/vue.YAML-tmLanguage#L165
https://github.com/vuejs/vue-syntax-highlight/blob/master/vue.YAML-tmLanguage#L183
https://github.com/vuejs/vue-syntax-highlight/blob/master/vue.YAML-tmLanguage#L215
https://github.com/vuejs/vue-syntax-highlight/blob/master/vue.YAML-tmLanguage#L233
https://github.com/vuejs/vue-syntax-highlight/blob/master/vue.YAML-tmLanguage#L251

**Comment by nightwing** [comment]
@Piterden thanks, i am working on a update for syntax highlighter, which will make embedding languages easy, it will be ready in about 2 weeks.

@boustanihani i am sorry, i am not able to find anything related to your report. And as for as i can see code formatting works now for basic things, so there must be a subtler issue.

**Comment by Piterden** [comment]
@nightwing If it would be opensource, then there is a big chance we go back from CM :wink:

**Comment by BeauAgst** [comment]
Any update on this?

**Comment by OlzhasAlexandrov** [comment]
😅 
> Q: I need to have syntax highlighting for Pug and Stylus
> A: How about using HTML instead? I heard it's good enough for basic tasks...

**Comment by InspiredGuy** [comment]
Vue language mode was added in https://github.com/ajaxorg/ace/pull/5483 and should be already available in latest Ace version.
