### ISSUE TITLE
Double-click selects entire document after some time

### ISSUE THREAD

**Issue by daskandalis** [ajaxorg/ace#2811]
Discovered with Rstudio IDE Version 0.99.486, in Ubuntu 14.04. 

Double clicking on a single word stops selecting that word, and instead selects the entire document. Triple click does select just the one word. Double click at the end of a line still selects the last word.

I can't tell what triggers this. This issue is probably the same as #1558.

**Comment by nightwing** [comment]
Could you please check if this happens on http://ajaxorg.github.io/ace/kitchen-sink.html?

**Comment by daskandalis** [comment]
It does not, from what I can tell.

**Comment by nightwing** [comment]
@daskandalis Did you report this issue to Rstudio?
cc @kevinushey

**Comment by daskandalis** [comment]
Not yet, I will do so now.

**Comment by kevinushey** [comment]
Thanks, we're looking into this on the RStudio side now -- I think this can be closed.

**Comment by kevinushey** [comment]
Hmm, I can replicate something like this with the following actions in the Kitchen sink:

1. Use the mouse wheel to middle-click on a word,
2. Attempt to double click on a word.

The word is no longer highlighted. The third click then highlights the entire document. The odd state seems to go away after a right-click or multiple middle clicks.

**Comment by nightwing** [comment]
Interesting, this can be caused by https://github.com/ajaxorg/ace/blob/master/lib/ace/mouse/default_handlers.js#L79 moving hidden textarea to cursor and leaving it there

**Comment by daskandalis** [comment]
I triggered the issue in Rstudio with kevinushey's steps. Thanks!

**Comment by jsalvatore** [comment]
I'm finding the exact same issue on rstudio 0.99 on Ubuntu 15.10... Can replicate the issue using the @kevinushey method described above... Any work-around fix for this?

**Comment by kevinushey** [comment]
I believe this has been fixed on the Ace side, but the patch hasn't yet made its way into RStudio. I'll file a bug to make sure we get this patch.

**Comment by jsalvatore** [comment]
Thanks @kevinushey - can you link me to the bug report so that I can follow?

**Comment by kevinushey** [comment]
Unfortunately our bug tracker is not public -- that's something else we need to get done. I can make sure we ping you here once it's in the daily builds.
