### ISSUE TITLE
Indentation errors for Ruby control expressions

### ISSUE THREAD

**Issue by alexrois** [ajaxorg/ace#2814]
There are two errors with automatic indent and outdent for Ruby control expressions in Ace editor:

When using 'if...elsif...else...end' branching every *elsif* line doesn't **outdent** automatically. Example:

![elsif](https://cloud.githubusercontent.com/assets/16092409/11829722/62f3a96e-a3a7-11e5-9a1f-ec338d475e2a.jpg)

In above example you can see automatic outdent for *else* and *end* keywords. But it doesn't work for *elsif* keyword. So developers need manual correction of every line with *elsif* keyword in 'if...end' branching. See info about this control expression, syntax and styling of 'if...end' in [Core API for Ruby.](http://ruby-doc.org/core-2.2.3/doc/syntax/control_expressions_rdoc.html#label-if+Expression)

When using 'case...when...end' branching every line inside *when* block doesn't **indent** automatically. Example:

![when](https://cloud.githubusercontent.com/assets/16092409/11829931/211bc39e-a3a9-11e5-8758-89d8b5521d77.jpg)

In above example you can see automatic indent for *else* block (next line after *else*'s line). But it doesn't work for *when* blocks (every line after *when*'s line should be indented). So developers need manual correction of every line inside *when* block in 'case...end' branching. See info about this control expression, syntax and styling of 'case...end' in [Core API for Ruby.](http://ruby-doc.org/core-2.2.3/doc/syntax/control_expressions_rdoc.html#label-case+Expression)

**Comment by alexrois** [comment]
Any suggestions?

**Comment by nightwing** [comment]
https://github.com/ajaxorg/ace/commit/b6abb5eacfb827bed9752f2a0d94a33a2bb152dd should help

**Comment by nightwing** [comment]
fixed by https://github.com/ajaxorg/ace/pull/2846
