### ISSUE TITLE
Binding Ace to global variable in headless mode

### ISSUE THREAD

**Issue by Immortalin** [ajaxorg/ace#2818]
I am trying to bind Ace to a global variable when it is ran via mockrenderer but to no avail. Here's my code:
```JavaScript
var Firebase = require("firebase")
var Firepad = require("firepad")

require("amd-loader")
global.ace = require("ace/lib/ace/ace.js")
var MockRenderer = require("ace/lib/ace/test/mockrenderer").MockRenderer
var Editor = require("ace/lib/ace/editor").Editor
if (typeof process !== "undefined") {
    require("ace/lib/ace/test/mockdom")
}

var editor = new Editor(new MockRenderer())
var firepadRef = new Firebase("my-firebase-url.firebaseio.com")
var firepad = Firepad.fromACE(firepadRef, editor)
```

However, I am getting the following error:
```JavaScript
Error: Couldn't find CodeMirror or ACE.  Did you forget to include codemirror.js or ace.js?

```

Can something like [this](https://gist.github.com/mikelehen/7995843) be used to get around the problem? [Mockdom](https://github.com/ajaxorg/ace/blob/master/lib/ace/test/mockdom.js) already does that but it doesn't seem to be working.

**Comment by nightwing** [comment]
Try assigning global.ace before calling `require("firebase")`

btw. if you have more questions about this, please keep asking them in this issue instead of opening new ones.

**Comment by Immortalin** [comment]
With the above changes, I got this error:
```JavaScript
../node_modules/firepad/dist/firepad.min.js:15

TypeError: Cannot read property 'replaceChild' of null
```
The error seems to be from [this line](https://github.com/firebase/firepad/blob/f618700f9467d067e84bb2e5a11ddd4c6ad2c2a2/lib/firepad.js#L47). I fixed this by adding the following lines to the `MockRenderer = exports.MockRenderer = function(visibleRowCount){}`:
```JavaScript
    this.container.className = "firepad"
    Object.defineProperty(this.container, "parentNode",{
        get: () => {return document.createElement("div")}
    })
```
However, now I am getting 
```JavaScript
../node_modules/ace/node_modules/node-jsdom/lib/jsdom/level1/core.js:614
          throw new core.DOMException(NOT_FOUND_ERR);
          ^
DOMException: Not found
```

**Comment by nightwing** [comment]
try 

```js
var modules = require("module");
var oldResolve = modules._resolveFilename;
var extraPaths = [];
modules._resolveFilename = function(request, parent) {
    request = request.replace(/^ace\//, "ace/lib/ace/");
    return oldResolve(request, parent);
};


require("amd-loader")
require("ace/test/mockdom")
global.ace = require("ace/ace.js")
global.navigator = window.navigator

var Firebase = require("firebase")
var Firepad = require("firepad")
var editor = ace.edit(document.body)


var firepadRef = new Firebase("my-firebase-url.firebaseio.com")
var firepad = Firepad.fromACE(firepadRef, editor)

```

**Comment by Immortalin** [comment]
With the above code and the following lines:
```JavaScript 
var chokidar = require('chokidar');
var fs = require("fs")

var data = fs.readFileSync("test.txt")

// One-liner for current directory/test.txt, ignores .dotfiles
chokidar.watch('./test.txt', {ignored: /[\/\\]\./}).on('all', (event, path) => {
    console.log(event, path)
    firepad.on('ready', function() {
        // Firepad is ready.
        firepad.setText(data)
    })

})
```
I tried to see if I can get can keep a file in sync read-only (i.e. without implementing the writing bit yet). However, I am getting the following error:
```JavaScript
/node_modules/ace/lib/ace/document.js:122
        var match = text.match(/^.*?(\r\n|\r|\n)/m);
                         ^

TypeError: text.match is not a function
```
I am not sure whether this is a bug in node or ace. I am using node version 4.2.3

**Comment by nightwing** [comment]
you are passing buffer instead of string  `var data = fs.readFileSync("test.txt", "utf8")`

**Comment by Immortalin** [comment]
I am attempting to keep two test.txt in sync with the following code:
```JavaScript
var chokidar = require("chokidar");
var fs = require("fs")

// One-liner for current directory/test.txt, ignores .dotfiles
chokidar.watch("./test.txt", {
    ignored: /[\/\\]\./
}).on("all", (event, path) => {
    console.log(event, path)
    firepad.on('ready', () => {
        // Firepad is ready.
        var data = fs.readFileSync("test.txt", "utf8")
        firepad.setText(data)
    })

})

firepad.on("ready", () => {
    // // Firepad is ready.
    // firepad.setText(data)
    // isSynced is false if user changes have not been synced
    firepad.on("synced", isSynced => {
        if (isSynced) {
            firepad.getText(text => {
                fs.writeFileSync("test.txt", text, "utf8")
            })
        }
    })
})

editor.on("change", change => {
    console.log("change event detected")
    firepad.on("ready", () => {
        firepad.getText(text => {
            fs.writeFileSync("test.txt", text, "utf8")
        })
    })
})
```

The editor on change event fires three times during the initialization but while the data seems to be syncing, it is not being written to file. This is not exactly related to ace editor but I am wondering how could the code be changed so that it can work better.

**Comment by lalitrane234** [comment]
up vote
0
down vote
favorite
I am trying to use Firepad. While trying to use firepad I am getting below error.

In Firefox.

Error: i.parentNode is null
c@https://cdn.firebase.com/libs/firepad/1.3.0/firepad.min.js:15:16104
c@https://cdn.firebase.com/libs/firepad/1.3.0/firepad.min.js:15:15380
In Chrome I am getting below error.

TypeError: Cannot read property 'replaceChild' of null
at new c (firepad.min.js:15)
at Function.c (firepad.min.js:15)
at n.$scope.initFirepad (NotesUtils.js:231)


<div class="form-group">
<label for="inpNoteDescription" class="col-md-3 control-label" id="inpNoteDescription">Note Description With Firepad</label>
<div class="col-sm-8" id="inpNoteDescription">
</div>
</div>  

$scope.initFirepad = function(){
var firepadRef = $scope.initObj.firepadRef  ;        
var noteDescription = $scope.currentNote.description ;
var codeMirror = CodeMirror(document.getElementById('inpNoteDescription'), { lineWrapping: true });
var firepad = Firepad.fromCodeMirror(firepadRef, codeMirror, { richTextShortcuts: true, richTextToolbar: true, defaultText: noteDescription });
}

**Comment by nightwing** [comment]
@lalitrane234 your code snippet uses CodeMirror not Ace.
@Immortalin i do not know why the last example doesn't work. Closing this issue, but feel free to comment if you have more questions about Ace.

**Comment by Immortalin** [comment]
@nightwing do you have any suggestions on keeping two text files in sync using ace + firepad?

**Comment by nightwing** [comment]
see the demo at https://github.com/firebase/firepad/blob/master/examples/ace.html, which works well https://rawgit.com/firebase/firepad/master/examples/ace.html#-K8JCzfJQt8N1OMig2Q5
