### ISSUE TITLE
reusing data from onChange event

### ISSUE THREAD

**Issue by KuroNoDev** [ajaxorg/ace#2819]
Say I pasted the word 'sample' on ace editor and got this data from the onChange event:
``` javascript
{
  "data": {
    "action": "insertText",
    "range": {
      "start": {
        "row": 7,
        "column": 3
      },
      "end": {
        "row": 7,
        "column": 9
      }
    },
    "text": "sample"
  }
}
```
Is there a way to reuse it like sending this data to another client via websockets (to update the contents based on the data) without manually detecting the 'action'?
eg:
```javascript
if( data.action == 'insertText' )
  AceEditor.insert(data.range, data.text);
```

**Comment by nightwing** [comment]
There are `session.doc.applyDelta`,  `session.doc.revertDelta` and  `session.doc.applyDeltas` methods https://github.com/ajaxorg/ace/blob/v1.2.2/lib/ace/document.js#L550-L584, worker_client in Ace uses that to synchronize documents in main thread and webworker.

**Comment by KuroNoDev** [comment]
Very neat, just what I need. Thanks a lot!
