### ISSUE TITLE
emacs: 'mark' should be cleared after 'kill-region'

### ISSUE THREAD

**Issue by kevinushey** [ajaxorg/ace#2820]
Repro, in kitchen sink:

1. Enable Emacs keybindings,
2. Set mark with `Ctrl+Space`,
3. Move the cursor around to select some text,
4. Kill the region using `Ctrl+W`,
5. Move the cursor around.

The 'mark' is still active (ie -- the selection still grows when the cursor is moved), which does not seem to match Emacs behaviour.

**Comment by ppham27** [comment]
I believe that the same fix needs to be applied in killRingSave. Same repro but Alt+W. I'm happy to put in the PR.
