### ISSUE TITLE
url anchor target line(s)

### ISSUE THREAD

**Issue by mothsART** [ajaxorg/ace#2824]
I like this Github feature : url anchor on a line or on selection like https://github.com/ajaxorg/ace/blob/master/static.js#L4-L10

Is there an "Ace" trick for doing the same? 
If so, is it possible to do a **#editor1-L4-L10** on a multi-embeding context?

best regards, Jérémie Ferry

**Comment by nightwing** [comment]
You can parse `location.hash` and use `editor.selection.setRange` something like
```js
var Range = require("ace/range").Range
editor.selection.setRange(new Range(4, 0, 10, Number.MAX_VALUE))
```

**Comment by nightwing** [comment]
Closing, let me know if you need more help with this.
