### ISSUE TITLE
How to hide Snippets tooltip

### ISSUE THREAD

**Issue by sdkcarlos** [ajaxorg/ace#2828]
I need to activate the snippets on my project, the problem  is that the tooltip which shows the snippets doesn't display correctly on small devices.

Is there any way to disable the tooltip without disable the snippets ? Or make the tooltip displays vertically ?
Thanks !
![tooltip](https://cloud.githubusercontent.com/assets/11634719/11934073/094afc84-a800-11e5-9382-5bf96c19c4b2.png)

**Comment by nightwing** [comment]
do disable tooltip use `require("ace/ext/language_tools").snippetCompleter.getDocTooltip = null`
Displaying tooltip above or bellow the popup requires modifying https://github.com/ajaxorg/ace/blob/master/lib/ace/autocomplete.js#L384, would you prefer that or would that make display too crowded?

**Comment by sdkcarlos** [comment]
The first solution is perfect, Pitifully with the mobile keyboard it wouldn't display so good even if i modify it. In the tablets is displaying good without modifications, thank you so much nightwing!
