### ISSUE TITLE
Setting firstLineNumber does not affect gutter width

### ISSUE THREAD

**Issue by TimBlo** [ajaxorg/ace#2829]
I think i spotted a bug that skips resizing the gutter width when setting firstLineNumber using editor.setOptions.
It looks a little akward when setting firstLineNumber from ones to tens or from tens to hundreds and so.

I don't need a solution, there are plenty of ways. But this is a bug, is it?

**Comment by nightwing** [comment]
Which version do you use?
https://github.com/ajaxorg/ace/blob/master/lib/ace/edit_session.js#L2531 emits an event which triggers gutter redraw.

**Comment by nightwing** [comment]
>. But this is a bug, is it?

This is clearly a bug, but i cannot reproduce this on https://ace.c9.io/#nav=about by running `editor.setOption("firstLineNumber", 1000000)` in the console, so likely this was an issue in older versions. Please comment if you see this in the latest version.
