### ISSUE TITLE
Request: keyboard shortcut to create link 

### ISSUE THREAD

**Issue by kevinSuttle** [ajaxorg/ace#2833]
CMD-K for Mac
CTRL-K for Windows (switching current behavior to CTRL-G)

**Comment by nightwing** [comment]
What do you mean by `create link`?

**Comment by kevinSuttle** [comment]
Sorry, hyperlink, anchor, etc. `[Link](example.com)

**Comment by jamessampford** [comment]
You can use your own keybindings to create a shortcut with a custom function to create the link as you wish

**Comment by nightwing** [comment]
I agree with @jamessampford, this command is only relevant to markdown mode and can be easily added from user code using the following snippet

```js
editor.commands.addCommand({
    name: "addMarkdownLink",
    exec: function(editor) {
        editor.insertSnippet("[${1:Link}](${0:example.com})")
    },
    bindKey: "Ctrl-K"
})
```

**Comment by kevinSuttle** [comment]
Ok thanks folks.
