### ISSUE TITLE
Tabs before lines when text mode

### ISSUE THREAD

**Issue by geakstr** [ajaxorg/ace#2834]
What reason to add tabs before lines when mode is `text`? 

![ace kitchen sink 2015-12-29 21-06-46](https://cloud.githubusercontent.com/assets/1496368/12039286/271a1062-ae70-11e5-8c41-bb27b242fb76.png)

**Comment by nightwing** [comment]
this is contolled by `indentedSoftWrap` softwrap setting  https://github.com/ajaxorg/ace/blob/v1.2.2/lib/ace/edit_session.js#L2529, probably it should be false by default

**Comment by geakstr** [comment]
Thank you. I read sources of other modes and this also fixes by

```js
(function() {
  this.type = "text";
}).call(Mode.prototype);
```

when define custom mode
