### ISSUE TITLE
Add Better Support for ECMAScript 2015 (ES6) Syntax

### ISSUE THREAD

**Issue by thealexbaron** [ajaxorg/ace#2835]
Can we highlight object functions that don't use the `function` keyword? 

this syntax does not get highlighted: `{ myFunction (someArgs) { } }`
while this does: `{ myFunction: function (someArgs) { } }`

I prefer the former syntax as it's less noisy, but the function name just turns white.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Method_definitions#Description

**Comment by nightwing** [comment]
In case of  `myFunction: function` it is very easy to detect the method definition.
` myFunction (someArgs) {` is too similar to method invocation
