### ISSUE TITLE
toggleCommentLines() toggles incorrectly in <style> and <script> tags

### ISSUE THREAD

**Issue by jamessampford** [ajaxorg/ace#2836]
Not sure if this is a bug or I'm doing something wrong...

Basically have a function (below) to insert a task tag to a given line (with spacing before and after) - the page is HTML (using HTML mode) and I thought I could comment the lines using the functionality in ACE to ensure that HTML blocks have `<!-- tag -->` tags and CSS/Scripts use `// tag` or `/* tag */`

`function addTag(tag, message. lineNum){`
`editor.gotoLine(lineNum);`
`editor.focus();`
`editor.insert("\n\n"+'@'+tag+': '+message+''+"\n\n");`
`editor.instance.selection.selectLine();`
`editor.toggleCommentLines();`
`}`

However, in style and script tags I keep getting `<!-- tag -->` - though when using the keyboard shortcut (Ctrl+/ or Ctrl+Shift+/) the style/script tags use the correct comment `/* tag */`

Everything looks ok in JavaScript (javascript mode) and CSS (css mode) files - however, for some reason PHP files (php mode) are using HTML comments tags

**Comment by nightwing** [comment]
This is caused by https://github.com/ajaxorg/ace/issues/2633, tokenizer doesn't have state for newly inserted lines.

**Comment by jamessampford** [comment]
Would I need to manually run the tokenizer on the new line (not sure how) on the new line before toggling the comment?
