### ISSUE TITLE
Typescript highlight error

### ISSUE THREAD

**Issue by AleksNFedorov** [ajaxorg/ace#2838]
After next type declaration all method signatures below bacame green.

<validType>

Example:
    private _listeners: Array<string> = [];

Here is a screenshot 

http://screenshot.co/#!/5a1c4daf18

![typescripterror](https://cloud.githubusercontent.com/assets/6401769/12082018/c48d7f32-b23f-11e5-8ebc-954b92433ce8.png)

**Comment by nightwing** [comment]
It was highlighting typescript as tsx, should be fixed in v1.2.3
