### ISSUE TITLE
Vue.js Syntax Support

### ISSUE THREAD

**Issue by joshbivens** [ajaxorg/ace#2841]
An example: https://github.com/vuejs/vue-syntax-highlight

**Comment by jimutt** [comment]
+1, made a suggestion about it a while ago #2810

**Comment by joshbivens** [comment]
Ah! I found if you change the document type from 'text' to 'JavaScript' (at the bottom right), it highlights properly.

**Comment by jeremy50dj** [comment]
I slept on this beach one night in a underground cavern with about ten other people and I was with echo my girlfriend in 1988-89. Then I put my belonging's their for a night and I found a pair of pants washed up to shore. So yes I'm on this beach in deep thought. So join me as I create other beaches as we all reach together to strengthen Humanity.

**Comment by boustanihani** [comment]
any updates on this ?

**Comment by BigChief45** [comment]
HTML mode works pretty well.

Duplicates: #2810, #3300

These issues can be closed.

@nightwing

**Comment by JulienAramino** [comment]
What about specific language in template or style ?
`<template lang="pug">`
while the structure of file could be:
```
<template lang="pug">
</template>
<script>
</script>
<style lang="scss">
</style>
```

It would be great to have different syntax highlighting per section with lang attribute.
