### ISSUE TITLE
Theming guidlines (what keywords to use)

### ISSUE THREAD

**Issue by OnkelTem** [ajaxorg/ace#2843]
I'm new to ACE editor, in fact I'm playing with it for an hour or two. I'd like to fix some styles and to add some new ones for YAML mode. However I can't decide which keywords should use to get them stylized in most themes. For example, YAML mode's `meta.tag` has no any properties in Ambiance theme and that was just my random guess, I suppose if I try other themes I'll face the same situation.

Is there any guidelines on using words?
What themes are more common/generic and can be used as a reference/base?

**Comment by nightwing** [comment]
Ace themes and modes are based on Sublime Text/Textmate.
But unfortunately that isn't very well thought system so often scope names assigned by modes are not highlighted by many themes.
The tool that converts textmate themes is at https://github.com/ajaxorg/ace/blob/master/tool/tmtheme.js#L21 but not all themes define styles for all the scopes listed there.

**Comment by OnkelTem** [comment]
@nightwing 

Thank you very much. Subl is my everyday editor, so this makes a lot of sense.
