### ISSUE TITLE
Ace documentation

### ISSUE THREAD

**Issue by sergiusignacius** [ajaxorg/ace#2849]
Hi guys,

The API reference website (https://ace.c9.io/api/) looks like this:

![image](https://cloud.githubusercontent.com/assets/448199/12262631/f1f58d4c-b920-11e5-9e1b-841f4bd62a66.png)
As you can see, there is nothing on the left. I can't seem to find a definitive place where thorough documentation is found.

Can you please give me a hand?

Thanks,
Sérgio

**Comment by nightwing** [comment]
Hi
please use https://ace.c9.io/#nav=api, 

https://ace.c9.io/api/ is just a text file used as a part of the first page.
