### ISSUE TITLE
CKEditor-like text formatting for ACE Editor

### ISSUE THREAD

**Issue by scottlingran** [ajaxorg/ace#2853]
I'm using ACE Editor for an experimental project.

However, I'm looking for text formatting options. I don't want to switch to CKEditor because I'd lose the 'syntax highlighting' feature of ACE Editor.
1. Is there a library/plugin that provides text formatting for ACE Editor? (A quick google/github search suggests there's not)
2. If not, what's the best way to approach building formatting options for ACE Editor? (e.g. bold, italic, font options)

**Comment by InfantAnto** [comment]
Hi scottyli
Now i am also in a need of adding the Formatting options to ACE editor. It has done? Any way to add formatting options?

**Comment by skyflysun** [comment]
i find a method
condition： brace/ace

js：
let beautify = ace.acequire( "ace/ext/beautify" );
      beautify.beautify( this.editor.getSession() ) ;

**Comment by ninbit** [comment]
hi, is there any success? @skyflysun @InfantAnto @scottlingran
