### ISSUE TITLE
Variables already set in javascript mode

### ISSUE THREAD

**Issue by aveuiller** [ajaxorg/ace#2857]
I'm using Ace in javascript mode and it seems that the main scope is already containing variables.

For instance if I try to declare a location variable, the editor will throw a warning `Redifinition of location`:

```
var location = "test";
```

And if I try to affect a value to it, the editor will throw a `Read only`:

```
location = 2;
```

These examples works the same way on the demo editor on [ace.c9.io](https://ace.c9.io).

Why is there variable in the editor, does that come from the page? 
Is it possible to provide an empty scope to the editor?

**Comment by nightwing** [comment]
jshint reports about name collision with global window.location when browser:true https://github.com/ajaxorg/ace/blob/master/lib/ace/mode/javascript_worker.js#L85 
same happens on http://jshint.com/

**Comment by aveuiller** [comment]
Ok, thanks for the info. 
Is there any way to change the worker options once loaded (or on startup)? 

I didn't find anything about that in the documentation,  the only `setOptions` method available seems to be in the session and is only modifying the editor configuration.
