### ISSUE TITLE
gotolineend(Ctrl+e) works abnormally

### ISSUE THREAD

**Issue by Rokt33r** [ajaxorg/ace#2858]
When softwrap enabled, the behavior of gotolineend is strange.

```
1|aaaaaaaaaaaaaaaaaaaaaaaaaa|
 |bbb                       |
2|                          |
3|                          |
4|                          |
```

As you can see, the last character of the first line is `b`
But, after pressing Ctrl+e, cursor move to the last `a` which is at end of screen.

This is my temporary expedient.

``` js
   execHandler = (e) => {
      switch (e.command.name) {
        case 'gotolineend':
          e.preventDefault()
          let position = this.editor.getCursorPosition()
          this.editor.navigateTo(position.row, this.editor.getSession().getLine(position.row).length)
          break
    }
    editor.commands.on('exec', execHandler)
```

**Comment by nightwing** [comment]
Ace uses screen lines for gotolineend/gotolinestart etc.
Is the default on emacs to use logical lines? If yes, do we need to provide  option for keeping current behavior?

**Comment by kevinushey** [comment]
Emacs does indeed use logical lines by default.

**Comment by nightwing** [comment]
@kevinushey would it be good to change `ctrl-e` to use logical lines and keep `Home/End` for screen lines?

**Comment by kevinushey** [comment]
That sounds like the right change to me as well.

**Comment by nightwing** [comment]
how should it handle folds? `function a() { <--> }`

**Comment by kevinushey** [comment]
My preference would be to move the cursor over the fold, to the end of the screen line in this case.

**Comment by brandt** [comment]
Please keep open.

**Comment by andrewnester** [comment]
Potentially, we can add a `bias` option similar to CodeMirror to configure either set the cursor to the end on line or the start of next line

**Comment by whazor** [comment]
I think when pressing `End` again, Ace should move the cursor from end of `a` to `b` as well. So going to end of the next inner line from the line. Similarly, `Home` should bring the cursor back to previous inner lines.
