### ISSUE TITLE
Recursive highlighter

### ISSUE THREAD

**Issue by geakstr** [ajaxorg/ace#2861]
Hello! I want to write recursive rules for my own highlighter. For example for text

```markdown
**wow, _[link to](google.com) google_**
```

I want next markup
```html
<b>wow, <i><a href="google.com">link to</a> google</i></b>
```

I have unanswered question on StackOverflow http://stackoverflow.com/questions/34526399/ace-editor-how-to-implement-highlighter-into-nested-blocks

Is this possible?

**Comment by nightwing** [comment]
Ace can't display arbitrary markup. Highlighters create list of tokens of the form `{value, type}` which is rendered as a list of spans `<span class=type>value</span>`

**Comment by geakstr** [comment]
Oh, ok, now I understand that my example is totally stupid, sorry 😱

I meant something like this

```markdown
**foo _google.com_ bar**
```

```html
<span class="strong">foo <span class="emphasis">google.com</span> bar</span>
```


And some offtopic. If ace can't arbitrary markup, how to do clickable links in text, for example?

**Comment by mlajtos** [comment]
Maybe [this](https://stackoverflow.com/questions/22765435/recursive-blocks-in-ace-editor/22766243#22766243) will help you.

**Comment by geakstr** [comment]
@mlajtos yeah, I've seen this before, thank you.

With simple push/pop it can't be done, because we don't have information about parent states. I spent a lot of time to research this question and now implement it with custom `onMatch()` functions and lot of code (maybe I'm dumb and there's a simpler approach). 

Look at this on gist (I wrote simple documentation) https://gist.github.com/geakstr/68cc92493feb166271ff

It's easy to use and have simple api. For example, custom ACE highlighter is just (I use brace wrapper):
```javascript
ace.define("ace/mode/custom_highlight_rules", (acequire, exports, module) => {
  const oop = acequire("ace/lib/oop");

  const TextRules = acequire("ace/mode/text_highlight_rules").TextHighlightRules;

  const CustomRules = function() {
    TextRules.call(this);

    const rules = {
      blocks: {
        simple: "^[^+]",
        custom: "^\\+"
      },
      paired: {
        strong: "\\*",
        italic: "_"
      },
      unpaired: {
        email: "[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,6}"
      }
    };

    extendRules.call(this, rules);
  };
  oop.inherits(CustomRules, TextRules);

  exports.CustomRules = CustomRules;
});
```

One more thing I can't implement - how provide ability to escape rules with backslash. Any idea about this? :) I try next type of rules `strong: "[^\\\\]?\\*",` but it don't work.
