### ISSUE TITLE
modelist.getModeForPath returns "JavaScript" for JSX files

### ISSUE THREAD

**Issue by vlad-ignatov** [ajaxorg/ace#2863]
Looking at the source I can see that `modelist.getModeForPath()` returns the first match that is found - https://github.com/ajaxorg/ace/blob/master/lib/ace/ext/modelist.js#L17, thus it does prefer `"js|jsm|jsx"` over `"jsx"`. 

Here is my quick fix that also respects the file extension occurrence order. I am just not sure if that is optimal:
```js
const modelist = ace.require("ace/ext/modelist");

function getModeForPath(path) {
    var mode      = modelist.modesByName.text;
    var fileName  = path.split(/[\/\\]/).pop();
    var extension = fileName.split('.').pop().toLowerCase();
    var options   = [],
        length;

    for (var i = 0; i < modelist.modes.length; i++) {
        if (modelist.modes[i].supportsFile(fileName)) {
            length = options.push(modelist.modes[i]);
        }
    }

    if (length === 1) {
        mode = options[0];
    }
    else if (length > 1) {
        mode = options.sort(function(a, b) {
            return b.extensions.indexOf(extension) - a.extensions.indexOf(extension);
        }).pop();
    }

    return mode;
}
```

**Comment by nightwing** [comment]
Unfortunately jsx file extension is used both by jsx language and react jsx.
Since react jsx is much more popular than jsx language, it gets precedence.

Also since very often people use js extension for react jsx, support for it is added to javascript mode and enabled by default.

**Comment by vlad-ignatov** [comment]
Thank you. I was talking about React JSX. That makes sense but the final result remains "odd". I think It's OK to add react jsx stuff to the JS mode but it doesn't seem OK to treat jsx files as JS because:

1. The syntax highlighting is different (which is not a big deal)
2. React JSX is often being written in ES6 and ES7. In JS mode the jshint is on but it can't handle them very well and reports a lot of issues...
3. Because of the above, the end users are forced to switch the mode to JSX for every opened jsx file manually and that quickly becomes frustrating :(
4. In general, when one opens a file called "whatever.x" he would expect it to be detected as "x" and not as "y".

Perhaps there are some internal reasons for the current behaviour that I don't understand. In any case I will have to stick to my workaround if I want to make my editor playing better with react apps.

**Comment by nightwing** [comment]
The jsx mode in ace has nothing to do with react jsx, it is for https://jsx.github.io/ (an older language without a support for inline xml syntax).

Javascript mode highlights react jsx and es6 out of box. (cloud9 uses it for react files too). 

> In JS mode the jshint is on but it can't handle them very well and reports a lot of issues...

I've overlooked this issue.
Unfortunately it looks like jshint is [not interested](https://github.com/jshint/jshint/pull/2167) in adding support for jsx, so we probably should switch to eslint instead.

> . In any case I will have to stick to my workaround if I want to make my editor playing better with react apps.

A better workaround is to call `session.setUseWorker(false)` if extension is jsx.

> Perhaps there are some internal reasons for the current behaviour that I don't understand.

the reasons for current behavior are that 
  1. jsx mode is not related to react jsx
  2. often people use js extension for [files with react jsx syntax](https://github.com/kriasoft/react-starter-kit/blob/master/src/components/ContentPage/ContentPage.js#L29) 
  3. other ides (e.g. webstorm) highlight jsx syntax in js files similar to what ace does.

Does this make sense?

**Comment by vlad-ignatov** [comment]
Yes, thank you. It makes perfect sense now. 

The jsx mode happens to highlight ES7 syntax (ex. class properties) better than the JavaScript one which I agree is perfectly normal right now. It's just that one can easily think that it has been created for React JSX. The same can be observed in Atom btw and now I see why.

+1 for using eslint. That would be so much better...

Just one more question before I close this:
Using `session.setUseWorker(false);` helps because jshint is not enabled. I just can't find the documentation about it. Does it do something else other than not enabling the linting?

**Comment by nightwing** [comment]
> Does it do something else other than not enabling the linting?

It only disables the webworker used for syntax checking.

> The jsx mode happens to highlight ES7 syntax (ex. class properties) better than the JavaScript one 

Could you paste a code snippet for which jsx mode works better?

**Comment by vlad-ignatov** [comment]
OK. This one for example:

```js
export class Something extends React.Component
{
    static propTypes = {
        step      : PropTypes.number,
        min       : PropTypes.number,
        max       : PropTypes.number,
        precision : PropTypes.number,
        parse     : PropTypes.func,
        format    : PropTypes.func,
        className : PropTypes.string,
        disabled  : PropTypes.bool,
        readOnly  : PropTypes.bool,
        style     : PropTypes.object,
        type      : PropTypes.string,
        size      : PropTypes.oneOfType([ PropTypes.number, PropTypes.string ]),
        value     : PropTypes.oneOfType([ PropTypes.number, PropTypes.string ]),
        code      : React.PropTypes.oneOfType([
            React.PropTypes.string,
            React.PropTypes.number
        ]),
        message: React.PropTypes.string,
        stack: React.PropTypes.string
    };

    // ...
}
```

It's not that it doesn't work but because the entire nested structure renders in single color one could think it doesn't (using the Twilight theme for example). JSX however seems to highlight objects, properties and keywords inside that so it "feels better". Once again, it's not a real issue but just a coincidence that can make you feel like it's not working well enough. 

If i change that to normal object literal like `var propTypes = { ... }` I can see  that it renders the same so it appears that this is not ES7 related. I also wonder why is it slightly different here in github. They also use ACE as far as I know.

I see you have a lot of github issues and since this is not a real issue I am closing it now. Thank you for your support. It is all clear now and I hope we can see eslint integration soon.
