### ISSUE TITLE
Can I use my syntax highlighting rule that already exists in compiler?

### ISSUE THREAD

**Issue by zhanzhenzhen** [ajaxorg/ace#2866]
I have designed a language of my own. In the compiler I wrote a highlighting function which outputs "styles" in the format like this:

```javascript
[[0, "normal"], [5, "string"], [25, "comment"]]
```

The numbers are the starting character index within the whole file. I do not split it into lines.

So, my question is: can I convert this to make it directly used by ACE editor without using RegExp to redefine the rule that is redundant and maybe inaccurate?

**Comment by nightwing** [comment]
It is possible for a tokenizer to provide custom getLineTokens method like https://github.com/ajaxorg/ace/blob/master/lib/ace/mode/xquery.js#L44 does, however using full parser will be slow, and likely won't work if there are syntax errors.

**Comment by zhanzhenzhen** [comment]
Thanks

**Comment by zhanzhenzhen** [comment]
`getLineTokens` first parameter is the line string, not the line number. How can the parser know the line number?

**Comment by nightwing** [comment]
the third parameter is the line number see https://github.com/ajaxorg/ace/blob/master/lib/ace/background_tokenizer.js#L231.

Replacing whole background_tokenizer might give better performance.

**Comment by zhanzhenzhen** [comment]
Already found that. But thank you all the same:)
