### ISSUE TITLE
f# mode

### ISSUE THREAD

**Issue by adamjimenez** [ajaxorg/ace#2871]
Can this f# mode be included?
https://github.com/BayardRock/FSharpWebIntellisense/blob/master/src/FSharp.Web.UX/Scripts/ace/mode-fsharp.js

it has apache licensed 2.0

**Comment by nightwing** [comment]
I think to include in ace we need a cla.

**Comment by tamizhvendan** [comment]
@nightwing Any updates on this?

**Comment by adamjimenez** [comment]
We need a cla see:
https://github.com/BayardRock/FSharpWebIntellisense/issues/8
