### ISSUE TITLE
Scroll bar is not visible on Safari

### ISSUE THREAD

**Issue by yoshiokatsuneo** [ajaxorg/ace#2872]
On Safari, I cannot see vertical or horizontal scroll bar, but the are is just white rectangle.
I can just see the issue even on https://ace.c9.io/ top page with long line.

The issue happens on both Safari 9.0.3 on Mac OS X El Capitan, and Safari on iOS 9.2.1.
I don't see the issue on Chrome or Firefox on Mac OS X.

My workaround is adding CSS below, or adding any non space contents to the DIV with ace_scrollbar-inner class.

```
.ace_scrollbar-inner {
  background-color: white;
  opacity: 0.01;
}
```

**Comment by syberknight** [comment]
THANK YOU!!!

**Comment by tjhiggins** [comment]
👍

**Comment by adrianbj** [comment]
Thanks @yoshiokatsuneo !

@nightwing - just bumping this for inclusion in the core please. It still seems to be an issue in Safari and the proposed solution works here.

**Comment by nightwing** [comment]
fixed in https://github.com/ajaxorg/ace/pull/3987
