### ISSUE TITLE
Is it possible to add custom html between two lines?

### ISSUE THREAD

**Issue by waywaaard** [ajaxorg/ace#2874]
We would like to add custom html between two code lines which could display comments or any other additional information. Is this currently possible?

Here is an image showing the monaco editor doing something similar.

![](http://www.hanselman.com/blog/content/binary/Windows-Live-Writer/A-new-rich-code-editor-now-spreading-to-_BF8F/Screenshot%20(15)_8f63a156-c2e4-48da-b075-9c02873739dd.png)

**Comment by nightwing** [comment]
Error marker does something similar using line widget api see [error_marker.js#L94 ](https://github.com/ajaxorg/ace/blob/master/lib/ace/ext/error_marker.js#L94 ) 

[inline_editor.js#L72](https://github.com/ajaxorg/ace/blob/master/demo/kitchen-sink/inline_editor.js#L72) is another example of using that api

**Comment by nightwing** [comment]
Closing, but feel free to comment if you have more questions.

**Comment by waywaaard** [comment]
Thanks, going to have a look at this.

**Comment by hadrienk** [comment]
I managed to insert an element based on the inline_editor example but I would like to have it expand the gutter as well. Any idea how to do that?

![image](https://user-images.githubusercontent.com/207345/45232154-b38a6a00-b2ce-11e8-84b8-f37bfdbedd19.png)

**Comment by nightwing** [comment]
@hadrienk set `coverGutter: true,` on the widget

**Comment by hadrienk** [comment]
It worked, thanks.
