### ISSUE TITLE
Scrolling in Microsoft Edge doesn't work on code editor element

### ISSUE THREAD

**Issue by BrianFranklin** [ajaxorg/ace#2875]
This is reproducible in the kitchen sink demo using the Edge browser on Windows 10:

1. Enter a bunch of lines so there's scrollable content (this works horizontally and vertically).
2. Place the mouse pointer over the code area and use a scroll wheel or touch scroll to try to scroll up/down, left/right. There will be no scrolling.
3. Place the mouse pointer over the vertical scrollbar and use a scroll wheel or touch scroll to try to scroll up/down. Scrolling works.
4. Place the mouse pointer over the horizontal scrollbar and use a scroll wheel or touch scroll to try to scroll left/right. Scrolling works.

This is different from other browsers where scrolling while positioned over the actual code editor will scroll as expected. There are no errors or warnings in the browser console.

**Comment by nightwing** [comment]
I cannot reproduce this using edge browser on windows 10 vm and http://ajaxorg.github.io/ace/kitchen-sink.html. maybe this depends on device too.
Could you try to debug this a bit more. set breakpoints  in https://github.com/ajaxorg/ace/blob/master/lib/ace/lib/event.js#L145 to see which of event listeners is added, and if the event listeners gets called when scrolling.

**Comment by BrianFranklin** [comment]
Interesting... Doing some digging, and I'm seeing that we get into the condition that checks for the presence of `onmousewheel` on the editor element here:

https://github.com/ajaxorg/ace/blob/da31749319bceaf0d64c9e5e079dc79adad37f10/lib/ace/lib/event.js#L145-L146

I can also see that after the event is attached to the element, the editor does have the anonymous function bound that's set on line 146.

I've tried four devices so far, each running an up-to-date Windows 10:

1. Macbook Pro using Bootcamp
2. Surface Pro 3
3. SurfaceBook
4. A custom built desktop computer

The desktop works fine using a Wedge mouse, but in each case that I'm using a touchpad, the `onmousewheel` event never fires. If I plug a wired mouse into the laptops and use it instead of the touchpad, the editor scrolls as expected.

I tried to remove any other factors by making a basic HTML page with only an `onmousewheel` event to fire some logs at my console, and that alone doesn't work. I tried everything listed in the [Edge API event reference](https://dev.windows.com/en-us/microsoft-edge/platform/documentation/apireference/events/) without success. I 

I don't think this is actually an Ace bug now, although I'm still investigating whether or not anything can be done to work around the issue. I'm closing this and if needed I'm going to open an Edge bug instead.

Thanks!

**Comment by nightwing** [comment]
Does it send `"wheel"` events?

**Comment by BrianFranklin** [comment]
It doesn't. I've actually found a couple old reports of this problem in the Edge bug tracker (as it relates to two-finger touch scrolling and mousewheel/wheel events) that was shrugged off as non-reproducible by one of the Edge developers, and I'm going to see if I can resurrect that.
