### ISSUE TITLE
`translatez(0)` causing blurred text

### ISSUE THREAD

**Issue by zhanzhenzhen** [ajaxorg/ace#2878]
If the parent container has CSS transforms such as "translate", then ACE will make the whole page blurred. But this is not an ACE bug. It's probably a WebKit bug that can be reproduced in Chrome and Safari in Mac OS X.

You can reproduce it by visiting my own language FutureScript's home page:
http://futurescript.org/

Now it renders perfectly, but that's because I modified `ace.js` to delete `translatez(0)`:
![2](https://cloud.githubusercontent.com/assets/731796/12840392/05135e94-cc1e-11e5-8972-a81382f1e281.png)

But if you re-add the `transform: translatez(0)` to `.ace_cursor` you will see this effect:
![1](https://cloud.githubusercontent.com/assets/731796/12840387/fa9fc4f2-cc1d-11e5-94de-50254565d36e.png)

(Why I use `translate(-50%,-50%)` is that `left` and `top` can be treated as the central point of an element, so that some UI design can be easier.)

Some people already reported this bug to Chromium and WebKit projects a year ago, but it's still unsolved. I think it may remain unsolved in the near future.

This bug doesn't exist in Windows.

**Comment by nightwing** [comment]
He had to add translate(0) since without that smooth cursor setting was causing rendering glitches on chrome some time ago.

**Comment by DavidSichau** [comment]
Is there any progress. We have users reporting this issue for Windows 10.
