### ISSUE TITLE
Support for BSON (MongoDB)?

### ISSUE THREAD

**Issue by samrm111** [ajaxorg/ace#2889]

**Comment by nightwing** [comment]
what do you mean by `support`? [BSON](http://bsonspec.org/) doesn't seem to be a language for which we could add syntax highlighting.

**Comment by samrm111** [comment]
It could be only a syntax check. It is pretty much the same as JSON except for BSON types such as ObjectID().

Full list of supported BSON types :
https://docs.mongodb.org/manual/reference/bson-types/

**Comment by feliixx** [comment]
A syntax checker for BSON would be really helpfull ! Is there any updates on this ?
