### ISSUE TITLE
Scrollbar disappears if text is too big

### ISSUE THREAD

**Issue by MRJCrunch** [ajaxorg/ace#2890]
Scrollbar disappears if text is too big.
I've found this problem, when I tried to use editor.setValue() with a really big text(about 30MB).
I'll try to explain why it happens:

Every browser has maxHeight for an element, which it can handle:
10737419px for IE, 17895698px for FireFox and 33554428px for Chrome.
Scrollbar(.ace_scrollbar-inner) in the aceEditor has height depending on the height of the text. And if a text has height more than maxHeight for browser, $(element).height() function always returns 0 and scrollbar disappears.
http://jsfiddle.net/y4tLxx53/9/
Maybe you should try another method for scrolling, like this:
http://jsdo.it/zz85/75cq

**Comment by nightwing** [comment]
after some value increasing the height of .ace_scrollbar-inner doesn't change the way scrollbar is drawn, we could normalize scroll positions if they are larger than say 0xFFFFF to not trigger this behavior.

**Comment by MRJCrunch** [comment]
Yes, you could
