### ISSUE TITLE
How to get cursor absolute position in text?

### ISSUE THREAD

**Issue by sergiusignacius** [ajaxorg/ace#2891]
Hi guys,

Is there a way to figure out what is the absolute cursor offset for a given text instead of a row/column?

Cheers,
Sérgio

**Comment by nightwing** [comment]
see https://groups.google.com/d/msg/ace-discuss/vfY7Q8RvGgE/o9mneFsACgAJ

**Comment by sergiusignacius** [comment]
Thanks! :+1:
