### ISSUE TITLE
Descriptions in auto-complete items

### ISSUE THREAD

**Issue by sergiusignacius** [ajaxorg/ace#2892]
Hi guys,

I'll need to provide custom descriptions for auto complete items. This already happens for snippets, where a tooltip shows the template of the script. Is there an API I can use for this?

Thanks!

**Comment by nightwing** [comment]
see https://github.com/ajaxorg/ace/blob/master/lib/ace/ext/language_tools.js#L73

**Comment by sergiusignacius** [comment]
Ok so I'd need to do the same for autocomplete items. Is this on the
roadmap? If I implement it, I'll create it if it isn't.

Thanks!

**Comment by nightwing** [comment]
You need to add getDocTooltip function to your autocompleter to provide custom descriptions for autocomplete entries created by it.

> Is this on the roadmap?

Not sure what do you mean here.

**Comment by sergiusignacius** [comment]
Thanks! I'll do that. 

> Not sure what do you mean here.

Sorry, I wasn't clear. I'm working on extending the autocompleter for Javascript. What I meant here was if there are plans to add descriptions to the autocomplete items for the language.

**Comment by cpetry** [comment]
What happened to this issue?
@sergiusignacius : Did you add this feature? Can you give an example on how to add this?

**Comment by sergiusignacius** [comment]
Hey @cpetry,

We ended up switch to VS code.

Sorry I can't be of more help!

**Comment by cpetry** [comment]
Still thanks for the info.
@nightwing can you give me more hints about how to implement this?
I would gladly contribute.
