### ISSUE TITLE
Extending certain lines

### ISSUE THREAD

**Issue by pawelkondraciuk** [ajaxorg/ace#2901]
Its not an issue, I am looking for way to extend height of few lines. I came up with half-way solution taken from #1817. 
```javascript
var rows = [1,4,6];
session.getRowLength = function(row) {
    var h = 0;
    if (row in rows) 
       h = 2;
    if (!this.$useWrapMode || !this.$wrapData[row]) {
        return 1 + h;
    } else {
        return this.$wrapData[row].length + 1 + h;
    }
} 
```
It works almost good. Markers aren't displayed properly also when I scroll lines acts like 1 line height, they dissapear too early. Auto scroll is also broken it treats multiline row as a singleline row. How can I extend some lines and make everything work well (it is the same functionality as line wrapping except that extended line should be empty)? Example:
![screen shot 2016-02-18 at 14 28 39](https://cloud.githubusercontent.com/assets/7136191/13144731/a538a73e-d64c-11e5-9b42-f3d4e7825bc9.png)

**Comment by nightwing** [comment]
You could use line widgets similar to https://github.com/c9/c9.ide.scm/blob/ca3c94b84fbd864eee9bcc9617f044a94aad4175/diff/twoway.js#L241

**Comment by pawelkondraciuk** [comment]
@nightwing It works almost good except that line is dissapearing too early (like it is just one line)

**Comment by pawelkondraciuk** [comment]
@nightwing nvm, it fixes my bug :) thanks
