### ISSUE TITLE
s.nextState can be a function

### ISSUE THREAD

**Issue by leofeyer** [ajaxorg/ace#2902]
After updating to version 1.2.3, editing PHP files was no longer possible:

```
s.nextState.indexOf is not a function
```

After some debugging I found out that `s.nextState` can be a function (named `push()` in my case). I have added a workaround in [text_highlight_rules.js:68](https://github.com/ajaxorg/ace/blob/master/lib/ace/mode/text_highlight_rules.js#L68):

```js
if (rule.nextState && typeof rule.nextState != "function" && rule.nextState.indexOf(prefix) !== 0)
```

However, I'm pretty sure that this is not the correct way of solving the issue ;)

**Comment by nightwing** [comment]
This is most likely caused by mootools modifying object prototype.
Please try using https://github.com/ajaxorg/ace-builds/commit/4c1551465499afb012ddb053a18872de83350357

**Comment by leofeyer** [comment]
Yes, I can confirm that the error is gone in ajaxorg/ace-builds@4c1551465499afb012ddb053a18872de83350357. Thanks a lot.
