### ISSUE TITLE
Ace validation allows invalid css

### ISSUE THREAD

**Issue by aaronmallen** [ajaxorg/ace#2907]
# Issue:
* Editor allows valid css tags without semi-colon (in any line).
* Editor allows technically correct syntax, but invalid css tags.

# Expected Result:
  * Editor should provide error annotation for css tags without semicolon (except for last property).
  * Editor should provide error annotation for invalid css tags,although technically correct (invalid css property/values are in black color)

**Comment by nightwing** [comment]
Can you please paste sample code to better explain what you mean?

**Comment by aaronmallen** [comment]
```
body {
    background-color: aqua;
    font-size: 18px;
     font-styl: italic;
     asdf: asdfasdfasdfasdfdsdsg
     dsfdsfdsfdsfdsf
     dsdfsdfdsf
     dsfsdfsdf
     dfdsf
    }
```
The above css does not create an error annotation.

```
body {
    background-color: aqua;
    font-size: 18px
     font-styl: italic;
    }
```
The above css does not create an error annotation.

**Comment by DontShootMe** [comment]
Maybe you use an old version ?
Testing  your code in the [Ace Mode Creator](https://ace.c9.io/tool/mode_creator.html), the invalid CSS are marked as invalid !

**Comment by aaronmallen** [comment]
This would appear to be a bug around the interface I am using for Ace. Closing and creating a new bug with that project.
