### ISSUE TITLE
Support for PHP 7

### ISSUE THREAD

**Issue by plugowski** [ajaxorg/ace#2908]
Hi,

Editor didn't understand php 7 constructs and mark it as incorrect;

```
<?php declare(strict_types=1);
```

show message: Syntax error, unexpected '=', expecting ')'

```
function foobar(): int {}
```

show  message: Syntax error, unexpected ':', expecting '{'

```
function test(int ...$i) {
    return $i;
}
```

show message: show  message: Syntax error, unexpected ':', expecting T_VARIABLE

```
$username = $_GET['user'] ?? 'nobody';
```

show message: show  message: Syntax error, unexpected '?'

```
echo 1 <=> 2;
```

show message: show  message: Syntax error, unexpected '>'

```
$app->setLogger(new class implements Logger {
    public function log(string $msg) {
        echo $msg;
    }
});
```

show message: show  message: Syntax error, unexpected T_CLASS, expecting ')'

http://php.net/manual/en/migration70.new-features.php

**Comment by SjonHortensius** [comment]
I've been staring really hard at https://github.com/ajaxorg/ace/blob/36e6744a5f40df0da52ff22b3bc729657c056e09/lib/ace/mode/php/php.js, but I cannot figure out how to add support for various php7 features.
Should this be done manually, or is it possible to recreate this file using the current php parser?

**Comment by nightwing** [comment]
that file was taken from https://github.com/niklasvh/php.js, which seems to not be maintained anymore.
we need to find some other php parser in js or maybe use http://lakhin.com/projects/papa-carlo/

**Comment by adamjimenez** [comment]
PHP.js hasn't been actively maintained but he has merged pull requests for those looking to contribute.

**Comment by SjonHortensius** [comment]
I also noticed https://github.com/niklasvh/php.js/issues/69, but ACE only needs the parser; not the actual implementation. It seems the parser is 'simply' a converted yacc parser, but I cannot find the instructions to redo this with a [the new parser from php7](https://github.com/php/php-src/blob/master/Zend/zend_language_parser.y)

**Comment by plugowski** [comment]
I tried to find other JavaScript parser for PHP, but with no results...

**Comment by adamjimenez** [comment]
php.js is used for syntax checking not highlighting in Ace.

**Comment by adamjimenez** [comment]
Uses kmyacc

```
trim(shell_exec('kmyacc -l -m kmyacc.js.parser ' . TMP_FILE . ' 2>&1')),
```

From:
https://github.com/niklasvh/php.js/blob/master/grammar/rebuildParser.php#L40

**Comment by plugowski** [comment]
I installed kmyacc on my mac, but when I try to run rebuildParser.php but zend_language_parser.y - https://github.com/php/php-src/blob/master/Zend/zend_language_parser.y -  has got different structure than previous one so script throws Exception: Unknown macro "sizeof" :/

**Comment by adamjimenez** [comment]
presumably we need another if statement in resolveMacros:
https://github.com/niklasvh/php.js/blob/master/grammar/rebuildParser.php#L82

**Comment by nikic** [comment]
The php.js parser is based on https://github.com/nikic/PHP-Parser. To make it work with PHP 7 one would have to update it to use (a modified version of) the grammar definition at https://github.com/nikic/PHP-Parser/blob/master/grammar/php7.y. As the grammar in php.js contains changes and the PHP-Parser has diverged quite a bit in the last 4 years, this will probably not be a simple update.

**Comment by nikic** [comment]
From a quick look it seems like ace does not actually need any of the AST construction logic -- it uses the parser only for syntax checking. If all the semantic actions from the grammar are simply discarded, generating a new parser would probably be much simpler.

**Comment by nikic** [comment]
PR up at #3107.

**Comment by SjonHortensius** [comment]
@nikic awesome work; I've used your branch to create a new worker & mode which I've deployed on https://3v4l.org and it works great. Thanks!
