### ISSUE TITLE
change event stopPropagation

### ISSUE THREAD

**Issue by dwelle** [ajaxorg/ace#2910]
The `change` event is not passed an event object which would allow for `stopPropagation`. What I want to achieve is to stop the `change` event from propagating to `selection`'s `changeCursor` event. Is that possible?

ace `1.2.3`

**Comment by nightwing** [comment]
it is not possible to stop change event since stopping it would make editor
state inconsistent.
why do you want to prevent selection getting change event? there may be
another way to achieve the same result.

**Comment by dwelle** [comment]
The handlers for `change` and `changeCursor` both tweak DOM in bit different ways so there's a race condition. It's not a problem to hack it (I cache a `lastEvent` and cancel the `changeCursor` if `change` preceded it, which works since the ace eventing is synchronous), but I just wondered if there's a clean way.
