### ISSUE TITLE
Ctrl-C Breaking on IE versions in Web Browser Control with Edge Mode

### ISSUE THREAD

**Issue by RickStrahl** [ajaxorg/ace#2913]
This is kind of an edge case but it's causing me some grief. I'm use Ace Editor in a Web Browser control for rendering code blocks - it's readonly mode. I'm also using it in CHM files - which also use some variation of a Web Browser control. 

But using the IE-Edge meta header the control actually renders and even works for most editing operations.

However one big issue that doesn't work is the clipboard functionality - and most importantly Ctrl-C.

For copy operations, the problem is this line in `handleClipboardData`:

```
 return clipboardData.setData(mime, data) !== false;
```

which gets:

**Unexpected call to method or property access**

This workaround seems to work returning the raw captured text without formatting:

```
if (clipboardData) {
                    try {
                        return clipboardData.setData(mime, data) !== false;
                    }
                    catch(ex) {
                        return;
                    }
}
```

This seems to work to return the raw text at least without failing.

FWIW, it's pretty damn cool that Ace works at all in this environment and it's a bonus that it does for me. I realize this is an edge case at best, but this is relatively simple fix that at least makes it possible to run inside of this funky browser environment.

**Comment by nightwing** [comment]
Could you check what value mime has, and if it works when using the other one from https://github.com/ajaxorg/ace/blob/master/lib/ace/keyboard/textinput.js#L272

**Comment by RickStrahl** [comment]
`mime` is set to `text/plain` and it seems to work with `Text`.

**Comment by RickStrahl** [comment]
When running in the Web Browser control (in CHM file or default Web control) the ` USE_IE_MIME_TYPE` value is `NaN`. For other versions 9, 10, 11 it's the version number. Makes sense since you don't support the older versions. 

After some more experimenting it seems that `Text` works in all versions of IE that I tried with browser emulation, so it looks to me that there should be no reason to use `text/plain` as the mime type?

**Comment by nightwing** [comment]
`text/plain` is needed for other browsers. Old webkit didn't work with 'Text', and on linux not all programs handle text copied with mime type "Text"
We probably could detect useragent detection, but https://github.com/ajaxorg/ace/pull/2915 should work too.

**Comment by RickStrahl** [comment]
Cool.

Another might be  add IE 7/8 to the captured IE versions for the `USE_IE_MIME_TYPE` constant...
It's a thing to consider for other things as well - in Edge mode the version number may just be bogus.

**Comment by nightwing** [comment]
code for detecting IE version is at  https://github.com/ajaxorg/ace/blob/master/lib/ace/lib/useragent.js#L76.

We already set USE_IE_MIME_TYPE to true for IE 7/8 but In edge useragent is different, so it ends up parsed as non ie.

**Comment by RickStrahl** [comment]
It looks to me that the browser check doesn't catch IE 7/8 in USE_IE_MIME_TYPE. I get NaN.
When I run in Edge mode I get NaN and the userAgent is IE 7 in that case.

isIE is NaN with this user agent:
`NaN Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0)`

`navigator.appName` is `Netscape` which might be the problem in this detection code.

This might be more reliable to detect IE 7-11:
```
var isIEBrowser = window.ActiveXObject && window.ActiveXObject.length;
```

**Comment by RickStrahl** [comment]
Unfortunately that code doesn't capture the browser correctly for IE 7 in the Web browser control. `navigator.appName` is `Netscape` and that makes that code never actually check for the version number.

This might be more reliable (if a bit uglier):
```javascript
var isIEBrowser = false
try {
    isIEBrowser = window.ActiveXObject.length ? true : false;  
} catch(e) { }

exports.isIE =  isIEBrowser
    ? parseFloat((ua.match(/(?:MSIE |Trident\/[0-9]+[\.0-9]+;.*rv:)([0-9]+[\.0-9]+)/)||[])[1])
    : parseFloat((ua.match(/(?:Trident\/[0-9]+[\.0-9]+;.*rv:)([0-9]+[\.0-9]+)/)||[])[1]); // for ie
```

This will get the version number properly for all versions of IE that tried in the IE Emulation modes, and it should also work for non-IE browsers.

**Comment by nightwing** [comment]
detecting ie edge as ie7 might be worse, since that will trigger code for isOldIE.

**Comment by RickStrahl** [comment]
Yeah that's why I didn't give you PR here. I'm not sure what the ramifications are for this throughout this large code base. 

Maybe another flag is needed in the userAgent module that returns just true or false rather than the version number. This is why useragent sniffing is such a bitch :-)

If I had to do this I would just throw the `isIEBrowser` check inline in the `handleClipboardData` and be done with it, but I can see why that wouldn't be very clean.

Thanks for looking at this. As long as Ctrl-C won't throw on old IE errors I'm stoked. 

Aloha.

**Comment by wdbsb** [comment]
Harutyun and Rick - I see that this prevents the error message but it does not make copy/paste actually work.  Is that correct?  If that is the case do you have any suggestions to work around this for embedded IE11?
Thanks

**Comment by RickStrahl** [comment]
If you're using embedded IE 11 and you're using the Registry flags to force it into IE 11 mode then things work as expected. The problem is just if you don't force the browser version explicitly and only rely on edge mode. 

I believe @nightwing's path should take care of this though even though it's a bit more involved. I don't think it's made it into the releases yet.

**Comment by wdbsb** [comment]
I'm actually using `<meta http-equiv="X-UA-Compatible" content="IE=edge">`.  I'd guess that 60-70% of my users have IE 11 so most of them are affected.  Is there a way that I can override handleClipboardData or opCut/onCopy/onPaste so that I can still use a CDN?

**Comment by wdbsb** [comment]
@nightwing  - I tried your modification to handleClipboardData (https://github.com/ajaxorg/ace/commit/f13bd0b372d631d50c971ca28cbf89c97b866181) and found that it causes infinite recursion in the embedded IE11 browser.  It always calls itself with the same arguments that were passed to it. 

Could I make an alternate suggestion?  You were concerned that Rick's modified exports.isIE setting code would cause an embedded browser in edge mode to be detected as IE7 and trigger code for isOldIE.  Here is a slight change to Rick's code that would avoid that:

```
var isIEBrowser = false
try {
    isIEBrowser = window.ActiveXObject.length ? true : false;  
} catch(e) { }

exports.isIE =  isIEBrowser
    ? parseFloat((ua.match(/(?:MSIE |Trident\/[0-9]+[\.0-9]+;.*rv:)([0-9]+[\.0-9]+)/)||[])[1])
    : parseFloat((ua.match(/(?:Trident\/[0-9]+[\.0-9]+;.*rv:)([0-9]+[\.0-9]+)/)||[])[1]); // for ie

if (isIEBrowser && navigator.appName=="Netscape" && isIE=="7") exports.isIE=11; // IE11 Embedded detection

```


Thanks.

**Comment by nightwing** [comment]
@wdbsb thanks for noticing! It needed to pass true instead of passing the same argument. Could you try the updated version https://github.com/ajaxorg/ace/pull/2915/commits/d7d3d79135c86a3dd7fd9b0ed2dd0b0147e1bb32?

**Comment by wdbsb** [comment]
@nightwing Thanks.  The updated version worked.  You might still want to consider the fix for exports.isIE (above)  just in case there are other things that break when exports.isIE has the value NaN.

**Comment by RickStrahl** [comment]
@wdbsb You'd have to be careful with your fix though as there could be versions other than IE 11 that run in Edge mode. 

However, at this point assuming IE 11 in edge mode is probably going to work as IE 10 has the same characteristics and if you're running IE 9 embedded well, you're just out of luck :-)

**Comment by wdbsb** [comment]
@RickStrahl Good point.  If the browser is embedded IE8, IE9 or IE10 then isIE will still be 7.  I don't know how to test for those.
