### ISSUE TITLE
Matching braces highlighting does not remove previous brace highlighting on new brace selection

### ISSUE THREAD

**Issue by chrissimpkins** [ajaxorg/ace#2918]
We are using ace.js v1.2.3 via cdnjs on the Font Playground site (https://sourcefoundry.org/hack/playground.html) and a user reported a matching braces highlighting issue with the following behavior:

- selection of a left brace appropriately matches and highlights the closing right brace
- selection of a new left brace appropriately highlights the matching right brace but the previously matched / highlighted right brace remains highlighted.

<img src="https://cloud.githubusercontent.com/assets/4249591/13482319/46c8256c-e0ba-11e5-92a9-3908a173aef7.gif" width="450" />

It was reported by a user in https://github.com/sf-web/sf-web.github.io/issues/9 on Ubuntu 14.04 with the Chromium browser and I can verify that it also occurs on OS X 10.10.5 in Firefox 46.0a2 (2016-03-02).

Any thoughts?

cc:@jublo

**Comment by nightwing** [comment]
looks like you have same session attached to two different editors.

**Comment by chrissimpkins** [comment]
@nightwing Thank you very much for the rapid response Harutyun.  I am assuming that this is coming from the side-by-side editor display approach that we are using?  We do have two editors implemented on the page.  

Is it possible to disable the brace matching feature?  The goal here is the display of code + syntax highlighting with the various typefaces, not to edit code.

cc: @burodepeper

**Comment by nightwing** [comment]
Sessions shared that way are going to cause other problems too. you can create two editors and set same value to both of them.

**Comment by chrissimpkins** [comment]
Thank you very much for your help.  I greatly appreciate it.  It looks like this is an issue on our end.  Will close this report.
