### ISSUE TITLE
vim mode block wise substitution

### ISSUE THREAD

**Issue by sreich** [ajaxorg/ace#2922]
can witness at: https://ace.c9.io/build/kitchen-sink.html

-set editor mode to vim
-enter blockwise visual mode (ctrl v)
-navigate down/up a few blocks
-hit s (for blockwise substitution)
- enter some chars
  -exit visual mode(escape)

only the first line gets the substitution, the rest just remove the chars. by contrast, this works with r and c, just not s. s is documented in vim as supposed to behave the same in visual mode.

**Comment by nightwing** [comment]
will be fixed by https://github.com/ajaxorg/ace/pull/2924
