### ISSUE TITLE
Deletion of nested selections in snippets cause highlighting error

### ISSUE THREAD

**Issue by cssherry** [ajaxorg/ace#2925]
If there was a nested snippet (for example, 
"CASE ${1:value} WHEN ${2:option1} THEN ${3:result1} ${4:WHEN ${5:option2} THEN ${6:result2}} ${7:ELSE ${8:default}} END"), the tabbing works properly if the user tabs through each selection.

However, if the user removes the outer nesting (eg by deleting ${4:....}), then tabbing will still try to select the nested snippet (eg, the position of ${5:...} will still be incorrectly selected even after deleting ${4:... ${5:...}...}). 

The expected behavior would be for the next existing selection to be tabbed to (for example, the position ${7:...} should be highlighted after ${4:...} is deleted).  

<img width="513" alt="screen shot 2016-03-15 at 5 07 25 pm" src="https://cloud.githubusercontent.com/assets/6097953/13798153/9f2c0230-ead0-11e5-924c-a1e4a82b6e1c.png">

<img width="505" alt="screen shot 2016-03-15 at 5 07 35 pm" src="https://cloud.githubusercontent.com/assets/6097953/13798154/9f31cec2-ead0-11e5-95c4-94c1a1238b6b.png">

**Comment by zhoux10** [comment]
I'm looking into this, currently looking in lib/ace/snippets.js file
