### ISSUE TITLE
Pressing backspace twice in snippet prevents tab from working again

### ISSUE THREAD

**Issue by cssherry** [ajaxorg/ace#2926]
When in snippet, and press backspace to remove the highlighted selection, then press backspace again to remove extra space, user can no longer tab to the next selection. 

Eg: For 
"CASE ${1:value} WHEN ${2:option1} THEN ${3:result1} END", when user delete ${2:..}, and the space in front of the selection, they can no longer tab to ${3:...}

**Comment by zhoux10** [comment]
I'm looking into this, currently looking in lib/ace/snippets.js file
