### ISSUE TITLE
API endpoint for setting selection from list of ranges

### ISSUE THREAD

**Issue by kevinushey** [ajaxorg/ace#2929]
Ace provides `addRange()` for adding a new range to the current selection (potentially entering multiselect mode if necessary). However, 'setting' the selection to a list of ranges is a bit tricky, because management of the current (single) selection is necessary.

The `findAll()` function has to handle this, e.g. here:

https://github.com/ajaxorg/ace/blob/master/lib/ace/multi_select.js#L591-L596

I wonder if this could be promoted to e.g. `session.setSelectionRangeList(list)`, which manages the primary selection as appropriate?

**Comment by nightwing** [comment]
there are toJSON fromJSON methods on selection which do something similar.

**Comment by kevinushey** [comment]
That looks like what I need. Thanks!
