### ISSUE TITLE
Fold *only* #region/#endregion code

### ISSUE THREAD

**Issue by NogsMPLS** [ajaxorg/ace#2937]
Is there a way to fold *only* regions of code using the methods described here: 

https://github.com/ajaxorg/ace/wiki/Non-Standard-Code-Folding

I tried `editor.session.foldAll()` but that also folds everything in `{...}` and `[...]`. I just want to fold ONLY the areas between `#region` and `#endregion`.

Sorry if this is something obvious, I'm having a hard time finding out options that are available to use. For instance, session.foldAll() isn't in the API reference https://ace.c9.io/#nav=api

**Comment by nightwing** [comment]
There is no api for this, you'll need to copy logic of https://github.com/ajaxorg/ace/blob/v1.2.3/lib/ace/edit_session/folding.js#L636-L666 and 
add `if (!/#region/.test(this.getLine(row))) continue` at https://github.com/ajaxorg/ace/blob/v1.2.3/lib/ace/edit_session/folding.js#L649

**Comment by NogsMPLS** [comment]
Hmmm...okay thanks

**Comment by NogsMPLS** [comment]
Okay cool, just wanted to confirm that this worked for me by adding to session protype. so for future people possibly wanting to do this, i did this:

```javascript
editor.session.__proto__.foldRegion = function(startRow, endRow, depth) {
      if (depth == undefined)
          depth = 100000; // JSON.stringify doesn't hanle Infinity
      var foldWidgets = this.foldWidgets;
      if (!foldWidgets)
          return; // mode doesn't support folding
      endRow = endRow || this.getLength();
      startRow = startRow || 0;
      for (var row = startRow; row < endRow; row++) {
          if (foldWidgets[row] == null)
              foldWidgets[row] = this.getFoldWidget(row);
          if (foldWidgets[row] != "start") continue;
          if (!/#region/.test(this.getLine(row))) continue; //regex to fold #region areas
          var range = this.getFoldWidgetRange(row);
          // sometimes range can be incompatible with existing fold
          // TODO change addFold to return null istead of throwing
          if (range && range.isMultiLine()
              && range.end.row <= endRow
              && range.start.row >= startRow
          ) {
              row = range.end.row;
              try {
                  // addFold can change the range
                  var fold = this.addFold("...", range);
                  if (fold)
                      fold.collapseChildren = depth;
              } catch(e) {}
          }
      }
    }
```

Could possibly make the regex a bit more robust to handle other situations, but that should get basic functionality in there. 

Thanks @nightwing I'll close this now.
