### ISSUE TITLE
Performance issues with editor.setOption('maxLines', 5000);

### ISSUE THREAD

**Issue by paulocheque** [ajaxorg/ace#2947]
I am having this issue when I use a text with 900 lines.

When I comment the `maxLines` config, the editor is fast. Otherwise, the typing is very slow. Is that an issue of Ace editor? Or am I missing any config??
- I am using Chrome 49.0.26 on OSX.
- Ace editor 1.2.3
- Using raw Javascript

Follow my setup:

```
editor = ace.edit("editor");
editor.setTheme("ace/theme/github");
editor.getSession().setMode("ace/mode/markdown");
editor.getSession().setUseWrapMode(true);
editor.getSession().setNewLineMode("unix");

**editor.setOption('maxLines', 5000); // this is required for the auto synced scroll**
editor.$blockScrolling = Infinity;

editor.setShowPrintMargin(false);
editor.renderer.setShowGutter(false);
editor.renderer.setOption('showLineNumbers', false);
```

Thanks in advance!

**Comment by nightwing** [comment]
maxLines is not designed to work that way. When there are too many dom nodes, browser becomes slow and there is no way around that.
Could you tell more about your usecase (e.g. show demo page)? maybe we can find a warkaround.

**Comment by paulocheque** [comment]
Thanks for the fast answer!

I am using Ace editor to compose markdown articles. In the page, we display a live preview. The **scroll** between the Ace Editor and the Preview must be **synced**. But I was just able to make this with the **maxLines enabled**. If I disable this option, the synced scroll stop working.

**Comment by paulocheque** [comment]
With maxLines setted:

![screen shot 2016-04-19 at 9 13 08 pm](https://cloud.githubusercontent.com/assets/94350/14659646/33407776-0674-11e6-94bb-684b2102f382.png)

Without maxLines:

![screen shot 2016-04-19 at 9 17 39 pm](https://cloud.githubusercontent.com/assets/94350/14659648/3591bb02-0674-11e6-8aa9-e1765d63a727.png)

**Comment by paulocheque** [comment]
I saw this performance issue is related to the wrapper I am using, but I have no idea 

    <div id="editor-wrapper">
        <div id="editor"></div>
    </div>

    #editor-wrapper {
        padding: 0;
        overflow: scroll;
        height: 400px;
    }

    #editor {
        min-height: 400px;
    }


    editor.getSession().setUseWrapMode(true);
    editor.setOption('minLines', 10); // this is required for the auto synced scroll
    editor.setOption('maxLines', 25); // this is required for the auto synced scroll
    editor.setAutoScrollEditorIntoView(false);
    editor.$blockScrolling = Infinity;

**Comment by paulocheque** [comment]
I guess we can summary this issue like: a higher number of the `maxLines` cause performance degradation.

**Comment by nightwing** [comment]
You can get scrolltop using `editor.session.getScrollTop()` there is no need to use maxLines for that, however it is still not a good idea, since scroll heights of preview and the code are different most of the time. see https://github.com/c9/c9.ide.preview.markdown/blob/master/markdown.js for a better way of syncing scroll positions

**Comment by paulocheque** [comment]
Thanks for the link.

Actually I did exactly like you said. I used scrollTop and stop using maxLines, then I got a good performance.

This issue can be closed for me. Just keep in mind the issue with high values in maxLines property.
