### ISSUE TITLE
Can't remove event listener on change event.

### ISSUE THREAD

**Issue by hadijaveed** [ajaxorg/ace#2952]
```
'htmlEditor.getSession().addEventListener('change', handleChange);
 htmlEditor.getSession().removeEventListener('change', handleChange);`
```

Handlechange is my callback that I bind on the change event. I can't remove change event listener. I have tried **off** and **removeListener** too but found no luck.

**Comment by nightwing** [comment]
any of `off` `removeListener` `removeEventListener` should work see implementation at https://github.com/ajaxorg/ace/blob/master/lib/ace/lib/event_emitter.js#L138

**Comment by hadijaveed** [comment]
@nightwing thank you!! It was a type in my code. It is working perfect now!!
