### ISSUE TITLE
Odd behavior updating JSHint options

### ISSUE THREAD

**Issue by willyg302** [ajaxorg/ace#2955]
I started with a simple file containing lots of unused variables: [ace-jshint.txt](https://github.com/ajaxorg/ace/files/237276/ace-jshint.txt)

If you copy the contents of this file into the [kitchen sink](https://ace.c9.io/build/kitchen-sink.html), you will notice that a yellow warning icon appears next to line 200 with the text `Too many errors. (97% scanned).` This makes sense, since none of the functions are used anywhere. However, no info icons appear next to their declarations. If you uncomment the `'use strict';` at the top, no icons show up. This I cannot explain.

I thought I'd fix this by adding the following code:

``` javascript
editor.session.on('changeMode', (e, session) => {
    if (session.getMode().$id === 'ace/mode/javascript' && session.$worker) {
        session.$worker.send('changeOptions', [{ unused: true }]);
    }
});
```

since by default it is [unset](https://github.com/ajaxorg/ace/blob/2d4b2f64b265244c8e30bb9b29b3d240450b5f47/lib/ace/mode/javascript_worker.js#L81), which could lead to weirdness. This causes the behavior to remain the same with `'use strict';` commented out, but uncommented causes info icons to appear next to all the function declarations!

Then I sent `[{ unused: false }]`. The behavior is equivalent to the default behavior.

Then I switched to `setOptions` with `[{ unused: true }]`. Now, with `'use strict';` commented out info icons appear next to function declarations _and_ the warning icon appears due to too many errors. Uncommenting and...warning icons everywhere.

Finally, `setOptions` with `[{ unused: false }]`. No icons when `'use strict';` is commented out, but warning icons everywhere when it's uncommented.

I'm not partial to having `unused` either on or off, just that whatever it happens to be set to the JSHint icons function as I'd expect them to, which none of the above combinations satisfy. To clarify, with `unused` true I'd expect the info icons to show until too many errors are displayed. With `unused` false I'd expect no icons to show up. Having looked at the JavaScript worker and parts of [jshint.js](https://github.com/ajaxorg/ace/blob/4a55188fdb0eee9e2d3854f175e67408a1e47655/lib/ace/mode/javascript/jshint.js) I'm baffled by why this wouldn't be the case.

Is there anything I'm doing wrong, or is this indicative of a larger issue with linting?

**Comment by thirdwheel** [comment]
I've noticed this as well - I've got a file in my project where the only error showing is that there are too many errors.
