### ISSUE TITLE
How many types of markers ?

### ISSUE THREAD

**Issue by nitinsurana** [ajaxorg/ace#2961]
Have been surfing internet and going through the docs for more than 40 mins but couldn't figure out how many types of Markers are there.

Can someone please point to the correct location ?

**Comment by nightwing** [comment]
"fullLine" "screenLine"  "text" and "line" which is the default 
see https://github.com/ajaxorg/ace/blob/v1.2.3/lib/ace/layer/marker.js#L79 and https://github.com/ajaxorg/ace/blob/v1.2.3/lib/ace/edit_session.js#L607
