### ISSUE TITLE
Composition gets wrong background color when using setHighlightActiveLine

### ISSUE THREAD

**Issue by vanillajonathan** [ajaxorg/ace#2968]
When using `setHighlightActiveLine` together with input composition (which is handled by the `.ace_text-input.ace_composition` class) the composition gets the background color of the editor instead of the background color of the line highlighted by `setHighlightActiveLine`.

**Comment by nightwing** [comment]
This should be fixed by https://github.com/ajaxorg/ace/pull/3635, please let us know if you still can reproduce this on http://ace.c9.io. Thanks.
