### ISSUE TITLE
Getting "text.match is not a function" when trying to do a setValue

### ISSUE THREAD

**Issue by dyetube** [ajaxorg/ace#2971]
I keep getting a "text.match is not a function" error when I do a `editor.setValue(ReportModel, -1);`  Here's what I'm doing:

`var ReportModel = @Html.Raw(Json.Encode(Model.Report).ToString());`
`editor.setValue(ReportModel, -1);`

Why am I getting this error?

**Comment by Clay-Ferguson** [comment]
try "new String(ReportModel)"

The 'match is not a function' usually means something expected an actual string object.

**Comment by dyetube** [comment]
Had a duh moment:  'var ReportModel = JSON.stringify(@Html.Raw(Json.Encode(Model.Report).ToString()), null, 2);' fixed the issue.

**Comment by JimWang1995** [comment]
var str=/**\n**f/gim; 
  editor.find(str,{
          backwards: false,
          wrap: false,
          caseSensitive: false,
          wholeWord: true,
          regExp: true
         },true);
It' dosen't work,if  str include "\n". 
How to match  **"\nf"** if can't use **"^f"** ?
