### ISSUE TITLE
Bug in JSON syntax highlighting? (Unexpected '')

### ISSUE THREAD

**Issue by Simran-B** [ajaxorg/ace#2975]
If I hover the area of the line number column at the first line, there is a tooltip that indicates a strange syntax error: `Unexpected ''`

![unexpected](https://cloud.githubusercontent.com/assets/7819991/15608383/e6bfc2da-2419-11e6-97c5-c3209f42784f.png)

What could be causing this?

**Comment by danbulant** [comment]
What version & browser are you using?
I was unable to reproduce this bug.

**Comment by Simran-B** [comment]
Too long ago, can't recall what I even used ACE for there. Seems to be fine in Chrome 75 on Windows 10 using ACE build at 7489e42
