### ISSUE TITLE
Code fence just after list in markdown mode doesn't highlight syntax.

### ISSUE THREAD

**Issue by Rokt33r** [ajaxorg/ace#2978]
<img width="333" alt="screen shot 2016-05-31 at 2 42 29 pm" src="https://cloud.githubusercontent.com/assets/5865853/15664356/fd0775f2-273d-11e6-993b-217238723eaa.png">

**Comment by i-need-to-tell-you-something** [comment]
I have a very similar problem with headers (in the Joplin's issue \#1567 referencing this) not getting syntax highlighted if they are preceded by a list (bullet or numeric).
