### ISSUE TITLE
Jade is now Pug

### ISSUE THREAD

**Issue by anowlcalledjosh** [ajaxorg/ace#2979]
https://github.com/pugjs/pug#rename-from-jade

Syntax highlighting is essentially the same.

**Comment by EricBalingit** [comment]
Note that if you are using pug you can `include any.jade` ( with the `.jade` extension explicitly ) while still obtaining the benefit of ace syntax highlighting.  Not the best solution, but better than none.

https://github.com/pugjs/pug/issues/2299#issuecomment-229823555

**Comment by nightwing** [comment]
if you are talking about cloud9, you can manually set the mode for a file with pug extension to jade using statusbar.
After that all pug files will get correct syntax highlighting.

Closing this issue since https://github.com/ajaxorg/ace/pull/3155 have fixed it.
