### ISSUE TITLE
Getting tokens by type - is this possible?

### ISSUE THREAD

**Issue by edoarsla** [ajaxorg/ace#2980]
I'm wondering if it is possible to get all tokens of a particular type.  For example, say I want to get all comments while in Java mode.

I'd love to get an array with each comment.
Obviously I'd like to do this without re-parsing the editor content.

Thank you!

**Comment by nightwing** [comment]
you can use editor.session.getTokens(row).filter(x => /comment/.test(x.type))

**Comment by edoarsla** [comment]
ok, I can work with that.  thank you!
