### ISSUE TITLE
Align close HTML tags in one line with open tag

### ISSUE THREAD

**Issue by alexlukin-softgrad** [ajaxorg/ace#2981]
I've discovered a slight problem with HTML tags alignment. I'm not sure if it is a bug or it could be fixed via editor configuration, but I couldn't make it work as I expect.

This issue could be repeated as follows.
In Ace Editor [kitchen sink](https://ace.c9.io/build/kitchen-sink.html) we set HTML mode and Enable Behaviours checkbox.
Then in body section we input any html in one line, for instance,
`<h2>Example</h2>`
Then we set text cursor to the begining of the text (before 'E' letter) and press Enter to get this

```
<h2>  
Example</h2>
```

Then we set text cursor to the end of text and press Enter. We obtain this

```
<h2>
   Example
   </h2>
```

but I expect `h2` open and close tag to be allign with the similar indent:

```
<h2>
   Example
</h2>
```

I would appreciate for any ideas related to this problem.

**Comment by arsen2010** [comment]
Before you set value into the editor, you can format the code as like the value in textarea,   i also have this problem, search some reformat functions on the internet, finally resovled.
