### ISSUE TITLE
When I use the Chinese input method in IE or Edge brower to enter text in the code mode ,have a problem.

### ISSUE THREAD

**Issue by gemron** [ajaxorg/ace#2982]
Characters that will appear in disorder include both English and Chinese.
Chrome is no this problem.IE and Edge have this problem.
hope you can repair this problem,thanks!
![qq 20160602175244](https://cloud.githubusercontent.com/assets/1953998/15741156/f753501e-28ea-11e6-8648-ed919704d114.png)

**Comment by nightwing** [comment]
This should be fixed by https://github.com/ajaxorg/ace/pull/3635, please let us know if you still can reproduce this on http://ace.c9.io. Thanks.

**Comment by gemron** [comment]
yes,i test the fix.i can't reproduce this problem.thanks your fix.
