### ISSUE TITLE
Eclipse theming is not exactly like original eclipse theming

### ISSUE THREAD

**Issue by ManojkumarV** [ajaxorg/ace#2983]
Eclipse theme in ace editor is not satisfying to the level of original eclipse editor. 
The variable names of the java file is highlighted with blue color in eclipse whereas the same is black color in ace editor. This makes quite difficult to identify the variables. 
Also eclipse italicizes final variables with blue color. The same would make the easier identify final variables in ace editor. 
I believe the java mode for eclipse mode can be altered to achieve the same. Likewise other language modes can be altered appropriately to give the same look like eclipse. 
Right now the basic need is for Java files in eclipse mode.

<img width="1130" alt="original eclipse theme" src="https://cloud.githubusercontent.com/assets/10399151/15745460/848a70da-28ef-11e6-82c2-9ce0ba99b6cb.png">
<img width="1060" alt="ace eclipse theme" src="https://cloud.githubusercontent.com/assets/10399151/15745466/8ac16ad0-28ef-11e6-9bee-022a0b62e5a7.png">

Here is the comparison between original eclipse theme and ace eclipse theme. Any help would be greatly appreciated.

**Comment by vinothwindows47** [comment]
@nightwing is it possible to give exact desktop ide eclipse theme for java language mode ?
