### ISSUE TITLE
How to disable onscreen keyboard showing when set to readOnly

### ISSUE THREAD

**Issue by exclm** [ajaxorg/ace#2984]
When set the editor to readOnly, onscreen keyboard of android / iOS will show up, but it is unnecessary (when using ace as a syntax highlighter).

How to prevent it?

**Comment by exclm** [comment]
well, sample [here](https://github.com/ajaxorg/ace/blob/master/demo/static-highlighter.html) is exactly what I need...

**Comment by nightwing** [comment]
Do you need it to always be readonly? if yes then using static_highlight is indeed better than ace.edit

**Comment by adamjimenez** [comment]
Is this as simple as setting the underlying textarea to readonly? Seems to work for me..
e.g.
`editor.textInput.getElement().setAttribute('readonly', 'readonly');`

**Comment by nightwing** [comment]
this is fixed now
