### ISSUE TITLE
Ace editor under disabled fieldset - Copy is not working

### ISSUE THREAD

**Issue by ajainarayanan** [ajaxorg/ace#2991]
When ace-editor is wrapped under a `<fieldset>` tag and if its disabled the CMD+C doesn't work, as in the Copy command of code inside the editor doesn't seem to work. Steps to reproduce,
1. Add ace-editor to DOM
2. Wrap the ace-editor under a `<fieldset>` tag.
3. Disable `<fieldset>` tag 
4. Try highlighting the code and use CMD + C and try to paste the code anywhere. 

Step - 4 wouldn't work as fieldset is disabled and since its disabled it doesn't pass on the `onFocus` events to the underlying input element. For some reason ace-editor requires `onFocus` event to have copy paste feature. 

[JSFiddle](http://jsfiddle.net/rY37e/144/) showcasing the issue.

PS: I am aware of ace editor having `readOnly` option that makes it non-editable but are there any other way to use it normally under fieldset and to allow copy feature natively?

**Comment by nightwing** [comment]
There is no easy way to make copy work without ace being focused. Ace doesn't create dom nodes for all the text it contains, and needs to handle copy event to put text to the clipboard

**Comment by ajainarayanan** [comment]
@nightwing Agreed, but just that when I have a form that has a lot of input fields, along with ace-editor, text selection and CMD + C works fine on other input elements. So now instead of wrapping all the form elements in one fieldset element and disabling them I have to now handle ace-editor separately. Was wondering if there were any other workarounds in such scenarios.

**Comment by nightwing** [comment]
it should be possible to add click listener to editor which will select a node inside editor with window.getSelection() then add a copy listener to window which will call copy listener of ace.

**Comment by ajainarayanan** [comment]
@nightwing hhhmm sounds a little convoluted to achieve the copy behavior for disabled scenario. Wrapped the form elements in 2 parts. One non-ace editor input elements & the other ace-editor and handling the disabled scenario using the `readOnly` attribute. You can close this issue if need be as that is the workaround I am pursuing.
