### ISSUE TITLE
[website] The website breaks the back navigation

### ISSUE THREAD

**Issue by stof** [ajaxorg/ace#2993]
the https://ace.c9.io/ website hijacks the back button (probably to rely on the history API as a single page app), but this happens even when the previous page in the history was github.com (going there through the link in the github repo description), which breaks the navigation

**Comment by nightwing** [comment]
On which browser do you see the issue? on chrome when i click on the link above, then click back i get back to this page as expected.

**Comment by stof** [comment]
Firefox

**Comment by rocketinventor** [comment]
@stof That sounds like a Firefox bug. The demo seems to be using hashes, not the location api.
Websites should not be able to "hijack" the back button, so it's a Firefox bug, either way.

**Comment by stof** [comment]
@rocketinventor The demo uses http://benalman.com/projects/jquery-bbq-plugin/ which changes the location of the page to store the state.

The issue seems to be related to the fact that accessing https://ace.c9.io/ will trigger an URL change to go to https://ace.c9.io/#nav=about and it will be registered it in the history API. When going back, it goes to ``https://ace.c9.io/`` which navigates again to ``https://ace.c9.io/#nav=about``, forbidding to go back further.

If the new history API was used, the initial URL change from https://ace.c9.io/ to https://ace.c9.io/#nav=about should use ``history.replaceState`` instead of ``history.pushState`` to fix this (so that it is not considered as a new page in the browser history, and so going back would not go back to https://ace.c9.io/ but to the previous page, github in my case). But jQuery BBQ does not have an equivalent for that (because it cannot be done with using the history API).

There is no Firefox bug here. It does its job perfectly when the page asks to change the location. The issue is that https://ace.c9.io/ navigates to a new URL instead of redirecting (which cannot be done client-side with the old APIs only)

**Comment by nightwing** [comment]
fixed in https://github.com/ajaxorg/ace/pull/3266/commits/a51f9097462138330f3efdbc971fc81851dbd37a, thank you for telling us about the issue.
