### ISSUE TITLE
Disable click events with multiple ace editors

### ISSUE THREAD

**Issue by webchaz** [ajaxorg/ace#2995]
We have multiple ace editors on a single page.  One of the editors is hidden by a parent div using css.

When we click on the non-hidden ace editor, the other editor appears in place as it seems that focusing on one editor, effects the styles for all editors.

Is there anyway to disable any click events, so this won't occur or can you suggest a work around?

**Comment by nightwing** [comment]
Could you please create a demo showing the issue? Clicking on one editor normally does not change other editors. see https://ace.c9.io/#nav=about for an example.

**Comment by webchaz** [comment]
It seems to be the ace_focus that's messing it up.  Is there anyway to simply disable any focus events?
