### ISSUE TITLE
Undo/Redo should coalesce edits

### ISSUE THREAD

**Issue by failurite** [ajaxorg/ace#300]
Most IDE's (VS, IntelliJ, NetBeans, Eclipse) combine key typing events together until some other event occurs such as a paste, tab, newline, etc.  

Currently ACE adds an undo event for each character typed or deleted.  It would be good if it did a better job of combining some undo's together.
@gissues:{"order":69.56521739130449,"status":"backlog"}

**Comment by friedmag** [comment]
So... why did this get re-closed?  This seems to still be the case, and has to be one of its most annoying issues as a long-time vim user.

**Comment by nightwing** [comment]
@friedmag this have been fixed long time ago, and there is an option controlling the merging behavior https://github.com/ajaxorg/ace/blob/v1.2.6/lib/ace/editor.js#L2642-L2645.
If it doesn't work the way you expect, please create a new issue with detailed description of what you do and what expect to happen.
