### ISSUE TITLE
[website] several logos are missing on the real world users page

### ISSUE THREAD

**Issue by stof** [ajaxorg/ace#3001]
Requests for these logos are receiving 404 errors: https://ace.c9.io/#nav=production

**Comment by dwelle** [comment]
for me, my avast antivirus says the logo contains a malware. Might be false positive.

![image](https://cloud.githubusercontent.com/assets/5153846/24063161/caec9538-0b5e-11e7-92af-a450c5b613d2.png)

**Comment by nightwing** [comment]
this was fixed some time ago, thanks for the report.

**Comment by stof** [comment]
`Cloud Commander` still triggers a 404
