### ISSUE TITLE
Snippet Manager Multi-line Selection Bug

### ISSUE THREAD

**Issue by knod** [ajaxorg/ace#3010]
**What I did:** Used Snippet Manager to insert text with a multi-line pre-selection, a bit like this:
```js
var insertMulti = document.querySelector('#insert_multi_line');
var multiStr = "<div>\n\t${1:Not everything that should be selected\n\tis selected}\n</div>";

insertMulti.addEventListener( 'click', function (evnt) {
    ace.config.loadModule('ace/ext/language_tools', function () {
        editor.insertSnippet( multiStr );
    }); 
});
```
**What happened:** The `${1:}` notations surrounded multi-line text, but only the first line ('Not everything that should be selected') of the multi-line selection was selected.

Here is a live example with two scenarios - a single line pre-selection and a multi-line pre-selection (click the buttons to see the text inserted): https://jsfiddle.net/ka7byd8z/3/
Here is a stackoverflow question with a more detailed explanation: http://stackoverflow.com/questions/38056123/selecting-multiple-lines-with-the-snippet-manager

Is this expected and desired behavior or is this a bug?

**Comment by nightwing** [comment]
https://github.com/ajaxorg/ace/pull/3011 will fix this, thank you for reporting!
