### ISSUE TITLE
Regex based syntax highlighting

### ISSUE THREAD

**Issue by dekhaus** [ajaxorg/ace#3016]
Hi All

  Is it possible to highlight text in the Ace editor that matches a regex ?  For example imagine there's a text field above the editor into which a user can enter a regex.   In realtime - while the user is constructing the regex - the contents of the Ace editor are searched for matches and if any found they're highlighted.  

  Also - in addition to the above, is it possible to retrieve a list of the lines that match the regex that a user is typing (in the scenario described above).

Thanks
Dave

**Comment by nightwing** [comment]
This sound very much like the search feature.
But if you need to use syntax highlighting for some reason, it is possible to recreate the tokenizer similar to what https://github.com/ajaxorg/ace/blob/v1.2.3/tool/mode_creator.js#L233 does
