### ISSUE TITLE
 Wrong behavior when using Spanish input(Mac OS X)

### ISSUE THREAD

**Issue by Rokt33r** [ajaxorg/ace#3022]
A char like `á` can be typed holding `a` key and press `2` key(or click the char from popup) on OSX.

It's behavior is like below
1. pressing and holding `a` =>  `a` is typed.
2. press `2` => `a` is replaced with `á`.

But, in Ace editor, this method populates `aá`. It doesn't seem to replace `a` character.

**Comment by nightwing** [comment]
This should be fixed by https://github.com/ajaxorg/ace/pull/3635, please let us know if you still can reproduce this on http://ace.c9.io. Thanks.
