### ISSUE TITLE
Idle Fingers theme: shouldn't .ace_storage be colored like .ace_keyword?

### ISSUE THREAD

**Issue by iweindesmedt** [ajaxorg/ace#3023]
Chrome theme:
![1](https://cloud.githubusercontent.com/assets/812033/16623309/b14a0806-439d-11e6-8159-95bfa79059bd.png)

Idle Fingers theme:
![2](https://cloud.githubusercontent.com/assets/812033/16623320/b9499f12-439d-11e6-959a-b328afd8cccb.png)

Shouldn't the Idle Fingers theme's ```function``` and ```var``` (both ```.ace_storage```) be colored like ```for``` (```.ace_keyword```) as in the Chrome theme?

**Comment by nightwing** [comment]
It should follow the original textmate theme. Is storage colored same as keyword in textmate/sublime?

**Comment by iweindesmedt** [comment]
you're right, it is indeed the correct highlighting, i must have compared with an altered version of Idle Fingers
http://inkdeep.github.io/TextMate-Themes/#idlefingers
