### ISSUE TITLE
Chinese input fail to work on the latest Chrome version 53

### ISSUE THREAD

**Issue by ghosert** [ajaxorg/ace#3027]
The input method is this one http://pinyin.sogou.com/, it's very famous in China. After switching to chinese input and input "nihao" for "你好"，both "nihao" and "你好" will be added into ace editor while the users need "你好" only.

This issue is introduced after upgrading chrome to version 53, it works as expected before version 53.

**Comment by ghosert** [comment]
The behavior of the issue is same to this one https://github.com/ajaxorg/ace/issues/1386, Happens on Windows 7, Chrome 53 and sogou input method, it seems working before, not sure why it's reproduced on the latest Chrome 53.

**Comment by xieranmaya** [comment]
Windows 10 has the same bug, Chrome 53 & any Chinese IME.

**Comment by mengxb** [comment]
I met this issue also, can this issue be solved soon? thank.

**Comment by mrdream24** [comment]
@ghosert 你是怎么解决这个bug的？求助！！

**Comment by valaxy** [comment]
same error in win7 chrome53

**Comment by valaxy** [comment]
@mrdream24 @mengxb there is a temporarily fix, please check https://github.com/ajaxorg/ace/issues/3097
