### ISSUE TITLE
Question concerning progressively loading content to avoid loading entire file into memory implementation

### ISSUE THREAD

**Issue by dekhaus** [ajaxorg/ace#3028]
Hi All

I've succeeded in implementing the changes necessary to support progressively loading pages of data into the ACE editor from a backend.  That's the good news.

My page loading scheme is based on a simple algorithm.  There are three pages.  The 'current' / 'previous' / 'next' pages.   The Pages are stored in an Array of length 3.

An example will best illustrate my algorithm ...
- User clicks on a file list in a browser window.  Modal is launched containing ACE editor.  Because file can be huge - I load content in 100 line pages.  ACE editor is rendered with the first 100 lines entered (first Page is retrieved from backend service) [NOTE Pages array looks like this [Page0, null, null]
- User scrolls down to line 100 - which triggers page fault.  I determine that Page 1 is needed and that there's room in the Pages array.  I retrieve Page 1 and load into into Pages Array (which now looks like this [Page0, Page1, null].  ACE contents are generated by concatenating Page0+Page1.  Last line in ACE editor is line 100.  Next to last line is 101, and so on.  Editor starts at line 1 and goes up from there.  All is good.  
- User scrolls down to line 200 - which triggers page fault.  I determine that Page 2 is needed and that there's room in the Pages array.  I retrieve Page 2 and load into into Pages Array (which now looks like this [Page0, Page1, Page2].  ACE contents are generated by concatenating Page0+Page1+Page2.  Last line in ACE editor is line 200.  Next to last line is 201, and so on.  Editor starts at line 1 and goes up from there.  All is good.  
- User scrolls down to line 300 - which triggers page fault.  I determine that Page 3 is needed and that there is NO room in the Pages array.  I shift Page1 & Page2 so that Page1 now occupies Pages array position 0 and Page2 now occupies Pages array position 1.  That leaves Pages array position 2 for Page3.  I retrieve Page 3 and load into into Pages Array (which now looks like this [Page1, Page2, Page3]. ACE contents are generated by concatenating Page1+Page2+Page3.  Editor now needs to start at line 100 and go up from there.  In order to accomplish this I call ...

$scope.editor.setOption("firstLineNumber", ... ) - I calculate that the value I need to pass in is 100.   This works great.  What does not work is that the last line in the editor should be 300 - but instead of 300 its 'jumped' to 350-ish.   All the proper lines are there and the content is correct.

I tried setting the last visible row to 300 by calling ...

var lastVisibleRow = editor.getLastVisibleRow() ;
editor.gotoLine(lastVisibleRow, 1, true);

If anyone can provide some insight into what I should be doing to get this to work correctly.  I'd really appreciate it.  

Thanks
Dave

**Comment by nightwing** [comment]
if you could create a working demo of your code, it would be easier to help you.

**Comment by dekhaus** [comment]
Fair enough - I'll post a JSFiddle link asap

**Comment by rocketinventor** [comment]
@dekhaus I'd also be interested in seeing a demo of this.
