### ISSUE TITLE
'of' keyword is not highlighted in TypeScript/ES6

### ISSUE THREAD

**Issue by thomasdenney** [ajaxorg/ace#3035]
TypeScript and ES6 support the following style of iteration, however ACE doesn't highlight the keyword `of`:

```typescript
let xs = [1, 2, 3]
for (let x of xs) {
  console.log(x)
}
```

**Comment by Noctisdark** [comment]
Any thoughts on this one ?
Take a look at this [line](https://github.com/ajaxorg/ace/blob/master/lib/ace/mode/javascript_highlight_rules.js#L56), the current Javascript mode highlights even ES7 keywords like `await`, `async`, `interface` etc... that may or may not be there in the future. I think there is no reason to ignore the `of` keyword.
