### ISSUE TITLE
Adding a new textDirection attribute to the Ace editor

### ISSUE THREAD

**Issue by wajnberg** [ajaxorg/ace#3041]
We need to add a new textDirection attribute to the Ace editor. its values can be "auto", "ltr" or "rtl"

I attach here the very simple changes I did to achieve this (Unfortunately I am not allowed to push my changes)

[Changes.zip](https://github.com/ajaxorg/ace/files/388726/Changes.zip)

**Comment by wajnberg** [comment]
I eventually succeeded in creating a pull request: https://github.com/ajaxorg/ace/pull/3042

Thank you for your review

**Comment by tomerm** [comment]
**Background**

Languages with bidirectional scripts (i.e. Arabic, Hebrew, Farsi, Urdu etc.) are running from right to left, while languages with Latin script (i.e. English) are running from left-to-right. In general text should be displayed with natural to it direction. LTR for English, German etc. and RTL for Arabic, Hebrew, Urdu etc. . If text is not displayed with natural text direction it may become incomprehensible. 
While overall responsibility for laying out text on the screen is in the hands of UBA (Unicode Bidi Algorithm) there are higher level protocols (i.e. HTML) which can instruct UBA in which direction text should be displayed. 

**Bidi text and ACE**

ACE is used for displaying plain text file content. In such use case, it acts very much similar to Notepad or multiline editable input field in web browser. 

**Requirements**

1.  For addressing plain text display used case, ACE should allow specification of default text direction inside content via external parameter (i.e. textDirection). Possible values go along HTML5 valid values of dir attribute (ltr, rtl, auto).

2. Allow interactive change of direction for selected list of rows (each row constitutes in ACE a separate paragraph) using keyboard. Change of text direction on a paragraph level is a very standard option supported by major browsers (i.e. IE = Ctrl - Left/Right-Shift; FF = Ctrl-Shift-X).

**Suggested implementation approach**

The implementation on the high level will use dir (or similar css property - direction) to convey direction information on the paragraph level.

**Comment by mkslanc** [comment]
Fixed by #3658
