### ISSUE TITLE
non-ascii characters = death

### ISSUE THREAD

**Issue by 12Me21** [ajaxorg/ace#3044]
When using some non-ascii characters (such as 𝓐𝓑𝓒), the cursor position is incorrect, and tons of errors are detected.

**Comment by Noctisdark** [comment]
I think this happens because ace only supports `monospace` ( all characters take up the same width or fixed-width characters ). I bet you will find [this](http://stackoverflow.com/questions/1938639/monospace-unicode-font) interesting.
