### ISSUE TITLE
"shrinkwrap" build option not available

### ISSUE THREAD

**Issue by mlajtos** [ajaxorg/ace#3051]
In makefile, there is a mention of "shrinkwrap" option that should concat all files into one. However, it is not working. Option is parsed, but not used later in build process. Will "shrinkwrap" option be usable or not?

Or is there any way to distribute Ace in one file?

**Comment by nightwing** [comment]
no, adding all modes and themes to one file results into a huge package, and doesn't work for syntax checkers which need to be loaded into  a web worker.
But if you need only a few modes, you can concatened ace.js with some other tool

**Comment by mlajtos** [comment]
Yes, it would be huge. :)

Thank you.
