### ISSUE TITLE
A ime problem in chromebook

### ISSUE THREAD

**Issue by aliezc** [ajaxorg/ace#3053]
A IME input bug in chromebook

if i will input "ni hao" as "你好"

it become "ni hao 你好 "

**Comment by chzju** [comment]
the same problem

reproduced in: chrome 53.0.2785.116

**Comment by nightwing** [comment]
This should be fixed by https://github.com/ajaxorg/ace/pull/3635, please let us know if you still can reproduce this on http://ace.c9.io. Thanks.
