### ISSUE TITLE
Autocompletion not working in 1.2.4

### ISSUE THREAD

**Issue by jcbvm** [ajaxorg/ace#3054]
I have an issue with 1.2.4, where it seems that autocompletion is no longer working.
I'm getting 'misspelled option "enableLiveAutocompletion"' warning in my console.

Both `ext-language_tools.js` and `mode-xml.js` are loaded.
I'm setting up ace by embedding it in DOM with `ace.edit(...)` and setting options:

    editor.setOptions({
          mode: 'ace/mode/xml',
          enableLiveAutocompletion: true
    });

In 1.2.3 this was working. Is there any change made in 1.2.4 which might affect this or causing this issue, because I'm somehow clueless.

NOTE: I'm using ace-builds (src-noconflict), maybe it's more related to that

**Comment by nightwing** [comment]
there was a regression in noconflict when there was a global define https://github.com/ajaxorg/ace/pull/3055/commits/c6453e0db7019734c50e2f770b6e0b43e3e162b5 should fix this.

**Comment by jcbvm** [comment]
Thanks :+1:
