### ISSUE TITLE
Editor doesn’t resize itself when its container changes size

### ISSUE THREAD

**Issue by arshtepe** [ajaxorg/ace#3058]
I put the editor container inside a flex container and when the size of its container changes the editor doesn’t comply. The effect is that I do have the vertical scrollbar on it but I can’t move it all the way to the bottom. I had to work around it by calling the “resize” method when the flex container resizes. Is this going to be mended in the future.

**Comment by nightwing** [comment]
When size of a dom node changes browsers do not send any event, so ace cannot detect the change.
There is a hacky way to detect change using several dom nodes and overflow events, but it is inefficient and doesn't work on all browsers.
So unless browsers add resize event for dom nodes, calling resize method  will be required.
