### ISSUE TITLE
Autocomplete mechanism – unwanted text parts get bolded

### ISSUE THREAD

**Issue by arshtepe** [ajaxorg/ace#3059]
I noticed some strange behavior of the autocomplete mechanism. The prompts narrowed by the text entered are sometimes bolded in some unwanted parts. As you can see by the screenshot attached, the actually entered text is “Testowa końcówka”. The prompt I received matches the input text but the bolded parts don’t match it. I mean what’s bolded is the text as entered but also an additional word “chwilę” gets bolded. Can you tell me why this is? Can it be changed in any way? I tried to examine the algorithm responsible for bolding the sentence parts but to no avail. 
![screenshot-1](https://cloud.githubusercontent.com/assets/1872336/17775638/744121e6-6559-11e6-9f19-fe64b877905b.png)

**Comment by arshtepe** [comment]
Can help somebody with this question?

**Comment by nightwing** [comment]
see https://github.com/ajaxorg/ace/pull/2996.
Currently autocompleter doesn't support strings longer than 32 characters.

**Comment by arshtepe** [comment]
@nightwing Are you will fix this?

**Comment by arshtepe** [comment]
@nightwing  Do you plan to increase this value in the future?

**Comment by arshtepe** [comment]
up
