### ISSUE TITLE
Bracket-matching outlines get stuck

### ISSUE THREAD

**Issue by ratiotile** [ajaxorg/ace#3066]
The rectangle outlines around matching brackets never go away. In fact they continue to stack up until code is unreadable. When they get stuck in this manner, the outlines don't move with the text if new lines are added.

![bracket matching stuck](https://cloud.githubusercontent.com/assets/7064626/17908602/3065801c-694f-11e6-9882-4d150a3015e6.PNG)

I wrote a tabbed editor using Ace where the tabs switch out EditSessions. This behavior occurs only after the editor tab is switched out, then back in.

**Comment by nightwing** [comment]
Do you see this on ace.c9.io? if no could you please show a page where it does.

**Comment by ratiotile** [comment]
I'm asking if anyone has seen this problem before. Is there a method I could call to reset the editor state when swapping sessions? 

I'm working on a repro, but it could take several days.

**Comment by nightwing** [comment]
Try setting breakpoint at https://github.com/ajaxorg/ace/blob/v1.2.5/lib/ace/editor.js#L505-L531.
Are you setting same session on two editors at once?

**Comment by ratiotile** [comment]
The tabs all control a single editor by swapping sessions. 

`this.session.removeMarker(this.session.$bracketHighlight);` is hit when the markers should be removed, but they are still visible afterwards. 

`this.session.$bracketHighlight` is initially a number eg. 19, then is null after removeMarker. However, the next time it is hit, the number is incremented by 2, eg. 21.

**Comment by nightwing** [comment]
swapping sessions is better. if you are destroying editor and need to keep the session call `editor.setSession(null)` and `editor.destroy()`

**Comment by ratiotile** [comment]
That worked, thanks!
