### ISSUE TITLE
Separating insert and replace operations in undoManager not working

### ISSUE THREAD

**Issue by dwelle** [ajaxorg/ace#3068]
Suppose I want to execute two operations, 1. insert 2. replace that inserted text with some text, and keep the undo history separate so that user can undo the replace to arrive at the originally inserted text.

I'm doing the following:

```
editor.startOperation({ command : "opOne" });
editor.insert( text );
editor.endOperation();

editor.startOperation({ command : "opTwo" });
editor.session.replace( range, otherText );
editor.endOperation();
```

but the two operations are acting as one in the undo history.

Is the API supposed to work like that?

Ace `1.2.3`

**Comment by nightwing** [comment]
`endOperation` doesn't work like that, Use `editor.session.markUndoGroup()` 

```
editor.session.markUndoGroup() // start new group
editor.insert('text');
editor.session.markUndoGroup() // start another group
editor.insert('otherText');
```
