### ISSUE TITLE
Autocomplete incorrect match highlighting when displaying caption

### ISSUE THREAD

**Issue by shds86** [ajaxorg/ace#3069]
I have some problem with autocomplite popup. In our suggestions we have length more than 32 symbols. But the Bitwise Left shift, https://github.com/ajaxorg/ace/blob/4a55188fdb0eee9e2d3854f175e67408a1e47655/lib/ace/autocomplete/popup.js#L188, is limited:
-  `1 << 30` has result `1073741824`
-  `1 << 31` has result `-2147483648`

because bitwise operators treat their operands as a sequence of 32 bits, 
therefore in next iterations we will have correct expression "data.matchMask & (1 << i)"

**Comment by austingreco** [comment]
See this PR: https://github.com/ajaxorg/ace/pull/2996
