### ISSUE TITLE
Converting tmTheme Error

### ISSUE THREAD

**Issue by narraressan** [ajaxorg/ace#3073]
I followed the the reference 
https://github.com/ajaxorg/ace/wiki/Importing-.tmtheme-and-.tmlanguage-Files-into-Ace
to upload a new tmTheme but running the last step in the cmd fails with error 

TypeError: parseString is not a function

I tried installing plist but it didn't work. Iam currently lost as to how to solve this problem. Please help me.

**Comment by nightwing** [comment]
Did `npm install` in tools folder work? What is the output of `npm list` and which version of node did you use?

**Comment by narraressan** [comment]
i guess npm install worked and here is the result of npm list

├─┬ browser-pack@5.0.1
│ ├─┬ combine-source-map@0.6.1
│ │ ├── convert-source-map@1.1.3
│ │ ├── inline-source-map@0.5.0
│ │ ├── lodash.memoize@3.0.4
│ │ └─┬ source-map@0.4.4
│ │   └── amdefine@1.0.0
│ ├── defined@1.0.0
│ ├─┬ JSONStream@1.1.4
│ │ ├── jsonparse@1.2.0
│ │ └── through@2.3.8
│ ├─┬ through2@1.1.1
│ │ ├─┬ readable-stream@1.1.14
│ │ │ ├── core-util-is@1.0.2
│ │ │ ├── inherits@2.0.1
│ │ │ ├── isarray@0.0.1
│ │ │ └── string_decoder@0.10.31
│ │ └── xtend@4.0.1
│ └── umd@3.0.1
├─┬ browserify@10.2.6
│ ├── assert@1.3.0
│ ├── browser-resolve@1.11.2
│ ├─┬ browserify-zlib@0.1.4
│ │ └── pako@0.2.9
│ ├─┬ buffer@3.6.0
│ │ ├── base64-js@0.0.8
│ │ ├── ieee754@1.1.6
│ │ └── isarray@1.0.0
│ ├── builtins@0.0.7
│ ├── commondir@0.0.1
│ ├─┬ concat-stream@1.4.10
│ │ └── typedarray@0.0.6
│ ├─┬ console-browserify@1.1.0
│ │ └── date-now@0.1.4
│ ├── constants-browserify@0.0.1
│ ├─┬ crypto-browserify@3.11.0
│ │ ├─┬ browserify-cipher@1.0.0
│ │ │ ├─┬ browserify-aes@1.0.6
│ │ │ │ ├── buffer-xor@1.0.3
│ │ │ │ └── cipher-base@1.0.2
│ │ │ ├─┬ browserify-des@1.0.0
│ │ │ │ ├── cipher-base@1.0.2
│ │ │ │ └─┬ des.js@1.0.0
│ │ │ │   └── minimalistic-assert@1.0.0
│ │ │ └── evp_bytestokey@1.0.0
│ │ ├─┬ browserify-sign@4.0.0
│ │ │ ├── bn.js@4.11.6
│ │ │ ├── browserify-rsa@4.0.1
│ │ │ ├─┬ elliptic@6.3.1
│ │ │ │ ├── brorand@1.0.5
│ │ │ │ └── hash.js@1.0.3
│ │ │ └─┬ parse-asn1@5.0.0
│ │ │   ├─┬ asn1.js@4.8.0
│ │ │   │ └── minimalistic-assert@1.0.0
│ │ │   ├─┬ browserify-aes@1.0.6
│ │ │   │ ├── buffer-xor@1.0.3
│ │ │   │ └── cipher-base@1.0.2
│ │ │   └── evp_bytestokey@1.0.0
│ │ ├─┬ create-ecdh@4.0.0
│ │ │ ├── bn.js@4.11.6
│ │ │ └─┬ elliptic@6.3.1
│ │ │   ├── brorand@1.0.5
│ │ │   └── hash.js@1.0.3
│ │ ├─┬ create-hash@1.1.2
│ │ │ ├── cipher-base@1.0.2
│ │ │ ├── ripemd160@1.0.1
│ │ │ └── sha.js@2.4.5
│ │ ├── create-hmac@1.1.4
│ │ ├─┬ diffie-hellman@5.0.2
│ │ │ ├── bn.js@4.11.6
│ │ │ └─┬ miller-rabin@4.0.0
│ │ │   └── brorand@1.0.5
│ │ ├── pbkdf2@3.0.4
│ │ ├─┬ public-encrypt@4.0.0
│ │ │ ├── bn.js@4.11.6
│ │ │ ├── browserify-rsa@4.0.1
│ │ │ └─┬ parse-asn1@5.0.0
│ │ │   ├─┬ asn1.js@4.8.0
│ │ │   │ └── minimalistic-assert@1.0.0
│ │ │   ├─┬ browserify-aes@1.0.6
│ │ │   │ ├── buffer-xor@1.0.3
│ │ │   │ └── cipher-base@1.0.2
│ │ │   └── evp_bytestokey@1.0.0
│ │ └── randombytes@2.0.3
│ ├── defined@1.0.0
│ ├── domain-browser@1.1.7
│ ├── duplexer2@0.0.2
│ ├── events@1.0.2
│ ├─┬ glob@4.5.3
│ │ ├─┬ inflight@1.0.5
│ │ │ └── wrappy@1.0.2
│ │ ├─┬ minimatch@2.0.10
│ │ │ └─┬ brace-expansion@1.1.6
│ │ │   ├── balanced-match@0.4.2
│ │ │   └── concat-map@0.0.1
│ │ └─┬ once@1.3.3
│ │   └── wrappy@1.0.2
│ ├─┬ has@1.0.1
│ │ └── function-bind@1.1.0
│ ├── htmlescape@1.1.1
│ ├─┬ http-browserify@1.7.0
│ │ └── Base64@0.2.1
│ ├── https-browserify@0.0.1
│ ├── inherits@2.0.1
│ ├─┬ insert-module-globals@6.6.3
│ │ ├─┬ combine-source-map@0.6.1
│ │ │ ├── convert-source-map@1.1.3
│ │ │ ├── inline-source-map@0.5.0
│ │ │ ├── lodash.memoize@3.0.4
│ │ │ └─┬ source-map@0.4.4
│ │ │   └── amdefine@1.0.0
│ │ ├── is-buffer@1.1.4
│ │ └─┬ lexical-scope@1.2.0
│ │   └─┬ astw@2.0.0
│ │     └── acorn@1.2.2
│ ├── isarray@0.0.1
│ ├─┬ JSONStream@1.1.4
│ │ ├── jsonparse@1.2.0
│ │ └── through@2.3.8
│ ├─┬ labeled-stream-splicer@1.0.2
│ │ └─┬ stream-splicer@1.3.2
│ │   ├── indexof@0.0.1
│ │   └── readable-wrap@1.0.0
│ ├─┬ module-deps@3.9.1
│ │ ├─┬ detective@4.3.1
│ │ │ └── acorn@1.2.2
│ │ └─┬ stream-combiner2@1.0.2
│ │   └─┬ through2@0.5.1
│ │     ├─┬ readable-stream@1.0.34
│ │     │ └── core-util-is@1.0.2
│ │     └── xtend@3.0.0
│ ├── os-browserify@0.1.2
│ ├─┬ parents@1.0.1
│ │ └── path-platform@0.11.15
│ ├── path-browserify@0.0.0
│ ├── process@0.11.8
│ ├── punycode@1.4.1
│ ├── querystring-es3@0.2.1
│ ├─┬ read-only-stream@1.1.1
│ │ └── readable-wrap@1.0.0
│ ├─┬ readable-stream@1.1.14
│ │ └── core-util-is@1.0.2
│ ├── resolve@1.1.7
│ ├─┬ shasum@1.0.2
│ │ ├─┬ json-stable-stringify@0.0.1
│ │ │ └── jsonify@0.0.0
│ │ └── sha.js@2.4.5
│ ├── shell-quote@0.0.1
│ ├── stream-browserify@1.0.0
│ ├── string_decoder@0.10.31
│ ├─┬ subarg@1.0.0
│ │ └── minimist@1.2.0
│ ├─┬ syntax-error@1.1.6
│ │ └── acorn@2.7.0
│ ├── through2@1.1.1
│ ├── timers-browserify@1.4.2
│ ├── tty-browserify@0.0.0
│ ├─┬ url@0.10.3
│ │ ├── punycode@1.3.2
│ │ └── querystring@0.2.0
│ ├── util@0.10.3
│ ├─┬ vm-browserify@0.0.4
│ │ └── indexof@0.0.1
│ └── xtend@4.0.1
├─┬ cson@3.0.2
│ ├── coffee-script@1.10.0
│ ├── cson-parser@1.3.3
│ ├─┬ extract-opts@3.3.1
│ │ ├── eachr@3.2.0
│ │ ├── editions@1.1.2
│ │ └── typechecker@4.3.0
│ ├─┬ requirefresh@2.1.0
│ │ └── editions@1.1.2
│ └─┬ safefs@4.1.0
│   ├── editions@1.1.2
│   └── graceful-fs@4.1.6
├── css-parse@1.0.3
├── css-stringify@1.0.3
├─┬ deps-sort@1.3.9
│ ├─┬ JSONStream@1.1.4
│ │ ├── jsonparse@1.2.0
│ │ └── through@2.3.8
│ ├─┬ shasum@1.0.2
│ │ ├─┬ json-stable-stringify@0.0.1
│ │ │ └── jsonify@0.0.0
│ │ └─┬ sha.js@2.4.5
│ │   └── inherits@2.0.1
│ ├─┬ subarg@1.0.0
│ │ └── minimist@1.2.0
│ └─┬ through2@1.1.1
│   ├─┬ readable-stream@1.1.14
│   │ ├── core-util-is@1.0.2
│   │ ├── inherits@2.0.1
│   │ ├── isarray@0.0.1
│   │ └── string_decoder@0.10.31
│   └── xtend@4.0.1
├─┬ derequire@2.0.3
│ ├── acorn@0.12.0
│ ├─┬ concat-stream@1.5.1
│ │ ├── inherits@2.0.1
│ │ ├─┬ readable-stream@2.0.6
│ │ │ ├── core-util-is@1.0.2
│ │ │ ├── isarray@1.0.0
│ │ │ ├── process-nextick-args@1.0.7
│ │ │ ├── string_decoder@0.10.31
│ │ │ └── util-deprecate@1.0.2
│ │ └── typedarray@0.0.6
│ ├─┬ escope@2.0.7
│ │ ├─┬ es6-map@0.1.4
│ │ │ ├── d@0.1.1
│ │ │ ├── es5-ext@0.10.12
│ │ │ ├── es6-iterator@2.0.0
│ │ │ ├── es6-set@0.1.4
│ │ │ ├── es6-symbol@3.1.0
│ │ │ └── event-emitter@0.3.4
│ │ ├─┬ es6-weak-map@0.1.4
│ │ │ ├── d@0.1.1
│ │ │ ├─┬ es5-ext@0.10.12
│ │ │ │ ├── es6-iterator@2.0.0
│ │ │ │ └── es6-symbol@3.1.0
│ │ │ ├── es6-iterator@0.1.3
│ │ │ └── es6-symbol@2.0.1
│ │ ├── esrecurse@1.2.0
│ │ ├── estraverse@1.9.3
│ │ └── util-extend@1.0.3
│ ├─┬ through2@2.0.1
│ │ ├─┬ readable-stream@2.0.6
│ │ │ ├── core-util-is@1.0.2
│ │ │ ├── inherits@2.0.1
│ │ │ ├── isarray@1.0.0
│ │ │ ├── process-nextick-args@1.0.7
│ │ │ ├── string_decoder@0.10.31
│ │ │ └── util-deprecate@1.0.2
│ │ └── xtend@4.0.1
│ └─┬ yargs@3.32.0
│   ├── camelcase@2.1.1
│   ├─┬ cliui@3.2.0
│   │ ├─┬ strip-ansi@3.0.1
│   │ │ └── ansi-regex@2.0.0
│   │ └── wrap-ansi@2.0.0
│   ├── decamelize@1.2.0
│   ├─┬ os-locale@1.4.0
│   │ └─┬ lcid@1.0.0
│   │   └── invert-kv@1.0.0
│   ├─┬ string-width@1.0.2
│   │ ├─┬ code-point-at@1.0.0
│   │ │ └── number-is-nan@1.0.0
│   │ ├─┬ is-fullwidth-code-point@1.0.0
│   │ │ └── number-is-nan@1.0.0
│   │ └─┬ strip-ansi@3.0.1
│   │   └── ansi-regex@2.0.0
│   ├── window-size@0.1.4
│   └── y18n@3.2.1
└─┬ plist@2.0.1
  ├── base64-js@1.1.2
  ├── xmlbuilder@8.2.2
  └── xmldom@0.1.22

**Comment by nightwing** [comment]
are you using latest version from master branch?
plist should be @1.1.0 https://github.com/ajaxorg/ace/blob/master/tool/package.json#L12

**Comment by narraressan** [comment]
wow! ... Thanks sir. it was the versions of my installed dependencies, my bad. Thank you for your help. ^_^

i got it working by following the entire dependencies in the link's package.json
