### ISSUE TITLE
Disable specific line

### ISSUE THREAD

**Issue by oknoorap** [ajaxorg/ace#3080]
I have editor with value like this

``` php
<?php
function myFn () {
// Editable line here
// And here
// And here... so on...
}
```

I want to disable line editing on 1st, 2nd, and last line. I've been using codemirror before, and right now I moved to ace, but I can't find how to do that. Can anyone give me solutions?

**Comment by nightwing** [comment]
It is possible to add listener for command events and stop the event if cursor is in a readonly range, something like https://github.com/c9/c9.ide.ace.repl/blob/master/repl.js#L275, but it's a bit awkward to do.
How did you do this in codemirror?

**Comment by oknoorap** [comment]
something like this

```javascript
// the line numbers to be "readonly"
var readOnlyLines = [0,1,2,3];

// create the CodeMirror instance
var editor = CodeMirror.fromTextArea(document.getElementById('input'));

// listen for the beforeChange event, test the changed line number, and cancel
editor.on('beforeChange',function(cm,change) {
    if ( ~readOnlyLines.indexOf(change.from.line) ) {
        change.cancel();
    }
});
```

**Comment by oknoorap** [comment]
okay I've found solution here
(http://www.bootply.com/V8d74PJXqd)[http://www.bootply.com/V8d74PJXqd]

can you help me little bit, how to prevent backspace after read-only line?
