### ISSUE TITLE
Render in Electron is blurry compared to browser

### ISSUE THREAD

**Issue by narraressan** [ajaxorg/ace#3081]
![compare](https://cloud.githubusercontent.com/assets/16384976/18162775/a9747e56-6fec-11e6-9383-eba51e112884.PNG)

The left image shows the ace.editor() run in kitchen-sink in chrome, and the image on the right is ace editor in electron. I am using theme tomorrow night 80.

Notice that the render and colors on the right is blurry and texts look a little heavier. Anybody has an idea what to do with this?....

**Comment by nightwing** [comment]
This may be caused by some of css in your project, when i open kitchen-sink.html in electron, it looks same as in chrome.

**Comment by Noctisdark** [comment]
I think this is an electron-related problem [Link](https://github.com/electron/electron/issues/3349).

Try adding these couple of lines, this might help you. not sure though.
```css
-webkit-font-smoothing: subpixel-antialiased;
text-rendering:optimizeSpeed;
 ```

**Comment by narraressan** [comment]
I had to enhance my css to a more brittle color anyways I used 
-webkit-font-smoothing: subpixel-antialiased;
text-rendering:optimizeSpeed;

as addition. Thanks.
