### ISSUE TITLE
Overtype in blockwise visual mode triggers cursor hop [vim bindings]

### ISSUE THREAD

**Issue by brentyi** [ajaxorg/ace#3088]
1) Select multiple lines (ie `gg<C-v>jjjj`)
2) `R` for overtype mode
![e16b - online latex editor sharelatex20160904070102](https://cloud.githubusercontent.com/assets/6992947/18231385/88ab21d8-726d-11e6-893b-76bd7720ebad.gif)

**Comment by nightwing** [comment]
What is the expected behavior? vim seems to delete all selected lines when pressing R or r in visual mode

**Comment by brentyi** [comment]
@nightwing that's the expected/documented behavior for `R` in visual moide. (though `r` should do a multiline character replacement, not sure why that's not working for you)

It's low priority and far from a commonly used key binding, though -- I think either emulating the vim behavior or going into a multiline overtype (as Ace does right now, but without the cursor hop) would both make sense.
