### ISSUE TITLE
Some commas causing Haskell code to highlight poorly

### ISSUE THREAD

**Issue by amalloy** [ajaxorg/ace#3094]
Sometime recently, Haskell code has started to get weird highlighting on GitHub - my understanding is that GitHub uses Ace for highlighting, hence this issue, but my apologies if I'm wrong. See https://github.com/haskell/containers/pull/339/files#diff-21b9457b6d34bafa3f8599b4b33534e5L75 for example: this code is perfectly fine, but highlighted as invalid. Seems like it has something to do with commas, but it's not totally clear.

The only at-all-recent change to the Haskell highlighting code I could find was https://github.com/ajaxorg/ace/commit/4fbe50a68052e50810ac6e665958f1fc54e3b8f0?w=1 - it doesn't seem to do much, and I don't understand enough context to know what it's doing wrong, I'm afraid.

On the other hand, I tried cloning and running Ace locally, and the Haskell source file I linked to above appears to render fine, so maybe I am totally barking up the wrong tree here.

Tagging @treeowl who said he was interested in following this issue.

**Comment by nightwing** [comment]
Ace is used on github only when editing files.
For highlighting in static views, github uses something else which appears to not be open source yet https://github.com/github/linguist/issues/1984#issuecomment-211122491
