### ISSUE TITLE
How to compile and execute the code?

### ISSUE THREAD

**Issue by suriyaJaay** [ajaxorg/ace#3095]
Could you pls update it with or explain how to compile and execute the codes like some other online editors like codechef, ideone etc.?

am creating my own inbrowser editor using angularJs and NodeJs, as usual complete the front part that displays simple editor using ACE and CODEMIRROR, but struggle to get the compiled out especially for PYTHON and R PROGRAMMING.

Kindly explain,
How to change mode to PYHTON and R PROGRAMMING?
how to setup those in AngularJS and NodeJS.

Helps appreciated those who up their heads.
Looking forward

thank you guys

**Comment by Noctisdark** [comment]
Ace and CodeMirror ? Those are two different editor components. Why would you use them together ?

To change the mode in Ace, you simply do `editor.session.setMode('ace/mode/' + your_mode);`.
In CodeMirror, you `editor.setOption('mode', your_mode);`.

How is compilation related to this ? if you want to compile a python, you'll have to use your command-line. Hopefully NodeJS provides a crossplatform way to do this.

```javascript
let exec = require('child_process').exec;
exec('python ' + filename);
```
.
You will need to provide filename as the current file being edited and this must be a part of your editor API.

**Comment by suriyaJaay** [comment]
@Noctisdark  thanks for your quick response man.!! well actually am using only one editor at a time. just said for an example. :) now i understood. am gonna try this. thanks for giving clear cut idea.

**Comment by Noctisdark** [comment]
You are welcome, don't forget to close the issue if your problem is solved ;).
