### ISSUE TITLE
[chrome] Hangul has not been entered correctly.

### ISSUE THREAD

**Issue by hangum** [ajaxorg/ace#3097]
Hangul typing from being updated to chromium 53.0.2785.116 version is abnormal.

Chrome : 53.0.2785.116 (64-bit)
![image](https://cloud.githubusercontent.com/assets/1335915/18534974/44aa84bc-7b2b-11e6-87d3-ac34254a07cc.png)

**Comment by x-yao** [comment]
typing Chinese too

**Comment by hangum** [comment]
@x-yao  Show them.

**Comment by mrdream24** [comment]
Chrome 52 work fine. This bug come when update Chrome 53

**Comment by mrdream24** [comment]
![2016-09-21 13_49_47](https://cloud.githubusercontent.com/assets/6170899/18699219/6b61215c-8002-11e6-83a2-2abf7f7d97ca.gif)

**Comment by hangum** [comment]
@mrdream24  same problems. 
my product is broken.  I tested Chrome 54 is abnormal.

What do you think about this problem?

**Comment by mrdream24** [comment]
@hangum my product is broken,too. 

I can't solve this problem

**Comment by hangum** [comment]
@mrdream24 my product is Tadpole DB Hub(https://tadpolehub.com/).  
you?

**Comment by mrdream24** [comment]
@hangum [掘金](http://gold.xitu.io)

**Comment by hangum** [comment]
@mrdream24 thanks.

**Comment by mrdream24** [comment]
github use ace lib. has the same bug.

[github](https://github.com/blog/905-edit-like-an-ace)

**Comment by hangum** [comment]
https://c9.io is same bug.

**Comment by anhh** [comment]
I don't know why but i just commented "onCompositionUpdate function" in ace.js file. It works.

**Comment by hangum** [comment]
@anhh are you fix the problem?

**Comment by anhh** [comment]
It seems like to work. I just tested hangul only. In the first line "onCompositionUpdate function", just put "return;"  code. 
It might have some side effects, but until now there is no side effect.

**Comment by hangum** [comment]
@anhh  감사합니다.  누구세요?

**Comment by hangum** [comment]
ace.js 파일의 부분을 다음과 같이 처리했습니다. 
    var onCompositionUpdate = function() {
//        if (!inComposition || !host.onCompositionUpdate || host.$readOnly)
//            return;
//        var val = text.value.replace(/\x01/g, "");
//        if (inComposition.lastValue === val) return;
//        
//        host.onCompositionUpdate(val);
//        if (inComposition.lastValue)
//            host.undo();
//        inComposition.lastValue = val;
//        if (inComposition.lastValue) {
//            var r = host.selection.getRange();
//            host.insert(inComposition.lastValue);
//            host.session.markUndoGroup();
//            inComposition.range = host.selection.getRange();
//            host.selection.setRange(r);
//            host.selection.clearSelection();
//        }
    };


처리 했을 경우 문제는 
콤마를 입력하고 한글을 입력하다가 지우면 처음에 입력했던 콤마가 삭제되는 오류가 있네요. 
예를들어  '한글테스트 라고 입력하는 중간에 뒤로 삭제하면 처음에 입력했던 콤마까지 삭제 되는 문제가 있습니다. 

그래도 감사합니다.  임시 패치라도 내보내야겠네요. 
누구신지 알려주시면 커피나 밥이라도 사고 싶습니다.

**Comment by hangum** [comment]
fixed 
https://github.com/openatx/atx-webide/commit/69b478a8100789821db4164b2fb0982f9a4c0eb1
