### ISSUE TITLE
[chrome53 and chrome 45 ] chinese input have problem

### ISSUE THREAD

**Issue by zhongxia245** [ajaxorg/ace#3099]
![](http://ww1.sinaimg.cn/large/65e4f1e6jw1f81h3u2mfng20ia0af75f.gif)

> mac os 10.11.3  chrome 53 and chrome 45  have this problem  
> could9 ide have same problem !

**Comment by hangum** [comment]
@zhongxia245  https://github.com/ajaxorg/ace/issues/3097

**Comment by poppinlp** [comment]
Is there any PR about this issue?
Seems there's a solution in linked issue.

**Comment by arathims** [comment]
+1, we are facing this issue too

**Comment by Brittani** [comment]
we are also have this issue too. when fix it?

**Comment by jiangjianxiao** [comment]
+1 we are also have this issue too.

**Comment by vsxen** [comment]
@zhongxia245
@JarvisYang

chrome55已经正常了

**Comment by jiangjianxiao** [comment]
@vsxen 
osx  55.0.2883.75 (64-bit) issue still

**Comment by vsxen** [comment]
Version 55.0.2883.75 (64-bit)
@jiangjianxiao 
![test](https://cloud.githubusercontent.com/assets/8838032/20909644/e15d4b76-bb97-11e6-9f44-e930c99dd59c.gif)

**Comment by JarvisYang** [comment]
@vsxen, ace fixed this bug, not Chrome.

**Comment by jiangjianxiao** [comment]
@JarvisYang  yes , after update ace, work fine.

**Comment by jiacai2050** [comment]
好奇这个问题是怎么发送的，能解释下嘛？
非常感谢。
