### ISSUE TITLE
Weird accents behavior on OSx with keys combos

### ISSUE THREAD

**Issue by implicitdef** [ajaxorg/ace#3100]
**Steps to reproduce :**
Macbook pro OS X El Capitan 10.11
QWERTY keyboard, set with US language
On the demo editor on https://ace.c9.io
Hold the **alt/option** key and the **e** key together. The **´** symbol appears. Release both, then press **e** again once.

**Expected behavior :** 
The **´** is replaced by **é**
Actual behavior :
The **´** is not replaced and the **é** doesn't appear.
If I hit **e** once again, then the following characters appear simultaneously : **ée**, added after the original **´**

Same problem observed with other accents : è, à, á, etc.

Might be linked to open issues https://github.com/ajaxorg/ace/issues/1756 https://github.com/ajaxorg/ace/issues/3022, but these are talking about the accents menu, and I'm talking about the keys combos.

I don't know how recent this bug is in ACE editor but I noticed it recently on Github' usage of the editor and I could swear it was working fine a few weeks ago...

**Comment by nightwing** [comment]
This should be fixed by https://github.com/ajaxorg/ace/pull/3635, please let us know if you still can reproduce this on http://ace.c9.io. Thanks.

**Comment by implicitdef** [comment]
It seems to be fixed indeed on https://ace.c9.io/. Thanks.
