### ISSUE TITLE
Urgent. Code has comments containing '\n' and Ace Editor adding new line for each \n. Please help!

### ISSUE THREAD

**Issue by sssaurabhkv** [ajaxorg/ace#3104]
Hello Experts,

I am setting value of ace editor programmatically like this:

editor.getSession().setValue(problem_code);

This is content of my problem_code:

public class Solution {
//\n\n\n
}

But when it renders in Ace Editor, it comes with new lines for each \n. I have attached a screenshot for the same.
![weirdaceeditorbehavior](https://cloud.githubusercontent.com/assets/3591689/18917990/fd2bb2e6-85b6-11e6-8ded-122e1811562f.png)

Please help.

Thanks!

**Comment by sssaurabhkv** [comment]
Could someone please help?

**Comment by nightwing** [comment]
Please show a page demonstrating this issue. How did you check that problem_code contains raw "\n" and not newline? Did you try adding `console.log(problem_code)` before editor.setValue?
