### ISSUE TITLE
localize character(not ascii char) inputs problem

### ISSUE THREAD

**Issue by sugerplay** [ajaxorg/ace#3105]
![problem3](https://cloud.githubusercontent.com/assets/8487913/18934383/597fee2e-8614-11e6-9b1d-876d0db137dd.gif)

I'm using C9 IDE and it is occurred when same condition.

**Comment by suqi** [comment]
I've got the same problem and I found that it's a compatible issue of ace editor and the latest v53 chrome.
![image](https://cloud.githubusercontent.com/assets/1326887/19229340/61e6855c-8eff-11e6-
82de-ed62acec7afa.png)

There's no problem in Safari and Chrome version<=52.

So maybe it's a problem of chrome v53 or a compatible issue?

**Comment by sugerplay** [comment]
It is occurred in Edge browser. I assume that it iss related with newal js(or css) implementation.

**Comment by nightwing** [comment]
This should be fixed by https://github.com/ajaxorg/ace/pull/3635, please let us know if you still can reproduce this on http://ace.c9.io. Thanks.
