### ISSUE TITLE
Add a div between two lines

### ISSUE THREAD

**Issue by ManojkumarV** [ajaxorg/ace#3106]
I need to add a div between two lines of ace editor and show some formatted documentation about the lines below in that div. How to add a div between two lines of the editor.

**Comment by mlajtos** [comment]
You want [LineWidget](lib/ace/line_widgets.js). You can look at [error_maker.js](lib/ace/ext/error_marker.js) on how to use them.

**Comment by ManojkumarV** [comment]
@mlajtos I'm able to add div using Line widgets. But when i scroll over the div of the widget the widget is not getting scrolled. Instead the editor is scrolled. Also when the height if the div increases or decreases the editor lines are not getting aligned properly.

**Comment by nightwing** [comment]
call resize method of widget when the height of the div changes.
call stopPropagation on the wheel event of the widget, to prevent editor from handling it
