### ISSUE TITLE
Handling large files

### ISSUE THREAD

**Issue by rahmanusta** [ajaxorg/ace#3112]
I'm so pleased to use Ace in https://github.com/asciidocinfx/AsciidocFX project. If file size larger than ~2MB, my editor's browser hangs until data totally loaded. Is there any way to handle large files in Ace ? 

Thanks

**Comment by nightwing** [comment]
ace doesn't handle data loading, most likely you are loading text with sync xhr, or some equivalent api.

**Comment by rahmanusta** [comment]
Sorry, I mean is the setValue method capable to handle large files?

**Comment by jsrun** [comment]
Hi friend, I believe this example solves what you are asking https://github.com/jsrun/express-send-stream

**Comment by rahmanusta** [comment]
Hello dear, I don't use express in my project. There is no problem while loading big file, I do load content from different thread. The issue is, while setting big content to ace, it hangs. Atom editor also hangs with big content, it is the same issue. I wondered is there a way to handle big content in ace in a lazy loading way.

Thanks

**Comment by vnesterovspirent** [comment]
@rahmanusta Hello! Please tell me if you managed to find a solution to this problem?

**Comment by rahmanusta** [comment]
> @rahmanusta Hello! Please tell me if you managed to find a solution to this problem?

I couldn’t find a way unfortunately.
