### ISSUE TITLE
Ace editor freezes with maxLines = 1 and setUseWrapMode(true)

### ISSUE THREAD

**Issue by mttcr** [ajaxorg/ace#3113]
Hello,
We are using ace editors with the following options, and it freezes the whole browser tab (a bit like #2495 )
This works:

```
var editor = ace.edit($("#editor").get(0));
editor.setOption("minLines", 1);
editor.setOption("maxLines", 1);
```

This fails:

```
var editor = ace.edit($("#editor").get(0));
editor.setOption("minLines", 1);
editor.setOption("maxLines", 1);
editor.getSession().setUseWrapMode( true );
```

Here is a jsfiddle to show the issue: https://jsfiddle.net/b3b8cm9a/
just add the `editor.getSession().setUseWrapMode( true );` below `editor.setOption("maxLines", 1);` and everything hangs when you click on run.

**Comment by edimitchel** [comment]
I confirmed this issue !

**Comment by mttcr** [comment]
still interested in this issue.

**Comment by andrewnester** [comment]
The issue is not reproducible with the latest 1.5.1 version of Ace, closing
