### ISSUE TITLE
Uncaught TypeError: Cannot set property '0' of null

### ISSUE THREAD

**Issue by dlangerenken** [ajaxorg/ace#3120]
When changing the mode 'on the fly' (based on user input), I get the following exception when switching to mode/sql from any other mode:

ace.js:8372 Uncaught TypeError: Cannot set property '0' of null
```js
    this.updateFoldWidgets = function(delta) {
        var firstRow = delta.start.row;
        var len = delta.end.row - firstRow;


    if (len === 0) {
        this.foldWidgets[firstRow] = null; <<--- foldWidgets is null
    } else if (delta.action == 'remove') {
        this.foldWidgets.splice(firstRow, len + 1, null);
    } else {
        var args = Array(len + 1);
        args.unshift(firstRow, 1);
        this.foldWidgets.splice.apply(this.foldWidgets, args);
    }
};
```

My code: 

```js

editor.getSession().setMode('ace/mode/javascript'); //default javascript
editor.setAutoScrollEditorIntoView(true);
editor.$blockScrolling = Infinity;
editor.setOption('maxLines', 100);
editor.renderer.setShowGutter(false);
editor.setShowFoldWidgets(false);
...

function updateMode(inputStart){
  var mode = interpreters[inputStart];
  if (mode && mode != editor.getSession().getMode()){
        editor.getSession().setMode(mode);
  }
}
```

Also: If I don't set the mode via `session.setMode({
   path: "ace/mode/python",
   v: Date.now() 
})`

I receive the following error:
`ace.js:16872 TypeError: Cannot read property 'postMessage' of null
    at WorkerClient.emit (ace.js:16869)
    at WorkerClient.$sendDeltaQueue (ace.js:16903)`

I don't mind these errors, as the syntax highlighting still works fine. However, the first error will cut a character when switching to mode/sql which is what is bothering me.

v1.2.5 via bower (ace-build#^1.2.5) . I only included ace.js, mode-javascript.js, mode-python.js, mode-markdown.js and mode-sql.js

**Comment by nightwing** [comment]
Could you please create a demo page showing how to reproduce this issue. You could modify http://jsbin.com/ojijeb/266/edit?html,output or give a link to your application.

**Comment by dynastywind** [comment]
@dlangerenken Hi, I've encountered the same problem. Did you solve your problem?

**Comment by Flowdeeps** [comment]
I found that adding a check for undefined sorted out my issue.
``` js
    this.updateFoldWidgets = function(delta) {
        var firstRow = delta.start.row;
        var len = delta.end.row - firstRow;
        if (len === 0) {
            this.foldWidgets[firstRow] = null;
        } else if (delta.action == 'remove') {
          if (this.foldWidgets !== null)
            this.foldWidgets.splice(firstRow, len + 1, null);
        } else {
            if (event !== 'undefined') {
              var args = Array(len + 1);
              args.unshift(firstRow, 1);
              this.foldWidgets.splice.apply(this.foldWidgets, args);
            }
        }
    };
```

**Comment by foobarfighter** [comment]
I recently hit this issue as well while using react-ace.  Here is the bug files in react-ace: https://github.com/securingsincity/react-ace/issues/590
