### ISSUE TITLE
Ace Editor Find And Replace Enhancement Needed

### ISSUE THREAD

**Issue by vinothwindows47** [ajaxorg/ace#3121]
In Ace Editor Find and Replace to show **number of total matches** and **current iteration match count of total matches** which would be helpful for many developers .

I attached below screenshot to use it .
![aceeditor_find_replace](https://cloud.githubusercontent.com/assets/3929019/19380124/57f60d26-9213-11e6-9ece-7087a7c4e294.png)

**Comment by vinothwindows47** [comment]
@nightwing

**Comment by vinothwindows47** [comment]
@nightwing Any idea about this ?

**Comment by nightwing** [comment]
@vinothwindows47 https://github.com/ajaxorg/ace/pull/3313 should fix this. btw where is this screenshot from?
