### ISSUE TITLE
Why there is no a method like 'removeCompleter'?

### ISSUE THREAD

**Issue by wmzy** [ajaxorg/ace#3122]
There is a method '[addCompleter](https://github.com/ajaxorg/ace/blob/master/lib/ace/ext/language_tools.js#L89)'.
But how to remove the completer?

**Comment by Noctisdark** [comment]
The `Editor` class has a special member called `completers` which contains all the completers attached to the instance.

To remove a completers, you simply have to deattach if from the `completers` array:

```javascript
//Supposes that you are calling you Editor instance editor
let completers = editor.completers;
completers.splice(completers.indexOf(myCompleter, 1));
```

**Comment by wmzy** [comment]
@Noctisdark Thanks!It works.

**Comment by Noctisdark** [comment]
Don't forget to close the issue if you don't need more assistance.
