### ISSUE TITLE
Language Server Protocol Integration

### ISSUE THREAD

**Issue by akosyakov** [ajaxorg/ace#3124]
Microsoft has announced [Language Server Protocol](https://github.com/Microsoft/language-server-protocol). Is there any plans to provide integration with it?

**Comment by jgoldshlag** [comment]
I'm also interested in support for this

**Comment by Aerilius** [comment]
I would be interested as well, as it promises higher quality code-completion than I currently have, with less maintenance effort. Having LSP support helps to keep Ace relevant for my project in the long-term.

**Comment by hez2010** [comment]
With LSP, Inteiilsence will be available for ace editor. Hope that ace editor can integrate LSP.

**Comment by apttap** [comment]
it would be a nice extension at the very least, I would love to develop a custom editor eventually with the work I'm doing in lsp. ace would be my preferred method for that

**Comment by andrewnester** [comment]
Just to provide an update on this - we're looking into LSP support for Ace as it's obviously one of the most asked features, so we'll keep this thread updated with any progress we make. In the meantime feel free to provide any feedback or ideas about how would you use Ace with LSP servers

**Comment by kungfooman** [comment]
> In the meantime feel free to provide any feedback or ideas about how would you use Ace with LSP servers

I use TypeScript for "live coding" and LSP could provide type safety and IntelliSense for quicker live coding. I usually bind Ctrl+Enter to "execute" all code in ACE and then copy over the snippets into VSCode.

I am also interested in language design itself, so that would also help building custom languages (e.g. TypeScript with operator overloading support or languages completely from scratch - nice for CS students for example).

**Comment by andrewnester** [comment]
@kungfooman where do you run LSP server in your use case?

**Comment by CypherpunkSamurai** [comment]
Any updates on this?

I'm currently trying to create a completer that sends the completion prompt via websocket, but i cant seem to understand how to send the received websock message as a autocompletion callback. Any help would be apreciated

completer code:
```js
var completer = {
    getCompletions: function(editor, session, pos, prefix, callback) {
        if (prefix.length === 0) { callback(null, []); return }
        // Get file contents
        const contents = editor.getValue();
        const row = pos.row;
        const col = pos.column;
        const triggerChar = prefix;
        didChange(socket, currentFilepath, contents);
        getLSPCompletion(socket, currentFilepath, row, col, triggerChar);
    }
}
```
```js
socket.onmessage = function(event) {
    // Log
    console.log(event);
}
```

Is there any way to use the socket onmessage to trigger the autocomplete prompt along with the values returned by the lsp?

**Comment by renhiyama** [comment]
any updates on this?

**Comment by Dineshchitta** [comment]
any updates on this?

**Comment by andrewnester** [comment]
The team is picking up this work and you should expect to see some related code changes any time soon :)
It's an important project for us and we will keep this thread updated with any details.

**Comment by nightwing** [comment]
The initial version is available at https://github.com/mkslanc/ace-linters. Currently it includes support for connecting to lsp server via websocket, and to monaco language services running in a webworker.

Any feedback and feature requests are highly appreciated.

**Comment by CypherpunkSamurai** [comment]
This is impressive work @nightwing @andrewnester!

I'll run live tests and let you know of any bugs

**Comment by whazor** [comment]
People can build LSP servers on top of Ace via [ace-linters](https://github.com/mkslanc/ace-linters) from @mkslanc, or use the API of ACE directly to add markers and add auto-complete.

**Comment by CypherpunkSamurai** [comment]
Hello @whazor, Can you guys also provide a Quick Start example with ace-linters? Like a complete separate repository possibly. The current implementations are using a lot of utility functions that might be hard to get the head around without diving into the core ace codebase. I tried to use it alongside a react project a long time ago but failed miserably and switched to monaco.

 A minimal vite project with maybe `type-scipt-language-server` and websockets would be cool👍🏼

**Comment by mkslanc** [comment]
Hi @CypherpunkSamurai ! For websockets example you could look into [readme](https://github.com/mkslanc/ace-linters?tab=readme-ov-file#usage-with-websocket-json-rpc) or [Verified Language Servers on wiki](https://github.com/mkslanc/ace-linters/wiki/Verified-Language-Servers-for-Ace-Linters). Also [demo](https://github.com/mkslanc/ace-linters/tree/main/packages/demo) has plenty of useful examples
