### ISSUE TITLE
Context menu edit options are no longer selectable on chrome 54

### ISSUE THREAD

**Issue by vegetableman** [ajaxorg/ace#3127]
After the latest chrome update to `54.0.2840.71`, the context menu for editing - `cut, copy, undo` are no longer selectable. 

![screen shot 2016-10-21 at 11 25 52 am](https://cloud.githubusercontent.com/assets/1330851/19588115/2b1ccc18-9781-11e6-9e6c-9d13cba70ed6.png)

**Comment by pketh** [comment]
I'm also having this problem in my own and all other instances of ACE in Chrome 54

<img width="324" alt="screen shot 2016-10-28 at 1 17 29 pm" src="https://cloud.githubusercontent.com/assets/877072/19815450/eef844fc-9d10-11e6-88c1-9c309279db17.png">

**Comment by pketh** [comment]
Also have the same issue in Canary 56

**Comment by anonymousandrew** [comment]
Appears to be tracked in https://bugs.chromium.org/p/chromium/issues/detail?id=621138

**Comment by robolivable** [comment]
@anonymousandrew are we sure this is the same issue? The bug described in that link seems to behave differently depending on the selected text. In regards to Ace, this issue is persistent inside any text field, regardless of how characters are selected.

**Comment by robolivable** [comment]
I can confirm to be able to repro on the following:

OS details:
 - OS X El Capitan 10.11.16
 - OS X Sierra 10.12.1

Chrome details: 
 - Google Chrome Version 54.0.2840.98 (64-bit)
 - Google Chrome Canary Version 57.0.2938.0 (64-bit)

**Comment by amasad** [comment]
I opened an issue on the chromium bug tracker because I'm not sure it's the same issue that @anonymousandrew pointed out.

Please [star it](https://bugs.chromium.org/p/chromium/issues/detail?id=686339&can=2&start=0&num=100&q=ace%20editor&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified&groupby=&sort=).

**Comment by tophf** [comment]
>[**Comment 4 by tkent@chromium.org**](https://crbug.com/686339#c4)
>It seems the root issue is that Chrome requires to focus on INPUT/TEXTAREA to show correct context menu after [r413695](https://crrev.com/413695), and usually right-mousedown focuses on the element, but Ace editor seems to prevent to focus.

Looks like Ace is to blame here?
In CodeMirror the menu items are working.

**Comment by DreaminginCodeZH** [comment]
I wonder when will this fix be released?

**Comment by amasad** [comment]
@nightwing Would be great to get a release out to fix this bug

**Comment by omeryagmurlu** [comment]
Any workarounds while the fix is on the way?

**Comment by amasad** [comment]
I think it's fixed. Just needs a release
