### ISSUE TITLE
JS exception when first action in Ace instance is clicking + dragging on HTML line widget

### ISSUE THREAD

**Issue by kevinushey** [ajaxorg/ace#3128]
We noticed this in RStudio -- if the first action a user takes within an Ace instance is clicking and dragging on a line widget (before ever clicking in the editor surface), then a JS exception is emitted:

![ace](https://cloud.githubusercontent.com/assets/1976582/19707605/628dc5ae-9acd-11e6-841f-bc60dec124a3.png)

We have a local patch that simply detects whether `mousedownEvent` is `null` before attempting to call `getShiftKey()`, but let me know if you think there's a better way for this to be handled.

**Comment by nightwing** [comment]
Sorry, for not replying to this in time. I was not able to reproduce the issue. Do you still see it? If yes, and if there are no further uses of mousedownEvent, checking for mousedownEvent sounds good.

**Comment by kevinushey** [comment]
We haven't taken the time to update the version of Ace embedded in RStudio just yet (we're still on v1.1.8); once we get to that I'll revisit this and let you know if we're still seeing any issues.
