### ISSUE TITLE
Is there a way to get all errors/warnings?

### ISSUE THREAD

**Issue by vbguyny** [ajaxorg/ace#313]
I really like the feature that displays the error/warning icons in the buffer area to the left of the text area.  However, I would like to get a collection of all errors/warnings so that I can display them to the user in a list.  I would also like this collection to contain the line/column number so that I can set the cursor position to each issue.

I would like something like:

var Errors = editor.getSession().getErrors();
var (var i = 0; i < Errors.length; i ++)
{
  var Error = Errors[i];
  // Error.LineNumber
  // Error.ColumnNumber
  // Error.Description
}

**Comment by ldijkman** [comment]
thanks

would like to use it in vertical scrollbar visualizer
https://ldijkman.github.io/Ace_Seventh_Heaven/Hell.html

```
//get warnings errors?
console.log("editor.getSession().getAnnotations()",editor.getSession().getAnnotations());
console.log("editor.getSession().getAnnotations().length",editor.getSession().getAnnotations().length);
for (let i = 0; i < editor.getSession().getAnnotations().length; i=i+1) {
console.log("errors/warnings on line ",
editor.getSession().getAnnotations()[i].row,
" type=",
editor.getSession().getAnnotations()[i].type);

}
```

**Comment by ldijkman** [comment]
> The object returned is simply a hash of hashes. It looks like this:
> 
> `this.$annotations = {};`
> 
> Thus the $annotations hash might look like this:
> 
> ```js
> {
>     {
>         row: 12,
>         column: 2, //can be undefined
>         text: "Missing argument",
>         type: "error" // or "warning" or "info"
>     },
>     {
>         row: 32,
>         text: "Missing semicolon",
>         type: "warning"
>     },
>     // etc
> }
> ```
> 
> You can iterate over the response like so:
> 
> ```js
> var annotations = editor.getSession().getAnnotations();
> 
> for (var anno in annotations) {
>      // anno.row, anno.column, anno.text, anno.type
> }
> ```

maybe i doi it wrong
but example did not work for me

https://ldijkman.github.io/Ace_Seventh_Heaven/Hell.html
```
//get warnings errors?
console.log("editor.getSession().getAnnotations()",editor.getSession().getAnnotations());
console.log("editor.getSession().getAnnotations().length",editor.getSession().getAnnotations().length);
for (let i = 0; i < editor.getSession().getAnnotations().length; i=i+1) {
console.log("errors/warnings on line ",
editor.getSession().getAnnotations()[i].row,
" type=",
editor.getSession().getAnnotations()[i].type);

}
var annotations = editor.getSession().getAnnotations();
for (var anno in annotations) {
     // anno.row, anno.column, anno.text, anno.type
     console.log(anno.row, anno.column, anno.text, anno.type);
}
```
