### ISSUE TITLE
Add Syntax Highlight for MIPS Assembler

### ISSUE THREAD

**Issue by jefersonla** [ajaxorg/ace#3131]
Hello,

Can someone, add syntax highlight for MIPS Assembler?
I found this answer on SO (http://stackoverflow.com/questions/28689942/has-anyone-created-a-mips-syntax-highlighter-for-ace-editor), but I can't figurate a way of add this inside my Cloud9 Workspace.
Any help will be apreciated. 

Thx.

**Comment by rchoudhary** [comment]
@nightwing  @jefersonla I have submitted a pull request that should take care of syntax highlighting of MIPS programs. It also handles doing `ctrl+/` to comment out lines.
