### ISSUE TITLE
Accent marks are not processed correctly in Mac + Chrome

### ISSUE THREAD

**Issue by antonio-ortega** [ajaxorg/ace#3138]
Hi,

We've realized accent marks are not properly processed when using Mac + Chrome (latest version). If you try to write "_Córdoba es una región de Andalucía_" you'll see something like "_C´órdoba es una regi´ón de Andaluc´ía_". It's happening only in Mac, and just for Chrome. In Firefox, you can see a non-recognize character while you're typing, but the word is eventually correct. In Safari is working as expected.

As far as we can find it out, looks like some event is catching the type of the accent mark and introducing an extra accent.

Thanks in advance.

Regards,

**Comment by rafbgarcia** [comment]
hi @antonio-ortega, do you know if there is a fix for that issue yet?

**Comment by nightwing** [comment]
This should be fixed by https://github.com/ajaxorg/ace/pull/3635, please let us know if you still can reproduce this on http://ace.c9.io.
