### ISSUE TITLE
How can I use ace with webpack

### ISSUE THREAD

**Issue by huangguozhen** [ajaxorg/ace#3139]

**Comment by waywaaard** [comment]
You can use the CDN version and add following object to your configuration:

```javascript
  externals: {
    "ace": true
}
```

This tells webpack, that ace is available and can be imported in es6 files:
```javascript
import Ace, { EditSession, UndoManager } from 'ace';
const modelist = Ace.require('ace/ext/modelist');
```
This allows you to even create custom EditSessions.

**Comment by huangguozhen** [comment]
@waywaaard thank you, It work follow your answer.
i have another question, how can i use it but don't include external script
 `<script src="cdn.bootcss.com/ace/1.2.5/ace.js"></scirpt>`.

**Comment by mryellow** [comment]
This isn't helpful. It needs to be packed with webpack rather than requiring 3rd party domains, CSP, etc etc.

**Comment by nightwing** [comment]
@mryellow this is a very old issue, here's an example showing an example of  using webpack https://github.com/ajaxorg/ace-samples/tree/master/samples/ace-builds-webpack
