### ISSUE TITLE
Incorrect representation of raw code

### ISSUE THREAD

**Issue by Khsaf** [ajaxorg/ace#3146]
ACE editor is not correctly presenting **&&** characters in java code.

I have a string variable which holds java code including:
`if (field.name.length == fieldLength && CharOperation.prefixEquals(field.name, fieldName))`
The ACE editor shows the code like the following:
`if (field.name.length == fieldLength &l;&l; CharOperation.prefixEquals(field.name, fieldName))`

**Comment by nightwing** [comment]
this is the way html works, & and < must be escaped see https://github.com/ajaxorg/ace/issues/3165#issuecomment-266785579
