### ISSUE TITLE
tooltips style

### ISSUE THREAD

**Issue by yopbeast** [ajaxorg/ace#3148]
Hi, how can i change the tooltips style?

I tried looking into the code and into the html but it seems they are somewhere else?

Isn't it a `title=""` html  attribute?
 

thanks

**Comment by nightwing** [comment]
If you are asking about gutter tooltips style is at https://github.com/ajaxorg/ace/blob/v1.2.6/lib/ace/css/editor.css#L293-L316, and tooltip is created at https://github.com/ajaxorg/ace/blob/v1.2.6/lib/ace/mouse/default_gutter_handler.js#L72

**Comment by rocketinventor** [comment]
@yopbeast If you are asking about the code autocomplete, I would suggest adding CSS code to your stylesheet (which I use) similar to the following:
```
/*Give suggestions list white text*/
.code_complete_text.dark .ace_line {
    color: white;
}
/*Give its info box a slight background*/
.code_complete_doc_text.dark {
    background: rgba(246,256,256,0.25);
}
```
