### ISSUE TITLE
Publish on packagist / composer?

### ISSUE THREAD

**Issue by ToX82** [ajaxorg/ace#3154]
Would it be possible to have ace published on [packagist.org](packagist.org), to be installed with composer?

**Comment by nightwing** [comment]
What is required to publish there? Also do you want to have ace or ace-builds published?

**Comment by ToX82** [comment]
I'd prefere the ace-builds as I think that this would be the most common use for other users.

According to its docs, the only thing needed to  is file called `composer.json` in the root of the project, containing something like this:

    {
        "name": "your-vendor-name/package-name",
        "description": "A short description of what your package does",
        "require": {
            "php": "^5.3.3 || ^7.0",
            "another-vendor/package": "1.*"
        }
    }

I think that the require part is not needed here though :)
Then you just need to submit the package to packagist.

You can see all the steps needed here too: https://packagist.org/
