### ISSUE TITLE
Syntax validation for java is not working.

### ISSUE THREAD

**Issue by yogitaAP** [ajaxorg/ace#3158]
I am using ace editor in an angular application and I have initialized the editor in Java mode. The syntax highlighting for Java is not working. However, if I change the mode to javascript, it works fine.  Why is that so?. Also, I set "$scope.editor.getSession().setUseWorker(true);" explicitly.

Attaching the screenshot for reference.

Java mode
<img width="677" alt="screen shot 2016-12-05 at 12 08 46 pm" src="https://cloud.githubusercontent.com/assets/9781726/20875805/9d8af8c6-bae3-11e6-8bfb-481e9c2779ba.png">

Javascript mode
<img width="678" alt="screen shot 2016-12-05 at 12 06 09 pm" src="https://cloud.githubusercontent.com/assets/9781726/20875760/44f3594c-bae3-11e6-9050-971b52ae4c1a.png">

**Comment by nightwing** [comment]
there is no syntax checker for java, you'll need to write java parser/linter that works in the browser, or use a server to run javac or findbugs.

**Comment by yogitaAP** [comment]
@nightwing Thanks for the response.
