### ISSUE TITLE
Initialize ace editor with HTML instead of text

### ISSUE THREAD

**Issue by yogitaAP** [ajaxorg/ace#3161]
I am initialising the editor with some code say "Hello World". Now I make some edits and then save the innerHTML of the editor as I annotated the html. I save the innerHTML of editor and next time I reload the editor I want same HTML with annotations. So I append the editor div with HTML formed from the innerHTML I saved. It does puts the code in the editor but I am not able to click on the editor or make any changes there after. Is there any other way to initialise the editor with HTML rather than text. Tried a handful of things, doesn't seem to work. Any help/comments/suggestions would be appreciated.

**Comment by nightwing** [comment]
modifying innerHTML of ace is going to break the editor, what kind of annotations do you add to the editor?

**Comment by yogitaAP** [comment]
I am adding some custom annotations. I have defined their types and styles. I have that modified HTML saved. I just need a way to initialise the editor with HTML rather than text. Is there a way?

**Comment by nightwing** [comment]
how do you update them when the editor scrolls? When scrolling ace will redraw it's contents and clear your annotations. Ace creates html nodes only for the visible part of the text so there is no way to restore text from snapshot of its html

**Comment by yogitaAP** [comment]
I have a copy in my code to update the annotations. However, I was unaware of Ace redrawing the elements on scroll and hence there is no point saving the snapshot of html as you said. Here is a brief description of what I am trying to achieve. 

Let's take a sample code: 

class Sample{
   public static void main() {
          class2.func1(); // wrapped in HTML tag span1
          class2.func2();// wrapped in HTML tag span2
   }
}

Now, I have a hash map which has some info of func1 and func2 and I need that info to display when there is a hover on those span1 and span2. I need to store this info as annotations or as span attributes. Next time when I reload the editor, this info has to be present. This is the reason I was annotating the spans and trying to take a snapshot of HTML for next time rendering. If there is any existing functionality to modify ace HTML elements, please enlighten me on the same. I am a newbie to ACE. Just started trying out things on it.
