### ISSUE TITLE
selection not available in Chrome context menu

### ISSUE THREAD

**Issue by kgersen** [ajaxorg/ace#3162]
The current selection isn't available in Chrome context menu (right click):

steps to reproduce:

double click a word or select something
right mouse click, the context menu appears.
The selection isn't known in the menu.
For instance, you see  `search  Google for "   "` instead of `search  Google for "<what is selected>"` 
Extensions that hook to this menu also don't work (such as the "Context Menu Search" extension).

screens (from https://ace.c9.io ) :
![bug1](https://cloud.githubusercontent.com/assets/1764578/20966889/d12527ca-bc7c-11e6-90c7-5688f0ce1fa1.png)

normal behavior (outside ace) :
![bug2](https://cloud.githubusercontent.com/assets/1764578/20966919/edafd278-bc7c-11e6-9e85-6002d497ba33.png)

**Comment by nightwing** [comment]
This is fixed by https://github.com/ajaxorg/ace/pull/3635, please let us know if you still can reproduce this on http://ace.c9.io. Thanks.
