### ISSUE TITLE
?<? breaks editor "unexpected token <"

### ISSUE THREAD

**Issue by aidanwolf** [ajaxorg/ace#3165]
Hi all,

I'm adding prewritten text to the editor window:

Breaks
` for(var x=xarray[0];x<xarray[1];x++){`

Doesn't break (added space after "<")
` for(var x=xarray[0];x< xarray[1];x++){`

All lines and characters after the "<" do not load in, nasty bug.

**Comment by nightwing** [comment]
you need to escape  `<` and `&` characters when writing html see https://github.com/ajaxorg/ace/blob/master/build_support/editor.html#L26
