### ISSUE TITLE
Spell checking with the Grammarly web plugin does not work in Ace

### ISSUE THREAD

**Issue by smaret** [ajaxorg/ace#3166]
I'd like to use the [Grammarly web plugin](https://www.grammarly.com) for spell checking LaTeX and MD documents written with Ace, but it does not seem to work. I've tried to edit a document using [demo editor](https://ace.c9.io/build/kitchen-sink.html), and the Grammarly icon does not appear in the text window.

Could this be fixed?

**Comment by rocketinventor** [comment]
@smaret I don't think _any_ grammar or spell checking works in ace. The plugin would have to be made to support it (could be implemented as an autocompleter, also). I would contact grammarly.

**Comment by smaret** [comment]
Thanks for the suggestion, I just got in touch with Grammarly's support.

**Comment by smaret** [comment]
I exchanged a few emails with the support, and they confirmed that the plugin does not work with Ace:

> Unfortunately, the technical team confirmed that Grammarly does not offer integration with the Ace web editor.
> 
> You are welcome to upload and check your documents in our Online Editor at https://app.grammarly.com/.
> 
> Please do not hesitate to contact us with any questions or concerns you might have. We are > committed to making your experience at Grammarly pleasant and rewarding.

Is there anything that can be done on the Ace side to get this working? Or is it a limitation of the plugin itself?

**Comment by octotree** [comment]
@rocketinventor this is funny reasoning: When none of the many spell checkers work with ace, smaret should contact one of the makers of such a spell checker to make it work with ace. Wouldn't it be right to fix the one software which seems to have a problem with all the spell checkers?

**Comment by rocketinventor** [comment]
@octotree There are spell checkers that work with Ace but, as far as we know, there are no code editors that work with Grammarly. Ace has ways to enable the default spellchecker (which may or may not work with Grammarly). Grammarly does not provide an API or any docs on how to integrate. If they did, its functionality could be added to Ace itself.

Grammarly only activates on certain types of input fields. That's _their_ decision.

In Ace, the spellchecker is disabled by default but, it can be enabled in a few ways. One method is to add `contenteditable="true" spellcheck="true"` to the attributes of the editor's div element enables spellcheck  (#2107). Another method is to use Ace's spellcheck.js extension. 

@smaret  [StackEdit](https://stackedit.io/editor) supports Chrome's built in spell-check for markdown, and [Share Latex](https://www.sharelatex.com/) uses the default spellchecker for LaTeX. Try writing something in [StackEdit](https://stackedit.io/editor) with Grammarly enabled and let me know if it has spell check for you or not.

**Comment by smaret** [comment]
> Try writing something in StackEdit with Grammarly enabled and let me know if it has spell check for you or not.

Yes, it works.

**Comment by rocketinventor** [comment]
Okay, it's not an issue with Ace, then; it's just a setting issue. Where
are you using the editor?

**Comment by octotree** [comment]
@rocketinventor thanks for your very insightful explanation. I would like to use Grammarly with sharelatex (which uses ace) and in fact, it works as soon as I add `contenteditable="true"` to the editor div :+1: (spellcheck was already enabled).

I will test it a little more and eventually create a PR for sharelatex. Thanks again :-)

**Comment by rocketinventor** [comment]
@octotree Great! Thanks for asking the right questions!

**Comment by rocketinventor** [comment]
@smaret Did this solve your problem?

**Comment by nightwing** [comment]
Simply setting `contenteditable="true"` won't work, because that way Grammarly can get only the visible part of the file, and when setting value, it will replace all the dom created by ace, so code using ace won't see changes made by Grammarly editor.

> Wouldn't it be right to fix the one software which seems to have a problem with all the spell checkers?

Ace is not the only editor with which Grammarly doesn't work . All of code editors: codemirror, monaco, orion, do not work, and many rich text editors, e.g. prosemirror, draft.js do not work well too.
On StackEdit grammarly often creates an infinite loop, freezing the page.

There is not much we can do in Ace to help Grammarly, only thing I can think of is a command to temporarily replace ace instance with a textarea.

**Comment by smaret** [comment]
> @smaret Did this solve your problem?

@rocketinventor I haven't tried yet. I'll do it asap and I'll keep you posted here. Thanks for the suggestion!

**Comment by natale-p** [comment]
Hello, any advancements on that?

**Comment by abreslav** [comment]
Would be wonderful to see this fixed. The comments box here has Grammarly working, but not the file editor or gist editor :(

**Comment by wmantly** [comment]
Please!

**Comment by alim1369** [comment]
no enhancement?

**Comment by marniks7** [comment]
it doesn't work for a file editor :(

**Comment by Rishgod** [comment]
:(

**Comment by daigotanaka** [comment]
I made it work with the hint from @octotree for my purposes.
https://github.com/daigotanaka/ace-builds
It's not perfect but I can live with this.
