### ISSUE TITLE
Add support to semantic highlighting 

### ISSUE THREAD

**Issue by marcospassos** [ajaxorg/ace#3168]
It would be awesome if the tokenizer could be able to dynamically provide not only a class name but also styles. The use case for such feature is [semantic identifier highlighting](https://medium.com/@evnbr/coding-in-color-3a6db2743a1e#.ulqkvrd6l), such as displaying hexadecimal colors in their respective colors or even semantic identifier highlighting, as [PHPStorm](https://blog.jetbrains.com/phpstorm/2016/09/phpstorm-2016-3-eap-163-4830/) has just introduced.

While it isn't officially supported yet, is there any other way to implement it currently?

**Comment by rocketinventor** [comment]
I agree, it would be really nice to see this as a feature I don't see any reason why this can't be implemented on the ACE Dom level, though (with poor performance).

**Comment by nightwing** [comment]
The code for rendering tokens is at https://github.com/ajaxorg/ace/blob/v1.2.6/lib/ace/layer/text.js#L361-L367, it would be easy to change that, to get style from token instead of className.
I don't plan working on semantic highlighting in the near future, but would be happy to help if someone else does.

**Comment by rocketinventor** [comment]
@nightwing So, if one changes the line that says ```var style = "";```, they can make the token have whatever styling they want _on top of_ the normal styling (added class)? How does one get the value of the token at this point? Is there any way to do this without modifying `text.js`?

**Comment by nightwing** [comment]
try adding 
```js
{
    token : function(value) {
        return "custom' style='color:" + value
    },
    regex : "#[a-f0-9]{6}"
},
```
in css mode, it will display hex color in its own color

this is of course a hack, but should work well enough for development.

**Comment by rocketinventor** [comment]
@nightwing That looks great, thanks for the quick reply! Where does that code go? Can it be put in a c9 user config.js?

**Comment by rocketinventor** [comment]
Like this?

```
var style = {
    token : function(value) {
        return "custom' style='color:" + value
    },
    regex : "#[a-f0-9]{6}"
};
```

Is there any way to do this via code injection?

**Comment by rocketinventor** [comment]
@nightwing I tried that code locally with Kitchen Sink. Nothing happened.
Perhaps I don't quite understand the implementation.
