### ISSUE TITLE
Use theme from remote server

### ISSUE THREAD

**Issue by rocketinventor** [ajaxorg/ace#3169]
I would like to be able to use remote theme files in ace (i.e. instead of `editor.setTheme("ace/theme/monokai")` I would like to specify a URL such as: `https://mysite.com/ace/theme/monokai.js`. However, `editor.setTheme("https://mywebsite.com/ace/theme/monokai")` and `editor.setTheme("https://mywebsite.com/ace/theme/monokai.js") do not seem to work.

**Comment by nightwing** [comment]
you can use something like
```js
ace.config.setModuleUrl(
    "ace/theme/monokai", 
    "http://ajaxorg.github.io/ace-builds/src-noconflict/theme-monokai.js"
)
editor.setTheme("ace/theme/monokai")
```

**Comment by rocketinventor** [comment]
Thanks for the quick reply @nightwing.

I was able to get this to work in [JSBin](http://jsbin.com/yudires/edit?js,output) but not via code injection on the [Kitchen Sink page](https://ace.c9.io/build/kitchen-sink.html). What gives?

**Comment by nightwing** [comment]
kitchen-sink doesn't have global ace, `require("ace/config").setModuleUrl` should work, if thee theme is served via https

**Comment by rocketinventor** [comment]
I tried using Chrome's console to inject:
```
require("ace/config").setModuleUrl("monokai", "http://ajaxorg.github.io/ace-builds/src-noconflict/theme-monokai.js")
```

On the Ace Kitchen Sink page. It didn't work.

**Comment by nightwing** [comment]
It didn't work, but printed a new error right?

try 
```js
require("ace/config").setModuleUrl("ace/theme/monokai", "https://ajaxorg.github.io/ace-builds/src/theme-monokai.js")
editor.setTheme("ace/theme/monokai")
```

it needs to be loaded from https because non https scripts can't be loaded on https page, and it needs to load the normal version instead of no-conflict one, since on kitchen-sink.html there is no global `ace === require("ace/ace")`

**Comment by rocketinventor** [comment]
That worked well enough. However, I find that the previous theme seems to come back at random time intervals. Any ideas why?

Also, what changes need to be made to make this work with ide.c9.io?

**Comment by rocketinventor** [comment]
It did not print an error, it just returned the URL I gave it.

Per your suggestion, I tried:
```
require("ace/config").setModuleUrl("ace/theme/monokai", "https://ajaxorg.github.io/ace-builds/src/theme-monokai.js")
editor.setTheme("ace/theme/monokai")
```
However, while this method works initially, it seems to be a little finicky and randomly reverts to the previous theme. Is there anything that can be done about this?

Thanks!

**Comment by rocketinventor** [comment]
@nightwing How can I get this to code to work in [Cloud9 IDE](https://ide.c9.io)? As is, it doesn't work.

Thanks so much for your help so far!

**Comment by rocketinventor** [comment]
I'm closing this request (it works in vanilla ace) and reposting the last question (about Cloud9) as a separate issue with different wording since it's really more about C9 integration than it is about this specific issue.

Again, thanks!

**Comment by nightwing** [comment]
In cloud9 something like 
```
require.config({paths: { "ace/theme/Afterglow": "https://colorsublime.com/js/ace/build/src-min/theme-Afterglow"}})
services.settings.set("user/ace/@theme", "ace/theme/Afterglow") 
```
should work, if https version of the script is available

or you could copy-paste that file directly into your user script.

**Comment by rocketinventor** [comment]
I tried running:
```javascript
require.config({paths: { "ace/theme/Afterglow": "https://colorsublime.com/js/ace/build/src-min/theme-Afterglow.js"}});
services.settings.set("user/ace/@theme", "ace/theme/Afterglow");
```
However, "services" is not defined. Instead of anything happening, I just get:
`ReferenceError: services is not defined`

**Comment by nightwing** [comment]
`services` variable is defined in user scripts (use `Cloud9>Open Your User Script` menu item), if you want to experiment from commandline use `var services = window.app || apf.nameserver.lookup.all`
Post to https://community.c9.io/ or c9/core issue tracker with more information about what exactly you are trying to do, would help me to give you more useful answer :)
