### ISSUE TITLE
Incorrect prototype for EditSession.getMarkers return object

### ISSUE THREAD

**Issue by ahirschberg** [ajaxorg/ace#3173]
### Issue:
The documentation for `EditSession.getMarkers` [(link)](https://ace.c9.io/#nav=api&api=edit_session) states that it should return a JavaScript Array. However, it returns an "arraylike" plain javascript object instead, i.e. it's prototype is Object instead of Array. 

This is an issue for people using acejs in languages such as TypeScript or Dart, where the interop layer between the the target language and ace.js cannot convert the return type correctly.

**Comment by nightwing** [comment]
this is a bug in the documentation, it is supposed to return an object.

**Comment by ahirschberg** [comment]
Why wouldn't it return an array, though? It is, after all, giving you a list of markers with indicies.

Is it because the integer keys are the marker ids and not necessarily sequential? That makes sense, I didn't think about that
