### ISSUE TITLE
How do I help work on ace editor?

### ISSUE THREAD

**Issue by velara3** [ajaxorg/ace#3176]
I would like to help work on ace editor. I've checked out the repository locally and created a patch based on modifications. I would like to know the process to help more in the future. I've only worked on my own repositories so I would need beginners instructions on how to submit changes to the main branch. 

Note: I use SourceTree to work with git repositories.

**Comment by Dmitri-2** [comment]
This article has some of the basics: https://help.github.com/articles/fork-a-repo/
Look at the heading "Propose changes to someone else's project"

From a forked repo, once you make changes, push them back to your fork on Github. Then go to your forked repo page and submit a pull-request (to Ace). This will then allow ajaxorg members to look at and comment on your proposed changes.

**Comment by rocketinventor** [comment]
Bonus points:
Create an online demo of your code and share it in a pull request or Issue. These are very helpful to others for understanding what your code does and testing it manually.

**Comment by aryanbhasin** [comment]
I think this issue should be closed now

**Comment by monkeypunch3** [comment]
If I get this message that means I didn't fork it correctly? 

> Pushing to https://github.com/ajaxorg/ace-builds.git
> remote: Permission to ajaxorg/ace-builds.git denied.
> fatal: unable to access 'https://github.com/ajaxorg/ace-builds.git/': The requested URL returned error: 403
> Completed with errors, see above

**Comment by Dmitri-2** [comment]
Yes, you want to fork it to your repository on Github. (Look for the button "Fork" on the Ace-Builds repo page). Then change your local repo's remote url to:
 https://github.com/monkeypunch3/ace-builds.git
In general, a forked repo will always follow the form:
https://github.com/<USERNAME>/<REPO-NAME>.git
See this page for more info: https://help.github.com/articles/changing-a-remote-s-url/

This url will then push changes to your fork on github, and from there, you can do a pull request on the web page.
