### ISSUE TITLE
Capturing Ctrl-O in IE and extra Character

### ISSUE THREAD

**Issue by RickStrahl** [ajaxorg/ace#3179]
I use Ace and have a bunch of key bindings associated with the Editor, one of which is the Ctrl-O key which in Internet Explorer 11 normally opens a Open Document window. There are a number of annoying behaviors with this particular command depending on how you handle it, none of them perfect.

If I use some sort of UI with it like this:

```javascript
 editor.commands.bindKeys({
 "ctrl-o": function () { 
    alert("ctrl-o");
    return null;
},
... bunch of other bindings
});
```

the native IE dialog doesn't pop up. However, the editor will inject an extra `o` character into the editor after the function returns.

![image](https://cloud.githubusercontent.com/assets/1374013/21598661/86d58272-d104-11e6-9970-b29c8659bcce.png)

 I've tried all sorts of returns - no returns, return false, return true, return null. It doesn't make a difference I can't keep the `O` from inserting.

The other scenario is even worse. If no UI is shown the code runs but the IE dialog still pops up:

```javascript
 editor.commands.bindKeys({
 "ctrl-o": function () { 
    status("ctrl-o");   //  displays DOM content
    return null;
},
... bunch of other bindings
});
```

Here the IE new Document Window pops up.

![image](https://cloud.githubusercontent.com/assets/1374013/21598639/0073fb6e-d104-11e6-964c-2e64fcb2c06e.png)

This seems to be a specific issue with IE. Chrome and Firefox have no problem with this. In this case this is an application hosted inside of a Windows WPF application so no real good options other than IE11 in this case.

Is there some way to prevent the default behavior from firing in IE?

Alternately perhaps there is some way to explicitly force my code to eat the character? Or inject a backspace?

I realize this isn't really an Ace issue per se, but maybe some of you smart folks have run into this before and can propose a workaround.

**Comment by nightwing** [comment]
Unfortunately internet explorer doesn't allow overriding ctrl-o without alert, and it inserts extra o in textarea too.
Only way i could find for preventing that is to blur and focus the editor.
```js
editor.commands.bindKey("ctrl-o", function(editor) {
    editor.blur()
    alert(1)
    setTimeout(function() {
        editor.focus()
    })
})
```

Another approach would be to prevent ctrl-o from wpf

**Comment by RickStrahl** [comment]
Thanks. I tried to work with Ctrl-o in WPF but it doesn't have an effect on the behavior inside of the browser. Since the browser has focus it gets the event first so it fires there. 

Your idea of blurring the browser - if it works would actually work for me. I'll give that a shot. 

Thank you.

**Comment by RickStrahl** [comment]
Just to close the loop here - using `editor.blur()` and `setTimeout()` to refocus works well. I did have to bump the timeout a little (50) or occasionally it would still cause the Ctrl-o to inject.
