### ISSUE TITLE
Is it possible to use inline:true in the static highlighter?

### ISSUE THREAD

**Issue by clevertechie** [ajaxorg/ace#3182]
I'm trying to avoid using php tags in the static highlighter, is there any way I can accomplish this using similar way as an editor?

I tried this and it doesn't work -  session.setMode({path:"ace/mode/php", inline:true})

**Comment by nightwing** [comment]
what code do you use to run static highlighter?

**Comment by clevertechie** [comment]
This code:
var highlight = ace.require("ace/ext/static_highlight")
var dom = ace.require("ace/lib/dom")
function qsa(sel) {
    return Array.apply(null, document.querySelectorAll(sel));
}
qsa(".code").forEach(function (codeEl) {
    highlight(codeEl, {
        mode: codeEl.getAttribute("ace-mode"),
        //theme: codeEl.getAttribute("ace-theme"),
        theme: "ace/theme/dark_effect",
        showGutter: false
    }, function (highlighted) {
    });
});

**Comment by clevertechie** [comment]
I found the solution, in case anyone needs this:

var highlight = ace.require("ace/ext/static_highlight")
var dom = ace.require("ace/lib/dom")
function qsa(sel) {
    return Array.apply(null, document.querySelectorAll(sel));
}

qsa(".code").forEach(function (codeEl) {
    //codeEl.getSession().setMode({path:"ace/mode/php", inline:true}),
    highlight(codeEl, {
        //mode: codeEl.getAttribute("ace-mode"),
        //theme: codeEl.getAttribute("ace-theme"),
        mode: {path: "ace/mode/php", inline: true},
        theme: "ace/theme/dark_effect",
        showGutter: false
    }, function (highlighted) {
    });
});
