### ISSUE TITLE
How to check whether cursor is surrounded by parenthesis or curly braces or double quotes ?

### ISSUE THREAD

**Issue by yogitaAP** [ajaxorg/ace#3186]
While I am typing in the editor, I need to find out at a certain point whether the cursor is surrounded by parenthesis or quotes or curly braces. Is there a straight forward way to do so or I would have to write it.

**Comment by rocketinventor** [comment]
@yogitaAP What do you have in mind for this functionality? I could imagine a plugin for this being quite useful if you do have to write it.

**Comment by yogitaAP** [comment]
Alright, so here is the use case. Suppose, I need certain keys to work only when I am trying to type in a string. For example, I have restricted the paste functionality but when I am typing a string, I need the paste to work as it is. Second case can be for autocomplete. I have a certain list for function arguments and conditional identifiers and I need that list(autocomplete dropdown with that list) to appear only when I am typing inside parenthesis. In order to do so, I need to find out whether the current cursor is surrounded by curly braces or quotes or parentheses as the need be. 

However, if there is no such default functionality, I am willing to write one. I already wrote for parentheses. I would extend it to make it a generic plugin and then create a PR.

**Comment by nightwing** [comment]
Currently there is no straightforward and fast way to check this.
Hacky methods are used in several places like: 
https://github.com/ajaxorg/ace/blob/master/lib/ace/mode/behaviour/cstyle.js#L274-L275 https://github.com/ajaxorg/ace/blob/master/lib/ace/editor.js#L2022

**Comment by yogitaAP** [comment]
@nightwing Thanks, that helped. Although I wrote the similar thing for the parentheses, so I think I can extend it for quotes as well. Closing this here.
