### ISSUE TITLE
XML syntax error missing in duplicate ID

### ISSUE THREAD

**Issue by yuvalmorad** [ajaxorg/ace#3192]
<Image id="welcomeImageId" width="100%" height="100%" id="welcomeImageId" />

id appears twice w/o error indication

**Comment by boghyon** [comment]
Do you mean something like this?

    <Something
      id="myId"
      id="myId"
    />

**Comment by boghyon** [comment]
@andrewnester Can we reopen this too? This issue is also still reproducible. It is expected that there is a syntax error indication for duplicated attributes in a single node.

**Comment by andrewnester** [comment]
Realistically, we would like to put our focus on proper LSP support (https://github.com/ajaxorg/ace/issues/3124) instead of improving custom build specific workers including XML. I'll keep this open in case we'll decide to address it anyway
