### ISSUE TITLE
Remote debugger?

### ISSUE THREAD

**Issue by knightburton** [ajaxorg/ace#3193]
Hello there!
I'd like to know it would be hard to implement a javascript remote debugger around this powerful editor?
I want to create a simple site where I can connect to a device with websocket and I can manage the breakpoints and  variables.

**Comment by nightwing** [comment]
This is possible, and cloud9 does that https://github.com/c9/c9.ide.run.debug, but it is not very simple.

**Comment by knightburton** [comment]
Thank you for your answer.
