### ISSUE TITLE
Most of the themes appear to be the same?

### ISSUE THREAD

**Issue by cosleyppl** [ajaxorg/ace#3197]

**Comment by rocketinventor** [comment]
If the themes are appearing the same to you, perhaps you are not properly implementing them.
Could you provide more details?

**Comment by cosleyppl** [comment]
its fine, its just that work space themes seem very simmalar

**Comment by nightwing** [comment]
Seems like you are talking about something other than ace themes, cobalt, tomorrow themes, monokai, solarized, all look different.

**Comment by rocketinventor** [comment]
@cosleyppl Can you provide a theme name or screenshot?
