### ISSUE TITLE
Â inserted on wrapped lines

### ISSUE THREAD

**Issue by rexm** [ajaxorg/ace#3200]
After plugging in a basic implementation of [jsoneditor](https://github.com/josdejong/jsoneditor), with no customizations except overriding some CSS colors, we've found that ACE is indenting wrapped lines with `Â&nbsp;`. Here's a screenshot:
![image](https://cloud.githubusercontent.com/assets/141929/22601989/67943b14-ea0f-11e6-9b7a-446ec4ad0477.png)

Here is the DOM inspector view:
![image](https://cloud.githubusercontent.com/assets/141929/22602048/987b896c-ea0f-11e6-9b53-cf6d01bef64d.png)

It's not immediately obvious to us what's causing this. Any input is appreciated.

**Comment by nightwing** [comment]
looks like an issue with encoding, try adding ` <meta http-equiv="Content-Type" content="text/html; charset=utf-8">` to ensure it is loaded as utf8

**Comment by rexm** [comment]
Yep, thanks!
