### ISSUE TITLE
session.on('change') event fired twice, if object containing session is passed into function

### ISSUE THREAD

**Issue by jethrokuan** [ajaxorg/ace#3204]
I'm trying to write a library that binds ace-editor to sharedb. It seems that if I pass it an instance of an ES6 class, as so:
https://github.com/jethrokuan/sharedb-ace/blob/6594ad62ad6d614c446dae06e5ab02bba6391118/source/sharedb-ace-binding.js#L17

Then the 'change' eventHandler is fired twice. If `.bind(self)` is removed, then the change eventHandler is fired once, as expected.

However, I really need to pass the object in. Is there a workaround  or solution to this?

**Comment by jethrokuan** [comment]
Update:

It seems this causes the handler to be bound twice in the session object:
![7xxj1ub](https://cloud.githubusercontent.com/assets/1667473/22679717/26545340-ed3f-11e6-879c-fbef3c295a7a.png)

**Comment by nightwing** [comment]
maybe `self.session.on('change', self.onLocalChange.bind(self));` is called twice? Since that line passes a new function every time it is called, self.session.on can't prevent it from adding multiple listeners

**Comment by jethrokuan** [comment]
this was a silly mistake on my part, was calling `setup` from another file, which called that line twice. Should've second-guessed my code before second guessing Javascript xD

Thanks for the hint!
