### ISSUE TITLE
Going to c9 URL (https://c9.io/) freezes Firefox

### ISSUE THREAD

**Issue by victoriastuart** [ajaxorg/ace#3209]
Just  FYR:

Firefox 51.0.1 (64-bit)
Arch Linux x86_64
xfce4 DE

Going to your URL (https://c9.io/) completely freezes/locks up Firefox, early on static page loading.  I need to go into system manager and kill the Firefox PID, as it is completely unresponsive!  :-/

Not in issue in:

* Chrome Version 56.0.2924.87 (64-bit)
* Opera 43.0

https://c9.io

**Comment by nightwing** [comment]
Do you have any addons installed? I can't reproduce this on firefox on ubuntu

**Comment by victoriastuart** [comment]
Adblock Plus	2.8.2
Add Bookmark Here ²	48.0.20160817
All-in-One Gestures	0.26.1-signed.1-signed
Always Ask	2.1.2
Auto Reload	1.21
Clean Links	2.7.1-signed.1-signed
Cutyfox URL Shortener (bit.ly, is.gd, goo.gl)	1.4.1.1-signed.1-signed
Download Cleaner	1.6.0
Download Status Bar	15.0.0.1
Download YouTube Videos as MP4	1.8.9
Google Analytics Opt-out Browser Add-on	0.9.8
Google Scholar Button	1.1.1-signed.1-signed
LCD Clock	0.4.2.2
Multiple Tab Handler	0.8.2016111701
Pop-up Controller	0.9.1-signed.1-signed
Print Edit	17.6
Private Tab	0.2.1.1
Reddit Enhancement Suite	5.4.2
Session Manager	0.8.1.13
Small Tabs	1.1.1-signed.1-signed
Tab Mix Plus	0.5.0.2
uBlock Origin	1.10.6
Video DownloadHelper	6.2.0

**Comment by nightwing** [comment]
I could't find all the plugins, and with the plugins i tried it didn't freeze. Could you please try opening the site with plugins disabled or with a fresh firefox profile? Thanks!

**Comment by victoriastuart** [comment]
Hi!  Hesitantly, I was just about to restart Firefox, in safe mode.  However, I just (accidentially) clicked the https://c9.io/ URL (I meant to copy, not open it) AND that page opened, normally.

I don't understand why, but good that it did.

The only real change in my system (that I can think of) is that earlier today I added another addon (https://addons.mozilla.org/en-US/firefox/addon/web-developer/), and restarted Firefox.

Weird.  To be sure, I will restart Firefox now, and report back.
