### ISSUE TITLE
YAML Syntax checker

### ISSUE THREAD

**Issue by Quezler** [ajaxorg/ace#3212]
Would be nice to have.

**Comment by Justin-Maxwell** [comment]
Two years, two thumbs, two comments.  I is not hopeful :-(

**Comment by JeSuisUnCaillou** [comment]
I managed to extend the yaml mode with a syntax checker. I described the process in [this post](https://medium.com/@valentin.shamsnejad/how-to-add-yaml-syntax-validation-to-ace-editor-6db1dff4ab1b).

I don't know if it's worth a PR, you tell me ;)

**Comment by andrewnester** [comment]
Yaml linter has been added as part of this PR and will be released soon in a new Ace version https://github.com/ajaxorg/ace/pull/3979

**Comment by andrewnester** [comment]
Released in version 1.7.0
