### ISSUE TITLE
Ace editor show wrong symbol?

### ISSUE THREAD

**Issue by easytrader** [ajaxorg/ace#3215]
I use ace-editor:
```
var editor1 = ace.edit("editor1");
editor1.setTheme("ace/theme/twilight");
editor1.getSession().setMode("ace/mode/python");
editor1.setFontSize(15);
editor1.setValue("{{strategy.strategy}}");
```
and {{strategy.strategy}} is `def main():\n    print(\"leo\")` But the chrome will show some warning: 
![234523](https://cloud.githubusercontent.com/assets/15394723/22860870/3a3c25b8-f145-11e6-8e97-08d767350375.png)
Ace editor will show wrong symbol:
```
def main():
    print(&quot;leo&quot;)
```
Anyone know how to fix this?

Thank you very much.

**Comment by nightwing** [comment]
You need to properly escape  `strategy.strategy`  if you want to insert it into javascript string.
This question is not related to ace, try asking on forums for the templating framework you are using.

**Comment by easytrader** [comment]
I have printed `strategy.strategy` and it shows `def main():\n print(\"leo\")`.
So I don't know how to fix it.

Thank you.
