### ISSUE TITLE
Text not in sync with editor.getValue even after updateText() call

### ISSUE THREAD

**Issue by thememoryleaker** [ajaxorg/ace#3216]
We are using ace editor as the text editor for our collaborative editing tool. The operational transform bit seems to be working but the text as displayed in the editor is not in sync with the editor's value.

For instance:
![image](https://cloud.githubusercontent.com/assets/1296541/22963900/a32b2b08-f390-11e6-8f0d-2dad38fa181f.png)

The text in the editor is different from what is logged in the console. We added a updateText() call after applying the delta transformations. 

The session value is:
"
a
b
c
d
e
f
"

But the editor displays
"
a
b
c
d
d
f
"

**Comment by nightwing** [comment]
could you give me a link to the page where i can debug the issue? The description above doesn't contain nearly enough information to understand what is happening.

**Comment by jethrokuan** [comment]
@nightwing any way I can consult you right now? I can setup something temporary for you to try this out

**Comment by nightwing** [comment]
@jethrokuan you can write to amirjanyan@gmail.com

**Comment by thememoryleaker** [comment]
Hi, there is an example:
http://jsbin.com/gokewemuvi/1/edit?html,console,output

Just keep clicking add value. it adds new line to the front of the text

**Comment by nightwing** [comment]
the delta you use is wrong, it should be
```js
{"start":{"row":0,"column":0},
                    "end":{"row":1,"column":0},"action":"insert",
                    "lines":["",""]}
```
instead of `"end":{"row":0,"column":1},`
