### ISSUE TITLE
Indentation Issues When Setting Value from Hidden Text Area

### ISSUE THREAD

**Issue by mrobock** [ajaxorg/ace#3219]
I have multiple views, some with a single code editor and one with multiple. Each editor corresponds to a hidden field that contains the values/data I am setting the corresponding editor to (also binding a change listener).

Whenever a non-JSON field is updated and reloaded, everything in that field below the 1st line gets indented further.

Before save (already over-indented when loading from hidden field):
<img width="986" alt="screen shot 2017-02-16 at 5 21 22 pm" src="https://cloud.githubusercontent.com/assets/23323639/23048753/d2e69c56-f46c-11e6-9efa-200715f5c3a7.png">

After save (an additional indentation is automatically added):
<img width="994" alt="screen shot 2017-02-16 at 5 21 50 pm" src="https://cloud.githubusercontent.com/assets/23323639/23048754/d4fe6582-f46c-11e6-8c0a-78cc94f97e4e.png">

Additionally, with ERB (HTML_Ruby) key words don't seem to get auto-indented after the first line. Please see images below...

Example 1:
<img width="610" alt="screen shot 2017-02-16 at 9 16 00 am" src="https://cloud.githubusercontent.com/assets/23323639/23032224/98acbfb4-f428-11e6-8722-c927c0a4cfdd.png">

Example 2:
![image](https://cloud.githubusercontent.com/assets/23323639/23032014/ea282bb8-f427-11e6-8aae-55aa06e943e8.png)

Please let me know if there is any additional information that I can provide to aid in solving these issues. Thank you.

**Comment by nightwing** [comment]
the second one is a known issue, autoindent/outdent is not supported for erb mode.
The first issue must be caused by your code, ace doesn't change the string you pass to it in setValue, i can help to debug if you show a page where the issue happens

**Comment by mrobock** [comment]
Sorry for the very delayed response. For the first issue I figured out it was due to HAML. We fixed by using :preserve. Bummer on the second issue but thanks for the clarification.
