### ISSUE TITLE
"--��� ���� ����(��Ŭ��)" Text distorts the entire selection size

### ISSUE THREAD

**Issue by miyakedev** [ajaxorg/ace#3221]
Hi, I have a certain amount of LUA files and all of them have the symbol "�" so selecting it distorts the entire selection size.

Image : http://image.prntscr.com/image/0d98f2a67c4442b19257c4606969022b.png

**Comment by nightwing** [comment]
looks like these files are not encoded in utf8, and ome characters are replaced with invalid character mark �.
Not handling non monospace characters like �, is a known limitation for now. Merging this into https://github.com/ajaxorg/ace/issues/460
