### ISSUE TITLE
tags "<",  ">" after include with mode c_cpp (c, c++) disapears

### ISSUE THREAD

**Issue by miyakedev** [ajaxorg/ace#3224]
I try put
include <windows.h>

and my output is ;
"include "

Any Solution? (Mode : c_cpp)

**Comment by arvindpdmn** [comment]
Did you find a solution to this? Thx

**Comment by miyakedev** [comment]
Its because in HTML the tag of <windows.h> are converted to <window></window>
I prevent it with a BBCode
