### ISSUE TITLE
documentation not clear on which ace.js file to use

### ISSUE THREAD

**Issue by samayo** [ajaxorg/ace#3231]
I installed ace editor using `yarn add ace-code-editor` and it downloaded many many files, folders, sub files and sub folder with multiple ace.js files. 

Exactly, which one do I need to have the editor? The doc says, "just copy one of src*" but there is no src folder.

**Comment by nightwing** [comment]
ace-code-editor contains unbuilt files from this repository,  readme snippet you quote is about ace-builds repository, and npm module with the same name

**Comment by samayo** [comment]
Is there any way to 'build' it? So, I can hae as minimum number of file as possible?

**Comment by BlakeBrown** [comment]
Second this

**Comment by nightwing** [comment]
There is https://github.com/ajaxorg/ace-builds/blob/master/src-min/ace.js, including all modes, themes and workers into that file would make it too large.

But you may like https://github.com/thlorenz/brace

**Comment by samayo** [comment]
@nightwing Thanks for sharing. I may be mistaken but the ace.js file is only `346 KB`. Unless I am missing something, that isn't as large as I though it would be, if it contains 'everything'. 

Anyway, I like both alternatives.

**Comment by BlakeBrown** [comment]
Thanks @nightwing 

I was mostly confused why the files were being hosted in `ace-builds` and not in the main repository, I think that should be clarified in the readme.

 I appreciate the browserify suggestion!
