### ISSUE TITLE
Prevent line break at start of code

### ISSUE THREAD

**Issue by miyakedev** [ajaxorg/ace#3232]
I want trim the spaces

Example 

My Code = "BREAK_SPACE
BREAK_SPACE
BREAK_SPACE
include <window.h>
BREAK_SPACE
public Form1() {
}
BREAK_SPACE"

Output = "include <window.h>

public Form1() {
}"

I use the settings like this : editor.setTheme("ace/theme/chrome");

**Comment by nightwing** [comment]
Do you want a command to remove spaces from the start or a way to do that when calling ace.edit?
If it is the later, use `editor.setValue(code.trim())`, if it is the former, moving cursor to the start of document and using `ctrl-delete` should work.
