### ISSUE TITLE
display: flex; doesn't highlight correctly

### ISSUE THREAD

**Issue by geddski** [ajaxorg/ace#3235]
Is there a way to configure Ace to set all CSS properties to be the same color? For example I'd like the "flex" to be the same color as other properties. 

![image](https://cloud.githubusercontent.com/assets/515722/23921663/154b1bb4-08c5-11e7-90bf-af07f35577f5.png)

**Comment by geddski** [comment]
it looks like ACE is considering "flex" to be a property rather than a value, since it's also possible to use the same word as a property: `flex: 1 0 auto;`. Is there a way to fix this?

**Comment by DontShootMe** [comment]
```javascript
{
    token : "text",
    regex : "flex(?!((\\s*:)|-))"
}
```

add this rule in the file :  ace/lib/ace/mode/css_highlight_rules.js
 to `this.$rules = {`
in the the section : ` "ruleset" : [`

or try it online at : [Mode Creator](https://ace.c9.io/tool/mode_creator.html?mode=css&document=css)

it should do the trick ...

**Comment by geddski** [comment]
Awesome thanks !
