### ISSUE TITLE
Ace damages the clipboard on first focus on Chromium 57 / Linux with clipboard manager

### ISSUE THREAD

**Issue by icarito** [ajaxorg/ace#3237]
Upon entering the editor, I can't paste my clipboard buffer, instead I get this character: 

It only happens the first time I focus the control.

It works fine in Firefox.

I was using xfce4-clipman with clipboard synchronization on. I disabled this feature as a workaround.

**Comment by icarito** [comment]
More info: The clipboard is affected by simply focusing the editor. Not paste or copy is necessary. Just focus once on the editor and then, trying to paste into any application returns a SOH / Ctrl-A character.

**Comment by nightwing** [comment]
on which OS do you see this? Is this about primary, or middle click clipboard?

**Comment by icarito** [comment]
Hi Harutyun,

This is running on Debian Testing, with XFCE desktop.

This is about the primary clipboard.

Thanks for looking into it!

**Comment by icarito** [comment]
More info,
This was with ace-builds 1.2.6 from npm. I just built 1.2.6 from release files myself and issue persists. Will test with master branch.

**Comment by icarito** [comment]
This looks like it has something to do with `xfce4-clipman` a bit like the report here: https://japhr.blogspot.pe/2013/03/ace-editor-does-good-job-of-managing.html
Disabling clipman seems to avoid the issue although I don't have clipboard syncronization active.

**Comment by icarito** [comment]
I'm changing the issue name accordingly to latest discovery.

**Comment by icarito** [comment]
Similar behaviour with running under Sugar Desktop Environment, which is a learning environment for children. Sugar has a clipboard manager that is not under the control of the user. The effect here is that once a text is "copied", the clipboard buffer gets emptied (not always? sometimes it's possible to copy/paste).

**Comment by nightwing** [comment]
https://github.com/ajaxorg/ace/pull/3635 fixes the issue with primary keyboard on chromium
