### ISSUE TITLE
Dirty status change event

### ISSUE THREAD

**Issue by flaub** [ajaxorg/ace#324]
I'm currently approximating when a document is dirty by digging into the undo manager and checking if hasUndo() is true. It would be more convenient to have a 'changeDirty' event fire whenever the document changes from having edits since the last load. 

It also appears that the 'change' event is firing out to embedder's code before the internal library has a chance to finish processing the event. My hack right now is to use a timer. How about having internal vs public events?
@gissues:{"order":64.59627329192563,"status":"backlog"}

**Comment by vanillajonathan** [comment]
The `isClean()` and ` markClean()` methods are undocumented.

UndoManager.markClean() is undocumented #2719 
UndoManager.isClean() is undocumented #2715
