### ISSUE TITLE
es6 spread causes syntax highlighting to fail

### ISSUE THREAD

**Issue by jonmann20** [ajaxorg/ace#3240]
Hello, I reported this to cloud9 and they sent me here.

![screenshot-uploads intercomcdn com 2017-03-20 15-36-24](https://cloud.githubusercontent.com/assets/2007099/24118159/366489da-0d83-11e7-8ce5-bf3a1fd5736b.png)

**Comment by nightwing** [comment]
Hi,
could you give the full text of file (or minimal text reproducing the issue), and tell for what mode does it happen.
I don't see it in .js file.

**Comment by jonmann20** [comment]
Apologies, I am no longer able to reproduce this consistently.  I am now just occasionally getting no syntax highlighting, but I suspect this to be a separate issue not related to es6 code.  I will report a new bug if I have more info.  Closing...
