### ISSUE TITLE
Chess pieces unicode characters are not interpretted as double-wide

### ISSUE THREAD

**Issue by Rush** [ajaxorg/ace#3248]
Paste this into ace editor;
```
♜♞♝♛♚♝♞♜
♟♟♟♟♟♟♟♟
♙♙♙♙♙♙♙♙
♖♘♗♕♔♗♘♖
```
Probably this would need to be extended:
https://github.com/ajaxorg/ace/blob/master/lib/ace/layer/text.js#L324

Could we use the wcwidth project to fix it for all double-wide characters https://github.com/mycoboco/wcwidth.js/tree/master ?

**Comment by icarito** [comment]
Strange, in my case it looks to me like those characters are handled correctly, but these aren't:
```
🂡🂢🂣🂤🂥🂦🂧🂨🂩🂪🂫🂬🂭🂮 
🂱🂲🂳🂴🂵🂶🂷🂸🂹🂺🂻🂼🂽🂾
🃁🃂🃃🃄🃅🃆🃇🃈🃉🃊🃋🃌🃍🃎
🃑🃒🃓🃔🃕🃖🃗🃘🃙🃚🃛🃜🃝🃞
```

**Comment by icarito** [comment]
Sure related to https://github.com/ajaxorg/ace/issues/460

**Comment by icarito** [comment]
There appears an unmerged patch is available at https://github.com/ajaxorg/ace/pull/2002 I wonder if it affects this.

**Comment by Rush** [comment]
Unfortunately this looks very heavy https://github.com/ajaxorg/ace/pull/2002/files#diff-5f7daffa9ef63e3751f46e374df96831R359

**Comment by JamesRDouglas** [comment]
The character ① appears to not be interpretted as double width either

**Comment by andrewnester** [comment]
This relates to this issue, so closing as a duplicate https://github.com/ajaxorg/ace/issues/460
