### ISSUE TITLE
Autocomplete is not working after dash

### ISSUE THREAD

**Issue by zation** [ajaxorg/ace#3252]
Please check this plunker: http://plnkr.co/edit/PVaREEYtgFQHrZjwnJTq?p=preview
We have 4 cases:

```js
const abc = 1;
-a;
+a;
/a;
*a;
```

When I press `ctrl` + `space` after `+a`, `/a`, `*a`, the autocomplete is working and show `abc`. But when I press `ctrl` + `space` after `-a`, there is no autocomplete suggestion display.
Seems ace editor treat `-a` as a single word. How can I make `-` same as `+` and make the autocomplete working?
Thanks!

**Comment by joaocraveiro** [comment]
@zation were you able to solve this? I'm having the exact same issue.

**Comment by sim-ahr** [comment]
Did this ever get solved/fixed?
