### ISSUE TITLE
[website] "Support" button selected style looks different from the rest in navigation menu

### ISSUE THREAD

**Issue by btzy** [ajaxorg/ace#3256]
On the main horizontal navigation menu of the [Ace editor homepage](https://ace.c9.io/), the "Support" button (rightmost on the menu) looks different when selected as compared to the other buttons.

Here is how a normal button looks like when selected:

![capture4](https://cloud.githubusercontent.com/assets/6948096/24616461/bd9b73d2-18c3-11e7-9cbf-3f6a08f304a1.PNG)

Here is how the "Support" button looks like when selected:

![capture5](https://cloud.githubusercontent.com/assets/6948096/24616537/038d32d6-18c4-11e7-9dff-85d24d3427e0.PNG)

The normal button looks like it has some inset box-shadow, with the background at the border areas being slightly darker than the middle.  The "Support" button doesn't have it.

This is the case for both Chrome 57 and Firefox 52, and likely the case for other browsers too.

**Comment by nightwing** [comment]
fixed in https://github.com/ajaxorg/ace/pull/3266
