### ISSUE TITLE
Content Security Policy Support

### ISSUE THREAD

**Issue by jamesarosen** [ajaxorg/ace#3260]
ACE inserts several inline `<style>` tags into the `<head>`. For example, the [virtual renderer imports `ace_editor.css`](https://github.com/ajaxorg/ace/blob/master/lib/ace/virtual_renderer.js#L49) and [themes import their own CSS](https://github.com/ajaxorg/ace/blob/4c7e5eb3f5d5ca9434847be51834a4e41661b852/lib/ace/theme/clouds_midnight.js#L38).

This is a problem for pages that want to run a Content Security Policy. Those inline `<style>` tags must have either a nonce (generated by the server, which `ace.js` wouldn't possibly know about) or a hash.

I don't have a clear suggestion, but here are some ideas:

 1. Offer a build of ACE that doesn't add any `<style>` tags to the DOM, but instead exposes them on the filesystem so application authors can include them via `<link>` tags or  `@import` directives.
 2. Provide some sort of manifest of hashes of all the CSS that ACE provides so application authors can add them to their CSP headers.
 3. Host ACE CSS files on a CDN and add `<link>` tags referencing them instead of `<style>` tags.

**Comment by jamesarosen** [comment]
Chrome, as of version 46, [no longer supports](https://developer.chrome.com/extensions/contentSecurityPolicy#relaxing-inline-script) the `unsafe-inline` option because it's too broad an attack vector, so that isn't an option.

[OWASP](https://www.owasp.org/index.php/XSS_(Cross_Site_Scripting)_Prevention_Cheat_Sheet#RULE_.234_-_CSS_Escape_And_Strictly_Validate_Before_Inserting_Untrusted_Data_into_HTML_Style_Property_Values) has some good information about why inline `<style>` tags are dangerous.

**Comment by jamesarosen** [comment]
I've calculated hashes for

 * [ace_editor.css](https://github.com/ajaxorg/ace/blob/4c7e5eb3f5d5ca9434847be51834a4e41661b852/lib/ace/virtual_renderer.js#L49) (`XYBtnr/s6KimmpqYM4EDrs1C2bYyBk40b3LwJcrAv8s=`)
 * [ace-tm](https://github.com/ajaxorg/ace/blob/4c7e5eb3f5d5ca9434847be51834a4e41661b852/lib/ace/theme/textmate.js#L39) (`Dn0vMZLidJplZ4cSlBMg/F5aa7Vol9dBMHzBF4fGEtk=`)
 * the [error_marker CSS](https://github.com/ajaxorg/ace/blob/4c7e5eb3f5d5ca9434847be51834a4e41661b852/lib/ace/ext/error_marker.js#L182) (`sA0hymKbXmMTpnYi15KmDw4u6uRdLXqHyoYIaORFtjU=`)
 * [ace-tomorrow-night](https://github.com/ajaxorg/ace/blob/4c7e5eb3f5d5ca9434847be51834a4e41661b852/lib/ace/theme/tomorrow_night.js#L38) (`0U0G1g5NVv9EirSrnNcK2svBrTzHeoUjWt4/Vcf/iuY=`)

That silences the errors while initializing the library.

But when ACE renders text, it uses `.innerHTML = ...` with a string that often includes a `style='...'` attribute. For example, in [`ace/layer/marker`](https://github.com/ajaxorg/ace/blob/4c7e5eb3f5d5ca9434847be51834a4e41661b852/lib/ace/layer/marker.js#L96) and [several methods in `ace/layer/text`](https://github.com/ajaxorg/ace/blob/4c7e5eb3f5d5ca9434847be51834a4e41661b852/lib/ace/layer/text.js). These cannot be whitelisted even with a SHA256 hash of the `style='...'` contents.

It may help to create `HTMLElement`s and set their `style` properties instead of using `innerHTML` to build up DOM.

**Comment by nightwing** [comment]
The two workarounds for css issue are relatively straightforward to implement, however stopping use of innerHtml is a major change which we can't implement quickly

**Comment by jamesarosen** [comment]
> however stopping use of innerHtml is a major change which we can't implement quickly

Is that something you'd be interested in, though? It's not something we've prioritized yet, but our team might be able to work on this. Improving XSS protection is very important to us.

**Comment by nightwing** [comment]
I have a prototype for removing innerHTML at https://github.com/ajaxorg/ace/pull/3372/files, unfortunately that branch is slower than v1.2.8 when running scroll benchmark from https://github.com/ajaxorg/ace/blob/master/tool/perf-test.html.
If you know a way of optimizing dom calls or know a better way to benchmark, please let us know.

**Comment by cgx** [comment]
I'll definitely try the *use-dom-api* branch. Thanks!

If ACE offers CSP support, it would be an advantage over the alternative solutions like [CodeMirror](http://codemirror.net/).

**Comment by lol768** [comment]
> If ACE offers CSP support, it would be an advantage over the alternative solutions like CodeMirror.

Absolutely. 

Are there any plans to extend the work in https://github.com/ajaxorg/ace/pull/3609 to the marker layer too, @fjakobs?

**Comment by nightwing** [comment]
@lol768 #3609 removed all uses of innerHTML, now we only need to find a solution for css.

**Comment by jamesarosen** [comment]
> now we only need to find a solution for css

While `style='foo: bar;'` is a security risk, `el.style.foo = 'bar'` should not be and is allowed by even strict Content Security Policies.

**Comment by nightwing** [comment]
@jamesarosen i mean solution for style elements, both providing hashes and creating separate css files require too much changes. Would a solution using nonce-* work for you? Something like:

```
"Content-Security-Policy": "default-src 'self' 'nonce-111'; style-src  'nonce-<secretNumber>'"`
```
```js
ace.config.set("cspToken", <secretNumber>)
ace.edit(...)
```

so that Ace can set `style.nonce` when creating the element in https://github.com/ajaxorg/ace/blob/master/lib/ace/lib/dom.js#L191

**Comment by jamesarosen** [comment]
From [the CSP level 2 spec](https://w3c.github.io/webappsec-csp/2/#script-src-the-nonce-attribute),

> If the policy contains a nonce-source expression, the server MUST generate a fresh value for the nonce-value directive at random and independently each time it transmits a policy. The generated value SHOULD be at least 128 bits long (before encoding), and generated via a cryptographically secure random number generator. This requirement ensures that the nonce-value is difficult for an attacker to predict.

> Note: Using a nonce to whitelist inline script or style is less secure than not using a nonce, as nonces override the restrictions in the directive in which they are present. An attacker who can gain access to the nonce can execute whatever script they like, whenever they like. That said, nonces provide a substantial improvement over 'unsafe-inline' when layering a content security policy on top of old code. When considering 'unsafe-inline', authors are encouraged to consider nonces (or hashes) instead.

Because nonces have to be generated on every request, it's not possible to put
```js
ace.config.set("cspToken", <secretNumber>)
```
in a separate `.js` file. It would have to be in the including HTML:
```js
<script type='application/javascript' nonce='nonceA'>
ace.config.set('cspToken', nonceB)
</script>
```

But an attacker who can read `ace.config` then has access to that value and could use it to execute code on the page.

**Comment by jithurjacob** [comment]
@jamesarosen - Is it recommended if we use 'unsafe-hashes' CSP directive along with sha values in csp header? This removed the console errors but I'm trying to understand the security implications.

style-src 'self' 'unsafe-hashes' 'sha256-gixU7LtMo8R4jqjOifcbHB/dd61eJUxZHCC6RXtUKOQ=' 'sha256-Dn0vMZLidJplZ4cSlBMg/F5aa7Vol9dBMHzBF4fGEtk=' 'sha256-sA0hymKbXmMTpnYi15KmDw4u6uRdLXqHyoYIaORFtjU=' 'sha256-MQjIdoaT+4ud/MEvS1P0oGESZb94X2E976aC2zlTfhs=' 'sha256-RzT6TL2rZ3eEL4w6JRWbjfrEKHyhByWPGY7quYXzQ8k=';

**Comment by jamesarosen** [comment]
`unsafe-hashes` is the escape hatch so the engineer can tell the browser "I know what I'm doing is a security risk; you don't need to report it." If you use it, you need to include the SHA values in the header.

> Whenever you see the prefix unsafe in a CSP keyword, that means that using this is not the most secure way to go. It is better to refactor your code to avoid using HTML event handler attributes (such as onload, onclick, onmouseover etc.)

https://content-security-policy.com/unsafe-hashes/ has more information. Note that only Chromium 69+ and Edge 79+ have support for this directive currently. Other browsers will continue to report the violations.
