### ISSUE TITLE
Help on snippets

### ISSUE THREAD

**Issue by tarokker** [ajaxorg/ace#3261]
Hi all,
I'm trying to implement simple snippets rules but I have problem even with the simplest (i'm using latest Ace release).

For example, I want to write a snippet when user writes something that starts with "funct":

```
regex //funct.*$/
snippet f
	function(${1:functionName})($2) {
	}

```

When I back to the Ace editor, when I write "funct" and then press tab, the snippet correctly appears, but when I press tab again, in order to jump to the $2 point, It looks like Ace is pasting the snippet again and again. For example, with funct + tab + tab + tab, I got this:
```
function(functionName)() {
})() {
})() {
}
```

I guess I'm doing something wrong with regex and I should skip the snippet if it's already pasted, but I can't figure how :(
Anyone can help?

Thanks in advance for your time.

**Comment by nightwing** [comment]
Hi
what​ do you want that regex to do?
Currently it replaces the whole line if there is a funct string before the
cursor.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Без
вирусов. www.avast.ru
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by tarokker** [comment]
well, that's exactly what I would like to achieve :)
But after pressing tab the first time (it inserts the snippet correctly on the first tab), if I continue to press tab, it continues to paste the snippet, instead of navigation through the two insertion points. I guess I should include some sort of guard in the first part of the regexp?

**Comment by nightwing** [comment]
after expanding the snippet the first time it still matches the regex so it
expands again.

Before
https://github.com/ajaxorg/ace/commit/2b10c2071ffffcc2841b0c6265d0155d739904cd
ace was not expanding snippets inside other snippets, perhaps this should
be changed to be an option, or a property on the snippet/tabstop

Could you tell a bit more about why do you want to replace the whole line?

**Comment by tarokker** [comment]
Sorry if mine is not the best approach, I'm still newbie with Ace :)
Ideally i would like to let user press "tab" and receive quickly the matched snippets, what's the suggested way to achieve this? (what are the options? instead of replace the whole line I mean).

**Comment by nightwing** [comment]
> Ideally i would like to let user press "tab" and receive quickly the
matched snippets,

the question is what do you consider matched. Should
funct bar bar|
with cursor at the end of line match snippet of funct?


​

**Comment by tarokker** [comment]
I would like to match when user presses tab and the cursors is at the end of the string "funct" (or functi, or functio, or function) and before "funct" i would like to allow only spaces or tabs.

For example:
<begin of line>funct<tab> match
<begin of line><space or tab>funct<tab> match
<begin of line>function<tab> match
<begin of line>bla bla funct<tab> no match

Please forgive me for artistic pseudo regexp!

**Comment by nightwing** [comment]
try
```
# Prototype
regex /^\s*/funct(i(on?)?)?/
snippet f
function(${1:functionName})($2) {
}
```

**Comment by tarokker** [comment]
it's working perfectly !
thanks a lot for the tip for your time
