### ISSUE TITLE
Highlight bug

### ISSUE THREAD

**Issue by w3suli** [ajaxorg/ace#3270]
Highlight bug:

"-webkit-animation:", "@keyframes myfirst" and "25%, 50%, 75%, 100%" is wrong highlight

![bug](https://cloud.githubusercontent.com/assets/20889555/25066993/349ada74-2236-11e7-9e98-5ce6520100a5.png)

**Comment by BigChief45** [comment]
I don't think `-webkit` style definitions are supported. A lot of other editors don't support this either.

**Comment by w3suli** [comment]
![bug-comment](https://cloud.githubusercontent.com/assets/20889555/25107555/7101bfd2-23d0-11e7-9fa8-50d68a3b0e63.png)

0% highlighting ok. 25%, 50%, 75%, 100% highlighting not ok.

(CodeMirror supported -webkit-, -ms-, -o-, -moz-) No highlighting of -webkit-. Highlighting animation properties.

**Comment by w3suli** [comment]
Original sublime text highlight:
![orig](https://cloud.githubusercontent.com/assets/20889555/25156809/5aba2ebc-249d-11e7-8720-43d9cc1d417f.png)

**Comment by nightwing** [comment]
Please try the version from https://github.com/ajaxorg/ace/pull/3275 at https://rawgit.com/ajaxorg/ace/mode-issues/kitchen-sink.html and let us know what do you think, it does not exactly match sublime but should be better that what we have now.

**Comment by w3suli** [comment]
Almost good, but the percentage sign is still wrong.

![bug](https://cloud.githubusercontent.com/assets/20889555/25317313/eae38dc6-2876-11e7-9ad1-15d98e1822e0.png)

**Comment by w3suli** [comment]
I found the cause of the mistake!
![bug](https://cloud.githubusercontent.com/assets/20889555/26030004/ce9aeabe-3844-11e7-9cc1-2b308dd479e1.png)
Recognition of blocks bounded by brackets is bad!

**Comment by nightwing** [comment]
should be fixed now, thanks fro reporting issue, and testing
