### ISSUE TITLE
Multiple cursor remain after undoing snippet insertion

### ISSUE THREAD

**Issue by TheMegaTB** [ajaxorg/ace#3272]
When inserting a snippet that utilizes multiple cursors like
```
\begin{${1:equation}}
  % body...
\end{${1:equation}}
```
and then undoing this action the second cursor remains whilst the snippet is gone resulting in a misplaced 
second cursor. These are some screenshots below that correspond to the above snippet:

First the snippet is inserted.
![img-2017-04-16-112134](https://cloud.githubusercontent.com/assets/5037967/25070158/1a76b7b0-2297-11e7-99fc-4cfd4e03c2cc.png)
![img-2017-04-16-112146](https://cloud.githubusercontent.com/assets/5037967/25070156/1a74225c-2297-11e7-859f-416539219a84.png)
Then I used CTRL+Z to undo this operation.
![img-2017-04-16-112155](https://cloud.githubusercontent.com/assets/5037967/25070157/1a764410-2297-11e7-86bf-e4954c978a90.png)
As you can see the text `counter{` in line 18 is selected after the undo operation, which is in the same position as the snippet was beforehand.

**Comment by nightwing** [comment]
fixed in 1.3.3, thanks for the report.
