### ISSUE TITLE
modifying storage.type as text goes

### ISSUE THREAD

**Issue by DxCx** [ajaxorg/ace#3273]
Hey,

I'm using ace editor as part of a page,
i have AST Parser running on the code inside,
so i'm generating a list of "known types" outside the editor.
now i want to inject them into the editor and append them as storage.type,
i was looking at the API and couldn't find a way how i can update type list from `editor.getSession()`

any ideas?

**Comment by thabo104** [comment]
you must first go to github.com and register github acc and you will get
api tutourials

**Comment by DxCx** [comment]
Well, i am clearly registered to github :)
Where i can find the api tutorials mentioned?
