### ISSUE TITLE
what means "Error: state doesn't exist"

### ISSUE THREAD

**Issue by phisu** [ajaxorg/ace#3274]
i try to use ace for my project. when i insert a code in my formel editor, i get an error, which i do not understand.  my setup of my formel editor is:
```js
		   textareaCalc = $('textarea.formelEditor');

		   var editDiv = $('<div>', {
		       position: 'absolute',
		       width: textareaCalc.width(),
		       height: textareaCalc.height(),
		       'class': textareaCalc.attr('class')
		   }).insertBefore(textareaCalc);
		   formelEditor = ace.edit(editDiv[0]);

		   formelEditor.setOptions({
		       showGutter : true,
		       showLineNumbers : true,
		       showInvisibles :true,
		       fontSize : 15,
		       mode : "ace/mode/javascript",
		       highlightActiveLine: true,
		       theme : "ace/theme/chrome"
		   });
```

and when i insert, i get in the console the error "Error: state doesn't exist"

if ($test < 3.5) { 50 }

what does it mean?

**Comment by nightwing** [comment]
state doesn't exist can mean that the mode is broken https://github.com/ajaxorg/ace/blob/master/lib/ace/tokenizer.js#L292.
But i can not reproduce the issue on https://ace.c9.io, when pasting `if ($test < 3.5) { 50 }` . Could you please create a demo demonstrating the issue, or try to reproduce it on https://ace.c9.io

**Comment by nightwing** [comment]
Closing, but please comment if you still see the issue.
