### ISSUE TITLE
Handling width of checkbox symbol correctly

### ISSUE THREAD

**Issue by johot** [ajaxorg/ace#3276]
When using the following text in ace the selection gets offset and is not rendered correctly, try this in ace using the font Consolas 14 px for example

Sample:
`☐ I have something to do!`
`☐ Buy milk`

Now try selecting the text or moving the charet close to the square symbol and you will see that the rendering is slightly off.
Can it be fixed somehow?

Thank you!

**Comment by 12Me21** [comment]
All non-ascii characters have the same effect
