### ISSUE TITLE
Ace modelist in rails

### ISSUE THREAD

**Issue by amitojsingh** [ajaxorg/ace#3278]
Hello developers,
I am trying to set mode for random files by using this! 
http://stackoverflow.com/questions/15903191/how-to-automatically-pick-a-mode-for-ace-editor-given-a-file-extension
But it's not working in my case no output is shown! 
Is the require link is correct? or something else is the problem! 
TIA

**Comment by nightwing** [comment]
Did you load ext-modelist.js file after ace.js?

**Comment by amitojsingh** [comment]
nopes i just included 
//=require ace-rails-ap
in my application.js 
as shown here
https://github.com/codykrieger/ace-rails-ap
what else I have to do?

**Comment by nightwing** [comment]
you need to somehow load https://github.com/codykrieger/ace-rails-ap/blob/master/vendor/assets/javascripts/ace/ext-modelist.js, but i don't know how to do that with rails, authors of ace-rails-ap may know more.

**Comment by amitojsingh** [comment]
Done thanks! 
I just load it using 
`//=require ace/ext-modelist.js`
in Application file! Thanks @nightwing
