### ISSUE TITLE
Chrome opens autofill

### ISSUE THREAD

**Issue by rawsh** [ajaxorg/ace#3284]
Chrome is opening auto fill inside ace:

![screenshot from 2017-04-27 11-18-14](https://cloud.githubusercontent.com/assets/7035671/25494395/2487afd8-2b3f-11e7-944c-190a185458f2.png)

**Comment by nightwing** [comment]
Does this happen in https://ace.c9.io/ too? do you have any extensions installed?

**Comment by rawsh** [comment]
@nightwing looks like it's just happening on that website. I think the problem is jquery qtip which is used for other things on the website.
