### ISSUE TITLE
Sometimes the enter key to create a new line won't work

### ISSUE THREAD

**Issue by rBok6** [ajaxorg/ace#3285]
Hi!

I've been testing Ace editor on my windowsphone 8.1 with Internet explorer 11 and sometimes when I'm editing HTML code and I want to go down a new line by hitting the enter key the editor wont do nothing it just gets stuck. I have to delete like two characters for the enter key to work again. any ideas why this might be happening and how can i fix it?

**Comment by nightwing** [comment]
This should be fixed by https://github.com/ajaxorg/ace/pull/3635, please let us know if you still can reproduce this on http://ace.c9.io. Thanks.

**Comment by rBok6** [comment]
Hi! I tried to reproduce the issue with the latest version (1.4.2) and it seems like there's a more annoying bug now. When I try to start typing the editor puts 1 character per line and it leaves a blank break line between characters. Even if I try to reposition de cursor to where I want the text to appear it just keep doing the same . I'm using internet explorer 11 on Windows phone 8.1.

**Comment by nightwing** [comment]
Could you please try enabling "Text Input debugger" from the sidebar, pressing backspace several times, and giving me the result from log area
![image](https://user-images.githubusercontent.com/341801/50424342-b60fd000-087b-11e9-84bb-ae6739998d61.png)

**Comment by rBok6** [comment]
Also the native "copy" from internet explorer is difficult to use with the editor. I has to take a screenshot, sorry.

**Comment by rBok6** [comment]
Also the native "copy" feature from internet explorer is difficult to use within the editor. I had to take a screenshot, sorry.

![error editor](http://html5games.xtgem.com/images/editor1.png)
