### ISSUE TITLE
Wrong annotation line is set

### ISSUE THREAD

**Issue by Neill83** [ajaxorg/ace#3287]
Hi,

using the setAnnotations() method you have to define a row. The row is not set correctly. When I do the following:

```
editor.setAnnotations([{
                                                        row: 85,
                                                        text: 'custom message here',
                                                        type: 'error',
                                                        column: 0
                                                    }]);
```

Then the annotation is set to row 86 instead of 85...

Is this a bug or a feature? :P 

Greetings

**Comment by nightwing** [comment]
This is a feature, row is 0 based, but numbers on gutter start with 1 to match other editors.
As a workaround you can use `editor.setOption("firstLineNumber", 0)`

**Comment by Neill83** [comment]
no i can't use that option... it won't fit my data from the response... i got an error on line 85, so it must be shown on 85 and not on 86. If I use that option than all text is moved 1 line down and won't be the same as in other editors.

**Comment by Neill83** [comment]
Thanks, i was working with that "workaround".

Could you check [this](https://github.com/ajaxorg/ace/issues/2629) please?

Thanks a lot.
