### ISSUE TITLE
[CSS]Emmet snipetts enhance on Cloud9 Editor

### ISSUE THREAD

**Issue by harapeko** [ajaxorg/ace#3288]
Can you Emmet snipetts enhance on Cloud9 Editor?
Perhaps it does not correspond to recent snippets.
e.g.
https://docs.emmet.io/cheat-sheet/

ex)
BAD
```
d:g
↓expand
display: ruby-text-group;
```

GOOD
```
d:f
↓expand
display: flex;
```

**Comment by nightwing** [comment]
The emmet in cloud9 was updated sometime this summer, thanks for bringing this issue into attention, and sorry for not updating issue when it was fixed.

**Comment by harapeko** [comment]
thx!!! d>w<b
