### ISSUE TITLE
highlightLines() highlights the wrong lines

### ISSUE THREAD

**Issue by sancarn** [ajaxorg/ace#3290]
I have the below code:

    editor.on("guttermousedown", function(e) {
        var target = e.domEvent.target; 
        if (target.className.indexOf("ace_gutter-cell") == -1)
            return; 
        if (!editor.isFocused()) 
            return; 
        if (e.clientX > 25 + target.getBoundingClientRect().left) 
            return;
        if (e.domEvent.button != 2)
            return;

        var row = e.getDocumentPosition().row;
        if(e.editor.session.getBreakpoints()[row]==undefined){
            e.editor.session.setBreakpoint(row);
            e.editor.session.highlightLines(row,row,'ace_breakpoint-line')
            console.log(e)
        } else {
            e.editor.session.clearBreakpoint(row);
            var markers = e.editor.session.getMarkers()
            for(var key in markers){
                if(markers[key].clazz == "ace_breakpoint-line"){
                    if (markers[key].range.start.row == row && markers[key].range.end.row == row){
                        e.editor.session.removeMarker(markers[key].id)
                    }
                }
            }
        }
        //e.domEvent.srcElement.appendChild()
        e.stop();
    })

When using highlightLines() no matter which row I select, the highlighted line will always be the first line... Either I am doing something incorrect or this is a bug of some sort?

**Comment by nightwing** [comment]
add `.ace_breakpoint-line {position: absolute}` css rule

**Comment by sancarn** [comment]
Right! Thant did the trick!
