### ISSUE TITLE
Additional spaces before cursor position when typing

### ISSUE THREAD

**Issue by brxue** [ajaxorg/ace#3295]
Hi,

It looks like, if the lang attribute of html element is set to "zh-CN", then there will be additional white spaces appear before the cursor position when typing. To be accurate, there will be 3 or 4 spaces.

Here is a JSBIN link that can reproduce this issue, the sample code is just copied from the demo page inside ace-builds,

http://jsbin.com/jiliguv/edit?html,css,output

My current work around is to add "lang='en'" to the div element where ace works on, and it works fine.

The browser I used is Firefox, using html lang='zh-CN' works fine for Chrome,

Thanks,
Brian

**Comment by nightwing** [comment]
Hi
i can't reproduce this behavior with chrome 58 on windows 7, tried both with english and chinese keyboard layouts.

**Comment by brxue** [comment]
@nightwing , I used Firefox, no issue found on Chrome.

**Comment by nightwing** [comment]
No, tried with firefox 53 on windows7 and 52 on mac. Do you have any firefox addons installed?

**Comment by brxue** [comment]
@nightwing I used Firefox 45.7.0 on CentOS 7, it has addons like Tile Tabs, and several others shown in below figure,

![screenshot from 2017-05-24 21-03-54](https://cloud.githubusercontent.com/assets/1690204/26404490/cb178dec-40c4-11e7-89fd-5cf801d41c98.png)
