### ISSUE TITLE
Catch re-throw dead code

### ISSUE THREAD

**Issue by kylekatarnls** [ajaxorg/ace#3298]
Hi, I'm studying your code in order to send a pull-request for #2118 and I found this pattern that sounds like dead code to me:
```js
try{
  do_something();
} catch (err) {
  throw new Error(err);
}
```
It occurs several times. What's the point in catch an error, wrap it in an error and throw it again?

**Comment by nightwing** [comment]
Hi,  where did you find that pattern?

**Comment by kylekatarnls** [comment]
3 in this file: https://github.com/ajaxorg/ace/blob/9200b313b9923abc28c40cf597571106328de4a0/lib/ace/ext/menu_tools/generate_settings_menu.js#L134

**Comment by nightwing** [comment]
yeah, that doesn't make sense, code in that file needs to be refactored.
Are you planning to make localizations for setting names?

**Comment by kylekatarnls** [comment]
Yes, I know it's a while, but I could now take some time to that. I will separately propose a try-cacth cleanup pull request.
