### ISSUE TITLE
add vue.js syntax support

### ISSUE THREAD

**Issue by ajayashuba** [ajaxorg/ace#3300]

**Comment by nightwing** [comment]
would it be enough to simply add vue file extension to list of extensions supported by  html mode https://github.com/c9/core/blob/master/node_modules/ace/lib/ace/ext/modelist.js#L94
Or does vue.js contain some special syntax, not covered by normal html mode?

**Comment by BigChief45** [comment]
I think HTML mode works exactly the same.
