### ISSUE TITLE
Not able to display hibernate inputHidden value or object.parameter value as content 

### ISSUE THREAD

**Issue by nitishsoni9493** [ajaxorg/ace#3305]
Trying to display hibernate input hidden content in ace editor code section. 
Similar issue with hibernate pojo content in ace editor

**Comment by nightwing** [comment]
what is`hibernate input hidden `?

**Comment by nitishsoni9493** [comment]
jsf/html library <H:inputHidden id="" value="#{object.value}">

**Comment by nightwing** [comment]
if you mean you put that string into html and then call ace.edit,you need to escape the html.
If you mean something else, please create a demo showing the isseue
