### ISSUE TITLE
allow users to enable / disable blinking cursor

### ISSUE THREAD

**Issue by kevinushey** [ajaxorg/ace#3306]
Some users prefer not to have a blinking cursor in their editors. It would be nice if Ace provided a mechanism (option?) for allowing users to explicitly disable blinking for their cursor.

It looks like the blinking state of the cursor is managed through e.g.

    editor.renderer.$cursorLayer.setBlinking(value);

However, its use is currently mostly internal to Ace, and is done to manage the blinking state during mouse drags and drops; e.g.

```
$ ag -Q "setBlinking"
layer/cursor.js
81:    this.setBlinking = function(blinking) {

mouse/dragdrop_handler.js
110:            editor.renderer.$cursorLayer.setBlinking(true);
268:            editor.renderer.$cursorLayer.setBlinking(false);
284:            editor.renderer.$cursorLayer.setBlinking(!editor.getReadOnly());
351:        this.editor.renderer.$cursorLayer.setBlinking(!this.editor.getReadOnly());
362:        editor.renderer.$cursorLayer.setBlinking(false);
```

That is, the cursor blinking is temporarily stopped during a drag, then restarted when that drag ends. It'd be nice if the usages here respected some global Ace option for disabling cursor blinking as well.

**Comment by nightwing** [comment]
there is a `cursorStyle` option. try setting it to `wide`.

**Comment by kevinushey** [comment]
Aha, I totally missed that and this appears to be the right solution. Thanks!
