### ISSUE TITLE
`data:` should not be used.

### ISSUE THREAD

**Issue by codeofnode** [ajaxorg/ace#3307]
The following says use of `data:` is risky

[https://security.stackexchange.com/a/95011](https://security.stackexchange.com/a/95011)
[https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy) > CSP in workers > 2nd para

There are tons of data:image used across the css of ace.

Can we avoid use of `data:`?

**Comment by dimovpetar** [comment]
Any update on this? `data:` blocks adoption of CSP Level 2 https://www.w3.org/TR/CSP2/#directives "In either case, developers SHOULD NOT include either 'unsafe-inline', or data: as valid sources in their policies."

**Comment by nightwing** [comment]
What is the alternative to using data for images in a js library? 

One possible solution may be to keep data for the default configuration but generate separate css and png files to allow people using strict csp, to load the styles separately. Would this solution work for you?

**Comment by dimovpetar** [comment]
Hello @nightwing , if I understand your proposal is to make it configurable - either choose between `data:` and internal styles in the head, or load images and css from separate? If this is it, then it works for me.

I have prepared this jsbin to demonstrate the problem https://jsbin.com/xapovafuce/edit?html,css,js

**Comment by vdh** [comment]
I've had to use a quite fragile patch (via Yarn patch) to patch out the data URLs both in `ace.js` for `blankImage.src`, as well as override the various `background-image` data URLs for the CSS files. It's quite the pickle that this sort of limitation on image assets is baked directly into the file like that.
