### ISSUE TITLE
YAML multiline highlighting should ignore colon

### ISSUE THREAD

**Issue by letmaik** [ajaxorg/ace#3309]
```yaml
after_success:
  - >
    if [[ "`git log -n 1 --pretty=format:'%d'`" =~ "tag: v" ]]; then
       pip install twine ;
       ...
```

GitHub rendering 05/06/2017:
![image](https://cloud.githubusercontent.com/assets/530988/26802399/49d52bae-4a38-11e7-8b9d-869aff866674.png)

Everything in the `>` multiline block should be highlighted the same color, but it seems that the `:` gets picked up and changes the highlighting. I haven't checked if this is fixed in a newer ACE version other than the one used by GitHub.

**Comment by nightwing** [comment]
https://github.com/ajaxorg/ace/pull/3275/commits/1168fdd728f193c4b7e4290695d166ca55ae3280 fixes this issue in ace, but AFAIK ace is not used for highlighting code in github comments.

**Comment by letmaik** [comment]
You're right, I got mislead somehow. For YAML, GitHub uses https://github.com/atom/language-yaml for highlighting (from this list: https://github.com/github/linguist/blob/master/vendor/README.md).

**Comment by letmaik** [comment]
Just for reference, the original grammar which is used by atom and also GitHub (and VS Code) has an issue for that filed already: https://github.com/textmate/yaml.tmbundle/issues/17
