### ISSUE TITLE
Foundation's normalize.css breaks some ace styles

### ISSUE THREAD

**Issue by tjhiggins** [ajaxorg/ace#3312]
We use Foundation which includes normalizing global styles which breaks ace styles for search/replace. Probably not fair to call this a bug, but I think it would be good to add more explicit styles to search/replacebtn classes to avoid issues with other libraries. 

With foundation.css: http://imgur.com/dsEBMNN
Without foundation.css: http://imgur.com/hctyW8c
Demo: https://jsfiddle.net/TJHiggins/260n6e0s/

https://cdnjs.cloudflare.com/ajax/libs/foundation/6.3.1/css/foundation.css

**Comment by nightwing** [comment]
https://github.com/ajaxorg/ace/pull/3313 should fix this
