### ISSUE TITLE
Ctrl-N not working in emacs/Firefox

### ISSUE THREAD

**Issue by ronburk** [ajaxorg/ace#3319]
https://ace.c9.io/build/kitchen-sink.html
Use Firefox, select 'emacs' as your keyboard handler, type "ctrl-N". It opens a new browser window instead of moving to the next line.

Without knowing much about it, I naively wonder if a call to "preventDefault()" is missing.

This problem is mentioned in #2503 but is clearly not the point of that report, so it seemed OK to open it as a distinct issue.

**Comment by nightwing** [comment]
Unfortunately firefox tries to copy everything chrome does including the bugs https://bugzilla.mozilla.org/show_bug.cgi?id=1291706. the event for ctrl-n is never sent to the webpage similar to chrome https://bugs.chromium.org/p/chromium/issues/detail?id=119881.

**Comment by ronburk** [comment]
Thanks, I knew Chrome had gone this way, but not Firefox. Unfortunately, this makes it unlikely one can do good editor emulation in JavaScript. In this particular case, Ctrl-N is one of the most-used keystrokes in Emacs. Rats.
