### ISSUE TITLE
Docs typo? ace.require is not a function

### ISSUE THREAD

**Issue by miqmago** [ajaxorg/ace#3320]
I've seen in docs to use `ace.require` but it actually does not exist.

Instead I'm using `ace.acequire` and all works fine :)

**Comment by nightwing** [comment]
sounds like you using a modified version of ace, there is only ace.require https://github.com/ajaxorg/ace/blob/master/lib/ace/ace.js#L66 in ace

**Comment by miqmago** [comment]
Thanks!  I'm using `react-ace` (which internally uses `brace`)
