### ISSUE TITLE
setvalue appears to cause blur event

### ISSUE THREAD

**Issue by ronburk** [ajaxorg/ace#3323]
I'm using ace in multiple small areas of the screen, so expect to generally manage the input focus globally myself. After getting inexplicable behavior, I stripped away more and more code until I was left with the conclusion that "setValue" may generate a 'blur' event, which appears both undocumented and (to me) completely unexpected. For example, in this example, the console claims a blur event occurred after you load the page, even if you don't click anywhere on the page.
```html
<!-- -*- mode: web; -*- -->
<!doctype html>
<html>
    <head>
        <meta charset="utf-8" >
        <style>
         .editor
        </style>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.6/ace.js" integrity="sha256-xrr4HH5eSY+cFz4SH7ja/LaAi9qcEdjMpeMP49/iOLs=" crossorigin="anonymous"></script>
        <script type="text/javascript">
         window.onload = function(){
             let editor = ace.edit("editor");
             editor.on('blur', function(event){
                 console.log("blur");
             });
             editor.on('focus', function(event){
                 console.log("focus");
             });
             editor.focus();
             editor.setValue("some text");
         };
        </script>
    </head>
    <body>
        <div id="editor"  class="editor" style="height: 100px;">
            some text
        </div>
        <div id="other" style="min-height: 100px; width:300px; border: 2px solid black">
            Click here!
        </div>
    </body>
</html>
```
This does not occur if the call to setValue is changed to `editor.setValue("some text", 1);` The documentation for that function both marks the second argument as "required", and specifies what happens if it is not supplied. One or more code examples pass only a single argument, so I assume that is not viewed as illegal.

**Comment by nightwing** [comment]
I can't reproduce the issue using chrome on mac. On which browser/OS do you see it.
The second argument to setValue is optional, it controls selection after setValue call, by itself setValue can't cause blur event, but perhaps browsers restore focus differently depending on wether something is selected in the textarea or not.

**Comment by ronburk** [comment]
This is Firefox 53.0.3 (64-bit) running on Windows 7. Also Firefox 54.0 (64-bit) on Ubuntu 16.04.  Can't repro on Windows 7 IE 11 (though that's the first time I used their debugger, so...). OK, will pursue as a browser "feature". Thanks!
