### ISSUE TITLE
namespace aware XML theme 

### ISSUE THREAD

**Issue by alainpannetier** [ajaxorg/ace#3324]
I haven't found any previous issue here regarding this.
Would be useful for instance for XSLT and a whole lot of other things.

I'm OK to do it but would need some hint about how to do it 'first-time-right'.

**Comment by nightwing** [comment]
@alainpannetier could you elaborate what do you mean, 
what should this syntax mode do, and are there any other editors supporting this?

**Comment by alainpannetier** [comment]
Sorry, I apparently missed your comment.

1/ Could you elaborate
Ideally, the tags 
<xsl:template> <xsl:...>
Would have a different highlighting than the tags of say the default namespace
<p> <ul>
... to take a simple example.
Obviously, this is hard to solve in a generic way because there is no limit on the number of name spaces in an XML document. A reasonablly simple JSF2 page can easily have 5 namespaces.
However, most cases are not that hard to support. 

2/  are there any other editors supporting this?
Eclipse does. But that's a bit of a stretch. This is because the XSL syntax highlighting preferences subclass the XML highlighting preferences. In other word, the XSL syntax highlighting rules will only apply to the xsl namespace. For the other tags, even from non default name spaces, the XML syntax highlighting will apply.
Eclipse's XML editor completion is names space aware as well of course.
May be a similar strategy can be applied, but honestly I don't know where to start. I've looked into this a long time ago because I liked the javascript colouring in the SVG mode and I seem to recall modes inherit from one another, but I stopped researching the topic altogether.

**Comment by alainpannetier** [comment]
I moved on.
