### ISSUE TITLE
fat arrow syntax coloring es6

### ISSUE THREAD

**Issue by jaacko-torus** [ajaxorg/ace#3325]
I was wondering if fat arrow syntax was gonna get colored any time soon.

```js
function x(m) {
    console.log("hey");
}

var x = function(m) {
    console.log("hey");
};

var x = (m) => {
    console.log("hey");
}
```

The first two are classic so it's awesome that they get colored, but I still thin it would be the awesomest if the third one had coloring as well(minor detail, the variable and the parameter have different colors)

**Comment by andrewnester** [comment]
Released in 1.13.2
