### ISSUE TITLE
ctrl+f resets selection

### ISSUE THREAD

**Issue by schoonc** [ajaxorg/ace#3327]
https://ace.c9.io/build/kitchen-sink.html

1. Select any text in the editor (keyword `function` for example)
2. Press ctrl + f.
3. A searchbox appears, but the selection in the editor is reset.

In addition, sometimes the selection on the current word disappears, but appears on some other word (at the moment of pressing ctrl + f)

The problem appeared after the update from 1.2.6 to 1.2.7

**Comment by nightwing** [comment]
https://github.com/ajaxorg/ace/pull/3329 should fix this
