### ISSUE TITLE
Find with the editor text selection not working

### ISSUE THREAD

**Issue by divat** [ajaxorg/ace#3328]
I was trying to find a text within a selection using ctrl+f in ace editor but it's not working.
Is there any shortcut commands to find the text in a selection ?

**Comment by divat** [comment]
Anybody have idea on this.
Suggest me the idea.

**Comment by nightwing** [comment]
https://github.com/ajaxorg/ace/pull/3329 should fix this

**Comment by divat** [comment]
@nightwing Does it works for you ?

**Comment by divat** [comment]
@nightwing I have the selected the text from editor and triggered the find(ctrl+f) by selecting the 'Search In Selection' option. It's not highlighting the text in selected range

**Comment by nightwing** [comment]
you need to press ctrl f, select text, click the `S` button.
After that search will be limited to the range that was selected.

**Comment by divat** [comment]
@nightwing I'm using src-noconflict javascript files. I have updated the #3329 code in ext-searchbox.js.
Based on above comment i have tried but i'm getting error like below in console,
TypeError: _this.activeInput is undefined[Learn More]  ext-searchbox.js:221:17
ReferenceError: MAX_COUNT is not defined[Learn More]  ext-searchbox.js:412:9

**Comment by divat** [comment]
@nightwing Are you displaying the count from a selection ?
Why don't we highlight only the finding's from the selection ?
Suggest me if you have idea on this.
