### ISSUE TITLE
Include comment in line like Git editor in commits

### ISSUE THREAD

**Issue by urionlinejudge** [ajaxorg/ace#3330]
Does ace has in its API an easy way to include comments in a line, by clicking like on its number? I know it is possible to include messages to a line to mark errors and warnings, but is it somehow possible to do it live, with an input box for instance?

**Comment by nightwing** [comment]
You could use line widgets to implement this, similar to https://github.com/ajaxorg/ace/blob/master/lib/ace/ext/error_marker.js

**Comment by nightwing** [comment]
Closing but please let me know if the above comment didn't answer your question
