### ISSUE TITLE
Undefined tooltipNode in Autocomplete blur listener

### ISSUE THREAD

**Issue by schmuli** [ajaxorg/ace#3331]
In PR #3266, as part of a fix for Issue #3233, the code of the Autocomplete's blurListener method was changed.

Whereas before it was just comparing `e.relatedTarget == this.tooltipNode`, the new code is calling `this.tooltipNode.contains(e.relatedTarget)`. However it is possible for `this.tooltipNode` to still be null/undefined, and this causes a TypeError.

Please see https://github.com/ajaxorg/ace/blob/master/lib/ace/autocomplete.js#L146 for reference.

### Steps to Reproduce
1. While the editor has focus, press any key (I used `f`)
2. The Autocomplete popup should now be visible
3. Use the mouse to click anywhere outside the editor
4. The `blurListener` will be called but `this.tooltipNode` is still `undefined`

**Comment by nightwing** [comment]
Fixed in https://github.com/ajaxorg/ace/pull/3332/files.
Thanks for the detailed bug report!

**Comment by schmuli** [comment]
Thank you for the rapid response and fix.

What is your release schedule for 1.2.8?

**Comment by nightwing** [comment]
Released today https://github.com/ajaxorg/ace-builds/releases/tag/v1.2.8
