### ISSUE TITLE
Highlight occurences of a keyword only in source. Not in comments

### ISSUE THREAD

**Issue by ManojkumarV** [ajaxorg/ace#3338]
Selecting a word highlights all the occurrences of that word in the file including comments for a function etc. But the end user need is only to highlight occurrences of the word only in source and not in comment areas. For example eclipse shows highlighting in the mentioned logic.
Is to possible to achieve this?

**Comment by nightwing** [comment]
IDEs usually have both highlighting of selected word, and highlighting of variable instances.

The variable highlight needs not only to exclude the comments, but also variables with the same name in other functions, so its implementation depends on language, and is outside of scope of Ace.

Ace only provides the simple selected world highlight similar to what sublime text and notepad++ do.

Here's how variable highlight is implemented in cloud9 https://github.com/c9/core/blob/1134d72259aa71a83b586351766c71cfa2d6535f/plugins/c9.ide.language.jsonalyzer/worker/highlight_occurrences.js#L18, https://github.com/c9/core/blob/1134d72259aa71a83b586351766c71cfa2d6535f/plugins/c9.ide.language.javascript/scope_analyzer.js#L743, but unfortunately it works for very few languages, and is too complicated to include in ace, if you know a better way of implementing this ideas are welcome.

**Comment by nightwing** [comment]
Closing as this does not look like something that can be added to ace.
But if you have suggestions on how to implement this, or are not convinced by my comment above, please comment.
