### ISSUE TITLE
Preserve current view when resizing editor horizontally?

### ISSUE THREAD

**Issue by kevinushey** [ajaxorg/ace#3339]
When word wrapping is enabled and an Ace editor instance is resized, the currently viewed lines 'shift' around, e.g.

![soft-wrap](https://user-images.githubusercontent.com/1976582/28034008-ce09f8d6-6564-11e7-8ae3-901ecbe6ad89.gif)

Does Ace by any chance provide an API that ensures that the current view is preserved when resizing the editor surface? (By preserved, I mean roughly ensuring that the top line visible in the editor remains visible as the editor is resized).

In the example above, I would like to see line 159 remain in view at the top of the screen even as the editor surface is resized, and lines are wrapped to form new 'screen' lines.

**Comment by nightwing** [comment]
currently there is no built-in mechanism to do this, since editor uses scrolltop as the 'source of truth' for scroll position, we probably should use some combination of first visible line, last visible line, and cursor if it is visible.
