### ISSUE TITLE
Rich TEXT editing in ACE editor is missing 

### ISSUE THREAD

**Issue by InfantAnto** [ajaxorg/ace#3340]
Now i am working in ACE editor . Please advice me on how to add rich editing option( tool bar with bold,italic etc.,) in ace editor by any third party plugin or using the default way in ACE editor.

**Comment by nightwing** [comment]
Are you asking about bold etc in markdown mode? Or want to display bold text in the editor?

**Comment by InfantAnto** [comment]
Hi nightwing,
I am asking for formatting options toolbar like CKeditor. Do you know how to add this?

**Comment by nightwing** [comment]
Ace doesn't support displaying rich text.

**Comment by InfantAnto** [comment]
![rich_editing](https://user-images.githubusercontent.com/29863092/28112877-2f7b4656-6718-11e7-9e79-22be39fa2980.png)

I need like the above. Is there any way to do this via any third party JS files?

**Comment by InfantAnto** [comment]
@nightwing Are you an employee in ACE ?

**Comment by nightwing** [comment]
What should the toolbar do?
How will user assigned formatting interact with the code coloring?
How would ace store the formatting?

**Comment by InfantAnto** [comment]
I am not using ACE editor for code syntax. Just to get the text using ACE editor. We have using text mode only , not asked any programming syntax. Need to get complaint from users in a project.
Users can format their comments. We get the content and mail it. No need for storing.

**Comment by InfantAnto** [comment]
I think now you can understand my point of view. Any way to add the formatting options?

**Comment by nightwing** [comment]
Why do you want to use ace for this instead of other rich text editors? Ace was not written for this usecase.

**Comment by InfantAnto** [comment]
@nightwing Thanks for your reply to make me clear on rich text editing is not supported by ACE editor. Now i have switched to CKEditor.

**Comment by nightwing** [comment]
There are many other rich text editors too, e.g. https://prosemirror.net/ looks pretty good.

**Comment by taf2** [comment]
@nightwing but does it support vim keybindings?

**Comment by nightwing** [comment]
@taf2 i think no, but it should be possible to create an api adapter similar to the one in ace or https://github.com/replit/codemirror-vim for prosemirror too.

**Comment by ninbit** [comment]
Hello, I will be using Ace editor for LaTeX highlighting, but I also want to add a Rich Text feature. For example, there will be buttons on top of the editor for Bold, Italic, Underline, Listing, etc. When we click on these buttons, the selected text will be surrounded by its LaTeX equivalent, for example, \textbf{} for bold. You can think of this as a kind of markdown.

How can I achieve this in the easiest and most error-free way? Firstly, there should be a function that examines the user's selection (whether the user has made a selection, selected the LaTeX code, selected the text, or selected both the LaTeX code and the text, etc.). Without such a function, the LaTeX code will likely produce errors. Is there a library available for this?

You can refer to Overleaf's rich text editor as an example:
https://www.overleaf.com/blog/new-overleaf-v2-features-rich-text-and-adding-linked-files

**Comment by nightwing** [comment]
@ninbit see this example which adds such buttons for markdown using using snippets  https://mkslanc.github.io/ace-playground/#toolbar
