### ISSUE TITLE
Completion dropdown menu bug

### ISSUE THREAD

**Issue by maxless** [ajaxorg/ace#3341]
I have the following code in my completer:
```
          completions.push({
            score: 1000,
            name: "getItem(id: Int)",
            value: "getItem()",
            meta: "method"
            });
```

Upon hitting the Ctrl-space, I see a dropdown with "getItem()    method" item and pressing Enter will insert "getItem()" into the code. So it looks like the dropdown menu always takes the string from the "value" field both for the dropdown menu display and for the inserted code. How would I make it display "getItem(id: Int)     method" but insert "getItem()" instead?

```
          completions.push({
            score: 1000,
            name: "getItem()",
            value: "getItem(id: Int)",
            meta: "method"
            });
```
Trying this instead shows the "getItem(id: Int)     method" and inserts "getItem(id: Int)" into the code.

**Comment by nightwing** [comment]
use 

```js
        completions.push({
            score: 1000,
            caption: "getItem(id: Int)",
            value: "getItem()",
            meta: "method"
        });
```
where did you find the name property, it is not used in ace?

**Comment by maxless** [comment]
Okay, looking through my browser history, must be from here:
https://github.com/ajaxorg/ace/issues/1966

Thanks. Is there an API reference for completion support? I couldn't find it anywhere, just some articles and examples in the documentation.
