### ISSUE TITLE
CTRL + Shift + Backspace keybinding does not work

### ISSUE THREAD

**Issue by doakey3** [ajaxorg/ace#3342]
Most text editors I use allow the user to press this keyboard short cut to erase all pre-cursor text of the current line:

CTRL + Shift + Backspace

This functionality does not work in ACE.

**Comment by nightwing** [comment]
Which text editors do that? Ace uses alt-backspace for similar effect https://github.com/ajaxorg/ace/blob/master/lib/ace/commands/default_commands.js#L559, but we can add CTRL + Shift + Backspace too, if there are many editors with that shortcut.

**Comment by doakey3** [comment]
This keyboard shortcut works on [notepad++](https://notepad-plus-plus.org/), [geany](https://www.geany.org/), and most <textarea> regions in html (including the ones for submitting issues)

**Comment by nightwing** [comment]
On which os and browser does Ctrl + Shift + Backspace work in <textarea>? I don't see it on windows

**Comment by doakey3** [comment]
Wow! You're right. I was using [Arch Linux](https://www.archlinux.org/) with Firefox before, but on Windows 7 with Firefox I don't see it in the <textarea>. However, the shortcut does work in geany in both operating systems. It is also present in notepad++ on Windows. 

At any rate, it appears the keyboard shortcut exists for some editors and I know of no other function associated with the combo so I don't think you'd be stepping on anyone's toes by adding it in.  

Thanks for the awesome work. ACE looks like a great project.

**Comment by nightwing** [comment]
The attached pr adds this as an aliases for remove to indentation, let me know if you think this should be deleting until column 0 instead.

> I don't think you'd be stepping on anyone's toes by adding it in.

One can never know for sure, it's better to double-check before changing keybindings :)

Thanks for taking the time to report the issue, and answering my questions!

**Comment by doakey3** [comment]
I think it should be deleting until column 0 instead because this is the behavior I see in notepad++ and Geany.
