### ISSUE TITLE
< symbol converting into &lt; in script tag

### ISSUE THREAD

**Issue by PavanKallur** [ajaxorg/ace#3344]
any suggestions

**Comment by nightwing** [comment]
> any suggestions

try to formulate your question in a more readable way, provide a code example showing what you are trying to do, and what doesn't work, search on google, do not open same issue twice.

if your question is: `how to convert < into &lt;` and you are using php, try [`htmlspecialchars`](http://php.net/manual/en/function.htmlspecialchars.php)

**Comment by PavanKallur** [comment]
I have implemented ace html, so need to add jquery script with < condition,
so its converting into &lt;
