### ISSUE TITLE
Highlight php without requiring opening "<?php" tag

### ISSUE THREAD

**Issue by kjdion84** [ajaxorg/ace#3348]
How do I do this?

Example code I'm using (via [jquery-ace](https://cheef.github.io/jquery-ace/))

    $('#php_code').ace({
        theme: 'chrome',
        lang: 'php',
        width: '100%',
        height: '200px'
    });

**Comment by kjdion84** [comment]
Nvm: https://github.com/ajaxorg/ace/issues/2542

**Comment by nightwing** [comment]
you can use the method from https://github.com/ajaxorg/ace/issues/2542#issuecomment-111288259

```
session.setMode({path:"ace/mode/php", inline:true})
```

with jquery-ace it would be something like
```
$('.my-code-area').ace().data("ace").editor.session().setMode({path:"ace/mode/php", inline:true})
```

but it would require a newer version of ace than the one included on jquery-ace website.
