### ISSUE TITLE
Unable to scroll page vertically when pointer in ace editor

### ISSUE THREAD

**Issue by danqing** [ajaxorg/ace#3350]
I'm having the exact same issue as #1629. It's a 4 year old issue so I thought I should open a new one.

Basically I have an ace editor that can scroll horizontally but not vertically (few but long lines). If I use trackpad (or touch on mobile) to scroll vertically, ace intercepts the scroll and the page can't move.

Is there a way to either adjust the threshold (of vertical vs. horizontal scroll) or disable vertical scroll altogether?

Thanks!

**Comment by danqing** [comment]
Wonder if @nightwing has any insight into this. Thanks!

**Comment by nightwing** [comment]
@danqing the touchmove handler in https://github.com/ajaxorg/ace/blob/master/lib/ace/mouse/default_handlers.js#L269 is very simplistic, it needs to better detect scroll direction, and the number of fingers touching

**Comment by danqing** [comment]
Does that include trackpad events too?

**Comment by nightwing** [comment]
AFAIK trackpad doesnot fire special events, so wheel handler above will be called,
But the issue seems to be the same even a tiny movement in x direction is treated as scroll that can be handled by ace, and the event is stopped.

**Comment by danqing** [comment]
I see.

So basically there are two things:

1. Increase the delta. It looks like now you can scroll both X and Y at the same time. It will be a lot easier if we just allow one at a time - say you go over 30 degree, then we allow you to scroll horizontally, etc.
2. If ace can't be scrolled on one direction, don't allow the scroll. That is, suppose I can only scroll to the right, then scrolling to the left should be bubbled to the browser.

**Comment by nightwing** [comment]
Implementing this turned out to be trickier than i expected at first.
@danqing could you take a look at the version from https://github.com/ajaxorg/ace/pull/3401 and see if the issue is fully fixed or not with it

You can try it online at https://rawgit.com/ajaxorg/ace/touch-scroll/demo/scrollable-page.html

**Comment by danqing** [comment]
Yes! Seems to be totally fixed. Thanks @nightwing !
