### ISSUE TITLE
Set the bookmark on corresponding line

### ISSUE THREAD

**Issue by divat** [ajaxorg/ace#3351]
Hey Team,
How to set the bookmark on ace editor and keep it highlighted until i jump back to the specified bookmark.

Is this feature already available in ace editor ?

Could anybody give me the suggestion on this ?

Thanks,
Diva

**Comment by divat** [comment]
Anybody have idea on bookmark option inside ace editor

**Comment by nightwing** [comment]
Ace doesn't have a bookmark feature.
You can use editor.revealRange method to jump to cursor, and use anchors to keep track of bookmark positions as document is edited
