### ISSUE TITLE
Attempting to extend highlighting rule other than text_highlight_rules results in error

### ISSUE THREAD

**Issue by judocode** [ajaxorg/ace#3355]
Using the examples in the docs, and using the CDN version of Ace, it shows how to extend highlighting using the text_highlight_rules, but when I attempt to extend anything else (it seems, eg. html_highlight_rules or liquid_highlight_rules), they are all undefined when I attempt to import them. Is there an issue here or do you have to pull in the entire ace-builds repo to get this to work?

**Comment by nightwing** [comment]
In ace-builds, there is no real require, so only modules that are already loaded are accessible.
If you load ace.js and mode-html.js, your mode can use html_highlight_rules.
Alternatively you can use this repository with require.js
