### ISSUE TITLE
pgSQL mode syntax highlighting

### ISSUE THREAD

**Issue by crosstocci** [ajaxorg/ace#3360]
White-space before a statement removes its syntax highlighting:

![screenshot_20170721_121151](https://user-images.githubusercontent.com/24857334/28474338-edf6548a-6e0d-11e7-91f4-2d8d807c1d25.png)

**Comment by nightwing** [comment]
Interesting, this seems to be have done intentionally https://github.com/ajaxorg/ace/blob/master/lib/ace/mode/pgsql_highlight_rules.js#L493

@desoi do you remember why the "^" in the regex was needed? sublime text allows statements starting at any indentation.

**Comment by desoi** [comment]
I don't recall, it has been a while. I think it was needed to distinguish the beginning of the overall SQL statement versus embedded statements within a dollar quoted function.
