### ISSUE TITLE
Provide support for YAML metadata blocks in Markdown?

### ISSUE THREAD

**Issue by kevinushey** [ajaxorg/ace#3361]
For Markdown documents that are digested by [pandoc](http://pandoc.org/), it's common to use YAML metadata blocks to help provide some configuration to pandoc when the document is processed. See the documentation [here](http://pandoc.org/MANUAL.html#extension-yaml_metadata_block).

The YAML blocks can occur either at the very start of the document, or after a blank line, and are delimited by `---` on top and either `---` or `...` on the bottom, e.g.

```
---
title: "My Document"
author: "Firstname McLastname"
---
```

Is this something that would be worth considering either as an extension to the `Markdown` highlight mode, or instead a separate `PandocMarkdown` highlight mode (extending the base `Markdown` rules)?

**Comment by nightwing** [comment]
@kevinushey i think it would be nice to have, i remember someone asking about this feature for cloud9 too.

I think we can add this to default markdown mode, and then if someone complains, we can make it optional/move to PandocMarkdown

**Comment by BigChief45** [comment]
If I am not mistaken, this is called YAML Frontmatter. It is also used by blog and static site generators such as Jekyll and Middleman. Therefore I think this should be added to Markdown.

However I am not sure if there are subtle differences with Pandoc (which I've never used), such as string quotes. Jekyll and Middleman examples don't seem to have them. @kevinushey  Can you confirm if this is also the case for Pandoc? I might take a shot at this feature.

**Comment by kevinushey** [comment]
I don't think there's anything special about the way Pandoc digests YAML -- I do know that it's okay not to quote strings in certain contexts, but one does need to be wary of e.g. strings containing colons; e.g. this:

```
title: My project: it was great.
```

would be parsed as having two keys, `title` and `My Project`, and so quoting would be necessary there. This particular issue is from http://pandoc.org/MANUAL.html#extension-yaml_metadata_block.

I know that these YAML metadata blocks are often referred to as YAML frontmatter (since it makes sense to put this sort of configuration up-front at the start of a document), but technically it can occur either at the start of a document, or anywhere in the document following a blank line.
