### ISSUE TITLE
How to get all the highlighted text matches 

### ISSUE THREAD

**Issue by divat** [ajaxorg/ace#3362]
Hi Folks,

Is there any function inside ace editor to get the highlighted text whenever i apply find(Ctrl-F) ?

Could anyone help me to get know about this.

Thanks,
Diva

**Comment by nightwing** [comment]
use, editor.getSelectedText()

The issue tracker is for reporting bugs, stackoverflow is a better place for asking questions,

**Comment by divat** [comment]
@nightwing Thanks
