### ISSUE TITLE
Autocomplete sorting is not intuitive for values with equal scores

### ISSUE THREAD

**Issue by shepmaster** [ajaxorg/ace#3365]
The [current sort for autocomplete](https://github.com/ajaxorg/ace/blob/36e70abcb0bb767adb621b6f546bb237a8ad39c6/lib/ace/autocomplete.js#L448-L450) doesn't specify a tiebreaker:

```js
        matches = matches.sort(function(a, b) {
            return b.exactMatch - a.exactMatch || b.score - a.score;
        });
```

This can happen when you trigger the autocomplete menu in a new spot and all the suggestions have the same score:

![image](https://user-images.githubusercontent.com/174509/28505183-5f166c44-6fef-11e7-82da-94b31e0c036e.png)

It looks silly to have later words come earlier in the list here.

I'd encourage a tiebreaker of some kind, perhaps based on the caption. For now, I'm setting my scores to all be different and in alphabetical order. This only works because I have a single completer function.

**Comment by mikecargal** [comment]
I'd like to second this suggestion.  We have set up an algorithm to score our matches, but *particularly when the prefix is "", all scores are equal.  As a result, suggestions appear in a random order.  I had hoped that perhaps ace would default to the array order as a fallback, but that doesn't appear to be the case (probably using an unstable sort on the score I'd assume).

We may look into something akin to the workaround above, but seems to be unnecessarily complicated.

**Comment by nightwing** [comment]
I've added alphabetical sorting in #3730.
