### ISSUE TITLE
Code folding doesn't recognize "part" or "chapter" environments

### ISSUE THREAD

**Issue by NilsEnevoldsen** [ajaxorg/ace#3367]
Code folding recognizes section and subsection (and, buggily, subsubsection (sharelatex/sharelatex#427)), but not part or chapter.

Originally reported as sharelatex/web-sharelatex/issues/487.

**Comment by nightwing** [comment]
@NilsEnevoldsen i can't find information on chapter and part, and how to use them.
Are they ordered as `section > subsection > subsubsection > part > chapter` or some other way?

**Comment by NilsEnevoldsen** [comment]
It's `part > chapter > section > subsection > subsubsection > paragraph > subparagraph`

Some references:

https://www.sharelatex.com/learn/Sections_and_chapters#!#Document_Sectioning

https://en.wikibooks.org/wiki/LaTeX/Document_Structure#Sectioning_commands

http://texdoc.net/texmf-dist/doc/latex/latex2e-help-texinfo/latex2e.pdf (Section 6)

**Comment by nightwing** [comment]
Should be fixed by https://github.com/ajaxorg/ace/pull/3369, let us know if you find any other issues, or missing features!
