### ISSUE TITLE
Add `vim-surround` functionality to vim keybindings

### ISSUE THREAD

**Issue by ashiklom** [ajaxorg/ace#3373]
See https://github.com/tpope/vim-surround

I believe I've seen this functionality in the vim mode of other editors. Based on the implementation of vim here, it may require re-coding all of the surround functions in javascript, but it's not a huge package. I might even be able to take a stab at it myself.

**Comment by nightwing** [comment]
Having this would be great.
Unfortunately I won't be able to work on this in the near future, so a pull request would be very welcome.
