### ISSUE TITLE
Ace Bookmarklet not Working

### ISSUE THREAD

**Issue by timharris777** [ajaxorg/ace#3380]
Bookmarklet generated from https://ace.c9.io/build/demo/bookmarklet/ is not working. AFter loading the bookmarklet I tripple click on a text area as directed and the following error shows in the javascript console of the browser

`VM92:1 Uncaught TypeError: ace.transformTextarea is not a function
    at HTMLTextAreaElement.<anonymous> (<anonymous>:1:802)
(anonymous) @ VM92:1`

**Comment by nightwing** [comment]
fixed in https://ajaxorg.github.io/ace-builds/demo/bookmarklet/index.html, the version at ace.c9.io will be updated with the next release.
