### ISSUE TITLE
Update the CSSLinter

### ISSUE THREAD

**Issue by eugeneford** [ajaxorg/ace#3382]
Hi, i found that there is an outdated version of CSSLint inside ace. 

Checkout pls: https://github.com/CSSLint/csslint

**Comment by eugeneford** [comment]
@nightwing any activity here? I can try to make CSSLint an external dependency, if you have no time

**Comment by eugeneford** [comment]
Also related to #3381

**Comment by nightwing** [comment]
@eugeneford making it an external dependency sounds like a good solution, a pr doing that would be very welcome.
