### ISSUE TITLE
X primary buffer does not work

### ISSUE THREAD

**Issue by mikhirev** [ajaxorg/ace#3384]
Hi!

I use Debian GNU/Linux with X.org and Firefox ESR (exact versions does not matter, the issue is reproducible with any versions). I often use the X primary buffer for copying text (mouse selection to copy, middle mouse button click to insert) that works everywhere except ACE (and probably some other JS editors). It is very inconvenient to use only X clipboard (Ctrl+C, Ctrl+V), I accustomed to copy and paste with mouse only.

**Comment by nightwing** [comment]
For short strings this is fixed on chrome by https://github.com/ajaxorg/ace/pull/3635.
On firefox there is no way to fix this because of https://bugzilla.mozilla.org/show_bug.cgi?id=953389
