### ISSUE TITLE
Cursor renders in the wrong place for mixed bold/regular fonts on safari 

### ISSUE THREAD

**Issue by MustafaHaddara** [ajaxorg/ace#3385]
When a line in Ace has some bold characters and some non-bold characters, safari calculates the character width incorrectly and renders the cursor in the wrong spot. 

Reproduction instructions:
Open Ace Kitchen Sink: https://ace.c9.io/build/kitchen-sink.html
Document: Python
Mode: Python
Theme: Github

Attempt to place the cursor at the end of the very last line. On my screen, at the "end of the line", the cursor is rendered on top of the `5` in the `celcius+.5` term. 

![screen shot 2017-08-14 at 2 11 35 pm](https://user-images.githubusercontent.com/11722214/29284886-862b1dae-80fa-11e7-95c7-fbbf7309fe2e.png)

Reproduced on 

Safari Version 10.1.2 (12603.3.8)
macOS Version 10.12.6 (16G29)
ace editor 2014.03.08 Version 1.1.3

I reproduced the same line with mixed bold/unbold text in jsfiddle (https://jsfiddle.net/Lj3xp0wh/) and found that there, the cursor is rendered correctly. This leads me to believe that it is not purely a safari/webkit bug.

**Comment by Sugaroverdose** [comment]
It's safari-specific bug in handling bold fonts(which isn't considered as monospace? whatever)
Here's screenshot of the same text line in safari(top) and firefox(bottom):
<img width="299" alt="ace_safari_ff" src="https://user-images.githubusercontent.com/10269200/32126530-d999137e-bb79-11e7-9c9b-a15c12fd2e26.png">
As you can see, safari makes bold text a little bigger and adds "bold" spacing
```css
font-family: monospace;
```
to 
```css
.ace-github .ace_keyword
```
fixes issue(kind of) fixed safari(top) firefox(bottom):
<img width="299" alt="ace_safari_fixed_ff" src="https://user-images.githubusercontent.com/10269200/32126836-7714ef14-bb7b-11e7-93a8-91e7ccf96a9d.png">
Adding 
```css
letter-spacing: -0.08em;
```
Makes safari line looks almost like firefox without it, but breaks firefox =)
<img width="299" alt="ace_safari_ls_ff" src="https://user-images.githubusercontent.com/10269200/32127066-eca2226e-bb7c-11e7-94b9-15f2d68285ae.png">

**Comment by Sugaroverdose** [comment]
After digging a little more i've found that it's specifics to 'Monaco' font, so changing `.ace_editor` style from 
```css
font: 12px/normal 'Monaco', 'Menlo', 'Ubuntu Mono', 'Consolas', 'source-code-pro', monospace;
```
to
```css
font: 12px/normal 'Menlo', 'Monaco', 'Ubuntu Mono', 'Consolas', 'source-code-pro', monospace;
```
Fixes issue for safari and should not harm anyone else
