### ISSUE TITLE
Unable to deselect by clicking outside?

### ISSUE THREAD

**Issue by danqing** [ajaxorg/ace#3386]
It just occured to me that if I select some text in ace, and then click outside (other part of the page), the selection remains. I'm not sure if this is intentional or a bug, but I'd expect that clicking elsewhere deselects the text. If this is intentional, is it possible to have an option for it?

Thanks!

**Comment by nightwing** [comment]
This is intentional, and other editors behave the same way.
if you want to clear selection on blur use the following:
```js
editor.on("blur", function(e, editor) {
    if (document.activeElement != editor.textInput.getElement())
        editor.selection.clearSelection(); 
})
```
