### ISSUE TITLE
New Feature: Provide support for max length option

### ISSUE THREAD

**Issue by christianbs** [ajaxorg/ace#3393]
Sometimes is important set a limit of the script.

**Comment by nightwing** [comment]
You can use the following code to disable inserting if editor value is longer than some limit

```js
var doc = editor.session.doc
doc.applyAnyDelta = doc.applyAnyDelta || doc.applyDelta
doc.applyDelta = function(delta) {
   if (delta.action == "insert" && this.$maxLength 
       && this.getValue().length > this.$maxLength) {
       return false;
   }
   return this.applyAnyDelta(delta);
}
doc.$maxLength = 20
```

Could you please tell in which cases do you need this, to help us understand whether this needs to be a part of default set of options or an extension.

**Comment by christianbs** [comment]
Of course!! So, in our application, the script is persisted at database and there's a limit to this column. I think this should be very common because the editor actually is very used in web applications. On the other hand, the script above should solve my problem... thanks
