### ISSUE TITLE
Flow Chart and Sequence Diagram Support

### ISSUE THREAD

**Issue by Cheedoong** [ajaxorg/ace#3396]
Supporting UML diagrams is obviously a useful feature. 
Would you like to add the support for flow charts and sequence diagrams? 
Like what provided in [StackEdit](https://stackedit.io/editor) 

simply via:
http://adrai.github.io/flowchart.js/
http://bramp.github.io/js-sequence-diagrams/

**Comment by nightwing** [comment]
StackEdit shows diagrams only in the markdown preview, not in the editor, and ace does not have any markdown preview functionality.
