### ISSUE TITLE
Tab key "indent" command doesn't work in some editing modes.

### ISSUE THREAD

**Issue by mouhannad-sh** [ajaxorg/ace#3403]
Hi, this is a weird bug,

Basically the "Tab" key doesn't indent at all in some modes however it works fine in other modes.

So far I've found this bug on "scss" , "css" and "html" modes.

Other modes like "ruby", "javascript" and "python" work fine.

I'm using version 1.2.8 of the editor

```
editor.setTheme('ace/theme/monokai');
 editor.$blockScrolling = Infinity;
 editor.setShowPrintMargin(false);
    editor.setOptions({
      enableBasicAutocompletion: true,
      enableSnippets: true,
      enableLiveAutocompletion: true,
      fontSize: '15px',
      wrap:true
    });
```

I load a single instance of the editor and update it on different tabs 
```
updateEditor = (node) => {
    let content = node.data.content;
    let mode = node.title.split('.').pop();
    CodeEditor.hide()
    clearUndo = typeof clearUndo != "undefined"? clearUndo : true;
    editor.setSession(aceSessions['session_'+node.key]);
    CodeEditor.show();
    editor.getSession().setMode('ace/mode/text');
    if (mode === "js") {
      window.editor.getSession().setMode('ace/mode/javascript');
    } else if(mode !== 'txt'){
      window.editor.getSession().setMode('ace/mode/'+mode);
    }
  }
```
I tried checking the `editor.commands` object and everything seems fine.

When I enter `editor.commands.commands.indent.exec` I get : `ƒ (t){t.indent()}`

**Comment by nightwing** [comment]
Hi
could you please show a page where this bug can be reproduced.
https://ace.c9.io/#nav=embedding has an editor in html mode, and it works.

**Comment by mouhannad-sh** [comment]
Hi @nightwing ,

Thanks for the quick reply ! 

Here's a fiddle: https://jsfiddle.net/mouhannad/3oxgve7m/

While adding assets I found that, the issue started to happen after I included Emmet from CDN,

removing Emmet from my project fixed the issue BUT, Emmet is an amazing extension that I would really like to have running on my project, so removing it isn't an optimal solution

**Comment by nightwing** [comment]
This is a bug in error reporting, in addition to ext-emmet you need to include the emmet source  code similar to https://github.com/cloud9ide/emmet-core/blob/master/emmet.js, which is obtained from dist/emmet-snippets.js in https://github.com/emmetio/emmet
( https://github.com/cloud9ide/emmet-core/blob/master/build.sh#L10)
