### ISSUE TITLE
"Save-As" dialog on custom command CTRL+S

### ISSUE THREAD

**Issue by padhie** [ajaxorg/ace#3406]
Hi Guys,
i want to set a custom command with the keybind "CTRL+S".
In Firefox the funktion works fine but the "Save-As" dialog pop up and in Chrome only the popup is opened and the funktion don't work (Firefox 55.0.3 (32-Bit) und Chrome Version 60.0.3112.113 (Offizieller Build) (64-Bit)).

Can you tell me if it is possible to fix it? It would be nice, because i want to submit the form with this keybind for make it easyer.

best reguards
padhie

**Comment by padhie** [comment]
I try a snippet for an old version of the ace-editor :/ not it's work :)

**Comment by nightwing** [comment]
Please create a snippet http://plnkr.co/ or http://jsbin.com/ showing what you are trying to do.
ctrl-s keybinding works at https://github.com/ajaxorg/ace/blob/v1.2.8/demo/kitchen-sink/demo.js#L223-L236
