### ISSUE TITLE
Access to Code Folding Arrows?

### ISSUE THREAD

**Issue by OughtImpliesCan** [ajaxorg/ace#3410]
The code folding arrows to the left of the code have a different effect than Ctrl-L... I want to be able to control that effect (clicking the arrow instead of the keyboard) programmatically... not only for more optimal integrations but adding the ability for third party developers to set tags throughout their code, tags that can be set to third party keyboard shortcuts that can then auto click all the arrows in the proper configuration so that your file with thousands of lines of code can easily be navigated without having to do it manually... 

I tried looking through the documentation but couldn't find anything and trying a .click() on an arrow with a browser extension didn't work... really frustrating that what is suppose to be an open editor is using a particular configuration that doesn't allow programmatic clicking... what's up with that?

**Comment by nightwing** [comment]
The is F2 shortcut does this https://github.com/ajaxorg/ace/blob/v1.2.8/lib/ace/commands/default_commands.js#L113

**Comment by OughtImpliesCan** [comment]
Gracias!
