### ISSUE TITLE
Autocomplete popup custom className and matched parts highlighting not working together

### ISSUE THREAD

**Issue by xmachac2** [ajaxorg/ace#3412]
Hi,

we implemented autocompletion in ACE editor for our SQL editor. Because there is no support for icons on autocomplete popup rows we use className property of completion items for visually distinguish between tables/views/synonyms. But if we specify className the completion highlighting of matched text parts doesn´t work.

This is because

https://github.com/ajaxorg/ace/blob/master/lib/ace/autocomplete/popup.js#L190

where is expression

`data.className || "" + ( flag ? "completion-highlight" : "")`

which discarts "completion-highlight" class from result if data.className is specified. Beter would be change expression (which preserve highlight class) to

`(data.className || "") + ( flag ? " completion-highlight" : "")`

It wrap subexpression to brackets because operators priority and add extra space between custom className and "completion-highlight" class.

Thank's and best regards
Zdeněk Machač

P.S. Better would be to add className to whole row and not to each DOM element in item row but this would be backward incompatible.

**Comment by insingh50** [comment]
Is there any update on this issue? 
I'm facing the same problem when trying to use the custom className.
