### ISSUE TITLE
define is not defined.

### ISSUE THREAD

**Issue by aayushpatidar** [ajaxorg/ace#3417]
I am using the src folder to access "ext-language_tools.js" but it is showing error. So, the keywords and snippets suggestion in dropdown is not coming. The error it is showing is mentioned below:

ext-language_tools.js:1 Uncaught ReferenceError: define is not defined at ext-language_tools.js:1
![image](https://user-images.githubusercontent.com/29274656/30681267-51b1880c-9ec2-11e7-91f5-775601368e4e.png)

And when I use the src-noconflict then also it showing the error:

ext-language_tools.js:1 Uncaught ReferenceError: aceis not defined at ext-language_tools.js:1
![image](https://user-images.githubusercontent.com/29274656/30681287-6da6310c-9ec2-11e7-89b5-b12cc4b70bc4.png)

Also showing this:
![image](https://user-images.githubusercontent.com/29274656/30681660-115dc43a-9ec4-11e7-857f-3ce936d5da0e.png)

Please suggest me the solution as soon as possible.
Thanks.

**Comment by nightwing** [comment]
Do you load ext-language_tools file before are after ace.js? 
If You load it after ace, please create a demo page reproducing the issue you see.

**Comment by mohanapreeya** [comment]
yeah me too got the same error when i was trying to include ext-modelist.js file

**Comment by blurymind** [comment]
same issue here

**Comment by nightwing** [comment]
@blurymind how exactly do you load the ace.js
the error can happen if ace.js script is not loaded before the ext- script.

**Comment by blurymind** [comment]
I got it to work by assigning it globally like this
Window.ace= require('ace-builds')
Window.define=ace.define

**Comment by ttaylor29** [comment]
Blurymind,

Here did you place this?

Window.ace= require('ace-builds')
Window.define=ace.define

I'm seeing the same issue, but can't find where to place the Window.define

**Comment by S-mardii** [comment]
Is there any solution to this issue yet?

**Comment by NoBodyButMe** [comment]
It's 2020 right now. Is there already an answer or a solution?

**Comment by andrewnester** [comment]
Wasn't able to reproduce it on the latest Ace build, could you provide steps to reproduce?

**Comment by rusproject** [comment]
Found a solution, need to change the code by adding one more <script> tag

```html

	<script src="/js/ace/ace.js" type="text/javascript" charset="utf-8"></script>

	<!-- add this: -->
	<script type="text/javascript">		
		define=ace.define
		window.require=ace.require
	</script>

	<script src="/js/ace/ext-language_tools.js" type="text/javascript" charset="utf-8"></script>
... 
```
