### ISSUE TITLE
changeFold event fired to soon?

### ISSUE THREAD

**Issue by ivanbacher** [ajaxorg/ace#3419]
```
editor.session.on('changeFold', () => {
    let first = this.editor.getFirstVisibleRow();
    let last = this.editor.getLastVisibleRow();
}
```
This event is fired before any of the rows in the editor are manipulated. This results in the incorrect values for the variables `first` and `last`.

Now if I use `setTimeout` with a delay of 500ms the values for the variables `first` and `last` are correct. 

```
editor.session.on('changeFold', () => {
    setTimeout( ()=> {       
         let first = this.editor.getFirstVisibleRow();
         let last = this.editor.getLastVisibleRow();
     },  500);
});
```

Is this the intended behaviour? If yes, is there another folding event that gets called after the corresponding rows  in the editor have been manipulated (removed/added)?

**Comment by nightwing** [comment]
This happens because First/LastVisibleRow are updated only after rendering the editor.
You may be able to use `editor.renderer.on("afterRender"` event in combination with `changeFold`, but that depends on your usecase. What do you use getLastVisibleRow() for?

**Comment by ivanbacher** [comment]
Ah I see. I was just using `getFirstVisibleRow()` and `getLastVisibleRow()` to figure out how many visible rows there are in the editor, as I am working on a type of minimap.

Anyway, I will try to use `editor.renderer.on("afterRender", () => {})`. Thanks for the suggestion.
