### ISSUE TITLE
Problem with getAnnotations value coming late

### ISSUE THREAD

**Issue by brianpinto31** [ajaxorg/ace#3423]
Using an Ace Editor in a C# form which  contains a TreeView and loads scripts at every TreeNode_AfterSelect event.
As i see, when any script is written it instantly shows the error symbols. But my problem is with the getAnnotations function. As every Script data is loaded via the TreeNode_AfterSelect event, I get the return value from getAnnotations always later.

E.g: Script 1-> contains 4 errors
Script 2 -> contains 9 errors

When selected node is Script2 if previously selected node is Script 1 i get 4 errors and there after i select Script1 and I get 9 errors. Its because I get the previous return value from the getAnnotations function when it is called the next time. It is not as dynamic as the symbols in the ace editor. What can be done here? Please help. I somehow need to get it running .

**Comment by nightwing** [comment]
Annotations are not displayed instantly, the worker computes them asynchronously. 

You can use `changeAnnotation` event listener  `editor.session.on("changeAnnotation", function() { ... })` to get notified when annotations are changed.

Closing the issue, but please comment if you have any followup questions.

**Comment by just-website** [comment]
Did you remove changeAnnotation event from the api? I don't see this event in the documentation. What is the current way to find out if a syntax error occurs?
https://ajaxorg.github.io/ace-api-docs/classes/Ace.EditSession.html#on
