### ISSUE TITLE
Allow modes to define own search highlight?

### ISSUE THREAD

**Issue by kevinushey** [ajaxorg/ace#3425]
For motivation, in R, identifiers may contain a `.`; e.g. `my.variable` is a valid identifier name. However, in Ace, attempts to highlight a variable with that name don't highlight other instances. Compare e.g.

![screen shot 2017-10-06 at 10 28 36 am](https://user-images.githubusercontent.com/1976582/31290389-25d16160-aa81-11e7-92a2-b049b542720a.png)

I think the associated code lives here: https://github.com/ajaxorg/ace/blob/fe4427e8d468c77e10dacf5ec213216117887a21/lib/ace/editor.js#L800-L830

I wonder if it would be worth allowing modes to provide a method here that controls what is valid for a selection to be considered for search?

Specifically, here: https://github.com/ajaxorg/ace/blob/fe4427e8d468c77e10dacf5ec213216117887a21/lib/ace/editor.js#L820

Could we allow a mode-specific regular expression rather than the hardcoded `[\w\d]`? (I'd be willing to submit a small PR)

**Comment by nightwing** [comment]
Adding a method to modes sounds good, though making the highlight accept more strings may be good too (things like `obj.method` in cstyle languages or camelCase parts of words).

Btw. does `.` need to be included in double click word selection for R mode?

**Comment by kevinushey** [comment]
That's correct (nice catch!) We'd like double-click to highlight the whole identifier (including `.`) as well.

**Comment by nightwing** [comment]
In https://github.com/ajaxorg/ace/pull/3451/files#diff-9939b765a7512c3749c8275012b3ac68R804 i am changing the default highlight regexp to accept selections with non word characters.
Does that fix this issue?

**Comment by nightwing** [comment]
@kevinushey looks like r mode already had code for including `.` in double click selection https://github.com/ajaxorg/ace/pull/3454/files#diff-ff627b70ea602469b759da44dd9ce36fR59

**Comment by kevinushey** [comment]
Sorry for the slow response! It looks like this would fix both the original issue I reported + the double-click selection. Would you be able to let me know when this becomes available in the Ace Kitchen Sink so I can do a bit of testing?

Thanks for taking a look at this so quickly!

**Comment by nightwing** [comment]
you can test it on https://rawgit.com/nightwing/ace/0f0385bd4fb6b3acabba0089f8f59b1578b2c133/kitchen-sink.html.

Btw do you use the version of r mode in ace or https://github.com/rstudio/rstudio/blob/master/src/gwt/acesupport/acemode/r.js#L60?

**Comment by kevinushey** [comment]
Just tested it out and it works great!

You're right that we're currently using our own custom-built R mode (ie, the one you linked to). The complexity of our R code model has spiraled out of control a little bit (it currently relies on the Ace tokenizer, and has a bunch of hacks here and there) and so we haven't been able to send most of these changes upstream :-/
