### ISSUE TITLE
Right click moves cursor position

### ISSUE THREAD

**Issue by ak131554** [ajaxorg/ace#3429]
I'm already using ace editors on my site. Now I want to add to those a context menu in which the user can select some boilerplates that are automatically inserted in the current cursor position. My problem is that right clicking within the editor moves the cursor to the position of the click. This behavior is so uncommon, no other text editor known to me behaves like that. It therefore lowers usability of my editors.

Is there an option to setup a more consistent behavior? Or can I use some javascript workaround to prevent cursor movement on right click?

You can just see the problem in the example editor on your page https://ace.c9.io/. It occurs in Firefox and Chrome both on Windows and Ubuntu.

**Comment by nightwing** [comment]
Many text editors behave this way, notepad++, visual studio code, textarea to name a few.

To override this behavior you could do:

```js 
editor.addEventListener("mousedown", function(e) {
    if (e.getButton() == 2) e.preventDefault();
})
```
