### ISSUE TITLE
Atropine doesn't decrease heart rate

### ISSUE THREAD

**Issue by Nich10solo** [ajaxorg/ace#3431]
Atropine doesn't decrease heart rate. It is actually used for bradyarrhythmias to increase heart rate. 

See this copy of the ACLS card for treatment of bradycardia: https://i.pinimg.com/originals/c7/94/00/c794007377e59c64e145badd209e29d5.jpg

and the medscape article on atropine for reference: https://reference.medscape.com/drug/atropen-atropine-iv-im-343093

Thanks.

**Comment by coachwn** [comment]
Come on don't just close the issue for no reason. 

The issue with Atropine has been a problem with ACE Medical for a long time now. 

https://www.ncbi.nlm.nih.gov/pubmed/6524277/

If it has been fixed or is being worked on at least make a notation directing those of us that are interested to the appropriate log location. I haven't seen it referenced yet.

**Comment by nightwing** [comment]
I had closed the original report because it looked too much like advertisement/spam. 
I am sorry that I had not asked for clarification first.

That said this is an issue tracker for a code editor, and is not related to ACE Medical, or Atropine in any way.
