### ISSUE TITLE
How to get reference to dom elements for a range of rows in ace editor?

### ISSUE THREAD

**Issue by adrian-moisa** [ajaxorg/ace#3436]
So far I have found `getLine()` and `getAllLines()` methods, but they return the string contents of the specified lines. 

    let line = this.editor.session.getLine(30);
    let lines = this.editor.session.doc.getAllLines()

How can I request the dom element for a certain line? I want to highlight a set of lines but I want to avoid creating `selectionRange` because I want the selection range to be free for other stuff. 

    selectionRange = editor.getSelectionRange();

    startLine = selectionRange.start.row;
    endLine = selectionRange.end.row;

    content = editor.session.getTextRange(selectionRange);

I would apply a css class changing the background color. Unfortunately there is no id class for `<div class="ace_line_group"` that I could highjack for this purpose. Also I would like to avoid any messy regex that loops all lines until it finds the ones I'm looking for.

**Comment by adrian-moisa** [comment]
Well... luckily, after some more googling I found the answer. It is also playing nice with webpack.

        var ace = require('brace');
        var Range = ace.acequire('ace/range').Range;
        editor.session.addMarker(
            new Range(1, 0, 15, 0), "ace_active-line", "fullLine", true
        );

**Comment by nightwing** [comment]
There is no, easy method of getting dome nodes.
You can use `editor.renderer.textToScreenCoordinates(row, column);` to show 
 the tooltip https://github.com/c9/core/blob/e5f6d5c4a801f8b8c76aa7eb212d321785d63612/plugins/c9.ide.language.core/tooltip.js#L188

**Comment by adrian-moisa** [comment]
Thank you so much for sharing this! This is exactly what I need to get started. Keeping the tooltip and editor scroll in sync should be easy. Off-topic, c9.ide looks really interesting. Cheers!
