### ISSUE TITLE
In Rust, `dyn` should be highlighted as a keyword.

### ISSUE THREAD

**Issue by vi** [ajaxorg/ace#3440]
https://github.com/integer32llc/rust-playground/issues/224

**Comment by shepmaster** [comment]
I believe the current list of keywords [can be found here](https://github.com/rust-lang/rust/blob/master/src/libsyntax_pos/symbol.rs#L248-L317). For example, it also looks like `catch` is missing. Of note is that `dyn` [is very new](https://github.com/rust-lang/rust/issues/44662) and hasn't been fully documented yet, much less available in a stable release of Rust yet. I'm not sure what Ace's position on such changes are.

**Comment by vi** [comment]
Added more keywords from that list: `become`, `catch`, `default`, `union`.
