### ISSUE TITLE
Does ACE have an ECCN?

### ISSUE THREAD

**Issue by otramony** [ajaxorg/ace#3442]
Hello. Our team would like to use/include your library in our product, and since we export outside of the U.S., we're required to provide ECCN (Export Control Classification Number) information for all 3rd-party libraries that may use/include encryption. We noticed some references to SHA1, so we thought we should ask. Thanks.

**Comment by nightwing** [comment]
Ace doesn't include encryption code, all references to sha1 and crypto are from syntax highlighters. Also Ace was not developed in USA. So there is no ECCN.
