### ISSUE TITLE
click on select area then select the area above it

### ISSUE THREAD

**Issue by zrx8269** [ajaxorg/ace#3446]
Hi,

I am using ace editor to show my source code. The code is long enough, you need to scroll the screen. For example, your screen's height is 500px(line 0 - 25), the editor's height is 1000px(line 0 - 50). if you select line 0 - 25 and then click on the select area, it woks fine, just clear the selection. But if you select code from line 26 to line 28, then click on line 27, the editor will scroll up and then select another area. What should I do to solve this problem? Thanks very much.

**Comment by nightwing** [comment]
Hi, 
if you are using css transform on parent element of the ace instance, you may be encountering a known bug
try adding the following css as aworkaround
```css
textarea.ace_text-input {
    position: absolute!important;
}
```
if this doesn't help, could you please show a page where this issue happens, there may be an issue with not calling resize correctly, or something else which is hard to understand from the above description
