### ISSUE TITLE
Persian language character sizing

### ISSUE THREAD

**Issue by pwwiur** [ajaxorg/ace#3455]
When i write `<a href="url">این یک لینک است</a>` the sizes of persian characters are big in chrome and small in mozilla firefox.
every character in chrome has the size of two characters in english.

It's size is normal when watching, but in editting it's not, in another words the cursor of editing is far apart from text.
You can see the position of cursor in pic i've added to this issue:

![capture](https://user-images.githubusercontent.com/22914652/32889120-d2dc03c4-cade-11e7-8706-2880afcc3247.JPG)

**Comment by trunov-ms** [comment]
I have same problem on Cyrillic symbols.

**Comment by pwwiur** [comment]
There are thousands of developers in the Persian language suffering from this problem. Please review this.
