### ISSUE TITLE
"tests" and "Mode Creator" links are broken

### ISSUE THREAD

**Issue by BillyRayPreachersSon** [ajaxorg/ace#3457]
Steps to reproduce:

* Visit the [Ace Kitchen Sink page](https://ace.c9.io/build/kitchen-sink.html)
* Click the [tests](https://ace.c9.io/build/lib/ace/test/tests.html) link or the [Mode Creator](https://ace.c9.io/build/tool/mode_creator.html) links at the bottom of the left-hand nav

Expected behaviour:
* Browser would be at the requested pages

Actual behaviour:
* Browser is at a 404 page

Incidentally (and probably not worth creating a new issue for), the "tests" link is mostly obscured by the "Mode Creator" link, due to its `padding: 1em;` style. To achieve the desired indentation, either use `padding-left: 1em;` or `text-indent: 1em; display: inline-block;`.

**Comment by nightwing** [comment]
Fixed in https://github.com/ajaxorg/ace/blob/master/kitchen-sink.html#L277 by disabling the links in the built mode, and fixed the padding issue in unpacked mode (will be on ace.c9.io after the next release)
