### ISSUE TITLE
fontSize crashes onkeyup in Firefox 57 on Ubuntu

### ISSUE THREAD

**Issue by jpuck** [ajaxorg/ace#3458]
There seems to be an issue between Firefox 57, Ubuntu 16.04, and Ace 1.2.9 fontSize.

consider this basic config:

```javascript
var editor = ace.edit("sql");
editor.setOptions({
    mode: "ace/mode/sql",
    maxLines: Infinity,
    fontSize: 18,
});
```

When I start typing in the editor, it crashes `onkeyup` and I've got no event handlers registered. If I simply remove the `fontSize: 18` option, then it works perfect. Same behavior when using `editor.setFontSize(18)`

I've tested it works in the following environments:

* [x] Chromium 62 Ubuntu 16.04
* [ ] Firefox 57 Ubuntu 16.04
* [x] Firefox 57 Windows 7
* [x] Firefox 56 Windows 7
* [x] Chrome 62 Windows 7

**Comment by nightwing** [comment]
What do you mean by "crashes onkeyup"
If i open https://ace.c9.io
and run 
```js
editor.setOptions({
    mode: "ace/mode/sql",
    maxLines: Infinity,
    fontSize: 18,
});
```
In the browser console, there are no errors on keyup event

**Comment by jpuck** [comment]
Yep. You're right. It works on that page no problem.

I'll close this issue for now until I can narrow down a shareable reproducible example.

Thanks for your time!

**Comment by jpuck** [comment]
@nightwing I discovered the issue stemmed from some conflicting JavaScript which autoexpands textareas to fit contents.

```js
$('textarea').each(function(){
    var ta = $(this);
    ta.keyup(function(){
        var top = parseFloat(ta.css('borderTopWidth'));
        var bottom = parseFloat(ta.css('borderBottomWidth'));
        while(ta.outerHeight() < this.scrollHeight + top + bottom) {
            ta.height(ta.height()+1);
        };
    })
});
```

I do not wish to reopen the issue, but I wanted to document it here in case someone comes searching for the same problem.

I am still curious as to why this only crashes in the most recent version of firefox for ubuntu, but I've got other things to worry about.
