### ISSUE TITLE
Relative Line Numbers

### ISSUE THREAD

**Issue by brycefrank** [ajaxorg/ace#3461]
Would it be possible to add a relative line numbers mode ala Vim? I use Rstudio (a downstream editor) and having this functionality is almost essential for navigating through documents quickly in Vim mode.

[Here](https://jeffkreeftmeijer.com/vim-number/) is an example of the functionality.

**Comment by nightwing** [comment]
there is already an implementation of this feature at https://github.com/c9/core/blob/master/plugins/c9.ide.ace/ace.js#L1577-L1608.

**Comment by nightwing** [comment]
fixed by https://github.com/ajaxorg/ace/pull/3631
