### ISSUE TITLE
setvalue() ----- Uncaught SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by gorenhi** [ajaxorg/ace#3465]
how to use editor.setValue("<script>...</script>")

**Comment by nightwing** [comment]
in html script tag `</script>` always closes the tag, use `<\/script>`

**Comment by ctf0** [comment]
@nightwing i have an issue with php which starts with `<?php` and ace for some reason give error of `Unexpected token <` is there a way to get it to work with php tag ?

**Comment by nightwing** [comment]
What exactly do you do to see the error?

**Comment by ctf0** [comment]
@nightwing i was trying to send the data directly to `setValue()` because of an issue with vue, but i finally got it solved.

thanx for the quick reply 👍
