### ISSUE TITLE
window.require is not a function

### ISSUE THREAD

**Issue by jpolvora** [ajaxorg/ace#3466]
Cannot use almond after optimize with r.js.

ace.js calls window.require but almond doesn't set a global window.require.
window.require is not a function

In order to make if functional, I need to patch the almond.js source by adding window.require = require .. etc

Currently using almond 0.33 (latest version available).

So I was forced do include the full require.js (not almond) so Ace is working ok.

**Comment by nightwing** [comment]
Ace has window.require only in worker.js which needs to be loaded into a webworker, and has it's own loader. 
Do you use ace or ace-builds repo, and if it is the former, how do you create separate files for modes and workers with r.js?

**Comment by nightwing** [comment]
Closing the issue, but please comment if my answer above didn't help.
