### ISSUE TITLE
Backslash (\)

### ISSUE THREAD

**Issue by stormit** [ajaxorg/ace#3470]
Hello,

I have a problem with this library. I uses it for a CSS field. When my css code has the Backslash character, it will be removed after saving. Could you please help me check it?

Thank you!

**Comment by nightwing** [comment]
Hi
this can be caused by not encoding/decoding the value correctly when saving and depends on the way you are saving it.
Could you show the code you use to save and load the value?

**Comment by nightwing** [comment]
Closing, but please comment if you still see this issue
