### ISSUE TITLE
Editor Doesn't Select All and Stops at the Cursor when Shortcut for "Select all" Is Pressed Right after Mouse Click

### ISSUE THREAD

**Issue by boghyon** [ajaxorg/ace#3471]
# Tested Browsers / Devices
Windows 10
  - FAIL:
    - Chrome 62.0.3202.94
    - Edge 41.16299.15.0
    - IE 11
    - Firefox 57.0.1
  - OK: n/a  

# URL Minimal Example
https://ace.c9.io/build/kitchen-sink.html

# Steps to Reproduce the Problem
1. Open the minimal example page and wait until it's fully loaded
2. Click on the editor and **immediately select** all text by pressing <kbd>Ctrl</kbd>+<kbd>A</kbd> (or <kbd>⌘</kbd>+<kbd>A</kbd> on Mac)
3. Observe how the selection is applied only until the position where the cursor was set.

# Any other information?
Screencast: https://photos.app.goo.gl/VzALmAuaeA37JaD32

**Comment by nightwing** [comment]
This is the intended behavior, as long as mouse is pressed it takes precedence over the keyboard.

But i can see how this can be annoying in some cases. How often does this happen, do you want other commands to release mouse press too, or only selectAll?

**Comment by boghyon** [comment]
Sorry, I should've mentioned that I'm using a touchpad instead of a mouse. When using a mouse, I cannot reproduce the problem. With touchpad however, the `keydown` (65) event is registered first before the `mouseup` event although I certainly raised my tap finger first and then pressed <kbd>Ctrl</kbd>+<kbd>A</kbd>. So the touchpad "feels slow" compared to the mouse. I wonder if it's only my laptop.

> How often does this happen

To me (as a touchpad user), it happened very often at the beginning which was confusing and annoying too. So I had to learn to wait a bit of milliseconds after I raised my Finger (making sure `mouseup` is registered first) and then to apply the shortcut to "select all".

**Comment by boghyon** [comment]
@nightwing Could you reproduce the behavior with your touchpad? If it's only my laptop registering `mouseup` event too slow, I'd close this issue.

**Comment by nightwing** [comment]
I am not nearly fast enough to test that :), but i remember reading about similar issues with trackpads, and other text editors release mouse when keyboard commands are invoked, so i opened https://github.com/ajaxorg/ace/pull/3478 
Could you check if it fixes the issue. (You can test online at
https://rawgit.com/ajaxorg/ace/fix-mouseup-delay/kitchen-sink.html)

**Comment by boghyon** [comment]
https://github.com/ajaxorg/ace/pull/3478 fixes the issue indeed. 👍 Thank you. I like that the behavior now matches with other editors. But I realized that the feature you mentioned in https://github.com/ajaxorg/ace/issues/3471#issuecomment-349407257 is also gone. Is it temporary?

**Comment by nightwing** [comment]
mouse taking precedence is gone permanently, we can't have both at the same time, because there is no way to detect the real mouseup event.
