### ISSUE TITLE
Chrome undo-stack interferes with Ace undo-stack

### ISSUE THREAD

**Issue by mhelvens** [ajaxorg/ace#3472]
### To reproduce

* With Google Chrome, go to https://ace.c9.io/#nav=embedding
* Type "abc" somewhere in the editor.
* Click outside the editor to make it lose focus.
* Press `Ctrl-Z`. (The editor gets focus back.)
* Click outside the editor to make it lose focus again.
* Press `Ctrl-Shift-Z`.

### Observed Behaviour

The letter "c" is added in the editor.

### Expected Behaviour

Nothing should happen.

### Extra info

I'm using Chrome version 62.0.3202.94.

### What we found out

Ace uses an internal `<textarea>` for single characters and binds key-events to that element. If `Ctrl-(Shift)-Z` is pressed without it having focus, the standard Chrome behaviour is triggered, and its undo-stack engaged with the single character Ace stores in the `<textarea>`.

**Comment by nightwing** [comment]
Unfortunately there is not much ace can do about this. Several versions ago chrome made undo manager shared between all text inputs, and there doesn't seem to be a way to prevent this behavior.

**Comment by mhelvens** [comment]
We fixed it by hijacking the ctrl-z and friends from the html document itself:

```javascript
document.addEventListener('keydown', (e) => {
  if (e.code === 'KeyZ' && (e.ctrlKey || e.metaKey) && !e.altKey) {
    e.preventDefault()
    if (e.shiftKey) this.editor.redo()
    else this.editor.undo()
    this.editor.focus()
  } else if (e.code === 'KeyY' && (e.ctrlKey || e.metaKey) && !e.altKey) {
    e.preventDefault()
    this.editor.redo()
    this.editor.focus()
  }
})
```

I understand you wouldn't do that by default, because there may be other inputs on the page for which to preserve normal undo behaviour, but perhaps you can offer it as an option. If not, perhaps this code can help others.

**Comment by nightwing** [comment]
This seems too specific to application logic to add an option to the editor itself. It's better to keep simple. Thanks for posting the example  code.

**Comment by demikhovr** [comment]
Hi!
Found a similar bug. Is it related to the same issue or not?

To reproduce:
1. Go to the page https://ace.c9.io/#nav=embedding
2. Insert at least 2 lines of code
3. Select lines
4. Click outside the editor
5. Press `Cmd+Z` or `Shift+Cmd+Z` several times

As result the last line of code starts to be inserted into the editor n-times.

Chrome 76.0.3809.87
macOs 10.14.5
