### ISSUE TITLE
Unable to write content via Protractor for automated testing

### ISSUE THREAD

**Issue by ashitvora** [ajaxorg/ace#3483]
I am trying to run an automated test and one of the steps of a test case is to clear the Ace Editor and insert text in it.

`element(by.css(["ng-model='aceEditor']")).clear().sendKeys("test.csv");`

Earlier I had regular content editable DIV and I was able to insert text in it but not anymore after switching to Ace Editor.

All I am doing is calling "clear" method on the element and then "sendText" on it. I tried adding "click" method before clear to make sure Ace Editor does have the focus and it did bring the focus to Ace Editor but it still throws an error that element should be user-editable to clear it.

I also tried putting a sleep of 5s before clearing it just in case, Clearing is getting triggered before Ace makes the div contenteditable.

Here's the exact error to be precise.
`Failed: invalid element state: Element must be user-editable in order to clear it.`

**Comment by nightwing** [comment]
try sending ctr a keys to select all instead of calling clear

**Comment by nightwing** [comment]
```js
var KEY = protractor.Key;
var CMD_KEY = isMac ? Key.COMMAND : Key.CONTROL;
element(by.css(["ng-model='aceEditor']")).sendKeys(CMD_KEY, "a", KEY.NULL, "test.csv");
```
