### ISSUE TITLE
getSelectedText() and selection.getRange() do not work with keyboard highlighted selection 

### ISSUE THREAD

**Issue by JohnArrowwood** [ajaxorg/ace#3495]
I have a function used for adding Markdown syntax to the highlighted text, like so:

    replaceSelectedWith( before: string, after: string, initial: string ) {
      if ( ! this.editor ) return;
      let text = this.editor.getSelectedText();
      let isSelected = !!text;
      if ( ! isSelected ) text = initial;
      let range = this.editor.selection.getRange();
      this.editor.session.replace( range, before + text + after );
      if ( ! isSelected ) {
        range.start.column += before.length;
        range.end.column = range.start.column + text.length;
        this.editor.selection.setRange( range );
      }
      this.editor.focus();
    }

This works great when the selection was made using the mouse.  If I hold the shift key while moving with the arrows to highlight a word, and then invoke this function, it doesn't work.  The value of `text` is empty, and the `range` is at the top of the document.

**Comment by nightwing** [comment]
Which version of ace do you use?
I have tried to reproduce the issue by running
```js
setInterval(function() {console.log(editor.getSelectedText())}, 500)
```
in browser console on https://ace.c9.io/#nav=about
hitting tab several times to get into the editor without mouse
pressing `shift-right` to select word

but i didn't manage to get to the state with incorrect value being shown in the console.

One thing that could in principle cause this issue is the $isEmpty flag in https://github.com/ajaxorg/ace/blob/master/lib/ace/selection.js#L207, but i don't see how exactly it can get into the broken state, so any aditional info will be very helpful.

**Comment by JohnArrowwood** [comment]
I am importing `brace` 0.11.0, not sure which version of ace.js it is importing because of the way it works.  I'll submit an issue on that repo.

**Comment by JohnArrowwood** [comment]
Wait...  Maybe the issue is the fact that I'm invoking the function by clicking on a button, which takes the focus away from the editor.  Is there a fiddle somewhere that I can fork and tweak and see if I can reproduce it?

**Comment by JohnArrowwood** [comment]
Nope.  I built a fiddle and confirmed that with the current release, it works correctly.  Will submit an issue on the brace repo.

**Comment by nightwing** [comment]
Interesting, brace  0.11 is using the current version of ace `require("brace").version == "1.2.9"`, could you share your jsfiddle?

**Comment by replaysMike** [comment]
*bump* I'm seeing this with the latest version. When using vertical/column select (ALT + select) and using getSelectedText() from the onSelectionChange event, it's not correctly processing the ranges. When calling getSelectedText() in the onCopy event however it works fine.

**Comment by replaysMike** [comment]
ah, maybe a false alarm. It's related to how fast the event fires, if you slow it down with a `setTimeout()` the selected text comes out correctly when using vertical select (ALT + select).
