### ISSUE TITLE
invalid string in JSON mode doesn't show error tip

### ISSUE THREAD

**Issue by cwtuan** [ajaxorg/ace#3497]
In the [demo](https://ace.c9.io/build/kitchen-sink.html), the string 
```
{
 "a":"
 
 
 123"
}
```
is invalid json. 

But ACE doesn't show error tip like this ![image](https://user-images.githubusercontent.com/3455798/34510305-b6bc7d34-f08d-11e7-8e18-b03f2a459edf.png)

![image](https://user-images.githubusercontent.com/3455798/34510287-9c906056-f08d-11e7-9417-e455e45a422b.png).

**Comment by cwtuan** [comment]
Could anyone help me solve this issue?

**Comment by ghosthope** [comment]
So, it looks like that json_parser have a mistake in string parser.

**Comment by nightwing** [comment]
fixed by https://github.com/ajaxorg/ace/pull/3502

**Comment by cwtuan** [comment]
Thanks for reply.
When will it be released in npm?

**Comment by cwtuan** [comment]
@nightwing 
When will it be released in npm?

**Comment by sujiangyin** [comment]
> In the [demo](https://ace.c9.io/build/kitchen-sink.html), the string
> 
> ```
> {
>  "a":"
>  
>  
>  123"
> }
> ```
> 
> is invalid json.
> 
> But ACE doesn't show error tip like this ![image](https://user-images.githubusercontent.com/3455798/34510305-b6bc7d34-f08d-11e7-8e18-b03f2a459edf.png)
> 
> ![image](https://user-images.githubusercontent.com/3455798/34510287-9c906056-f08d-11e7-9417-e455e45a422b.png).

**i found the same problem,how to solve it please help**
