### ISSUE TITLE
Highlighting text containing umlaut does not highlight other occurrences

### ISSUE THREAD

**Issue by aharwood** [ajaxorg/ace#3498]
I wrote the following code into the Ace editor (on the site homepage):
```
fuge_rule
fuge_rule
füge_rule
füge_rule
```
If you double click on ```fuge_rule``` then the other occurrence is highlighted. If you double click on ```füge_rule``` though then the other occurrence is not highlighted (I expected it to be). It seems the highlighting doesn't work with at least umlauts (didn't test other non-ASCII characters).

**Comment by nightwing** [comment]
Thanks for the report
This is fixed on the master branch as a side effect of https://github.com/ajaxorg/ace/pull/3451.
You can test it at https://rawgit.com/ajaxorg/ace/master/kitchen-sink.html.
