### ISSUE TITLE
split views

### ISSUE THREAD

**Issue by Gozala** [ajaxorg/ace#35]
One of the most useful features of vim are split views.  I would really love to have build-in support for them in ace. 
@gissues:{"order":97.51552795031057,"status":"backlog"}

**Comment by allroadcole** [comment]
I'm using the code that jviereck provided, and it works great. 

However, if I close on of the ace instances, then the other instance gets each key stroke doubled up and repeated.

What do I need to do when one instance is closed to keep the other instances running smooth?

Thanks,
