### ISSUE TITLE
Syntax checking works on src-noconflict but fails on src-min-noconflict

### ISSUE THREAD

**Issue by Sophist-UK** [ajaxorg/ace#3501]
Upgraded to v1.2.9 in order to get syntax checking.

It works when I use src-noconflict, but fails with the following message using src-min-noconflict:
```
Uncaught TypeError: Cannot read property 'start' of undefined
    at u.applyDeltas (worker-php.js:1)
    at Array.<anonymous> (worker-php.js:1)
    at n.r._emit.r._dispatchEvent (worker-php.js:1)
    at e.onmessage (worker-php.js:1)
```

**Comment by nightwing** [comment]
When do  you see this error, i couldn't reproduce the issue with https://plnkr.co/edit/5thiUA2fnYujsneiUXLg?p=preview

**Comment by Sophist-UK** [comment]
I see the error as soon as I start typing into a php or javascript Ace editor box.

I downloaded the 1.2.9 zip file and uploaded the src-min-noconflict and src-noconflict directories to my web site.

When I load ace from src-min-noconflict I get the JS error as soon as I type into the window.

With src-noconflict I don;t get any error message. The only change between the two is changing the directory I load ace from.

**Comment by nightwing** [comment]
The error above can happen if version of ace.js and php-worker are not compatible.
Is there a way to set up a page online where i can debug the issue, or could you try to load ace from https://ajaxorg.github.io/ace-builds/src-min-noconflict/ace.js directly?

**Comment by Sophist-UK** [comment]
Yes - but I deleted the directories containing the previous version and uploaded the new ones. So the contents of src-min-noconflict should be consistent - but apparently they aren't.

**Comment by Sophist-UK** [comment]
I tried loading directly from the link given and it works. I can try downloading the zip file again and try uploading again.

**Comment by Sophist-UK** [comment]
I download ace-builds-1.2.9.zip from the ace builds repo. I have downloaded unzipped and uploaded again. And get the same issue.

So it would appear that it may be a problem with the zipping routine.

**Comment by nightwing** [comment]
Looks like an issue with encoding. 
Uglify js have converted the string
```js
"\x09\x0A\x0B\x0C\x0D\x20\xA0\u1680\u180E\u2000\u2001\u2002\u2003" +
    "\u2004\u2005\u2006\u2007\u2008\u2009\u200A\u202F\u205F\u3000\u2028" +
    "\u2029\uFEFF";
```
to 
```js
"	\n\f\r \u00a0\u1680\u180e\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u202f\u205f\u3000\u2028\u2029\ufeff"
```
which does not work if the script is not served as utf8

**Comment by Sophist-UK** [comment]
UglifyJS v1 has a `--ascii` parameter, UgliftJS3 has `ascii_only` - but perhaps you are already using those.
