### ISSUE TITLE
Vertical scroll bar appears when it shouldn't.

### ISSUE THREAD

**Issue by Sophist-UK** [ajaxorg/ace#3503]
I have Ace set up so that the min-height is exactly 10 rows high and edit box will grow and shrink as lines are added / removed. I start with an empty edit, and add CRs. When I get to 10 lines, there is a 1px white space under row 10 and rows 1-10 are shifted up by 1px and the vertical scroll bar appears (but without any scroller). Add another row to 11 rows and scroll bar disappears. This happens again at 13, 16, 18, 19, 21, 24, 27, 29 etc.

This looks like some sort of boundary issue with pixel calculations but I have been unable to track it down.

**Comment by nightwing** [comment]
How do you set the min height to 10 rows, do you use maxLines/minLines options?

**Comment by Sophist-UK** [comment]
No - I set it to the exact number of pixels needed for the 10 rows. Though perhaps using minLines would be better - I will have to try that.

**Comment by nightwing** [comment]
Must be caused by your code and  code in ace rounding line height differently.
could you find the
```js
size.scrollerHeight - maxHeight + scrollPastEnd < 0 || this.scrollTop > sm.top);
```
line in ace.js and change it `< 1`, and see if the issue goes away?
https://github.com/ajaxorg/ace/blob/master/lib/ace/virtual_renderer.js#L988

**Comment by Sophist-UK** [comment]
Ok - I increased my resize function by 1px and it sort of fixed it.

However, I think my original calculation is correct but is being thrown out by a 1px white gap just above line 1.

**Comment by nightwing** [comment]
Interesting, could you please create a demo/show a page where this happens, there should not be a white gap.

**Comment by Sophist-UK** [comment]
Apologies - looks like another mistake on my part - forgot to clear browser cache after updating Ace.
