### ISSUE TITLE
korean input causes problem in ie11

### ISSUE THREAD

**Issue by circleGiven** [ajaxorg/ace#3505]
hello.
i  had a problem using the editor.
in chrome, korean input good work.
but in ie11, korean input cause problem.
i can't solve this problem.
![image](https://user-images.githubusercontent.com/34206463/34764892-32601eaa-f633-11e7-839b-ac79423c9304.PNG)
Who has had similar problem?

**Comment by nightwing** [comment]
hi, could  you please test on https://rawgit.com/ajaxorg/ace/master/kitchen-sink.html, this issue should be fixed on master by https://github.com/ajaxorg/ace/pull/3463
