### ISSUE TITLE
Bug: editor window highlights any line starting with '#' even if not heading

### ISSUE THREAD

**Issue by laurent22** [ajaxorg/ace#3515]
This was reported [here](https://github.com/laurent22/joplin/issues/98) but it seems to be a bug in ACE as I can replicate it on the [kitchen sink](https://ace.c9.io/build/kitchen-sink.html) too.

When selecting Markdown language, the line should only be highlighted as a heading if there is a space after the '#' before the next character. Otherwise, it should be treated as a plain text line and not highlighted:

![](https://user-images.githubusercontent.com/5920765/34028195-796954de-e1b5-11e7-9668-93c717fb3c63.png)

**Comment by nightwing** [comment]
This was an intentional behavior, since most markdown parsers used to treat that as heading, we will update the mode to match with commonmark.
