### ISSUE TITLE
How to customize the wrapping strategy.

### ISSUE THREAD

**Issue by haozhaodev** [ajaxorg/ace#3517]
Reccently, i embeded ace editor for my project, it's really nice. But i got a problem about wrapping.
Using ace editor as ansible playbook(yaml based text), i want to wrap the yaml file according to following strategy:
 When the yaml file contain `roles` (some concept in ansible) , how can i just display the `roles`part.
![screenshot_2018-01-17_16-28-44](https://user-images.githubusercontent.com/18000467/35032869-8249c0a4-fba3-11e7-8e09-a9d6d9455065.png)

Thereby, cosidering the above example,is it possilbe to display the line after `roles` (11th line) and keep the lines above it hidden but exist?

**Comment by nightwing** [comment]
you can put cursor on line 12 and press `alt-0`(`alt-cmd-0`) on mac, to fold other groups, or you can use the addFold api

```js
var Range = require("ace/range").Range;
editor.session.addFold("...", new Range(0, 0, 10, Number.MAX_VALUE))
```
