### ISSUE TITLE
Cursor displayed incorrectly after scale transformation

### ISSUE THREAD

**Issue by bartosz-m** [ajaxorg/ace#3520]
After applying scale transformation editor cursor is displayed in wrong position and with wrong size, see picture below. I tried either  css transform and svg + foreignObject approach.

screenshot from official [page](https://ace.c9.io/) with css `transform: scale(1.5)'

![obraz](https://user-images.githubusercontent.com/11303115/35184368-ebb198ca-fdf4-11e7-9a8e-4520c4e894fb.png)

**Comment by nightwing** [comment]
The issue with cursor position is fixed on master see https://rawgit.com/ajaxorg/ace/master/demo/transform.html

The mouse position calculation is still wrong, but i have a wip branch for that  https://github.com/ajaxorg/ace/commit/c857e0bf34e173d65dd2cacd14287b7b0701e9e6

**Comment by bartosz-m** [comment]
Thanks for info. Master branch for my use-case works like charm!  :smile:  
Closing now.
