### ISSUE TITLE
[question] Is it possible to customize the editor's slider?

### ISSUE THREAD

**Issue by jamesqo** [ajaxorg/ace#3522]
I want to customize the editor such that when the content is too long to fit into it, the sliders look like the "popsicle stick sliders" you see on mobile devices instead of rectangular ones. Is this possible?

**Comment by nightwing** [comment]
If doing this only on chrome and safari is enough you can use css similar to https://github.com/c9/core/blob/master/plugins/c9.ide.ace/scrollbar.js#L6, for other browsers we need to change scrollbar.js to create custom scrollbar in javascript.

**Comment by ukandrewc** [comment]
There is now an extension for this: https://github.com/ukandrewc/Ace-Scrollbars

**Comment by Rhyan-eduardo** [comment]
> Se fazer isso apenas no chrome e safari for suficiente, você pode usar css semelhante a https://github.com/c9/core/blob/master/plugins/c9.ide.ace/scrollbar.js#L6 , para outros navegadores nós precisa alterar scrollbar.js para criar barra de rolagem personalizada em javascript.

Não esta surgindo efeito, o que poderia ser
