### ISSUE TITLE
[bug] Ace does not scroll upwards when attempting to highlight editor text that's off-screen

### ISSUE THREAD

**Issue by jamesqo** [ajaxorg/ace#3524]
**Repro:**

1. Download [wwwroot.zip](https://github.com/ajaxorg/ace/files/1652751/wwwroot.zip)
2. Open index.html
3. Click the left box and hit Enter until the text goes off the page
4. Click to start a selection and drag the mouse upwards. Hold it at the top of the screen

**Expected:** The editor scrolls upwards

**Actual:** It doesn't

Couldn't find a preexisting issue for this... is it a problem on my side or Ace's side? I noticed that if I replace the editor with a normal div, the scrolling works fine.

**Comment by nightwing** [comment]
There is `autoScrollEditorIntoView` option, but currently that works only if the scrollable parent element is the document root.
In addition to the scrolling issue, using editor with scrollable parent like this will have worse performance, and clicking on the white part of inputContainer blurs the editor.

It may be better to make editor height same as `inputOutputContainer` height, and synchronise scrolling between two editors

**Comment by nightwing** [comment]
It is possible, use something like:
```
<div class=inputOutputContainer style="position:relative;padding:0">
     <div id=editor1 style="position:absolute;top:0;left:0;height:100%;width:50%" ></div>
     <div id=editor2 style="position:absolute;top:0;left:50%;height:100%;width:50%" ></div>
</div>
```
