### ISSUE TITLE
Copy not working on Google Chrome on OS X

### ISSUE THREAD

**Issue by hene193** [ajaxorg/ace#3529]
Similar issue to #2794 

When trying to copy it doesn't copy anything to clipboard. Sometimes some different apps treat the copied item as some sort of invisible character. 
Cut and paste are working just fine. 
OS is OS X 10.13.2
I'm fairly sure that it's chrome related issue  and not OS since it works fine on Firefox and Safari.

I don't really know what details you want to debug this so please ask and I will provide as much detail as possible.

**Comment by nightwing** [comment]
Does this happen in the incognito mode too? this can be caused by chrome addons e.g. `don't fuck with paste`

**Comment by hene193** [comment]
Yea my bad... So sorry to take your time. Stupid me didn't check if any extensions would interfere.
