### ISSUE TITLE
Error loading AWS CloudFormation JSON Schema

### ISSUE THREAD

**Issue by mauroj** [ajaxorg/ace#3531]
I tried to load the AWS CloudFormation JSON schema located at: 
https://d1uauaxba7bl26.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json

I received the following error message: ERROR: Failed to load JSON schema.

Please advise,
Thank you
Mauro

**Comment by nightwing** [comment]
How did you try to load it? The error seems to be unrelated to this repository.

**Comment by mauroj** [comment]
I clicked on Setting->Add Schema 
Then in the Add JSON Schema window I select:
"Specify a public url. Urls which need authentication or do not have CORS enabled cannot be loaded"
and enter the URL: https://d1uauaxba7bl26.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json
after Clicking OK, I received the error message.

**Comment by nightwing** [comment]
On which site dod you do this?

**Comment by mauroj** [comment]
The Google Chrome JSON Editor:

chrome-extension://lhkmoheomjbkfloacpgllgjcamhihfaj/index.html#/

**Comment by nightwing** [comment]
This issue is not related to ace, please report it to https://github.com/josdejong/jsoneditor/
