### ISSUE TITLE
double cursor when pressing enter in internet explorer

### ISSUE THREAD

**Issue by xFailsafeNY** [ajaxorg/ace#3535]
I am getting a weird bug.

In internet explorer 11 when I press enter to get to a new line a double cursor and a bunch of extra whitespace appears at the bottom of the code window.

![image](https://user-images.githubusercontent.com/18269402/35440709-969d2042-026e-11e8-8358-cf3e56ac48ea.png)

Here is my editor code:

`var editor = ace.edit("editor");`
        `editor.setTheme("ace/theme/xcode");`
        `editor.session.setMode("ace/mode/sql");`
        `editor.setAutoScrollEditorIntoView(true);`
        `editor.setOption("maxLines", 30);`
        `editor.setOption("minLines", 5);`
        `document.getElementById('editor').style.fontSize = '16px';`
        `editor.getSession().setUseWrapMode(true);`
        `editor.session.setNewLineMode("windows");`

Any idea how to fix this?

**Comment by nightwing** [comment]
could you please check if https://github.com/ajaxorg/ace/pull/3537 fixes this issue

**Comment by xFailsafeNY** [comment]
@nightwing This was successful when implemented. Thank you for the help.
