### ISSUE TITLE
insert "\n\t" have no effect

### ISSUE THREAD

**Issue by ht1131589588** [ajaxorg/ace#3538]
insert("\n\t")  result equal insert("\n")
I'd better be able to effect of  enter

**Comment by nightwing** [comment]
Could you explain in a bit more detail what do you mean. Currently
`editor.insert("\n")` inserts new line and triggers the autoindent behavior
`editor.insert("\n\t")` inserts new line and a single tab character
`editor.session.insert({row:0, column:1}, "\n")` inserts literal `\n` without triggering autoindent or brace pairing behaviors.

**Comment by ht1131589588** [comment]
My problem has been solved, thank you！
