### ISSUE TITLE
Uncaught Error: couldn't load module github or it didn't call define

### ISSUE THREAD

**Issue by OtoNoOto** [ajaxorg/ace#3541]
Running into the following error when trying to set theme:

_Uncaught Error: couldn't load module github or it didn't call define
    at o (ace.js?ver=1/27/2018 7:02:53 PM:1)
    at ace.js?ver=1/27/2018 7:02:53 PM:1
    at Array.forEach (<anonymous>)
    at ace.js?ver=1/27/2018 7:02:53 PM:1
    at n (ace.js?ver=1/27/2018 7:02:53 PM:1)
    at a (ace.js?ver=1/27/2018 7:02:53 PM:1)
    at a (ace.js?ver=1/27/2018 7:02:53 PM:1)
    at HTMLScriptElement.i.onload.i.onreadystatechange (ace.js?ver=1/27/2018 7:02:53 PM:1)_

Here is how I am calling the editor :

        <script>
            ace.config.set('basePath', 'Content/ace');
            ace.config.set('modePath', 'Content/ace/');
            ace.config.set('themePath', 'Content/ace/');
            var editor = ace.edit("editor-@compId");
            editor.setTheme("github");
            editor.getSession().setMode("csharp");
            editor.setAutoScrollEditorIntoView(true);
            editor.setReadOnly(true);
        </script>

All the files appear to be in place. Any idea what I am doing wrong?

**Comment by nightwing** [comment]
Check in devtools what url ace tries to load, and what is the correct url for theme-github.js.
`editor.setTheme("github");` probably should be `editor.setTheme("ace/theme/github");` and the line for mode should be `editor.session.setMode("ace/mode/csharp");`

**Comment by OtoNoOto** [comment]
@nightwing that was the issue! updating the editor.setTheme & editor.session.setMode paths resolved the issue. I thought I tried both, but I think I was having conflicts between toggling base paths and the former. Everything is working now, thanks!

**Comment by itm-platform** [comment]
Hi there,
I'm having the same issue (*), both using the code below or this one: `editor.setTheme("/ace/theme/github");`

```html
<!-- ACE EDitor Embedded -->

<div id="editor">{"projects":{"tasks":[{"name":"Task",
    "Duration":22},{"name":"Task", "Duration":22}]},
    "risks":{"name":"risk1", "probability": 76}}</div>

<script src="/ace/src/ace.js" type="text/javascript"
    charset="utf-8"></script>

<script>
    ace.config.set("basePath", "/ace/src")
    ace.config.set('modePath', '/ace/src');
    ace.config.set('themePath', '/ace/src');
    var editor = ace.edit("editor", {
        "theme": "/ace/theme/github",
        "mode": "/ace/mode/json"
    })
</script>
<!-- END ACE EDitor Embedded -->
```
(*) console
```console
ace.js:18860 Uncaught Error: couldn't load module /ace/theme/github or it didn't call define
    at afterLoad (ace.js:18860:23)
    at ace.js:3803:27
    at Array.forEach (<anonymous>)
    at ace.js:3802:23
    at _require (ace.js:88:37)
    at req (ace.js:138:24)
    at afterLoad (ace.js:3798:9)
    at HTMLScriptElement.s.onload.s.onreadystatechange (ace.js:3421:17)
```
I copied https://github.com/ajaxorg/ace-builds/tree/master/src into my /ace folder, having, as a result, a `/ace/src` folder containing all files (mode*.js, theme*.js, etc)
