### ISSUE TITLE
Cursor wrongly positioned when line is long

### ISSUE THREAD

**Issue by WiseBird** [ajaxorg/ace#3545]
**Reproduction**: https://jsfiddle.net/WiseBird/agy2msog/

When using some modes (e.g. `groovy` or `sass`) and set `fontSize` in pixels:
```
editor.setOptions({
    fontSize: '14px',
});
window.editor.getSession().setMode('ace/mode/groovy');
```
cursor starts shift when line grows. On the gif at start I past string `a a a a a a ` multiple times, type some chars, move cursor to the left and hit backspace a few times:
![area-1517237032195](https://user-images.githubusercontent.com/1745378/35516168-1aa328fa-051c-11e8-8236-aee04eabb7d2.gif)

There would be no problem if you:
- Change `fontSize` from `px` to `pt`
- Change mode to e.g. `json`
- Will use string without spaces

**Ace version**: 1.2.9
**Browsers**: 61.0.3163.100, 64.0.3282.39
Can't reproduce on FF 58.0

**Comment by idantr** [comment]
Hi we see that also, in 1.3.x when can this be fixed?
