### ISSUE TITLE
Character duplication when attempting to insert diacritic on macOS

### ISSUE THREAD

**Issue by kevinushey** [ajaxorg/ace#3546]
On macOS, it's possible to insert diacritics on the press and hold of a keyboard button when the `ApplePressAndHoldEnabled` option is on (which I believe it is by default). For example, one could insert į by holding down the <kbd>I</kbd> key, and then pressing <kbd>5</kbd>.

When performing this action in the Ace Kitchen Sink + Safari 11.0.2, I see that an initial `i` is inserted (which appears to be the expected behavior in all applications), but the newly inserted į following does not remove the original `i`. See e.g.

![diacritic](https://user-images.githubusercontent.com/1976582/35544965-b769fd94-0521-11e8-9024-24c665c3efc6.gif)

In case you want to try testing yourself but see the character repeated instead of a diacritic menu being shown, you can run

    defaults write -g ApplePressAndHoldEnabled -bool true

in the terminal, and then restart Safari and re-navigate to the Ace kitchen sink.

**Comment by nightwing** [comment]
This should be fixed by https://github.com/ajaxorg/ace/pull/3635, please let us know if you still can reproduce this on http://ace.c9.io. Thanks.

**Comment by kevinushey** [comment]
I can confirm that this appears to be fixed. Thanks!
