### ISSUE TITLE
Selecting all when there is no selection in 1.3.0. Worked fine in 1.2.9

### ISSUE THREAD

**Issue by adrianbj** [ajaxorg/ace#3549]
The code I was using to store selections in 1.2.9 now results in selection of the entire contents if none was selected.

The localStorage JSON looks like:

```
{"selections":{"start":{"row":6,"column":0},"end":{"row":6,"column":0},"isBackwards":false},"scrollTop":0,"scrollLeft":0}
```

And I apply it onload like this:

```
ace.selection.fromJSON(EditorState.selections);
```

This worked fine on 1.2.9.
It still works in 1.3.0 so long as I actually select something - ie so that the `start` and `end` are different , but when they are the same (ie no selection), it results in everything being selected.

Does my code need to be different now, or is this a bug?

**Comment by nightwing** [comment]
This is a regression in v1.3.0, we'll release v1.3.1 asap.
Thanks for reporting.
