### ISSUE TITLE
Extra characters added while inputting Korean text

### ISSUE THREAD

**Issue by laurent22** [ajaxorg/ace#3554]
Initially reported [here](https://github.com/laurent22/joplin/issues/113) but since this is an Ace Editor issue I'm copying it here:

> Hello.
> I've found something strange while I type Korean letters on Joplin.
> I'm using Kubuntu with [Nimf](https://github.com/cogniti/nimf) input framework.
> 
> While Korean letters(consonants and vowels) are assembled, unnecessary space is inserted.
> It's hard to tell, but just please watch the gif I attached.

![](https://user-images.githubusercontent.com/5688288/35857987-22822676-0b7e-11e8-9a39-b1bf69c697f6.gif)

**Comment by nightwing** [comment]
This should be fixed by https://github.com/ajaxorg/ace/pull/3635, please let us know if you still can reproduce this on http://ace.c9.io. Thanks.
