### ISSUE TITLE
Text input issues on Android

### ISSUE THREAD

**Issue by stefaniapedrazzi** [ajaxorg/ace#3555]
While writing some text on an Android device, the word that is being written is displayed twice with an visible space offset that make it hard to read.

I tested on 3 different Samsung smartphones and I can reproduce this issue also in the Ace Kitchen Sink example.

**Comment by stefaniapedrazzi** [comment]
I tried to understand what is the problem and it seems that the two texts come one from the TextInput and one from the system composition (that also displays an extra character at the beginning).

Playing with the CSS only I was not able to fix the problem properly.
But adding hiding programmatically the Composition text when inserting some text seems to fix the issue.

What I tried is simply to set the color of 'ace_cursor' class to transparent in `textinput.js:onCompositionStart` and reset it in `textinput.js:onCompositionEnd`:

```
var onCompositionStart = function(e) {
    if (inComposition || !host.onCompositionStart || host.$readOnly) 
        return;
    var cursor = document.getElementsByClassName("ace_cursor");
    cursor.style.color = 'transparent';
....
}
var onCompositionEnd = function(e) {
     if (!host.onCompositionEnd || host.$readOnly) return;
     // console.log("onCompositionEnd", inComposition &&inComposition.lastValue)
     var cursor = document.getElementsByClassName("ace_cursor");
     cursor.style.color = '';
...
}

**Comment by AbijeetP** [comment]
Facing a similar issue on our side with Samsung devices.

**Comment by nightwing** [comment]
This should be fixed by https://github.com/ajaxorg/ace/pull/3635, please let us know if you still can reproduce this on http://ace.c9.io. Thanks.
