### ISSUE TITLE
XML Mode: Attributes starting with a colon shouldn't be an error

### ISSUE THREAD

**Issue by jpayne** [ajaxorg/ace#3556]
Ace is showing an error in XML mode for attributes that have a colon as the first character:

`<foo :bar="hello, world!">`

However, this is valid XML.

**Comment by apb2006** [comment]
Not valid in XML but ok in HTML5. In XML  `:` is used to indicate namespaces. 
See https://stackoverflow.com/questions/925994/what-characters-are-allowed-in-an-html-attribute-name
