### ISSUE TITLE
Vim: implement ex-command history?

### ISSUE THREAD

**Issue by kevinushey** [ajaxorg/ace#3558]
In Vim, one can recall a history of ex-commands (the commands executed after typing <kbd>:</kbd>) by pressing the Up and Down keys after typing <kbd>:</kbd>. Is this something that Ace's Vim mode could implement as well?

http://vimdoc.sourceforge.net/htmldoc/options.html#'history'

(Let me know if this is the right place to place Vim feature requests or if this should be routed upstream somewhere)

**Comment by nightwing** [comment]
This was implemented in Codemirror recently. I'll merge the change from upstream.

**Comment by kevinushey** [comment]
Awesome! Thank you for this quick merge.
