### ISSUE TITLE
Official Ace.js for angular 4/5?

### ISSUE THREAD

**Issue by AlgeriaSoft** [ajaxorg/ace#3565]
Hello
Is there an official project for ace.js compatible with angular 4/5

**Comment by AlgeriaSoft** [comment]
Hello @nightwing

**Comment by nightwing** [comment]
There is no official project for any version of angular.
What are you looking for specifically,  a simpler way to load ace with webpack, a wrapper angular component to not use ace api, or something else?

**Comment by AlgeriaSoft** [comment]
Ace.js library compatible with angular 4/5 and typescript

**Comment by AlgeriaSoft** [comment]
@defunkt 
@josh 
@ericallam 
@probablycorey

**Comment by nightwing** [comment]
this should work as is, if you see any issues please report the details.

**Comment by AlgeriaSoft** [comment]
thanks
