### ISSUE TITLE
https://ace.c9.io https problem solution

### ISSUE THREAD

**Issue by w3suli** [ajaxorg/ace#3567]
![acec9io-https](https://user-images.githubusercontent.com/20889555/36265407-7587f04c-126f-11e8-98a5-c3f118d8f916.png)

Change branch, lively-web, colorsublime png link:
http://www.branchcms.com/layout/images/branch-brand-logo-2.png
http://lively-web.org/core/media/lively-web-logo.png
http://colorsublime.com/img/ColorSublime_logo.png
to
https://www.branchcms.com/layout/images/branch-brand-logo-2.png
https://lively-web.org/core/media/lively-web-logo.png
**Delete:** http://colorsublime.com/img/ColorSublime_logo.png **ELIMINATED**
Then the padlock icon will be green :).

**Comment by nightwing** [comment]
Done! thanks for the tip.
