### ISSUE TITLE
configuration wiki hard to read (and even find)

### ISSUE THREAD

**Issue by daKmoR** [ajaxorg/ace#3572]
hey,

https://github.com/ajaxorg/ace/wiki/Configuring-Ace

is the only place I found which explains how to configure (e.g. set options) for the editor.

the info is not really nice as you will have to (for most of them) guess if they need a string, a true/false or whatever value.

also some options are missing like `navigateWithinSoftTabs`...

here are some updates
```
showPrintMargin: true | false (defaults to true)
printMargin: number (defaults to 80)
useSoftTabs: true | false (defaults to false)
navigateWithinSoftTabs: true | false (defaults to false)
```

**Comment by nightwing** [comment]
I have updated that page and added a link to it in https://ace.c9.io/#nav=howto, let me know if you think it still needs some cleanup, maybe moving to ace.c9.io?

**Comment by daKmoR** [comment]
nice :) all options with types :)

thxxx :)

I think if they were directly on the page instead of the link it would be way easier to find... or maybe add the link also to the code (probably it's just me but if there is code I mostly ignore the rest hehe)

```js
// pass options to ace.edit
ace.edit(element, {
    mode: "ace/mode/javascript",
    selectionStyle: "text"
    // all options can be found here https://github.com/ajaxorg/ace/wiki/Configuring-Ace
})
```
