### ISSUE TITLE
this.onChangeFold.bind undefined in EditSession function

### ISSUE THREAD

**Issue by markentingh** [ajaxorg/ace#3574]
I checked the object properties for this.onChangeFold, and the object contained many properties & methods (init, id, EditSession, session, explorer, etc.), but it did not contain a bind method. Found within the EditSession function

```
this.on("changeFold", this.onChangeFold.bind(this));
```

I am using EditSession the same way it is used in the documentation, 

```
var EditSession = require("ace/edit_session").EditSession;
```

I see no reason why onChangeFold should be missing the `bind` function, unless it relies on jQuery, which I am not using.

**Comment by nightwing** [comment]
`onChangeFold` should be a function defined in https://github.com/ajaxorg/ace/blob/master/lib/ace/edit_session.js#L251, so should have a bind method, unless something changes it.

Try to isolate the issue by creating plnkr/jsbin reproducing it,

**Comment by nightwing** [comment]
Did you manage to find a solution for this issue?
I am closing this as there is not enough information to reproduce it, but if it is still happening please let me know and i'll be happy to take another look.

**Comment by markentingh** [comment]
Yes I believe it was a simple mistake on my part.
