### ISSUE TITLE
TypeScript usage (any guidance?)

### ISSUE THREAD

**Issue by 43081j** [ajaxorg/ace#3592]
Hi,

More a request for people in similar situations to offer some guidance than an issue.

How are people currently using ace in typescript projects?

I'm falling into these issues (anywhere i mention `the types`, i mean those in the definitelytyped repo):

* I can't import `ace` because the types don't export a module
* I can't load ace in the browser (via `ace-builds`) and use a `<reference ..>` to the types because everything is declared in `AceAjax` which doesn't seem to exist anywhere except in the type declarations (it should all be on `ace`)
* I can't import ace from `ace-builds` because the types are under `ace` so the two mismatch

I work with a webpack/TS project so i should just be able to bundle ace like any other node module... by importing it (`import * as ace from 'ace'`). maybe the types are just strangely written or im missing something here?

**Comment by nightwing** [comment]
Hi,
Try using https://www.npmjs.com/package/brace which seems to work because type definition file is in the same package.
We are planning to add first class support for typescript, and better type definitions, but it will take a couple of months.

**Comment by 43081j** [comment]
do you need any help with that? maybe we could at least ship some type definitions (i could do a PR) which assume a global (`ace` in global namespace).

im not really sure what the thought behind the definitelytyped ones was... its all thrown into an `AceAjax` namespace that doesn't exist anywhere for anyone 🤔

**Comment by nightwing** [comment]
A pull request would be very helpful:)

**Comment by 43081j** [comment]
Fixed in #3605.
