### ISSUE TITLE
The ext/textarea plugin unconditionally focuses upgraded textarea

### ISSUE THREAD

**Issue by msevcenko** [ajaxorg/ace#3602]
If the ACE editor is initialized via the ext/textarea plugin, the plugin after upgrading the area to editor unconditionally focuses the editor.

This may be quite annoying for the users, page may contain many widgets, even many ACE editors, and there might be no reason why (the last of the) editors should be focused and scrolled to.

It would be better if the auto-focus could be turned off, or better may be driven by the autofocus property of the underlying textarea, for example.

**Comment by nightwing** [comment]
Does https://github.com/ajaxorg/ace/pull/3603 fix this issue?

**Comment by msevcenko** [comment]
Well, there may be some issues regarding page lifecycle - is the element focused at the time it is being upgraded to the editor? It might be focused too late, which is not propagated to the editor.

I would suggest to focus the editor also if the textarea has autofocus set, and might not be focused yet by the browser at the time of upgrade. I.e.

```var isFocused = document.activeElement == element || element.autofocus;```

Otherwise it solves my case, but I'm not sure if it does not break someone else's code who relies on the unconditional focus.
