### ISSUE TITLE
 Ace build files fingerprinting

### ISSUE THREAD

**Issue by ManojkumarV** [ajaxorg/ace#3606]
Is there any way to fingerprint ace editor build files fingerprinted with md5 hash value?
There are a lot of ways to fingerprint JS and CSS files (For example: gulp-rev, grunt-rev). Is there any built in way to fingerprint ace build files using Makefile.dryice.js

**Comment by nightwing** [comment]
There is no way to fingerprint files using Makefile.dryice.js.

**Comment by ManojkumarV** [comment]
@nightwing So is there any other way to fingerprint files while building? Fingerprinting files will help reduce loading time in browser. Unchanged files need be loaded every time if it is fingerprinted.

**Comment by nightwing** [comment]
I think you should be able to use the same method you use to fingerprint the rest of files in your project.
You only need to run `ace.config.setModuleUrl("ace/mode/javascript", <hash for mode-javascript.js file>)` afterwards.

Let me know if i misunderstand the issue.

**Comment by ManojkumarV** [comment]
@nightwing If we need to run ace.config.setModuleUrl("ace/mode/javascript", <hash for mode-javascript.js file>) for every file then we need to do for each and every dynamic import used by ace.js file. 
Usually all the files should be fingerprinted and the references of those files used in the main file or any other file should be changed based on the finger print value. 
For example if the mode-javascript.js file is fingerprinted to mode-javascript-fingerprint.js then the value must be modified based on the fingerprint value wherever it is used. 
If an image file java.png is fingerprinted to java-123.png then the css using it should be changed like below. 
Original Code:
.java_class {
   background-image: url("java.gif");
}
Changed Code: 
.java_class {
   background-image: url("java-123.gif");
}

**Comment by nightwing** [comment]
> @nightwing If we need to run ace.config.setModuleUrl("ace/mode/javascript", ) for every file then we need to do for each and every dynamic import used by ace.js file.

you need to do this for every file you rename, ace does not load images and css, and all the files it uses can be configured with setModuleUrl
