### ISSUE TITLE
autocomplete identifierRegexps doesn't work in live-autocomplete

### ISSUE THREAD

**Issue by maxHoo** [ajaxorg/ace#3608]
Hi, 

I am using custom completer with `identifierRegexps` that wish to capture characters with dots for example: `class.func,` when input `class.` it pop out all its functions names under it.
It works well when set this custom completer to `BasicAutocomplete`, but when enable live, it does not give prefix for the first dot end, which is, when input `c`, prefix is `c`; input `c.`, dont have prefix; input `c..`, prefix is `c..` . I simply modified the `ID_regex` and use it in `identifierRegexps`.

here is my code:

```
var customCompleter = {
      identifierRegexps: [/[a-zA-Z_0-9\.\-\u00A2-\uFFFF]/],
      getCompletions: function(editor, session, pos, prefix, callback) {
          if (prefix.length === 0) { callback(null, []); return }
          let matches = findSuccessor(prefix, json)
          callback(null, matches);
       }
    };
    langTools.addCompleter(customCompleter);
    editor.setOptions({enableLiveAutocompletion: 'customCompleter'});
```

I have not checked all source coed, but it is odd since it works fine in basic mode.

**Comment by 380847438** [comment]
mark ，same problem

**Comment by maxkrieger** [comment]
Bumping this!

**Comment by kroggen** [comment]
It appears that this can solve the problem:

```js
editor.getCompletionRegex = () => /[a-zA-Z_0-9\.\$\-\u00A2-\uFFFF]/;
```

source [here](https://stackoverflow.com/questions/28920998/custom-autocompleter-and-periods)
