### ISSUE TITLE
Lua 'end' keyword not closing functions, etc.

### ISSUE THREAD

**Issue by develephant** [ajaxorg/ace#3615]
Hi,

This is must have started with a recent release, as on older webapp I have is not exhibiting the same behavior. Essentially, the 'end' keyword for Lua is not finalizing any functions, loops, conditionals, etc.

It looks like so when editing:

```lua
function hello()
    --a comment
    end

```

You can actually see the behavior currently in the [kitchen sink demo](https://ace.c9.io/build/kitchen-sink.html) in Lua mode.

Any suggestions? Thanks in advance.

**Comment by nightwing** [comment]
The change in behavior was introduced in https://github.com/ajaxorg/ace/commit/a73d81a09efa83a0dc4b2a967e1ac30b89d95339, not reverting it now because the behavior was pretty broken before that too, and needs a a better fix.

**Comment by develephant** [comment]
Hi,

Thanks for the reply. That's a shame, I guess I'll have to figure out how to use the older build in my app as it was working fine before. Not sure what _zoowii_ was referring to.

Cheers
