### ISSUE TITLE
Initializing editor a second time results in runaway CPU and browser hang

### ISSUE THREAD

**Issue by adrianbj** [ajaxorg/ace#3620]
This started with v1.3.1 and is still an issue with 1.3.2, but was fine with 1.2.9.

I have ace running in a modal window. The first display on that window is fine, but if I close and reopen (without a browser reload), everything hangs.

I haven't spent any real time trying to debug - thought I'd post here first to see if you might have any idea of something that changed in 1.3.1 that might be responsible.

Perhaps it has to do with how I load ace.js (https://github.com/adrianbj/TracyDebugger/blob/8645b3868286375e9f0faa60ad908c2a7d55d839/panels/ConsolePanel.php#L498) but as I mentioned it still works fine with 1.2.9.

Please let me know if you need more info and thanks for your time.

**Comment by nightwing** [comment]
https://github.com/ajaxorg/ace/pull/3624/commits/6afe590ec224f767989c55dc9dbfa8c197ca94ce#diff-1d3adf2538ef07e28972236f3a26311aR926 likely should fix this issue, but it is hard to tell for sure without a live page where it can be tested.

**Comment by adrianbj** [comment]
Hi @nightwing - thanks for the quick response. Unfortunately though it doesn't seem to have helped. If you don't have any other ideas on what it might be, let me know and I'll see what I can do about getting you access to a test site.

**Comment by nightwing** [comment]
I don't have any other ideas unfortunately, a test site would be very helpful.

**Comment by adrianbj** [comment]
Hi @nightwing - it turns out this is related to https://github.com/ajaxorg/ace/issues/3700

I do a division on the height of the container div vs the renderer line height:

```
var ml = Math.round(document.getElementById("tracyConsoleCode").offsetHeight / tracyConsole.tce.renderer.lineHeight);
tracyConsole.tce.setOptions({
    maxLines: (ml - 1),
    minLines: (ml - 1)
});
```

Because `renderer.lineHeight` is sometimes zero, it causes everything to crash.

Using your suggestion in that other issue seems to work ok, but is there an alternate approach we should be using, or could the ACE core take care of this better somehow?

```
tracyConsole.tce.renderer.on("afterRender", function() {
    var ml = Math.round(document.getElementById("tracyConsoleCode").offsetHeight / tracyConsole.tce.renderer.lineHeight);
    tracyConsole.tce.setOptions({
        maxLines: (ml - 1),
        minLines: (ml - 1)
    });
});
```

**Comment by nightwing** [comment]
@adrianbj what are you trying to do? seems like `tracyConsole.tce.container.height = document.getElementById("tracyConsoleCode").offsetHeight + "px"` should work the same

**Comment by adrianbj** [comment]
PS - keep in mind that I am using splitjs (https://nathancahill.github.io/Split.js/) to make it easy to change the relative heights of the code and results panes and when the users adjusts this split, it calls a resize function which contains that code shown above, so the `minLines` and `maxLines` values are changed that way.

**Comment by nightwing** [comment]
sorry, i meant `tracyConsole.tce.container.style.height= ` (container here should be simply the dom node for which ace is created)
Why do you want the height of the editor to be an exact multiple of lineHeight? setting the height on container and calling editor.resize() should work better.

**Comment by adrianbj** [comment]
> sorry, i meant tracyConsole.tce.container.style.height= (container here should be simply the dom node for which ace is created)

Right - that does seem to work - thanks.

> Why do you want the height of the editor to be an exact multiple of lineHeight?

That's not really what this is doing - what it's doing is setting the number of lines to match what will fit in the available height of the editor. The reason for this is that I want splitjs to handle the scrolling of the editor pane rather than ACE.

Here's a screencast of the interface in action which maybe helps to explain why I am doing what I am. Not saying there's not a better way still though.

![console-demo](https://user-images.githubusercontent.com/871211/43795166-61994790-9a35-11e8-9cab-ca7c4e85ff51.gif)

Just in case you're interested, the code for this is available here:
https://github.com/adrianbj/TracyDebugger/blob/master/panels/ConsolePanel.php

This version does not include my changes today to allow me to update from ACE v1.2.9, but this shows the approach I am using for integrating ACE with splitjs and usin AJAX to execute code and return the output in the results pane.

**Comment by nightwing** [comment]
Then I think you do not need to use minLines and maxLines

you could even set tracyConsoleCode to position:relative and tracyConsoleEditor to height:100%, and then only call `tracyConsole.tce.resize(); `

As for the issue of infinite loop, https://github.com/ajaxorg/ace/commit/17cde9a852eeb7ce09a7760ad229f21268bb4be8 should prevent it in this case.

**Comment by adrianbj** [comment]
Thanks for the tip regarding setting to 100% etc - that approach seems to be working fine. 

The minLines check to prevent a possible infinite loop is also a great addition - thanks.

I think it's probably time I close this issue - thanks for all the tips and feedback and of course for ACE!
