### ISSUE TITLE
v1.3.2 missing on CDN

### ISSUE THREAD

**Issue by cnsgithub** [ajaxorg/ace#3621]
Version has been released and is listed here but responds with HTTP 404: https://cdnjs.com/libraries/ace/1.3.2

E.g. https://cdnjs.cloudflare.com/ajax/libs/ace/1.3.2/ace.js

**Comment by nightwing** [comment]
This seems to be an issue with cdnjs https://github.com/cdnjs/cdnjs/issues/12634 which should be fixed soon.
