### ISSUE TITLE
Scrollbars broken on firefox quantum

### ISSUE THREAD

**Issue by mikolajpp** [ajaxorg/ace#3625]
I am embedding ace editor inside div with height, width set to 100%.
Scrollbar have the wrong size and are unusable, making it impossible to scroll to the end of the content.

Here is the gif of the situation:
https://imgur.com/a/dkuRm

The entire gif is the containing div. Once I generate enough lines for scrollbals to appear, they appear with wrong size, shifted upwards. Morover, trying to scroll down eventually fails with strange jumps. 

The same issue exists for horizontal scrollbars.

**Comment by mikolajpp** [comment]
I should also add, that bug does not appear when the size of the container is set explicitly in pixels. 
It only appears once the height or width are set to percentage values.

**Comment by nightwing** [comment]
Does the same happen in chrome, and could you show a webpage or plunkr/jsbin reproducing the issue?

This sounds like a bug in firefox, but maybe there is some workaround for it.

**Comment by mikolajpp** [comment]
Yes, it does happen in chrome, but does not happen in brave (the difference might that brave seem to not use GTK scrollbars. At least they look different to the system ones in gnome 3)

It is a webapp i am developing: https://github.com/mikolajpp/plato-elm, but I can try 
to make a demo page trying to reproduce this.

**Comment by mikolajpp** [comment]
Here is clip of the same app working perfectly well in brave: https://imgur.com/a/gmiH8

**Comment by mikolajpp** [comment]
I am unable to replicate the issue in a simple example, such as this: https://jsfiddle.net/rY37e/616/
Unsure what could be causing this, but at least we know for sure it is a browser dependend behaviour

**Comment by mikolajpp** [comment]
And here is more detailed clip of the bug on firefox: https://imgur.com/a/CuFyy

**Comment by nightwing** [comment]
Maybe size of the editor container changes after ace.edit is called?
If so you need to call editor.resize(), to let ace update it's cached size.

**Comment by mikolajpp** [comment]
And here is demonstration, the bug will even disappear if the browser window is resized slightly:
https://imgur.com/a/o1JaY

The container size is definitely fixed and ready before the ace is called: which takes place after all DOM nodes are in place.

**Comment by mikolajpp** [comment]
@nightwing But you are right that ace is miscalculating size for some reason. 
When I examine the ace root node it is oversized compared to the containing container. Resizing browser window fixes that.

Could there be some rase condition wrt ace constructor and DOM nodes acquiring size?
In any way, that would be very strange, because the container node never could have size of the oversized ace node.

**Comment by nightwing** [comment]
try running `window.removeEventListener("resize", embedded_editor.container.env.onResize)`, then opening devtools won't fix the problem anymore

**Comment by nightwing** [comment]
that's most likely a race condition, try adding a breakpoint at https://github.com/ajaxorg/ace/blob/master/lib/ace/virtual_renderer.js#L341, to see what size the node has when ace measures it.

**Comment by mikolajpp** [comment]
Correct, I did that and the problem persist. Here is what happens to ace root node wrt container node size: https://imgur.com/a/6hGeC

Right now I am using webpack. Since I only got packed JS, do I have to switch to externally source ace bundle?

**Comment by mikolajpp** [comment]
Ok, I have confirmed that just calling editor resize after the app boots fixes the bug. So indeed this is a race condition.

**Comment by mikolajpp** [comment]
After investigating further, It happens that only 'ace_content' has incorrent size (too large). All other component of ace interface has the correct size and fit inside the container node.

**Comment by mikolajpp** [comment]
We can close this one. It was caused by some issues with font loading slowing down application of css styles.
