### ISSUE TITLE
Garbage character in mobile korean keyboard not google keyboard

### ISSUE THREAD

**Issue by ubbox** [ajaxorg/ace#3629]
Hello,

I'm using Ace Editor for mobile application made by ionic.
I want to use autocomplete functionality, but it doesn't work because of garbage character in start point.
That is, if I input alpahbet in mobile application or browser by korean keyboard(default samsung keyboard), this problem always happens. (There is small box in start point.)
![input](https://user-images.githubusercontent.com/10172785/38028057-e94c5f10-32bb-11e8-9be1-a066cbe7de5e.PNG)

Because of this problem, Autocomplete is not working. If I use google default keyboard, there is no problem and there is no garbage character.
I can't figure out what is problem. So please give me some advice .

p.s> In kitchen-sink demo, this problem also happens.
![input2](https://user-images.githubusercontent.com/10172785/38082320-81d0cd84-3370-11e8-9a1d-b973e2371c9d.PNG)

Thanks,

**Comment by nightwing** [comment]
This should be fixed by https://github.com/ajaxorg/ace/pull/3635, please let us know if you still can reproduce this on http://ace.c9.io. Thanks.
