### ISSUE TITLE
Ace editor breaks when textarea in html

### ISSUE THREAD

**Issue by aloksharma1** [ajaxorg/ace#3630]
hello all,

i am using ace editor to alter my html or other related code on fly (html,css,js & sometimes php/cshtml).
So i have forms in my page too, but whenever i try to edit a page in ace editor which have form elements specifically textarea the editor breaks up as shown in screenshot. i think the issue is the editor being render & replacing the textarea containing html.

but how to rectify the issue, please help.
![screencapture-ace-editor](https://user-images.githubusercontent.com/4345706/38098209-08eb9abe-3395-11e8-8fc8-491f6c0b8590.png)

**Comment by nightwing** [comment]
if you are setting editor value by outputing some text in html, you need to make sure that the text you add to html is escaped, if you use php htmlspecialchars will do that.

**Comment by aloksharma1** [comment]
hi ,
i am using asp.net mvc and using Html.Raw function which i think does the escaping for me, but i am still getting this issue. any other alternatives or maybe some javascript params to cope with the issue?
thanks again

**Comment by nightwing** [comment]
Html.Raw does the exact opposite, you need to use Encode  https://msdn.microsoft.com/en-us/library/system.web.mvc.htmlhelper.encode(v=vs.118).aspx#

**Comment by aloksharma1** [comment]
i tried encode just now my whole html messed up , i dont think encode will work in my case

**Comment by aloksharma1** [comment]
weird i just tried HttpUtility.HtmlDecode and that actually fixed the output for me so ace is not breaking up now, but now i need to check if the saved data is going in correct forma or not, i will update on this after my tests.

**Comment by aloksharma1** [comment]
i got it now it was not the textarea but the escaping in cshtml @**@ causing the issue, thanks for the help and pointers :+1:
