### ISSUE TITLE
Violation errors in chrome js console with verbose logging

### ISSUE THREAD

**Issue by Sophist-UK** [ajaxorg/ace#3633]
If I enable Verbose logging in chrome's javascript console I get the following messages:

`ace.js:1 [Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
t.addListener @ ace.js:1
t.addMouseWheelListener @ ace.js:1
l @ ace.js:1
w @ ace.js:1
t.edit @ ace.js:1
initializeAce @ fabrikeditor.js:81`

`ace.js:1 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
t.addListener @ ace.js:1
t.addTouchMoveListener @ ace.js:1
l @ ace.js:1
w @ ace.js:1
t.edit @ ace.js:1
initializeAce @ fabrikeditor.js:81`

`ace.js:1 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
t.addListener @ ace.js:1
t.addTouchMoveListener @ ace.js:1
l @ ace.js:1
w @ ace.js:1
t.edit @ ace.js:1
initializeAce @ fabrikeditor.js:81`

Latest or recent version of ace, minified no conflict, php 7.1

**Comment by nightwing** [comment]
Unfortunately there doesn't seem to be anything  we can do about these, the non-passive event listeners are required since ace uses custom logic for scrolling, and needs to call prevent default

**Comment by sherlock1982** [comment]
Looks like if you add `{ passive: false }` that will silence the warning.

**Comment by BrandonXLF** [comment]
All you have to do is replace `return e.addEventListener(t,n,!1);` with `return e.addEventListener(t,n,{passive:!1},!1);`.

**Comment by nielsboogaard** [comment]
It seems the packaged build (for version 1.4.7) does not contain this fix although it is mentioned in the release notes?
