### ISSUE TITLE
How to make multiple chunk of lines readonly in ace editor

### ISSUE THREAD

**Issue by GNSubrahmanyam** [ajaxorg/ace#3634]

**Comment by nightwing** [comment]
there is no builtin method for that
But https://stackoverflow.com/questions/39640328/how-to-make-multiple-chunk-of-lines-readonly-in-ace-editor has working implementation, https://github.com/ajaxorg/ace/issues/3080 has some more information too

**Comment by GNSubrahmanyam** [comment]
@nightwing please make official demo as soon as possible.

**Comment by GNSubrahmanyam** [comment]
@nightwing  @fjakobs @gjtorikian @jviereck @danyaPostfactum @joewalker @wcandillon  
 
please make official demo as soon as possible.

**Comment by gjtorikian** [comment]
No.

**Comment by GNSubrahmanyam** [comment]
Any updates on this

**Comment by vianna274** [comment]
Any updates on this?
