### ISSUE TITLE
Soft wraps broken after 1.3.3, does not redraw when line overflows

### ISSUE THREAD

**Issue by zebzhao** [ajaxorg/ace#3642]
Hi, thank you for the great library. I noticed that the rendering for soft wraps is broken due to commits after 1.3.3 release.

Steps to reproduce:

1. Turn on soft wraps for editor (free)
2. Resize window so that line wraps
3. Start typing in the middle of the file until line overflows (sometimes it takes overflow of 2 lines)
4. Notice the line after does not get shifted down as the previous line overflows, the next line and the overflow line overlaps.

Tested with the latest commit a0b94508f7a08ce5025a8ebdd47d6e17904f8798

Suspect it has something to do with commit 992fa76e9ecea38ba2e81c2877e1014f0eb55eba

**Comment by nightwing** [comment]
This was caused by https://github.com/ajaxorg/ace/pull/3623, https://github.com/ajaxorg/ace/pull/3644 should fix it.
Thanks for the detailed bug report!
