### ISSUE TITLE
markClean() > Type a symbol > Undo > Isclean() == false

### ISSUE THREAD

**Issue by MrMoronIV** [ajaxorg/ace#3643]
session..getUndoManager().markClean();
session.getUndoManager().isClean() is true

Then when I type a single symbol and directly undo that action by pressing Ctrl+Z it's not marked as clean.

session.getUndoManager().isClean() is false

This is confusing since it's obviously the same state as when it was marked as clean. Is there a way to "fix" this or am I missing something?

**Comment by nightwing** [comment]
which version of ace do you use? I couldn't reproduce this on ace.c9.io, by trying to do that manually, or using 
```js
editor.session.$undoManager.markClean();
editor.insert("a")
editor.undo()
editor.session.$undoManager.isClean()
```
in browser console

**Comment by MrMoronIV** [comment]
Version 1.3.3

I do this to store my multiple sessions
  ```
  EditSessions[sessionID] = new EditSession('');
  aceEditor.setSession(EditSessions[sessionID]);
  aceEditor.setValue(data.content, -1);
  aceEditor.session.setUndoManager(new ace.UndoManager());
```

Then for the markclean and isclean:
```
EditSessions[sessionID].getUndoManager().markClean();
EditSessions[sessionID].getUndoManager().isClean()
```
Without that new ace.UndoManager line there is no undo functionality at all.

**Comment by nightwing** [comment]
i've triedrunning the following code in the browser console on ace.c9.io 
```js
EditSessions = {}; sessionID = 1;
EditSession = ace.EditSession
UndoManager = ace.UndoManager
EditSessions[sessionID] = new EditSession('');
aceEditor = editor
aceEditor.setSession(EditSessions[sessionID]);
aceEditor.setValue("data.content", -1);
aceEditor.session.setUndoManager(new ace.UndoManager());

EditSessions[sessionID].getUndoManager().markClean();
EditSessions[sessionID].getUndoManager().isClean() // true
editor.execCommand("insertstring", "abc")
editor.undo()
EditSessions[sessionID].getUndoManager().isClean() // true
```
but `isClean()` returns `true` as expected. 
Could you help me to modify this code to reproduce the issue?

**Comment by MrMoronIV** [comment]
I found the problem, I check if the the document isClean when there is a change triggered by aceEditor:

```
  EditSessions[sessionID].on('change', function() {
    var content = EditSessions[sessionID].getValue();
    saveFileToLocalStorage(sessionID,content);
    setUnsavedTab(sessionID);
  });
function setUnsavedTab(sessionID)
{
  console.log('setUnsavedTab isClean',EditSessions[sessionID].getUndoManager().isClean());
 // always returns false
  if(EditSessions[sessionID].getUndoManager().isClean())
    $("#"+sessionID).removeClass('tab_unsaved');
  else
    $("#"+sessionID).addClass('tab_unsaved');
}
```
So when I add a timeout to my console.log it actually returns the expected value after using Ctrl+Z:

```
  console.log('setUnsavedTab isClean',EditSessions[sessionID].getUndoManager().isClean()); // false
  setTimeout(function() {
  console.log('setUnsavedTab Delayed isClean',EditSessions[sessionID].getUndoManager().isClean());
   },50); // true!
```

Apparently the change event is triggered before the undomanager did its job. Is there any other best practice for this check or is the setTimeout the way to go?

**Comment by nightwing** [comment]
use the input event as shown in https://github.com/ajaxorg/ace/blob/master/demo/toolbar.html#L41

**Comment by MrMoronIV** [comment]
That seems to work, what is the difference in behavior of on(input) compared to on(change) that I should be aware of?

**Comment by nightwing** [comment]
input is fired after a timeout
