### ISSUE TITLE
Can readonly be applied to a session?

### ISSUE THREAD

**Issue by MrMoronIV** [ajaxorg/ace#3646]
So that when I switch sessions the editor becomes readonly or not depending on that session setting?

Or do I need to set the editor.setReadOnly(); to true and false manually every time the session is switched?

**Comment by DontShootMe** [comment]
Maybe you can use :

```javascript
     Editor.on("changeSession", function(Object e)) 
```
> Emitted whenever the EditSession changes.

> Argument e => Required. 
   An object with two properties, oldSession and session, that represent the old and new EditSessions.

**Comment by MrMoronIV** [comment]
Yeah doing it manually is the only option since the readonly flag isn't something that is stored in the session itself apparently.

However, this is worked around long ago, you answered a fairly old question ;)
