### ISSUE TITLE
MS Edge random sting freezes whole page

### ISSUE THREAD

**Issue by etouchesSlav** [ajaxorg/ace#3653]
Hi there,
I have discovered some issue when using an editor on MS Edge v41 - not being able to end typing a random string and after that no other elements on a page can be changed or clicked. 
Please note this works fine in Edge v40 and other browsers ( like Chrome or Mozilla FF )

So, not so sure whether it is a MS Edge problem or problem with the editor.

Also attaching here a video that might potentially better describe my problem
https://screencast-o-matic.com/watch/cFfqFkbheW

**Comment by nightwing** [comment]
This should be fixed by https://github.com/ajaxorg/ace/pull/3635, please let us know if you still can reproduce this on http://ace.c9.io.
