### ISSUE TITLE
how to  escape snippet  code like $user.loginid

### ISSUE THREAD

**Issue by tonyyls** [ajaxorg/ace#3657]
using ace for  custom ide.  add snippet  like :
++++++++++++++++++++++
```
snippet $user
	$user.id  
```
++++++++++++++++++++++
when  enter  $user + `Tab`  in  ace ,  it  displays    `.id`   ,  how can i do ?

I want to display `$user.id`  in ace .

thanks.

**Comment by nightwing** [comment]
use backslash
```
snippet $user
	\$user.id  
```
