### ISSUE TITLE
Any plan to support Racket-lang syntax?

### ISSUE THREAD

**Issue by impvd** [ajaxorg/ace#3659]
I just browse https://github.com/ajaxorg/ace/tree/master/lib/ace/mode ,and could not find the syntax file for racket (https://racket-lang.org/)

Is there any plan to support it?

Or any tutorial teaching us to write such a mode? In that case I could write it my self.

**Comment by nightwing** [comment]
There is no plan to support it so far, but a pull request will be welcome.
The tutorial teaching about modes can be found at https://ace.c9.io/#nav=higlighter, you probably can start by modifying existing lisp or clojure modes, and i'll be glad to answer any questions you may encounter.
