### ISSUE TITLE
Scrollbar covers values in intellisense window

### ISSUE THREAD

**Issue by Hourglasser23** [ajaxorg/ace#3662]
Hi we found this issue while using great ace editor - we are satisfied with it and it helps us a lot so thanks in advance. 

Steps to reproduce: 
1) even on https://ace.c9.io/ in free line write this value: **asf**
2) press **ctrl + space** to evoke intellisense
3) hit **left arrow** 

Actual result: 
You can see that for sometime values in intellisense window are **covered** by scrollbar 

Expected result: 
All values are **visible** 

Additional information: 
I found out that window with values width shrinks after while. It lower its value from 280px to 263px. 
Probably some kind of invalidate happens there and then it gets correct.

**Comment by nightwing** [comment]
you can set width of the popup using css
```
.ace_autocomplete {
    width: 40em!important;
}
```

**Comment by nightwing** [comment]
Closing, but please comment if the suggestion above doesn't work well for you and you think the autocompleter must be changes to work differently.

**Comment by Hourglasser23** [comment]
.ace_autocomplete {width: 400px !important;} this is default option. 
Setting different value to width will not help.
