### ISSUE TITLE
JSX Highlighting: keywords inside JSX tags are unnecessarily highlighted

### ISSUE THREAD

**Issue by radubl** [ajaxorg/ace#3663]
Hey. Thanks for the JSX support and the JSX highlighter. 

I noticed that when writing text inside HTML(JSX) tags, some javascript keywords like 'function', 'const', 'for' are highlighted as such, whereas they should be free-text.

Steps to reproduce:
1. go to https://ace.c9.io/build/kitchen-sink.html
2. Select JSX
3. Paste this:
```jsx
class Test {
    render() {
        <div>
        I have some extra highlighted words like const var function for
        </div>
    }
}
```
Expected behaviour: 'const var function for' are white.
Actual behaviour:  'const var function for' are treated as JavaScript keywords.

**Comment by nightwing** [comment]
jsx mode is for https://github.com/jsx/JSX which is not related to react jsx.
javascript mode correctly highlights html tags out of box

**Comment by radubl** [comment]
Thanks for the reply. You are absolutely right! I've been sitting on this longer than I'd like to admit. Hope this thread will help others that happen to confuse the JSX language with react JSX.
