### ISSUE TITLE
Diff viewer support

### ISSUE THREAD

**Issue by ManojkumarV** [ajaxorg/ace#3680]
I've been using ace editor for a long time and one feature I'm missing in it is the in built diff support. Code mirror and Monaco editor has in-built diff viewer support. 
There is a separate [library](https://github.com/ace-diff/ace-diff) that support diff view on ace editor but are there any plans to add diff view support for ace editor by ace editor?

**Comment by wupengFEX** [comment]
Good issue, we have the same demand!
