### ISSUE TITLE
Cursor position is reset after focus is lost from the editor

### ISSUE THREAD

**Issue by ashitvora** [ajaxorg/ace#3685]
I am trying to add content to Ace Editor dynamically and after the content of Ace Editor is added, focus is lost and cursor position is set to the beginning of the Editor. How can we disallow Ace Editor from resetting the cursor position.

**Comment by nightwing** [comment]
Sounds like you are deleting the editor and creating a new one,or using session.setValue instead of insert
But it is hard to say what specifically goes wrong, please create a page demonstrating the problem, and i'll try to give a better answer

**Comment by nightwing** [comment]
Closing, but please comment if you still see the issue

**Comment by GNSubrahmanyam** [comment]
@nightwing Same issue i am also facing same issue. I am using uiace https://github.com/angular-ui/ui-ace

**Comment by shubh0709** [comment]
> I am trying to add content to Ace Editor dynamically and after the content of Ace Editor is added, focus is lost and cursor position is set to the beginning of the Editor. How can we disallow Ace Editor from resetting the cursor position.

were you able to solve the issue ??
