### ISSUE TITLE
Marker (used with Anchor) doesn't always refresh automatically when highlightActiveLine is false

### ISSUE THREAD

**Issue by b-treebeard** [ajaxorg/ace#3687]
See behaviour here: http://jsfiddle.net/xtz2gs5L/1/

When inserting text before the marker, the marker stays put and doesn't immediately update. A delete operation refreshes the editor and the marker "snaps" to the correct position.

This behaviour goes away without the `editor.setHighlightActiveLine(false);`

**Comment by nightwing** [comment]
Currently updateFrontMarkers/updateBackMarkers are not called automatically

As a workaround you can use
```js
editor.on("change", editor.$onChangeBackMarker)
```
to redraw backmarkers after every change.
