### ISSUE TITLE
Incorrectly calculating text width for some fonts

### ISSUE THREAD

**Issue by strandloper** [ajaxorg/ace#3695]
I discovered a bug while using Markdown Monster and raised [issue \#394](https://github.com/RickStrahl/MarkdownMonster/issues/394) (now closed) there. I was informed that this would be a bug in the ACE Editor control they use and it was suggested I raise an issue here.

It appears that the Fira Code Light font is wider in its bold form than in its regular form, affecting the kerning offsets. This results in incorrect cursor positioning after using keystrokes to move over a word or to the end of a line. This screenshot shows the result of pressing Shift-Enter from the home position on a line rendered in bold text.

![image](https://user-images.githubusercontent.com/668433/42025952-2cfd731e-7ac6-11e8-958b-d477134a464b.png)

I have tested using the following fonts

- Consolas
- Envy Code R
- Fira Code
- Fira Code Light

and it is only with Fira Code Light that the problem is seen.

I have also tested editing the same file in Sublime Text 3 with the MarkdownEditing plugin so the line is rendered bold. In that case, despite using Fira Code Light at the same size, the problem is not seen; this would suggest the problem lies in the editor code rather than in the font.

**Comment by MehbubRashid** [comment]
For me, Fira code regular also produces the same problem
