### ISSUE TITLE
Please support Solidity syntax highlighting (widely used for smart contract/blockchain coding)

### ISSUE THREAD

**Issue by bynariu-ofer** [ajaxorg/ace#3697]
Solidity (https://github.com/ethereum/solidity)
Is the language in which smart contracts for the Ethereum network are written. its syntax is fairly similar to javascript and has highlighting support already in vim, emacs, atom, sublime etc.

**Comment by thewhiterabbit** [comment]
I second this. I'm working on a web based IDE after the tronsmartcontract.space scam fiasco.  Dual purpose for Ethereum and Tron.

**Comment by nightwing** [comment]
There is a third party module that provides soldity syntax highlighting https://github.com/raphaelhuefner/ace-mode-solidity. Try asking the author to contribute the mode to ace, if you think it would be easier to use that way.
