### ISSUE TITLE
Possible regression on 1.3 - lineHeight initially set to 0

### ISSUE THREAD

**Issue by JackuB** [ajaxorg/ace#3700]
In Ace-diff I got reports of an issues with Ace `^1.3` https://github.com/ace-diff/ace-diff/issues/34

Figured out that the issue was that `editor.renderer.lineHeight` is initially set to `0` and you need to wait for a next tick to get a correct `lineHeight` - see the patch https://github.com/ace-diff/ace-diff/pull/44/files#diff-1fdf421c05c1140f6d71444ea2b27638

It used to be a synchronous operation in `<1.3.0`

**Comment by nightwing** [comment]
This indeed have become async because we started to use ResizeObserver when it is available.

One workaround is to use the "afterRender" event similar to https://github.com/c9/c9.ide.scm/blob/master/diff/twoway.js#L486
