### ISSUE TITLE
Using Coffee script throws errors into console

### ISSUE THREAD

**Issue by Filipos** [ajaxorg/ace#3704]
From version of Ace 1.3.3 worker for coffee script tries load helpers.js file which was merged into mode/coffee/coffee.js 2 years ago ( to version 1.2.0 ). Due to this coffee worker throws error and doesn't work at all.

You can see errors in console it in your demo https://ace.c9.io/build/kitchen-sink.html ... switch to coffee - checking syntax does not work.

**Comment by nightwing** [comment]
Fixed in 1.4
