### ISSUE TITLE
Not correct paths for theme/mode

### ISSUE THREAD

**Issue by fortcms** [ajaxorg/ace#3706]
I am include Ace dynamically.
`success: (function(file, i){
							return function(){
								if(i == fc){
									if(onsuccess != undefined){
										onsuccess.call();
									}
									return;
								}else{
									includejs();
								}
							}
						})(file, i),`

Ace Editor searches for files in the root ((
They are not there...

**Comment by nightwing** [comment]
use `ace.config.set("basePath", "url to the folder that contains ace.js")`

**Comment by fortcms** [comment]
@nightwing it's work
