### ISSUE TITLE
Autocomplete doesn't work with symbols

### ISSUE THREAD

**Issue by TrevorThomas4** [ajaxorg/ace#3711]
I have a domain specific language that I am using ace to help write. In the DSL, we have actions that might look something like like: 

```
{runAction: MyAction} 

{/runAction}
```

I am running into a problem with autocomplete not working when what I want to autocomplete starts with a non alpha numeric character. 

So in my code I have something the following 
```
var thingsToAutocomplete = ['apples', 'bananas', "{runAction: }\n\n{/runAction: }"]; // The braces are intentional
var langTools = ace.require('ace/ext/language_tools');

var staticWordCompleter = {
    	getCompletions: function(editor, session, pos, prefix, callback) {
        	var wordList = thingsToAutocomplete;
        	callback(null, wordList.map(function(word) {
        		// console.log("word = " + word);
        		// console.log("prefix= " + prefix);
            	return {
                	caption: word,
                	value: word,
                	meta: "static"
            	};
        	}));

    	}
}

	editor.completers = [staticWordCompleter]

	editor.setOptions({
	    enableBasicAutocompletion: true, 
	    enableSnippets: true,
    	    enableLiveAutocompletion: true
	});
```

Now, when I start typing `ap`, "apples" comes up and I can click it and it inserts "apples" which is correct. However, when I type `{ru`, my "{runAction: }" shows up but when I click it, it becomes `{{runAction: }` (Note the extra `{`). 

Is there a way around this?

**Comment by qwertie** [comment]
I think `identifierRegexps` in your Completer is supposed to be used to solve this kind of problem. [The feature is broken right now](https://github.com/ajaxorg/ace/issues/3337#issuecomment-591518308) but I proposed a workaround at the link.

**Comment by masbaehr** [comment]
Came across this issue. Is there any solution or workaround for this? 

e.g when typing "t" but the auto-completion says "[title]" it correctly writes [title]
but when typing "[t" it will write [[title]
