### ISSUE TITLE
ResizeObserver stay alive when editor is destroyed

### ISSUE THREAD

**Issue by amiramw** [ajaxorg/ace#3714]
We have a flow where the editor is destroyed and then immediately new one is created on the same dom element.
This cause a race condition that some times cause error in chrome: 
```
TypeError: Cannot read property 'getTokens' of null
```

This happens because in chrome there is ResizeObserver and it is triggered in FontMetrics in order to observe changes on the dom element however it never disconnected.

Maybe it should be disconnected in the destroy?https://github.com/ajaxorg/ace/blob/57218c220f2e276fc81080f28158075f05026ece/lib/ace/layer/font_metrics.js#L164-L168 ?

So when the editor is destroyed and then immediately created the observer is called with the new editor and since there is no `bgTokenizer` on the session yet it fails on the call to `getTokens`.

BTW, `$fontMetrics` is instanciated in `VirtualRenderer` constructor. Shouldn't it be destroyed in its destroy method?
https://github.com/ajaxorg/ace/blob/9b5b63d1dc7c1b81b58d30c87d14b5905d030ca5/lib/ace/virtual_renderer.js#L1661-L1664

**Comment by nightwing** [comment]
Thanks for the detailed report, https://github.com/ajaxorg/ace/pull/3715 should fix this.

Btw after destroying you probably should do `container.textContent = ""`, to not leave nodes created by the previous editor in the new one.
