### ISSUE TITLE
char encoding, ÿ tp unknown char icon

### ISSUE THREAD

**Issue by bmatusiak** [ajaxorg/ace#3716]
char encoding, ÿ tp unknown char icon

![capture](https://user-images.githubusercontent.com/1822932/43068830-81ad7ee6-8e39-11e8-9a53-78c4f05fcdd0.PNG)

in the picture,,  left c9, right github

as github show the correct character

c9 will save incorrect letter

i believe the same hex value is \xff

**Comment by nightwing** [comment]
Is the file encoded in utf8 or some other encoding? c9 supports only utf8

**Comment by bmatusiak** [comment]
yup your right.. its ANSI, sorry
