### ISSUE TITLE
Application with several canvas layers

### ISSUE THREAD

**Issue by markusmoenig** [ajaxorg/ace#3726]
I have a problem integrating Ace into my app which consists of two canvas layers. One has z-index of 0, the other id 1 (a 3D layer which displays some 3D widgets as an overlay).

The problem is that the ace widget is visible but only the column on the left (line numbers) receives mouse and keyboard input, the main content body does not receive mouse and keyboard input.

When I remove the canvas at z-index 1 it all works.

Any ideas ? I assume ace internally uses canvas elements itself ?

Thanks

**Comment by nightwing** [comment]
Ace doesn't use canvas elements. 
The most likely causes of the issue can be: another element covering ace, or some css rule on the page interfering with ace styles, but it is hard to say for sure without seeing the issue. I could give more helpful answer if you could show a page reproducing the issue.

**Comment by markusmoenig** [comment]
I found a workaround by giving both the 2D and 3D canvas the z-index of 0 but initializing the webgl canvas later, so the 3D layer is on top of 2D and Ace works. As soon as I give the 3D layer a higher index ace does not work anymore (the left column part works, the body not).

I guess this is a very specialized use case, so I will close the issue for now. Thanks.
