### ISSUE TITLE
Hide errors in gutter but still show line numbers?

### ISSUE THREAD

**Issue by ebower12** [ajaxorg/ace#3733]
I'm using the Ace Editor in a component that lets a user write custom Terraform code. Since there's no Terraform mode I just have it set in JSON mode, which means there will obviously be a lot of errors. Setting showGutter={false} hides both the errors and the line numbers. Is there a way I can hide the errors in the gutter without also hiding the line numbers?

**Comment by nightwing** [comment]
To disable error checking you can use
```js
editor.session.setOption("useWorker", false)
```

But terraform mode was added in version 1.4 of ace released today https://github.com/ajaxorg/ace/blob/master/lib/ace/mode/terraform.js

**Comment by ebower12** [comment]
Well that works! Thanks a lot!
