### ISSUE TITLE
[v1.4.0] Issue on autocomplete

### ISSUE THREAD

**Issue by ecarriou** [ajaxorg/ace#3734]
Since I have updated my project with the last version of ace, I get sometimes this error: `TypeError: Cannot read property 'length' of undefined`.

The issue seems to be located in `popup.js` file at [this line](https://github.com/ajaxorg/ace/blob/ca4db19cf35ce44f57ffb2f211a9c3febeb1c0b1/lib/ace/autocomplete/popup.js#L210) and the line above.

The issue is due to the fact that previous check on `data.caption` has been removed. It seems we have to used `caption` variable instead.

**Comment by nightwing** [comment]
This should be fixed in 1.4.1, thanks for the report
