### ISSUE TITLE
Insert into ace editor without getting pushed to Undo Stack

### ISSUE THREAD

**Issue by ManojkumarV** [ajaxorg/ace#3743]
Is it possible to insert text to a position or remove a range without getting updated in Undo Stack.
In a collaborative environment the change from the other client should be updated in the document without getting added to Undo stack. 
Is there any way to achieve it?

**Comment by nightwing** [comment]
use markIgnored method similar to  [c9.ide.collab/ot/document.js#L740-L742](https://github.com/c9/core/blob/e9490da4e721915df42d1c468ea7c98f879fbb11/plugins/c9.ide.collab/ot/document.js#L740-L742)

```js
var rev = session.$undoManager.startNewGroup(); // start new undo group
... // apply the edit 
session.$undoManager.markIgnored(rev); // mark the new group as ignored
```
