### ISSUE TITLE
[v1.4.1] An invalid match in the autocomplete can occurred 

### ISSUE THREAD

**Issue by ecarriou** [ajaxorg/ace#3744]
An invalid match in the autocomplete can occurred sometimes (maybe due to a mix between the previous and current behavior with autocomplete).

Let’s say we have `require` in the list of word.

- If user types `r`, **r**equire is shown (first letter in bold): which is correct.
- If user types `re`, **re**quire is shown (2 first letters in bold): which is correct.
- If user types `ree`, **ree**quire is shown (3 first letters in bold), which is incorrect, the match is not correct. I suspect that the match finds the last character `e` as a correct occurrence.

**Comment by nightwing** [comment]
Fixed in https://github.com/ajaxorg/ace/pull/3745, thanks for the report!
