### ISSUE TITLE
XML broken wrapping

### ISSUE THREAD

**Issue by mikeyT42** [ajaxorg/ace#3748]
Sometimes, the wrapping of XML text is weird. All of the text is layed out on top of each other.
![ace editor](https://user-images.githubusercontent.com/15900384/44117177-85300094-9fe0-11e8-87d8-602b5e67ac73.PNG)
Here is the original XML for your reference:
```
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
    <SOAP-ENV:Header xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"/>
        <SOAP-ENV:Body xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
            <SOAP-ENV:Fault xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
                <faultcode>SOAP-ENV:Server</faultcode>
                <faultstring xml:lang="en">Fault</faultstring>
                <detail>
                    <cause>UnrecoverableClientError</cause>
                    <code>SchemaError</code>
                    <desc>validation failure for CreateOpenShipmentRequest Error:cvc-datatype-valid.1.2.1: '' is not a valid value for 'dateTime'.
cvc-type.3.1.3: The value '' of element 'v13:ShipTimestamp' is not valid.</desc>
                </detail>
            </SOAP-ENV:Fault>
        </SOAP-ENV:Body>
    </SOAP-ENV:Envelope>
```

**Comment by nightwing** [comment]
How do you initialize the editor? Could you show the page where this happens, or create a demo on jsbin?

**Comment by mikeyT42** [comment]
`// Initialize the ace code editor
        for (var i=1; i <= 4; i++) {
        	var id = 'tab' + i + 'text';
            var editor = ace.edit(id);
            ContentWidget.editors[i-1] = editor;
            editor.setTheme("ace/theme/twilight");
            editor.session.setMode("ace/mode/xml");
        }`
