### ISSUE TITLE
Bug in Chrome with Unicode text consisting of more then 1 byte per character

### ISSUE THREAD

**Issue by gvozdetsky** [ajaxorg/ace#3753]
cursor position shows on the wrong place

**Comment by gvozdetsky** [comment]
In Firefox and Safari everything goes well, thus this bug is specific for Chrome

**Comment by pakmanlh** [comment]
I am not sure what are you pointing at exactly, could you provide some examples? Thanks

**Comment by YellowAfterlife** [comment]
The issue was most likely related to non-fixed-width glyphs breaking cursor position (rather than glyph being multi-byte), which can differ per-browser depending on how they decide the font to inherit missing glyphs from
