### ISSUE TITLE
Scroll is way too hard on Mobile (touch)

### ISSUE THREAD

**Issue by mayrinck** [ajaxorg/ace#3754]
Scrolling vertically and horizontally on Ace in a smartphone is really hard, specially if you have big files opened (more than 1500 lines). You can take about a minute scrolling down to reach the line 1000, and the scrolling is not that soft as in any other scrollable element in a page. 

Is there any way to fix this on my side or this is something to be patched on a future release?
(This is related to touch scrolling, using a mouse is just fine).

**Comment by XanderLuciano** [comment]
Agreed, it needs a bit of "weight" and velocity to it's scrolling, instead of just stopping when you lift your finger.
