### ISSUE TITLE
Is there a way to convert / preserve line-breaks to/from spaces when copy text between a single / multiline editor instance?

### ISSUE THREAD

**Issue by jbarker4682** [ajaxorg/ace#3755]
We have a UI where we present a small, single-line Ace editor instance that allows the user to quickly write a short, simple query using our custom mode.  We have just added the ability to open a dialog containing a larger, multi-line editor that allows the user to write more complex queries.  However, when closing the editor and copying the text back to the single-line editor, the carriage returns are stripped, and if the user re-opens the multi-line popup, all of their formatting is destroyed...

Is there any way, maybe using something like a custom token, to identify a carriage return (/r/n) so that it renders as an empty space in the single-line version, but renders as a hard-return in the multi-line version?

Thanks!

**Comment by jbarker4682** [comment]
<img width="393" alt="screen shot 2018-08-19 at 7 05 08 pm" src="https://user-images.githubusercontent.com/1664024/44314804-7d01b380-a3e2-11e8-9c7f-7ccf6684c93a.png">
<img width="245" alt="screen shot 2018-08-19 at 7 04 55 pm" src="https://user-images.githubusercontent.com/1664024/44314805-7d9a4a00-a3e2-11e8-85be-fc36bd677c52.png">

**Comment by nightwing** [comment]
One way to achieve this is to change the split method on the doc that you want to be one-lined

```js
session.doc.$split = function(text) { return [text]  }
```

another is to change the renderer to render lines  after each other, but that is a bit harder to do, and with that home/end/down/up will treat lines as separate.

**Comment by jbarker4682** [comment]
Ok, so it turns out that this wasn't an issue with the ace editor... someone had written an onChange method that was retroactively stripping line returns after the editor was updated...
