### ISSUE TITLE
embeded javascript in html code not showing in editor

### ISSUE THREAD

**Issue by xrcwrn** [ajaxorg/ace#3759]
I am loading code from database which contains embeded javascript in html code.
like below 
```
editor.setValue(`<!DOCTYPE html>
<html>
<body>

<p id="demo"></p>

<script>
var x = 100 + 50;
document.getElementById("demo").innerHTML = x;
</script>

</body>
</html>
`, 1);
```
this code is not showing in ace editor

**Comment by nightwing** [comment]
this can happen if the `editor.setValue` call is itself in a `<script>`, so `</script>` in the value closes the outer tag.
