### ISSUE TITLE
Copy Paste is not working in Tablet

### ISSUE THREAD

**Issue by quelist** [ajaxorg/ace#3761]
I embedded the ace editor in our site and copy paste is working smoothly from the laptop but it is not working in touch devices(tablet). I am using iBall slide for testing purpose. 

Is there a way around for this or this is something to be patched in the next version?
Screenshot here [https://imgur.com/a/eFfWb64](https://imgur.com/a/eFfWb64 )

**Comment by hawkeye116477** [comment]
Duplicate, unfortunately it wasn't fixed a few years ago => `https://github.com/ajaxorg/ace/issues/2265`. It was in 2014, so rather, we can no longer count on a patch.

**Comment by Elvincth** [comment]
+1

**Comment by sagarwalzade16** [comment]
Hi, have you found any solution to paste in ace editor in table? I am facing same issue and i need to fix it asap.

**Comment by kerkenit** [comment]
+1
