### ISSUE TITLE
Show custom message(alert) in editor 

### ISSUE THREAD

**Issue by sns2009** [ajaxorg/ace#3763]
I looked for a way to show custom message(alert) inside editor and didn't found one. 
It could be useful when you want to show user than max number of characters exceeded , or show some hint, based on what was typed. 
Do Ace editor provide this kind of functionality?

**Comment by nightwing** [comment]
see this stackoverflow question https://stackoverflow.com/questions/26695708/how-can-i-add-placeholder-text-when-the-editor-is-empty/26700324
