### ISSUE TITLE
GitHub changelog on tagged releases

### ISSUE THREAD

**Issue by vanillajonathan** [ajaxorg/ace#3767]
When releases are tagged on GitHub it would be nice if it came with a changelog.

https://github.com/ajaxorg/ace/releases

Example:
https://github.com/github/fetch/releases

**Comment by vanillajonathan** [comment]
Please make releases!

**Comment by andrewnester** [comment]
Has been fixed here https://github.com/ajaxorg/ace/commit/189ccfb2122a8a1f84a5d0eee21d88a07d561b75

**Comment by andrewnester** [comment]
we didn’t release new version after the change was made, next ones will appear there
