### ISSUE TITLE
Ignoring certain warnings

### ISSUE THREAD

**Issue by Ugoku** [ajaxorg/ace#3768]
Cross-posted from https://github.com/ajaxorg/ace-builds/issues/134 where it got no replies :(

Consider the following code:

```
html {
    box-sizing: border-box;
}
*, *:before, *:after {
    box-sizing: inherit;
}
body {
    background: rgba(0, 0, 0, 0.6);
    padding: 1em 40px;
    width: 40em;
}
main {
    color: hsl(215, 75%, 50%);
}
```

This gives the following warnings:
* The box-sizing property isn't supported in IE6 and IE7
* The universal selector (*) is known to be slow
* Using width with padding can sometimes make elements larger than you expect
* Fallback background (hex or RGB) should precede RGBA background
* Fallback background (hex or RGB) should precede HSL background

Is there a way to ignore these warnings?
* I don't care about IE at all (our users use different browsers)
* The universal selector [is not slow](https://www.paulirish.com/2012/box-sizing-border-box-ftw/)
* I know about the padding, that's why I'm using `box-sizing: border-box`
* RGBA/HSL are very well supported, I don't need a fallback background

**Comment by nightwing** [comment]
Sorry i have missed the issue on ace-builds.

This issue is caused by an old version of csslint, in the next version we'll remove built-in linters, and allow installing linters separately from the editor.

until that you can use

```js
editor.session.$worker.call("setDisabledRules", ["box-sizing|ids|order-alphabetical|universal-selector|fallback-colors|box-model"]) 
```
to reconfigure csslint.

**Comment by Ugoku** [comment]
Awesome, thanks!
