### ISSUE TITLE
disable/hide replace button ('+') in search box when editor is in read only mode

### ISSUE THREAD

**Issue by gnijuohz** [ajaxorg/ace#3773]
I noticed that when the editor is in read only mode, the search box still can be expanded into a find replace box, which doesn't quite make sense.

I could use css to hide the button but I think this could be addressed more properly in ace itself. Currently there seems to be no way to turn on regex search by default as well. (correct me if I'm wrong :))

Is this something open to a pull request? I could spend some time on this to make the search box more customizable.

**Comment by nightwing** [comment]
Yes, the pull request for this would be welcome.
