### ISSUE TITLE
Get value of div php

### ISSUE THREAD

**Issue by Rapprogtrain** [ajaxorg/ace#3774]
I am using ace.js to create own online editor. So i want to set all values from texarea to db, but i dont know how. To make textarea in Ace.js you nede to write `<div id="editor"></div>`. But sql cant take this value. Where is the problem? 
```php
<div id="htmlEditor"></div>
<div id="line"></div>
<div id="cssEditor"></div>
<div id="line2"></div>
<div id="jsEditor"></div>
<div id="line3"></div>
</div>	
<div id="result-block">
<iframe id="result" frameborder="0"></iframe></div></div>
	<script src="js/app.js"></script>
		  </body>
		  </html>
			<script language="javascript">

var htmlEditor = ace.edit('htmlEditor');
var cssEditor = ace.edit('cssEditor');
var jsEditor = ace.edit('jsEditor');
var htmlSave = (localStorage.getItem("htmlSave"));
var cssSave = (localStorage.getItem("cssSave"));
  var jsSave = (localStorage.getItem("jsSave"));
    $.ajax({
        type: "POST",
        url: "index.php",
        data: { htmlSave: htmlSave, cssSave: cssSave, jsSave: jsSave }
    }).done(function(data) {
			console.log(htmlSave);
        });
</script>
<?php
if(isset($_POST['submit']))
{
	$htmlSave = $_POST['htmlSave'];
	$cssSave = $_POST['cssSave'];
	$jsSave = $_POST['jsSave'];
	$insert=$db->query("INSERT INTO `field`(`html_field`, `css_field`, `js_field`) VALUES ('$htmlSave',
	'$cssSave', '$jsSave')");
} ?>
```

**Comment by Rapprogtrain** [comment]
> 
> 
> you probably need to use getValue method on the editor like `var htmlSave = htmlEditor.getValue()`

i used but this didnt help me. With localstorage i can get value but with htmlSave = htmlEditor.getValue() i cant get

**Comment by nightwing** [comment]
`htmlEditor.getValue` get's the value from the editor, if you already have the correct value, then the issue is not related to ace.

**Comment by Rapprogtrain** [comment]
> 
> 
> `htmlEditor.getValue` get's the value from the editor, if you already have the correct value, then the issue is not related to ace.

 i already got got the value from localStorage, but how ti insert it in db?

**Comment by nightwing** [comment]
Inserting into db is not related to ace, and is the same for any string, unfortunately i don't know enough php to help you, try asking on stackoverflow where someone may know php.

**Comment by Rapprogtrain** [comment]
> 
> 
> Inserting into db is not related to ace, and is the same for any string, unfortunately i don't know enough php to help you, try asking on stackoverflow where someone may know php.

i asked many times but ...
