### ISSUE TITLE
vim: cursor is no longer transparent

### ISSUE THREAD

**Issue by kevinushey** [ajaxorg/ace#3777]
E.g. on kitchen sink:

![screen shot 2018-09-21 at 1 57 59 pm](https://user-images.githubusercontent.com/1976582/45905765-60241b80-bda6-11e8-94cc-d78e710192b4.png)

This is with the 'Ace' cursor style. If I switch to 'wide', the cursor is transparent again but no longer flashes (which I believe is the expected behavior for 'wide'; just thought it's worth pointing out that there's a difference in transparency between the two cursor types).

**Comment by kevinushey** [comment]
Similar issue with Emacs keybindings:

![screen shot 2018-09-21 at 2 00 48 pm](https://user-images.githubusercontent.com/1976582/45905845-c6a93980-bda6-11e8-9620-e3df08f0c0cb.png)

although the underlying character is still visible in that case (although just barely)

**Comment by nightwing** [comment]
I have changed the color of the cursor to rgba, which seems to fix the issue.
