### ISSUE TITLE
How to make  the autocomplete and suggestions show up as we type

### ISSUE THREAD

**Issue by arunkumar413** [ajaxorg/ace#3783]
Currently I have press the ctrl+space for the suggestions to showup. Is it possible to trigger the code complete suggestions as we type?

**Comment by arunkumar413** [comment]
Seems like we have to just enable the liveautocomplete option. I just tried it but it isn't suggesting some methods like document.querySelector etc,.

**Comment by arunkumar413** [comment]
It's been quite  a while since I raised this issue. Did anyone had a chance to look into this?

**Comment by nightwing** [comment]
Sorry for missing this issue, the option is indeed `enableLiveAutocompletion`, 
But unfortunately, similar to `enableBasicAutocompletion` it performs only general autocompletion based on words in the editor, and is not very smart.

**Comment by arunkumar413** [comment]
Any ideas or suggestions on how to make it smart?

**Comment by arunkumar413** [comment]
For me it's enough if it's smart enough to show suggestions like all the web API methods and properties 
https://developer.mozilla.org/en-US/docs/Web/API/Document
