### ISSUE TITLE
When focused or pressed key inside editor the page scrolls to top

### ISSUE THREAD

**Issue by andylacko** [ajaxorg/ace#3788]
hello, i have ace editor configured like this

```
  window.htmlEditors[moduleId] = ace.edit(`htmlEditor-${moduleId}`);
  window.htmlEditors[moduleId].session.setMode("ace/mode/html")
  window.htmlEditors[moduleId].setOptions({
    enableBasicAutocompletion: true,
    selectionStyle: "text",
  })
  if (typeof moduleData !== 'undefined') {
    window.htmlEditors[moduleId].session.setValue(moduleData.html)
  }
```

- when I focus on mobile into editor, it scrolls top automatically
- when key is pressed window scrolls to top instantly

any idea? Pretty useless with this issue, my version is 1.4.1

one more thing noticed, after clicking, it selects the part upward from where the cursor clicked

another thing noticed! after removing **.ace_text-input-ios** it works fine

**Comment by schmave** [comment]
I just noticed this issue as well. Here's a JS Bin showing the behavior:

https://jsbin.com/rezuye

As @andylaci said, if I manually remove the "ace_text-input-ios" class from the textarea tag, it works fine. 

It looks like this bug was introduced between ACE versions 1.1.1 and 1.2.0.

**Comment by nightwing** [comment]
removed ace_text-input-ios in  https://github.com/ajaxorg/ace/pull/3824/commits/69da3f3a6b1caf7c971b9f425562fb5124d49ac2
