### ISSUE TITLE
ace_selected is not marked in autoComplete popup

### ISSUE THREAD

**Issue by suhasdeshpande** [ajaxorg/ace#3799]
## plunker to reproduce this 
http://plnkr.co/edit/6MVntVmXYUbjR0DI82Cr?p=preview

## Why? 
I recently updated ace to 1.4.x from 1.2.x. For autocomplete, I used to see ```ace_selected``` on first row of the autoComplete. Code sets ```autoSelect = true``` 

As seen in screenshot, row appears to have selection style but not the ```ace_selected``` selector. There seems many event listers that add/remove mutate this selector. I was not sure if this is bug with my implementation or ace. So I checked with the plunker and it had the same behavior. 

![screen shot 2018-10-16 at 4 52 43 pm](https://user-images.githubusercontent.com/606167/47053993-64a0e180-d164-11e8-974c-4b28ec3681a8.png)

![screen shot 2018-10-16 at 4 52 54 pm](https://user-images.githubusercontent.com/606167/47053927-1f7caf80-d164-11e8-9eb0-b6e332f8803b.png)

**Comment by suhasdeshpande** [comment]
@nightwing Any suggestion or things I can do in order to assign first row ace_selected in autocomplete?

**Comment by nightwing** [comment]
This issue is fixed by https://github.com/ajaxorg/ace/commit/14f73bf328ceb3d1bc9be3ae8038f088b1d74dcd#diff-c5396386eba2b427c622ebee1a36b15b, 
The fix will be included in the next release of ace which will be released next friday.

**Comment by nightwing** [comment]
this is fixed in v1.4.2
