### ISSUE TITLE
ace.require in src-min-noconflict returns undefined

### ISSUE THREAD

**Issue by jeffreymeng** [ajaxorg/ace#3803]
I'm trying to load the `statusbar` extension with this code:
```javascript
var StatusBar = ace.require("ace/ext/statusbar").StatusBar;
var statusBar = new StatusBar(editor, document.getElementById("statusBar"));
```
But when I run it I get the error `Cannot read property 'StatusBar' of undefined`. It seems that when I run `ace.require("ace/ext/statusbar")` by itself in the console it returns undefined.

Am I loading the extension incorrectly?

**Comment by nightwing** [comment]
you need to  include the script for statusbar for  ace.require to work.

**Comment by jeffreymeng** [comment]
I see. 

Do I also need to load the mode and language files too then? I'm using ace.require to load those and ace loads them for me right now.

**Comment by nightwing** [comment]
setMode and setTheme can load scripts because they are async,  ace.require will work for  modes loaded like that.

The equivalent for extensions would be using ace.config.loadModule like this https://github.com/ajaxorg/ace/blob/9df72aa051d48ecf1fd628fed303e110c9cdde66/doc/site/js/main.js#L20

**Comment by jeffreymeng** [comment]
Ok, thanks.
