### ISSUE TITLE
Customize Fold Icon Image

### ISSUE THREAD

**Issue by vinothwindows47** [ajaxorg/ace#3804]
Hi,
I have set Crimson Editor Theme in my code editor. I feel the fold icon is looking ugly. Can I change fold Icon Image ?

[screencapture-ace-c9-io-build-kitchen-sink-html-2018-10-23-11_42_21.pdf](https://github.com/ajaxorg/ace/files/2504710/screencapture-ace-c9-io-build-kitchen-sink-html-2018-10-23-11_42_21.pdf)

**Comment by nightwing** [comment]
We can set a background color to the fold similar to the textmate theme 
https://github.com/ajaxorg/ace/blob/master/lib/ace/theme/crimson_editor.css#L55
https://github.com/ajaxorg/ace/blob/master/lib/ace/theme/textmate.css#L12

Alternatively you can add a css rule overriding the rule at https://github.com/ajaxorg/ace/blob/master/lib/ace/css/editor.css#L355
