### ISSUE TITLE
Missing snippets in webpack-resolver.js

### ISSUE THREAD

**Issue by manubb** [ajaxorg/ace#3811]
I already opened an issue in the ace-builds repo: https://github.com/ajaxorg/ace-builds/issues/144
(I do not know what is the best place.)
Maybe i'm doing things in the wrong way but i think that those lines should be added to webpack-resolver.js file:
```js
ace.config.setModuleUrl('ace/snippets/javascript', require('file-loader!./src-noconflict/snippets/javascript.js'))
ace.config.setModuleUrl('ace/snippets/html', require('file-loader!./src-noconflict/snippets/html.js'))
...
```

**Comment by nightwing** [comment]
You are right, snippets are missing in https://github.com/ajaxorg/ace/blob/master/Makefile.dryice.js#L136
