### ISSUE TITLE
Firefox Extension "Riak JSON Editor"

### ISSUE THREAD

**Issue by inukaze** [ajaxorg/ace#3812]
Hi there right now i am trying to edit a ".json" file loaded directly on firefox from my desktop folder.
and i see ["Dev Keys"](https://github.com/ajaxorg/ace/wiki/Default-Keyboard-Shortcuts) i reach here. 

i just have 2 dunnos:
1 - How i can edit file directly?
2 - How i can use the Keyboard Shortcuts, and work on the extension and not in the web browsers firefox. ?

**Comment by nightwing** [comment]
Ace provides only the editor ui, you need to load the file as text using firefox file api and use `editor.session.setValue(text)`

I don't understand your second question.
