### ISSUE TITLE
enableSnippets  is reported as misspelled option name

### ISSUE THREAD

**Issue by vitalije** [ajaxorg/ace#3813]
I am using ace.js from https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.1/ace.js

When I try to use

```
editor.setOptions( {enableSnippets: true})
// or
editor.setOption('enableSnippets', true)
```
I get warning that `enableSnippets` is misspelled option and snippets are not enabled.

The same error is when using
https://cdn.jsdelivr.net/gh/ajaxorg/ace-builds@1.4.1/src-min/ace.js

**Comment by nightwing** [comment]
include the `ext-language_tools.js` script before using enableSnippets option

**Comment by vitalije** [comment]
Thanks

**Comment by nightwing** [comment]
Good point, i have added that to https://github.com/ajaxorg/ace/wiki/Configuring-Ace.
