### ISSUE TITLE
Python & Autocomplete 

### ISSUE THREAD

**Issue by Dariusz1989** [ajaxorg/ace#3815]
Hey

Apologies if I'm asking about a "simple" topic but I'm mostly c++/python dev and never really looked into java/html etc. I want to add an ide-isch editor to my python embedded interpreter in c++ application. The app is Qt5 based and we have running the ACE in QtWebEngine type node. 

I was able to enable auto complete/other cool things but I wonder how can I enable autocomplete of imports?

Say if I do
`   import test as xx
    xx.printTest(10)
`

Our initial html code is as follows:

```
<!doctype html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Ace</title>
<script src="qrc:/jquery/latest.js" type="text/javascript"></script>
<script src="qrc:/ace/ace.js" type="text/javascript"></script>
<script src="qrc:/ace/ext-language_tools.js"></script>
<script src="qrc:/ace/snippets/python.js"></script>
<style type="text/css" media="screen">
    #editor {
        position: absolute;
        top: 0;
        right: 0;
        bottom: 0;
        left: 0;
        font: 14px monospace;
    }
</style>

<script>
    var editor;
    window.onload = function () {
        editor = ace.edit("editor");
        editor.setOptions({
            enableBasicAutocompletion: true,
            enableSnippets: true,
            enableLiveAutocompletion: true,
        });
    }
</script>
</head>
<body>
<div id="editor"></div>
</body>
</html>
```
We use pybind and PYBIND11_EMBEDDED_MODULE to expose our C++ functions to python/modules. 

Any help would be awesome. 
TIA

**Comment by nightwing** [comment]
Do you want to display completions based on the methods of objects or simply include the words from test file in the frequency based word completion list?
The second is relatively easy, but the first is quite hard.
For it to work you'd need to run some autocompletion provider for python like jedi, or a language server.

**Comment by Dariusz1989** [comment]
Hey. 
Sorry for long reply. I'm not quite sure to be honest

Say if inside Ace I define some kind of class like

```
class ComplexNumber:
    def __init__(self,r = 0,i = 0):
        self.real = r
        self.imag = i

    def getData(self):
        print("{0}+{1}j".format(self.real,self.imag))
```
I can type stuff like 
```
x = ComplexNumber()
x.real
x.imag
```
and the x. would auto suggest to real/imag + bunch of other random stuff (I wonder if there is a way to disable the random stuff?)

But if I import a class like
import class as c
and then do 
```
something = c.classA()
if I do something. I get no auto suggestion.

So I what do I need to get ACE to do it?

**Comment by suhasdeshpande** [comment]
I don't think that's how Ace would handle this. You would need to handle the smartness by implementing completion provider that is always aware of what and where things are being typed. One solution which suggested by @nightwing is to implement your own [language server](https://microsoft.github.io/language-server-protocol/).
