### ISSUE TITLE
执行toUpperCase()之后，中文输入有问题

### ISSUE THREAD

**Issue by waka992** [ajaxorg/ace#3818]
![image](https://user-images.githubusercontent.com/30035361/48185150-236cad80-e36f-11e8-85f0-3ab2b5a43bef.png)
![image](https://user-images.githubusercontent.com/30035361/48185233-59aa2d00-e36f-11e8-8e3a-3cc9777d66f9.png)
![image](https://user-images.githubusercontent.com/30035361/48185240-5e6ee100-e36f-11e8-9e84-dbd903281bd1.png)
需求：把输入的英文都转换成大写

情况：设置了toUpperCase之后，输入‘测试’，正常，输入'sh'，会自动把前面的 '测试' 二字给覆盖掉

**Comment by nightwing** [comment]
changing value from change event can have unpredictable results.

If you want to always convert input to uppercase, use:

```js
editor.commands.on("exec", function(e) { 
    i f(e.command.name == "insertstring") 
       e.args = e.args.toUpperCase();  
})
```
