### ISSUE TITLE
The first row always appears spaces.？ 中文:第一行总是出现空格，导致python雨大格式不正确

### ISSUE THREAD

**Issue by 529834149** [ajaxorg/ace#3819]
![image](https://user-images.githubusercontent.com/22534117/48189023-1c976800-e37a-11e8-9734-0c7bc9b09732.png)

            for x in guards:
    goto(x)
    y=getDict(x)
    password=y["name"]
    say(password)
        
第一行的for错行了，这是python代码。其余的是
![image](https://user-images.githubusercontent.com/22534117/48189077-43559e80-e37a-11e8-990f-9416ed13b465.png)
 哪位同行遇见过帮我看一下我的配置
`      editor.setTheme("ace/theme/chrome");
        editor.session.setMode("ace/mode/python");//设置语言
        editor.setOption("minLines", 5);
        editor.setOption("maxLines", 20);
        editor.setFontSize(16);
        
        editor.setOption("wrap", "free");
        editor.getSession().setTabSize(4);
        editor.getSession().setUseSoftTabs(true);
        editor.getSession().getUndoManager().reset();
        editor.setShowPrintMargin(false);
        editor.setBehavioursEnabled(true);
//      新增
        editor.setOption("useSoftTabs", "true");
        editor.getSession().on('change', function(e) {
            document.getElementById('ace-input-{$this->id}').value = editor.getValue();
            
        });`

**Comment by nightwing** [comment]
The editor uses textContent on the node, so if there is a space in the html (e.g. due to indentation) it remains as a value of the editor.

**Comment by 529834149** [comment]
think you  找到原因了，主要我的编辑器模版中
![image](https://user-images.githubusercontent.com/22534117/48236950-6d9d6f80-e3ff-11e8-8350-74206c88a647.png)
使用了<pre>标签导致我pre前面的空格都保留了，坑得很

**Comment by nightwing** [comment]
if your templating language adds spaces, instead of `ace.edit(element)` use

```
editor = ace.edit(element, {
    value: element.textContent.trim()
})
```
