### ISSUE TITLE
Vim ctrl-v (block editing mode) not working properly.

### ISSUE THREAD

**Issue by tommyvanduyne** [ajaxorg/ace#3827]
I have not done a full test of the block-level commands for Vim, but two things stand out:
- ctrl-v can only select maximum two lines for the block
- ctrl-v shift-i no longer inserts in all the lines selected

**Comment by kevinushey** [comment]
I think this is fixed by https://github.com/ajaxorg/ace/pull/3787 but I don't know if it's part of a public release / the kitchen sink yet.

**Comment by nightwing** [comment]
This is fixed in v1.4.2 released today.
