### ISSUE TITLE
autocomplete highlight words mixed-up

### ISSUE THREAD

**Issue by robs-scc** [ajaxorg/ace#3828]
When typing a word for the autocomplete popup, the highlight (CSS class: .ace-line .ace_completion-highlight) tends to jumble up the readable text.
To repro, go to this URL:
http://plnkr.co/edit/6MVntVmXYUbjR0DI82Cr?p=preview
(I would provide my own URL, but it is still in development behind a firewall.)
Type in this text: cpleo
Press ctrl+space.
You will notice that the caption reads 'compleompletion' instead of 'completion'.
![screen shot 2018-11-15 at 5 01 18 pm](https://user-images.githubusercontent.com/8127254/48591290-28de7080-e8f8-11e8-85e4-ef1eb2f92c8f.png)

In an example of what I'm working on, I enter in some text, such as 'waste', and some suggestions popup.  The filter isn't really working correctly, but I guess that's for another bug.
The text should be 'CaWholesaleDistributors', but instead it reads 'CaWaWholesaleDistesaleDistributors'.
![screen shot 2018-11-15 at 5 03 34 pm](https://user-images.githubusercontent.com/8127254/48591507-0567f580-e8f9-11e8-9b88-1883f61f3711.png)

**Comment by adrianbj** [comment]
I'd love to see this fixed also - definitely a long-standing bugbear of mine. Here's an example from my situation:

![image](https://user-images.githubusercontent.com/871211/48725394-e9a66d00-ebe0-11e8-9782-011dc86996da.png)

It even adds matches which don't exist, eg:
`$page->tage->trashable()`

The valid match is simply: `$page->trashable()`

@nightwing - if there is anything I can provide to make it easier for you to replicate this, please let me know. 

Not sure, but was this https://github.com/ajaxorg/ace/commit/14f73bf328ceb3d1bc9be3ae8038f088b1d74dcd an attempt to fix this? I am using an existing ACE build. Maybe I need to build my own which includes this commit? Or maybe ACE needs a new release?

**Comment by nightwing** [comment]
The fix is included in v1.4.2, thank you for the bug report!
