### ISSUE TITLE
Line breaks after paste and char input in IE

### ISSUE THREAD

**Issue by benSn** [ajaxorg/ace#3831]
After pasting any text into an ace editor instance in IE11 and start typing, the editor first inserts two new lines below the current line, moves the cursor two the beginning of the second inserted line and then inserts the typed character.

Environment:
Ace v1.4.1: https://ace.c9.io/build/kitchen-sink.html
Browser: IE11

Reproduce:
1. Copy a word/character to clipboard
2. Set the cursor anywhere in the ace editor
3. Paste (ctrl+v) the copied word/character
4. Type a character

**Comment by nightwing** [comment]
This is fixed in v1.4.2, please let me know if you still see the issue. Thanks!
