### ISSUE TITLE
Copy-Paste on middle mouse click does not work in linux firefox

### ISSUE THREAD

**Issue by licam** [ajaxorg/ace#3834]
to reproduce:

Write some text, select it with the mouse, move mouse to a different location, middle click.

actual: cursor moves to that location, but nothing is inserted
expected: cursor moves to that location and the previously selected text is inserted at that location

**Comment by nightwing** [comment]
Pasting actually works on firefox 65 (nightly), but copying still doesn't.
We can add a workaround for copy-pasting inside the same editor, but copying to other editors still won't work.

**Comment by ddodt** [comment]
The problem still persists (70.0.1 (64-bit) ubuntu 19.10). :(

**Comment by omnister** [comment]
Problem still exists in 71.0 on ubuntu 19.10.  This makes outlook mail useless for sending code snippets.  I must type in code by hand since there is no other way to include it in a text message short of including the text as an attachment.

**Comment by gdish** [comment]
I have the same issue, when using Ctrl-C to copy with Firefox 84 on linux. Paste works fine.

**Comment by ddodt** [comment]
The problem still persists (99.0 (64-bit) ubuntu 20.04). Just to keep track of it...
