### ISSUE TITLE
Ctrl-M Characters are ignored in ace document getAllLines() method

### ISSUE THREAD

**Issue by ManojkumarV** [ajaxorg/ace#3836]
When there are ctrl-M characters in a string those characters are not returned in getAllLines() method of ace document. This is resulting in index difference when calculating the index from position since the actual content has some characters in it.

**Comment by ManojkumarV** [comment]
This is happening even if I enforce newLineMode to "unix". Is there any way to handle this?

**Comment by nightwing** [comment]
The positionToIndex seems to work correctly as well:

```js
editor.setValue("a\r\nb"); 
editor.session.doc.positionToIndex({row: 1, column: 1}) // prints 4
```

Please give an example of the code you are using to reproduce the problem, because without it we seem to be talking about different things.

**Comment by ManojkumarV** [comment]
Issue got fixed after properly using positionToIndex method. Will close this issue.
