### ISSUE TITLE
renderer.setMargin does not set all margins

### ISSUE THREAD

**Issue by jamalf** [ajaxorg/ace#3843]
I'm trying to set a fixed top-margin to ace. Currently i'm using renderer.setScrollMargin as a stop-gap but ideally the margin would not be part of the scrollable content. I see in 965f49e3 that the functionality was started but not finished - currently only the left margin is used during rendering.

My use case is to provide a margin between a row of editor tabs and the editor content, and for it to be styled as part of the editor (eg theme colors, gutter and scrollable area both extended up in the margin).

**Comment by nightwing** [comment]
SetMargin is indeed partially implemented, but if it was implemented keeping the same logic which was used for the left margin it would look something like the following, to allow adding other widgets at the top
![image](https://user-images.githubusercontent.com/341801/49547607-99c3e780-f8fc-11e8-9912-bd643a02b267.png)
is this what you are looking for?

**Comment by jamalf** [comment]
Thanks for the response. I've since modified my design so i no longer need a margin.
What i'd originally envisioned was to have the gutter and scrollbar extend, but have the margin set for the content area, although after seeing your image it occurs to me the scrollbar would not extend through the margin, so it may have been a silly idea in the first place.
