### ISSUE TITLE
Cannot add command Ctrl+Tab

### ISSUE THREAD

**Issue by cayhorstmann** [ajaxorg/ace#3844]
Trying to define an action for Ctrl-Tab and Shift-Ctrl-Tab does not work.

```
        editor.commands.addCommand({
          name: "myamazingcommand",
          bindKey: {win: "Ctrl-Tab", mac: "Cmd-Tab"},
          exec: function() {
             // amazing stuff
          }
        });
```

The function is not called when hitting Ctrl-Tab.

I am trying to define these keys for accessibility, to escape an Ace editor that captures tabs.

**Comment by nightwing** [comment]
ctrl-tab key is captured by chrome, and unfortunately they keep closing feature requests to add option to allow pages to use that keybinding.

Other browsers, like vivaldi, allow using ctrl-tab in web pages.

**Comment by cayhorstmann** [comment]
Thanks for letting me know. That's unfortunate. I described a workaround in #3149.
