### ISSUE TITLE
prettify/tidy/beautify HTML,CSS and JS code

### ISSUE THREAD

**Issue by arunkumar413** [ajaxorg/ace#3845]
HI Team,

How to implement tidying up the code on editors. Is it possible to use any external code tidy tools? If yes, what do you suggest?

Thanks,
Arun

**Comment by nightwing** [comment]
Hi
you can use jsbeautify similar to https://github.com/c9/core/blob/master/plugins/c9.ide.format/formatters/jsbeautify.js#L208
Or use the built-in beautify extension similar to https://github.com/ajaxorg/ace/blob/master/demo/kitchen-sink/demo.js#L484
