### ISSUE TITLE
Content Security Policy refused to create a worker from 'blob'

### ISSUE THREAD

**Issue by KyooMario** [ajaxorg/ace#3846]
Hello Ace team,

We are trying to integrate ace.js with Salesforce but run into the issue: Content Security Policy refused to create a worker from 'blob'.
In the ace.js code the snippet is: " new Blob([t],{type:"application/javascript"} "

Can you advise how to workaround this?

Hope you can help.
Kind regards,
Mario

**Comment by nightwing** [comment]
Hi
Blob is used because using script directly causes security error when loading the editor from cdn.
https://github.com/ajaxorg/ace/pull/3862 adds an option to disable usage of Blob, which will help with this issue, if you are loading the editor from the same domain.

**Comment by KyooMario** [comment]
Hello Nightwing,

Thanks.
Question: Do you maintain the npm i ace-code-editor
Or do I need to download the latest github source?

Kind regards,
Mario

**Comment by JamesRDouglas** [comment]
Thanks very much for this patch; Now I can use Ace syntax validation in my Firefox extension :)

**Comment by nightwing** [comment]
@KyooMario we do not maintain ace-code-editor, you can use ace-builds npm package instead https://www.npmjs.com/package/ace-builds
