### ISSUE TITLE
Scrollbar covers last line in editor

### ISSUE THREAD

**Issue by ketysek** [ajaxorg/ace#3856]
Hi there, is it somehow possible to place scrollbar out of the editor textarea so it will not cover the last line of the content?
<img width="613" alt="screen shot 2018-12-19 at 14 41 31" src="https://user-images.githubusercontent.com/11921885/50224971-87878600-039f-11e9-9ed2-0ec2b9949ca5.png">

**Comment by nightwing** [comment]
Is the scrollbar autohiding, and is the behavior the same for textarea?

If yes, then a workaround for this is to use:
```js
dom = require("ace/lib/dom")
dom.scrollbarWidth_orig = dom.scrollbarWidth_orig || dom.scrollbarWidth
dom.scrollbarWidth = function(doc) { return Math.max(10, dom.scrollbarWidth_orig(doc)) }
```
if no, then this is a bug. On which browser and os do you see it?

**Comment by ketysek** [comment]
I've added padding-bottom to .ace-editor ;) but if you're curious, it happens on OS X Mojave, in Chrome & also FF

**Comment by brandonburr** [comment]
![image](https://user-images.githubusercontent.com/1245838/82249845-59dd9e00-98ff-11ea-95a4-a186bc46246f.png)

You can even see the problem on Ace homepage(chrome/ff/safari on a mac, image is from here: https://ace.c9.io/)

Seems like scrollbars are usually autohiding on a mac, and this problem does indeed occur with a plain <textarea>. Neither the workaround or the padding-bottom on .ace-editor worked for me (though padding-bottom does work for <textarea> so might just be my specific css setup), but using `setScrollMargin` did do the trick for me:

`editor.renderer.setScrollMargin(0, 10, 0, 10)`

and I'm using react-ace, so solution was from here:  https://github.com/securingsincity/react-ace/issues/386
