### ISSUE TITLE
[doc] completer.identifierRegexps should be documented

### ISSUE THREAD

**Issue by exoego** [ajaxorg/ace#3859]
To customize characters that trigger text completion, adding `completer.identifierRegexps` to completer object is required.
https://github.com/ajaxorg/ace/blob/9b5b63d1dc7c1b81b58d30c87d14b5905d030ca5/lib/ace/autocomplete/util.js#L74-L88

However, such option is not documented as far as I browsed docs.
It would be helpful if `identifierRegexps` is documented and/or has a demo.

**Comment by mahdi943** [comment]
> To customize characters that trigger text completion, adding `completer.identifierRegexps` to completer object is required.
> https://github.com/ajaxorg/ace/blob/9b5b63d1dc7c1b81b58d30c87d14b5905d030ca5/lib/ace/autocomplete/util.js#L74-L88
> 
> However, such option is not documented as far as I browsed docs.
> It would be helpful if `identifierRegexps` is documented and/or has a demo.

Hi,
I am using Ace editor in my project for Gherkin syntax. I have already implemented existing ace autocomplete but it just suggests current words in the editor; I need to add my custom list for Autocompletion.
How can I do that?
Thanks.
