### ISSUE TITLE
popup missing

### ISSUE THREAD

**Issue by waka992** [ajaxorg/ace#3868]
hello, i am meeting a problem when i set up the editor for a long code like 170+ lines.
and it throw the wrong belows
![image](https://user-images.githubusercontent.com/30035361/50545372-29835a00-0c4d-11e9-8b6f-e8c8a29b9edd.png)
it points to the code belows:
![image](https://user-images.githubusercontent.com/30035361/50545376-4455ce80-0c4d-11e9-9e9b-a781138a4798.png)
And i print the completer and found there is no "popup" key in "completer" object.

But everything works corret when the editor working with less code like 50+ lines.
Would you please tell me what should i do to fix the problem?
thanks.

**Comment by nightwing** [comment]
The startAutocomplete command can be async in some cases, try using the following instead

```js
 var Autocomplete = require("ace/autocomplete").Autocomplete;
 if (!editor.completer) {
    editor.completer = new Autocomplete();
    editor.completer.editor = editor
    editor.completer.getPopup()
}
```

In the next version of ace, we'll add a more convenient method to achieve this, either by adding editor.getCompleter() or editor.getCompleterPopup() method

**Comment by waka992** [comment]
thanks, it did work to me.
And thanks for your effort. The editor helps me much.
