### ISSUE TITLE
Preserve indent after editor.insert()

### ISSUE THREAD

**Issue by sethwilsonUS** [ajaxorg/ace#3869]
Hello,

I'm using `editor.insert()` to insert code into my editor via JavaScript after other events on my page. But if my insert ends with a new line, my cursor doesn't keep the indentation level. I've tried using `\r` instead of `\n` to simulate a carriage return, but that didn't seem to help.

Any suggestions on either preserving my indentation level or just telling Ace to simulate pressing`Enter`? Thanks!

**Comment by nightwing** [comment]
Behaviors like pairing braces expanding tabs or changing indentation are applied only if one character is inserted. So if you call editor.insert("\n") ace will behave as if Enter was pressed.

**Comment by sethwilsonUS** [comment]
Thanks so much!
