### ISSUE TITLE
Searchbox prev/next buttons height shrank?

### ISSUE THREAD

**Issue by elgs** [ajaxorg/ace#3870]
When I click ctrl + F in the editor, it shows on the top right corner a searchbox, however, the height of the prev/next buttons seems to be shrunk. I wonder if I have missed anything. Any help will be greatly appreciated. Thanks.

https://jsbin.com/mopoxod/2/edit?html,output

```html
<html>
<head>
    <meta charset="UTF-8">
    <title>Document</title>
    <style>
        html,
        body {
            margin: 0;
            padding: 0;
        }
        div#ed {
            height: 100%;
            width: 100%;
        }
    </style>
</head>
<body>
    <div id="ed"></div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.2/ace.js"></script>
    <script>
        const ed = document.querySelector('div#ed');
        const editor = ace.edit(ed, {
            mode: "ace/mode/html",
        });
    </script>
</body>
</html>
```

**Comment by nightwing** [comment]
It appears the browser uses different layout based on doctype, when i add `<!doctype html>` the height is correct https://jsbin.com/yulecugado/edit?html,output

**Comment by elgs** [comment]
Thank you so much! It works. Can you please educate me a little more about what layouts browser uses based on the `doctype`?

**Comment by nightwing** [comment]
I don't know much about it myself, https://stackoverflow.com/a/12870462/1743328 seems to have some useful information.

**Comment by elgs** [comment]
Thank you so much! It actually solved my other long pending problem here: https://stackoverflow.com/questions/53965326/overflow-difference-between-chrome-and-firefoxs-in-grid-container
