### ISSUE TITLE
Help - Error when typing characters which aren't in English alphabet

### ISSUE THREAD

**Issue by MQTEnt** [ajaxorg/ace#3871]
I use `ng2-ace-editor` version `^0.3.8`, when I type characters aren't in English alphabet like Japanese or Vietnamese then the editor displays weird character (look like a box).
![error-type](https://user-images.githubusercontent.com/14356177/50818469-a7d0b200-1359-11e9-88af-2493eb86cd30.png)
Can you help me fix it.
Thanks.

**Comment by nightwing** [comment]
This issue is fixed on master (try https://ace.c9.io)
Unfortunately the brace module used ng2-ace-editor still uses an older version of ace.

**Comment by MQTEnt** [comment]
> This issue is fixed on master (try https://ace.c9.io)
> Unfortunately the brace module used ng2-ace-editor still uses an older version of ace.

thank for your information
