### ISSUE TITLE
worker-xml.js reports "entity not found" for externally defined entities

### ISSUE THREAD

**Issue by ansco11** [ajaxorg/ace#3873]
Possibly this could be fixed by the worker script not triggering an error condition in this case if there is a reference to external entities in the XML.

Here's my entity reference which causes the red X to appear with its unhelpful message:

```
<!DOCTYPE xyz [
<!ENTITY % common.entities SYSTEM "xsd/common.entities">
%common.entities;
]>

```

**Comment by D-Groenewegen** [comment]
I have the same issue even with internally defined entities. It is common practice in [TEI XML](https://tei-c.org) to define one's entities (potentially including custom entities) - see for instance, [this guide by Peter Flynn](https://books.google.nl/books?id=p1vaBwAAQBAJ&pg=PA171&lpg=PA171&dq=ampersir&source=bl&ots=7Qn7ZjHEOX&sig=ACfU3U0dHsm0u6QQEiHmajVOMCYGFFjJHw&hl=en&sa=X&ved=2ahUKEwi2z8f81bH5AhXI1qQKHa5KBNsQ6AF6BAgcEAM#v=onepage&q=ampersir&f=false). The [default set of allowed entities](https://github.com/ajaxorg/ace/blob/94422a4a892495564c56089af85019a8f8f24673/lib/ace/mode/xml/dom-parser.js#L18) is too restrictive, which could amount to riddling the interface with unnecessary error messages.
