### ISSUE TITLE
Custom Markers Are Broken

### ISSUE THREAD

**Issue by mmacfadden** [ajaxorg/ace#3874]
Greetings,

Thanks for ACE! It is a great project. We have created some custom markers for use in ACE. In commit
https://github.com/ajaxorg/ace/commit/06276c99d4a0bab82df750082f9a7e7a6da82410 something was changed in the Marker layer that seems to have broken them.  The line in question is linked below:

https://github.com/ajaxorg/ace/blob/96088d0fc292daf0706b2d029cc03c3799be5974/lib/ace/layer/marker.js#L77

Previously the html variable was initilaized like this:

```
var html = [];
```

Now it is like this:
```
var html;
```

Later on in the file this line appears:

https://github.com/ajaxorg/ace/blob/96088d0fc292daf0706b2d029cc03c3799be5974/lib/ace/layer/marker.js#L82

The `html` variable passed to the marker is now undefined. Therefore when we try to append HTML to the marker HTML we get an error. The change log and commit mention "remove usage of innerHTML". It seems like the intention is to work with the element structure directly, however, we have been unable to figure out exactly what to do.  There is the new "elt" method that seems to have something to do with it.

I would note that are custom markers and a whole subtree of elements, not just a single div with a class name.

What is the best way to work with the new system?

**Comment by nightwing** [comment]
Unfortunately this is a bit hard to do because currently marker layer reuses the dom nodes not created with the elt method, which seems to be a bug.

Here is a dynamic marker that adds subtree of elements and works with the current version of ace
```js
var buildDom = require("ace/lib/dom").buildDom
editor.session.addDynamicMarker({
    contentNode: null,
    update: function(_, layer, session, config) {
        if (this.contentNode) {
            // we need to manually remove this because the
            // parent may have been used by another marker
            this.contentNode.remove() 
        }
        else {
            this.contentNode = buildDom(["div", {class: "foo"}, "nested", ["span", "-"]])
        }
        layer.elt("my-marker", "top: 5px;left: 5px")
        var parentNode = layer.element.childNodes[layer.i - 1] || layer.element.lastChild
    	parentNode.appendChild(this.contentNode)
    }
})
```

Could you show the code you used with the previous version of ace? It would help to improve the marker api.

**Comment by mmacfadden** [comment]
Thanks for the reply.  The code can be seen here:

https://github.com/convergencelabs/ace-collab-ext/blob/master/src/ts/AceCursorMarker.ts

I am refactoring now to see if I can get it to work as above. I'll post that too.  What would be ideal for efficiency sake is if the dynamic marker rendering were split up a bit. Where I we are given a parent node to attach too, and that will always be our parent. At this point you can do whatever you want with that parent node. So for example if all I need to do is update the top / left css properties on a child node I can simply set them without doing heavy weight DOM operations.

At the very least, the  elt method could be trivially modified to return the parent node, which would remove the complex line to get it.

If I get this working perhaps I can play with the API and share some ideas.

**Comment by nightwing** [comment]
We were doing something very similar in our collab plugin, and the way it was handled there was using `::before`  pseudoelement from css https://github.com/c9/core/commit/74023713c7bd47f71ac162bb675a753fa3099b46#diff-94f33cead0d2c3374b50c6a0a8779ee0R88

That may be a good solution for your usecase too, but of course fixing the api for dynamic marker is important anyway

**Comment by mmacfadden** [comment]
I was actually just thinking that. The cursor element is also going to bet a tool tip that fades in and out, just hadn't gotten there yet, so I think I will still wind up with multiple elements, anyway.

I also have a module for remote selection (like you also have) here:
https://github.com/convergencelabs/ace-collab-ext/blob/master/src/ts/AceMultiSelectionManager.ts which has many elements since it is multi line.

In case you are curious, we build a real time collaboration engine, [https://convergence.io/](https://convergence.io/), and a collaborative ACE editor is one of our examples of things you can build with out API. I knew it was possible since it is used in C9 for such a use case!

**Comment by mmacfadden** [comment]
I got the remote cursor working, working on the selections now.... then I will think about the marker API a bit and comment back.

**Comment by mmacfadden** [comment]
https://examples.convergence.io/ace/index.html

**Comment by mmacfadden** [comment]
Ok, I have updated the code and it is working, thanks for the tips.  You can see how it looks here:

https://github.com/convergencelabs/ace-collab-ext/blob/master/src/ts/AceCursorMarker.ts

In looking at the API. I think there are a few suggestions / comments:

- Do we really need to call `remove()`? Wouldn't calling `parent.appendChild` remove the element from whatever parent it was attached to previously.
- If the existing elt method simply returned the created element, then there would not be a need to look it up using a fairly long calculation.
- Is there a way to assign the maker a parent node that is persistent such that the adding and remove of the nodes don't need to happen each time?
- Perhaps splitting an initialization step from the update step. In the initialization step, you could give the marker its node to bind to, then in the update method you would not need to deal with that each time.

Either way, thanks for the help! I am good for now.

**Comment by rafeautie** [comment]
@mmacfadden 

Does the example on the convergence website reflect these changes? I have remote cursors showing up but they are stuck in the position `row: 0, col: 0`. My code is based on the example.

**Comment by mmacfadden** [comment]
@rafeautie I'll take a look and verify. If you want to open a bug report on the https://github.com/convergencelabs/ace-collab-ext perhaps I can chase it down.

**Comment by rafeautie** [comment]
@mmacfadden [Done.](https://github.com/convergencelabs/ace-collab-ext/issues/9)
