### ISSUE TITLE
Unable to use autocomplete on iframe

### ISSUE THREAD

**Issue by pikename** [ajaxorg/ace#3875]

**Comment by nightwing** [comment]
Could you tell a bit more about what exactly doesn't work, this jsbin has ace.c9.io embedded in an iframe https://jsbin.com/dutiduh/edit?html,output, and autocomplete works in it.

**Comment by nightwing** [comment]
Closing, but please comment if you still see the issue, or have any additional information that would help to reproduce the issue.
