### ISSUE TITLE
this.$renderToken if new line is start with '\t' will has an error " .cloneNode(true)" is not a function

### ISSUE THREAD

**Issue by acejunnan** [ajaxorg/ace#3879]
if (tab) {
    var tabSize = self.session.getScreenTabSize(screenColumn + m.index);
        **if (isNaN(tabSize)) {
            tabSize = tab;
        }**
    valueFragment.appendChild(self.$tabStrings[tabSize].cloneNode(true));
    screenColumn += tabSize - 1;
}

**Comment by nightwing** [comment]
This can happen if tabSize option on the editor is set to string, could you please check if you  set it to a string accidentally?
