### ISSUE TITLE
[PHP] Autoclose PHPdoc comments.

### ISSUE THREAD

**Issue by xaav** [ajaxorg/ace#388]
When the user types `/**`, and presses enter, ace should automatically replace the text with this:

``` php5
<?php #Note: PHP tag is for syntax highlighting only. Please ignore it.

/**
 * CURSOR_HERE
 */
```

Additionally, ace should add more stars upon pressing enter (example below):

``` php5
<?php #Note: PHP tag is for syntax highlighting only. Please ignore it.

/**
 * 
 * 
 * CURSOR_HERE
 */
```

@gissues:{"order":56.52173913043498,"status":"backlog"}

**Comment by mkslanc** [comment]
Fixed by #5109
