### ISSUE TITLE
Highlighting doesn't work when I put a blank after keyword

### ISSUE THREAD

**Issue by 380847438** [ajaxorg/ace#3881]
in mysql mode, my keywords like this ：
  |select |from |as |inner join |
autocompletion is OK,but highlight doen't work.
Is there any solution?

**Comment by nightwing** [comment]
This is the expected behavior, regexp for keywords does not contain spaces, why do you want to add a space to them?

**Comment by 380847438** [comment]
thanks for reply. One Space Less.
In order to make the operation more convenient.
for example:
         select * from t_demo
after you  input select/from, next must be space.

**Comment by nightwing** [comment]
You can override editor.session.$mode.getCompletions method on mysql mode to add  spaces.

**Comment by 380847438** [comment]
It works, thank a lot!
