### ISSUE TITLE
Remove to Line Start - Cursor backward movement issue 

### ISSUE THREAD

**Issue by vinothwindows47** [ajaxorg/ace#3886]
When I Use "Remove to Line End" , the cursor moves to the next line automatically. But as I use "Remove to Line Start", the cursor will not move to the previous line automatically.

**Comment by nightwing** [comment]
Are you talking about the menu item in cloud9? 
Both "Remove to Line End" and  "Remove to Line Start" are not supposed to move the cursor to the next line, (similar to sublime, notepad++, vscode). I can help you to write a user script if you want a different behavior.

**Comment by vinothwindows47** [comment]
No, I am not talking about cloud9. Common IDE Scenario bug. When I use "Cmd + Delete - Remove to Line End" , the cursor automatically move to the next line. **But When I use "Cmd + Backspace - Remove to Line Start" , the cursor will not move to the previous line. That's the issue**.

**Comment by nightwing** [comment]
https://github.com/ajaxorg/ace/commit/f9b7156dac69a0d4682a77bf7da84adb69869759 fixes this issue, you can test it on  https://raw.githack.com/ajaxorg/ace/f9b7156dac69a0d4682a77bf7da84adb69869759/kitchen-sink.html
