### ISSUE TITLE
7 tabs at first of all codes retrive from db

### ISSUE THREAD

**Issue by abmohajeri** [ajaxorg/ace#3889]
Hi all,
When i retrive codes from db and make and ace editor , 7 tabs added at first and end of my code like attach image how can i fix it?
![image](https://user-images.githubusercontent.com/19857443/52519000-e06def00-2c69-11e9-9113-58e0354aab51.png)

**Comment by nightwing** [comment]
if you are using some kind of html template to set value to the editor, make sure to not add whitespace to the  editor div. something like
```php
<div id=editor><?php echo html_spacial_chars($value);?></div>
```

instead of 
```php
      <div id=editor>
           <?php echo $value;?>
      </div>
```
