### ISSUE TITLE
ACE on new created window

### ISSUE THREAD

**Issue by Anymfah** [ajaxorg/ace#3891]
Hello,

I've been able to run ACE the regular way, but i'm trying to make it load to a new window, looks like it is loaded but i can't write anything to it, i just get number '1' top left of screen, and the grey block from theme... Any ideas ? here is what i've done : 
```
function newWindow() {
w = window.open();
var html = '<body><div id="sass_editor"></div></body>';
$(w.document.body).html(html);
loadace();
}

function loadace() {
$('#sass_editor', w.document).each(function() {
var div = $(this);
var editDiv = $('<div>', {
'class': textarea.attr('class')
}).insertBefore(div);
editor = ace.edit(editDiv[0]);
editor.getSession().setMode('ace/mode/scss');
editor.setTheme("ace/theme/twilight");
});
}
```

Thanks for your help because i'm going mad on this :(

**Comment by nightwing** [comment]
We have tried to do this in cloud9 too, but unfortunately never managed to make it work reliably enough, because browsers throttle setTimeout and requestAnimationFrame calls in the background window.

Here's what we have tried

```js
// prepare the window
w = window.open("", "xxx", "width=420,height=230,resizable,scrollbars=yes,status=1");
w.document.body.innerHTML = '<div id="sass_editor"></div>'

// create the editor
e1 = ace.edit(w.document.body.firstChild, {
     mode: 'ace/mode/scss',
     theme: "ace/theme/twilight",
})
e1.container.style.height="300px"

// let the editor know that it need to add css styles to the new styling scope
e1.renderer.attachToShadowRoot()

// a very hacky workaround for throttling
setInterval = function(a,b) {return w.setInterval(a,b) }
setTimeout  = function(a,b) {return w.setTimeout(a,b) }
clearInterval = function(a,b) {return w.clearInterval(a,b) }
clearTimeout  = function(a,b) {return w.clearTimeout(a,b) }
require("ace/lib/event").nextFrame = function(a) {return w.requestAnimationFrame(a)}

// add resize listener to the correct window
w.addEventListener("resize", function() { e1.resize() })
setTimeout(function() { e1.resize() }, 10)

```

plus, it is needed to change the capture method to be (but if you decide to use this i can add this change in ace)
```js
 require("ace/lib/event").capture = function(el, eventHandler, releaseCaptureHandler) {
    var document = el.ownerDocument;
    function onMouseUp(e) {
        eventHandler && eventHandler(e);
        releaseCaptureHandler && releaseCaptureHandler(e);

        document.removeEventListener("mousemove", eventHandler, true);
        document.removeEventListener("mouseup", onMouseUp, true);
        document.removeEventListener("dragstart", onMouseUp, true);
    }

    document.addEventListener("mousemove", eventHandler, true);
    document.addEventListener("mouseup", onMouseUp, true);
    document.addEventListener("dragstart", onMouseUp, true);
    
    return onMouseUp;
};
```

a more reliable method to overwrite setTimeout  is
```js
var setTimeout = window.setTimeout;
var setInterval = window.setInterval;
var clearTimeout = window.clearTimeout;
var clearInterval = window.clearInterval;
var requestAnimationFrame = window.requestAnimationFrame;
var focused = window;
window.setFocused = function(v, e) {
    if (e === false && focused == v) focused = window;
    focused = v;

};
window.addEventListener("focus", function() {
    window.setFocused(this);
});
window.setTimeout = function() {
    if (focused == window)
        return setTimeout.apply(focused, arguments);
    else
        return {
            id: setTimeout.apply(focused, arguments),
            w: focused
        };
};
window.setInterval = function() {
    if (focused == window)
        return setInterval.apply(focused, arguments);
    else 
        return {
            id: setInterval.apply(focused, arguments),
            w: focused
        };
};
window.clearTimeout = function(x) {
    if (x && typeof x == "object")
        return clearTimeout.call(x.w, x.id);
    else
        return clearTimeout.apply(focused, arguments);
};
window.clearInterval = function(x) {
    if (x && typeof x == "object")
        return clearInterval.call(x.w, x.id);
    else 
        return clearInterval.apply(focused, arguments);
};
window.requestAnimationFrame = function() {
    return requestAnimationFrame.apply(focused, arguments);
};
```
and then for all new windows do 
```js
            win.addEventListener("focus", function() {
                window.setFocused(this);
            });
            win.addEventListener("close", function() {
                window.setFocused(this, false);
            });
```
but then we decided that this is too complex, and it is better to simply load the ace.js in the new window instead.

**Comment by Anymfah** [comment]
Very nice help you bring here, thank you very much.
Finally i think you are right about loading ace inside the new window this is the simplest way, i did manage to make it work the way you gave me but i had this delay with the setTimeout making it not viable and i might haven't done everything fine. Anyway i think it might be a nice feature to add somedays (like add an option wich adds a btn that allow to detach the ace editor in new window, and keep all the sessions from it) if it is possible.

Best regards.

**Comment by Jaaneek** [comment]
Could you guys @Anymfah @nightwing tell me how you solved this? Loading ace.js by <script> in new window doesnt work for me

**Comment by Anymfah** [comment]
What error do you get ? It works fine for me..  I think the best way is this one :
- From your main page, in your javascript, create a var for your new window

`var thePopup = window.open('', '_blank', $someoptions...);`

- Then in this same js file (from main page still) :

`$('head', thePopup.document).append('<script src="acejs.js">')`

**Comment by Anymfah** [comment]
Hello, today i made it work by just adding what you shared before : 
`// create the editor
e1 = ace.edit(w.document.body.firstChild, {
     mode: 'ace/mode/scss',
     theme: "ace/theme/twilight",
})
e1.renderer.attachToShadowRoot()`

editor.renderer.attachToShadowRoot() seems to fix it ! (no need of the setTimeout and intervals..)
