### ISSUE TITLE
Scss Autocomplete

### ISSUE THREAD

**Issue by Anymfah** [ajaxorg/ace#3892]
Hello,
It looks like css autocomplete works fine, but sadly not for scss. Is there a way to use scss highlights while using css autocomplete ?

Thanks

**Comment by ericuldall** [comment]
Hi,

We're also noticing this (or similar) issue. We recently switched from css mode to scss mode and the only thing getting syntax highlighted is the scss structures (variables, etc...). But we no longer get the autocomplete for css selectors which should be a valid part of the scss autocompletion.

Any update on this? Is there some file we're missing?

**Comment by timothylong** [comment]
I am experiencing this issue as well. I had to revert back to CSS mode in order to get autocomplete working again.

**Comment by nightwing** [comment]
Hi, the fix for this is included in v1.4.3, thanks for reporting the issue.
