### ISSUE TITLE
Remove is not operated in the IDE, but remove is transferred in the action.

### ISSUE THREAD

**Issue by sasadaisy** [ajaxorg/ace#3895]
hi,

```js
if (len === 0) {
        this.foldWidgets[firstRow] = null; <<--- foldWidgets is null
    } else if (delta.action == 'remove') {
        this.foldWidgets.splice(firstRow, len + 1, null);
    } else {
        var args = Array(len + 1);
        args.unshift(firstRow, 1);
        this.foldWidgets.splice.apply(this.foldWidgets, args);
    }
};
```

i don't see that `delta.action` how to Trigger and How to transfer the value of action?
Remove is not operated in the IDE, but remove is transferred in the action.

**Comment by nightwing** [comment]
Could you tell a bit more about the issue, where do you use ace, and what you are doing before the issue happens.

**Comment by sasadaisy** [comment]
@nightwing 
this.$updateAnnotations = function (delta) {
        if (!this.$annotations.length)
            return;
        var firstRow = delta.start.row;
        var len = delta.end.row - firstRow;
        if (len === 0) {
        } else if (delta.action == 'remove') {
            this.$annotations.splice(firstRow, len + 1, null);
        } else {
            var args = new Array(len + 1);
            args.unshift(firstRow, 1);
            this.$annotations.splice.apply(this.$annotations, args);
        }
    };
I'm using ace for web-IDE development.
When I perform the update operation, the error information in the IDE cannot be displayed again after being deleted. I think that the information in this.$annotations is deleted. As a result, the value cannot be obtained when the error information is inserted again, my question is how to assign a value to the error message when I insert it again.

**Comment by nightwing** [comment]
What do you mean by "perform the update operation" do you call the updateAnnotations method? it is supposed to be called only from the event handler

**Comment by sasadaisy** [comment]
@nightwing After I update the error information, the foreground displays that the error information will be cleared. However, I hope that the error information is always displayed. Where can I trigger the clearing operation?
