### ISSUE TITLE
How to integrate 3rd party library in ace

### ISSUE THREAD

**Issue by arjunballa** [ajaxorg/ace#3899]
@nightwing I did the below but it is not working
- I cloned the https://github.com/ajaxorg/ace.git
- I added downloaded https://github.com/fent/randexp.js/blob/master/build/randexp.min.js and added it to ace/lib/ace/lib
- I wanted to use it in a jsonIntellisense.js customization file I created and so I added below code
```
var RandExp = require("../../lib/randexp"); // There are no errors but RandExp is null.
```
- I did the build using `node Makefile.dryice.js` 
- I checked build/src/worker-json.js file and it has the contents of randexp.min.js
- I am not sure if there is problem with amdfication
- When building I see below on console
```
Written output in '/Users/arjunballa/soa/projects/ace/build/src/worker-javascript.js'
wrapping module ace/lib/randexp
```
Can you please help?

**Comment by nightwing** [comment]
It doesn't work because randexp does `define("RandExp", ...)`, so you need to setup paths so that randexp can be loaded with `require("RandExp")`.

It may be better to use webpack with ace-builds similar to https://github.com/nightwing/ace-webpack-demo

**Comment by arjunballa** [comment]
@nightwing Thanks for answering my questions.
I made the below changes and it worked.

1. I converted es6 https://github.com/fent/randexp.js/blob/master/lib/randexp.js and all it dependencies to es5 using https://es6console.com/
2. I wrapped all the converted code in below define pattern
```
define(function(require, exports, module) {
// put es5 code
});
```
3. I copied all the file to ace/lib/ace/lib (https://github.com/ajaxorg/ace/tree/master/lib/ace/lib) 
4. I loaded randexp using below `require` statement 
```
var RandExp = require("../../lib/randexp/randexp.js");
```

All worked.
