### ISSUE TITLE
Dynamic syntax highlighting

### ISSUE THREAD

**Issue by Woofthecat** [ajaxorg/ace#3905]
Hi,

I'd like to allow the users to add a list of keywords of their own if it's needed (as an extra set of keywords next to the available set of keywords of the selected mode) - therefore I have no idea what the user defined keywords are going to be. I've already figured out how to add custom values to the autocompletion (via creating a completer and using `langTools.addCompleter()`), and that's working fine. The problem is that this way those certain keywords remain without syntax highlighting.

I've been searching a lot but I cannot find a solution. Is this something that's supported? If not, is it possible to introduce a dynamic syntax highlighting feature?

**Comment by nightwing** [comment]
This can be achieved by modifying createKeywordMapper before any session is created https://github.com/ajaxorg/ace/blob/master/lib/ace/mode/text_highlight_rules.js#L210 to do
```js
var TextHighlightRules = ace.require("ace/mode/text_highlight_rules").TextHighlightRules
TextHighlightRules.prototype.createKeywordMapper = function(
     map, defaultToken, ignoreCase, splitChar
) {
    var keywords  = this.$keywords = Object.create(null);
```

After this new keywords can be added like this:
```js
editor.session.$mode.$highlightRules.$keywords["foo"] = "variable.language"
```
The modification will be applied to all editors in the page using that mode.
To trigger redraw of specific editor after the mode is changed use
```js
editor.session.bgTokenizer.start(0)
```

The reason `this.$keywords` is not assigned by default is that on old browsers, keeping it in the closure was making the function noticeably faster (maybe this is fixed on modern browsers).

**Comment by Woofthecat** [comment]
Thanks for your reply! I've tried to get it working but I think I misunderstood you. Is this something I'm supposed to modify in the source code itself?

**Comment by nightwing** [comment]
I meant something like this https://jsbin.com/taniqikagi/edit?html,js,output
For which language mode do you want to use this?

**Comment by Woofthecat** [comment]
Ah okay, I was testing it against text and pascal modes, but it won't work with them.

The ideal situation would be if I could add syntax highlighting to a set of keywords, no matter what the language mode is. Would that be possible?

**Comment by nightwing** [comment]
Do you want syntax aware highlighting, that is to not highlight the word if it is inside a string or a comment, or highlighting all instances of the word?

**Comment by Woofthecat** [comment]
I'd need syntax aware highlighting.

**Comment by YellowAfterlife** [comment]
The above advice is correct - if you insert a keywordMapper (or a custom rule that maps keywords through a function), you can later add/remove key-value pairs to it to register/unregister keywords.

I'm actively using this in GMEdit for context-specific highlighting (local definitions > project-specific definitions > native definitions).

If you need row/column data, see #3500 for what you'd need to tweak.

**Comment by Woofthecat** [comment]
But wouldn't that require me to modify the source code and update every single mode highlight rule that does not have a keywordMapper? Based on the small jsbin demo that @nightwing provided and taking a quick look at the source code, the only difference between for example Pascal and Java is that java_highlight_rules has a keywordMapper that's used in the rules: `var keywordMapper = this.createKeywordMapper(...);`

So the refined question is: 
Without modifying the source code, can I achieve syntax aware highlighting for a set of keywords that are user defined (meaning I don't know them beforehand)? I'd like this to work no matter what language mode is selected.

**Comment by nightwing** [comment]
Unfortunately i do not see a universal way to do this for all modes, but most of the modes already use keywordMapper so a possible solution is to manually update the ones that are not using it yet https://github.com/ajaxorg/ace/pull/3911

**Comment by Woofthecat** [comment]
Sorry I had many projects going on so I forgot to reply. I see how that could be a solution, but I assume it also depends on how many modes are missing the keywordMapper.

Thanks!
