### ISSUE TITLE
Does ace completer framework support grouping of suggestions

### ISSUE THREAD

**Issue by arjunballa** [ajaxorg/ace#3906]
@nightwing I am trying to add custom JSON completer based on provided schema. In order to support [oneOf](https://ajv.js.org/keywords.html#oneof) keyword I need to display all schema properties defined in `oneOf` array. I want to group the property suggestions under schema name.
I saw only below
```
collector.add({
    caption: key,
    value: value,
    score: score,
    meta: 'property',
    label: key,
    snippet: codeSnippet,
    docHTML: propertySchemaDescription
});
```
For example for below schema I want to group all properties of `reference` under `reference` and all properties under `schema` under `schema`.
```
"schemaOrReference": {
            "oneOf": [
                {
                    "$ref": "#/definitions/reference"
                },
                {
                    "$ref": "#/definitions/schema"
                }
            ]
        }
```
![image](https://user-images.githubusercontent.com/613351/54299717-b06f7f80-4578-11e9-8252-8a558490dcbc.png)

If this is not supported, may I get guidance in adding this support to ace.

**Comment by YellowAfterlife** [comment]
You would want to tweak the [popup box renderer](https://github.com/ajaxorg/ace/blob/e1fc3e8d10065f21800d3d403080c7676a61b61a/lib/ace/autocomplete/popup.js#L173), or perhaps extend it so that you insert additional "header items" to it based on metadata from completion items.
An easy way around would be to disable score-based sorting [here](https://github.com/ajaxorg/ace/blob/b7554f698fbae97ab410ae97a7b986d40cbd36fb/lib/ace/autocomplete.js#L462), or assign a unique score to each group, and then give the row's tokens a different type (so that you can show a separator line before them) if their group does not match that of preceding line.

**Comment by arjunballa** [comment]
@YellowAfterlife Thanks for replying.
I can handle the below requirements for `category` item as follows .

Please review and let me know if approach is correct.
If the approach is right I will make changes and submit a **Pull Request**

- Add special class
collection object supports `className` [popup.js#L183](https://github.com/ajaxorg/ace/blob/e1fc3e8d10065f21800d3d403080c7676a61b61a/lib/ace/autocomplete/popup.js#L183) property and I can use it set style class **but it looks like a hack**. I am planning to handle using `meta='ace-popup-category' as you suggested and use it every where I need.

- Do not add `ace_selected` class.
I need to do this here [popup.js#L144](https://github.com/ajaxorg/ace/blob/b7554f698fbae97ab410ae97a7b986d40cbd36fb/lib/ace/autocomplete/popup.js#L144)

- Do not display any hover styles.
I can handled this in css based on special class.

- Do not display `selected` styles.
I need to handle in [popup.js#L134](https://github.com/ajaxorg/ace/blob/b7554f698fbae97ab410ae97a7b986d40cbd36fb/lib/ace/autocomplete/popup.js#L134)

- Disable selection
I need to add if condition and based on `meta` property value in `data` we need to skip selection
[autocomplete.js#L184](https://github.com/ajaxorg/ace/blob/e1fc3e8d10065f21800d3d403080c7676a61b61a/lib/ace/autocomplete.js#L184)

- Disable click.
Same as "Disable selection"

- Disable Return.
Same as "Disable selection"

- Skip selection with keyboard
I need to add if condition and based on `meta` property value in `data` we need to skip selection
[popup.js#L246](https://github.com/ajaxorg/ace/blob/b7554f698fbae97ab410ae97a7b986d40cbd36fb/lib/ace/autocomplete/popup.js#L246)

**Comment by arjunballa** [comment]
@nightwing Can you please review the approach?

**Comment by nightwing** [comment]
This seems to be a good approach, i'd be happy to merge a pull request implementing it (or help to implement it).
