### ISSUE TITLE
snippet value ""$ref": "${0:}"" is written as "" : "" into editor instead of "$ref": ""

### ISSUE THREAD

**Issue by arjunballa** [ajaxorg/ace#3909]
@nightwing 
snippet value `""$ref": "${0:}""` is written as `"" : ""` into editor instead of "`$ref": ""`.

ace variable replacer is considering `$ref` as a placeholder and replacing it with `""` as variable `ref` is undefined.

Either there should be a way to escape `$ref` or we need to fix the `start` regular expression `/(:)|(\\.)|(})|(\$(?:\d+|\w+))|(\$\{[\dA-Z_a-z]+)|(\n)|($)/g` at [tokenizer.js#L246](https://github.com/ajaxorg/ace/blob/master/lib/ace/tokenizer.js#L246).

Tokens created by above regular expression are used in 
[snippets.js#L229](https://github.com/ajaxorg/ace/blob/master/lib/ace/snippets.js#L229)
[snippets.js#L184](https://github.com/ajaxorg/ace/blob/master/lib/ace/snippets.js#L184)

**Comment by nightwing** [comment]
it can be escaped as `\$ref`. Afaik snippets in textmate, sublime and monaco are expanded the same way.

**Comment by arjunballa** [comment]
I already tried `\$ref` and it did not work. If I do `$$ref` it writes `$` into editor.

**Comment by nightwing** [comment]
Maybe an issue with not escaping `\` in the js string? `editor.insertSnippet('\\$ref: "${0:}"\n')` inserts `$ref: ""` as expected

**Comment by arjunballa** [comment]
Thanks. I tried that and works.
