### ISSUE TITLE
Does ace support completion overwrites? 

### ISSUE THREAD

**Issue by arjunballa** [ajaxorg/ace#3912]
@nightwing 
By default ace completions for values are **inserts**. That mean it will insert the snippet and does not delete the partial match text.
![image](https://user-images.githubusercontent.com/613351/54708894-9b0ece00-4b01-11e9-825b-a2873836e5ca.png)

It does not delete the existing double quotes. The snippet is `"#/definitions/ObjectType"`.

![image](https://user-images.githubusercontent.com/613351/54708958-c5608b80-4b01-11e9-87ee-444a5b42d121.png).

but overwrites work for property suggestions. I am not able to understand the difference.
![image](https://user-images.githubusercontent.com/613351/54709162-41f36a00-4b02-11e9-8214-6a1deab99316.png)

add is replaced.
![image](https://user-images.githubusercontent.com/613351/54709217-58012a80-4b02-11e9-8048-d2d9ec78b1de.png)

I will do more digging but just wanted to post to see someone has an answer.

**Comment by nightwing** [comment]
This happens because in the second case is the whole word is included in the text used for filtering and in the second case " is not included https://github.com/ajaxorg/ace/blob/master/lib/ace/autocomplete.js#L189
