### ISSUE TITLE
Unable to use Ace as RequireJS dependency

### ISSUE THREAD

**Issue by Pacheco95** [ajaxorg/ace#3916]
I'm trying to use Ace with RequireJS, but this code below is not working. The Ace script was downloaded, but the required parameter `ace` is always `undefined`.

```javascript
requirejs(['https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.3/ace.js'], function (ace /*always undefined*/) {
  console.log(ace);
});
```
I'm using RequireJS 2.3.6

![Screenshot from 2019-03-24 16-26-55](https://user-images.githubusercontent.com/12385467/54884629-177f1500-4e52-11e9-85b2-79baf1e92572.png)

**Comment by nightwing** [comment]
this seems to be answered in https://stackoverflow.com/questions/55327736/unable-to-use-ace-as-requirejs-dependency

**Comment by Pacheco95** [comment]
Yes! Both were made by me haha

**Comment by bmomani1** [comment]
What to do if I want to require ext-language_tools too
it seems this plugin does not support AMD

currently I managed to make it work via shim (no async loading for it, it shall wait for ace to get loaded)

```
require.config({
    paths: { ace: ['/resources/app/js/lib/ace'] },
    shim: {
        '/resources/app/js/lib/ace/ext-language_tools.js': {
            deps: ['ace/ace']
        },
    }
});


require(["ace/ace", "/resources/app/js/lib/ace/ext-language_tools.js"], function (/*ace and script now in window*/) {
      // some logic
 });
```

is there any thing we could do about it? 
thanks in advance.
