### ISSUE TITLE
Auto complete keywords for Latex not working with Latex mode.

### ISSUE THREAD

**Issue by yadurvt** [ajaxorg/ace#3918]
When editor mode is set to latex using editor.getSession().setMode("ace/mode/latex"), autocomplete works only for local keywords/previously typed keywords. I need to make it done for all latex keywords like \usepackage,\documentclass etc. It works for all other javascript,php modes.

Php and javascript syntax is autocompleted. I need the same for latex mode. Any idea??

**Comment by lcswillems** [comment]
Up! I need the same. Did @yadurvt not use the good code or is it not implemented?
