### ISSUE TITLE
autocomplete break after '.' dot char

### ISSUE THREAD

**Issue by noririco** [ajaxorg/ace#3921]
I have a list of words that includes .

example 
hello.world

1.if I try to autocomplete hello. the autocompleter "breaks" and return the original full list
2.if I try to autocomplete hello the autocompleter return hello.world as suggestion

if I try (2) and after the list is open I type . it WILL find it in the list and let me use it.

so the problem is only when I try to search something that has a '.' already in it

**Comment by meadlai** [comment]
mark it, hope to append method or member after the . dot
so, it is able to autocomplete java methods or members.

**Comment by TomLevvv** [comment]
This behavior is very problematic for me,
When will you add an option to custom it?

Thanks,  
Tom

**Comment by zpf96126** [comment]
mark it.Hope to add a Custom prompt box funtion ,which could only appear when meeting the conditions
