### ISSUE TITLE
HTML tags in javascript

### ISSUE THREAD

**Issue by ArnauCarrasco** [ajaxorg/ace#3922]
Hi all,

I'm having trouble with HTML tags inside javascript code. I've found some solutions, about changing content -> innerHTML, but it did not solve the issue... Consider this code:
```
for (var i = 9; i >= 0; i--) {
      $("#log" + i).html("<h3>Number" + i + "</h3>");
   }
```
In normal ace operation (getContext) the result will be:
```
for (var i = 9; i >= 0; i--) {
      $("#log" + i).html("Number" + i + "");
   }
```
So HTML Tags are deleted... If I change to get innerHTML the tags will remain, but then:
```
for (var i = 9; i &gt;= 0; i--) {
      $("#log" + i).html("<h3>Number" + i + "</h3>");
   }
```
It changes `i >= 0` for `i &gt;= 0`.

So, can I tell Ace something like "get innerHTML only if the text is inside a string"?...

Idk if i'm explaining well...

**Comment by ArnauCarrasco** [comment]
Hi all... I posted the issue and now I post the solution. The editor works well, if you use a code like this:

```
editor.session.setValue("for (var i = 9; i >= 0; i--) test('<h3>')");
```
It works 100% fine. My problem was that I am getting the javascript code from mysql and I just write the code:
```
<pre id="editor">
<?php echo $script; ?>
</pre>
```
Then the setValue is omitted, and then I have the issue. The solution may be filling a javascript variable or an html element with the script, and then pass the setValue function, or just pass a php function and simply echo the result. Just in case someone else has the problem, I paste here the function I made (php):
```
function sql_to_ace($source) {
   $ret = "";
   $sstring = false;
   $dstring = false;
   $last_slash = false;
   for ($i = 0; $i < strlen($source); $i++) {
      if ($source[$i] == '\\' && !$last_slash) {
         $last_slash = true;
      } else {
         $last_slash = false;
      }
      if ($source[$i] == '"' && !$last_slash) $dstring = !$dstring;
      if ($source[$i] == '\'' && !$last_slash) $sstring = !$sstring;
      if ($source[$i] == '<' && ($sstring || $dstring)) {
         $ret .= "&lt;";
         continue;
      }
      if ($source[$i] == '>' && ($sstring || $dstring)) {
         $ret .= "&gt;";
         continue;
      }
      $ret .= $source[$i];
   }
   return $ret;
}
```

**Comment by nightwing** [comment]
You can also use the builtin htmlspecialchars  function to escape html https://www.php.net/manual/en/function.htmlspecialchars.php
