### ISSUE TITLE
Editor not shown completely in bootstrap 4 modal

### ISSUE THREAD

**Issue by nihem** [ajaxorg/ace#3923]
hi, I tried to integrate the ace editor in a bootstrap 4 modal. I initialized it in a td cell of the dataTables details plugin. After doing this only the background without the code is shown in the modal. It looks like there is a kind of width problem, because all underlying elements have no width.

I also made an attemt initializing the editor after timeout unfortunately without success too.

Any ideas?

![code_not_shown](https://user-images.githubusercontent.com/9929245/55473987-53fbff00-5610-11e9-8e04-eb46e8e1bdd7.PNG)
![html](https://user-images.githubusercontent.com/9929245/55474182-d5539180-5610-11e9-8328-fb8e240d0d73.PNG)

**Comment by nightwing** [comment]
Does the `#editor2` div have the correct size? If no, try to get it to have the correct size without calling `ace.edit` since ace doesn't modify the size of the container div. If it has the correct size call editor.resize after the modal dialog is displayed
