### ISSUE TITLE
Multi cursor snippets are available even enableMultiSelect is false

### ISSUE THREAD

**Issue by satetsu888** [ajaxorg/ace#3924]
Snippets like html a tag shows multi cursor even if editor configured as enableMultiSelect: false.
It seems a bit confusing behavior. So I want to prevent to show multi cursor.

Are there anyway to input multi cursor snippets with single cursor?

**Comment by nightwing** [comment]
Unfortunately that would require a significant amount of additional code. 
Could you tell more about your use-case and why completely disabling multicursor is important for it? That would help us to understand how much additional complexity is justified.

**Comment by nightwing** [comment]
Turns out this was easier than expected, https://github.com/ajaxorg/ace/blob/b808ac14ec6d6afa74b36ff5c03452a2832b32a4/lib/ace/snippets.js#L899
