### ISSUE TITLE
VIM keybinding on iOS

### ISSUE THREAD

**Issue by yoshiokatsuneo** [ajaxorg/ace#3925]
VIM keybindings does not work on iOS.
This can be reproduced on iOS emulator on Chrome.

When I type "a", I got text below:
```
cde fg
a
```

And, when I type "a" again, I got text below:
```
cde fg
acde fg
a
```

**Comment by nightwing** [comment]
thanks for the report https://github.com/ajaxorg/ace/issues/3926 fixes this  (can be tested on https://raw.githack.com/ajaxorg/ace/8cbab2bcca20d7d94f41edec4bc6d53c1212a362/kitchen-sink.html)

**Comment by yoshiokatsuneo** [comment]
Thank you for the quick fix !
I see that the issue is fixed!
Could you please update the build repository to include the fix ?
  https://github.com/ajaxorg/ace-builds

Thank you!
