### ISSUE TITLE
Some keyboard shortcuts don't work on firefox on Linux

### ISSUE THREAD

**Issue by scottimcdonald** [ajaxorg/ace#3929]
These 4 change nothing:
Ctrl+Alt+Up
Ctrl+Alt+Down
Ctrl+Alt+Right
Ctrl+Alt+left
This ends up deleting the text instead of changing it to uppercase:
Ctrl+Shift+U

**Comment by nightwing** [comment]
Unfortunately this shortcuts are captured by system level shortcuts on linux, if you have suggestions for alternative shortcuts i'll be happy to add them for linux
