### ISSUE TITLE
setValue in onfocus select text (even with second argument) #jsfiddle provided

### ISSUE THREAD

**Issue by Bonjour123** [ajaxorg/ace#3931]
When calling setValue in a focus handler, the text is always selected from the begining (if second argument is -1) or from the end (if second argument is 1) to the mouse position. 
Could someone provide a quick fix for this really annoying issue ? 

Here is a demo of the described behavior:
http://jsfiddle.net/1gxf0j9q/1/

**Comment by nightwing** [comment]
this happens because you change the value of the editor when mouse is pressed, which resets selection start point to document start.

To avoid this you can cancel the mouse selection before calling setValue

```js
if (editor.$mouseHandler.releaseMouse)
  editor.$mouseHandler.releaseMouse();
```

**Comment by Bonjour123** [comment]
Thank you, this is a lot better. But do you know a way so that the caret is where my mouse was pressed ?

**Comment by Bonjour123** [comment]
> which resets selection start point to document start.

Would it be possible to disable this behavior ?

**Comment by nightwing** [comment]
You can use the mousedown event listener instead of focus event listener to change the value of the editor.

**Comment by Bonjour123** [comment]
Yes it's perfect, a lot simpler than I thought  -_- . Thanks :)
