### ISSUE TITLE
Regexp unconsistent results

### ISSUE THREAD

**Issue by Bonjour123** [ajaxorg/ace#3932]
I'm trying to find a simple regex in the editor. It works for almost all the cases, but for the following, I can't make it work.
Here is the [regexp, in an online tester](https://regex101.com/r/wLgISd/2/)

Here is the [jsfiddle](http://jsfiddle.net/2Ly95gq3/1/) 

Can't find the reason why it doesn't match, and how to make it match.

**Comment by nightwing** [comment]
Currently multiline search works only for literal text. What are you trying to do maybe there is another way to achieve that?

**Comment by Bonjour123** [comment]
Maybe yes, I don't need very extended regexp, just str1.*str2, and that all the result be selected.

-Would it be long to modify the search function for literal text, so that when a certain condition is set, it extracts str1, str2,  search them and select all what is between ? In this case, in which js file the search function is ?
-The second solution is to getValue to a basic string, and make the multiline regex on this string, and return the offset of the first and last chars of the results. But then, how to select this ? Because as I know, selection works in terms of coordinates and not with offsets (don't really understand why this isn't supported though). I'm more for this solution, as it would make a multline regex possible for ace editors, which would be cool !

**Comment by Bonjour123** [comment]
Didn't wanted to close ^^
