### ISSUE TITLE
AcePopup memory leak when ace editor used in a dynamic view such as a modal

### ISSUE THREAD

**Issue by blongstreth** [ajaxorg/ace#3933]
The AcePopup is added to the DOM as follows:
`this.popup = new AcePopup(document.body || document.documentElement);`

When an editor is placed into a modal (as an example) and the user opens/closes the model (modal created, viewed and destroyed), the auto_completion div element is never removed (cleaned up).  This can cause many orphaned elements in the document.  Please fix.  This issue was found as a result of implementing a workaround for #2629 which if fixed, will add tooltips to the document body similar to the AcePopup component.

**Comment by nightwing** [comment]
Thanks for reporting this, i'll change it to create only one instance of popup for all editors.

**Comment by blongstreth** [comment]
Thanks for getting back so quickly.  I am not fully up on how things work but please consider this:  If there is more than one editor in the view (i.e. split view as simple example), will a shared popup be an issue?  In other words, can you think of a case where someone would want the popup to say visible (active) even when the focus is lost.  If so, then I guess just proper cleanup would be better.

**Comment by acejunnan** [comment]
I have the same problem,Could you tell me how to solve it? Thank You.

**Comment by mkslanc** [comment]
Fixed by #3984
