### ISSUE TITLE
Question: Is there a setting to change selection behavior when holding SHIFT + Clicking to add to the selection?

### ISSUE THREAD

**Issue by eastside** [ajaxorg/ace#3935]
**Here's how it works now (see GIF below):** First, select some text from RIGHT TO LEFT. Then, hold SHIFT and CLICK at the end of the line. Ace deselects the original text and selects from the original insertion point to the end of the line.

**Here's what we want:** Keep everything selected that is presently selected. If the user has text selected, and they hold SHIFT and then click to select additional text, the new text should always be added to the selection, even if it was in the opposite direction of the original insertion point. (This is how Sublime Text works.)

It is likely that there is a setting that enables this behavior, but we can't seem to find it. If it exists, what is that setting?

![out](https://user-images.githubusercontent.com/3721132/56249966-9d156f80-6062-11e9-9482-2377b64bbed4.gif)

**Comment by nightwing** [comment]
this is not supported now, we can add the option by adding
```js
if (
    Range.comparePoints(editor.selection.anchor, editor.selection.cursor)
   * Range.comparePoints(editor.selection.anchor, pos) < 0
) {
    editor.selection.moveToPosition(editor.selection.cursor) 
}
```
at https://github.com/ajaxorg/ace/blob/master/lib/ace/mouse/default_handlers.js#L109
