### ISSUE TITLE
how to set the width of gutter layer?

### ISSUE THREAD

**Issue by huiyuye** [ajaxorg/ace#3937]
I have looked for all document for Ace, but i can't search how to set the width of gutter layer. I think I need help. thanks my brother.

**Comment by nightwing** [comment]
You can overrite the $updateGutterWidth method https://github.com/ajaxorg/ace/blob/d3337b5c8e1ce97d643f41caeaedca4beb452008/lib/ace/layer/gutter.js#L171

```js
editor.renderer.$gutterLayer.$updateGutterWidth =  function(config) {
        var gutterWidth = 100;
        if (gutterWidth !== this.gutterWidth && !isNaN(gutterWidth)) {
            this.gutterWidth = gutterWidth;
            this.element.parentNode.style.width = 
            this.element.style.width = Math.ceil(this.gutterWidth) + "px";
            this._signal("changeGutterWidth", gutterWidth);
        }
    };
```

If you tell more about why do you want to set different width, we may be able to add a better/easier method of doing this.

**Comment by huiyuye** [comment]
because I want to write  a IDE of web app on mobile. I want to try that write the code in mobile. just cool ! thank you very much. I will create a mobile Ace if this Ace not suitable for  my project.
