### ISSUE TITLE
[Feature Request] Ability to Disable Emojis

### ISSUE THREAD

**Issue by KelseyCooper24** [ajaxorg/ace#3938]
It would be great to be able to easily disable emojis for ace editor so as to prevent any issues with usage that does not and will never require emoji support.

**Comment by nightwing** [comment]
What do you mean by disabling emojis? filtering them out of pasted text or something else?

**Comment by KelseyCooper24** [comment]
I guess would it be possible to mark the Windows Emojis as invalid in some way?
