### ISSUE TITLE
"SyntaxError: invalid regexp group" Problem with "<" character

### ISSUE THREAD

**Issue by doakey3** [ajaxorg/ace#3941]
I want to add the following rule to my syntax highlighter:

```
{
    token : "bullet_header",
    regex : /(?<=^\*\s).*;/
},
```

But I get the error message:

`SyntaxError: invalid regexp group`

I think it is because of the "<" character I'm using to make a lookbehind assertion in the regex. It doesn't matter if I use a string or a regex, it's the same. Thanks.

**Comment by nightwing** [comment]
Ace does not throw this error.
Which browser do you use? I think `<=` is supported only on latest version of chrome.

It is better to use multiple states instead:
```js
    this.$rules = {
        "start" : [ {
            token : "bullet_header",
            regex : /^\*\s+/,
            next: [{
                token : "bullet_header",
                regex : ";|$",
                next: "start",
            }, {
                defaultToken : "bullet_header",
            }]
        } ,{
            token : "string.regex",
            regex : /(.)/ 
        }]
    };
    this.normalizeRules();
```
