### ISSUE TITLE
Markdown highlight breaks when adding underscore

### ISSUE THREAD

**Issue by ghost** [ajaxorg/ace#3942]
Adding underscore to the markdown breaks the markdown highlighting in the editor.

**Additional info:**
Snapshots from Ace live [demo](http://ace.c9.io/build/kitchen-sink.html)
1. When writing in blockquote
![image](https://user-images.githubusercontent.com/48474184/56658615-b0ef5000-66b8-11e9-8220-e4c51590450e.png)

2. When writing in plain text
![image](https://user-images.githubusercontent.com/48474184/56659154-09731d00-66ba-11e9-92e0-8015d2632b14.png)

Thought it does not break the resultant markdown, text written in a code span works, but highlighting breaks. It highlights as an emphasis but resulting in code span.

**Expected behavior**
It should not highlight as emphasis instead, code span should take more precedence.

**Comment by tessus** [comment]
This is a parsing error of the hl engine (or the rules are wrong).

Italics should only be highlighted when surrounded by 
- at least one space on both sides 
- at least one space on one side and a punctuation character on the other

<img width="469" alt="image" src="https://user-images.githubusercontent.com/223439/77197636-ed3f5200-6abb-11ea-98b5-63e3da7eb179.png">

As you can see [here](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22This%20is%20%2Aitalics%2A%20text.%20Or%20_italics_.%5Cn%5CnThe%20following%20are%20highlighted%20but%20shouln%27t%20be.%20These%20examples%20are%20not%20rendered%20as%20italics%3A%5Cn%5Cn%23%20mod_authnz_ibmdb2%5Cn%5CnWithin%20text%20mod_authnz_ibmdb2%20text%5Cn%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-markdown%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Afalse%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D), they are not rendered as italics.

This behavior is really annoying the only way to make text readable is to override `.ace_string.ace_emphasis` with the color of the standard text.
