### ISSUE TITLE
Vim: column position not preserved when moving up / down lines

### ISSUE THREAD

**Issue by kevinushey** [ajaxorg/ace#3943]
Using current kitchen sink:

![vim-lines](https://user-images.githubusercontent.com/1976582/56699154-3f5bd580-66a9-11e9-8bef-dbf4d6956c80.gif)

Note that the cursor column when moving to line 4 is now at the start of the line, rather than the original cursor column as on line 2.

This appears to only affect Vim in normal mode, insert / visual / visual block modes are all fine.

**Comment by kevinushey** [comment]
Looks like this is the code resetting the column position of the cursor:

https://github.com/ajaxorg/ace/blob/a2dad44e1e1804e97d1e3996e4f500461ea15ed7/lib/ace/keyboard/vim.js#L5882-L5883

Just a guess, but maybe the check here needs to be tweaked?

https://github.com/ajaxorg/ace/blob/a2dad44e1e1804e97d1e3996e4f500461ea15ed7/lib/ace/keyboard/vim.js#L6102-L6103

**Comment by nightwing** [comment]
looks like `if (isHandled ` should have been `if (!isHandled `
