### ISSUE TITLE
How to make matched fields repeatable.

### ISSUE THREAD

**Issue by catherinezhxj** [ajaxorg/ace#3946]
![1](https://user-images.githubusercontent.com/23161404/56858463-fcea0f80-69ac-11e9-9254-d6527173e72b.jpg)
![2](https://user-images.githubusercontent.com/23161404/56858464-fcea0f80-69ac-11e9-9afd-cdfa0b3c97ea.jpg)

When the matched fields are repeated, the fields are de-duplicated.
But because my table names are different, I want to keep duplicate fields.

So how do I deal with it?

**Comment by nightwing** [comment]
you can disable deduplication by modifying the setFilter method of FilteredList
```js
    require("ace/autocomplete").FilteredList.prototype.setFilter = function(str) {
        if (str.length > this.filterText && str.lastIndexOf(this.filterText, 0) === 0)
            var matches = this.filtered;
        else
            var matches = this.all;

        this.filterText = str;
        matches = this.filterCompletions(matches, this.filterText);
        matches = matches.sort(function(a, b) {
            return b.exactMatch - a.exactMatch || b.$score - a.$score 
                || (a.caption || a.value) < (b.caption || b.value);
        });

        this.filtered = matches;
    };
```
