### ISSUE TITLE
Changing parentheses behaviour?

### ISSUE THREAD

**Issue by jonathanpipe** [ajaxorg/ace#3949]
I'd like to change the default way parentheses highlighting works.

<img width="289" alt="Screen Shot 2019-05-08 at 6 20 27 AM" src="https://user-images.githubusercontent.com/38086784/57368592-84781100-7159-11e9-9f5f-9b58826931b0.png">

- Instead of putting a box around only one of the 2 parentheses, I'd like to put boxes around both of them. 
- Instead of using boxes, I'd like to change the color of the parentheses themselves.
- If the selected parentheses has no match, I'd like to change its color to red.

Is there a way to configure this? If not, how would I begin to implement this?

**Comment by nightwing** [comment]
Currently there is no configuration for this. To highlight both ranges and highlight the error you'll need to modify https://github.com/ajaxorg/ace/blob/e44205741fde63b5138a6db55b59ef8bc04235a7/lib/ace/editor.js#L524 by creating a new function findMatchingBracketRanges that will return an object with both ranges, and changing the removeMarker call to remove the marker only after the cursor leaves the bracket range.

Changing the color is a bit more complicated, we'll need to either add a textcontent option for the markers, or modify the text layer to allow changing the classes of rendered tokens based on markers.
