### ISSUE TITLE
Could ace define different sizes for heighlighting words

### ISSUE THREAD

**Issue by seuliang** [ajaxorg/ace#3950]
Could ace define different sizes for heighlighting words?
so that, titles and subtitles in same page can be separated more easily

**Comment by nightwing** [comment]
This is  not supported so far, but i'd like to implement this soon.
Do you want to use this with markdown or some other mode?

**Comment by seuliang** [comment]
I'd like to use it with markdown. I see this feature from **stackedit** which i think is useful.
