### ISSUE TITLE
Suggestion: Provide a way to disable old browsers support

### ISSUE THREAD

**Issue by marcagba** [ajaxorg/ace#3952]
Hello!
In [lib/ace/ace.js](https://github.com/ajaxorg/ace/blob/master/lib/ace/ace.js), we systematically call the line `require("./lib/fixoldbrowsers");`

In [lib/ace/lib/fixoldbrowsers.js](https://github.com/ajaxorg/ace/blob/master/lib/ace/lib/fixoldbrowsers.js) we call polyfills like `require("./es5-shim");` that all browsers above IE11 supports natively.

As ace is a relatively old project in the web age, I understand why these polyfills are here.

It could be great to provide a way  (appart from forking the repo) to disable these polyfiils loading when wanted, as they can represent up to thousands of unwanted lines in browsers above IE11 which are pretty common nowadays!

I'm not sure for now about how to proceed, but would a PR in this way be welcomed ?

**Comment by nightwing** [comment]
Hi, this is something i wanted to do, but couldn't think of any good backwards compatible way so far.
Maybe we should publish new npm package with ace in esm or commonjs format? Would be happy to hear any suggestions you have.

**Comment by marcagba** [comment]
The esm format sounds appealing! We wouldn't need to publish a new npm package. Instead, we could leverage the `module` field within [package.json](https://stackoverflow.com/questions/42708484/what-is-the-module-package-json-field-for).

It is a way for providing an es2015 ready version of a library without breaking backward compatibility.

It is seems to be a _de facto_ standard, as bundlers like [webpack v2.x](https://webpack.js.org/guides/author-libraries/#final-steps) and [rollup](https://github.com/rollup/rollup/wiki/pkg.module) supports it!

What do you think about it ?
