### ISSUE TITLE
Text replacement fails on RTL line

### ISSUE THREAD

**Issue by dometto** [ajaxorg/ace#3957]
On ACE 1.4.4, `editor.replace` seems to behave weirdly on RTL lines, but:

* only when dealing with the first or last word on the line
* only when the replacing text contains non-alphanumeric characters on the outside of the string.

To reproduce, take the following line and shift to RTL with `Ctrl-Alt-Shift-R`:

```
‫test foo bar
```

Execute the following code:
```js
var Range = ace.require('ace/range').Range;
selRange = new Range(0, 1, 0, 5); // 1 and 5 instead of 0 and 4 because of the bidi character at position 0.
```

Now this:
```js
window.ace_editor.session.replace(selRange, "XtestX");
```
Gives the following, correct result:
```
XtestX foo bar
```

While this:
```js
window.ace_editor.session.replace(selRange, "_test_");
```

Gives the following, incorrect result:
```
‫_test_ foo bar
```

Similarly, trying to replace `bar` gives the following incorrect result:

```
_test foo _bar
```

However, replacing `foo` with `_foo_` gives the correct result `test _foo_ bar`.

**Comment by dometto** [comment]
I've tested, and the bug already exists on `1.4.1`, so it's not something recently introduced (I haven't tried further back).

**Comment by dometto** [comment]
Further information: I can also reproduce this on the currently online Kitchen Sink, changing what's necessary:
```
var Range = require('ace/range').Range;
selRange = new Range(0, 1, 0, 5);
window.ace.session.replace(selRange, "_test_");
```

**Comment by nightwing** [comment]
This is not related to replace

```js
editor.setValue("_test_ foo bar", 1)
editor.setOption(editor.$options.rtlText.name, true)
editor.execCommand("rightToLeft")
```

produces the same result.

**Comment by nightwing** [comment]
Turns out this is the rendering that is defined in bidi algorithm. The equivalent of this string with ltr characters
```
"_\u05d0\u05d0_ \u05d0\u05d0"
```
is rendered as
```
_אא_ אא
```

What rendering do you expect?

**Comment by dometto** [comment]
That still seems to have the _ around the word, which would be fine. But the result I'm seeing is one where the _ characters no longer surround the word. This effectively breaks markup (in this case, markdown) for RTL. Apologies if I misunderstood!

**Comment by nightwing** [comment]
In your example _ is around the word as well, markdown doesn't render the word with emphasis because the first _ is preceded by "\u202b" and commonmark requires _ to be preceded by either punctuation or whitespace https://spec.commonmark.org/0.29/#emphasis-and-strong-emphasis.

Maybe the rtl option would work better for your use case as it doesn't modify the document itself?

**Comment by dometto** [comment]
> is rendered as ...

Just noticed something interesting. The output you pasted displayed as expected on the Octodroid app, but I'm getting the mistaken output in the browser.

In the app (correct, expected):

![Screenshot_20190516-165441](https://user-images.githubusercontent.com/147111/57864463-366ba900-77fc-11e9-9a80-e1adbcefc7c2.png)

In the browser (incorrect, same as the original problem I encountered):

<img width="767" alt="Screenshot 2019-05-16 at 16 54 48" src="https://user-images.githubusercontent.com/147111/57864106-97df4800-77fb-11e9-93d6-e6453b610a9f.png">

**Comment by dometto** [comment]
> Maybe the rtl option would work better for your use case as it doesn't modify the document itself?

I get  the same result when using the rtl option. In the kitchen sink, compare how the following two lines behave before/after activating the RTL option.

Before:

<img width="245" alt="Screenshot 2019-05-16 at 17 06 55" src="https://user-images.githubusercontent.com/147111/57865025-2902ee80-77fd-11e9-9db3-f3dfc9c1f4db.png">

After:

<img width="75" alt="Screenshot 2019-05-16 at 17 07 02" src="https://user-images.githubusercontent.com/147111/57865041-2ef8cf80-77fd-11e9-8c93-c253c1ac9e9e.png">

One would expect `_das_ das` on the second line, no?

**Comment by nightwing** [comment]
The text on second line is still `_das_ das` but according to bidi rules _ takes the direction of preceding text so the first _ is rendered on the right, then english character starts a left to right span, and the second _ is rendered in the middle of it.

**Comment by dometto** [comment]
Ah, thank you for explaining the proper behavior! The combination of English characters on an RTL line was what was confusing me.
