### ISSUE TITLE
Auto-close special characters everywhere

### ISSUE THREAD

**Issue by defunkt** [ajaxorg/ace#396]
Right now JavaScriptMode auto-closes special characters such as " ' ( { etc. It also surrounds text with these characters if you select the text then type one, e.g. selecting `user` and typing `"` produces `"user"`.

It'd be awesome if this feature was enabled in every mode. Maybe in TextMode? In TextMate even plain text mode auto-closes quotes and it's great.

In particular, I'm missing this feature when writing CoffeeScript, Ruby, Markdown, etc.
@gissues:{"order":54.65838509316791,"status":"backlog"}

**Comment by nightwing** [comment]
this have been fixed some time ago https://github.com/ajaxorg/ace/pull/2936
