### ISSUE TITLE
FontAwesome 5

### ISSUE THREAD

**Issue by fncap** [ajaxorg/ace#3962]
There Will be any plan to update to FontAwesome 5, or is there any workound to use it?
I'm using FontAwesome5 on my last Angular WebApp, and ACE toolbar is missing some icons, like headings icon, because 'fa-header' is now 'fa-heading'!

**Comment by nightwing** [comment]
Ace doesn't provide a toolbar and doesn't use fontAwesome. This must be a feature added by some other project.

**Comment by fncap** [comment]
I'm sorry ... it was my fault, frenetic to choose on which project add that issue!
