### ISSUE TITLE
take into PHP account declare(strict_type = 1)

### ISSUE THREAD

**Issue by paulbohman** [ajaxorg/ace#3965]
It may be that I'm using a version of Ace that is outdated, but when I use the following line in PHP, the syntax validator calls this an error:

declare(strict_type = 1);

This syntax is available only in PHP 7, not earlier versions of PHP, but it is valid and I need Ace to allow it. Right now, I get a message saying that the equals sign is unexpected, and that it expects a closed parenthesis. All syntax validation stops working from that point on in the code.

The version I'm using is the one available for the MODX content management system (https://modx.com/extras/package/ace), which hasn't been updated in a while, but looking through the Ace code here on Github, I couldn't find a reference to declare(strict_type = 1); Can this be added? Or how can I add it to my own instance of Ace?

**Comment by nightwing** [comment]
this doesn't produce any errors with ace v1.4.4 on https://ace.c9.io/build/kitchen-sink.html?doc=php
So using the current version should fix the issue.

**Comment by nightwing** [comment]
Closing as this appears to be fixed in the current version, but please let me know if there is anything else i can help with.
