### ISSUE TITLE
Small HTML breaks editor

### ISSUE THREAD

**Issue by prettydiff** [ajaxorg/ace#3966]
I am using the latest version of Ace published on NPM and this following code sample produces a JavaScript error in the editor:

```html
<a class="nav-link" {% if m.href is defined %} href="{{ m.href }}" {% endif %} {% if m.id is defined %} id="{{ m.id }}" {% endif %}>
    <em class="fa fa-icon"></em>
    <p>{{ m.label }}</p>
</a>
```

The reported error is:

```
TypeError: self.$tabStrings[tabSize] is undefined[Learn More] ace.js:16379:17
    $renderToken http://localhost:9001/node_modules/ace-builds/src/ace.js:16379
    $renderSimpleLine http://localhost:9001/node_modules/ace-builds/src/ace.js:16520
    $renderLine http://localhost:9001/node_modules/ace-builds/src/ace.js:16563
    $renderLinesFragment http://localhost:9001/node_modules/ace-builds/src/ace.js:16316
    update http://localhost:9001/node_modules/ace-builds/src/ace.js:16342
    $renderChanges http://localhost:9001/node_modules/ace-builds/src/ace.js:18351
    <anonymous> self-hosted:974
    _flush http://localhost:9001/node_modules/ace-builds/src/ace.js:17039
```

Here is another code example producing a similar error: https://github.com/prettydiff/prettydiff/issues/591

**Comment by nightwing** [comment]
This can happen if tabSize option is set to 0, could you please check if that is what is happening when you see the error.

**Comment by prettydiff** [comment]
I am using 4 spaces for indentation.

**Comment by nightwing** [comment]
here's what i have tried:

- open https://prettydiff.com/ in private firefox 67 window
- paste the text copied from this issue into both ace instances on the page, press execute.
- do the same with the view source text from linked issue
- paste the text in https://ace.c9.io

in all cases there was no error in the console, and everything was working correctly. Could you describe the steps you take before seeing the error?

**Comment by prettydiff** [comment]
Playing with just the small code sample above I cannot reproduce on prettydiff.com either.  I am experiencing this when running the Pretty Diff application on my local although the problem identified in my issue 591 was found by one of my users and I could reproduce that.

It is somehow related to a space character as the value of Pretty Diff's *indent_char* option.  When I change the value to letter *x* the issue goes away.  When I change the value back to space the issue is present again only when I reload the page.  Setting a space for that option value executes `getSession().setUseSoftTabs(true)`;.  Code - https://github.com/prettydiff/prettydiff/blob/master/api/prettydiff-webtool.ts#L546-L580

I updated the stacktrace with valid line numbers using the *src* code instead of *src-min-noconflict*.

I have tried altering various options on my tool and still cannot reproduce the defect using that small code sample above on my public domain.  I don't know what I did the present this error.  I probably just pasted it into my editor using CTRL+V and I believe the defect automatically presented.

**Comment by nightwing** [comment]
Could you please try to modify the getScreenTabSize 
 function in your local version of ace similar to this commit https://github.com/ajaxorg/ace/commit/77256ffb2b1accab3575ba0ae6158e586d4cd842, to ensure that this is not anything related to tabSize being 0

**Comment by prettydiff** [comment]
Without thinking I changed the contents of the editor as necessary to test an unrelated issue and I can no longer reproduce this defect.  I am taking precautions in my code that the value for setTabeSize will always be a number never less than 1.

**Comment by nightwing** [comment]
I've also added a check for >0 in https://github.com/ajaxorg/ace/pull/3972/commits/14835b9e66dc56af513b39d22917f61cc8bd6296
