### ISSUE TITLE
addEventListener not updating textareas

### ISSUE THREAD

**Issue by SuperSajuuk** [ajaxorg/ace#3976]
Hello

A couple of years ago, I needed some help with updating a text editor's value after submitting a form with a button, see here: https://github.com/ajaxorg/ace/issues/3434

The solution provided there worked at that time, but I've been rewriting functionality in the application and for some reason, the specific code to "add an event listener" that would update the value in the textarea with that of the value of the ace editor, no longer works. There is no indication that the event listener has been added or that the trigger is working.

The only change I have made is that the button opens a Popover, rather than a screen-covering modal, would this have any effect on making a button that should be acting as a Submit listener not update as required?

Here is my function to make the ace Editor and bind an event listener to the submit event:
```
function createEditor(page, name, state) {
	// find the textarea
	var textarea = document.querySelector("textarea[name='" + name + "']");
	
	// create ace editor
	var editor = ace.edit();
	editor.container.style.height = "300px";
	editor.setTheme("ace/theme/twilight");
	editor.getSession().setMode("ace/mode/json");
	editor.session.setValue(textarea.value);

	// Disable if read only
	if (state === true) {
		editor.setReadOnly(true);
	} else {
		editor.setReadOnly(false);
	}

	// replace textarea with ace
	textarea.parentNode.insertBefore(editor.container, textarea);
	textarea.style.display = "none";

	// find the parent form and add submit event listener
	if (page === "edit_cfg") {
		var form = textarea;
		while (form && form.localName !== "form") form = form.parentNode;
		form.addEventListener("submit", function () {
			// update value of textarea to match value in ace
			textarea.value = editor.getValue();
		}, true);
	}
}
```
Here is the code that handles the form creation and the button to submit the form:
```
<form name="UpdateConfiguration">{% autoescape false %}
	Guild Bot Configuration: <br /><textarea name='guild-data' rows=15 style="width: 80%">{{ guildConfig }}</textarea><br />
	Guild Permissions: <br /><textarea name='perm-data' rows=15 style="width: 80%">{{ perms }}</textarea>{% endautoescape %}<br />
	<div align="right" id="UpdateBtn"><button id="TriggerUpdate" class="btn btn-sm btn-light" onclick="validateConfiguration('{{ guildID }}');return false;">Validate</button></div>
</form>
```
Any help would be appreciated :)

**Comment by nightwing** [comment]
maybe if (page === "edit_cfg") { prevents the event listener from being added

**Comment by SuperSajuuk** [comment]
> maybe if (page === "edit_cfg") { prevents the event listener from being added

@nightwing the other code works fine. I tested by doing console.log(); in random places, everything apart from the .addEventListener code is working as intended. Could a popover from bootstrap cause the event listener to not be seen as a submit?

**Comment by nightwing** [comment]
Please create a jsbin reproducing the issue and i can help you to debug it, without the example i do not have enough information to tell what is going wrong, since the issue is not related to ace.

**Comment by SuperSajuuk** [comment]
@nightwing https://jsbin.com/nafojaqesi/edit?html,js,output as requested. First time I've used JSBin so please bear with me on how it looks 👍

**Comment by nightwing** [comment]
Since you are using javascript to submit the data, you do not need need the textarea at all, just use the editor.getValue() in the validateConfiguration function https://jsbin.com/leqeyizehi/edit?html,js,output

**Comment by SuperSajuuk** [comment]
Thank you! This code works as I expect!
