### ISSUE TITLE
Editor options to disable auto-close of special characters and auto-indent.

### ISSUE THREAD

**Issue by iebuggy** [ajaxorg/ace#398]
Preface:  I like typing every single character and generally dislike code editors that attempt to automatically write code for me.  I was attempting to write some Javascript in ACE last night, eventually got frustrated, and ended up typing the code in my favorite external editor.

First, the automatic closing of characters (parenthesis, quotes, etc) seems like a cool feature to have as a lot of people like auto-closing characters, but I've found that the current support in ACE is too flaky for use in a production environment.  There needs to be an option to turn this feature on/off.

Related issue:  Automatic indentation is wildly inconsistent.  There needs to be a separate option to turn this feature on/off.

Related bug:  Selecting some spaces near the start of a line and pressing Tab on the keyboard doesn't replace the selected spaces with a tab - the auto-indent feature is probably getting in the way.  The ACE demo has this problem too.
@gissues:{"order":53.41614906832319,"status":"backlog"}

**Comment by nightwing** [comment]
fixed by https://github.com/ajaxorg/ace/pull/4225
