### ISSUE TITLE
Full screen issues in the scrollable page demo

### ISSUE THREAD

**Issue by knivre** [ajaxorg/ace#3981]
Hi,

While playing with [the scrollable page demo](https://ace.c9.io/demo/scrollable-page.html) (using Firefox and Chromium), I noticed multiple issues when hitting F11 in the first editor:
 - sometimes, only line #7 is visible and it is impossible to scroll up (no scroll bar); in this case, the default 8px margin from the \<body\> is visble on the left, on the right but neither at the top nor at the bottom.
  - sometimes, it goes full screen as expected (no 8px margin at the bottom though). Adding enough lines at the end of the snippet makes a scrollbar appear (not imediately though), however it seems possible to have lines below the scrollview (in which case one has to type at least one character on the current line for the editor to adjust itself) but also above it (in which case one has to resize the browser window until the editor adjusts itself).

As I am writing this report, I have no clue as to what triggers one behaviour or the other.

**Comment by nightwing** [comment]
This happens because `transform` applied to the body breaks position fixed. Attached pull request should fix this.
