### ISSUE TITLE
Ace on server side

### ISSUE THREAD

**Issue by lcswillems** [ajaxorg/ace#3990]
Hi,

Is it possible to use Ace on the server side?

I mean: I give a code and a language to Ace and it returns a string.

**Comment by nightwing** [comment]
Hi, it is possible to use ace like that for creating highlighted text. See the example at https://github.com/ajaxorg/ace/blob/master/demo/static-highlighter/server.js#L9. Only limitation is that `amd-loader` is required for ace to work.

**Comment by lcswillems** [comment]
Okay, thank you!
