### ISSUE TITLE
How to reset the auto complete custom strings and adding new 

### ISSUE THREAD

**Issue by PrabakarKaruppasamy** [ajaxorg/ace#3991]
Hi Team,

I have added the custom strings into the editor like below.

```
      /**To add the customize atoms */
    var langTools = ace.require("ace/ext/language_tools");
    console.log('langTools', langTools.snippetCompleter, langTools.textCompleter);

    var stepLineCompleter = {

      getCompletions:function(editor, session, pos, prefix, callback)
      {
        var completions = [];
            console.log('before foreach....', this.atomFields, fieldsList);
            fieldsList.forEach(function(w)
        {
            completions.push({
              value:w,
              meta:"keyword",
              name:'atom'
            });
        });
        callback(null, completions);
      }

    }
    langTools.addCompleter(stepLineCompleter);
```
the fieldlist list keep on updating/changing.. That means every time i get new data from server.  Once the data was changed i need to remove the existing custom strings added into editor and needs to add the new data which i got it from the server.

Please let me know how can we achieve this?

**Comment by nightwing** [comment]
Hi
if you change the value of `fieldsList` the `getCompletions` function will automatically use the new `fieldsList` when invoked. So it is not required to add a new completer object every time the `fieldsList` is changed

**Comment by PrabakarKaruppasamy** [comment]
@nightwing Thanks for your response... can you please elaborate this.  what you mean by new completer object.. Sorry I am newbie to this.  Once again thanks a lot

**Comment by nightwing** [comment]
Could you show more of your code, the part where you get fieldsList

**Comment by PrabakarKaruppasamy** [comment]
@nightwing Sure I have share the entire function as below. Please let me know if u need any info.

`loadFields(){
  this.iteService.getAtomFields(this.saveIteObj).subscribe(value => {
    if(value.success == true){
      this.fields = value.payload;
      var fieldsList = this.fields;
      console.log('B4 fields....', fieldsList);
      /**To add the customize atoms */
    var langTools = ace.require("ace/ext/language_tools");
    console.log('langTools', langTools.snippetCompleter, langTools.textCompleter);
    var stepLineCompleter = {

      getCompletions:function(editor, session, pos, prefix, callback)
      {
        var completions = [];
            console.log('before foreach....', this.fields, fieldsList);
            fieldsList.forEach(function(w)
        {
            completions.push({
              value:w,
              meta:"keyword",
              name:'atom'
            });
        });
        callback(null, completions);
      }

    }
    langTools.addCompleter(stepLineCompleter);
    }
    else{
      return false;
    }
    console.log("value of load...", value.payload);
  });
}`

**Comment by nightwing** [comment]
move stepLineCompleter out of that function

```js
    var fieldsList = []
    /**To add the customize fields*/
    var langTools = ace.require("ace/ext/language_tools");
    console.log('langTools', langTools.snippetCompleter, langTools.textCompleter);
    var stepLineCompleter = {
      getCompletions:function(editor, session, pos, prefix, callback) {
        var completions = [];
            console.log('before foreach....', this.fields, fieldsList);
            fieldsList.forEach(function(w) {
            completions.push({
              value:w,
              meta:"keyword",
              name:'atom'
            });
        });
        callback(null, completions);
      }

    }
    langTools.addCompleter(stepLineCompleter);


loadFields(){
  this.iteService.getfields(this.saveIteObj).subscribe(value => {
    if(value.success == true){
      this.fields = value.payload;
      fieldsList = this.fields;
      console.log('B4 Atom fields....', fieldsList);
    }
    else{
       fieldsList = [];
       return false;
    }
    console.log("value of load...", value.payload);
  });
}

```

**Comment by PrabakarKaruppasamy** [comment]
Thanks for your valueable response. It is works as expected. So the design would we need to initialize only one time right.

**Comment by nightwing** [comment]
Yes, if you need different completers for different editors, you can modify editor.completers array instead.

**Comment by PrabakarKaruppasamy** [comment]
@nightwing  we need the different completers for different editors for that how to modify the editor. Can we pass the editor parameters dynamically?
