### ISSUE TITLE
Bug in delta values in editor.on('change') event

### ISSUE THREAD

**Issue by raffi-ismail** [ajaxorg/ace#3994]
```javascript
editor.on('change', function(delta) {
    console.log(delta);
}
```
With the following lines (note \n represents empty lines):
```text
LINE 1
LINE 2
LINE 3
\n
\n
LINE 6
```

Cursor at line 5, hit backspace, delete line 5

Expected delta value:
```javascript
{
    action: "remove",
    end: {row: 4, column: 0},
    lines: (2) ["", ""],
    start: {row: 5, column: 0}
}
```

Actual delta value:
```javascript
{
    action: "remove",
    end: {row: 4, column: 0},
    lines: (2) ["", ""],
    start: {row: 3, column: 0}
}
```

I think there's a need to also include \r and/or \n in 'lines' value to distinguish between removals of empty lines and removal "into empty lines"

**Comment by nightwing** [comment]
Why do you expect for the dela to be on range `5/0=>4/0` ? Range end is always greater than range start, and the removed character is one on the left from cursor, so the range should be the same as the range returned by pressing shift-left and running `editor.selection.getRange()+""` which is `"Range: [3/0] -> [4/0]"` consistently with the delta.

**Comment by raffi-ismail** [comment]
My bad. I got confused with the zero based row numbering in the source and the ui which starts with 1.
