### ISSUE TITLE
Ace Logo as SVG?

### ISSUE THREAD

**Issue by PythonLinks** [ajaxorg/ace#3999]
Would it be possible to get a copy of the Ace Logo as an SVG file?

I am presenting the forestwiki.com at EuroPython as a poster session.  The Forest Wiki makes heavy use of the Ace Editor for editing HTML, CSS, Javascript, Pug, and Python, so it would be great to be able to add your logo to my poster.  But I worry that a png file  will not print well.  It is a large poster.

**Comment by nightwing** [comment]
Unfortunately i do not have svg version, but i can try to get the psd file if it is still needed.

**Comment by PythonLinks** [comment]
The poster has been printed.

It looks fine.

Thanks you

Chris
