### ISSUE TITLE
Ace Editor for inline code

### ISSUE THREAD

**Issue by lcswillems** [ajaxorg/ace#4002]
Is it possible to use Ace editor for inline code ?

E.g. `<p>This code</p>`, not:

```
<p>This code</p>
```

**Comment by nightwing** [comment]
It is possible to set display of editor container element to "inline-block", but it requires setting the width of the editor explicitly, which may be not what you are looking for. 
For your use case what should happen if text is too long for one line, or user inserts new line?

**Comment by lcswillems** [comment]
Yes, I tried to, but there is the problem with the `width` that is to set. But maybe there is a way to autoresize it?

If it is inline code, user is not allowed to insert new lines or to write too long text for one line.

**Comment by lcswillems** [comment]
I may have a solution, but not working perfectly:

While an inline code is edited, I can update its width to be `n_char * char_width`, i.e. the number of characters times the width of a character (as the font is monospaced).

However, it doesn't work. Ace Editor doesn't seem to update the width internally even if I update the style width.

**Comment by lcswillems** [comment]
Okay, I just have to use `editor.resize()`. But it is mentioned nowhere.

Once again, thank you for your help!
