### ISSUE TITLE
Hide the other bracket

### ISSUE THREAD

**Issue by lcswillems** [ajaxorg/ace#4003]
Hi,
If I write `{}` in Ace Editor and put the cursor before the first bracket, I will have second one highlighted. How to disable it?

**Comment by nightwing** [comment]
Hi
there is no way to disable it via setOption, but it can be disabled by changing the highlightBrackets method on the editor `editor.$highlightBrackets = function() {}`. 

Why do you want to disable it? If it is a common requirement we could add an option for it to the core.

**Comment by lcswillems** [comment]
Thank you, it works!
But I still have a similar issue.

In fact, my code is the following (it is Latex code):

```
\begin{itemize}
\item An item.
\end{itemize}
```

And `\end` is surrounded by a border. I would like to remove it also.

More generally, I am trying to disable the editor when it is blurred. So, currently, when it blurs, I do:

```
editor.setOptions({
        readOnly: true,
        highlightActiveLine: false,
        highlightGutterLine: false,
        highlightSelectedWord: false,
});
```

But it is not sufficient. I need to hide the surrounded ending bracket or `\end{itemize}`.

**Comment by nightwing** [comment]
Are you trying to build some kind of notebook, where unfocused cells are supposed to look as if they are not editors?

In that case using css would be better
```
.ace_editor:not(.ace_focus) .ace_marker-layer,
.ace_editor:not(.ace_focus) ace_cursor-layer {
    display: none;
}
```

**Comment by lcswillems** [comment]
Thank you!! It works great. I also added this:

```
.ace_editor:not(.ace_focus) .ace_gutter-active-line {
    background-color: initial;
}
```

So my full code is:

```
.ace_editor:not(.ace_focus) .ace_marker-layer,
.ace_editor:not(.ace_focus) ace_cursor-layer {
    display: none;
}
.ace_editor:not(.ace_focus) .ace_gutter-active-line {
    background-color: initial;
}
```

I think this code must be written in the documentation because I think a lot of people want this.
