### ISSUE TITLE
Disable information tooltips

### ISSUE THREAD

**Issue by lcswillems** [ajaxorg/ace#4004]
Is it possible to disable this kind of information tooltip?

![image](https://user-images.githubusercontent.com/5437552/60576836-72dc6f80-9d7e-11e9-86f4-407168d91d27.png)

**Comment by nightwing** [comment]
you can use `editor.on("showGutterTooltip", tooltip=> { tooltip.hide(); });`

**Comment by lcswillems** [comment]
And is it possible to hide the little `i` also?

**Comment by nightwing** [comment]
If you want to remove annotations as well then simply do `editor.session.setUseWorker(false)`

**Comment by lcswillems** [comment]
Thank you for the help :)
