### ISSUE TITLE
VSCode keyboard shortcuts

### ISSUE THREAD

**Issue by lcswillems** [ajaxorg/ace#4005]
Hi,
Is there any plan to add the Visual Studio Code keyboard shortcuts?

**Comment by YellowAfterlife** [comment]
You would want to write a keyboard shortcut mapper like the existing ones:
https://github.com/ajaxorg/ace/tree/master/lib/ace/keyboard
It is not a particularly hard task (I can't think of anything unusual that VSC shortcut theme requires) but it would take some time.
