### ISSUE TITLE
Support for regex lookaheads in search & replace

### ISSUE THREAD

**Issue by 40thieves** [ajaxorg/ace#4006]
Search & replace does not appear to support positive look-aheads:

<img width="842" alt="Screen Shot 2019-07-05 at 14 39 47" src="https://user-images.githubusercontent.com/424411/60726161-cbed0480-9f32-11e9-86a3-a3b932ff21aa.png">

The search result is highlighted, but clicking the Replace button here does nothing.

**Comment by cipri-tom** [comment]
Interestingly, _negative_ lookahead does work:
![Screenshot 2022-01-31 at 14 14 43](https://user-images.githubusercontent.com/2991890/151799858-cb49efb0-7372-46bb-acd3-46da021b4fbf.png)

![Screenshot 2022-01-31 at 14 15 02](https://user-images.githubusercontent.com/2991890/151799893-06e7fe81-83a4-417a-9374-6d5e701fa91f.png)

(here I'm using it in Google Earth Engine)
