### ISSUE TITLE
Autocomplete popup broken on iOS

### ISSUE THREAD

**Issue by jdmunro** [ajaxorg/ace#4009]
The autocomplete popup doesn't render correctly on iOS. You can also reproduce this by using an iPhone user agent in Google Chrome:

 
<img width="465" alt="Screenshot 2019-07-08 at 13 06 19" src="https://user-images.githubusercontent.com/17656/60808872-38f5d980-a181-11e9-96e1-628f16bf00f4.png">

Repro here (this is using `react-ace` but the issue is with the underlying ace CSS): https://codesandbox.io/s/gifted-banach-v4kkn

**Comment by nightwing** [comment]
This is fixed in the latest version of ace, try using ace-builds instead of brace which is old.

https://codesandbox.io/s/modest-raman-dmwn8. If you are using webpack you may need to add a ignore rule for brace to keep bundle size small.

**Comment by jdmunro** [comment]
@nightwing Thanks for the example - indeed that's solved the problems 🎉
