### ISSUE TITLE
Ace is available on PageCDN

### ISSUE THREAD

**Issue by praisedpk** [ajaxorg/ace#4011]
PageCDN uses **brotli-11** compression that reduces ace.js size by more than 11 KBs compared to other CDNs. In addition, **immutable caching** is enabled by default to optimize content delivery a little more aggressively. [Ace CDN](https://pagecdn.com/lib/ace) on PageCDN.

    83.20 KB   ace.js on PageCDN
    94.48 KB   ace.js on other CDNs

Thanks.

**Comment by nightwing** [comment]
Thanks
