### ISSUE TITLE
html:mode tab key not working

### ISSUE THREAD

**Issue by adyuebanwan** [ajaxorg/ace#4014]
if I set 
EDITOR.getSession().setMode("ace/mode/html");

when I press Tab key, it's not working

**Comment by adyuebanwan** [comment]
demo:https://ace.c9.io/#nav=embedding

work:  
  var editor = ace.edit("editor");
    editor.setTheme("ace/theme/monokai");
    editor.session.setMode("ace/mode/javascript");

not work:
    var editor = ace.edit("editor");
    editor.setTheme("ace/theme/monokai");
    editor.session.setMode("ace/mode/html");

**Comment by nightwing** [comment]
Could you try to modify this jsbin to reproduce the issue https://jsbin.com/mecizazuxe/edit?html,output, 
on it tab works with html mode.

**Comment by adyuebanwan** [comment]
I kown the reason，it's because of ace version;
https://ace.c9.io/build/src/ace.js not work!
https://ajaxorg.github.io/ace-builds/src-noconflict/ace.js work!
https://pagecdn.io/lib/ace/1.4.5/ace.js      all not work! (I download from here)

**Comment by adyuebanwan** [comment]
I kown the reason，it's because of ace version;
https://ace.c9.io/build/src/ace.js  work!
https://ajaxorg.github.io/ace-builds/src-noconflict/ace.js work!
https://pagecdn.io/lib/ace/1.4.5/ace.js all not work! (I download from here)

**Comment by adyuebanwan** [comment]
<script src="assets/drag/js/lib/ace-1.4.3/ace.js"></script>
    <script src="assets/drag/js/lib/ace-1.4.3/ext-beautify.js"></script>
    <script src="assets/drag/js/lib/ace-1.4.3/ext-elastic_tabstops_lite.js"></script>
    <script src="assets/drag/js/lib/ace-1.4.3/ext-emmet.js"></script>
    <script src="assets/drag/js/lib/ace-1.4.3/ext-error_marker.js"></script>
    <script src="assets/drag/js/lib/ace-1.4.3/ext-keybinding_menu.js"></script>
    <script src="assets/drag/js/lib/ace-1.4.3/ext-modelist.js"></script>
    <script src="assets/drag/js/lib/ace-1.4.3/ext-static_highlight.js"></script>
    <script src="assets/drag/js/lib/ace-1.4.3/ext-searchbox.js"></script>
    <script src="assets/drag/js/lib/ace-1.4.3/ext-language_tools.js"></script>
    <script src="assets/drag/js/lib/ace-1.4.3/mode-html.js"></script>
    <script src="assets/drag/js/lib/ace-1.4.3/worker-html.js"></script>
    <script src="assets/drag/js/lib/ace-1.4.3/theme-monokai.js"></script>




EDITOR = ace.edit("magicalcoderCodeEdit");
           beautify = ace.require("ace/ext/beautify");
           EDITOR.setTheme("ace/theme/monokai");
           /*这一行导致tab键失效 */
           EDITOR.getSession().setMode("ace/mode/html");
 
           EDITOR.setOptions({
               enableBasicAutocompletion: true,
               enableSnippets: true,
               enableLiveAutocompletion: true//实时自动完成代码
           });
 
           EDITOR.getSession().selection.on("changeCursor", function(e) {//记住历史选择
               if(OPEN_CHANGE_CURSOR_EVENT){
                   var cursor = EDITOR.selection.getCursor()
                   row = cursor.row;
                   column = cursor.column;
               }

           });

**Comment by nightwing** [comment]
Could you try to reload the page with cache disabled, because the version from pagecdn works here.

Also does https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.5/ace.js work?

**Comment by adyuebanwan** [comment]
May be it's not ace.js problem
if ace.js works with another plugins  ,the Tab key will not work;


my Js:
          EDITOR = ace.edit("magicalcoderCodeEdit");
           beautify = ace.require("ace/ext/beautify");
           EDITOR.setTheme("ace/theme/monokai");
           /*这一行导致tab键失效*/
           EDITOR.getSession().setMode("ace/mode/html");
           // EDITOR.getSession().setMode("ace/mode/javascript");
           EDITOR.setOptions({
               enableBasicAutocompletion: true,
               enableSnippets: true,
               enableLiveAutocompletion: true//实时自动完成代码
           });

html:  work:
<script src="assets/drag/js/lib/ace-1.4.5/ace.js"></script>

html: not work:
    <script src="assets/drag/js/lib/ace-1.4.5/ace.js"></script>
    <script src="assets/drag/js/lib/ace-1.4.5/ext-beautify.js"></script>
    <script src="assets/drag/js/lib/ace-1.4.5/ext-elastic_tabstops_lite.js"></script>
    <script src="assets/drag/js/lib/ace-1.4.5/ext-emmet.js"></script>
    <script src="assets/drag/js/lib/ace-1.4.5/ext-error_marker.js"></script>
    <script src="assets/drag/js/lib/ace-1.4.5/ext-keybinding_menu.js"></script>
    <script src="assets/drag/js/lib/ace-1.4.5/ext-modelist.js"></script>
    <script src="assets/drag/js/lib/ace-1.4.5/ext-static_highlight.js"></script>
    <script src="assets/drag/js/lib/ace-1.4.5/ext-searchbox.js"></script>
    <script src="assets/drag/js/lib/ace-1.4.5/ext-language_tools.js"></script>
    <script src="assets/drag/js/lib/ace-1.4.5/mode-html.js"></script>
    <script src="assets/drag/js/lib/ace-1.4.5/worker-html.js"></script>
    <script src="assets/drag/js/lib/ace-1.4.5/theme-monokai.js"></script>

**Comment by nightwing** [comment]
that code works on https://jsbin.com/mecizazuxe/edit?html,output, maybe it is happening because of interaction with some other code?

**Comment by adyuebanwan** [comment]
Hi, I know the reason now 
I delete this line ,the Tab key works now!

**Comment by adyuebanwan** [comment]
Thanks for your help,may be it's "ext-emmet"'s problem
