### ISSUE TITLE
Cursor's location in editor is off

### ISSUE THREAD

**Issue by thigg** [ajaxorg/ace#4018]
Coming from  [couchdb-fauxton/1201](https://github.com/apache/couchdb-fauxton/issues/1201).

When editing documents in the editor, the cursor is off.
## Expected Behavior

The cursor should be at the same place where text is inserted.

## Current Behavior

The cursor is to the right of where text is inserted. In this image, I just typed "newText".

Couchdb's Fauxton:
![I just typed newText](https://user-images.githubusercontent.com/7593137/60532131-e2aa1600-9cfc-11e9-8588-06567e946625.png)

On https://ace.c9.io/:
![image](https://user-images.githubusercontent.com/7593137/61115707-52559900-a493-11e9-8261-c67e816442b6.png)

System:
```
$ uname -a
Linux` hostname 5.2.0-arch2-1-ARCH #1 SMP PREEMPT Mon Jul 8 18:18:54 UTC 2019 x86_64 GNU/Linux
$  firefox --version
Mozilla Firefox 68.0
```

And i get the warning in the console on  https://ace.c9.io/: 
`Will-change memory consumption is too high. Budget limit is the document surface area multiplied by 3 (929280 px). Occurrences of will-change over the budget will be ignored.`

**Comment by nightwing** [comment]
Looks like the monospace font is either missing or misconfigured on your computer. 
try searching for `monospace` in firefox options, and change the monospace font.

**Comment by thigg** [comment]
Fixed it, by fiddeling with font-config. I guess there's nothing to do in ace then. Seems stupid to work around the case, that a user messed with its fonts.
