### ISSUE TITLE
Add document sidebar

### ISSUE THREAD

**Issue by ReDiGermany** [ajaxorg/ace#4019]
Is there a way to add a document overview sidebar such as sublime and vs code uses?
Didn't find it on the docs or the examples :/

![image](https://user-images.githubusercontent.com/10668572/61272588-c94aa480-a7a7-11e9-9337-b7bc4be272bf.png)

**Comment by nightwing** [comment]
Currently minimap is not supported, but it is high on our priority list of feature requests.

**Comment by chudongsong** [comment]
> Currently minimap is not supported, but it is high on our priority list of feature requests.

Hello, I don’t know if minimap is under development plan now
