### ISSUE TITLE
Android Delete

### ISSUE THREAD

**Issue by Go2sites** [ajaxorg/ace#4020]
On Android if you delete with an empty space to the right side of the cursor it copies the entire line and drops it below. I am new to ace so not sure if i am missing something or this is a bug. Any ideas? i have had a good google search but found nothing.

**Comment by nightwing** [comment]
Which phone and what keyboard are you using?

**Comment by Go2sites** [comment]
Google Pixel 2, Daydream keyboard

**Comment by Go2sites** [comment]
No Google GBoard

**Comment by nightwing** [comment]
does this happen on ace.c9.io? i can't reproduce it there with chrome+gboard on samsung galaxy note

**Comment by Go2sites** [comment]
Yeah it does

**Comment by Go2sites** [comment]
just tested on a Huawei and it also does it on their

**Comment by Go2sites** [comment]
The Huawei is also using Gboard

**Comment by Go2sites** [comment]
Here is a vidoe to show what its doing:
https://drive.google.com/file/d/1-SFnDqUQojEirIhPCNHdn0T2TDEE53OW/view?usp=sharing

**Comment by nightwing** [comment]
Thanks, the video was helpful, could you test if the issue is fixed on https://raw.githack.com/ajaxorg/ace/master/kitchen-sink.html?

**Comment by Go2sites** [comment]
Hi yeah well done i can confirm that has fixed the issue.

**Comment by Go2sites** [comment]
When will the fixed update be available?
