### ISSUE TITLE
UndoManager: Redo available after setValue

### ISSUE THREAD

**Issue by AlexHolly** [ajaxorg/ace#4024]
On Master the editors behavior seems broken.
https://github.com/ajaxorg/ace/commit/b808ac14ec6d6afa74b36ff5c03452a2832b32a4

Test expected result 'c' but returns 'cb'
```
editor.session.doc.setValue(`a`);
editor.session.doc.setValue(`b`);
editor.session.getUndoManager().undo();
editor.session.doc.setValue(`c`);
editor.session.getUndoManager().redo();
```
It works in this version
(https://cdnjs.cloudflare.com/ajax/libs/ace/1.2.3/ace.js)
https://codepen.io/alexholly/pen/qeOBMa?editors=1010

EDIT: The behavior changed between version 1.2.9 and 1.3.0

**Comment by nightwing** [comment]
This was an intentional change, to allow more flexibility, but i don't remember using this, so maybe we should disable it.

**Comment by AlexHolly** [comment]
Do you prefer to make it optional?
