### ISSUE TITLE
Question: How is 'ace_print-margin' calculated?

### ISSUE THREAD

**Issue by prettydiff** [ajaxorg/ace#4026]
`ace_print-margin` is the class name of the vertical line that appears as a guide in the editor.  It is defined by a CSS style of `left: 676px` where the number is reflective of a character distance in the editor.  The value is set with `editor.setPrintMarginColumn(value)` where value is a number of characters or columns.

What is the calculation that transforms the `value` input into the css `left` result?  I am trying to add an interactive slider to my Ace instances around this, but my interaction does not scale correctly.

**Comment by nightwing** [comment]
It multiplies by characterWidth and adds padding

https://github.com/ajaxorg/ace/blob/b808ac14ec6d6afa74b36ff5c03452a2832b32a4/lib/ace/virtual_renderer.js#L595
