### ISSUE TITLE
Editor sometimes overwrites text on next line when copying and pasting

### ISSUE THREAD

**Issue by gpowerone** [ajaxorg/ace#4027]
ACE Editor v1.4.5 (from the changelog.txt file)

The bug is not easy to reproduce, but if you copy and paste enough you will get it eventually.

Screenshot attached
![acebug](https://user-images.githubusercontent.com/10482124/61798357-2d4c1900-adf7-11e9-8c27-e5bd2e6f7949.png)

**Comment by nightwing** [comment]
Could you tell a bit more what do you do to get this issue, e.g. are you copying and pasting the whole line/several lines/ or a part?

**Comment by gpowerone** [comment]
The issue happens when you copy at least 2 lines of text (doesn't matter where the start and end is) and then paste somewhere in the middle of a block of text. It doesn't happen right away, you need to copy and paste around for a couple of minutes and then it happens. In the example in the screenshot I started copying and pasting the long string of random characters ("testafdkajfa") and then went to copying and pasting "aaaaaa" and then back to the random characters ("testadkfal;ja") and then I triggered it.

Sorry I cannot give you more info, that's the best I've got.
