### ISSUE TITLE
Feature request: Mobile version of ACE

### ISSUE THREAD

**Issue by ennoweichert** [ajaxorg/ace#403]
Hi,
I'd like to see ACE working on my Android device - the Asus Transformer. That device got a keyboard and I want to put it to good use ;-)
However there are several severe usability issues that make is impossible to work with ACE on that device. Scrolling seems to be one of them and navigating with the arrow keys another one.
I'd like to see this happen to the WEB version of ACE because I don't care so much about it stand-alone but embedded into apps like Cloud9 or Github.

Thanks a lot :)
-- Enno
@gissues:{"order":51.55279503105612,"status":"backlog"}

**Comment by AStoker** [comment]
For scrolling, I think I'm on to something with getting some touch support implemented. I have it working on the iOS simulator. Check out the fork (https://github.com/AStoker/ace), you currently need to build it to compile (as that is the source code), but if you follow the build instructions in the realm, it's cake. I would love some help with any improvements, as it doesn't seem that touch support is a high priority right now (but that's the benefit of open source, we can fix it ourselves). Made the pull request https://github.com/ajaxorg/ace/pull/2555
