### ISSUE TITLE
Ace Editor SyncTex Support

### ISSUE THREAD

**Issue by yadurvt** [ajaxorg/ace#4031]
Any support documents for implementing synctex with ace editor.

**Comment by yadurvt** [comment]
Any support documents for implementing synctex with ace editor.

**Comment by nightwing** [comment]
if you get row and column from synTex, you can use the following to scroll the editor
```js
editor.selection.moveTo(row, column)
editor.scrollToLine(row, true, true);
```
and you can use `editor.getCursorPosition()` to get row number to  pass to syncTex

**Comment by yadurvt** [comment]
> if you get row and column from synTex, you can use the following to scroll the editor
> 
> ```js
> editor.selection.moveTo(row, column)
> editor.scrollToLine(row, true, true);
> ```
> 
> and you can use `editor.getCursorPosition()` to get row number to pass to syncTex

**Comment by yadurvt** [comment]
Thanks!!! For forward search i used synctex view and for backward search used synctex edit. Its worked.
