### ISSUE TITLE
[Chrome Android] Suggestion: Provide an option to replace TextInput's inner element with <input>

### ISSUE THREAD

**Issue by eyedean** [ajaxorg/ace#4032]
Chromium has [this bug](https://bugs.chromium.org/p/chromium/issues/detail?id=901839) that shows suggested words for regular text on Android phones.  

Those suggested words are completely useless in certain modes like coding in Javascript. And until Chromium fixes it, I was thinking maybe an option can be put in Ace Editor.

That option, as the only workaround I've found, is to replace the hidden <textarea> element with `<input type="password" autocomplete="new-password">`.  This way numbers pop up, instead of suggested words, which are way more beneficial for the user when coding on their phone.

The drawbacks are:
• Capturing <enter> key would be challenging.
• Chrome, sometimes, pops a prompt to save this new password!  So that needs to be disabled.

Any suggestion?

Thanks.

PS. It impacts at least 40% of users on phone.

**Comment by nightwing** [comment]
I've tried to do this in https://github.com/ajaxorg/ace/compare/input, but this would make already complicated code even more complicated, and would most likely cause issues with many mobile keyboards, which do not send keyCodes. Because of this i am very reluctant to apply this patch to master, but maybe you can manually apply this patch to the version you use, and let us know if it works well or if you get many complaints from mobile users.

**Comment by eyedean** [comment]
This is wonderful @nightwing and I am very impressed by the level of care and support you have shown to my request!  Thank you. : )

I'll give it a shot and will let you know how it works.  I'll also open a PR to your branch if further changes were needed.  Once I confirmed it works on major devices we can add it as a setup/config-option (with the default being `<textarea>` for backward compatibility and mitigating the risk) because I totally agree with you that it's such a fundamental change and definitely there might be some browsers not liking it!

Thanks again. <3

**Comment by eyedean** [comment]
## Update:

I just found that with the newest update of Chrome, it is adding a new bar showing a key sign and offering password management, if the input field has `type="password"`.  See the screenshot below. (forget about the gap above the numbers and below the new bar -- it was hard to take screenshot of keyboard in action!)  Since that was the only option that would disable the suggestion row, we are almost blocked.

Also for future reference, I tested the changes that @nightwing had on `input` branch.  It definitely needs some work on Chrome+Android (Google Pixel 3XL) since the cursor moves to the beginning of the line after every key press.  Also on iPhone X (Chrome browser) similar behavior happens.

All said, I think I have to wait for the bug on Chromimum to get fixed.  Thanks again for your quick and valuable turnaround @nightwing! : )

Cheers,
--Aideen.

----

![Screenshot_20190730-225811](https://user-images.githubusercontent.com/5694695/62187401-19844380-b31e-11e9-91c3-37eec0d70847.png)
