### ISSUE TITLE
Ctrl+Meta shortcut (?) un-indents line

### ISSUE THREAD

**Issue by larsgw** [ajaxorg/ace#4033]
I noticed that by just pressing <kbd>Ctrl</kbd>+<kbd>Meta</kbd>, the editor un-indents the current line or all selected lines one level. This is a bit annoying, as I use the <kbd>Ctrl</kbd>+<kbd>Meta</kbd>+arrow keys shortcut to move between virtual desktops, and the editor still un-indents code, right as I cannot see the window anymore. This is especially annoying on Overleaf with code samples in large amounts of text, but I see the same behavior in the demo. Is this intended behavior?

For completeness: <kbd>Ctrl</kbd> has keycode 17 and <kbd>Meta</kbd> has keycode 91 on my end.

**Comment by nightwing** [comment]
This is not the indented behavior, on which browser and OS do you see this? Could you check what the https://dvcs.w3.org/hg/d4e/raw-file/tip/key-event-test.html shows when pressing ctrl-meta

**Comment by larsgw** [comment]
I'm running Google Chrome 75.0.3770.100 on Debian Linux. The table shows this, I'm not sure what the bracket in `91 '['` means but that seems like a key that could trigger a block un-indent.

<table id="output"><thead><tr><td align="center" class="keycell empty"></td><td align="center" colspan="3" class="keycell legacy legacy_header">Legacy</td><td align="center" colspan="4" class="keycell modifiers modifiers_header">Modifiers</td><td align="center" colspan="3" class="keycell olddom3 olddom3_header" style="display: none;">Old DOM3</td><td align="center" colspan="5" class="keycell dom3 dom3_header">DOM3</td><td align="center" colspan="1" class="keycell uievents uievents_header">UI Events</td><td align="center" class="keycell inputbox empty"></td></tr><tr><td align="center" class="keycell etype etype_header">Event type</td><td align="center" class="keycell legacy legacy_header">charCode</td><td align="center" class="keycell legacy legacy_header">keyCode</td><td align="center" class="keycell legacy legacy_header">which</td><td align="center" class="keycell modifiers modifiers_header">shift</td><td align="center" class="keycell modifiers modifiers_header">ctrl</td><td align="center" class="keycell modifiers modifiers_header">alt</td><td align="center" class="keycell modifiers modifiers_header">meta</td><td align="center" class="keycell olddom3 olddom3_header" style="display: none;">keyIdentifier</td><td align="center" class="keycell olddom3 olddom3_header" style="display: none;">keyLocation</td><td align="center" class="keycell olddom3 olddom3_header" style="display: none;">char</td><td align="center" class="keycell dom3 dom3_header">key</td><td align="center" class="keycell dom3 dom3_header">code</td><td align="center" class="keycell dom3 dom3_header">location</td><td align="center" class="keycell dom3 dom3_header">repeat</td><td align="center" class="keycell dom3 dom3_header">data</td><td align="center" class="keycell uievents uievents_header">locale</td><td align="center" class="keycell inputbox inputbox_header">Input field</td></tr><tr><td align="center" class="keycell etype">keyup</td><td align="center" class="keycell legacy">0</td><td align="center" class="keycell legacy">17</td><td align="center" class="keycell legacy">17</td><td align="center" class="keycell modifiers modOff">✗</td><td align="center" class="keycell modifiers modOff">✗</td><td align="center" class="keycell modifiers modOff">✗</td><td align="center" class="keycell modifiers modOff">✗</td><td class="undef keycell olddom3" align="center" style="display: none;">-</td><td class="undef keycell olddom3" align="center" style="display: none;">-</td><td class="undef keycell olddom3" align="center" style="display: none;">-</td><td align="center" class="keycell dom3">'Control'</td><td align="center" class="keycell dom3">ControlLeft</td><td align="center" class="keycell dom3">LEFT</td><td align="center" class="keycell dom3">false</td><td class="undef keycell dom3" align="center">-</td><td class="undef keycell uievents" align="center">-</td><td align="left" class="keycell inputbox">''</td></tr><tr><td align="center" class="keycell etype">keyup</td><td align="center" class="keycell legacy">0</td><td align="center" class="keycell legacy">91 '['</td><td align="center" class="keycell legacy">91 '['</td><td align="center" class="keycell modifiers modOff">✗</td><td align="center" class="keycell modifiers modOn">✓</td><td align="center" class="keycell modifiers modOff">✗</td><td align="center" class="keycell modifiers modOn">✓</td><td class="undef keycell olddom3" align="center" style="display: none;">-</td><td class="undef keycell olddom3" align="center" style="display: none;">-</td><td class="undef keycell olddom3" align="center" style="display: none;">-</td><td align="center" class="keycell dom3">'Meta'</td><td align="center" class="keycell dom3">MetaLeft</td><td align="center" class="keycell dom3">LEFT</td><td align="center" class="keycell dom3">false</td><td class="undef keycell dom3" align="center">-</td><td class="undef keycell uievents" align="center">-</td><td align="left" class="keycell inputbox">''</td></tr><tr><td align="center" class="keycell etype">keydown</td><td align="center" class="keycell legacy">0</td><td align="center" class="keycell legacy">91 '['</td><td align="center" class="keycell legacy">91 '['</td><td align="center" class="keycell modifiers modOff">✗</td><td align="center" class="keycell modifiers modOn">✓</td><td align="center" class="keycell modifiers modOff">✗</td><td align="center" class="keycell modifiers modOff">✗</td><td class="undef keycell olddom3" align="center" style="display: none;">-</td><td class="undef keycell olddom3" align="center" style="display: none;">-</td><td class="undef keycell olddom3" align="center" style="display: none;">-</td><td align="center" class="keycell dom3">'Meta'</td><td align="center" class="keycell dom3">MetaLeft</td><td align="center" class="keycell dom3">LEFT</td><td align="center" class="keycell dom3">false</td><td class="undef keycell dom3" align="center">-</td><td class="undef keycell uievents" align="center">-</td><td align="left" class="keycell inputbox">''</td></tr><tr><td align="center" class="keycell etype">keydown</td><td align="center" class="keycell legacy">0</td><td align="center" class="keycell legacy">17</td><td align="center" class="keycell legacy">17</td><td align="center" class="keycell modifiers modOff">✗</td><td align="center" class="keycell modifiers modOn">✓</td><td align="center" class="keycell modifiers modOff">✗</td><td align="center" class="keycell modifiers modOff">✗</td><td class="undef keycell olddom3" align="center" style="display: none;">-</td><td class="undef keycell olddom3" align="center" style="display: none;">-</td><td class="undef keycell olddom3" align="center" style="display: none;">-</td><td align="center" class="keycell dom3">'Control'</td><td align="center" class="keycell dom3">ControlLeft</td><td align="center" class="keycell dom3">LEFT</td><td align="center" class="keycell dom3">false</td><td class="undef keycell dom3" align="center">-</td><td class="undef keycell uievents" align="center">-</td><td align="left" class="keycell inputbox">''</td></tr></thead></table>

**Comment by larsgw** [comment]
Okay, the `'['` means that `key >= 32 && key < 127` and `String.fromCharCode(key) === '['`.

**Comment by nightwing** [comment]
Thanks for the help, the issue is caused by broken getModifierState("Os") on chrome on linux, i'll add a workaround shortly.

**Comment by larsgw** [comment]
Thank you!
