### ISSUE TITLE
Undo/Redo causes multiple inserts

### ISSUE THREAD

**Issue by demikhovr** [ajaxorg/ace#4039]
Hi!
Noticed a bug with undo/redo and selected lines.

To reproduce:

1. Go to the page https://ace.c9.io/#nav=embedding
2. Insert at least 2 lines of code
3. Select lines
4. Click outside the editor
5. Press Cmd+Z or Shift+Cmd+Z several times

As a result the last line of code inserts into the editor n-times.

Chrome 76.0.3809.87
macOs 10.14.5

Is it related to this issue [https://github.com/ajaxorg/ace/issues/3472](https://github.com/ajaxorg/ace/issues/3472) or not?

**Comment by nightwing** [comment]
Hi, this is indeed related,
luckily there is a new browser api https://developer.mozilla.org/en-US/docs/Web/API/InputEvent/inputType that allows to handle this.
