### ISSUE TITLE
Scroll using mobile touch feels jerky

### ISSUE THREAD

**Issue by pulkit604** [ajaxorg/ace#4040]
The scroll on desktop version is smooth but on a touch mobile device becomes jerky.

**Comment by nightwing** [comment]
With which version of ace, and on which device do you see this?

**Comment by pulkit604** [comment]
Thanks for your reply.
Ace version is 1.2.9 
Device ->                Nextbit Robin, 
Android ->              7.1.1
Google Chrome -> 75.0.3770.101
Also, I've tried in some other devices too and got same issue.

**Comment by nightwing** [comment]
try ace v1.4.5 https://ace.c9.io/, the issue should be fixed there.

**Comment by pulkit604** [comment]
Thanks a lot for your help @nightwing. It works fine.
