### ISSUE TITLE
On value changed event

### ISSUE THREAD

**Issue by aelassas** [ajaxorg/ace#4049]
Is there a way to fire an event when the value of the editor changes?

**Comment by nightwing** [comment]
there is a "change" event which is fired immediately after each change, and can be fired multiple time during one operation, and there is "input"  event which is fired after a timeout after change event, the first is useful for tracking changes and the second is for the code that does not need to handle delta objects, e.g. updating ui https://github.com/ajaxorg/ace/blob/master/demo/toolbar.html#L42.
