### ISSUE TITLE
ace.d.ts doesn't have a definition for "onCommandKey" of Editor

### ISSUE THREAD

**Issue by eyedean** [ajaxorg/ace#4050]
It seems like the definition file for Typescript doesn't have `onCommandKey` neither on the `Editor` nor on the `keyBinding`.

My current workaround is:
```ts
import * as AceBuild from "ace-builds";

export interface ExtendedAceEditor extends AceBuild.Ace.Editor {
	onCommandKey(e: Event | null, hashId: number, keyCode: number): void;
}
```

Can we please update the definition file to have this function as well as some other public ones that are available but not exposed in `.d.ts` file?

Thanks,
--Aideen.

PS. I am working on building a custom touch keyboard for coding in mobile, kinda like option 2 of https://github.com/ajaxorg/ace/issues/925.  I am trying to integrate that with Ace Editor and there are some challenges I am running into here and there.  Is there a Slack or Gitter or Discord channel/forum that I can communicate with experts of Ace? :)

**Comment by mkslanc** [comment]
Fixed by #4450
