### ISSUE TITLE
Search is registering as a change in the code editor

### ISSUE THREAD

**Issue by ayumihamsaki** [ajaxorg/ace#4051]
Hi,

I'm opening this issue in two places to better understand the issue. Which can be found here as well: https://github.com/octobercms/october/issues/4532

The issue I'm seeing is when a user opens the search box and does a search it's registering as a change in the code editor.

Is there a way of setting the ace editor to do a search but not registering it as a code change in the editor.

Thanks.

**Comment by nightwing** [comment]
Hi, this doesn't look like an issue related to code in ace, most likely octobercms uses keypress to detect change instead of using change event emitted by ace.

**Comment by ayumihamsaki** [comment]
Thank you, that makes sense.
