### ISSUE TITLE
editor.onCommandKey(null, -1, 13) adds "return" instead of "\n"

### ISSUE THREAD

**Issue by eyedean** [ajaxorg/ace#4052]
I am working on a mouse/touch-driven virtual keyboard that plugs to the Ace Editor.  When I tap on my "Return" <button>, I want to simulate the "Return"/"Enter" key press.  I found that one way would be calling `editor.onCommandKey(null, -1, 13)`.

It works fine on executing the commands that are bound to "return key" (e.g. emmet's autocomplete) but when it's **not** handled by any of the commandHandlers, it just addes the string "`return`" instead of "\n" character to the textinput.

Apparently, it's happening in [these lines](https://github.com/ajaxorg/ace/blob/master/lib/ace/keyboard/keybinding.js#L129-L132) of `keybinding.js > $callKeyboardHandlers` with `keyString` being `"return"`.  The root of the problem is `keyUtil.keyCodeToString(keyCode)` for `keyCode = 13` returns the string "`return`" instead "\n" [which is used when `onCommandKey(...)` is called](https://github.com/ajaxorg/ace/blob/master/lib/ace/keyboard/keybinding.js#L140-L143).

---

So my suggested solution are:

### 1. Modifying `keyUtil.keyCodeToString()`
... to return "\n" for `13`.  The risk is, since `keyUtil` is a shared util, it might have side effects.

### 2. Lettings `onCommandKey()` take a fourth optional parameter of `keyString`
... which should happen both on `keybinding.js` and `editor.js`.  If this optional param is present, that's going to be taken instead of `keyUtil.keyCodeToString`.  With this I can override the problem with `keyCodeToString()` without any side effect.

### 3. return the `success` result of internal `$callKeyboardHandlers` to the outside caller
I believe it should happen anyway.  the `onCommandKey` functions (on both keybinding.js and editor.js) are not returning anything right now and they can easily pass up the result of the handlers.

While this is not ideal, at least it allows me to put 
```js
   if (!editor.onCommandKey(null, -1, 13)) {
      editor.insert("\n");
   }
```

If you let me know which one you prefer, I am down to create a PR for that. :)

Thanks!

**Comment by eyedean** [comment]
PS. Just in case it takes longer to fix and release, my current workaround for this is defining a custom command for insertion!

```js
    this.editor.commands.bindKey("Return", (editor) => editor.insert("\n"));
```

I need to this manually for `\t`, `\n` and other custom keys.

**Comment by nightwing** [comment]
for the 3rd method of passing up the result we had a similar requirement some time ago, so https://github.com/ajaxorg/ace/pull/4053 added it.

I am not sure what solution is the best:
the first solution could work if it was to convert to  "\n" only if hashId was -1.
a variation of second would be to allow passing string as the third parameter
and another solution would be to add a new method to the editor sendKey which could accept  string like "Ctrl-Alt-X" "Return" or "\n"

**Comment by eyedean** [comment]
Thanks for merging https://github.com/ajaxorg/ace/pull/4053!  I think that should do it for me.
