### ISSUE TITLE
Ability to disable Ace editor box

### ISSUE THREAD

**Issue by dimroc** [ajaxorg/ace#406]
It would be great if we could disabled the Ace editor box with the disabled attribute, similar to what's available with a textarea:

``` html
<textarea rows="3" cols="25" disabled="disabled">
This textarea is grayed out and disabled for interaction.
</textarea>
```

**Comment by xyzdata** [comment]
# Q: How to disable the `Ace` editor edit?

# A: `editor.setReadOnly(true);`

https://stackoverflow.com/questions/24757506/how-to-disable-in-ace-editor-the-selection

**Comment by xgqfrms** [comment]
# ContentEditable

> not work for this situation?

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/contenteditable

**Comment by gxjcoo** [comment]
i can't wirte but can delete text after use setReadOnly(true).
