### ISSUE TITLE
Uncaught DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'http://localhost:3000/servicemanager/api/center/319/worker-php.js' failed to load.

### ISSUE THREAD

**Issue by ywcr** [ajaxorg/ace#4060]
Hello,  the following is the translation software used.

I am using npm install ace-builds 。

Encountered these problems：

Uncaught DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'http://localhost:3000/servicemanager/api/center/319/worker-php.js' failed to load.

and

Uncaught DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'http://10.39.25.3/servicemanager/api/center/319/worker-json.js' failed to load.

Because it is used in the react project，My method of use is：

` 
import modeJava from 'ace-builds/src-min-noconflict/mode-java.js' // 默认设置的语言模式
import modeGolang from 'ace-builds/src-min-noconflict/mode-golang.js' // 默认设置的语言模式
import modePython from 'ace-builds/src-min-noconflict/mode-python.js' // 默认设置的语言模式
import modePHP from 'ace-builds/src-min-noconflict/mode-php.js' // 默认设置的语言模式
import modeJson from 'ace-builds/src-min-noconflict/mode-json.js' // 默认设置的语言模式
import themeMonokai from "ace-builds/src-min-noconflict/theme-monokai.js";
import themeEclipse from "ace-builds/src-min-noconflict/theme-eclipse.js";

ace.config.setModuleUrl("ace/mode/php", modePHP)
ace.config.setModuleUrl("ace/mode/json", modeJson)
ace.config.setModuleUrl("ace/theme/eclipse", themeEclipse)
ace.config.setModuleUrl("ace/theme/monokai", themeMonokai)
ace.config.setModuleUrl("ace/mode/java", modeJava)
ace.config.setModuleUrl("ace/mode/golang", modeGolang)
ace.config.setModuleUrl("ace/mode/python", modePython)
 `

This use led to the above problem。

The reason for this use is that the following usage will generate many dependent files when packaged.

'ace-builds/webpack-resolver' // that's it

`
import ace from 'ace-builds'

import 'ace-builds/webpack-resolver' // 在 webpack 环境中使用必须要导入
import 'ace-builds/src-min-noconflict/theme-monokai.js' // 默认设置的主题
import 'ace-builds/src-min-noconflict/mode-java.js' // 默认设置的语言模式
import 'ace-builds/src-min-noconflict/mode-golang.js' // 默认设置的语言模式
import 'ace-builds/src-min-noconflict/mode-python.js' // 默认设置的语言模式
import 'ace-builds/src-min-noconflict/mode-php.js' // 默认设置的语言模式
import 'ace-builds/src-min-noconflict/mode-json.js' // 默认设置的语言模式
`

Perhaps the above description is confusing, please forgive me.

**Comment by nightwing** [comment]
the large number of files is needed to allow optional loading of modes, themes, workers and extensions

while most of these can be included in the main bundle, workers still need to be served as separate files, try adding:
```js
ace.config.setModuleUrl('ace/mode/php_worker', require('file-loader!./src-noconflict/worker-php.js'))
ace.config.setModuleUrl('ace/mode/php_json', require('file-loader!./src-noconflict/worker-json.js'))
```
similar to 
https://github.com/ajaxorg/ace-builds/blob/7489e42c81725cd58d969478ddf9b2e8fd6e8aef/webpack-resolver.js#L234

**Comment by Drumsin** [comment]
Experiencing issue

**Comment by dorji-tshering** [comment]
I am also having the same issue. 
Here is the import statements I have used:
`import ace from 'ace-builds/src-noconflict/ace';
import monokai from 'ace-builds/src-noconflict/theme-monokai';
import 'ace-builds/src-noconflict/mode-javascript';`

And here is how I am accessing: 
`editor = ace.edit('code-editor');
        editor.setTheme(monokai);
        editor.session.setMode("ace/mode/javascript");
        editor.setOptions({
            autoScrollEditorIntoView: true,
            copyWithEmptySelection: true,
        });`

**Comment by dorji-tshering** [comment]
For anyone that comes across this issue, adding `useWorker: false` to `editor.setOptions()` has resolved the issue. Also notice that I have imported the modules directly as shown above.
