### ISSUE TITLE
Mismatch of rendered cursor position and real cursor position

### ISSUE THREAD

**Issue by hubitor** [ajaxorg/ace#4063]
The cursor is not rendered at the right position. I've found similar issues, some of them are closed, some are still open:

[https://github.com/ajaxorg/ace/issues/3861](url)
[https://github.com/ajaxorg/ace/issues/3295](url)
[https://github.com/ajaxorg/ace/issues/3545](url)
[https://github.com/ajaxorg/ace/issues/3385](url)
[https://github.com/ajaxorg/ace/issues/3032](url)
[https://github.com/ajaxorg/ace/issues/2548](url)

I don't use Russian characters or long lines. I've just installed ACE and trying it out. The proposed solutions of monospace fonts didn't work for me. This is what I've tried already:

```
    <style type="text/css" media="screen">
      #editor {
        position: absolute;
        top: 0;
        right: 0;
        bottom: 0;
        left: 0;
      }

      /* .ace_editor,
            .ace_text-input,
            .ace_editor div {
              font-family: monospace !important;
              font: 12px/normal 'Menlo', 'Monaco', 'Ubuntu Mono', 'Consolas', 'source-code-pro', monospace;

            } */

      /* .ace_editor * { */
      /* Necessary to make sure Russian text is displayed properly */
      /* https://github.com/laurent22/joplin/issues/155 */
      /* font-family: monospace !important; */
      /* }  */

      .ace_editor div,
      .ace_editor span {
        font-size: 12px !important;
      }

      /* .ace_editor,
            .ace_text-input,
            .ace_editor div {
              font-family: monospace !important;
            } */

      .ace_editor,
      .ace_editor div {
        font-family: monospace;
      }
    </style>
```

**Comment by nightwing** [comment]
Did you manage to find a solution? If not could you paste a screenshot, that would help to better understand what is going wrong.

**Comment by hubitor** [comment]
> Did you manage to find a solution? 

No.

> If not could you paste a screenshot, that would help to better understand what is going wrong.

I thought of making a .gif but there are already videos with exactly the same issue in the links I mentioned before.
I'm also trying out CodeMirror and I don't have such issues so far.

**Comment by 394620295** [comment]
字体必须设置在#editor上，并且和子元素的字体一致。因为是根据#editor上的字体大小进行计算的

**Comment by nicolasbadia** [comment]
From version 1.4.0, the `importCssString` method last line was changed. `root.appendChild(style);` become `container.insertBefore(style, container.firstChild);`.
Because of this, the stylesheet is inserted before all the others, and, the font defined to `.ace_editor` is overridden by my app custom styles.
