### ISSUE TITLE
Highlight active line

### ISSUE THREAD

**Issue by pafitopc-rt** [ajaxorg/ace#4065]
Hi, when i try to highlight an active line in different color when the cursor is at different line, it doesn't work. 

Example:  I try to highlight the second line in red, it highlight the first line in first color(blue) every time.

How to fix it?
Thanks for help!

**Comment by nightwing** [comment]
Hi, unfortunately i didn't fully understand what are you trying to do from the description, could you show the code snippet you have tried to use.
