### ISSUE TITLE
When I click,why  the line of code will be highlighted in purple.  how can I cancle it

### ISSUE THREAD

**Issue by xiaolee55** [ajaxorg/ace#4067]

**Comment by nightwing** [comment]
try `editor.setOption("highlightActiveLine", false)`, if that doesn't help could you please show a screenshot, without it, it is hard to tell what is causing the purple highlight

**Comment by xiaolee55** [comment]
I solved it by setting`this.aceEditor.on("guttermousedown", function(e) {e.stop()},true); `
