### ISSUE TITLE
removing a linefeed breaks worker applyDelta

### ISSUE THREAD

**Issue by mikecargal** [ajaxorg/ace#4075]
I'm trying to implement a single line ace editor based on answers to this SO question: 
(https://stackoverflow.com/questions/32315244/single-line-ace-editor)

I'm finding that the editor is injecting a linefeed that I didn't put in the document (using either editor.setValue, or editor.session.setValue.  So I've tried a variation of some code in the first answer.  It appears a bit dated (my event didn't match the structure the example was coded against).

my code is:
```
        ed.getSession().on("change", e => {
          console.log(e);
          if (e.action == "insert" ) {
            console.log("cancel event");
            ed.find(String.fromCharCode(10));
            ed.replaceAll("");
            ed.selection.clearSelection();
          }
        });
```
When I issue this replaceAll, the worker applyDelta function (action == "remove") has a docLines array with a single line in it, but the delta.end.row == 1 (delta.end.column ==0) means that the following line in apply_delta.js attempts to take a substring of a non-existent line.  (endRow == 1, but docLines is a single item array)
```
   docLines.splice(
       row, endRow - row + 1,
       line.substring(0, startColumn) + docLines[endRow].substring(endColumn)
   );
```

**Comment by nightwing** [comment]
The first answer is wrong, changing editor value from onchange callback breaks the editor. 

Use the method in the second answer of that question https://stackoverflow.com/a/32316070/1743328
