### ISSUE TITLE
Dynamic syntax highlighting

### ISSUE THREAD

**Issue by jaa134** [ajaxorg/ace#4076]
Hi,

I'd like to add a list of custom keywords to a mode. Ive found this issue here (#3905), but I'm instead looking for a solution that is NOT syntax aware. That is to highlight all instances of the word (red) even if it is inside a string or a comment. It seems like the solution that @nightwing shared highlights the added keywords even when in a string, but keeps them the same color as the string. I'd like to use a different color. [Here's an example of what I'd like.](https://jsbin.com/cafonijigu/edit?output) Does the ace editor currently support this behavior?

Bonus: Can we supply additional keywords as a regex pattern?

**Comment by YellowAfterlife** [comment]
At the very least you could add a new rule (with a regex for your additional keywords) to front of each tokenizer state so that it matches before anything usually would.

**Comment by jaa134** [comment]
@YellowAfterlife Thanks for the response! I came up with something like this:
```
// initialize editor
this.editor = ace.edit(this.editorId);
var session = this.editor.session;
session.setMode(`ace/mode/${this.language || 'sh'}`);

// update the rule set to match my rules first
var rules = session.$mode.$highlightRules.getRules();
for (var stateName in rules) {
    if (Object.prototype.hasOwnProperty.call(rules, stateName)) {
        rules[stateName].unshift({
            token: 'my_token',
            regex: '\\${p:.+}|\\${p\\?:.+}'
        });
    }
}

// force recreation of tokenizer
session.$mode.$tokenizer = null;
session.bgTokenizer.setTokenizer(session.$mode.getTokenizer());
// force re-highlight whole document
session.bgTokenizer.start(0);
```

**This is so close to working!** However, it seems as if the last line doesn't do anything because the document isn't actually re-highlighted until the second load of the editor. I've been able to fix this by setting a temporary mode and then setting the mode again back to the intended mode. This seems to force the editor to re-highlight. Like this:
```
session.setMode('ace/mode/text');
session.setMode(`ace/mode/${this.language || 'sh'}`);
```
What am I missing? I don't really want to rely of setting the mode 3 times.

**Comment by nightwing** [comment]
Most likely this happens because setMode is async for modes that are not loaded yet, so the code updating the rules adds new rules to the text mode instead of the new mode., try using the callback to the `.setMode`

```js
session.setMode(`ace/mode/${this.language || 'sh'}`, function() {
    var rules = session.$mode.$highlightRules.getRules();
    for (var stateName in rules) {
        if (Object.prototype.hasOwnProperty.call(rules, stateName)) {
            rules[stateName].unshift({
                token: 'my_token',
                regex: 'FLIGHTINFO|\\${p:.+}|\\${p\\?:.+}'
            });
        }
    }
    // force recreation of tokenizer
    session.$mode.$tokenizer = null;
    session.bgTokenizer.setTokenizer(session.$mode.getTokenizer());
    // force re-highlight whole document
    session.bgTokenizer.start(0);
});
```

**Comment by jaa134** [comment]
@nightwing @YellowAfterlife I was able to verify this was the problem. To all others who have this problem, you can use my original solution and pass it as a callback to Session.setmode. Thank you both for your help! I'm going to close this now.

**Comment by Mehdi-YC** [comment]
Hello, 
i know this is old, but this is not working , i tried implementing it, i don't know if the API changed or what, but the keyword is still not highlighted and is displayed as Error by the linter (could be not related to this)

**Comment by nightwing** [comment]
@Mehdi-YC could you please show the code you are using? that would help to find the issue.

**Comment by Mehdi-YC** [comment]
After i re red the ticket it might not be the same problem, it might be ace-linter issue, the thing is i want to add some completions that are ignored by the linter like predefined globals
