### ISSUE TITLE
Ctrl+[ not working as ESC on iPadOS

### ISSUE THREAD

**Issue by gtritchie** [ajaxorg/ace#4077]
Safari in iPadOS (13.1) is much better behaved than previous versions, for example the arrow keys and most Ctrl+_n_ combinations are working just like a grown-up web browser.

However, `Ctrl+[` (in place of ESC, smart-keyboard doesn't have an ESC key) doesn't work in vim-mode for getting out of insert mode and such. Tried on kitchen sink, works with desktop browsers (Chrome and Safari), doesn't on iPadOS.

Looked at keyboard events using http://jsfiddle.net/dujpynb4/ and there are a subtle differences that might explain this problem. I haven't looked into the Ace code yet to confirm.

Reported last keycode from `down`, `press`, and `up` events:

Platform | Hold `Ctrl`    | Press and release `[` | Release `Ctrl`
-------- | ---------------| --------------------- | ----------------
Desktop  | 17, none, none | 219, 27, 219          | 219, 27, 17
iPadOS   | 17, none, none | 27,  27, 27           | 27,  27, 17

In the middle column, iPadOS is reporting as though a physical ESC key was pressed, but in the third column, it then reports that the Ctrl key was released. Perhaps this discrepancy is the cause of the misbehavior.

Switched to a bluetooth iPad keyboard with an ESC key. ESC works, `Ctrl+[` does not.

**Comment by nightwing** [comment]
When pressing ctrl-[ ipad sends the keyCode for escape but sets event.ctrlKey to true, https://github.com/ajaxorg/ace/pull/4083/commits/65b5becfb91a9c8fc9aff228a326832376f7e66c should help with this issue.
