### ISSUE TITLE
issue for Korean input (IME) , only in IE 11

### ISSUE THREAD

**Issue by Rem486** [ajaxorg/ace#4080]
Hi, first thank you for provide this awesome plugins! 

I had met with some difficulties,when i use [`Ace Kitchen Sink`](https://ace.c9.io/build/kitchen-sink.html) to input `Korean` in `IE 11`.There is no composition prompt.

- **in IE 11**
![json-editor-3](https://user-images.githubusercontent.com/22462424/65736372-59dd2380-e10d-11e9-91de-628687d610ad.gif)

- **in Chrome**
![json-editor-4](https://user-images.githubusercontent.com/22462424/65736392-66617c00-e10d-11e9-909f-e738297dae66.gif)

>Only in IE 11 have this problem,the other brower(chrome) is normal.

![1](https://user-images.githubusercontent.com/22462424/65736424-85f8a480-e10d-11e9-84cd-2653840b2849.png)

plz help me with this. Thanks a lot!

>Is it similar to this? https://github.com/ajaxorg/ace/issues/3622

**Comment by Rem486** [comment]
I found `ace_text-input` had different style when typing in IE 11 and Chrome.

```
<textarea class="ace_text-input" 
style="left: 228px; top: 112px; width: 1px; height: 0px; font-size: 1px; opacity: 0;" >
</textarea>
```

in IE the `width` and `height` of it  is always `1px 0px`
in Chrome it will be set to `13px 16px`

**Comment by nightwing** [comment]
Please check if this is fixed on https://raw.githack.com/ajaxorg/ace/keyboard/kitchen-sink.html. THis was caused by editor not handling correctly the way IE selects composition text.

**Comment by Rem486** [comment]
Great! It was fixed in https://raw.githack.com/ajaxorg/ace/keyboard/kitchen-sink.html. Thank you!

![json-editor-5](https://user-images.githubusercontent.com/22462424/65824401-000a6400-e29b-11e9-98df-39890a8de1e7.gif)
