### ISSUE TITLE
Adding unexpected end tag (source) to <picture> tags

### ISSUE THREAD

**Issue by Go2sites** [ajaxorg/ace#4084]
If you load html with picture tags it adds unexpected source tags, it shows you the error saying "unexpected end tag (source)", but ace has added the source tags. 

It does this when opening/loading the html, if you delete the unexpected source tags save, then reopen the source tags have been added again.

Example picture tag below, if you load html with this picture element it will add two unexpected end tags.

`
<picture>
    <source media="(min-width: 650px)" srcset="img_pink_flowers.jpg">
    <source media="(min-width: 465px)" srcset="img_white_flower.jpg">
    <img src="img_orange_flowers.jpg" alt="Flowers" style="width:auto;">
</picture>
`

**Comment by nightwing** [comment]
If you are setting initial content of the editor by adding the text to the html page, you need to escape the `<` and `&` characters in the text to prevent it from being interpreted as html by the browser

**Comment by Go2sites** [comment]
i am doing this the problem is Ace is adding source end tags? only to the picture elements. have you tested using picture tags like the one below? as you can see the source tag does not need source end tags but ace is adding them.

`
<picture> 
    <source media="(min-width: 650px)" srcset="img_pink_flowers.jpg"> 
    <source media="(min-width: 465px)" srcset="img_white_flower.jpg"> 
    <img src="img_orange_flowers.jpg" alt="Flowers" style="width:auto;"> 
</picture>
`

**Comment by nightwing** [comment]
Could you describe in more detail in which case ace is adding them, i cannot reproduce this by using 
```js
editor.setValue(`<picture> 
    <source media="(min-width: 650px)" srcset="img_pink_flowers.jpg">
    <source media="(min-width: 465px)" srcset="img_white_flower.jpg"> 
    <img src="img_orange_flowers.jpg" alt="Flowers" style="width:auto;">
</picture>`)
```
or 

```js
document.body.innerHTML = "<div id=editor style=height:100px>" 
    + ace.require("ace/lib/lang").escapeHTML`<picture> 
    <source media="(min-width: 650px)" srcset="img_pink_flowers.jpg">
    <source media="(min-width: 465px)" srcset="img_white_flower.jpg"> 
    <img src="img_orange_flowers.jpg" alt="Flowers" style="width:auto;">
</picture>`
   + "</div>"
ace.edit("editor", {mode: "ace/mode/html"})
```

**Comment by Go2sites** [comment]
Ok my bad! I am using Ace with htmlagilitypack and the bug is within htmlagilitypack NOT Ace so sorry for wasting any time.
