### ISSUE TITLE
How to enable different types of soft wrapping?

### ISSUE THREAD

**Issue by HansvdLaan** [ajaxorg/ace#4087]
First of all, thanks for this awesome library! 

I'm trying to activate different soft wrapping types in my editor, as shown in the kitchen sink. (ex: view, margin or 40 characters). However, I can not find in the documentation how to do this. 

Which method am I overlooking? Which method can be used to set the soft wrapping type?

**Comment by nightwing** [comment]
use `editor.setOption("wrap", 20) // or true or "printMargin"`
