### ISSUE TITLE
vim keybinding supports 'whichwrap'?

### ISSUE THREAD

**Issue by tigerk0430** [ajaxorg/ace#4088]
I want to add custom vim setting in overleaf vim keybinding like

`set whichwrap+=h,l,<,>,[,] ` to move to the next line at the end of the current line.

but no one seemed to ask about this setting. 

does it support? and how to configure it?

thanks in advance!

**Comment by nightwing** [comment]
This option is not supported, for now as indeed noone have asked about this. I have several questions on how this option should work:

Does this modify only behavior of selection, or also the behavior of things like `dl`, `y10l`?
 
Do you need  h, l, and arrows to be separately configurable, or turning the option on and off for all of  them at once would be enough.

Also how does the option change the behavior of [ and ], it doesn't seem to have any effect in vim.

**Comment by tigerk0430** [comment]
@nightwing 

actually, I copied this command from the web, I use only `set whichwrap+=h,l` because it's enough for me.

this command enables vim to move to the next line at the end of the current line when press 'l'. 
also move to the previous line at the beginning of current line when press 'h' .

as far as I know, It doesn't have to do with `dl' and `y10l` commands.


Thanks for informing me that this option is not supported yet  :-)
