### ISSUE TITLE
Support for UI specific additional properties on tokens?

### ISSUE THREAD

**Issue by jaa134** [ajaxorg/ace#4092]
I've recently run into a problem where I would like to show a tooltip on hover of a specific token.   It seems one way to do this would be to supply a title attribute to the domNode that is created to wrap the token (I believe on line ~400 of [text.js](https://github.com/ajaxorg/ace/blob/902d1a02864479cfa7c47f46972ff53fb56924fc/lib/ace/layer/text.js)) But, it seems like there isn't currently any support for this. Is there another way of doing this?

**Comment by nightwing** [comment]
It is possible to add a tooltip similar to https://github.com/ajaxorg/ace/blob/master/demo/kitchen-sink/token_tooltip.js#L40 (you can see it in action in kitchen-sink demo by enableing "Show token info" option). Adding title property would not work, because text nodes are behind another element.

**Comment by jaa134** [comment]
Thanks @nightwing. Exactly the start I needed to find a solution. For anyone else, I found this helpful as well. [Example Solution](https://github.com/devuxd/SeeCodeRun/wiki/Ace-code-editor)
