### ISSUE TITLE
show invisibles broken in kitchen sink demo

### ISSUE THREAD

**Issue by fiws** [ajaxorg/ace#4093]
Clicking "Show invisibles" in the [kitchen sink demo](https://ace.c9.io/build/kitchen-sink.html) looks like this for me:

![image](https://user-images.githubusercontent.com/3409958/66938763-160d7800-f042-11e9-80dd-87b021001c08.png)

All whitespace disappears

**Comment by nightwing** [comment]
On which browser and OS do you see this?

**Comment by fiws** [comment]
Chrome on Arch Linux. The rendered font seems to be 'source-code-pro'. It works if i remove that.
