### ISSUE TITLE
Strange Ctrl + Backspace Behavior

### ISSUE THREAD

**Issue by MarkQueppet** [ajaxorg/ace#4095]
In most standard text entry fields you can press ctrl + backspace to delete a whole word. This also will delete a space or punctuation mark when attached to a word.

This is perhaps one of the most useful general shortcuts that I know of for quickly deleting text, fixing typos, or reformatting sentences.

So for example take the sentence below:

`This, is a test sentence.`

In a _normal_ text box, you can

- Place your cursor at the end of the sentence
- Hold down control
- Press backspace **5** times and delete the whole sentence.

In the ace editor, the same sentence will take **11** presses of ctrl+backspace because it treats every space and symbol as its own "word".

I vote for this be changed to match most other standard text entry fields due to the enhanced efficiency.

**Comment by llinfeng** [comment]
For Vim-bindings, `<c-w>` in Insert mode is doing the same thing: it is treating whitespace as if it is a word. To delete `a word`, it takes a total of `1 + 2` key-presses.

**Comment by llinfeng** [comment]
I observe a proper `<c-w>` behavior on Overleaf, with no special mapping through any user script, **as long as I use a browser that does not use `<c-w>` to close a tab**. Browsers include:
* Internet Explorer
* Safari (only available on MacOS)
* Vivaldi ==> all shortcuts for Vivaldi is configurable, and deleting `<c-w>` as a shortcut leaves a fully functional `<c-w>`.
