### ISSUE TITLE
JSON: Pasting valid content shows "Syntax error" and doesnt process other changes

### ISSUE THREAD

**Issue by ngmgit** [ajaxorg/ace#4099]
I am using the following code to format the json and set the value for ace editor.
```
const textToJSON = JSON.parse(text);
const formattedJSONString = JSON.stringify(textToJSON, null, 2);
```

So every time I paste a valid JSON in the editor it adds a marker with error "Syntax error" on the very first line.
```
column: 705
row: 0
text: "Syntax error"
type: "error"
```
In order get rid of this error I  have to delete the first line as shown below.
```
{
   "test": 1
}
```
```
{"test":1
}
````

**Comment by ngmgit** [comment]
Update: Also the column value is the length of file contents always.

**Comment by nightwing** [comment]
On which page do you see this behavior? I couldn't reproduce the issue on https://ace.c9.io/build/kitchen-sink.html?doc=Json
