### ISSUE TITLE
syntax highlighting for Mix mode (json/xml) 

### ISSUE THREAD

**Issue by wck821829906** [ajaxorg/ace#4101]
Does Ace editor support mix language syntax highlighting， I have not found reference API document 。。。

**Comment by nightwing** [comment]
is `Mix` a language (i couldn't find anything about it on google) or are you asking  how to create a mode combining two other modes?

**Comment by wck821829906** [comment]
Not mix two language, just hope set different languages in one editor, ace can identify user input and show proper syntax highlighting.

**Comment by nightwing** [comment]
Ace does not have support for that. But for json/xml you can do

```js
var value = editor.getValue();
var mode = value[0] == "<" ? "ace/mode/xml" : "ace/mode/json";
editor.setMode(mode);
```

**Comment by wck821829906** [comment]
ok, get it, thanks
