### ISSUE TITLE
Documentation Out of Sync

### ISSUE THREAD

**Issue by DavidSichau** [ajaxorg/ace#4107]
First thanks for the great editor, however the documentation requires some love.

In my humble opinion there are several issues:

## 1. Documentation not up to date

The API Documentation of Ace on the Website does often not correspond to the implementation. The last change to the api docs is more than 2 years ago.

Often it is required to read the source code of ace to understand how the api works.

This makes it very cumbersome to work with the api.

A good example for a good documentation is e.g. https://microsoft.github.io/monaco-editor/api/index.html

## 2. Changelog not very helpful

It would be nice if the changelog in the future is more elaborate:
```
2019.10.17 Version 1.4.7
* add placeholder option
```
Does not really help. Where is placeholder option added? Which api has changed....

I know it is really cumbersome and hard to provide good and up to date documentation. However this would reduce the amount of created issues and would help new users to successful start with ace.

**Comment by oprobst-ethz** [comment]
The editor is great! Definitely looking forward to see a better documentation.

**Comment by poiuqwer78** [comment]
I strongly support this request. It's very difficult to upgrade ace and being able to profit from the improvements that have been introduced since earlier versions.

**Comment by nightwing** [comment]
There is a work in progress version of documentation using typedoc https://nightwing.github.io/ace-documentation-2/doc/modules/ace.html, we expect to release it with ace v2 soon.

Placeholder option can be used with `editor.setOption("placeholder", "some text")`.

**Comment by mkslanc** [comment]
Fixed by [Ace API reference generator](https://github.com/ajaxorg/ace-api-docs)    

[Link to API reference](https://ajaxorg.github.io/ace-api-docs/index.html)
