### ISSUE TITLE
vim: entering insert mode with 'a' can place cursor in middle of emojis

### ISSUE THREAD

**Issue by kevinushey** [ajaxorg/ace#4108]
To reproduce, in [kitchen sink]():

https://ace.c9.io/build/kitchen-sink.html

1. Turn on Vim keybindings,
2. Copy and paste the emoji 😇into the editor,
3. Press <kbd>a</kbd> to enter insert mode "after" the character under the carat,
4. Notice that the carat is placed "in the middle" of the emoji.

At this point, pressing <kbd>Backspace</kbd> also removes the first element of the surrogate pair making up the emoji, leaving behind the other (now invalid) piece.

**Comment by kevinushey** [comment]
Appears to still be an issue.

**Comment by andrewnester** [comment]
I tried to reproduce this on the latest version of Ace in kitchen sink using your steps and it does not seem to be reproducible. Could you please confirm that?

**Comment by kevinushey** [comment]
Very weird... I tried to reproduce again, and it seems like it reproduces inconsistently? For example:

https://user-images.githubusercontent.com/1976582/176506278-66a6beff-3485-4226-9a7a-288dae334353.mov

Using `x` to delete a character seems to always delete the first "half" of the emoji, though.

**Comment by andrewnester** [comment]
This PR fixes the issue in our dependency https://github.com/replit/codemirror-vim/pull/49

Once it's merged we can update the dependency

**Comment by andrewnester** [comment]
Fixed by this PR https://github.com/ajaxorg/ace/pull/4933 and released in version 1.11.1

**Comment by andrewnester** [comment]
Added additional fixes and released in 1.11.2
https://github.com/ajaxorg/ace/releases/tag/v1.11.2
