### ISSUE TITLE
Regex failing for custom commands

### ISSUE THREAD

**Issue by gone63** [ajaxorg/ace#4110]
I am using react-ace library and when I added a custom function for save a file("Ctrl-S") and another function for Save all files("Ctrl-Shift-S") always save a file is triggering.
![image](https://user-images.githubusercontent.com/23372594/68401306-8326b000-019f-11ea-8ee5-c792978ca9c9.png)

**Comment by nightwing** [comment]
Must be an issue with props dispatch or fileSourceUpdate, try adding console.trace to the exec functions of commands to see that different functions are called by ace. see https://codesandbox.io/s/ace-worker-3-43fm2
