### ISSUE TITLE
Multiple cursors

### ISSUE THREAD

**Issue by sebastianpantin** [ajaxorg/ace#4117]
I am trying to use the ace editor and it has worked great so far but now i have run into some problem. I want to navigate to some part by ctrl-leftclick on some text in the editor but this behaviour now starts the multiple cursors functionality. Is there any way to disable this functionality, without changing the ace.js file? I dont need it in my use case at all.

**Comment by nightwing** [comment]
you can completely  disable multiselct with 
```js
editor.setOption("enableMultiselect", false)
```

change it to use ctrl-alt instead of ctrl with
```
editor.$mouseHandler.$enableJumpToDef = true 
```

**Comment by sebastianpantin** [comment]
Cool! Thanks a lot!!
