### ISSUE TITLE
Chrome/Win: sometimes ace is an object, but ace.config is undefined

### ISSUE THREAD

**Issue by SjonHortensius** [ajaxorg/ace#4124]
I'm debugging an issue where `window.ace` is an object, but `ace.config` is somehow undefined. I use the following setup code:

```js
function()
{
        if ('object' != typeof ace)
                return;

        ace.config.set('workerPath', '/s/');
        // etc..
```

where the `ace.config.set` results in `Uncaught TypeError: Cannot read property 'set' of undefined`. I have not been able to reproduce this, but I see these errors (very infrequent, but only) from `Chrome 64, 70, 77 and 78`, all on `Windows 7, 8 or 10`.

Is this (even in theory) possible and can I prevent it?

**Comment by nightwing** [comment]
How do you load ace, with a script, or a module manager?
Are other methods such as `ace.edit` missing too?

**Comment by SjonHortensius** [comment]
This is on https://3v4l.org/ - it is directly included via a script. This only happens for a tiny percentage of hits - I cannot exclude the possibility this is some bot with only partial javascript support or another bug. I'm mainly interested whether this is possible at all, or should be ignored

**Comment by nightwing** [comment]
I don't see any way for this to happen in normal browser. I would add add `if (!ace.config) some logging` to see what is going on

**Comment by SjonHortensius** [comment]
thanks for your feedback. If I get anything more specific from my logging I'll let you know
