### ISSUE TITLE
Opening an editor with overtype already enabled

### ISSUE THREAD

**Issue by Llorx** [ajaxorg/ace#4125]
If you enable overtype with Insert key (Windows), then open an ace-editor, when you write something it will overtype although the editor cursor is not the overtype mode. If you then press the Insert key, overtype is enabled in ace-editor, the cursor changes to the overtype one and will still overtype.

In other words, when you open an ace-editor with overtype enabled, is impossible to disable overtype.

**Comment by nightwing** [comment]
On which browser do you see this, and is there a setting to enable overtype in browsers? For me on windows 7 both chrome and firefox ignore insert key and do not enable overtype in textarea

**Comment by Llorx** [comment]
Chrome under Win7. Not in textarea/inputs but yes on contenteditables: https://jsfiddle.net/20joudgb/

**Comment by nightwing** [comment]
Unfortunately i don't see any way for ace to detect this situation, without breaking the handling of ime input. Since the same bug affects textarea too, it's probably best to wait until https://bugs.chromium.org/p/chromium/issues/detail?id=1030231 is fixed.

**Comment by Llorx** [comment]
Yes, that's the issue I've just created haha.

**Comment by andrewnester** [comment]
Chromium bug has been already fixed https://bugs.chromium.org/p/chromium/issues/detail?id=1030231
