### ISSUE TITLE
Autocompletion adds problematic semicolon in CSS media queries

### ISSUE THREAD

**Issue by timothylong** [ajaxorg/ace#4126]
Found an issue with autocompletion in ace/mode/scss. When creating a media query like so:

`@media(min-width:992px) {...}`

Ace's autocompletion will add a semicolon as show below, which causes the CSS/SCSS to fail:

`@media(min-width:992px;){...}`

**Comment by timothylong** [comment]
Commenting to keep this alive.

**Comment by andrewnester** [comment]
Has been fixed and released in recent Ace version
