### ISSUE TITLE
Function to set how 'show invisibles' get shown.

### ISSUE THREAD

**Issue by iebuggy** [ajaxorg/ace#413]
These are hardcoded:

```
this.EOF_CHAR = "&para;";
this.EOL_CHAR = "&not;";
this.TAB_CHAR = "&rarr;";
this.SPACE_CHAR = "&middot;";
```

With no high-level functionality to make changes to the displayed symbols.  Something like:

```
opts = { SPACE_CHAR : '.' };
aceeditor.setShowInvisibleOptions(opts);
```

Would be nice.

Also, it looks like SPACE_CHAR is not working at the moment in the demo.
@gissues:{"order":98.75776397515529,"status":"backlog"}

**Comment by mkslanc** [comment]
Fixed by #4226
