### ISSUE TITLE
keys.PRINTABLE_KEYS is missing a number for the '+' sign

### ISSUE THREAD

**Issue by Vinnecent** [ajaxorg/ace#4131]
Used Browser: Chrome 78.0.3904.108
Operating System: macOS 10.15.1

There should be a code 187 for the '+' sign inside the PRINTABLE_KEYS array.

Following error occurred:
I tried to add a command with addCommand that used a '+' in bindKey. The exec function was never called.

**Comment by nightwing** [comment]
187 is already used for `=` key, `+` key is `shift-=`

**Comment by Vinnecent** [comment]
Ohh i see. What do you mean with `+` key is `shift-=`?

So it isn't possible to do something like this?
```
editor.commands.addCommand({
	name: 'increaseFontSize',
	bindKey: {win: 'Ctrl-+', mac: 'Command-+'},
	exec: function(editor) {
		editor.setFontSize(editor.getFontSize() + 1);
	},
	readOnly: false
});
```

**Comment by nightwing** [comment]
In QWERTY layout + key is the `=` with shift pressed. 

To handle plus keys both on keypad and main keyboard you need to do use ` bindKey: "Ctrl-=|Ctrl-+"` https://github.com/ajaxorg/ace/blob/v1.4.7/demo/kitchen-sink/demo.js#L189
