### ISSUE TITLE
scrolling further than content possible?

### ISSUE THREAD

**Issue by nielll** [ajaxorg/ace#4138]
Is there currently a way to scroll further than the limitation of the content? Like infinite?

I use ace along with markdown and since there are different offsets in editor and preview, the synchronized scrolling between ace and the markdown preview is not exactly the same. Mostly the md preview is higher than ace editors content and due to that i have to scroll down to the end within the preview div.

I hope I explained well enough, otherwise tell me if you need more background informations.

thanks in advance!

**Comment by nightwing** [comment]
You can use the `scrollPastEnd` option `editor.setOption("scrollPastEnd", 3)`, which is the number of screen heights to scroll past the end of document.

**Comment by nielll** [comment]
thank you, that helped me a lot. 

Is it possible to stop ace content from scrolling when reach some point?
