### ISSUE TITLE
vim mode: the functionality `. doesn't work and also has other missing features

### ISSUE THREAD

**Issue by rafaelmuynarsk** [ajaxorg/ace#4144]
On Vim, when we use `. the pointer returns to the last known position. Using the Vim mode on Ace this functionality is not yet implemented...

**Comment by nightwing** [comment]
Thanks for the report! could you please check if  <code>`.</code>   and <code>``</code>  work as expected on  https://raw.githack.com/ajaxorg/ace/vim/kitchen-sink.html

**Comment by rafaelmuynarsk** [comment]
Hi...

On this link it's working as expected. Is it an older version? On the version 1.4.7 neither ``.` or  are working:

https://ace.c9.io/build/kitchen-sink.html

**Comment by nightwing** [comment]
It is not an older version, it is the version in the pull request https://github.com/ajaxorg/ace/pull/4145, so this issue will be fixed in 1.4.8.

**Comment by rafaelmuynarsk** [comment]
I've also realized that the indent feature of Vim doesn't work on Ace's vim mode. So commands like `gg=G`, `=ap`, `=a{` are not working too.

**Comment by nightwing** [comment]
For the `=` command how closely would you expect the automatic indentation to match vim behavior to consider it working? Would simply indenting the way ace indents after pressing enter be enough?

**Comment by rafaelmuynarsk** [comment]
Not really, I'd need to apply indentation on all the text... Is there any Ace command outside vim mode that can do it? So I can just use it like when we use `Ctrl+/` on Ace that still works on vim mode even though it's not a vim mode specific command...

**Comment by nightwing** [comment]
Currently ace doesn't have a command to auto indent all the text. Some of  ides using ace, e.g cloud9, have commands to apply autoformatter but that changes more than indentation.

The hard part about adding command for automatic indentation is that different languages have different conventions, and there are often edge cases that are hard to handle.

So my question was how close to the indentation produced by vim should it be to be useful for you.

E.g. vim produces
```
if (
    a
     ) {
    b
}
```
but ace would indent it as
```
if (
    a
) {
    b
}
```
So how important are small details like this?

**Comment by rafaelmuynarsk** [comment]
So there's a way to indent as you showed on your second example on ace? For me it's fine like that too, those small details are not important in my case...

**Comment by nightwing** [comment]
There is no way yet, but it should be relatively easy to implement, i'll update the issue when it is done.
