### ISSUE TITLE
Content don't fit the editor window.

### ISSUE THREAD

**Issue by tall1432** [ajaxorg/ace#4147]
Hello,
  I have an issue the content is overflowing the editor window  on a React app ,
![image](https://user-images.githubusercontent.com/49268640/72171020-4ca12780-33d2-11ea-8501-52e89202aecf.png)
, how can i fix this problem ?

**Comment by nightwing** [comment]
Unfortunately it's hard to tell what is happening without seeing the page itself.
But ace editor does not draw anything outside its container div, so a simple way to debug is to replace ace editor with a div, debug the layout then enable the editor again.

**Comment by nightwing** [comment]
Closing, but please comment if the suggestion above did not help to fix the issue.
