### ISSUE TITLE
Latest Mozilla platform code doesn't like use of innerHTML()

### ISSUE THREAD

**Issue by jorgk3** [ajaxorg/ace#4152]
The story is this. I'm the author of the Mozilla Thunderbird add-on which integrates Ace into the Thunderbird Write/Compose window so you can edit the HTML of a new mail message:
https://addons.thunderbird.net/en-GB/thunderbird/addon/thunderhtmledit/
Apparently that has 6600 users right now.

Recently I noticed that a debug version of Thunderbird crashes on a MOZ_ASSERT(false) here:
https://searchfox.org/mozilla-central/rev/68b2e0fd4323261a229233ec2ab8606228979141/dom/security/DOMSecurityMonitor.cpp#105
A MOZ_ASSERT() is basically a "debug break", so a binary compiled with debug will crash, a production binary doesn't crash.

On the debug console I see the output of the fprintf() which I included below. I don't know why the fragment is printed as X's.

This is a little similar to https://github.com/ajaxorg/ace-builds/issues/147 where assigning to innerHTML was an issue. Frankly, I don't understand what the "fragment parsing" is about, and it's also hard to tell what Ace does since the library I use is minimised. I'm happy to supply more information.

EDIT: Sorry, just noticed, 147 was filed in ace-builds, should I move this one here?

Output follows:
Do not call the fragment parser (e.g innerHTML()) in chrome code or in about: pa
ges, (uri: ), (caller: chrome://thunderhtmledit/content/ace/ace.js, line: 1, col
: 283193), (fragment: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX)Assertion failure: false, at c:/mozilla-s
ource/comm-central/dom/security/DOMSecurityMonitor.cpp:105
#01: mozilla::dom::FragmentOrElement::SetInnerHTMLInternal (c:\mozilla-source\co
mm-central\dom\base\FragmentOrElement.cpp:1960)
#02: mozilla::dom::Element_Binding::set_innerHTML (c:\mozilla-source\comm-centra
l\obj-x86_64-pc-mingw32\dom\bindings\ElementBinding.cpp:3742)
#03: mozilla::dom::binding_detail::GenericSetter<mozilla::dom::binding_detail::N
ormalThisPolicy> (c:\mozilla-source\comm-central\dom\bindings\BindingUtils.cpp:3
099)

**Comment by nightwing** [comment]
most likely it is coming from https://github.com/ajaxorg/ace/blob/ad8153f4127fcb29bbaeb9b956e20887955b4835/lib/ace/layer/font_metrics.js#L59, (or the other innerhtml call in the same file) which can be easily changed to textContent. 

Could you try changing that two lines in your version of ace to verify that no other code causes similar issues?

**Comment by jorgk3** [comment]
Thanks for the quick reply.

In my minimised version of Ace 1.4.5 which is included in the latest version of my Thunderbird add-on, I replaced those two assignments of .innerHTML with .textContent as suggested.

Result: No crash any more :-)

While editing ace.js, I noticed that there were five more assignments to .innerHTML. I don't know which code path there are on or in which context (chrome or content) they will run or whether they might be made subject to further restrictions by Mozilla later, so maybe you can check them while we're here.

**Comment by nightwing** [comment]
The other uses are either for empty strings, which  seems to be allowed https://searchfox.org/mozilla-central/rev/68b2e0fd4323261a229233ec2ab8606228979141/dom/security/DOMSecurityMonitor.cpp#24or require change of the public api, for which we'll need to wait until the next major version.

**Comment by jorgk3** [comment]
Right, I saw that code.
