### ISSUE TITLE
I got it all working in no time! Thanks for maintaining this!

### ISSUE THREAD

**Issue by JobLeonard** [ajaxorg/ace#4153]
I managed to embed Ace into ObservableHQ with little to no hassle:

https://observablehq.com/@jobleonard/hello-ace-editor

... and I'm just genuinely impressed with how easy it was to set up, and how much power this thing manages to squeeze out of a few hundred kilobytes! Kudos!

(feel free to close as off-topic, just figured you peeps don't get enough thanks between all the bug reports)

**Comment by nightwing** [comment]
Thanks for using ace, and for kind word!
