### ISSUE TITLE
CSS mode "animation" property does not support custom animation names

### ISSUE THREAD

**Issue by aliadnan1984pk** [ajaxorg/ace#4166]
in css mode for "animation" property it does not support custom animation name and removes the space between name and next value e.g. 

```
.classname{
  animation: appear 1.5s ease-in-out;
}
```

turns into: 

```
.classname{
  animation: appear1.5s ease-in-out;
}
```

for now we have asked users to use a workaround fix for this using "animation-name" property i.e. 

```
.classname{
  animation-name: appear;
  animation: 1.5s ease-in-out;
}
```

**Comment by nightwing** [comment]
Which version of ace do you use? I could not reproduce the issue with 1.4.8 on https://ace.c9.io/build/kitchen-sink.html?doc=css

**Comment by aliadnan1984pk** [comment]
I updated the version but still the issue was there. on further inspection I found that its the "beautify" command  (ext/Beautify) that causes the issue. I have set the beautify command to execute on focus and blur. 
in above example you provided if you run the "beautify" command it reproduces the issue. 
for reference this is my code. I have multiple editors on page with different modes and i pass the editor reference to setEditorBeautify()
```
var beautifyFunc = ace.require("ace/ext/beautify").beautify;
var beautifyCommand = {
    name: 'Beautify',
    bindKey: {win: 'Ctrl-Alt-B',  mac: 'Command-Alt-B'},
    exec: function(editor) {
        beautifyFunc(editor.session);
    }
};
var beautifyEditor = function(editor){
    editor.execCommand('Beautify');
};
var setEditorBeautify = function(editor){
    editor.commands.addCommand(beautifyCommand);
    editor.on('focus',function(){
        beautifyEditor(editor);
    });
    editor.on('blur',function(){
        beautifyEditor(editor);
    });
};
```

**Comment by aliadnan1984pk** [comment]
Hi @nightwing  ace-builds/master   https://github.com/ajaxorg/ace-builds/tree/master , replaced all my with src-min . but the issue still there.
