### ISSUE TITLE
multiple styles(types) for tokens

### ISSUE THREAD

**Issue by dhakehurst** [ajaxorg/ace#4174]
I am writing my own tokenizer for Ace.
I'd like to be able to assign multiple different 'type's for the token.
Code in the 'renderer' (and other places) assumes that 'type' is a string.

is it possible to modify this so that we can have an array of strings,
or alternatively allow for another property (e.g. styles] that is an array of strings.

so that each rendered '<span>' can have multiple css classes assigned to it.

**Comment by nightwing** [comment]
You can use a string like "class1.class2" which is translated to class attribute of the form `"ace_class1 ace_class2"`

**Comment by dhakehurst** [comment]
ah. Many thanks for the tip. Is this documented anywhere? (I couldn't see it).

seems a bit of an odd way to do it, I'd have thought a string array would be clearer to the user.
Maybe the dot separated way is faster somehow ?

**Comment by dhakehurst** [comment]
any answer to above questions?

Is this documented anywhere?

seems a bit of an odd way to do it, I'd have thought a string array would be clearer to the user.
Maybe the dot separated way is faster somehow ?

**Comment by andrewnester** [comment]
I don't think it's documented somewhere, so we need to update our wiki to address this, thanks

**Comment by dhakehurst** [comment]
is the wiki updated ?
and have you considered a string array ?
