### ISSUE TITLE
implement tree editor, jsoneditoronline style

### ISSUE THREAD

**Issue by SavedByZero** [ajaxorg/ace#4176]
I would like to see tree view editing possible, in the style of jsoneditoronline.org.  I know that site uses ace, but I'd like to see what they did more automated and automatic.

**Comment by nightwing** [comment]
Unfortunately tree editor similar to jsoneditoronline is a whole new project which is outside of the scope of a code editor. If we tried to do it in ace, we would make ace worse for majority of users who do not need that, and would most likely make an inferior copy of jsoneditoronline as we need to work on the editor too. A better approach would be to submit feature requests to jsoneditoronline with suggestions of making it more automated and automatic.
