### ISSUE TITLE
Cursor as in textarea on mobile devices

### ISSUE THREAD

**Issue by ghost** [ajaxorg/ace#4178]
Hello.

in the editor on mobile devices, moving the cursor is only possible by tapping. It is not comfortable.
for example:
![1](https://user-images.githubusercontent.com/25941273/74103001-90b25400-4b59-11ea-86a4-45e0ce6f48e2.gif)

How can I smoothly move the cursor by swipe, just as it works in the element textarea using native tools iOS/Android?
for example:
![2](https://user-images.githubusercontent.com/25941273/74103003-9445db00-4b59-11ea-92b6-e9f2991593a4.gif)

**Comment by bmatusiak** [comment]
it looks like thats native to the phone's keyboard+webkit software,  but if i wher to code it in,, i would have to hook into the webkit's touch sensors, and watch for a direction..  but i dont know how that would work with selection in ace and current cursor rules

**Comment by vitomax** [comment]
The problem is not in the native keyboard+webkit, but the aceEditor. Here is an example editor that works like a native keyboard (on mobile) with textarea: http://satya164.xyz/react-simple-code-editor/

All online editors used in the textarea, but the browser events editors are treated differently. Maybe you can somehow configure to work with gesture events?

**Comment by vitomax** [comment]
this problem can not be solved? tell me where is the source of the code that is responsible for this and I will think about how to change it

**Comment by xu-xionglong** [comment]
Hi, do you find the solution to solve this problem? I meet the same problem and I found that codemirror behave exactly what we are looking for. However, it takes some effort for me to migrate from ace to codemirror

**Comment by eyedean** [comment]
> The problem is not in the native keyboard+webkit, but the aceEditor. Here is an example editor that works like a native keyboard (on mobile) with textarea: http://satya164.xyz/react-simple-code-editor/
> 
> All online editors used in the textarea, but the browser events editors are treated differently. Maybe you can somehow configure to work with gesture events?

@nightwing This link is dangerous and spam right now (possibly an expired domain).  I tried to report it, but it seems like GitHub has a bug in that.  You might want to delete it.  Thanks.

**Comment by akoreman** [comment]
Thanks for letting us know, deleted the comment. (For future reference, the deleted comment mentioned https://github.com/react-simple-code-editor/react-simple-code-editor as an alternative code editor which functions as desired in this issue)

**Comment by andredcoliveira** [comment]
This should be fixed for Android in #5087. Next step is to verify this and also to understand what it means for other mobile platforms (e.g., iOS)
