### ISSUE TITLE
unable to use ace.js with Angular due to path issues

### ISSUE THREAD

**Issue by manuchadha1979** [ajaxorg/ace#4179]
I am trying to use ng2-ace-editor in my Angular application. Angular6 makes the bundle which is then served by my `Play` application. But when the application loads, I get error

(ace.js:1 Unable to infer path to ace from script src, use ace.config.set('basePath', 'path') to enable dynamic loading of modes and themes or with webpack use ace/webpack-resolver
f @ ace.js:1
theme-monokai.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
52be6b88-fd69-4dab-aa4e-0536d6ea47e0:1 Uncaught DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'http://localhost:9000/assets/ui/worker-javascript.js' failed to load.
    at blob:http://localhost:9000/52be6b88-fd69-4dab-aa4e-0536d6ea47e0:1:1)

I am clueless at the moment about what the issue is.

**Comment by eyedean** [comment]
See https://github.com/securingsincity/react-ace/issues/725#issuecomment-629068872
