### ISSUE TITLE
MediaWiki mode 

### ISSUE THREAD

**Issue by lmn8** [ajaxorg/ace#4181]
Is MediaWiki support welcome in this extension? I have a rough set of highlighting rules on my PC, but I'm not sure how to implement Markdown style `syntaxhighlight` support :/

Asking because this extension is used in MediaWiki extension CodeEditor :)

**Comment by nightwing** [comment]
Yes it would be welcome. 
What do you mean by "Markdown style syntaxhighlight"?

**Comment by lmn8** [comment]
```xml
<syntaxhighlight` lang="lua">
local test = require 'testframework'
</syntaxhighlight>
```
is MediaWiki's alternative to Github-style code blocks.

**Comment by lmn8** [comment]
Some todos:
* A `<syntaxhighlight lang="lua">` tag should highlight its contents in the respective mode (Lua)
* Some kind of folding support. Maybe for `<xml>` tags, `{| ... |}` (tables) and `{{template}}`s
* Tests would be welcome :)

**Comment by lmn8** [comment]
Also a large number of [switches](https://www.mediawiki.org/wiki/Help:Magic_words#Behavior_switches) (token = `variable.language.mediawiki`?) are missing
