### ISSUE TITLE
RegExp capturing groups are not inserted in replacement, when using editor.session.replace()

### ISSUE THREAD

**Issue by JeSuisUnCaillou** [ajaxorg/ace#4185]
When trying to replace a regex with a string containing a reference to a capturing group (the `$1`) with the javascript method `editor.session.replace()`, it doesn't insert the matched capturing group, it just put `$1`.

```javascript
const range = editor.find(/regex_with_group(group)/, { regExp: true })

if (range) {
  const match = editor.session.getTextRange(range)
  editor.session.replace(range, 'new_string_$1')
}
```
It works fine when I use the "Search & Replace" box of the editor embedded in my page, but not when I try to do it with my javascript code.

**Comment by nightwing** [comment]
use 
```
if (range) {
   editor.replace('new_string_$1')
}
```
similar to https://github.com/ajaxorg/ace/blob/master/lib/ace/ext/searchbox.js#L339
`session.replace` is only supposed to work with strings and ranges, not with regexps.

**Comment by JeSuisUnCaillou** [comment]
Ooooh, thank you ! I didn't get this subtlety.

What if I used `editor.findAll(/regex_with_group(group)/, { regExp: true })` ?
Should I just call `editor.replace('new_string_$1')` as many times as there is ranges in my `findAll` result ?

**Comment by JeSuisUnCaillou** [comment]
Ok, I found the `editor.replaceAll()`, my bad. Well, this issue is pretty much over now :)
