### ISSUE TITLE
attempting to add the same line widget twice causes a hang

### ISSUE THREAD

**Issue by kevinushey** [ajaxorg/ace#4186]
Sorry, I don't have a reproducible example, but I think I can explain the issue.

When a line widget is registered, if an old line widget is detected on the same row, the new line widget is tagged with the old widget as `$oldWidget`:

https://github.com/ajaxorg/ace/blob/d35142c47b5549ab5714848f373b98a4462d2bdd/lib/ace/line_widgets.js#L192-L199

Later, `$updateRows()` is called, which tries to update the tagged row for each line widget:

https://github.com/ajaxorg/ace/blob/d35142c47b5549ab5714848f373b98a4462d2bdd/lib/ace/line_widgets.js#L178-L181

However, this will enter an infinite loop if `w` and `w.$oldWidget` refer to the same object.

Could / should Ace detect this situation and handle it more gracefully? This is an erroneous use of the API but one can accidentally do this in some cases.

**Comment by nightwing** [comment]
Ace definitely should handle this more gracefully, but i am not sure how to do that, yet. Should we remove the widget from the old position and add again similar to the way appendChild would work?
