### ISSUE TITLE
Adding json.snippet to the ace editor

### ISSUE THREAD

**Issue by sandhyacCLS** [ajaxorg/ace#4187]
I want to create my own json.snippet file and import it to the ace editor which i have embedded in a visual force page. I want to do this without having to create a function and then using the snippetManager that loops through each snippet

**Comment by nightwing** [comment]
It is not possible to do this without snippet manager. 

You need to load the snippets as text using `require("text!` or inline string.
```js
 snippetText = "snippet vfx\n\t<visalforce>\n\t\t$1\n\t</visalforce>"
var snippetManager = require("ace/snippets").snippetManager;
snippets = snippetManager.parseSnippetFile(snippetText);
snippetManager.register(snippets, "visualforce");
```
Or alternatively provide snippets as js object
```js
snippets=[{
   tabTrigger: "apax",
   content: "<apex:$1>"
}]
snippetManager.register(snippets, "visualforce");
```

**Comment by sandhya-pillai** [comment]
could you please elaborate on how to load the xyz.snippet file in a visualforce page as text

**Comment by nightwing** [comment]
Unfortunately i do not know much about visualforce and its build system, with normal javascript and webpack you could use `require("text!./xyz.snippet")`
