### ISSUE TITLE
insert characters at the cursor and run to another location,

### ISSUE THREAD

**Issue by w3yyb** [ajaxorg/ace#4206]
When I edit a file, insert characters at the cursor and run to another location, I  use  chrome 80 on ubuntu.
see this video: [https://www.hdycsx.com/WeChat_20200305085714.mp4](https://www.hdycsx.com/WeChat_20200305085714.mp4)

**Comment by nightwing** [comment]
This happens because the font is not monospace, ace supports only monospace fonts for now.

**Comment by sujiangyin** [comment]
> monospace

**why i had import the monospace font's ttf,but still met the problem like above vedio?**

i try two kind of font as:
1:
	@font-face {
		font-family: 'Monaco';
        src: url('Monaco.ttf');
        font-weight: normal;
        font-style: normal;
	}

2:
	@font-face {
		font-family: 'monospace';
        src: url('monospace.ttf');
        font-weight: normal;
        font-style: normal;
	}

.all is not use.

what to do next?

**Comment by sujiangyin** [comment]
> When I edit a file, insert characters at the cursor and run to another location, I use chrome 80 on ubuntu.
> see this video: https://www.hdycsx.com/WeChat_20200305085714.mp4

**have you solve that pro?what the methed you use?**
