### ISSUE TITLE
Anyway to change the comment style of ctrl + / for a mode?

### ISSUE THREAD

**Issue by yipenghe** [ajaxorg/ace#4207]
Currently I'm using markdown mode, and the  behaviour when selecting multiple rows and hit "ctrl + /" is to add \ around each rows

that is:
```
abc
abc
```
goes to 
```
<!--abc-->
<!--abc-->
```
Is there a way to just override the comment style to be wraping the rows with // instead? I guess I can override the whole exec for "ctrl + /", but just wondering if there's an easy way to change the comment style of a markdown mode.

Thanks!!

**Comment by nightwing** [comment]
You can change the `blockComment` property on the mode
`editor.session.$mode.blockComment = {start: "/", end: "/"}`

**Comment by yipenghe** [comment]
> You can change the `blockComment` property on the mode
> `editor.session.$mode.blockComment = {start: "/", end: "/"}`

I see I was trying getMode, thanks!

**Comment by yipenghe** [comment]
@nightwing Sorry for bothering again, it didn't seem to work. To be more specific, I'm using it like this:
```
var editor = ace.edit('worksheet-editor');
editor.$blockScrolling = Infinity;
editor.session.setUseWrapMode(false);
editor.setShowPrintMargin(false);
editor.session.setMode('ace/mode/markdown');
```
when I pring out editor.session.$mode
it shows that the object has $highlightrules, $behaviour, $tokenizer and HighlightRules property, but no blockComment property,
so adding
`editor.session.$mode.blockComment = {start: "/", end: "/"}
`
didn't work.

**Comment by nightwing** [comment]
this is probably because of delayed loading of modes either include the script for markdown mode the same way you load the ace.js or use

```js
editor.session.setMode('ace/mode/markdown', function() {
    editor.session.$mode.blockComment = {start: "/", end: "/"}
});
```

**Comment by yipenghe** [comment]
> this is probably because of delayed loading of modes either include the script for markdown mode the same way you load the ace.js or use
> 
> ```js
> editor.session.setMode('ace/mode/markdown', function() {
>     editor.session.$mode.blockComment = {start: "/", end: "/"}
> });
> ```

I see, works great, thank you so much!!
