### ISSUE TITLE
unexpected token '< ' 

### ISSUE THREAD

**Issue by BrijeshDarji1** [ajaxorg/ace#4210]
I am getting **unexpected token '< '** error in the console, when I reload page which contains my ace editor.

**Comment by nightwing** [comment]
Sometimes this can happen if a script is missing, and server is returning html as part of the error message. Are there any errors shown in network tab of browser devtools?

**Comment by BrijeshDarji1** [comment]
@nightwing Okay. No there is no error in the network tab. I only get error in console.

**Comment by baronwithyou** [comment]
Had the same issue, but the error gone when I remove the `enableSnippets` option.
