### ISSUE TITLE
In some of the mac os and chrome browser ace editor autocomplete popup is not working

### ISSUE THREAD

**Issue by ranjeet-kumar-nutanix** [ajaxorg/ace#4213]
In some of the mac os and chrome browser ace editor autocomplete popup (custom autocomplete) is not working.

below are the details of browser :

Chrome Version 80.0.3987.132 on macOS Catalina Version 10.15.3

and currently I am using https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.5/ace.js and https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.5/ext-language_tools.js

**Comment by nightwing** [comment]
Browser version and OS are most likely not related to the issue, but without a test page and description of how exactly is it not working it is not possible to say what is causing it.
Could you show a demo page where autocomplete is not working? Are there any errors in the browser console?
