### ISSUE TITLE
removeCommand not working for goToNextError

### ISSUE THREAD

**Issue by cipri-tom** [ajaxorg/ace#4214]
Hi,

One of the projects I am using is based on Ace editor (google earth engine playground).

It has this keybinding for `Ctrl-E` -> `goToNextError`. I am capturing the editor in the console and I want to remove this command. I have tried `editor.commands.removeCommand(editor.commands.commands.goToNextError)` as well as `myEditor.commands.removeCommand('goToNextError')`. Each version correctly removes the command entry, but I do not recover the native `Ctrl-E` shortcut, which on macos is "Go to line end".

Am I doing something wrong?

Edit: I have now realised that `gotolineend` also has `Ctrl-E` as a key binding. However, still nothing happens when I hit `Ctrl-E`. Could it be because there was a conflict initially ?

**Comment by nightwing** [comment]
Hi, unfortunately i couldn't find a way to access `google earth engine playground` to test which version of ace they use, on the latest version ctrl-e should work out of the box.

But in any case `editor.commands.bindKey("ctrl-e", "gotolineend")` should help.

**Comment by cipri-tom** [comment]
Hi,

Indeed, it is a private alpha for now so no easy way to use it. Sorry, I should've mentioned :(. Hope you didn't spend too much time searching for it.
How can I find out the editor version? (just cause you made me curious)

Indeed, the rebinding worked ! Thank you !!
Previously I had try rebinding it to `null`, expecting that it would let the event bubble all the way up to the OS. Any explanation why removing the command or rebinding to null doesn't let it bubble ? I had a look in the code but couldn't figure it out (my first time here). 

Thanks again ! 

p.s. Currently, I have put a breakpoint where they call `ace.edit(...)` and save that variable in a global one. Do you know of an easier way to get a reference to the editor from the console?

**Comment by nightwing** [comment]
There is `.env.editor` property on the container node so the following should work in browser console.
```
Array.from(document.querySelectorAll(".ace_editor")).map(x => x.env.editor.commands....)
```

The version can be accessed as `ace.version` it is also shown in options dialog (`Cmd-,`) but that may be disabled.

Ace and other javascript code editors, reimplement cursor movement commands, because they use a hidden textarea that doesn't contain all the code, and the displayed code is not editable.

**Comment by cipri-tom** [comment]
Awesome ! Thank you very much ! 

There is no `.version` on global `ace` 😞 . And `Cmd-,` opens the Firefox options, so probably disables. 

Thanks for the explanations !
