### ISSUE TITLE
Feature request:  Option to disable all auto-indent, auto-character completion, etc.

### ISSUE THREAD

**Issue by cubiclesoft** [ajaxorg/ace#4219]
Bug:

* In the Kitchen sink demo (default Javascript example), type: `"\"`
* Press backspace.

Result:

* `"\`  <-- Closing quote mark removed.

Probably expected:

* `"\"`

Related:  #485, #398.

Bug:

```
switch (x)
{
	case 1:
		{ <-- Why u indented?!!!?!
			// RAWR!!!!
		}
}
```

Related:  #2895.

I could go on all day long but these two examples are enough.

If there were options to turn off auto-indent, auto-character completion, etc.  I could simply turn off the "always guaranteed to be buggy" features (like I do in any sane text editor) and not open a feature request on a bug tracker.

**Comment by nightwing** [comment]
When turning off auto-indent would you expect the indentation on new line to be 0 or to stay at the level of the previous line?

**Comment by cubiclesoft** [comment]
0.  No indentation.  When I press carriage return, I expect a new line and only a new line.  What I enter on my keyboard is what I expect to get in the buffer and on the screen.  Anything else is broken by design.

**Comment by cubiclesoft** [comment]
How about an option to disable automatic character completion?  (Quotes, parenthesis, braces, brackets, etc.)

**Comment by nightwing** [comment]
That option already exists, use: `editor.setOption("behavioursEnabled", false)`

**Comment by cubiclesoft** [comment]
Ah.  Okay.  Thanks.

**Comment by cubiclesoft** [comment]
The items in this issue appear to be done.  Thanks for taking the time to implement `enableAutoIndent`.  Closing.
