### ISSUE TITLE
Hide previous bracket highlighting after editor.SetValue("", -1)

### ISSUE THREAD

**Issue by feliixx** [ajaxorg/ace#4232]
Hi, 

First of all, thanks a lot for this excellent library ! 

I've noticed a bug with Bracket Highlighting introduced in version 1.4.8 ( reproduced on firefox 74 and chrome 80) with this code: 

```
var resultEditor = ace.edit(document.getElementById("result"), {
     "mode": "ace/mode/javascript",
     "fontSize": "16px,
     "readOnly": true,
     "showLineNumbers": false,
     "showGutter": false,
      "useWorker": false,
      "highlightActiveLine": false,
      "wrap": true
})
resultEditor.SetValue(indent("[{'key': 'value'}]"), -1)

resultEditor.SetValue("", -1)
```

result: 

![bracket](https://user-images.githubusercontent.com/10615565/78105133-36888d80-743c-11ea-977e-8fc1e035bb0f.png)

**Comment by nightwing** [comment]
Thanks for detailed bug report! Turns out this was present before too, but wa less noticeable because did not happen with cursor at 0

```js
editor.setValue("{     }", -1);
editor.navigateRight();
```
```js
editor.session.insert({row: 0, column: 3}, "foo")
```
