### ISSUE TITLE
editor.selection is "undefined" on mobile (v1.4.9)

### ISSUE THREAD

**Issue by radimitrov** [ajaxorg/ace#4233]
editor.selection isn't defined on mobile and no related functions can be invoked. It works on desktop, though. Version 1.4.8 worked for both, so that should narrow it down.

**Comment by nightwing** [comment]
Do you see any errors in the console? And could you tell more about the way you use ace or show a demo page, on https://ace.c9.io/ editor.selection works on android the same way as on desktop.

**Comment by radimitrov** [comment]
I'm embedding the editor in an Android library with WebView. Though I tested with plain files on mobile with the same result. No console errors beyond "undfined" when trying to use editor.selection or editor.session.selection.

Code segment to reproduce on mobile with a delay just in case would be:
```javascript
var editor = ace.edit("editor");
console.log(editor.selection); //undefined on mobile only
console.log(editor.session.selection); //same
setTimeout(function() { console.log(editor.selection); console.log(editor.session.selection); }, 5000);
```

**Comment by nightwing** [comment]
By testing with plain files on mobile, do you mean loading the example in a browser?

I am testing with 

```html
<div id=editor style='height:100px'></div>
<script src="https://ajaxorg.github.io/ace-builds/src/ace.js"></script>
<script>
    var editor = ace.edit("editor");
    if (!editor.selection) editor.setValue("selection is undefined")
    else  editor.session.setValue("all is ok " +  editor.selection + "\n" + ace.version)
</script>
```
and it is setting the value to `all is ok` on chrome and firefox on android.

Could you check if you see an error with this jsbin https://output.jsbin.com/funezahaqe ?

**Comment by radimitrov** [comment]
Ok, I have different behaviours. In all cases the same HTML code below is loaded.
**1.** It always works in mobile Chome and Firefox.

**2. With webview.loadDataWithBaseURL("file:///android_asset/", htmlString, "text/html", "UTF-8");**
 Says "all is ok" at start and "selection in undefined" later (during selection). This used to work several hours ago in v1.4.8.

**3. With webview.loadUrl("file:///path_to/ace_test.html");**
This works properly - a file. The only thing that currently works with a WebView (Android 9, Redmi Note 5).

Still no errors in console. 

```html
<div id=editor style='height:100px'></div>
<script src="https://ajaxorg.github.io/ace-builds/src/ace.js"></script>
<script>
    var editor = ace.edit("editor");
    if (!editor.selection) editor.setValue("selection is undefined")
    else {
		editor.session.setValue("all is ok " +  editor.selection + "\n" + ace.version)
		editor.selection.on("changeSelection", function (e) {
			if (!editor.selection) console.log("selection is undefined");
                        else console.log("ok");
		});
	}
</script>
```

**Comment by nightwing** [comment]
Is there any other code running in the page?
Could you please try running the following code snippet to see what is setting the value of selection to undefined

```html
<div id=editor style='height:100px'></div>
<script src="https://ajaxorg.github.io/ace-builds/src/ace.js"></script>
<script>
(function() {
    var editor = ace.edit("editor");
    if (!editor.selection) editor.setValue("selection is undefined")
    else {
        editor._selection_= editor.selection
        editor.__defineGetter__("selection", function() {
            return this._selection_
        })
        editor.__defineSetter__("selection", function(v) {
            console.log(v)
            console.trace("selection object changed")
            return this._selection_ = v
        })
        editor.session.setValue("all is ok " +  editor.selection + "\n" + ace.version)
		editor.selection.on("changeSelection", function (e) {
			if (!editor.selection) console.log("selection is undefined");
            else console.log("ok");
		});
	}
})();
</script>
```

**Comment by radimitrov** [comment]
Your example works. I found the problem. It is an error on my part. I was setting the editor "div" to "display: none" to avoid an initial white background before the theme takes effect and then dispaying it.  That must have done something internally. Same with ace.edit(element, options). I'll do it another way.
