### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by praisedpk** [ajaxorg/ace#4238]
Hi, we are seeing lots of 404 requests in our logs for the following files:

```
/mode-js.js
/mode-aodocs_reference.js
/mode-undefined.js
/theme-undefined.js
/mode-mode.js
/theme-vibrant.js
/mode-vue.js
/mode-SCSS.js
```
There are several more files. I can paste the complete list here if you want. These errors span last several versions of ace. Can you please check if its possible to fix these missing files?

Thanks.

**Comment by praisedpk** [comment]
The above errors are from PageCDN's public CDN logs. Here is the ACE repo for list of files: https://pagecdn.com/lib/ace

**Comment by nightwing** [comment]
These can happen if setMode or setTheme are called with wrong values. For instance   request to mode-js means that your code have called `setMode("ace/mode/js")` instead of `setMode("ace/mode/javascript")`

**Comment by mayngutsy** [comment]
> The above errors are from PageCDN's public CDN logs. Here is the ACE repo for list of files: https://pagecdn.com/lib/ace

I am running Ace as an npm node module, but we seem to be having a lot of missing file errror on terminal  when we try to bundle ace with browserify.
