### ISSUE TITLE
Latest Version not in NPMJS

### ISSUE THREAD

**Issue by shanuashwani** [ajaxorg/ace#4244]
Hi,
We cannot see latest version of ACE library in NPMJS. Last version available is 1.3.0.
https://www.npmjs.com/package/ace

Can you please upload latest to NPMJS.

Regards,
Ashwani

**Comment by nightwing** [comment]
Unfortunately the ace package on npm is not related to ace editor, https://github.com/ajaxorg/ace-builds is published to npm as https://www.npmjs.com/package/ace-builds

**Comment by tobymurray** [comment]
It looks like https://www.npmjs.com/package/ace-code-editor is associated with this project, and it does appear to have a very old version. While trying to find a way to use this project and manage it via NPM, I tripped over this as well. Maybe covered by #3731, but just adding an anecdote.

**Comment by dbones** [comment]
is this some thing that you will look to publish to in the near future?
