### ISSUE TITLE
Strange tab key behavior in PHP editing mode

### ISSUE THREAD

**Issue by cubiclesoft** [ajaxorg/ace#4248]
In the kitchen sink demo, when the document/mode is set to PHP and behaviors are disabled, pressing the tab key results in very odd behavior.

Steps to replicate:

* Select PHP document/mode.
* Disable behaviors and autocompletion.
* Place the cursor after or even inside `echo` or a variable like `$num`.
* Press tab on the keyboard.

Result:

The text preceding the cursor is transformed and wrapped in "HTML" tags, usually badly.

```
<1nu></1nu>m
```

The situation can be made worse by pressing the left arrow key and then pressing tab again.  What was a variable called $num quickly becomes:

```
<<<1num></1num>></1num>></1num>
```

**Comment by nightwing** [comment]
Kitchen sink has the emmet extension enabled  it can be disabled with `editor.setOption("enableEmmet", false)`, but in other places the extension is disabled by default .
