### ISSUE TITLE
Documentation for setOption()/setOptions() is missing

### ISSUE THREAD

**Issue by cubiclesoft** [ajaxorg/ace#4249]
Under the API Reference page of the documentation -> Editor, there is no `setOption` or `setOptions` function listed.

Would be nice to have a complete list of fully documented options somewhere.  What each option is, what it does, what values are allowed, etc.

**Comment by samuei** [comment]
It is definitely missing the `hasCssTransforms` option, so it is incomplete.

**Comment by cubiclesoft** [comment]
I've implemented a dialog that uses nearly all of the user-configurable options (didn't have a use for hasCssTransforms and a couple of others in a configuration dialog):

https://github.com/cubiclesoft/php-filemanager/blob/master/support/file-manager.js#L2138

I tried to summarize what each option does and I tried to logically group related options together.  Searching ace.js for the string `defineOptions()` helped identify the entire list of possibilities.  Here's what my Settings dialog looks like:

![image](https://user-images.githubusercontent.com/1432111/90706161-6a2c4e80-e249-11ea-95bc-f16f46ec1b3e.png)

![image](https://user-images.githubusercontent.com/1432111/90706346-cabb8b80-e249-11ea-9850-19f618d0931b.png)

![image](https://user-images.githubusercontent.com/1432111/90706409-ede63b00-e249-11ea-8857-9f73c8bc8b4a.png)

**Comment by mkslanc** [comment]
Fixed by [Ace API reference generator](https://github.com/ajaxorg/ace-api-docs)    

[setOptions API reference](https://ajaxorg.github.io/ace-api-docs/interfaces/ace.Ace.Editor.html#setOption)
