### ISSUE TITLE
Allow configuration of autocomplete commands

### ISSUE THREAD

**Issue by SaraaraS** [ajaxorg/ace#4250]
Usecase - Currently autocomplete matches on Tab and Return, I would like to make it configurable to which (or both) it completes on, in autocomplete.js I see the object where these commands are set, but it would be great to be able to pass in a configuration object.

**Comment by henrymgarrett** [comment]
I second this enhancement.  My use case is to have the 'Tab' key select the current autocomplete selection, and the Enter key submit the input (no matter if autocomplete is enabled or not).  Currently, the autocomplete Enter command overrides the editor Enter command, so the user cannot submit an input when the autocomplete popup is opened.

**Comment by mahdi943** [comment]
> Usecase - Currently autocomplete matches on Tab and Return, I would like to make it configurable to which (or both) it completes on, in autocomplete.js I see the object where these commands are set, but it would be great to be able to pass in a configuration object.

Hi,
I am using Ace editor in my project for Gherkin syntax. I have already implemented existing ace autocomplete but it just suggests current words in the editor; I need to add my custom list for Autocompletion.
How can I do that?
Can you help me where can I define my own list?
Thanks.

**Comment by SaraaraS** [comment]
> > Usecase - Currently autocomplete matches on Tab and Return, I would like to make it configurable to which (or both) it completes on, in autocomplete.js I see the object where these commands are set, but it would be great to be able to pass in a configuration object.
> 
> Hi,
> I am using Ace editor in my project for Gherkin syntax. I have already implemented existing ace autocomplete but it just suggests current words in the editor; I need to add my custom list for Autocompletion.
> How can I do that?
> Can you help me where can I define my own list?
> Thanks.

Hey totally off topic for this issue - but you need to create a custom completer on the editor object. Helpful gist (not mine) here - https://gist.github.com/yuvalherziger/aa48782568c6914b55066d290ff88360

**Comment by mahdi943** [comment]
> > > Usecase - Currently autocomplete matches on Tab and Return, I would like to make it configurable to which (or both) it completes on, in autocomplete.js I see the object where these commands are set, but it would be great to be able to pass in a configuration object.
> > 
> > 
> > Hi,
> > I am using Ace editor in my project for Gherkin syntax. I have already implemented existing ace autocomplete but it just suggests current words in the editor; I need to add my custom list for Autocompletion.
> > How can I do that?
> > Can you help me where can I define my own list?
> > Thanks.
> 
> Hey totally off topic for this issue - but you need to create a custom completer on the editor object. Helpful gist (not mine) here - https://gist.github.com/yuvalherziger/aa48782568c6914b55066d290ff88360

 I am quite new in Github and could't find the topic related my question. 
Your response was helpful.
Thank you so much.

**Comment by mdecarlo** [comment]
@toddperumal, this would still be a good enhancement for us, yes?

**Comment by toddperumal** [comment]
@mdecarlo EMPHASTIC YES. :) appreciate you tagging.

**Comment by linuspahl** [comment]
In case it will be helpful for others, I found a workaround here: https://groups.google.com/g/ace-discuss/c/ormPdBQfCvw/m/g2n8y6g2AAAJ
 
```
if (editor.completer?.keyboardHandler?.commandKeyBinding?.return) {
  editor.completer.keyboardHandler.removeCommand('Return');
}
```

Please note, you need to run this when the autocomplete popover is open, otherwise `editor.completer` is not defined. It is a workaround, but it is the only solution I found.
