### ISSUE TITLE
Race condition in onChangeAnnotation when editor is being destroyed

### ISSUE THREAD

**Issue by Sidnioulz** [ajaxorg/ace#4257]
## Bug Description

1. Create an editor
2. Load some content into it
3. Before annotations are parsed and before `onChangeAnnotation` is called, destroy the editor
4. With a bit of bad luck, `onChangeAnnotation` will be called after `editor.destroy()`, and `editor.getSession()` will return `null`, causing a crash

I can reproduce this bug systematically in my (proprietary) app's end-to-end test platform, but some of my colleagues can't, because, well, it's a race condition. We're using react-ace along with ace-builds, though I believe the bug is in the original Ace source code.

## Fixes?

I am under the impression that when the editor is destroyed, event handlers aren't disconnected. This would be necessary in order to ensure any async processing going on in the background does not result in calling invalid handlers.

An easier, but dirtier fix would be to return from `onChangeAnnotation` if the session is `null`. This is what I do locally on my ace-builds package to circumvent the issue.

It's also possible that, when the editor is being destroy, `session.destroy()` does not clear listeners in the same way that `setSession` does, and that calling `setSession(null)` instead would fix the issue.

**Comment by nightwing** [comment]
https://github.com/ajaxorg/ace/pull/4235 adds this.removeAllListeners calls which should fix this issue. Could you please try v1.4.10?

**Comment by Sidnioulz** [comment]
I'd love to, unfortunately my project is using `ace-builds` along with a React package, so I can't do this trivially. I can backport the code changes into my local copy and see if the race condition disappears, though, and then double check when `ace-builds` is up to date. Would that be an ok criteria of acceptance for you?

**Comment by nightwing** [comment]
Sorry for the confusion, the version 1.4.10 of ace-builds released yesterday is up to date and contains the fix from pull request

**Comment by Sidnioulz** [comment]
It's taken me some time to test this as I had to bump `react-ace`'s version, redeploy a patched version, etc, but I'm pleased to confirm that it is fixed indeed.

@nightwing thank you for your quick help.
