### ISSUE TITLE
Ace gets confused with Hebrew

### ISSUE THREAD

**Issue by fur-hebwiki** [ajaxorg/ace#4261]
So, for hebrew sites, it's often required to use hebrew strings as part of the code, e.g. for prompts, labels, and regex expressions.
so you may want to write something like

```
var currentValue = 'אני אוהבת ללקק גלידה';
if ( prompt('מה את אוהבת לעשות?', currentValue) ) {
   doSomething();
}
```
the problem is that ACE jumbles the prompt() line, and trying to edit this line later (say, change currentValue to suggestedValue), is an exercise in frustration.

the main issue seems to be the location of the caret, but it's not the only misbehavior.

copy the tiny snippet above to the [kitchen sink](https://ace.c9.io/build/kitchen-sink.html) to reproduce the issue.

(i suspect it's the same with any RTL language strings - did not test)

peace.

**Comment by nightwing** [comment]
Unfortunately the default fonts used in ace (consolas on windows) do not have monospace characters for hebrew, and since ace does not support variable width fonts yet, the caret get's rendered in a wrong place. As a temporary workaround you can add `font-family: courier;` css rule for the editor.

**Comment by fur-hebwiki** [comment]
thank you so much! 
sorry for the late response. this is very helpful.
peace
