### ISSUE TITLE
Build 1.4.10 adds outdated "ace" dependency

### ISSUE THREAD

**Issue by dpraul** [ajaxorg/ace#4262]
This seems unintentional, but as of build `1.4.10` [the `package.json`](https://github.com/ajaxorg/ace-builds/blob/2ea299a2bee97fdf58fc90cb76eec6c45535a63f/package.json#L21) now lists a dependency on [`ace@1.3.0`](https://www.npmjs.com/package/ace) - a package that has not been updated in 4 years, and has many out-of-date dependencies itself. Is there any reference to why this is needed, if it was intentional?

**Comment by nightwing** [comment]
thanks for the bug report, this was not intentional, fixed in v1.4.11

**Comment by dpraul** [comment]
Thanks! The package on NPM looks good now. There's no corresponding release on GitHub, though.

**Comment by dpraul** [comment]
Just checked and it's reflected there now - thanks again!
