### ISSUE TITLE
Typo in Editor `blur` event typing

### ISSUE THREAD

**Issue by aldo-roman** [ajaxorg/ace#4263]
Says `flur`, should say `blur`

Method `flur` does not exist on Editor

https://github.com/ajaxorg/ace/blob/e1d9586aef7926ac74e091ebc013a606778ac626/ace.d.ts#L749

**Comment by catrina4200** [comment]
> Says `flur`, should say `blur`
> 
> Method `flur` does not exist on Editor
> 
> https://github.com/ajaxorg/ace/blob/e1d9586aef7926ac74e091ebc013a606778ac626/ace.d.ts#L749
[https://github.com/ajaxorg/ace/pull/4264#issue-404230291]()
