### ISSUE TITLE
Is there a way to tell when the editor is ready for input?

### ISSUE THREAD

**Issue by csteez** [ajaxorg/ace#4265]
I created a custom mode, with its own folding rules. The folds show up, but we would like the editor to load with everything folded. We load the editor with a saved value. 
If I call `editor.getSession().foldAll();` too early, it doesn't do anything because the editor hasn't finished loading. 
Is there an event that is emitted after `setValue` is called? Or another way to handle this issue?

**Comment by nightwing** [comment]
`setValue` in ace is synchronous. 

FoldAll not finding foldwidgets can happen if it is called before the mode is loaded, the best workaround for that is to include the mode with require before calling setMode.
alternatively it is possible to pass a callback as a second argument to setMode, or use event listener for the changeMode event on session
 https://github.com/ajaxorg/ace/blob/v1.4.10/lib/ace/edit_session.js#L940

a third possibility is to add `attachToSession` method to the mode https://github.com/ajaxorg/ace/blob/master/lib/ace/edit_session.js#L934-L936 similar to https://github.com/c9/core/blob/master/plugins/c9.ide.find.infiles/findinfiles.js#L148, but then foldall will be called also when switching modes
