### ISSUE TITLE
[Mode Request] gLua Syntax

### ISSUE THREAD

**Issue by ArnaudLier** [ajaxorg/ace#4269]
Hello! I'm requesting gLua Syntax Mode.
Here what it looks actually :
![image](https://user-images.githubusercontent.com/32982428/79747698-6f65a500-830c-11ea-8413-efabee8b1988.png)
What it should looks : 
![image](https://user-images.githubusercontent.com/32982428/79747729-80161b00-830c-11ea-9c3f-723678e59697.png)
Main changes : 
![image](https://user-images.githubusercontent.com/32982428/79747792-9a4ff900-830c-11ea-83be-7d82410dee46.png)

**Comment by ZeProf2Code** [comment]
Here is a tmLanguage file for it : https://github.com/FPtje/Sublime-GLua-Highlight/blob/master/Lua.tmLanguage

**Comment by lmn8** [comment]
There's a pull for this at https://github.com/ajaxorg/ace/pull/3226 but still open
