### ISSUE TITLE
setNewLineMode problem

### ISSUE THREAD

**Issue by ifuchs** [ajaxorg/ace#4270]
I am using the ACE editor in the text_editor in NextCloud. My problem is that if I edit a file which ends in \n, the editor is saving the file with \n\r as line endings. Some of these files are .py scripts that are run by Apache, which gives an error due to the \r line ending. I can fix these files by running dos2unix and all is well but I was hoping I could avoid this extra step by telling the ACE editor to not add \r. 
I have line 432 in editor.js as:
`aceEditor.getSession().setNewLineMode("auto");`
Am I misunderstanding how this is supposed to work? Is there a way to get the editor to leave the line endings alone?

**Comment by nightwing** [comment]
try using `aceEditor.session.setNewLineMode("unix");` the auto mode detects new line based on initial text or first user input.

**Comment by ifuchs** [comment]
Thanks, but I tried that and it didn’t help.

**Comment by nightwing** [comment]
Maybe something other than ace is converting the new lines to windows style, because the following logs `true`, `false` as expected.
```js
editor = ace.edit(document.body)
editor.setValue("x\r\nx")
console.log(/\r/.test(editor.getValue())) 
editor.session.setNewLineMode("unix")
console.log(/\r/.test(editor.getValue()))
```
