### ISSUE TITLE
Mobile touch selection breaks when horizontal scroll > 0

### ISSUE THREAD

**Issue by radimitrov** [ajaxorg/ace#4279]
Mobile touch selection breaks when left/horizontal scroll > 0 and falls back to scrolling behaviour. Looks like another offset issue.
Link to replicate issue on mobile: [https://output.jsbin.com/pesagufeco](https://output.jsbin.com/pesagufeco)

**Comment by nightwing** [comment]
Thanks for the detailed bug report!
The linked pull request should fix this.
