### ISSUE TITLE
XML Editor highlights incorrect tag when block contains a self-closing tag

### ISSUE THREAD

**Issue by slimjimsoftware** [ajaxorg/ace#4282]
The highlighting of matching start/end tags in the XML editor is incorrect when a block contains a self closing tag.

**Steps to reproduce:**

Add the following XML

```
<anytag>
    <anytag/>
</anytag>
```

Click on the end tag `</anytag>`

**Expected results:**

The `<anytag>` start tag should be highlighted

**Actual results:**

The self-closing embedded `<anytag/>` tag is highlighted.

**Comment by mkslanc** [comment]
Fixed by #4947
