### ISSUE TITLE
something like `lispwords` for correct lisp indentation

### ISSUE THREAD

**Issue by bandaloo** [ajaxorg/ace#4284]
The Clojure indentation seems to indent everything like a function, including `let` and `defun`. In vim, the way you would fix this for a weird/novel lisp syntax is by adding keywords to the `lispwords` option, which is a comma separated list of words. For example, if `weirdly-named-let` were added to `lispwords`, the auto-indent would correctly do this when you hit return:

```
(weirdly-named-let ((x 1) (y 2) (z 3))
  (+ x (* y z)))
```

but if the editor were unaware that `weirdly-named-let` is a keyword and not a function call, it would incorrectly auto-indent the code like this:

```
(weirdly-named-let ((x 1) (y 2) (z 3))
                   (+ x (* y z)))
```

(I'm not sure if Ace already has something like this; if it does I couldn't find any info. I noticed the above behavior in the "kitchen sink" example.)

**Comment by nightwing** [comment]
Maybe `minorIndentFunctions` is the equivalent of `lispwords` https://github.com/ajaxorg/ace/blob/master/lib/ace/mode/clojure.js#L49

**Comment by bandaloo** [comment]
> Maybe `minorIndentFunctions` is the equivalent of `lispwords` https://github.com/ajaxorg/ace/blob/master/lib/ace/mode/clojure.js#L49

yes, i think so! i figured clojure mode have `minorIndentFunctions` populated with more stuff. also, mode/lisp.js doesn't have a similar construct. it also seems like it's repeated across mode/scheme.js. actually, it looks like those files are almost exactly identical apart from the contents of minorIndentFunctions.

i know vim has a "lisp mode" that is totally distinct from the indentation mode for other languages. since this kind of indentation functionality is desirable for pretty much every lisp dialect, maybe it would be useful for `minorIndentFunctions` to be a higher-level abstraction. adding Racket or other dialects would be pretty easy and clean then.
