### ISSUE TITLE
Mobile input inserts "." after space

### ISSUE THREAD

**Issue by radimitrov** [ajaxorg/ace#4287]
Looks like it is caused by mobile input composition seemingly on all Android keyboards.
Steps to replicate:
1. Type anything in editor
2. Press space several times like in the attached video
[Screenrecorder-2020-05-06-22-46-47-379.zip](https://github.com/ajaxorg/ace/files/4589153/Screenrecorder-2020-05-06-22-46-47-379.zip)

**Comment by nightwing** [comment]
Unfortunately some android keyboards interpret two spaces as end of a sentence. And they don't even send a keyCode to allow us to reliably detect why the dot was inserted. 

I am not sure what we should do here. The only way that seems to work is replacing all `.  ` with two spaces https://github.com/ajaxorg/ace/commit/2e24d3997c919be57d328cc656334d2303eb585c, but that seems too hacky.

**Comment by radimitrov** [comment]
Some keyboards do indeed think they know what is best all the time. 

The fix  is good since it does the important part of replacing a syntax breaking "." with a space. Thanks
