### ISSUE TITLE
Rendering format strings in Erlang

### ISSUE THREAD

**Issue by milikhin** [ajaxorg/ace#4290]
In Erlang mode format strings (having `~` symbol) are rendered with left/right margins around `~` .
These margins break monospace rendering and cursor positioning.
For example, `~p` string is rendered as `~   p   `.

I think the issue is somehow connected with the `.ace_placeholder` class being added to the DOM element of a format string, so such strings are rendered similar to text input placeholders.

The issue can be reproduced in the [Ace Kitchen Sink](https://ace.c9.io/build/kitchen-sink.html) using the following file in the Erlang mode: [test.erl.txt](https://github.com/ajaxorg/ace/files/4605240/test.erl.txt)

**Comment by mkslanc** [comment]
Fixed by #5535
