### ISSUE TITLE
tests fail because the request localhost:9000/064e8460-0ef0-4903-a867-7548088308a3 fails

### ISSUE THREAD

**Issue by manuchadha1979** [ajaxorg/ace#4297]
In my application which uses `ace.js`, it seems that `ace` tries to get files from server by code which looks like `blob:http://localhost:9000/064e8460-0ef0-4903-a867-7548088308a3`. This maps to code like `importScripts('http://localhost:9000/ace-builds/worker-html.js');`.

What is `ace` trying to do here? My unit tests randomly fail because server returns `404` for request `blob:http://localhost:9000/064e8460-0ef0-4903-a867-7548088308a3`. 

Could someone please explain to me what is happening under the hood so that I can try to resolve the issue.

**Comment by nightwing** [comment]
ace is trying to load webworker for syntax checking https://github.com/ajaxorg/ace/blob/master/lib/ace/worker/worker_client.js#L53, you can use `session.setOption("useWorker", false)` to disable it

**Comment by manuchadha1979** [comment]
thanks. I tried this  hoping that disabling worker use will stop the error but my test cases still fail :( again around this code `blob:http://localhost:9882/44a520b4-29c6-4c15-94d3-fa5d248266f2`.

**Comment by manuchadha1979** [comment]
I think things work if I disable `loadWorkerFromBlob` but I had to do it inside `ace.js` as none of the following options let me set this configuration. 

Disabling worker option didn't work. It seems `loadWorkerFromBlog` is not effected by this.

`this.editor.session.setOption("useWorker", false);` - Doesn't work

I tried the following as well but I get `misspelled` warning

    ```this.editor.setOptions({
      readOnly: this.readonlyFormStatus,
      loadWorkerFromBlob:false
    });```

Please see detailed explanation here - https://stackoverflow.com/questions/61762954/importscript-and-worker-html-js-are-failing-jasmine-karma-test-cases/61826114#61826114

So that I can understand the concepts of `ace.js` well, can you please explain 
1) Why I might be getting the error at the first place
2) Why `useWorker` didn't work
3) How to disable `loadWorkerFromBlob`

**Comment by nightwing** [comment]
`loadWorkerFromBlob` is a global option, it can be configured with `ace.config.set("loadWorkerFromBlob", false)` . 

Maybe `useWorker` did not work because it was called after worker creation was attempted.

**Comment by manuchadha1979** [comment]
Thanks. It seem to work. Would you know why workers are not working in the unit test?
