### ISSUE TITLE
Line height is too low

### ISSUE THREAD

**Issue by eugen1j** [ajaxorg/ace#4300]
Hello! 

I have a strange behavior of Ace editor on websites. Editor lines overlap each other.

https://ace.c9.io/
![image](https://user-images.githubusercontent.com/36046510/82177307-b5992e80-98e1-11ea-9c72-da885a64a194.png)

https://editor.swagger.io/
![image](https://user-images.githubusercontent.com/36046510/82177343-cd70b280-98e1-11ea-9551-f2e8472aea2b.png)

Here the same problem in Postman:
https://github.com/postmanlabs/postman-app-support/issues/6760

Environment: 
- Chrome Version 81.0.4044.138
- MacOS Catalina 10.15.4

How can I solve this problem?

**Comment by nightwing** [comment]
Hi, this is very strange, seems like line height is not calculated correctly, but i could not reproduce the issue.

Does this happen on firefox too? 

What happens when running `editor.renderer.$textLayer.$fontMetrics.$measureSizes()` in browser console on ace.c9.io ?

**Comment by eugen1j** [comment]
@nightwing 

Chrome:

```
{
    height: 5, 
    width: 7.203125
}
```

![image](https://user-images.githubusercontent.com/36046510/82343087-12d4d300-99fb-11ea-9658-4d6ae1e0a10a.png)


Firefox looks good:

```
 { 
    height: 14, 
    width: 7.19921875 
}
```

![image](https://user-images.githubusercontent.com/36046510/82343368-6ba46b80-99fb-11ea-808e-805ee1961565.png)

**Comment by nightwing** [comment]
Thanks! I am very sorry but i have to ask you for more help, because i don't have any idea what could cause the height of measure node to be smaller than the font size.

Could you try running the following code

```js
console.log(el.getBoundingClientRect())
console.log(el.style.cssText)
el = editor.renderer.$textLayer.$fontMetrics.$measureNode; 
el.style.visibility = "visible"; 
el.style.background="gold"
el.style.zIndex = 10000;
el.parentNode.style.overflow = ""
el.clientHeight
```

and if the above doens't help
```js
editor.container.style.lineHeight=2 
```

Also sometimes issues like this can be caused by browser extensions, could you check if editor works in an incognito tab?

**Comment by eugen1j** [comment]
@nightwing Yes, sure.

I try the following code in an incognito tab with no luck. 

![image](https://user-images.githubusercontent.com/36046510/82368167-a3bca600-9a1d-11ea-826b-90e307dbc126.png)

    editor.container.style.lineHeight=2 

This code helps to expand rows 

![image](https://user-images.githubusercontent.com/36046510/82368295-de264300-9a1d-11ea-85e9-5097fa3fe325.png)

 
Also, I find this bug in Postman https://github.com/postmanlabs/postman-app-support/issues/6760

**Comment by nightwing** [comment]
Interesting, this looks like a bug in chrome.
could you try running `getComputedStyle(editor.container).lineHeight` to see if the value is default "normal" as it should be
Then try to explicitly set line height `editor.container.lineHeight = "normal"` , 
and  then try another font `editor.container.style.fontFamily = "Courier"`, maybe this will help us to isolate minimal testcase that reproduces the issue.

**Comment by eugen1j** [comment]
Yes, `editor.container.style.fontFamily = "Courier"` fixes the problem

![image](https://user-images.githubusercontent.com/36046510/82374834-4a0da900-9a28-11ea-9813-1d2f674bc186.png)


So, how can I set default fontFamily for Chrome and Postman?

**Comment by nightwing** [comment]
Maybe there is a broken/(not supported by chrome) font installed on your computer.  
Try running the following code several times until you find the one which is rendered with 5px height, and then one which is rendered normally.

```js
editor.fonts = editor.fonts || 'Monaco, Menlo, "Ubuntu Mono", Consolas, source-code-pro, monospace'.split(/,\s*/)
editor.container.style.fontFamily = editor.fonts.shift()
```
Then try finding the file for that font. (the file may be useful for submitting to chrome bug tracker)

**Comment by eugen1j** [comment]
Yes, it was a problem with font `Monaco` on my computer. I had two copies of this font, one was broken. I deleted it using `Font Book` for MacOS. Now the editor looks good. 

![image](https://user-images.githubusercontent.com/36046510/82407135-130fb580-9a71-11ea-89b1-b3a074d56ef2.png)

Thank you, @nightwing!

**Comment by nightwing** [comment]
Is there a way you can recover the deleted font file? I think we should report the bug to chrome, because  firefox didn't have a problem with that font.

**Comment by eugen1j** [comment]
@nightwing  I had two copies of font `Monaco`. I suppose Firefox used the first, correct font file. 

The second one looked bad in `Font Book` so it isn't chrome's bug.
