### ISSUE TITLE
Cursor does not flash after inserting content manually

### ISSUE THREAD

**Issue by masbaehr** [ajaxorg/ace#4303]
Hi, i came across this issue. When i do a manual insert

editor.insert("hello world");

the cursor stops flashing and pressing enter causes a duplication of the previous insertion.

Only if i do a manual:

document.getElementsByClassName("ace_text-input")[0].focus();

The cursor starts flashing again. Am i doing anything wrong?

**Comment by nightwing** [comment]
Cursor is not supposed to flash when editor is not focused. If you call editor.insert when user clicks a button, focus may move from editor, call editor.focus() to move focus back to the editor.

**Comment by masbaehr** [comment]
Ok but if that theory is true and - If the editor is not focused. Why does pressing "Enter" cause another insertion?

**Comment by nightwing** [comment]
Interesting, maybe something else goes wrong, but it is hard to tell without more details.

Could you show a page where this is happening? I've tried to replicate the issue with `setInterval(_=>editor.insert("hello world"), 1000)` but it did not stop cursor flashing.
