### ISSUE TITLE
Ace Editor does not show cursor handle on Android chrome

### ISSUE THREAD

**Issue by hexise** [ajaxorg/ace#4304]
I tried ace editor on Android chrome, and found that the cursor handles when selecting text did not show. Here is a screenshot from Galaxy S10 with Android 10, Chrome 81.0.4044.138:

https://ace.c9.io/build/kitchen-sink.html

![cursor-ace](https://user-images.githubusercontent.com/6280560/82983807-ada65200-9fa5-11ea-83fc-225d4bd55f2f.png)

Here is standard text widget from Google translate website, you can notice the cursor handle which I marked in black:

![cursor-google](https://user-images.githubusercontent.com/6280560/82983832-b72fba00-9fa5-11ea-878e-a05415a9a3e1.png)

Without these two touch handles, it is hard to expand or reduce the selection scope on touch screen.

**Comment by hexise** [comment]
I want to keep it open..

**Comment by deadlyjack** [comment]
You can implement it manually. Check out this code I've written mimic android teardrop behavior.

https://github.com/deadlyjack/Acode/blob/main/src/ace/touchHandler.js

**Comment by hexise** [comment]
I want to keep it open.
