### ISSUE TITLE
Replace "\n" and type in "${}"  and \' in python mode.

### ISSUE THREAD

**Issue by xunmeng2015** [ajaxorg/ace#4307]
What can i do to keep the code i type in.
Type in :
![image](https://user-images.githubusercontent.com/15134608/83369843-25cea680-a3f0-11ea-855c-1513c02a7809.png)

After save and reopen i get code below :
![image](https://user-images.githubusercontent.com/15134608/83369853-2d8e4b00-a3f0-11ea-99f0-b0abeadc183d.png)

**Comment by nightwing** [comment]
This is not related to ace, and most likely is caused by incorrect escaping when loading value into the editor. Try doing the same using textarea instead of ace, `textarea.value = ...` instead of `editor.setValue(...)` to verify that the issue is not related to ace.

**Comment by xunmeng2015** [comment]
> This is not related to ace, and most likely is caused by incorrect escaping when loading value into the editor. Try doing the same using textarea instead of ace, `textarea.value = ...` instead of `editor.setValue(...)` to verify that the issue is not related to ace.

Thank you! Just like what you said, after i using textarea instead of ace, it worked.

**Comment by nightwing** [comment]
hmm, i was saying it won't work with textarea too. If you see the issue with ace but not with textarea, could you please show the code with which you initialize ace?

**Comment by xunmeng2015** [comment]
> hmm, i was saying it won't work with textarea too. If you see the issue with ace but not with textarea, could you please show the code with which you initialize ace?

Of course!

Html code:
![image](https://user-images.githubusercontent.com/15134608/83468487-7a852680-a4af-11ea-85a7-aa40e910cd4a.png)

Javascript code:
![image](https://user-images.githubusercontent.com/15134608/83468684-2a5a9400-a4b0-11ea-9261-5a1788036747.png)


And i use `textarea.val()` to get the code. By the way, I use jquery in this jinja2 sample.
