### ISSUE TITLE
How do I subscribe to the scroll event of a marked element?

### ISSUE THREAD

**Issue by zskumar** [ajaxorg/ace#4318]
Hello! I have a number of lines marked(front marker) with a class in the editor. I was hoping to get a callback to the `scroll` event on these lines, but I can't seem to get it working. For the moment, I'm using the "wheel" event and that works. Just wondering why this is happening? 

```JS
element.addEventListener("scroll", e => {
    // Can never hit a break point here. When I debugged this, it looks like ACE handles the scroll event internally?
});
element.addEventListener("wheel", e => {
    // This works.
});
```

**Comment by nightwing** [comment]
What is `element` in this example. If you want an event for editor scrolling use `editor.session.on("changeScrollTop", ...)`

**Comment by zskumar** [comment]
Ah, I should've clarified. `element` in my example is a set of lines marked as `highlightLines`. Code below:

```JS
leftEditor.session.addMarker(new Range(value.LeftStart.line, value.LeftStart.column, value.LeftEnd.line, value.LeftEnd.column), "highlightLines", "fullLine", true); // highlightLines changes the background of these lines to some color
```

Later on, I'm trying to do:
```JS
element = document.getElementsByClassName("highlightLines")[0] as HTMLElement; // This gets me 1 set of highlighted lines
element.addEventListener("scroll", e => {
    // Can never hit a break point here. When I debugged this, it looks like ACE handles the scroll event internally?
});

```

**Comment by nightwing** [comment]
The element created by the marker is an empty div so doesn't have a scrollbar, and doesn't get scroll events.

What do you want to do in the scroll event listener, maybe there is a better way. In general it's better to not modify dom nodes created by the editor because they are not part of the public api, and due to virtual viewport their behavior can be unintuitive.

**Comment by zskumar** [comment]
I see. What I'm trying to do is this:
I have 2 editors in 2 panes in my window: a left editor and right editor with a gutter in between. I have some pairs of lines highlighted in both editors. Each highlighted line has a background of, say blue and opacity of 0.3. When I `mouseenter` the highlighted lines, I change the opacity to 1, and when I `mouseleave, I change the opacity back to 0.3. Also, on `mouseenter` I draw an SVG element in the gutter that connects the highlighted lines in the left and right editors, and on `mouse leave` I delete that svg element. Both are handled by subscribing to the `mouseenter` and `mouseleave`events. The reason I'd like the `scroll` event is to redraw the svg so it connects the right lines (when one editor scrolls, the svg element doesn't connect the original lines perfectly anymore). It's very similar to https://ace-diff.github.io/ace-diff/demos/demo1/ :). Although, now that I played around with ace-diff, it looks like they handle the scroll and svg perfectly, so I can look at their code to see what approach they used. I'd be very interested in hearing your thoughts though @nightwing.

**Comment by zskumar** [comment]
Ah, so ace-diff is working off the editor's `changeScrollTop` event. The real difference is that all the elements are always highlighted so ace-diff can redraw everything, as opposed to what I'm doing where they are highlighted based on if they mouse is inside them. Is there a way to subscribe to the `changeScrollTop` event AND know which element(if any) a mouse is inside of?

**Comment by nightwing** [comment]
Redrawing only the highlighted element is even simpler, you can save the line for the element which needs to be highlighted, and redraw it on scroll.
