### ISSUE TITLE
Dynamic syntax highlighting based on start index and end index of words

### ISSUE THREAD

**Issue by ManojkumarV** [ajaxorg/ace#4323]
I'm having a parser which will parse the content of file and return highlighting rules in the below format.

```
[{
    "name": "UnaryOperator",
    "range": {
        "start": {
            "line": 1,
            "character": 0
        },
        "end": {
            "line": 1,
            "character": 3
        }
    }
}, {
    "name": "PascalCaseWord",
    "range": {
        "start": {
            "character": 3,
            "line": 1
        },
        "end": {
            "line": 1,
            "character": 9
        }
    }
}, {
    "name": "Newline",
    "range": {
        "end": {
            "character": 10,
            "line": 2
        },
        "start": {
            "line": 2,
            "character": 9
        }
    }
}, {
    "name": "PascalCaseWord",
    "range": {
        "start": {
            "line": 2,
            "character": 10
        },
        "end": {
            "line": 2,
            "character": 22
        }
    }
}]
```

Based on the **name** value and **range** value in the objects of the above array syntax highlighting must be applied to the code. 
The above array will get continuously updated as the content of the document is changed.

Is there any way to achieve this in ace editor?

**Comment by nightwing** [comment]
To highlight a line like `foo bar`
ace expects to get an array in the form `[{value: 'foo', type: "keyword"}, {value: ' ', type: "text"}, {value: 'bar', type: "constant"}]`, these tokens are saved in `session.bgTokenizer.lines`.

You can extend https://github.com/ajaxorg/ace/blob/master/lib/ace/background_tokenizer.js to generate array of lines based on the output of the parser.
