### ISSUE TITLE
Can I add virtual lines to the editor?

### ISSUE THREAD

**Issue by zskumar** [ajaxorg/ace#4324]
Hello! I tried searching online, but didn't come up with anything, so I thought I'll ask here. Is there a way to add virtual lines(the lines with stripes) to the editor like the following screenshot?

<img width="370" alt="Screen Shot 2020-06-21 at 2 32 17 PM" src="https://user-images.githubusercontent.com/65389272/85235703-14affe80-b3cc-11ea-9cd3-be990393e372.png">

Note: The virtual lines above line 10 don't increase the line number. Line 9 is above the virtual area.

**Comment by nightwing** [comment]
You can use linewidgets similar to the  [code lens ](https://github.com/ajaxorg/ace/blob/master/lib/ace/ext/code_lens.js#L136) extension.

The api is a bit awkward to use, but with the following you can add 3 empty rows above row 2

```js
var {LineWidgets} = require("ace/line_widgets")
var session = editor.session
if (!session.widgetManager) {
    session.widgetManager = new LineWidgets(session);
    session.widgetManager.attach(editor);
}

widget = session.widgetManager.$registerLineWidget({
    rowCount: 3,
    rowsAbove: 3,
    row: 2,
    column: 0,
})
session._emit("changeFold", {data: {start: {row: 0}}});
```

Are you building a diff viewer with ace?

**Comment by zskumar** [comment]
Awesome, I'll try this out and let you know. Is there a place I can try out what this looks like in the meanwhile?

> Are you building a diff viewer with ace?

Yes, I am!! ACE has been great so far for all my needs! I did find some minor type definitions missing from ace.d.ts (I'm using TS in my project). I'll submit a PR to update them in the near future :)

**Comment by zskumar** [comment]
As a follow up, is it possible to give the line widget a class name so I can style it in the DOM? @nightwing (in case notifications are messed up on closed issues :))

**Comment by nightwing** [comment]
With the example above no elements are rendered in the dom, it is possible to create dom elements and set el property on the widget similar to https://github.com/ajaxorg/ace/blob/v1.4.12/lib/ace/ext/error_marker.js#L133, but a better approach would be to implement to add render listener and create dom nodes only for widgets similar to https://github.com/ajaxorg/ace/blob/v1.4.12/lib/ace/ext/code_lens.js#L153
https://github.com/ajaxorg/ace/blob/v1.4.12/lib/ace/ext/code_lens.js#L46
