### ISSUE TITLE
When I set wrap: true, a lot of question marks are displayed. I can't find the reason

### ISSUE THREAD

**Issue by lenosp** [ajaxorg/ace#4325]
When I set wrap: true, a lot of question marks are displayed. I can't find the reason. The configuration and display are as shown in the figure below:

edit= ace.edit("editor", {
					theme: "ace/theme/eclipse",
					mode: "ace/mode/javascript",
					wrap: true,
					selectionStyle: "text",
					autoScrollEditorIntoView: true,
					enableBasicAutocompletion: true,
					enableSnippets: true,
					enableLiveAutocompletion: true,
					showPrintMargin:false,
				});
![image](https://user-images.githubusercontent.com/18375648/85242229-07008480-b471-11ea-84a7-6f8b338cf8ef.png)

If I manually wrap the line, the question mark disappears，As shown below：
![image](https://user-images.githubusercontent.com/18375648/85242275-2dbebb00-b471-11ea-8aa9-c3cb314eeafb.png)
I don’t know if it’s my configuration problem。

**Comment by nightwing** [comment]
looks like something changes the code at https://github.com/ajaxorg/ace-builds/blob/master/src/ace.js#L16583  while serving the file .

Does the same happen when you load ace from http://ajaxorg.github.io/ace-builds/src-noconflict/ace.js?
