### ISSUE TITLE
Copying multiple lines within Firefox is broken?

### ISSUE THREAD

**Issue by adamroyjones** [ajaxorg/ace#4326]
I am able to reliably reproduce this issue with Firefox 77.0.1 on both Ubuntu 20.04 and macOS 10.15.5. This issue does not occur with Chromium (and so presumably not with Chrome).

On the [demonstration site](https://ace.c9.io/build/kitchen-sink.html), selecting all of the text and copying it only inserts the following onto the clipboard:

```
    }	// Real Tab.
}
```

Related issues arise with other multiline selections; single-line selections seem to be fine.

Are you able to reproduce this issue?

**Comment by nightwing** [comment]
This issue can be caused either by an extension like https://addons.mozilla.org/en-US/firefox/addon/don-t-fuck-with-paste/ or by the about:config setting `dom.event.clipboardevents.enabled` being set to false. 

Both of these break the clipboard api, so only the  small amount of text kept in the hidden textarea is copied.

**Comment by adamroyjones** [comment]
My hero!

It was indeed because `dom.event.clipboardevents.enabled` was set to false. (Some sites I visit abuse this to insert crud into the clipboard.)

Thanks for the help—hopefully anyone else who has this problem can find it here, amongst the issues.

**Comment by lokesh1729** [comment]
i do not know but somehow the property `dom.event.clipboardevents.enabled` was set to false. I did not set this, does any of the extensions can set this property ? sorry, i am not aware of firefox addons but does firefox allows addons to modify these properties ?

**Comment by adamroyjones** [comment]
@lokesh1729 It is not possible: https://stackoverflow.com/questions/50023416/is-it-possible-to-create-a-firefox-webextension-that-changes-aboutconfig-settin.

**Comment by nightwing** [comment]
It could be changed by the old extensions though, was this on a new firefox installation or several years old?
