### ISSUE TITLE
Text can be blurry after scrolling

### ISSUE THREAD

**Issue by lid** [ajaxorg/ace#4328]
# Type of issue (choose one):
  - [X] Bug
  - [ ] Feature request
  - [ ] Question

### Description

After scrolling in either [Ace Kitchen Sink](https://ace.c9.io/build/kitchen-sink.html) or [Caret](https://github.com/thomaswilburn/Caret) (a downstream project), the text sometimes appears to be more blurry, depending on where the scroll is stopped. Other code editors (e.g. CodePad) and webviews do not exhibit this behavior. Could this be the result of an undesirable antialiasing behavior?

Before scrolling:
![not-blurry](https://user-images.githubusercontent.com/831121/82750122-63a74b80-9dae-11ea-821b-680382a1c42c.png)

After scrolling:
![blurry](https://user-images.githubusercontent.com/831121/82750126-643fe200-9dae-11ea-8e07-9bc1cae1e588.png)

### Additional notes

Originally filed downstream: https://github.com/thomaswilburn/Caret/issues/729
Potentially related issues: https://github.com/ajaxorg/ace/issues/3081, https://github.com/nos/client/issues/376

### System details
ChromeOS | 84.0.4147.64 (Official Build) beta (64-bit)

**Comment by nightwing** [comment]
On windows similar issue was happening with because of css transform.

Could you try running `require("ace/lib/dom").HI_DPI` to see if ace is using css transforms or absolute positioning in this case.

**Comment by lid** [comment]
```
> require("ace/lib/dom").HI_DPI
< true
```

**Comment by nightwing** [comment]
Does it look better on http://raw.githack.com/ajaxorg/ace/fix-blurred-text-on-chromeos/kitchen-sink.html ?

**Comment by lid** [comment]
Thanks for the quick attempt at a fix! However, the githack seems to be about the same, TBH.

Clear before scroll:
![Clear before scroll](https://user-images.githubusercontent.com/831121/86542159-694a9200-bf13-11ea-83bd-b3b811df7b7a.png)

Blurry after scroll:
![Blurry after scroll](https://user-images.githubusercontent.com/831121/86542163-6e0f4600-bf13-11ea-8a2f-5b4412bdeefe.png)

**Comment by nightwing** [comment]
could you also run `require("ace/lib/dom").HI_DPI` again to see if the change have actually switched it to false?

**Comment by lid** [comment]
I'm afraid it didn't change on githack, I get the same console result:

```
> require("ace/lib/dom").HI_DPI
< true
```

**Comment by nightwing** [comment]
Thanks, could you try if http://raw.githack.com/ajaxorg/ace/4e96653032f248a87d879d7d28cddd5e196d6ecf/kitchen-sink.html fixes the issue
and if it doesn't what is the output of `window.devicePixelRatio` and  `require("ace/lib/useragent").isChromeOS`

**Comment by lid** [comment]
It's fixed with that latest githack! Thank you!
