### ISSUE TITLE
[Question] Snippets dropdown

### ISSUE THREAD

**Issue by Burkino** [ajaxorg/ace#4333]
I'm not exactly sure what this is called but I hope pictures can explain it well enough.

So in Monaco when you use snippets you can create a dropdown of options such as this.
![image](https://user-images.githubusercontent.com/24849979/86414256-6d677d00-bc91-11ea-9365-2cd61bcf1276.png)

However in Ace, these options just don't show up.
![image](https://user-images.githubusercontent.com/24849979/86414307-8ec86900-bc91-11ea-8182-edb380e9d2e3.png)

So I was wondering if it would be possible to make the options show up? I may be doing something wrong.
```
snippet GetService
	local ${1} = game:GetService("${1|AssetService,BadgeService,ChangeHistoryService,CollectionService,ContextActionService,DataStoreService,GamepadService,GamePassService,GroupService,GuiService,HapticService,HttpService,InsertService,JointsService,LocalizationService,LogService,MarketplaceService,MessagingService,PathfindingService,PhysicsService,PluginGuiService,PolicyService,RunService,ServerScriptService,SocialService,SoundService,StudioService,TeleportService,TestService,TextService,TweenService,UserInputService,VRService,Workspace|}")
```

**Comment by nightwing** [comment]
does the version from attached pull request work the way you'd expect?
You can try it from http://raw.githack.com/ajaxorg/ace/fix-snippet-choices-popup/kitchen-sink.html, using edit snippets button.

**Comment by Burkino** [comment]
Yes that version does work. Thank you so much!
![image](https://user-images.githubusercontent.com/24849979/86486033-4740ec00-bd28-11ea-9d61-c641a04ec957.png)
