### ISSUE TITLE
Editor treat new line'\n' character as a normal charactor

### ISSUE THREAD

**Issue by lhf552004** [ajaxorg/ace#4335]
Hi I'm developing our custom markdown editor.

When I add '\n' before and after selected text .
`textToInsert = '\n' + textToInsert +'\n\n';`
Then I move cursor to line 7, 
![image](https://user-images.githubusercontent.com/10030850/86523920-35855300-bea6-11ea-898f-8155c820b242.png)
and get line. I have the line contains the '\n' character.  the range is {start: {row: 6, column: 0}, end: {row: 7, column: 0})
The selected text is
```
 "1. Ordered List
"
```
![image](https://user-images.githubusercontent.com/10030850/86523944-77ae9480-bea6-11ea-9f4a-429814aeffbe.png)

Actually, I expect to get single line at row 6.
How to fix it?
Thanks

**Comment by nightwing** [comment]
selectLine selects the newline as well, use the second parameter to getLineRange method, or construct the range separately to not select it
```js
// pass null  instead of row to select cursor line 
range = editor.selection.getLineRange(row, true) 
editor.selection.setRange(range)
```

**Comment by lhf552004** [comment]
@nightwing ,thanks. it works
