### ISSUE TITLE
Permission to use

### ISSUE THREAD

**Issue by foozzi** [ajaxorg/ace#4337]
Hi, in our project https://github.com/schenkd/nginx-ui we would like to use your tool for editing server configurations. Your license says we need written permission.

ace@c9.io is not receive mails...

**Comment by nightwing** [comment]
Hi,
we are using [BSD license](https://github.com/ajaxorg/ace/blob/master/LICENSE) which does **not** require any permission for use .

The part about written permission is only about using the name: that is if you fork the editor, and distribute it as a new editor, you can't call the forked version ace without permission.
