### ISSUE TITLE
CSS transforms cause horizontal scroll

### ISSUE THREAD

**Issue by samuei** [ajaxorg/ace#4345]
With `transform: scale(1.8)` and `transform-origin: 0px 0px 0px` on the body, I'm noticing that selecting the Ace editor sometimes forcibly jumps the horizontal scroll for the page all the way to the left. Since my editor is out of view from the far left at that scale, this is disruptive for users. It only seems to occur on the initial click or when something other than the editor has been clicked last, which suggests that it might have something to do with a focus event.

Do you know what's going on?

I have the `hasCssTransforms` property set to `true`, but the issue still presents. 

Adding the CSS transforms to the body in the About page displays the issue as well, so it's not just something in my application.

**Comment by nightwing** [comment]
Is the autoScrollEditorIntoView option enabled too? looks like transform interferes with `window.innerHeight`  caomparision in https://github.com/ajaxorg/ace/blob/master/lib/ace/editor.js#L2812

**Comment by samuei** [comment]
It is.

Is there a workaround, or do I need to choose one or the other?

**Comment by samuei** [comment]
I had a bit more time to look at this. Seems like it's still happening with `autoScrollEditorIntoView` disabled. We do have `highlightActiveLine` enabled, which I suppose is also dealing with positioning. Not sure why it would cause _horizontal_ scrolling, though.

**Comment by nightwing** [comment]
The issue with autoScrollEditorIntoView is a bug, i'll try to fix it in the next version, but highlightActiveLine is not related to scrolling into view. 

On which browser do you see this behavior, and does that happen on mousedown, or when changing selection in some other way? 
Some browsers try to scroll textarea into view when it is [focused](https://github.com/ajaxorg/ace/blob/master/lib/ace/keyboard/textinput.js#L109), which  can be related to this issue.

**Comment by samuei** [comment]
I'm seeing it in Firefox. It's definitely whenever the Ace editor gains focus (initial click and first click after something else on the page has been clicked), but it is still happening after I've disabled autoScrollEditorIntoView.

**Comment by cnandibatla** [comment]
We are still having this issue and would like a fix for autoScrollEditorIntoView in the new version.
