### ISSUE TITLE
Is 'keepRedoStack' not needed anymore?

### ISSUE THREAD

**Issue by AlexHolly** [ajaxorg/ace#4356]
related: https://github.com/ajaxorg/ace/issues/4024

I noticed that 'keepRedoStack' has no effect anymore.  Did something change, can it be removed?

version: https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.12/ace.js

https://codepen.io/alexholly/pen/qeOBMa

**Comment by nightwing** [comment]
The `$keepRedoStack` still has effect, in the following example with true the output will be `ab  c` and with false `a  c`

```js
editor.session.getUndoManager().$keepRedoStack =  true 
editor.setValue("  ", -1)
editor.insert(`a`);
editor.session.markUndoGroup()
editor.insert(`b`);
editor.session.getUndoManager().undo();
editor.navigateFileEnd()
editor.insert(`c`);
editor.session.markUndoGroup()
editor.session.getUndoManager().redo(); 
```

**Comment by AlexHolly** [comment]
Can you add it as an option?

var editor = ace.edit("editor", {
  $keepRedoStack : false
});
