### ISSUE TITLE
Pressing backspace removes two characters

### ISSUE THREAD

**Issue by DiamondDemon669** [ajaxorg/ace#4357]

**Comment by nightwing** [comment]
On which OS and browser does this happen, if this happens on mobile which keyboard is used?

**Comment by meteorlin** [comment]
It happends on Windows 10 PC. The browser is Chrome and it doesn't happen on IE Edge.

**Comment by meteorlin** [comment]
I suddenly discovered that after disabling the "Tampermonkey
4.8.41" Chrome plug-in, the problems including "pressing the Tab key will automatically jump to the next HTML element" and "pressing the Backspace key once will delete two characters at the same time" have been solved.
