### ISSUE TITLE
DragDrop handler "blankImage" content security policy issue 

### ISSUE THREAD

**Issue by Lmbrtz** [ajaxorg/ace#4364]
Hey there,

the [drag-drop handler](https://github.com/ajaxorg/ace/blob/6933ab5202ca90b07b1d58a6b016c70f13d310eb/lib/ace/mouse/dragdrop_handler.js) appears to cause issues if there is a "img-src 'self'" content security policy in place:

> Refused to load the image [...] because it violates the following Content Security Policy directive

Is there a way to prevent this error without changing the content security policy?
A couple of other images loaded can simply be unset via CSS, but this one can't be replaced so easily because it's loaded even if it's not added to the DOM.
Any advice?

Would it make sense to add some option to disable all images and/or specify custom ones?

**Comment by nightwing** [comment]
Seems like it is possible to replace this image with a simple dom node which would also allow to show the dragged text, but not sure what can be done with other images.
