### ISSUE TITLE
Current word in cursor

### ISSUE THREAD

**Issue by PonomarenkoDeniss** [ajaxorg/ace#4372]
Hello!

I have this example code:
```
function_name()
```
When I have cursor in arguments I want to add hint with argument list.
For this i need to get function name.

How to do this?

**Comment by YellowAfterlife** [comment]
You would want to use a token iterator to step backwards from the current token until you hit ( and then an identifier.

I have implemented such a feature in an open-source Ace-based code editor I made,
![image](https://user-images.githubusercontent.com/731492/91664376-8fe20f00-eaf7-11ea-8106-4ef23543fcdb.png)
though there's obviously some additional logic here
https://github.com/GameMakerDiscord/GMEdit/blob/5af347d3ce5f1a034f8b0124007230fa83ed63fe/src/ace/AceStatusBar.hx#L199
