### ISSUE TITLE
Ace Editor Auto Completer exactMatch

### ISSUE THREAD

**Issue by Govind85** [ajaxorg/ace#4375]
Hi Team,
I am trying to add completer which can match the word which user has typed and return the exact matches. 
For example:- List is [‘Apple’, ‘Application’, ‘Aeroplane’, ‘Ace’].
If user types ‘ap’. The autocomplete should return [‘Apple’, ‘Application’] but it is returning [‘Apple’, ‘Application’, ‘Aeroplane’]

**Comment by mahdi943** [comment]
> Hi Team,
> I am trying to add completer which can match the word which user has typed and return the exact matches.
> For example:- List is [‘Apple’, ‘Application’, ‘Aeroplane’, ‘Ace’].
> If user types ‘ap’. The autocomplete should return [‘Apple’, ‘Application’] but it is returning [‘Apple’, ‘Application’, ‘Aeroplane’]

Hi,
I am using Ace editor in my project for Gherkin syntax. I have already implemented existing ace autocomplete but it just suggests current words in the editor; I need to add my custom list for Autocompletion.
How can I do that?
Thanks.

**Comment by Govind85** [comment]
You can use editor.completers.push(yourCustomCompleter)
  let yourCustomCompleter = {
          getCompletions: function (editor, session, pos, prefix, callback, isRHSEditor) {
            callback(null, this.customList.map(function (column) {
              return {
                caption: "What ever you want the user to see when they type any keyword",
                value: "What ever you want in the editor when they select any caption",
                meta: 'Completer Type',
              }
            }))
          }
        }
        
        Please let me know if this fixs your issue.

**Comment by Govind85** [comment]
runEditor.on('input', function (e) {
        if (runEditor.completer && !runEditor.completer.exactMatch) {
          runEditor.completer.exactMatch = true
          runEditor.completer.completions.exactMatch = true
        }
      })
      
      I was able to fix it by myself using above code.

**Comment by Govind85** [comment]
@mahdi943 My comment was of any help?

**Comment by mahdi943** [comment]
I have fixed the issue before but I really appreciate your help.

**Comment by mahdi943** [comment]
> Hi Team,
> I am trying to add completer which can match the word which user has typed and return the exact matches.
> For example:- List is [‘Apple’, ‘Application’, ‘Aeroplane’, ‘Ace’].
> If user types ‘ap’. The autocomplete should return [‘Apple’, ‘Application’] but it is returning [‘Apple’, ‘Application’, ‘Aeroplane’]

Are there any solution for exactMatch? I also need this option

**Comment by Govind85** [comment]
runEditor.on('input', function (e) {
if (runEditor.completer && !runEditor.completer.exactMatch) {
runEditor.completer.exactMatch = true
runEditor.completer.completions.exactMatch = true
}
})

This will enable exact match.
