### ISSUE TITLE
Problem with hindy language

### ISSUE THREAD

**Issue by Cobr3n** [ajaxorg/ace#4376]
Hello can u fix it? 
type in editor **अपार्टमेंट** and try edit
![image](https://user-images.githubusercontent.com/25749976/92557349-39629680-f296-11ea-8fcd-cba4e457d391.png)

**Comment by AlexRAV** [comment]
Same issue. Is there workaround?

**Comment by Cobr3n** [comment]
for example in codemirror works fine, but your plugin is much faste

**Comment by Cobr3n** [comment]
Hello anybody help me ?
