### ISSUE TITLE
Question. How to show autocomplete for functions

### ISSUE THREAD

**Issue by Kagayakashi** [ajaxorg/ace#4379]
Hello. 

I have system with ace editor and internal ready to use functions and constants.

For example.
1) `var sb_const = ['#user', '#now'];`
1) `var sb_functions = ['create_user(data_array)', 'create_object(process, group)', 'select_users(filter, roles)'];`

I already made autocompletion for constants like this:

```
var custom_completer = {
    getCompletions: function(editor, session, pos, prefix, callback) {
        var sb_const = ['#user', '#now'];
        callback(null, [
            ...sb_const.map(function(word) {
                return {
                    caption: word,
                    value: word,
                    meta: 'constant',
                };
            })
        ]);
    }
};
editor.completers.push(custom_completer);
```

Now I need to do the same for functions. But I also want to show function parameters.
For example, function `select_users` have two parameters `select_users(filter, roles)`.
When user write in editor function, I want to show parameters and highlight them like in this picture:
![image](https://user-images.githubusercontent.com/15884480/93346952-37bc4400-f83d-11ea-9f7c-04c3c7d7d11d.png)

How to do this?

P.S. All functions are system-internal and they are ready to use.

hope for fast response.

**Comment by mahdi943** [comment]
> Hello.
> 
> I have system with ace editor and internal ready to use functions and constants.
> 
> For example.
> 
> 1. `var sb_const = ['#user', '#now'];`
> 2. `var sb_functions = ['create_user(data_array)', 'create_object(process, group)', 'select_users(filter, roles)'];`
> 
> I already made autocompletion for constants like this:
> 
> ```
> var custom_completer = {
>     getCompletions: function(editor, session, pos, prefix, callback) {
>         var sb_const = ['#user', '#now'];
>         callback(null, [
>             ...sb_const.map(function(word) {
>                 return {
>                     caption: word,
>                     value: word,
>                     meta: 'constant',
>                 };
>             })
>         ]);
>     }
> };
> editor.completers.push(custom_completer);
> ```
> 
> Now I need to do the same for functions. But I also want to show function parameters.
> For example, function `select_users` have two parameters `select_users(filter, roles)`.
> When user write in editor function, I want to show parameters and highlight them like in this picture:
> ![image](https://user-images.githubusercontent.com/15884480/93346952-37bc4400-f83d-11ea-9f7c-04c3c7d7d11d.png)
> 
> How to do this?
> 
> P.S. All functions are system-internal and they are ready to use.
> 
> hope for fast response.

Hi,

I am using Ace editor in my project for Gherkin syntax. I have already implemented existing ace autocomplete but it just suggests current words in the editor; I need to add my custom list for Autocompletion.
How can I do that?
Can you help me where can I add my own list?

Thanks.
