### ISSUE TITLE
Auto line wrap

### ISSUE THREAD

**Issue by mehq** [ajaxorg/ace#4380]
Is there a way to force line wrap only if line length is exceeding width of the container?

**Comment by nightwing** [comment]
use `editor.setOption("wrap", true)`

**Comment by mezba1** [comment]
> use `editor.setOption("wrap", true)`

I've tried that but lines are capped at 80 characters. The container is quite big and theres a lot of unused spaces. I need to fill the remaining spaces and only wrap after that.

**Comment by nightwing** [comment]
There must be something in your code setting wrap either to 80 or to "printMargin", or editor may be not sized correctly.
To see that try running the following code on https://ace.c9.io/
```js
var editor = ace.edit(null, {
   wrap: true,
   value: "a".repeat(160)+"b".repeat(1600), 
   fontSize: 8
})
document.body.textContent=""
document.body.appendChild(editor.container)
editor.container.style.width = "800px"
editor.container.style.height = "100px"
editor.container.style.position = "absolute"
editor.container.style.zIndex = Number.MAX_SAFE_INTEGER
editor.resize(true)
```

You should see editor with wrapped text, and wrapping should start at the end of the string of `a`s, closer to the 160.

If you show me a page where `editor.setOption("wrap", true)` doesn't work, i can help you to debug it.
