### ISSUE TITLE
update bundled CSS lint tool

### ISSUE THREAD

**Issue by kevinushey** [ajaxorg/ace#4391]
Right now, Ace uses a fairly old version of CSSLint for diagnostics in CSS files, from 2014:

https://github.com/ajaxorg/ace/blob/master/lib/ace/mode/css/csslint.js

However, this version of CSSLint doesn't understand many modern CSS constructs; e.g. CSS properties or variables.

<img width="215" alt="Screen Shot 2020-10-07 at 9 11 17 AM" src="https://user-images.githubusercontent.com/1976582/95357703-115a5900-087d-11eb-9161-a299fceb00be.png">

It looks like CSSLint is now only sparsely maintained:

https://github.com/CSSLint/csslint

stylelint appears to be a more modern replacement:

https://github.com/stylelint/stylelint

It might be worth considering upgrading the bundled CSS linter.

**Comment by STaRDoGG** [comment]
was anything ever done (or planned) with this?

This is severely affecting my coder OCD: :p

![image](https://user-images.githubusercontent.com/1524526/148696909-702fcf3a-417d-4047-9811-08fb7c7e7760.png)

**Comment by bogger33** [comment]
Definition of custom properties, as in your screenshot, should already be fixed by my accepted pull request here (which I believe is included in the latest release already):

https://github.com/ajaxorg/ace/pull/4465

I've also just submitted one that will allow var() to be recognized as a valid property value anywhere

**Comment by andrewnester** [comment]
CSSlint is already updated, closing this issue

**Comment by In1quity** [comment]
@andrewnester Hello! The CSSLint was replaced by an stylelint? :)

**Comment by andrewnester** [comment]
@In1quity no, we haven't replaced CSS lint, feel free to send a PR for this
