### ISSUE TITLE
html/ css/ js highlighting in php mode

### ISSUE THREAD

**Issue by adamjimenez** [ajaxorg/ace#44]
syntax highlighting for html/ css and js in php mode.
@gissues:{"order":94.40993788819878,"status":"backlog"}

**Comment by PaykomanVll** [comment]
Hello,

im new on ACE and i need it too, for Tmplates, is better when highlite "php, css, html" on same time...
How i must make to can use "editor.session.setMode("ace/mode/oop");" for multiple Highliting???

I use ACE as build, i have read your comment (fjakobs) but i understand not =(

Im very happy anyone can tell me step by step.

**Comment by nightwing** [comment]
use `editor.session.setMode("ace/mode/php");` not `/oop`

**Comment by PaykomanVll** [comment]
lol, i know, but this is only for php, the issue is Highlite more as one language o.O
