### ISSUE TITLE
.isClean() is false after setValue, even after editor.session.getUndoManager().markClean();

### ISSUE THREAD

**Issue by JamesNewton** [ajaxorg/ace#4403]
Something is calling `editor.on("input"` but NOT calling `editor.session.on("change"` after doing:
````
      editor.setValue(responseText);
      editor.clearSelection();
      editor.session.getUndoManager().markClean();
````
and it is making the `.isClean()` return false. So I can't load a file, and then load _another_ file without saving the first one, even if I didn't make any change. My code to load in a new file is:

````
    if(status == 200) { //console.log("Content:",responseText.substr(0,11))
      if (responseText.substr(0,11) == "#!/bin/bash") { console.log("bash")
        editor.getSession().setMode("ace/mode/sh")
        }
      editor.setValue(responseText);
      editor.clearSelection();
      editor.session.getUndoManager().markClean();
      console.log("marked clean")
      if (editor.session.getUndoManager().isClean()) { console.log("is clean")}
      editor.savefile.style.color="black"
      setTimeout(function(){editor.session.getUndoManager().markClean();console.log("again");},1000)
      }
````

My code for the `editor.session.on("change"` will `console.log("changed")` and the `editor.on("input"` will `console.log("input")`. When I load a new file, in the console I see:
````
marked clean
is clean
input
again
````
Note that "changed" doesn't show up in there. If I type anything in the document, it does log "changed". 

I'll keep pounding on this because setTimeout is such a hack, but wanted to report it in case anyone else was trying to come up with something that warns users when they are about to load a new file without saving the old one.

**Comment by nightwing** [comment]
It's hard to tell what is the issue from this snippet of code because when running it in browser console on https://ace.c9.io/, the session is marked as clean as expected.

But if you need to load multiple files, a good way to do that would be to use separate sessions for each file 

```js
var session = new EditSession(value);
session.setUndoManager(new UndoManager());
sessions[path] = session;
editor.setSession(session);
```

**Comment by JamesNewton** [comment]
`ReferenceError: EditSession is not defined`

**Comment by JamesNewton** [comment]
Ah. My bad. The issue was apparently related to accidentally using a very old version of ace. It was finding a 1.2.6 version instead of the current 1.4.12. When I figured that out and updated the correct file, it all started working without the set timeout. 

So if anyone else runs into this, make sure you have the right version.

**Comment by nightwing** [comment]
EditSession and UndoManager can be  accessed from ace `var {EditSession, UndoManager}` or you can use the `ace.createEditSession` method. using setValue to switch files will break the undo history.

**Comment by JamesNewton** [comment]
In `sessions[path] = session;`
- Where do I get `sessions` from and 
- what is `path`?

Just so you know, I have been all through the API docs and I don't see anything called sessions. 

Are those things you are assuming I have in my code?

**Comment by JamesNewton** [comment]
Just for future reference, what I ended up with and what seems to work is:
````js
    var session = ace.createEditSession(""); //https://github.com/ajaxorg/ace/issues/4403
    editor.setSession(session);
````
And then I make an ajax call to get the text of the document from the server and
````js
      editor.setValue(responseText);
      editor.clearSelection();
      editor.session.getUndoManager().markClean(); 
````

And that final markClean() probably isn't required. The first part, making a new session and setting it into the editor, appears to have been the key. I'm not assigning a value to the session when created because I want a new session made before the attempt to load the file, so that if that fails, the prior session isn't still in there. And I set the mode after the file content shows up, so I can do things like:
````js
      if (responseText.substr(0,11) == "#!/bin/bash") { console.log("bash")
        editor.getSession().setMode("ace/mode/sh")
        }
````
