### ISSUE TITLE
CLA links 404 -- file has been deleted

### ISSUE THREAD

**Issue by MysterAitch** [ajaxorg/ace#4405]
Hi,

The two links to the individual/corporation CLAs link to a deleted file:

![image](https://user-images.githubusercontent.com/1537214/97589466-6d844900-19f5-11eb-9725-8fb813870d81.png)

https://github.com/ajaxorg/ace/blob/master/CONTRIBUTING.md

https://github.com/ajaxorg/ace/blob/a505922a01395ab77a878c08da06eb09b7822d23/CONTRIBUTING.md#L10-L11

**Comment by nightwing** [comment]
Thanks for reporting this. CLAs are not needed anymore, instead of them leaving the text in  [.github/PULL_REQUEST_TEMPLATE.md](https://github.com/ajaxorg/ace/blob/master/.github/PULL_REQUEST_TEMPLATE.md) when creating pull request is enough. We'll remove mention about CLAs from CONTRIBUTING.md.

**Comment by tapdiego-amzn** [comment]
https://github.com/ajaxorg/ace/blob/master/CONTRIBUTING.md still contains the dead links.

**Comment by andrewnester** [comment]
Links are removed now
