### ISSUE TITLE
Vim keybindings do not scroll to the selected line on `:n`

### ISSUE THREAD

**Issue by jyn514** [ajaxorg/ace#4412]
When I select a line that's out of the range of the screen, the cursor will move but the viewport won't, so the cursor can end up outside the screen.

Steps to reproduce: go to https://play.rust-lang.org/?version=nightly&mode=release&edition=2018&gist=e59b183cd5eeeea326a6864c56aa5ad0 and hit `:50`.

_Originally reported by @jyn514 at https://github.com/integer32llc/rust-playground/issues/646._

**Comment by jyn514** [comment]
This is still an issue with the current version of ace.

**Comment by andrewnester** [comment]
Released in 1.13.2
