### ISSUE TITLE
Jinja2 Mode

### ISSUE THREAD

**Issue by PythonLinks** [ajaxorg/ace#4413]
I can't seem to find a Jinja2 mode. 
There is a closed issues thread on Jinja2 here from 2014.  They talk about a Django Mode, but since Django supports both Django Templates, and Jinja2 templates,  I assume that they are different. 

A Google search also did ot reveal anything. 

Ace is so awesome, it must have a Jinja2 mode. 

What am I doing wrong?

**Comment by jurkov** [comment]
Maybe the nunjucks mode will meet your requirements: https://github.com/django-ace/django-ace/blob/main/django_ace/static/django_ace/ace/mode-nunjucks.js
