### ISSUE TITLE
Autocomplete not working in mobile

### ISSUE THREAD

**Issue by merbin2012** [ajaxorg/ace#4420]
In the ace editor, everything is working perfectly on mobile devices, except Autocomplete option. This is not working in Ace-kitchen-sink also. Kindly check the error and fix it as soon as possible. Thank you.

**Comment by nightwing** [comment]
On which OS and which keyboard do you see this issue? I couldn't reproduce it on galaxy note with samsung keyboard.

**Comment by merbin2012** [comment]
Os android and google keyboard. Thanks for your reply.

**Comment by zoubaihan** [comment]
Hi, dear friend, I am also considering to use popup.js to complete my code, but when I add the code below into my html file:
<script src="ace/autocomplete/popup.js" type="text/javascript" charset="utf-8"></script>
The browser remind me that there throws an error:
![image](https://user-images.githubusercontent.com/60840371/109273615-64917000-784d-11eb-8837-6fe453b91931.png)
How can I use this autocomplete function, could you please teach me?

**Comment by merbin2012** [comment]
@zoubaihan use popup.js, already it is in the package.
