### ISSUE TITLE
scrollToLine animate slower

### ISSUE THREAD

**Issue by terrencekuo** [ajaxorg/ace#4421]
the scrollToLine function allows users to animate scrolling. 

Is there an func available to change the speed of the scrollToLine animation?
i.e the scrollToLine function takes 10s instead of 10ms

**Comment by nightwing** [comment]
There is no public api for this, but it is possible to change the STEPS constant used for animation, or to override editor.renderer.$calcSteps method to use different animation function

```js
editor.setOption(editor.$options.animatedScroll.name, true)
editor.renderer.STEPS = 1000
editor.scrollToLine(0, 0, true, console.log)
editor.renderer.STEPS = 8
```

It is also possible to use scrollBy without using  scrollToLine https://github.com/ajaxorg/ace/blob/master/lib/ace/mouse/touch_handler.js#L330

**Comment by terrencekuo** [comment]
thank you @nightwing

this worked perfectly!

`editor.setOption(editor.$options.animatedScroll.name, true)` works better than `editor.setAnimatedScroll(true)`

which file in the acejs library did you look at to find `editor.renderer.STEPS` and `setOption(editor.$options.animatedScroll.name, true)`?

**Comment by ldijkman** [comment]
Thank you 
this works nice
editor.setOption(editor.$options.animatedScroll.name, true);

https://codepen.io/ldijkman/pen/poqbbqa

![2023-09-03-060039_1920x1080_scrot](https://github.com/ajaxorg/ace/assets/45427770/9501bbee-5e39-4119-8091-f9e3f1b2da97)
