### ISSUE TITLE
the toUpperCase function works but the toggleCommentLines does not work

### ISSUE THREAD

**Issue by kegilko** [ajaxorg/ace#4427]
I am from Symfony 5 and webpack encore, I use ace-builds with the version 1.4.12

Given a webpage with an ace editor bloc (containing some code lines). On pageLoad, I want to automatically upperCase and comment the lines 1 to 2. 

I instantiate the ace editor simply like this : 

```javascript
let editor = ace.edit(editorElement); // editorElement is an html element containing some code lines
editor.setOptions({
    maxLines: Infinity,
});
editor.getSession().setMode("ace/mode/python");
```

And this is the code executed after the pageLoad : 

```javascript
require('ace-builds');
require('ace-builds/webpack-resolver'); // my project is managed by symfony 5 and webpack encore

let Range = require('ace-builds').Range;
editor.getSelection().setRange(new Range(0,0,2,0));

editor.toggleCommentLines(); // does nothing...why ?
editor.toUpperCase(); // its work !
// editor.clearSelection();
```

The result is : 

[![enter image description here][1]][1]

The lines 1 and 2 are in upperCase as expected, but the lines aren't commented and I don't understand why...

I don't won't "just" add a '#' char because the mode of the generated ace editor may change. By example, the mode may be 'ace/mode/sql', and the comment in sql don't use the '#' char 

Thanks for any help :) 

  [1]: https://i.stack.imgur.com/RoHGb.png

**Comment by nightwing** [comment]
Maybe when you call toggleCommentLines the mode is not loaded yet. 

try 

```
editor.session.setMode("ace/mode/python", function() {
    editor.toggleCommentLines();
});
```

Or load the mode file via require or script.

**Comment by kegilko** [comment]
Ho ! its works with 

```
editor.session.setMode("ace/mode/python", function() {
    editor.toggleCommentLines();
});
```
I understand my mistake
Thank you :)
