### ISSUE TITLE
Configuring rules for worker-html

### ISSUE THREAD

**Issue by dsl101** [ajaxorg/ace#4430]
This might just be not understanding how to configure the html mode, but I'm trying to use it for validating snippets of HTML, not entire documents (in a UI). I'd like to get rid of the info `Start tag seen without seeing a doctype first. Expected e.g. <!DOCTYPE html>.` which always shows on line 1.

Via Stackoverflow, I see it's possible to call this function in worker-css:
```
editSession.$worker.call('setDisabledRules', [DISABLED_RULES.join('|')])
```
I can't find an equivalent to 'disable' the `expected-doctype-but-got-start-tag` rule in worker-html. Is it possible?

I see there was an oblique [reference to this back in 2013](https://github.com/ajaxorg/ace/issues/1181#issuecomment-21085824)...

**Comment by dsl101** [comment]
Well, that's a shame. Yes, I'd still like to know how to do this, but I guess nobody else does :(

**Comment by andrewnester** [comment]
Does this change address your use case? https://github.com/ajaxorg/ace/pull/4812

**Comment by dsl101** [comment]
> Does this change address your use case? #4812

Thanks—I will check this out as soon as I can.

**Comment by dsl101** [comment]
Andrew, would you be able to give some guidance how to use this feature with ace-builds? I'm using ace inside a large app, build with Vue & webpack, and this is how I've been initialising the editor (which is working fine):
```js
  import ace from 'ace-builds/src-min-noconflict/ace.js'
  import htmlWorkerUrl from 'file-loader!ace-builds/src-min-noconflict/worker-html'
  ace.config.setModuleUrl("ace/mode/html_worker", htmlWorkerUrl)
  import 'ace-builds/src-min-noconflict/ext-language_tools.js'
  import 'ace-builds/src-min-noconflict/mode-html.js'
  import 'ace-builds/src-min-noconflict/theme-chrome.js'

...

      this.htmlEditor = ace.edit(this.$refs.aceHTML, {
        ...this.editorConfig,
        mode: 'ace/mode/html',
      })
```

I've updated that to read:
```js
  import ace from 'ace-builds/src-min-noconflict/ace.js'
  import htmlWorkerUrl from 'file-loader!ace-builds/src-min-noconflict/worker-html'
  ace.config.setModuleUrl("ace/mode/html_worker", htmlWorkerUrl)
  import 'ace-builds/src-min-noconflict/ext-language_tools.js'
  import { Mode as HtmlMode } from 'ace-builds/src-min-noconflict/mode-html'        // ←--------- Change
  import 'ace-builds/src-min-noconflict/theme-chrome.js'

...

      this.htmlEditor = ace.edit(this.$refs.aceHTML, {
        ...this.editorConfig,
        // mode: 'ace/mode/html',                                                   // ←--------- Remove
      })
      this.htmlEditor.session.setMode(new HtmlMode({ fragmentContext: 'body' }))    // ←--------- Add
```
and I _think_ that's working (in that I see no console errors, and the editor no longer warns about missing `<!DOCTYPE>`). Is that all that's needed? Many thanks!

**Comment by andrewnester** [comment]
@dsl101 yes, that seems like the right way to use it
