### ISSUE TITLE
Code completion is automatic

### ISSUE THREAD

**Issue by LLZWWY** [ajaxorg/ace#4437]
Excuse me
Is there any code completion function in ACE? Or how to enable this feature?
I just started to learn to use JavaScript to make a suitable editor for my own use.

**Comment by KarthickMathesh** [comment]
@LLZWWY  

You can use emmet autocomplete which is located in ace/lib/ace/ext/emmet.js

```html
<script src="js/emmet.js"></script>
```

```js
<script>
  // Enable Emmet
editor.setOption("enableEmmet", true);
</script>
```
