### ISSUE TITLE
getLength is missing on document in ace.d.ts file

### ISSUE THREAD

**Issue by rbirkgit** [ajaxorg/ace#4438]
Is it on purpose that the getLength() method is missing on the document object in the typescript ace.d.ts file? I see the session version is calling the doc.getLength() so it seems it is indeed doing the same thing.

I noticed this when adding type check to our code and it complained all places we did doc.getLength() and I had to update the code to use the session object instead.

**Comment by mkslanc** [comment]
Fixed by #4450
