### ISSUE TITLE
PHP 8.0 support

### ISSUE THREAD

**Issue by TysonAndre** [ajaxorg/ace#4439]
I assume this would be done by re-running steps similar to 5834d8ff8f7e29357bb7131cc362d8bc703b1eab 

- The latest version https://github.com/nikic/PHP-Parser/blob/master/grammar/php7.y also supports php 8 grammar such as `T_MATCH` (php 8.0 match expressions) - unlike the switch from php5.0 to php7.0, php8 isn't reinventing parser.

Mentioned in https://github.com/phan/demo/issues/13

```php
<?php

function baz() {
	$val = match ( 'foo' ) {
		'foo' => 'v1',
		'bar' => 'v2'
	};
	echo $val;
}
baz();
```

**Comment by mkslanc** [comment]
Fixed by  #4696
