### ISSUE TITLE
Duplicate <style> sections

### ISSUE THREAD

**Issue by rbirkgit** [ajaxorg/ace#4442]
Seems because of this "fix": https://github.com/ajaxorg/ace/issues/3590  

This "fix" is causing our code to get duplicate ace <style> chunks and our ace editors now have duplicate css. Not sure if this is only happening on Angular apps or in other frameworks too. All our code that has projections or conditional statements (e.g. *ngIf) is causing local copies of the styles in "random" places in our code, in addition to styles being added to the document header. This because we have multiple ace editors in our code. None of our code use web components. Just plain Angular. I wish there was a way to force all styles in document header so we don't end up with all these duplicates.

**Comment by rbirkgit** [comment]
comment

**Comment by andrewnester** [comment]
I wasn't able to reproduce the issue on the latest build, could you please provide reproduction steps?

**Comment by rbirkgit** [comment]
Maybe this was fixed. Don't see it right now.
