### ISSUE TITLE
No scrollbar for long autocompletion values displayed

### ISSUE THREAD

**Issue by sleepomeno** [ajaxorg/ace#4454]
When I have a very long value for autocompletion, it would be necessary to have a horizontal scrollbar in the tooltip in order to be able to see the complete line. 
![autocomplete](https://user-images.githubusercontent.com/1987377/109154575-c333ec80-776e-11eb-8956-e5c58ce7999f.png)
I tried achieving that with a CSS solution, to no avail. Given that somehow the renderer is used for the vertical scrollbar, I just wonder how https://github.com/ajaxorg/ace/blob/master/lib/ace/autocomplete/popup.js (?) would need to be adapted to support that?

**Comment by zoubaihan** [comment]
Hi, dear friend, I am also considering to use **popup.js** to complete my code, but when I add the code below into my html file:
<script src="ace/autocomplete/popup.js" type="text/javascript" charset="utf-8"></script>
The browser remind me that there throws an error:
![image](https://user-images.githubusercontent.com/60840371/109273229-e03eed00-784c-11eb-8607-469b39052a00.png)
How can I use this autocomplete function, could you please teach me?

**Comment by mahdi943** [comment]
Hi,

I am using Ace editor in my project for Gherkin syntax. I have already implemented existing ace autocomplete but it just suggests current words in the editor; I need to add my custom list for Autocompletion. 
How can I do that?
Any one can help me where can I add my own list?

Thanks.
