### ISSUE TITLE
Ace Compatible with WPF C#?

### ISSUE THREAD

**Issue by ENDAWERKZ** [ajaxorg/ace#4455]
The only way I know how to implement ace into C#. I have saw that WFP uses **correct scaling** and C# looks blurry but web browsers do not make code if you double click in WPF C# so I think it is Impossible to use ace in WPF... Am I wrong?

**Comment by LoganDark** [comment]
Ace is written in JavaScript and designed to be run in a browser... you could use a webview to embed Ace, perhaps?

**Comment by YellowAfterlife** [comment]
People generally use AvalonEdit in C#+WPF applications. As for correct scaling, that's something to investigate separately.
