### ISSUE TITLE
ace editor not showing warning.

### ISSUE THREAD

**Issue by suchethan** [ajaxorg/ace#4474]
![screen](https://user-images.githubusercontent.com/61040321/113884124-5c2d3d00-97dc-11eb-9a32-4eaf142da27c.png)

Whenever there is a wrong syntax given the ace editor is not showing a warning.

**Comment by AlexanderMisel** [comment]
Syntax validation is enabled by default. I didn't reproduce your problem on [mode_creator](https://ace.c9.io/tool/mode_creator.html), are there any errors shown in browser console?
