### ISSUE TITLE
Regular Expression DoS vulnerability

### ISSUE THREAD

**Issue by linci8210** [ajaxorg/ace#4475]
We are working on the [ReDoS](https://www.owasp.org/index.php/Regular_expression_Denial_of_Service_-_ReDoS) problem and detected 1 vulnerable regex(es) from your repository.

1: ``("(?:\\.|[^"])*")|(?:,\s*)+([\]\}])|(\w+)\s*:|([\]\}]\s*[\[\{])|(\/\/.*|\/\*(?:[^\*]|\*(?=[^\/]))*?\*\/)`` in ace/tool/lib.js

Please try the following:

	var pattern = "(\"(?:\\\\.|[^\"])*\")|(?:,\\s*)+([\\]\\}])|(\\w+)\\s*:|([\\]\\}]\\s*[\\[\\{])|(\\/\\/.*|\\/\\*(?:[^\\*]|\\*(?=[^\\/]))*?\\*\\/)";
	var input = "\"\\\b\\\b\\\b\\\b\\\b\\\b\\\b\\\b\\\b\\\b\\\b\\\b\\\b\\\b\\\b\\\b\\\b\\\b\\\b\\\b\\\b\\\b\\\b\\\b\\\b\\\b\\\b\\\b\\\b\\\b\\\b\\\b\\\b\\\b\\\b\\\b\\\b\\\b\\\b\\\b\\\b\\\b\\\b\\\b\\\b\\\b\\\b\\\b\\\b\\\b\\\b\\\b\\\b\\\b\\\b\\\b\\\b\\\b\\\b\\\b\\\b\\\b\\\b";
	var re = new RegExp(pattern);
	var matched = input.match(re);

We didn’t create a pull request because we're not sure if these cases are possible to take place in your program, we also do not understand the functionality of these regexes as you do. Thank you for your understanding.

**Comment by nightwing** [comment]
The one here seems to be fixed by adding `\\` to the first `[^"]` in the regex.

Do you have an automated tool that can detect regexp vulnerabilities like this? This one was in a rarely used part of the code, but we have many regexps in the code higlighters which would benefit greatly from such a tool.

**Comment by linci8210** [comment]
Our tool Revealer will appear at the [S&P 2021](https://www.ieee-security.org/TC/SP2021/program-papers.html). We will release the code in github later.
