### ISSUE TITLE
Variables support for json mode

### ISSUE THREAD

**Issue by ohryk-intellias** [ajaxorg/ace#4477]
Hi all! Guys, is there exist some easy way to extend JSON mode to support variables syntax (see below)?

```
{
  "name": "Alex",
  "tag": {{my_custom_variable}}
}
```
The goal is to highlight the `{{<any_string_name>}}` token and (what is more important) make this syntax construction to be correct (right now, it is not supported by JSON mode and it throws the error "Bad string").

Thanks!

**Comment by ohryk-intellias** [comment]
I have investigated a little bit with this tool https://ace.c9.io/tool/mode_creator.html and seems that it is easy to define a new highlighting rule, but the question with syntax checking is still opened...

And seems that the only way is to extend this file https://github.com/ajaxorg/ace/blob/master/lib/ace/mode/json/json_parse.js to support the custom variables.

**Comment by ohryk-intellias** [comment]
This issue can be closed.

**Comment by SunYuanOnly** [comment]
> Hi all! Guys, is there exist some easy way to extend JSON mode to support variables syntax (see below)?
> 
> ```
> {
>   "name": "Alex",
>   "tag": {{my_custom_variable}}
> }
> ```
> 
> The goal is to highlight the token and (what is more important) make this syntax construction to be correct (right now, it is not supported by JSON mode and it throws the error "Bad string").`{{<any_string_name>}}`
> 
> Thanks!

How do you make it support that? I encountered the same problem bro.
