### ISSUE TITLE
TM_SELECTED_TEXT or SELECTED_TEXT or  SELECTION in Snippets does not work as Document says

### ISSUE THREAD

**Issue by wlbksy** [ajaxorg/ace#4480]
I find `SELECTED_TEXT` AND `SELECTION` in [https://cloud9-sdk.readme.io/docs/snippets#section-using-special-variables](https://cloud9-sdk.readme.io/docs/snippets#section-using-special-variables) and `TM_SELECTED_TEXT` in [https://ace.c9.io/build/kitchen-sink.html](https://ace.c9.io/build/kitchen-sink.html)  javascript mode does not work. 

First, select one word. The selection content goes empty when I type the corresponding leading trigger, so the snippet containing these variables does not work as intended.

**Comment by nightwing** [comment]
What behaviour do you expect in other editors selection goes empty as well, and the only way to use such a snippet is to either pick it from completer popup, or from a menu or a button.

**Comment by wlbksy** [comment]
visual studio code can do this starting from version 14.9 

There're a gif on this stackoverflow demonstrating this. https://stackoverflow.com/questions/41191054/using-tm-selected-text-in-my-custom-snippets/48676522#48676522.

Besides, can we get CLIPBOARD working too?
