### ISSUE TITLE
Potential optimization for gatherCompletions

### ISSUE THREAD

**Issue by YellowAfterlife** [ajaxorg/ace#4482]
**Context:** For organizational purposes and following the example of existing completers, my application uses different completers for different purposes, to a total of 31 (annotated [here](https://github.com/YellowAfterlife/GMEdit/blob/master/src/ace/AceWrapCommonCompleters.hx#L53)).

While looking into whether smart auto-completion performance could be improved for particularly large (26K resource names) projects, I noticed an interesting detail: code from this line onward  
https://github.com/ajaxorg/ace/blob/94422a4a892495564c56089af85019a8f8f24673/lib/ace/autocomplete.js#L313  
will re-run as completion results are being collected, meaning that a batch of results from a completer is filtered and sorted (length - completer's index) times total - even if the completers returned their results immediately.

I imagine that the best solution could be to filter only the newly added results in gatherCompletions and delay sorting+display until the next frame (so that results added during the same frame would be filtered together), but for my purposes (and, I'd suspect, other general uses) "batching" result handling for completers that returned them immediately was enough:
https://github.com/YellowAfterlife/GMEdit/commit/70cba3c5729b6b9ac3e6d490f732fdcb94e9dab8

**Comment by nightwing** [comment]
This would be a very useful optimization. Could you make a pull request with this change?
