### ISSUE TITLE
Enabling/disabling mousewheel handling?

### ISSUE THREAD

**Issue by warpspin** [ajaxorg/ace#4487]
It would be great to have an option to enable/disable mousewheel handling on the fly. I have multiple Ace editors on one page and greatly prefer, if they only handle the events if the editor is actually focussed so that you can still quickly scroll over the page itself without "stopping by" at every ace editor field.

**Comment by warpspin** [comment]
Feature request is still valid

**Comment by nightwing** [comment]
currently it is possible to do

```js
disableDefaultWheel = function(e) { e.defaultPrevented = true }
editor.on("mousewheel", disableDefaultWheel) // disable
editor.off("mousewheel", disableDefaultWheel)  // enable
```
