### ISSUE TITLE
Issue with firefox after save locally a page containing an ace editor element containing a line wih a lenght > 130

### ISSUE THREAD

**Issue by kegilko** [ajaxorg/ace#4494]
Hi ! 
First, thanks you for your amazing library ! Thanks your work and also the community, I created an online tool containing lessons and interactives examples for my students :) 

I'm looking for allow my students to save a webpage containing an ace editor element (if they want to read a lesson without internet in the future). 

If I save a page with Chrome (ctrl+s ...), all works fine when I load the saved local page file. But I have a issue with firefox if the ace editor contains a long line (> 130 char).

Given this simple standalone code : (its a simplified code of my tool, in my tool I need to use a 'save' element and upload its content when the content of the editor change)

```html
 <!DOCTYPE html>
<html lang="fr">
<script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.12/ace.js"></script>
<body>
    <div id="editor"></div>
    <div id="save" style="display:none;">
        -- [#0] création des tables et champs de la BDD {
        --  = this is a comment very very very very very very very very very very very very very very very very very very very very very long
        CREATE TABLE foo(
            id INTEGER NOT NULL,
            faa VARCHAR(100),
            fuu VARCHAR(100),
            fii VARCHAR(30),
            PRIMARY KEY (id)
        );
    </div>
    <script>
            document.getElementById('editor').innerHTML = document.getElementById('save').innerHTML;
            var editor = ace.edit("editor");
            editor.getSession().setMode("ace/mode/sql");
            editor.setOptions({
                    autoScrollEditorIntoView: true,
                    maxLines: Infinity,
                    wrap: true
            });
            editor.getSession().on('change', function() {
                    document.getElementById('save').innerHTML = document.getElementById('editor').innerHTML;
            });
    </script>
</body>
</html>
```
If I save this code in a .html file and load it from the browser firefox, all works as expected : 

![Screenshot from 2021-05-16 17-38-07](https://user-images.githubusercontent.com/58623661/118403242-dc618080-b66d-11eb-96a7-13634e24ff82.png)

...then if I save the loaded page (with a simple ctrl+s on firefox) and then load the saved page in a new browser tab, as you can see the ace editor load incorrectly the content : 

![Screenshot from 2021-05-16 17-40-10](https://user-images.githubusercontent.com/58623661/118403247-dff50780-b66d-11eb-9e7a-7f64ebea96b2.png)

As I said in the beginning, this bug occurs when the length of a line is above of 130 (chars)

Thanks for any help if I do something wrong or if there is a workaround..

**Comment by nightwing** [comment]
use getValue,  innerHTML contains only visible text.
```js
var editor = ace.edit("editor", {
    value: document.getElementById('save').textContent,
    mode: "ace/mode/sql",
    autoScrollEditorIntoView: true,
    maxLines: Infinity,
    wrap: true
});

editor.on('input', function() {
    document.getElementById('save').textContent = editor.getValue();
});
```

Also `maxLines: Infinity` is a really bad idea, it will make editor very slow with large amount of text.

**Comment by kegilko** [comment]
thanks for your quickly reply and I take note of your advises ! 
Unfortunately, theses points does not solve my main issue...

**Comment by nightwing** [comment]
@kegilko which is your main issue? As far as i understood it was the long lines, and likely lines with html tags, not being saved correctly and using getValue and textContent the way i have showed above should help. If it doesn't could you give me an example of a page where i can test?

**Comment by kegilko** [comment]
@nightwing 
I'm sorry yes I should have give the new version of the code after your answer :) 

Here is it :

```html
 <!DOCTYPE html>
<html lang="fr">
<script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.12/ace.js"></script>
<body>
    <div id="editor"></div>
    <div id="save" style="display:none;">
-- [#0] création des tables et champs de la BDD {
--  = this is a comment very very very very very very very very very very very very very very very very very very very very very long
CREATE TABLE foo(
	id INTEGER NOT NULL,
	faa VARCHAR(100),
	fuu VARCHAR(100),
	fii VARCHAR(30),
	PRIMARY KEY (id)
);
    </div>
    <script>
            var editor = ace.edit("editor");
			editor.setValue(document.getElementById('save').textContent, -1);
            editor.getSession().setMode("ace/mode/sql");
            editor.setOptions({
                    autoScrollEditorIntoView: true,
                    maxLines: 50,
                    wrap: true
            });
            editor.getSession().on('change', function() {
                    document.getElementById('save').textContent = editor.getValue();
            });
    </script>
</body>
</html>

```

As you can see, I use now `getValue()` and `textContent` but if : (from Firefox browser) 

1. I load the html page, I get : 

![image](https://user-images.githubusercontent.com/58623661/119241373-28249600-bb56-11eb-9aa1-3a8a8552a9f9.png)

2. I modify one line : 

![image](https://user-images.githubusercontent.com/58623661/119241414-5efaac00-bb56-11eb-9363-a40e218e98ec.png)

3. I save the page (via ctrl+s) 
4. I load the saved page, I get : 

![image](https://user-images.githubusercontent.com/58623661/119241427-8782a600-bb56-11eb-9592-7fb4759bf95f.png)

=> the modification in step 2 is kept as expected
=> but ! as you can see, the (long) line 3 in the step 1 is mysteriously transformed into 2 lines. This bug is as I said only trigged when I use the browser Firefox

**Comment by andrewnester** [comment]
It seems you have a wrap enabled in your editor settings and this is what causes the line to go on the next line (being wrapped)
