### ISSUE TITLE
Add support for Wren (I'm willing to help)

### ISSUE THREAD

**Issue by joshgoebel** [ajaxorg/ace#4497]
- https://wren.io
- https://github.com/exercism/wren/issues/8

How picky is Ace about merging PRs for language support?  I could probably work on this and get something 90% there... is that good enough for merging?  Is a PR welcome if it works well but say only covers 90% of language features... could it be merged and then improved upon later?  

Trying to get a vibe for the culture before I go and spend time working on a PR.

**Comment by nightwing** [comment]
So far our policy for not very popular languages have been to merge PRs if someone proposed, and trust the author that the provided mode is more useful than editing without a mode. So covering 90% and then improving would be ok.

**Comment by joshgoebel** [comment]
We decided to go with a different editor, but if anyone finds this later and needs help I might be able to offer a little help or review a PR.  I maintain Highlight.js so I know a little something about regex and pattern matching for grammars.  I found the web editor building thingy pretty useful to play around with.
