### ISSUE TITLE
Wrong cursor position

### ISSUE THREAD

**Issue by Be1zebub** [ajaxorg/ace#4499]
When I type my cursor is always to the left of the last entered character.
How can this be fixed?
Perhaps this is a problem with an old browser because m using awesomium (sort of like it's chromium 65), it works well on last chromium version.

Here is 10 sec video where i show this bug:
[![IMAGE ALT TEXT](https://i.imgur.com/Ca0VKIg.png)](https://youtu.be/piYPbWWFIk4 "Ace Cursor Bug")

Perhaps there is a way to add +1 to the cursor position when the user enters a character into the editor window.
idk, any fix way would be good 4 me.

**Comment by Be1zebub** [comment]
solved with:
```javascript
editor.getSession().on("change", function(e) {
	setTimeout(function() {
		var cursor = editor.selection.getCursor();
		editor.selection.moveTo(cursor.row, cursor.column + 1);
	}, 50);
});
```

**Comment by Be1zebub** [comment]
nvm my previous post, this hack breaks newlines.
Enter key does not always work.

**Comment by bhdr1** [comment]
> nvm my previous post, this hack breaks newlines.
> Enter key does not always work.

We had the same problem. Our problem is related to span css. 
We override the span element like this;
span {
  overflow: hidden;
  white-space: nowrap;
  text-overflow: ellipsis;
} 

Changed to 

span:not([class^="ace"]) {
  overflow: hidden;
  white-space: nowrap;
  text-overflow: ellipsis;
}

Maybe it helps to you

**Comment by Be1zebub** [comment]
Unfortunately, this did not help.
here is my css (i just copied that from embedding guide)
```css
#editor { 
	position: absolute;
	top: 0;
	right: 0;
	bottom: 0;
	left: 0;
}
```
its just a old browser issue.
here is useragent:
Mozilla/5.0 (Windows; Valve Source Client) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1003.1 Safari/535.19 Awesomium/1.7.5.1 GMod/13
Chrome 18 as you see. (2012 year release)  

What causes this bug? It would be easier to find a solution knowing the cause of the bug.

**Comment by andrewnester** [comment]
Unfortunately can't reproduce it in the newer versions of browser, could you please help us with reproduction steps?
