### ISSUE TITLE
Can i make Css Linter ignore a section of code?

### ISSUE THREAD

**Issue by schockocraft** [ajaxorg/ace#4503]
I use ace as part of the Mediawiki Extension [CodeEditor](https://www.mediawiki.org/wiki/Extension:CodeEditor) with Mediawiki in turn being hosted by a remote hoster, which means i cannot change anything about the installation of Ace. I am writing Css and the Linter recognizes errors, that are correct in new not-yet-in-specifications css, but even if these are already fixed in ace, i cannot expect my version of ace to be updated soon.

I am looking for a way to mark these sections as expected errors, so i can see when i have actual errors at other positions. 

After looking through issues i know that it is possible to use `/* jshint asi:true */` in js code to prevent the JS Linter from recognizing missing `;` as an error; is there something similar for my usecase, so i don't have to learn the ace editor api for just using it once?

**Comment by andrewnester** [comment]
Unfortunately we don't provide this functionality and Ace and don't have plans to add this at this moment
