### ISSUE TITLE
Highlighting heredoc in PHP

### ISSUE THREAD

**Issue by KoljaL** [ajaxorg/ace#4504]
Is there a way to highlight the HTML part:

 
```php
<?php
    $html = <<<HTML
    <div class="card">
        <img src="$img" alt="">
        <h2>$title</h2>
        <p>$desc</p>
    </div>
    HTML;
```

**Comment by AlexanderMisel** [comment]
You can refer to the markdown highlighter (which could highlight code fences in multiple languages) to extend the PHP highlighter.
