### ISSUE TITLE
CSP 'script-src' directive is violated

### ISSUE THREAD

**Issue by dimovpetar** [ajaxorg/ace#4506]
Hello,

There are some usages of `eval` and `Function` that break the 'script-src' directive. Right now, the only workaround is to disable it by setting it's value to `unsafe-eval`.
These are the lines of code that violate it:

- https://github.com/ajaxorg/ace/blob/145328b96083c6b7c306d3dcf841948f73486919/lib/ace/mode/javascript_worker.js#L108
- https://github.com/ajaxorg/ace/blob/145328b96083c6b7c306d3dcf841948f73486919/lib/ace/mode/css/csslint.js#L4411

And these lines of code are not executed, but code analysers report warnings for them:
- ` return Function(importsKeys, sourceURL + 'return ' + source).apply(undefined, importsValues);` in this file https://github.com/ajaxorg/ace/blob/master/lib/ace/mode/xquery/xqlint.js
- https://github.com/ajaxorg/ace/blob/563113e1900f691d0d669f64abe238d45796bcb0/lib/ace/mode/javascript/jshint.js#L251 https://github.com/ajaxorg/ace/blob/563113e1900f691d0d669f64abe238d45796bcb0/lib/ace/mode/javascript/jshint.js#L2413 https://github.com/ajaxorg/ace/blob/563113e1900f691d0d669f64abe238d45796bcb0/lib/ace/mode/javascript/jshint.js#L3984

More information about [Unsafe eval expessions](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#unsafe_eval_expressions).

Are there any plans to adopt CSP and remove these?

- [x] Fix for javascript_worker.js #4540 
- [x] Fix for csslint.js #4465
- [ ] Fix for xqlint.js
- [ ] Fix for jshint.js

**Comment by hobojoe** [comment]
Facing the same issues! Wish it could be removed indeed!
