### ISSUE TITLE
$handlePaste and Empty String ('')

### ISSUE THREAD

**Issue by RickStrahl** [ajaxorg/ace#4514]
Ran into an issue with `editor.$handlePaste()` when pasting an empty string into a selection. It works fine when pasting a non-empty string value, which replaces the active selection with the value provided.  But when the value is `''` the selection is not replaced with the empty string value. I would expect that to essentially clear the selection, but that's not happening.

Stepping through the code in Ace I see the string coming in as `''` and then the `lineMode` flag getting triggered to `true` on the empty string:

![image](https://user-images.githubusercontent.com/1374013/122691819-a6706880-d1e6-11eb-97c4-afd83c22c684.png)

The intent from my end of course is to the clear the selection on a paste operation (initiated in an external application) where I call:

```javascript
te.editor.$pasteOperation('');  
```

to effectively clear the selection.

Not sure what the intent is there and why `''` would be treated differently than a non-empty string value. Am I missing something here?

Ran into this as I recently switched my code from explicitly manipulating ranges to `$pasteOperation()` to simplify and get what appears to be cleaner operation for some paste operations.

For now I switched to using my old code on empty strings:

```js
setselection: function (text) {
    if (text)
        te.editor.$handlePaste(text);    
    else {
        var range = te.editor.getSelectionRange();
        te.editor.session.replace(range, text);
    }
    te.editor.renderer.scrollSelectionIntoView();
}
```

 which works, but is awkward.

**Comment by nightwing** [comment]
https://github.com/ajaxorg/ace/pull/4517 should fix this, but $handlePaste is a private method and its behavior will depend on the last text copied in lineMode (can be triggered by ctrl-c with empty selection when copyWithEmptySelection option is enabled)

**Comment by RickStrahl** [comment]
Is there a non-private way to basically tell ACE to replace the existing selection other than the selection range code I was using? I've been having issues with that code, where `$handlePaste()` seems to work more reliably (except for the empty value).

The range selection/replace works most of the time, but I've found on occasion when handling copy and paste operations explicitly it doesn't work (ie. I copy text in one section then paste it back in another) when I call it from my external host application.  Occasionally calling the range replace code from the host doesn't work, but $handlePaste seems to always work (other than the '' :smile:).

Thanks for the fix!

**Comment by nightwing** [comment]
What issues did you have with the selection range code? It is the only way to replace selected range with other text,  But if you are trying to exactly replicate the behavior from pasting text, then $handlePaste or  onPaste are fine, we simply didn't handle the case with empty string because we drop that already at the clipboard event handler https://github.com/ajaxorg/ace/blob/35ddb50f353f14ba56872b5921d95d81e1ad7f08/lib/ace/keyboard/textinput.js#L298

**Comment by RickStrahl** [comment]
The issues I've run into is that copy operations are not working when doing copy from document then paste into another part of document. It's very rare and I've never been able to actually have a live case that I can debug seeing the actual state, but it happens occasionally when running the editor. When it happens all intercepted copy/paste operations stop working (it's the paste that fails).

To be fair there could be other external factors as this actually goes into a host (desktop) application first. My guess is the problem has to do with the the selection ranges not getting set correctly when manually pasting. It's not consistent. It almost always works just fine, but when it doesn't it's broken until doc is reloaded.

The nice thing about $handlePaste() is that it completely automates all that - uses the current selection and pastes back to it with the clipboard value - so it's much more direct.

The reason I need to intercept in the host is because we allow pasting of non-text content (images, files) into the editor. Those items are embedded into the editor as links (markown). I haven't figured out a way I can figure out inside of ACE or JavaScript whether the clipboard content is text or something else without going async code gymnastics to simulate a sync call scenario. If I could figure that out more easily inside of ACE I wouldn't have to go into the host, except for the occasional non-text pastes...

Regardless with the space fix in $handlePaste() though it looks like I should be able to use $handlePaste() regardless it looks like.

Thank you!
