### ISSUE TITLE
Make some portions of editor readonly

### ISSUE THREAD

**Issue by qburst-varunnath** [ajaxorg/ace#4515]
I am using editor to edit html. I need to prevent editing text between tags containing a given attribute. For example below given I need to make the P tag and inside contents readonly since it contains the attribute **_data-readonly_**

`<p class="dummy" data-readonly>This is not editable </p>`

Could any one please help to find a solution for this

**Comment by andrewnester** [comment]
closing as duplicate of https://github.com/ajaxorg/ace/issues/3634
