### ISSUE TITLE
Automatically expand editor div vertically

### ISSUE THREAD

**Issue by stefan-reich** [ajaxorg/ace#4520]
Hi,

I'm using a nice little JS hack to make textareas grow vertically as needed (up to a maximum), so they can be used as replacements for input fields. ([Example](https://bea.gazelle.rocks/query), press Enter to see the effect.)

Can I do the same thing with Ace Editor?

Thanks

**Comment by nightwing** [comment]
Use 
```js
    var editor = ace.edit("editor", {        
        autoScrollEditorIntoView: true,
        maxLines: 30,
        minLines: 2
    });
```
https://ace.c9.io/build/demo/autoresize.html

**Comment by stefan-reich** [comment]
Thanks, will try!
