### ISSUE TITLE
Outdated/Missing documentation for onChange event

### ISSUE THREAD

**Issue by sischnei** [ajaxorg/ace#4528]
I'm upgrading from Ace 1.1.9 to 1.4.12 and I noticed that there have been changes to the onChange event API. I think this was part of the following ticket: https://github.com/ajaxorg/ace/pull/1745

However, the API documentation on the website (https://ace.c9.io/#nav=api&api=editor) still shows the old API calls and there isn't really a good source pointing to the above ticket (which contains helpful information).

![image](https://user-images.githubusercontent.com/1112685/125293246-86ceea80-e323-11eb-81ab-dcb672f1658d.png)

**Comment by nightwing** [comment]
This was fixed by https://github.com/ajaxorg/ace/pull/4900 https://ajaxorg.github.io/ace-api-docs/interfaces/Ace.Delta.html
