### ISSUE TITLE
Improve doc of addMarker()

### ISSUE THREAD

**Issue by champignoom** [ajaxorg/ace#4532]
> `addMarker(Range range, String clazz, Function | String type, Boolean inFront)
> 
> Adds a new marker to the given Range. If inFront is true, a front marker is defined, and the 'changeFrontMarker' event fires; otherwise, the 'changeBackMarker' event fires.
>
> Arguments
> - range; Range; Required. Define the range of the marker
> - clazz; String; Required. Set the CSS class for the marker
> - **type; Function | String; Required. Identify the type of the marker**
> - inFront; Boolean; Required. Set to true to establish a front marker

The supported "type"s should be mentioned.

**Comment by akoreman** [comment]
Will be included in the next ace release (1.24.0)
