### ISSUE TITLE
Static highlighter font size

### ISSUE THREAD

**Issue by mctoohey** [ajaxorg/ace#4533]
At the moment the static highlighter always uses a font-size of 12px and will not inherit the font-size from the parent. 

This means if you have a paragraph with larger text, then a section of static highlighted code. The code will look small and out of place.

I think either the font-size should not be explicitly set so that it can be inherited _or_ one of the options when calling the `highlight` function should be to set the font-size.

Anyone have any thoughts on this and which approach would be best?

**Comment by nightwing** [comment]
As a workaround you can add the following css on your page 
```css
.ace_static_highlight {
    font-size: inherit!important;
}
```

The code doing this is at https://github.com/ajaxorg/ace/blob/94422a4a892495564c56089af85019a8f8f24673/lib/ace/ext/static.css#L3, but i am not sure if we should break backwards compatibility by doing this now, or wait for the next major version.

**Comment by mctoohey** [comment]
Thank you for that.

My solution had been to change the style of the element with that class dynamically in the callback function.
```
highlight(codeElement, {
                mode: mode,
                showGutter: true
            }, function(highlighted) {
                    codeElement.getElementsByClassName('ace_static_highlight')[0].style['font-size'] = "16px";
            });
```
I certainly understand not wanting to break backwards compatibility. Which is why I thought maybe it would be better as an options in the `opts` parameter of the highlight function? 

Anyway, I have a fix now, thanks again for providing another solution.
