### ISSUE TITLE
Emmet demo not working

### ISSUE THREAD

**Issue by muthu32** [ajaxorg/ace#4550]
Emmet demo for ace editor is not working. At first all files are loaded and it turns blank white page after loading.

Browser: Chrome Version 92.0.4515.159 (Latest Version)
URL: https://ace.c9.io/demo/emmet.html

**Comment by nightwing** [comment]
I can't reproduce this issue. Do you see any errors in browser console?

**Comment by muthu32** [comment]
Found the cause of the Error. It was Chrome Extension [Grepper extension](https://chrome.google.com/webstore/detail/grepper/amaaokahonnfjjemodnpmeenfpnnbkco?hl=en).
This extension add **position:relative** to **pre tag** that causes ace editor page to turn blank page.
