### ISSUE TITLE
Ability to apply range on scrollbar

### ISSUE THREAD

**Issue by undergroundwires** [ajaxorg/ace#4556]
I wonder if it's possible to add native support for highlighting/indicating/marking lines on scrollbar? If not, would you recommend a nice way to achieve it?

Example showing how it's done in Visual Studio Code:
![image](https://user-images.githubusercontent.com/15555035/131329896-34f1603b-d88f-4acf-9505-b13e8e56c4b5.png)

Thank you for the awesome project. I've been happily using it in [privacy.sexy](https://privacy.sexy) for a while now.

**Comment by nightwing** [comment]
This was implemented by https://github.com/ajaxorg/ace/pull/4905 which have added customScrollbar option, please let us know if it does what you need.

**Comment by undergroundwires** [comment]
Hi @nightwing , thank you for the information. I've checked the PR but still have hardtime understanding how I can highlight range of lines. It's very straightforward to add a marker:

```javascript
editor.session.addMarker(
        new AceRange(startRow, 0, endRow, 0),
        'code-area__highlight',
        'fullLine',
      );
```

And I can highlight like this:
      
```scss
  background-color: $color-secondary-light;
  position: absolute;
```
    
But how can I get line number based highlighting of a range just like this? I see no examples or no documentation. I'd appreciate any guide.
    
My code: https://github.com/undergroundwires/privacy.sexy/blob/bab6316e7625230cf4a4cf67c3aca417347db75c/src/presentation/components/Code/TheCodeArea.vue#L116-L123
