### ISSUE TITLE
Custom auto completer for custom complex data

### ISSUE THREAD

**Issue by kaphula** [ajaxorg/ace#4561]
Is it possible to add custom auto completer for more complex objects and their nested properties. For example let's say I want to add auto completer for this kind of custom data. 

```javascript
Data = {
  Colors: {
    Red,
    Blue,
    Yellow  
  },
  Names: {
    A,
    B,
    C
  }
}
```
The idea is that I have a javascript library with this kind of data or functionality available, but obviously Ace does not know about it because it is not directly written into the editor for Ace to analyze it along with other code.

Thus after configuring and adding this custom data to Ace, writing in the editor

```
Data.Colors.
```
 would display `Red`, `Blue` and `Yellow` in as the first items in the auto completion dialog.

Now I would like to feed this data structure to Ace using the `langTool.addCompleter` callback, but the callback setup offers only support for simple one level definitions, not nested objects like the one above if I understood this correctly?

**Comment by nightwing** [comment]
For javascript and typescript it is possible to use ace-linters with custom type declaration as shown in https://mkslanc.github.io/ace-playground/#typescript-language-service, however for the general case one needs to write a parser to figure out the context and decide which completions to show.
