### ISSUE TITLE
Height of each autocomplete line

### ISSUE THREAD

**Issue by KryeKuzhinieri** [ajaxorg/ace#4562]
We are trying to change the height of the lines in the autocomplete, however that is not working as desired. 

   ```
   .ace_autocomplete .ace_line {
        height: 30px !important;
      }

      .ace_autocomplete .ace_active-line {
        height: 30px !important;
      }

      .ace_autocomplete .ace_line-hover {
        height: 30px !important;
        top: inherit !important;
      }
```

I am assuming that there is some way to do that using jquery or javascript because I see that the height is being changed programmatically.

**Comment by nightwing** [comment]
Setting line-height via css should work:
```css
.ace_editor.ace_autocomplete {
    line-height: 30px;
}
```

**Comment by KryeKuzhinieri** [comment]
It worked, thank you :)
