### ISSUE TITLE
Make gutter width based on the total number of lines, not the currently visible lines

### ISSUE THREAD

**Issue by BGR360** [ajaxorg/ace#4565]
Scrolling from line `10^N - 1` to line `10^N` results in the code shifting to the right, which is really disorienting when scrolling back and forth between different sections of code:

<a href="https://gyazo.com/f303766a0b30b4afbfffb0a683d0252d"><img src="https://i.gyazo.com/f303766a0b30b4afbfffb0a683d0252d.gif" alt="Image from Gyazo" width="378"/></a>

I would greatly prefer if the gutter width were based on the total number of lines. I.e., if there are 100 lines, then the gutter should always be three digits long, and if there are 1000 lines, then the gutter should always be four digits long.

Forgive me if this is what `fixedWidthGutter` is meant to fix, but based on its name I assumed it meant completely fixed.

**Comment by nightwing** [comment]
with  fixedWidthGutter the width is always based on the width of the last
line as you describe, do you get a different behavior?

**Comment by brijsiyag** [comment]
There is an option of **Fixed Gutter Width** in development build which do the same thing you want but don't know how to use when embedding in own page.
<p align="center">
  <img width="250px" src="https://i.imgur.com/SVw31eD.png"/>
</p>

**Comment by nightwing** [comment]
it  can be used with
   editor.setOption("fixedWidthGutter", true)
or by passing options object ot ace.edit like this
   ace.edit(domNode, {"fixedWidthGutter", true})

**Comment by BGR360** [comment]
> with fixedWidthGutter the width is always based on the width of the last line as you describe, do you get a different behavior?

Thanks, and apologies for not looking closer to see that for myself. I'm not actually a user of this library, I encountered the problem on play.rust-lang.org which uses ace. I will update the issue on that side to suggest using `fixedWidthGutter`.
