### ISSUE TITLE
Matching pairs in vim: incorrect display of match when consecutive closing characters

### ISSUE THREAD

**Issue by cornejom** [ajaxorg/ace#4568]
When using vim key bindings in vim's "normal" mode, placing the fat cursor on a bracket/parentheses that closes a matching pair does not always result in highlighting of the the matching opening bracket.  This happens when there are consecutive closing brackets.

Consider the snippet `((hello, world))`.  Moving the fat cursor to the final ")" does not highlight its match, the first "(".  

Interestingly, if the consecutive closing bracket is not at the end of the line, as in `((hello)), world` then moving fat cursor one character to the right (i.e. over the comma) triggers highlighting of the first opening parentheses.  This also is incorrect behavior for vim "normal" mode ... though it resembles correct behavior for "insert" mode (i.e. thin cursor).

I tried the above in JavaScript and R documents.

**Comment by nightwing** [comment]
The issue seems to be caused by vim mode using bracket matching logic from ordinary editor, looking for bracket before and after the slim cursor instead of bracket under the fat cursor.
