### ISSUE TITLE
Lua floor division operator not recognised

### ISSUE THREAD

**Issue by adrfantini** [ajaxorg/ace#4571]
Ace seems to consider the Lua operator `//` as invalid.
See for example this code:
```lua
function round(v, step)
    return math.tointeger((v + step*0.5) // step * step)
end
```

This is supported in Lua 5.3 ([doc](https://www.lua.org/manual/5.3/manual.html#3.4.1))

Tested in the [kitchen sink](https://ace.c9.io/build/kitchen-sink.html).

**Comment by andrewnester** [comment]
Fixed and released in 1.12.0
