### ISSUE TITLE
Is it possible to get and set the state of the registers on the Vim mode?

### ISSUE THREAD

**Issue by rafaelmuynarsk** [ajaxorg/ace#4574]
I know I can start vim mode using `editor.setKeyboardHandler("ace/keyboard/vim")`. However, I'd like to create a logic where I save the state of my registers, just so if I close it I will be able to set it to what it was before... 

The problem is about getting and setting the registers current state on a javascript variable... In a general way, I imagine having something like the following:

```
editor.setKeyboardHandler("ace/keyboard/vim")
...
var myRegisters = editor.getVimRegisters()
...
editor.setVimRegisters(myRegisters)
```

Is it possible to do? Or I'll always lose all the values stored on the registers once I close the editor?

**Comment by nightwing** [comment]
Currently it is possible to do 
```js
var {Vim} = require("ace/keyboard/vim") // ace.require in packaged mode
registerController = Vim.getRegisterController()
RegisterController.pushText(....)
```
https://github.com/ajaxorg/ace/blob/203a9d5df042f87c0c54959128ab51f547ffe772/lib/ace/keyboard/vim.js#L1948
