### ISSUE TITLE
virtual keyboard overlaps editor on Chrome

### ISSUE THREAD

**Issue by cscovino** [ajaxorg/ace#4575]
When using the ace editor on Chrome (mobile), the option autoScrollEditorIntoView doesn't work well, and the virtual keyboard overlaps the editor. While on Safari works fine.

### Chrome
https://user-images.githubusercontent.com/9748855/139104744-2f7f34e6-afc1-40bf-a1ef-37cdde604221.mp4

### Safari
https://user-images.githubusercontent.com/9748855/139104889-413ec20d-7bef-467d-8308-cd2c71912485.mp4

Is there a workaround to make the editor works fine on Chrome?

**Comment by cscovino** [comment]
I'm using an iPad (7th generation) with iOS 15.0.2 and Chrome 95.0.4638.50

**Comment by rruanruan** [comment]
> Does it work when autoScrollIntoView is disabled? if yes this may be caused by chrome reporting a wrong value of `window.innerHeight` here https://github.com/ajaxorg/ace/blob/master/lib/ace/editor.js#L2811. On which device do you see this issues? I couldn't reproduce it on samsung phone with samsung keyboard.

same problem here,autoScrollIntoView disabled doesn't work for me 

here is my useragent

Mozilla/5.0 (iPhone; CPU iPhone OS 14_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148

https://user-images.githubusercontent.com/22092758/143010938-9e2517d4-8751-404e-82a7-6c5ac375b647.mp4

plz help

**Comment by rruanruan** [comment]
is this sth safari do or ace do?
