### ISSUE TITLE
Disabling line-wrapping for single line

### ISSUE THREAD

**Issue by undergroundwires** [ajaxorg/ace#4578]
Let's say that I want to keep all lines wrapped except line number 53.

Is it possible? How would you suggest implementing it?

**Comment by nightwing** [comment]
You can override [`editor.session.$computeWidth`]( https://github.com/ajaxorg/ace/blob/v1.4.13/lib/ace/edit_session.js#L1038) and [`editor.session.$updateWrapData`](https://github.com/ajaxorg/ace/blob/v1.4.13/lib/ace/edit_session.js#L1726) to not wrap lines that you do not want. It's hard to tell more details, without knowing how is it decided which lines should be left unwrapped.
