### ISSUE TITLE
Cannot click scroll down button while the content is not ended

### ISSUE THREAD

**Issue by quan1506** [ajaxorg/ace#4580]
When the editor has very long content (7k lines), moving to the very near end of the editor, the scroll down button is grayed out while the content is not ended yet. Only using mouse wheel is able to scroll to the end. 

From the bottom, using mouse wheel to scrolling up but also don't see the scroll down button be enabled again, it's still grayed out until scrolling up a bit more.

This issue seems happend from version 1.2.4. I tested on version 1.2.3, it's still OK.

**Comment by andrewnester** [comment]
Could you please verify it on the latest version of Ace (1.15.0)?
