### ISSUE TITLE
Editor and custom snippet, is possible to create a custom snippet that generate a variable bloc depending of a parameter ?

### ISSUE THREAD

**Issue by kegilko** [ajaxorg/ace#4582]
Hello ! first, thank you for this amazing lib thanks that I created an cool online tool for my students :) 

I'm a beginner in creating of custom snippet and I have a question : 

Currently, I can generate a custom html element with a custom snippet I created. In my editor, when I type : 
customSnippet + tab 
I get 
```html
<aCustomTag>
    <aCustomSubField></aCustomSubField>
    <aCustomSubField></aCustomSubField>
    <aCustomSubField></aCustomSubField>
    <aCustomSubField></aCustomSubField>
</aCustomTag>
```
All work perfectly.

Now, I would like manage the number of the `<aCustomSubField></aCustomSubField>` tags when I use a snippet shorcut. Is it possible ? 

The current code of my custom snippet is : 

```js
const snippets = `
snippet tablefull
	<aCustomTag>
		<aCustomSubField></aCustomSubField>
		<aCustomSubField></aCustomSubField>
		<aCustomSubField></aCustomSubField>
		<aCustomSubField></aCustomSubField>
	</aCustomTag>
`;
```

Is it possible to do something like this ? (currently its not work)

```js
const snippets = `
snippet tablefull
	<aCustomTag>
		<aCustomSubField></aCustomSubField>*$1
	</aCustomTag>
`;
```
And from the editor, use the snippet : 

customSnippet2 + tab 

The expected result after press tab: 

```html
<aCustomTag>
    <aCustomSubField></aCustomSubField>
    <aCustomSubField></aCustomSubField>
</aCustomTag>
```

As I am a beginner in creating of custom snippet, I don't if its possible and how I can perform that I'm looking for...

**Comment by nightwing** [comment]
Is this a feature that is supported by other editors?
I think Textmate/Vscode do not support `*$1` syntax, so adding it to snippet syntax may cause problems.

But there is a hacky way to achieve this from javascript

```js
snippetManager = require("ace/snippets").snippetManager
snippetManager.register([{
    name: "customSnippet",
    trigger: customSnippet(\\d*)",
    get content() {
        var count = parseInt(this.matchBefore && this.matchBefore[1]) || 4

        return "<aCustomTag>\n"
           + "\t<aCustomSubField>$1</aCustomSubField>\n".repeat(count)
           +  "</aCustomTag>"
    }
}])
```

**Comment by kegilko** [comment]
Thanks for your help !

> Is this a feature that is supported by other editors?
I don't know, it was an example for explain what Im looking for ;)  

I keep your hacky way in a corner of his head if there will not a better proper solution !

**Comment by kegilko** [comment]
> Thanks for your help !
> 
> > Is this a feature that is supported by other editors?
> 
> I don't know, it was an example for explain what Im looking for ;)
> 
> I keep your hacky way in a corner of my head if there won't be a better solution !

**Comment by akoreman** [comment]
Thanks for opening the issue. Looking at the [textmate snippet syntax](https://macromates.com/manual/en/snippets) we see that this request would diverge our syntax from syntax used by textmate (and VS code). I don't think this is desirable, as such I will close the issue.
