### ISSUE TITLE
Flexible Autocomplete width

### ISSUE THREAD

**Issue by delawere** [ajaxorg/ace#4584]
Hi there!
It is possible to Autocomplete popup using a maximum available width of the container instead of small fixed width?
For example, if I have a very long value for autocompletion I expect the popup to stretch to show me the full text.
![photo_2021-11-23_15-42-34](https://user-images.githubusercontent.com/35735722/143025963-68231dca-976c-47f6-b2e8-42a108a297ea.jpg)

If not, it would be good to use something like [fit-content](https://developer.mozilla.org/en-US/docs/Web/CSS/fit-content) when autocomplete uses all available space, but cannot be larger than the width of the container.

**Comment by WinterSilence** [comment]
It's can be work only if add Ace CSS file(s) after user's CSS file(s).
Fast solution: you can override [.ace_editor.ace_autocomplete](https://github.com/ajaxorg/ace-builds/blob/5e6390ba5d12b21e9b5c88ec17e3baa792c910fc/css/ace.css#L763).
