### ISSUE TITLE
Case-insensitive autocompletion

### ISSUE THREAD

**Issue by delawere** [ajaxorg/ace#4588]
Hi there!
Is it possible to use case-insensitive search in Autocomplete filter? The only way I've found is to dirty patching the sources.
In ext_language_tools I can do this:
```
this.filterCompletions = function(items, needle) {
  // ....
  needle = needle.toLowerCase();
  caption = caption.toLowerCase();
  // ....
```
And it solved my problem.
So, what do you think about adding a new flag to control this option?

Version: 1.4.12

**Comment by mkslanc** [comment]
@delawere Hi! Can't reproduce issue, could you provide some clarification? (and maybe some example)
