### ISSUE TITLE
 format/beautify the rust code 

### ISSUE THREAD

**Issue by arunkumar413** [ajaxorg/ace#4593]
Hi Team,

Currently ace is formatting the code in the below format.

![aceRustFormat](https://user-images.githubusercontent.com/7776779/145712994-b6395659-b79b-406d-9dac-a196bea2a45f.png)

 I would like the beautification in the below format. Any idea on how to achieve this in ace editor?
![rustGtkFormat](https://user-images.githubusercontent.com/7776779/145713021-f4c88d23-4872-474d-a1dd-0e5636ef4afd.png)

**Comment by nightwing** [comment]
The existing [beautify extension](https://github.com/ajaxorg/ace/blob/master/lib/ace/ext/beautify.js ) is mainly for php and related languages.
It is possible to improve that extension, but it may be much easier to compile  https://github.com/rust-lang/rustfmt into wasm.
