### ISSUE TITLE
Bogus Scroll Top Values

### ISSUE THREAD

**Issue by gchallen** [ajaxorg/ace#4595]
I have code that is using the `changeScrollTop` event to listen to changes to the scroll position.

Most of the time this works fine. Scrolling quickly to the top or bottom of an editor generates a small number of scroll events with reasonable offsets.

However, periodically scrolling to the top or bottom of the editor will generate a long sequence of events (I'm throttling to 100ms). In addition, when I check the scroll position of the editor using `getScrollTop`, the values are bogus: either negative (when scrolling to the top), or past the bottom of the editor (when scrolling to the bottom).

Here's some example output:

```sh
// Normal scroll up from 64 -> 0
2021-12-12T17:01:43.320Z: 59.5
2021-12-12T17:01:43.421Z: 0
// Normal scroll down from 0 -> 64
2021-12-12T17:01:44.456Z: 4.5
2021-12-12T17:01:44.557Z: 64
// Normal up again
2021-12-12T17:01:45.507Z: 62.5
2021-12-12T17:01:45.607Z: 0
// Bogus down: many more events
2021-12-12T17:01:46.338Z: 1.5
2021-12-12T17:01:46.439Z: 64
// Including ones with bogus scrollTop positions: 64 is the max, 4 row editor, 8 rows of content, 16px line height
2021-12-12T17:01:46.942Z: 77.5
2021-12-12T17:01:47.043Z: 71.5
2021-12-12T17:01:47.144Z: 68.5
2021-12-12T17:01:47.245Z: 67
2021-12-12T17:01:47.345Z: 65.5
// Finally stabilizes at the correct value
2021-12-12T17:01:47.446Z: 64
```

My current plan is to bound these events based on the editor window size so that we can reject the bogus positions. But something strange is going on here, so I thought I'd report it.

**Comment by nightwing** [comment]
Long list of events can be generated when `animatedScroll` option is enabled, and a key like `ctrl-home` is used. 

Values larger than screen size are reported because clipping is done asynchronously when render is called from requestAnimationFrame.

Could you describe what kind of problems does this behavior create for your code?

**Comment by gchallen** [comment]
> Long list of events can be generated when animatedScroll option is enabled, and a key like ctrl-home is used.

That's not what's happening here. I'm just scrolling normally using the mouse.

> Could you describe what kind of problems does this behavior create for your code?

We're recording scroll position for later replay, and so there are two problems. First, the large number of additional events generated after scrolling has completed visually. I'm already throttling the scroll handler at 100ms, so there are a lot more firings hidden in between the ones shown above.

Second, the bogus scroll positions, which don't work during replay. We can't set the scroll position to a negative value, or one that's beyond the height of the editor.

These aren't hard to filter. My report was mainly in case this was due to a bug in the way that scroll events are fired.
