### ISSUE TITLE
`ace.config.set('basePath', 'path')` error (cdnjs)

### ISSUE THREAD

**Issue by dlv-dls2** [ajaxorg/ace#4597]
I'm creating an HTML project with the ace editor (cdnjs) but I can't set the theme and mode because of `Unable to infer path to ace from script-src, use ace.config.set('basePath', 'path') to enable dynamic loading of modes and themes or with webpack use ace/webpack-resolver` error. Can you please help me? 🙏

**Comment by nightwing** [comment]
Can you show the code you are using to load ace? Are you loading it with script tag or in some other way? 

Also did you try doing `ace.config.set('basePath', 'https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.13/')` as the message is suggesting?

**Comment by web-veera** [comment]
I'm also facing this issue in my react application.

**Comment by RoNUII** [comment]
I also ran into this issue while trying to set up Ace with Vite.

**Comment by RoNUII** [comment]
> I also ran into this issue while trying to set up Ace with Vite.

The solution to the problem is to add the path:
`ace.config.set('basePath', '/node_modules/ace-builds/src-min-noconflict');`

**Comment by proatik** [comment]
Thanks a lot.  @RoNUII
It saved my day. 👌
