### ISSUE TITLE
Ace is taking Rust namespace token identifiers as text

### ISSUE THREAD

**Issue by rohanrhu** [ajaxorg/ace#4600]
Hi, my debugger ([GDBFrontend](https://github.com/rohanrhu/gdb-frontend)) is using Ace.

Ace is taking Rust identifiers as `"text"`. So I made this for Rust sources:

https://github.com/rohanrhu/gdb-frontend/blob/52acca28bdc8655b7c80b188b2bd945d79af9e0b/frontend/components/FileTabs/js/FileTabs.js#L811-L819

This may not be a serious problem but I thought you might want to know.

**Comment by AlexanderMisel** [comment]
Can you provide some examples? I think this is a problem with the highlight rule and should be easy to fix.
