### ISSUE TITLE
Scrolling jumping by 9 lines

### ISSUE THREAD

**Issue by xenonii** [ajaxorg/ace#4601]
The scrolling jumps by 9 lines on minimal scroll, making it uncontrollable to scroll predictably. In Windows OS settings, the mouse scrolling is set to minimum. This happens also on the [Ace demos](https://ace.c9.io/).  I first I thought it was perhaps because of the Magic Mouse, but I tried two other Microsoft common mice, and the behaviour is the same. It just jumps by 9 as soon as I scroll the wheel by one "click". I don't see this behaviour in any other app though.

As a workaround, I tried the following as suggested by the developer of GMEdit:
opened ace.js in a text/code editor, found this bit (around line 1503 as of writing), and edited the factor to be a higher value. 64 worked fined.

```
    if ("onmousewheel" in el) {
        exports.addListener(el, "mousewheel", function(e) {
            var factor = 8;
            if (e.wheelDeltaX !== undefined) {
                e.wheelX = -e.wheelDeltaX / factor;
                e.wheelY = -e.wheelDeltaY / factor;
            } else {
                e.wheelX = 0;
                e.wheelY = -e.wheelDelta / factor;
            }
            callback(e);
        });
```

I also added a console.log(e.wheelDeltaX, e.wheelDeltaY, e.wheelDelta) and the values when scrolling were:
```
ace.js:1513 0 -300 -300

ace.js:1513 0 -1200 -1200

ace.js:1513 0 -1500 -1500

ace.js:1513 0 -600 -600

3ace.js:1513 0 -300 -300

ace.js:1513 0 -2400 -2400

ace.js:1513 0 -300 -300

ace.js:1513 0 -900 -900

3ace.js:1513 0 -300 -300

ace.js:1513 0 -1200 -1200

ace.js:1513 0 -300 -300

ace.js:1513 0 -1200 -1200

2ace.js:1513 0 -900 -900

2ace.js:1513 300 0 300

7ace.js:1513 0 300 300

40ace.js:1513 0 -300 -300

ace.js:1513 300 0 300

15ace.js:1513 0 -300 -300

ace.js:1513 300 0 300
```

**Comment by nightwing** [comment]
Usually wheelDelta reports much smaller values
Could you try running the following code in console and checking what it prints when scrolling ace and when scrolling some normal element
```js
window.addEventListener("wheel", function(e) {
    console.log(`type: ${e.type}, deltaY: ${e.deltaY}, detail: ${e.detail}, ${e.deltaMode}, wheelDelta: ${e.wheelDelta}`)
}, true)
```
maybe deltaY has a more consistent value, or deltaMode is different.
With this code i get something like `type: wheel, deltaY: 100, detail: 0, mode: 0, wheelDelta: -120`

**Comment by xenonii** [comment]
I'm getting the following when scrolling ace. I modified ace.js. I'm not
sure what you mean by "scrolling some normal element".
type: mousewheel, deltaY: -83.33332824707031, detail: 0, 0, wheelDelta: 300
type: mousewheel, deltaY: 83.33332824707031, detail: 0, 0, wheelDelta: -300

**Comment by nightwing** [comment]
Thank you! Could you please check if the linked pull request https://raw.githack.com/ajaxorg/ace/wheel-event/kitchen-sink.html fixes this issue?

**Comment by xenonii** [comment]
Hi,
I just tested that link by copy pasting the code until I got some scrolling
action, and the scrolling was perfect.
Thanks for the fix!
