### ISSUE TITLE
include: $self is not supported

### ISSUE THREAD

**Issue by AlexanderMisel** [ajaxorg/ace#4604]
Many tmlanguage converted modes use `include: $self`, which is not supported by ace editor. Maybe it's better to automatically convert such syntax to a reference to `start` rule.

**Comment by whazor** [comment]
Agreed! This is easily resolved in #5079, and has impact on 9 of our modes.

**Comment by akoreman** [comment]
Closing this issue since #5079 is merged, it will be released in the next Ace release.
