### ISSUE TITLE
HTML editor: literal ">" or "<" inside <code> or <pre>

### ISSUE THREAD

**Issue by GaoOufan** [ajaxorg/ace#4605]
I am expecting the highlighter to recognize "<" and ">" which are inside &lt;code&gt;&lt;/code&gt; tags, but it fail, confusing the system with unclosed tag in a case of "if(x>130) { ... }" line of code inside &lt;code&gt;

Changing ">" to "& gt;" result in wrong presentation in the browser: "if(x& gt;130){ ... }" (note the space after "&" is here just because it will convert it automatically to ">" here in GitHub)

**Comment by nightwing** [comment]
Escaping html characters is handled by browser itself not ace. `if(x&gt;130){ ... }` seems to work correctly here https://jsbin.com/ciranabiwa/edit?html,output. Could you give an example of wrong presentation being displayed?
Alternatively you can use `setValue` or pass value from javascript `editor(element, {value: "if(x>130) { ... }" })`

**Comment by GaoOufan** [comment]
Our issue is about text inside <code> or <pre> which remians "as is" in the browser (and not get parsed) as the intention to showup code marking, like for example: <code>if(EF.$h<88) { ... </code> See the "<":
If I change it to "&lt;" it will be rendered as "<code>if(EF.$h&lt;88) { ... </code>" due to the nature of <code> and <pre>
While leaving it as is causing ACE to just not recognize the "<" as part of the contents of <code> and messing up the markup from that point onward.
![image](https://user-images.githubusercontent.com/6761112/148156052-e967d3d5-eb1d-4e21-8181-add6854753b6.png)

**Comment by nightwing** [comment]
The code tag does not change the way html inside it is parsed (see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/code).  ace shows error on `<code>if(EF.$h<88) { ... </code>` because if instead of 88 there was a variable say `<code>if(EF.$h<a) { ... </code>` the browser would not display the text starting with `<`.
