### ISSUE TITLE
Need help to update PHP worker

### ISSUE THREAD

**Issue by WinterSilence** [ajaxorg/ace#4606]
[PHP manual](https://www.php.net/manual/en/tokens.php):
 > T_* constants values are automatically generated based on PHP's underlying parser infrastructure.

Steps to add PHP8 features: 
1. Adds constants "T_ATTRIBUTE", "T_MATCH" and "T_NAME_FULLY_QUALIFIED" and update  token values
2. Add RegExp's to detecting/parsing new features
3. Fix bug: `T_CHARACTER` removed in PHP7 (long time ago), but yet in worker objects(`PHP.Parser.prototype` and etc.), besides `PHP.Constants`

**Need help**, because I'm don't know how it's work in complex. For example, why list of tokens duplicate in 3-4 places. 
I can help with 1. and 2.
Script generates new `PHP.Constants`: https://3v4l.org/BibCA#v8.1.1

**Comment by nightwing** [comment]
Unfortunately i am not able to provide much help here, as this was a third party contribution based on a php.js project which seems to be abandoned now. 

But perhaps the commit message for the latest update of worker file can help you to figure out how it was generated   https://github.com/ajaxorg/ace/commit/5834d8ff8f7e29357bb7131cc362d8bc703b1eab

**Comment by WinterSilence** [comment]
@nightwing PHP code in #5834d8f is fake/not complete: for example, constant `RESULT_FILE` never used. 
We can use [rebuildParsers.php](https://github.com/nikic/PHP-Parser/blob/master/grammar/rebuildParsers.php) with custom `*.template` files to generate JS parser(s)
**Need help** to convert [PHP template](https://github.com/nikic/PHP-Parser/blob/master/grammar/parser.template) into  something like [kmyacc.js.parser](https://github.com/niklasvh/php.js/blob/master/grammar/kmyacc.js.parser).
