### ISSUE TITLE
Add Support for the Chaining Operator '?.'

### ISSUE THREAD

**Issue by szediwy** [ajaxorg/ace#4609]
Add support for the chaining operator in the javascript mode.

The operator is described here:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

At the moment the behavior looks like:
![image](https://user-images.githubusercontent.com/4198982/148252803-59f26793-2778-4bc3-ab77-5184973f31da.png)

**Comment by AlexanderMisel** [comment]
Ace editor uses jshint for syntax checking. As 'Optional chaining' is only available in ES11, the jshint in Ace should be updated to support this.

**Comment by szediwy** [comment]
> The jshint library can be updated following steps described in this [PR](https://github.com/ajaxorg/ace/pull/4240).

I tried to follow the steps ... Thanks for feedback.

**Comment by justplayd** [comment]
Were you able to fix it?

**Comment by andrewnester** [comment]
Released in 1.10.0
