### ISSUE TITLE
save on ctrl + s

### ISSUE THREAD

**Issue by llabbasmkhll** [ajaxorg/ace#4612]
please add saving when `ctrl + s` pressed

**Comment by AlexanderMisel** [comment]
Where do you want to save? You can add custom commands to fit your needs.

**Comment by llabbasmkhll** [comment]
i use ace in a Cpanel for my shared host . when ever i press `ctrl + s` it promp chromes save html to file which is so annoying . can this be solved ?

**Comment by AlexanderMisel** [comment]
https://stackoverflow.com/questions/11000826/ctrls-preventdefault-in-chrome

**Comment by inyourface34456** [comment]
Hear is an implementation of ace that allows for saving within the [editor](https://ace-code-etitor.donoldjtrump.repl.co/). Ctrl-S for saving, Ctrl+Shift+L for loading.  The slot name MUST be identical.
