### ISSUE TITLE
How to disable double space to trigger a period

### ISSUE THREAD

**Issue by elgs** [ajaxorg/ace#4616]
Not sure if this is a feature or a bug, I found when I press the space key twice, it always put a period in the editor. This is reproducible in the kitchen sink (https://ace.c9.io/build/kitchen-sink.html). Is there a way this can be disabled?

**Comment by elgs** [comment]
I found this happens only with macOS. But this doesn't happen in other text editors like Sublime Text.

**Comment by nightwing** [comment]
This is a mac os feature that can be disabled from preferences https://howchoo.com/macos/disable-double-space-bar-period-dot-macos

**Comment by elgs** [comment]
Thanks @nightwing, it works! But interesting it doesn't happen in every text editor in macOS. It seems it happened to me only in ace editor.

**Comment by andrewnester** [comment]
We don't have plans to diverge from the default OS X behaviour in this case, closing the issue
