### ISSUE TITLE
Update method of dynamic marker not called because Range is always defined in MarkerLike type (Typescript)

### ISSUE THREAD

**Issue by leandroberetta** [ajaxorg/ace#4626]
Hello, in Kiali project we are trying to implement the dynamic markers features for the editor, highlighting some words and including some html code to achieve something like the following:

https://codepen.io/oatssss/pen/oYxJQV?editors=0010

The only difference is that we are using Typescript and when we implemented this, we saw that the addDynamicMarker function requires a marker of type MarkerLike, where the Range is not optional, it must be passed when using this function:

![ace-kiali](https://user-images.githubusercontent.com/1286393/151981171-92e310d5-0e03-48e1-8cc1-2202b5fe48ed.png)

Looking a little bit into the Ace code, I see that Range is not optional:

![ace-markerlike](https://user-images.githubusercontent.com/1286393/151981250-e9df1ec6-f494-4e44-a30f-845cb4ddf012.png)

And that in the code that update the markers and calls the update funciton is not is undefined, is skipping the call because range is not undefined:

![ace-update](https://user-images.githubusercontent.com/1286393/151981335-d9d7cff9-f17a-4954-b318-643d93b8d295.png)

Am I wrong or the Range field should be optional for the dynamic marker's update method works?.

**Comment by andrewnester** [comment]
Released in 1.9 version
