### ISSUE TITLE
Part of the web page appears in google

### ISSUE THREAD

**Issue by godlikeSwan** [ajaxorg/ace#4639]
### So when I follow this link
![image](https://user-images.githubusercontent.com/14862534/154793878-53fbc22a-64a1-4b33-a936-104a962a1ea3.png)

### It shows that page
![image](https://user-images.githubusercontent.com/14862534/154793941-373b5deb-906d-44f9-9fe1-8d84dc78f42b.png)

May be this is okay because there is link to the main website on the page but I guess this is not what regular user would expect

**Comment by nightwing** [comment]
This was fixed by https://github.com/ajaxorg/ace/pull/4900
