### ISSUE TITLE
Getting marker exact position

### ISSUE THREAD

**Issue by danimnh** [ajaxorg/ace#4643]
Hello, I've been using ACE for a while and I think It's awesome!

I have a question though,

![image](https://user-images.githubusercontent.com/39585094/155725282-a02c7c4e-7020-4ae2-af0a-2a7e5606646e.png)

Is there any way that I can get the exact style position (`top, left`) of my marker? I can't use the `row, col` because I have a few lines being folded & hidden and that makes calculating the `top` & `left` unreliable for me.

I tried to get the element by javascript but the `HTMLCollection` returns undefined for me.

-----

- Adding my marker

```
editorLearner.session.addMarker(markerRange, "highlight", "background");
```

- Getting my marker
```
let highlights = document.getElementsByClassName("highlight");

console.log(highlights);
console.log(highlights.length);
```

-----
I got the elements but the `length` is 0. I did make sure the DOM is updated though. Is there any other way?
![image](https://user-images.githubusercontent.com/39585094/155726000-60fb81b5-9990-4d9c-87cc-efb25b97b089.png)

This is my first time posting issues/getting help online so thank you for answers!

**Comment by nightwing** [comment]
There is `editor.renderer.textToScreenCoordinates(row, column)` method to get pixel positions from row and column.

How do you want to use top and left? knowing that may help to find a more convenient method.

**Comment by danimnh** [comment]
@nightwing Thanks for the quick reply! I was trying to replicate a focus state on the editor (the blinking cursor while typing) without the keyboard prompt on mobile-side.

**Comment by nightwing** [comment]
`editor.onFocus()` method may be more useful for that https://github.com/ajaxorg/ace/blob/v1.4.14/lib/ace/editor.js#L731
