### ISSUE TITLE
Is there a way to add custom margin/height for specific lines?

### ISSUE THREAD

**Issue by rohanrhu** [ajaxorg/ace#4644]
Hi, is there a way to set custom space between specific lines?

Like this:
![image](https://user-images.githubusercontent.com/1125150/155849896-89f42494-7867-4f3d-b473-18faeee2b80f.png)

**Comment by nightwing** [comment]
There is no api specifically for this, but it is possible to add empty
lineWidgets with rowCount and without dom element, similar to the way difff
view does here
https://github.com/c9/core/blob/7e1ac98f51b85e8bed401c593774ef73ada3cd07/plugins/c9.ide.scm/diff/twoway.js#L248

**Comment by rohanrhu** [comment]
> There is no api specifically for this, but it is possible to add empty lineWidgets with rowCount and without dom element, similar to the way difff view does here https://github.com/c9/core/blob/7e1ac98f51b85e8bed401c593774ef73ada3cd07/plugins/c9.ide.scm/diff/twoway.js#L248

Oh.. thank you 😱 I'm using Ace Editor in my debugger: https://github.com/rohanrhu/gdb-frontend

I will add a feature for split view as source - disassembly. 😊
