### ISSUE TITLE
Shortcut LUA block-comments uses single square brackets instead of the required double square brackets

### ISSUE THREAD

**Issue by Sarcas666** [ajaxorg/ace#4646]
Block comments shortcut ( SHIFT-CTRL-/ ) creates:

```
--[blabla
blabla
blabla]--
```

instead of 

```
--[[blabla
blabla
blabla]]--
```

Single square brackets obviously causes errors.

**Comment by nightwing** [comment]
Should the closing symbol be `]]--` ? Sublime text uses `--]]` and VSCode uses  just`]]`

**Comment by Sarcas666** [comment]
Sorry, I overlooked the reply.

“A comment starts anywhere with a double hyphen (--) and runs until the end of the line. Lua also offers block comments, which start with --[[ and run until the corresponding ]]. A common trick, when we want to comment out a piece of code, is to write the following:”

Source: [https://www.lua.org/pil/1.3.html](https://www.lua.org/pil/1.3.html)
