### ISSUE TITLE
Fast Scrolling speeds not supported on Firefox

### ISSUE THREAD

**Issue by janik6882** [ajaxorg/ace#4647]
### Describe the bug

Scrolling in Web Editor not working with at faster speeds for hardware supporting those speeds.

### To Reproduce

1. Click on the Code which shall be edited
2. Scroll down/up in Editor using a mouse supporting fast Scrolling (Tested using Logitech MX Master)
3. Scrolling Stops and continues in main Page (outside editor)

### Expected behavior

By user (which I am) scrolling would be expected to continue, not abruptly stop. Bug does not occur when scrolling through Web Editor File Browser

### What browsers are you seeing the problem on?

Firefox

### Additional context

Tested on Logitech MX Master, Firefox 97.0.1 (64-Bit), Windows 10, poses no Problem on standard html Input tag on other websites.

### Further Details

Happened in Editor embedded in https://github.com/ls1intum/Artemis/ , Issue opened under https://github.com/ls1intum/Artemis/issues/4777 but Member says Bug seems not to be on side of artemis (view reply here: https://github.com/ls1intum/Artemis/issues/4777#issuecomment-1059771646 ).
For further Information on please reffer to https://github.com/ls1intum/Artemis/

**Comment by nightwing** [comment]
Could you please check if  https://raw.githack.com/ajaxorg/ace/wheel-event/kitchen-sink.html from [this ](https://github.com/ajaxorg/ace/pull/4611) pull request fixes the issue for you?

**Comment by janik6882** [comment]
> Could you please check if https://raw.githack.com/ajaxorg/ace/wheel-event/kitchen-sink.html from [this ](https://github.com/ajaxorg/ace/pull/4611) pull request fixes the issue for you?

I was unable to reproduce the bug under the mentioned Link.

**Comment by andrewnester** [comment]
Fixed in 1.50.0 version
