### ISSUE TITLE
Soft Tabs working as tabs

### ISSUE THREAD

**Issue by striwensko** [ajaxorg/ace#4650]
I need to disable all tabs  and transform the tabs into space. I tried to use soft tabs however i click on the tab and the tab character is still a tab. Im using:
editor.setOptions({
        enableBasicAutocompletion: true,
        // enableLiveAutocompletion: true,
        enableSnippets: true,
        showLineNumbers: true,
        tabSize: 4,
        theme: "ace/theme/monokai",
        useSoftTabs: true,
      });

Also another question will this fix when a text is being paste to remove tab values too?

**Comment by nightwing** [comment]
useSoftTabs option controls the behavior of tab key.

If you want to convert indentation of existing text use 
```
require("ace/ext/whitespace").convertIndentation(session, "\t", 4)
```
There is no way to do this for paste event use

```
editor.on("paste", function(e) {
   e.text = e.text.replace(/^\t+/gm, function(t) {
       return " ".repeat(t.length * 4) 
   })
})
```
