### ISSUE TITLE
support unicode property escapes in tokenizer

### ISSUE THREAD

**Issue by kevinushey** [ajaxorg/ace#4653]
It could be useful if Ace supported Unicode property escapes in its tokenizer, as described in https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Unicode_Property_Escapes.

Rules could include a `unicode` property to indicate if the pattern should be treated as a Unicode regular expression.

**Comment by kevinushey** [comment]
I'm trialing a small patch of the following form:

```
diff --git lib/ace/tokenizer.js lib/ace/tokenizer.js
index 23126595..ffe3866c 100644
--- lib/ace/tokenizer.js
+++ lib/ace/tokenizer.js
@@ -62,8 +62,10 @@ var Tokenizer = function(rules) {
             var rule = state[i];
             if (rule.defaultToken)
                 mapping.defaultToken = rule.defaultToken;
-            if (rule.caseInsensitive)
-                flag = "gi";
+            if (rule.caseInsensitive && flag.indexOf("i") === -1)
+                flag += "i";
+            if (rule.unicode && flag.indexOf("u") === -1)
+                flag += "u";
             if (rule.regex == null)
                 continue;
```

and it seems to work well, although existing highlight rules might need to be tweaked a little to support these. (The main issue we saw locally is that non-necessary escapes are treated as errors, e.g. things like `\'` or `\-`.)

**Comment by nightwing** [comment]
Did the escape issue cause problems for all highlight rules or only the ones that actually use `u`?

If the later, we can apply this patch and update the old rules only when required.

**Comment by kevinushey** [comment]
> Did the escape issue cause problems for all highlight rules or only the ones that actually use u?

Fortunately, only the ones using `u`.
