### ISSUE TITLE
API pages (`/api/*.html`) not reflect real code

### ISSUE THREAD

**Issue by WinterSilence** [ajaxorg/ace#4655]
Current API pages (`/api/*.html`) not reflect real code. 
For example: missed parameter `options` for [ace.edit](https://github.com/ajaxorg/ace/blob/master/api/ace.html).

Need generate API pages by [JSDoc](https://jsdoc.app/about-getting-started.html) on publish new release.

**Comment by nightwing** [comment]
This was fixed by https://github.com/ajaxorg/ace/pull/4900 https://ajaxorg.github.io/ace-api-docs/modules.html#edit
