### ISSUE TITLE
Question - Autocomplete

### ISSUE THREAD

**Issue by anonimo82** [ajaxorg/ace#4657]
Hello everyone.
Given this code snippet:

```
<!DOCTYPE html>
<html>
	<body>

		<canvas id="myCanvas" width="200" height="100" style="border:1px solid #d3d3d3;">
			Your browser does not support the HTML canvas tag.
		</canvas>

		<script>
			/** @type {HTMLCanvasElement} */
			var canvas = document.getElementById("myCanvas");
			var ctx = canvas.getContext("2d");
			ctx.moveTo(0,0);
			ctx.lineTo(200,100);
			ctx.stroke();
		</script>
	</body>
</html>
```

I don't get right ctx autocomplete hints.
Why?

As a sidenote, I got this code from w3schools, I'm using KitchenSink, and the type annotation is from another issue about JavaScript. (Link: https://github.com/microsoft/vscode/issues/136717)

FYI, look at this screenshot from Code-Server:
[click](https://pasteboard.co/4NjdZ1VCRxKk.jpg)

And here's the ACE result for the same code (note, I'm using the same code as above for both screenshots)
[click](https://pasteboard.co/od0krCWAbIz0.jpg)

**Comment by WinterSilence** [comment]
@nightwing this guide already exist in wiki, but missed on site.

**Comment by anonimo82** [comment]
@nightwing no, thanks anyhow

**Comment by WinterSilence** [comment]
@anonimo82 https://github.com/ajaxorg/ace/wiki/How-to-enable-Autocomplete-in-the-Ace-editor

**Comment by WinterSilence** [comment]
@anonimo82 if you want i can show my autocomplete for php
