### ISSUE TITLE
Hash symbol in tag property ruins all format

### ISSUE THREAD

**Issue by hswhsw610** [ajaxorg/ace#4659]
![image](https://user-images.githubusercontent.com/48399282/159153649-7512a65f-4e5a-43e5-8979-6396c6709e7a.png)
as you can see, after hash symbol, all strings all turns into green.
why i take this serious? cause thiis ruins beautify too.

**Comment by hswhsw610** [comment]
> For which mode does this happen?

Oh i didnt describe that..
Well i am using php blade

**Comment by hswhsw610** [comment]
@nightwing bump

**Comment by nightwing** [comment]
It appears that our blade highligter https://github.com/ajaxorg/ace/blob/master/lib/ace/mode/php_laravel_blade_highlight_rules.js#L53 includes `#` `//` `/**/` as comments alongside `{{-- --}}`

Do you know if in the following code example `//` should be treated as comment or if we should simply remove the extra comment types?

```php.blade
        @env('local')
            // The application is in the local environment...
        @elseenv('testing')
            // The application is in the testing environment...
        @else
            // The application is not in the local or testing environment...
        @endenv
```

**Comment by hswhsw610** [comment]
@nightwing
those symbols are still used to comment since its php native syntax

**Comment by hswhsw610** [comment]
@nightwing 
bump again

**Comment by hswhsw610** [comment]
Ok it seems it is all fixed and there is no more bugs.
thanks! but when will it be released?
