### ISSUE TITLE
Load existing file

### ISSUE THREAD

**Issue by nycrofox** [ajaxorg/ace#4660]
Hi!

I have the following problem. I have an Ace editor with which I can edit local files at the moment. But now I want to call files from a server. How do I do that? At the moment I read the contents of a file with PHP and store it in a variable. Now I want to load this content into the editor. Or is there a more elegant solution?

How is it possible to save these changed files also on the server?

Please only helpful suggestions and no spiteful comments!

Thanks in advance, Greetings!

**Comment by nightwing** [comment]
Hi
ace only provides editing ui (similar to a textarea but better). Loading and saving of files is outside the scope of functionality provided by ace.

**Comment by nycrofox** [comment]
And with the default_content?

**Comment by nycrofox** [comment]
<script>ace.require("ace/ext/language_tools");var editor=ace.edit("editor");ace.require('ace/ext/settings_menu').init(editor);var editor_cnt=1,editor_index=1,active_editor=1,editor_session=[];var request,init_ts,open_file_name;var lang='python3';default_content="<?=$the_code?>";

**Comment by nightwing** [comment]
To save you need to make an xhr request to the server, and on the server write the file to.

Maybe the following code from the kitchen-sink demo can be a useful direction: 
https://github.com/ajaxorg/ace/blob/master/demo/kitchen-sink/doclist.js#L187 

https://github.com/ajaxorg/ace/blob/master/static.js#L44

**Comment by nycrofox** [comment]
the text is read from a file. do i have to do this via javascript? because at the moment i do this via PHP...

**Comment by nycrofox** [comment]
How can I insert that there then? With PHP the editor is only grayed out and I can't enter anything. With PHP I can not solve the whole thing unfortunately...

My code is the following:

`editor.session.setValue("<?=$the_code?>") `

**Comment by nycrofox** [comment]
![Screenshot (2)](https://user-images.githubusercontent.com/89037664/159353711-e42c6e92-da9f-482c-a92f-59a66c4e72ef.png)

**Comment by nightwing** [comment]
If you need to open more than one file you need to do it via javascript like this: https://github.com/ajaxorg/ace/blob/master/demo/kitchen-sink/doclist.js#L166

**Comment by nycrofox** [comment]
no, i only need to open one file from a server. how can i do that? Please help me!

**Comment by nycrofox** [comment]
But thank you for all you last comments!

**Comment by ninezero90hy** [comment]
You can just read the file in PHP and put it in the editor.

Find out how to read files in PHP.

https://github.com/ajaxorg/ace/issues/4660#issuecomment-1074081731

That already told you the solution in the comments. 

@nycrofox Calmly search for solutions in order.

**Comment by nycrofox** [comment]
Is there a javascript code that opens a file immediately? e.g.

`editor.openFile('PathToFile')`

**Comment by ninezero90hy** [comment]
@nycrofox Please refer to this.
- https://www.w3schools.com/php/func_filesystem_readfile.asp
- https://stackoverflow.com/questions/5895842/how-to-assign-php-variable-value-to-javascript-variable
