### ISSUE TITLE
How fix basic autocomplete?

### ISSUE THREAD

**Issue by WinterSilence** [ajaxorg/ace#4665]
How filter by full words only?
![изображение](https://user-images.githubusercontent.com/3521094/160224946-ed448c6b-2902-469a-9e68-ac3a2c1363ac.png)
How filter case-sensative(hide `array_...` or `..._array` at `Array`)?

**Comment by nightwing** [comment]
there is an undocumented option 
```js
var Autocomplete = ace.require("ace/autocomplete").Autocomplete;
var completer = Autocomplete.for(editor);
editor.completer.exactMatch = true
```

**Comment by WinterSilence** [comment]
@nightwing thanks! it's work fine
