### ISSUE TITLE
How to delete EditSession's ?

### ISSUE THREAD

**Issue by danimnh** [ajaxorg/ace#4668]
Is there any way to get all existing EditSession(s) ?
I'm currently optimizing my app to be deleting Editor instances and EditSessions on component destroy.
However, I noticed that the `session.id` is just keep incrementing and I think there's no way to detect that previous's ID have been destroyed succesfully? I checked my chrome devTools on Memory Tab that it keeps making new sessions

**Comment by nightwing** [comment]
the id is supposed to increase with each session

to keep track of all created and deleted edit sessions you can use the following code
```js
allSessions = {}
ace.config.on("session", function(session) {
    if (allSessions[session.id]) throw "this can't happen"
    allSessions[session.id] = session
    session.on("destroy", unregister)
})
function unregister(session) {
    delete allSessions[session.id]
}

// workaround for missing destroy event on session
if (!EditSession.prototype.destroy_orig) {
    EditSession.prototype.destroy_orig = EditSession.prototype.destroy
    EditSession.prototype.destroy = function() {
        this._signal("destroy", this)
        this.destroy_orig()
    }
}
```
