### ISSUE TITLE
Get Autocomplete's suggestion in array

### ISSUE THREAD

**Issue by danimnh** [ajaxorg/ace#4671]
I'm trying to create a suggestion / autocomplete bar on top of my keyboard while I'm typing on my mobile. I guess one way to make this happens is somehow I need to fetch the Array / any type that is used to render the `editor.popup` dropdowns on the Autocomplete.

I don't think there's a documentation on that? Or is it currently not accessable? Anything that links to this could help! Thanks!

**Comment by nightwing** [comment]
maybe you can override [updateCompletions](https://github.com/ajaxorg/ace/blob/v1.4.14/lib/ace/autocomplete.js#L269) and [openPopup]( 
https://github.com/ajaxorg/ace/blob/v1.4.14/lib/ace/autocomplete.js#L43) methods of autocomplete

**Comment by danimnh** [comment]
> maybe you can override [updateCompletions](https://github.com/ajaxorg/ace/blob/v1.4.14/lib/ace/autocomplete.js#L269) and [openPopup](https://github.com/ajaxorg/ace/blob/v1.4.14/lib/ace/autocomplete.js#L43) methods of autocomplete

Seems that I can only override stuff on the `language_tools.js` and not on Autocomplete, do you have an example on how to do it?

This is my attempt to override `language_tools`:
```
      let langTools = ace.acequire("ace/ext/language_tools");

      langTools.snippetCompleter.getCompletionsOrig =
        langTools.snippetCompleter.getCompletions;

      langTools.snippetCompleter.getCompletions = function (
        editor,
        session,
        pos,
        prefix,
        callback
      ) {
        console.log("MyCode");
        return this.getCompletionsOrig(editor, session, pos, prefix, callback);
      };
```

**Comment by nightwing** [comment]
you can do
```js
var {Autocomplete} = ace.acequire("ace/autocomplete")
Autocomplete.prototype.openPopup = ...
```
or to change it for only one editor instance
```js
Autocomplete.for(editor).openPopup = ...
```
