### ISSUE TITLE
this is a error when i use type=json

### ISSUE THREAD

**Issue by lush-99** [ajaxorg/ace#4676]
![image](https://user-images.githubusercontent.com/77112588/162922866-c13d8ff7-34f6-4c2d-8e32-45edcbee73f7.png)
![image](https://user-images.githubusercontent.com/77112588/162922980-8cc9bd9b-9b98-43b5-b4e3-aef544e64bb8.png)
when i use mode="json" that have a error

**Comment by andrewnester** [comment]
I wasn't able to reproduce it on my side, could you please provide some minimal reproduction example? Also it seems like the issue might be related to [react-ace](https://github.com/securingsincity/react-ace)
