### ISSUE TITLE
CSP Violation causes <head> to be ignored

### ISSUE THREAD

**Issue by AlexSCorey** [ajaxorg/ace#4678]
I am trying to set up a Content Security Policy for `style-src` via a nonce value.  It seems though as if age is injecting a <style> tag at build time into the <head> tag.  This causes fire fox to throw a warning that says the <head> tag will be ignored invalidating the whole csp.  We have styling for the editor to be github style and it seems that styling is also begin ignored. 

I am on ace-builds version 1.4.12 and react-ace version 9.5.0

![Screen Shot 2022-04-14 at 1 20 16 PM](https://user-images.githubusercontent.com/39280967/163440955-c4ae6f3c-60c3-4ff3-a380-f7730649d17b.png)
![Screen Shot 2022-04-14 at 1 19 53 PM](https://user-images.githubusercontent.com/39280967/163440959-18d61d66-f948-4427-9050-358fb9b4cb21.png)

**Comment by nightwing** [comment]
in version 1.4.14 https://github.com/ajaxorg/ace/blob/master/demo/csp.html#L23 it is possible to use `ace.config.set("useStrictCSP", true);` before creating editors and load required css via link 

We can add support for specifying nonce as well, if css is hard to use.

**Comment by AlexSCorey** [comment]
@nightwing we have very little css in our project and tend of offload that code to external libraries.  Support for a `nonce` would be awesome!
