### ISSUE TITLE
Disaster data recovery from browser's cache?

### ISSUE THREAD

**Issue by schweini** [ajaxorg/ace#4679]
So the mini datacenter where all my servers where stationed burned down. I used Ace.js to edit files directly on the server using my (Chrome) browser at home.

I lost quite a couple of rather important programs.

I was wondering if, maybe, there might be something from the files I edited with Ace.js left in my browser's cache or localstorage or whereever?

Thanks for any help.

**Comment by nightwing** [comment]
Ace by itself is roughly equivalent to an improved textarea, it doesn't
provide functionality to edit files or save data.

So there must have been some other software that used ace to display files.
Maybe it have saved data somewhere.

**Comment by schweini** [comment]
Yes, on the server side I had some perl script doing the actual saving on the server's hard drive.

Exactly since ace.js is kind of a <textarea>, I was wondering if Chrome saves that data somewhere, e.g. to recover a browser crash. Or if ace.js itself uses some local cacheing.

**Comment by nightwing** [comment]
Sadly neither ace nor chrome save the text in the editor. In the best case there may be cache of downloaded files (which can be accessed from devtools https://developer.chrome.com/docs/devtools/storage/cache/, or one of cache viewer extensions), but usually such requests have nocache header.
