### ISSUE TITLE
Cannot read properties of null (reading 'getFoldAt')

### ISSUE THREAD

**Issue by KVPasupuleti** [ajaxorg/ace#4680]
We are catching the errors in Sentry and the trace showed that the error is at

```
TypeError: Cannot read properties of null (reading 'getFoldAt')
  at moveCursorTo(../node_modules/ace-builds/src-noconflict/ace.js:5375:33)
  at moveCursorToPosition(../node_modules/ace-builds/src-noconflict/ace.js:5372:14)
  at moveToPosition(../node_modules/ace-builds/src-noconflict/ace.js:4999:14)
  at handleLongTap(../node_modules/ace-builds/src-noconflict/ace.js:3173:30)
  at r(../../src/helpers.ts:87:17)
```
  
  When I check this in the code, I can find this code in `selection.js`
  
```
  this.moveCursorTo = function(row, column, keepDesiredColumn) {
        // Ensure the row/column is not inside of a fold.
        var fold = this.session.getFoldAt(row, column, 1);
        .
        .
        .
    };
```
   
   The session is null while accessing.
   
   So, I checked where we are making the session null. I found this in `range_list.js`
   
```
   this.detach = function() {
        if (!this.session)
            return;
        this.session.removeListener('change', this.onChange);
        this.session = null;
    };
```

As `moveCursorTo` will be called when `touchStart` event starts after a timeout of 450ms, I assume the edit session is getting null before the code reaches `getFoldOf`.  
   
As the user is in an interaction with the editor with the touch event, I don't think the component has unmounted abrupty (In React Terminology).

All I could think of is a reload, but I am not sure this is the root.

Any reason or a fix for this issue? 

Not only this, we are getting similar issues like this at some other locations. 

How about checking if there is a session actually before accessing the session's keys?

**Comment by venkatasrikanthkarri** [comment]
@andrewnester 

We got the similar error reported in sentry

The trace shows error as below

![Image Pasted at 2022-6-2 12-09](https://user-images.githubusercontent.com/38688446/171568705-aeaa47fc-3e36-4c97-80f5-40f806005432.png)

It is reported to sentry when user clicked on `div.ace_scroller > div.ace_content`

**Comment by andrewnester** [comment]
@venkatasrikanthkarri the issue you mentioned (bgTokenizer one) is fixed here and was released in latest NPM version https://github.com/ajaxorg/ace/issues/4711

This issue is different from #4711
