### ISSUE TITLE
Cannot load worker if its URL is cross-origin in Chrome and Firefox

### ISSUE THREAD

**Issue by dimovpetar** [ajaxorg/ace#4683]
Hello,

When the origin from which ace is loaded is different there is an exception in some browsers, and the worker is not loaded.
Exception: <b>Could not load worker DOMException: Failed to construct 'Worker': ... </b>
This problem occurs when strict CSP mode is used. In this case blob cannot be used, hence `ace.config.set("loadWorkerFromBlob", false)` is configured and loading the worker with URL is the only option. Looks like cross-origin URLs cannot be used to construct workers in this case. I couldn't make isolated example, because there is no CDN for the CSS of ace. So you can check this out - https://codesandbox.io/s/codeeditorissuesapui5-hqwdh?file=/index.html. It shows the ace editor wrapped by CodeEditor class. 
![image](https://user-images.githubusercontent.com/32839090/165765036-9bb8e902-8aee-47ec-b18f-934c18b81993.png)

We managed to workaround this problem by modifying the ace code to run workers inside iframe. All the communication between the worker and the main window goes through `window.postMessage`. You can check our solution here https://github.com/SAP/openui5/commit/74ef7ed26553213a7e36cbec67ad0f257335019d
Would be nice to see this solution with improved code incorporated in the ace itself.

Best regards,
Petar

**Comment by andrewnester** [comment]
Thanks for reporting the issue to us @dimovpetar 
As there is a workaround for the issue I categorised it as a feature request
