### ISSUE TITLE
YAML: keys following multiline strings not tokenized as expected

### ISSUE THREAD

**Issue by kevinushey** [ajaxorg/ace#4694]
### Describe the bug

Given the following YAML:

```
key-1:
    key-2: |
        This is a multi-line string.
    key-3:
```

The `key-3:` part is tokenized just as plain text.

<img width="314" alt="Screen Shot 2022-05-10 at 1 28 41 PM" src="https://user-images.githubusercontent.com/1976582/167716422-3da3b3a5-3668-4936-9031-e4b75ef2da63.png">

### Expected Behavior

The item should be tokenized as a key, as with other keys.

### Current Behavior

(see description above)

### Reproduction Steps

(see description above)

### Possible Solution

I can't quite parse out from the YAML specification as to what's considered "valid" for a key, but I'm guessing that any collection of non-syntactic characters would be valid.

### Ace Version

Kitchen sink.

**Comment by andrewnester** [comment]
it seems like it might have been fixed by this PR already but kitchen sink was not yet updated
https://github.com/ajaxorg/ace/pull/3919

**Comment by andrewnester** [comment]
NVM, seems to still be reproducible on 1.5.0 and recent kitchen sink

**Comment by andrewnester** [comment]
Has been release in 1.5.1
