### ISSUE TITLE
ext-beautify doesn't format JSON code well

### ISSUE THREAD

**Issue by LidiyaGeorgieva** [ajaxorg/ace#4701]
### Describe the bug

The beautifier doesn't do well with formatting JSON (it is OK with javascript).
Example:
```
var editor = ace.edit("editor");
var beautify = ace.require("ace/ext/beautify");

editor.getSession().setMode("ace/mode/javascript");
editor.setValue(JSON.stringify({"a":1, "b":2}));
```

### Expected Behavior

I would expect that it inserts new lines like:
```
{
    "a": 1,
    "b": 2
}
```

### Current Behavior

Results in the following output:
```
{
    "a":1,"b":2
}
```

### Reproduction Steps

open jsfiddle: https://jsfiddle.net/240kdos3/
press "pretty print" button to see the result

### Ace Version

1.5.0

**Comment by andrewnester** [comment]
Also reproducible on older version of Ace

**Comment by andrewnester** [comment]
Has been release in 1.5.1

**Comment by tcstory** [comment]
@andrewnester  where is the 1.5.1 ? i can only find 1.5.0 in ace-builds

**Comment by andrewnester** [comment]
latest one is 1.10 https://www.npmjs.com/package/ace-builds
