### ISSUE TITLE
https://www.online-python.com/: Vulnerability : you can see every file hosted on this server

### ISSUE THREAD

**Issue by SarveshGuptaPythonist** [ajaxorg/ace#4704]
### Describe the bug

When I was seeing this website, I wrote a python script using os module to see into your system and got this issue. Here using this code you can see and change any file on server. by adding 2-3 commands on it.
`import os
 os.chdir('/home/repl')
for i, j, k in os.walk(os.getcwd()):
    for l in k:
        print(f'{i}/{l}')
for i, j, k in os.walk(os.getcwd()):
    for l in k:
        print(f'{i}/{l}')
        try:
            f = open(f'{i}/{l}')
            print(f.read())
            f.close()
            print('\n\n')
        except:
            pass`

### Expected Behavior

I expect it to not show or fail. 

### Current Behavior

It shows every library on server. and every file on server.

### Reproduction Steps

The code I gave you will reproduce it.

### Possible Solution

disable os module. restrict any module which will somehow access to your code.

### Ace Version

v1.5.0

**Comment by SarveshGuptaPythonist** [comment]
import os
os.chdir('/')
for i, j, k in os.walk(os.getcwd()):
    for l in k:
        print(f'{i}/{l}')
for i, j, k in os.walk(os.getcwd()):
   for l in k:
      print(f'{i}/{l}')

**Comment by andrewnester** [comment]
Ace editor is just a code editor and not IDE and we don't control any language related functionality or modules thus we can't disable any language features

**Comment by SarveshGuptaPythonist** [comment]
So, where Do I raise this issue?

**Comment by SarveshGuptaPythonist** [comment]
@andrewnester where Do I raise this issue?

**Comment by andrewnester** [comment]
Please reach out to whoever maintains online-python.com, they should do this on their server side
