### ISSUE TITLE
(Syntax): (Wrong display)

### ISSUE THREAD

**Issue by npacoder** [ajaxorg/ace#4712]
### Describe the bug

wrong display of text color in jsx . syntax 😭

### Expected Behavior

Please fix it

### Current Behavior

wrong display of text color in jsx . syntax 😭

### Reproduction Steps

No

### Possible Solution

Fix

### Additional Information/Context

No

### Ace Version

No

**Comment by npacoder** [comment]
![Uploading Screenshot_20220528-143413_Acode.jpg…]()

**Comment by andrewnester** [comment]
Please provide details regarding the issue including reproduction steps, expected and current behavior and Ace version used
