### ISSUE TITLE
syntax error in php-mode

### ISSUE THREAD

**Issue by gentlawk** [ajaxorg/ace#4731]
Hello team,

In ace1.4.14 php-mode, ace editor showed syntax error at property with 'readonly' and type declaration.
I think it allows to use 'readonly' and type declaration at the same time in PHP8.1.

    <?php
    
    class A
    {
        public int $a; // => OK
        public readonly $b; // => OK
        public readonly int $c; // => Syntax Error :( 
    }

Could you fix this?

Best regards.

**Comment by andrewnester** [comment]
Been fixed here https://github.com/ajaxorg/ace/pull/4696 and release in 1.5+ versions

**Comment by gentlawk** [comment]
I can see the problem was fixed at ver1.5.2!!
Thank you very much for your reaction and fix.
