### ISSUE TITLE
`__init__` keyword for python

### ISSUE THREAD

**Issue by jnthbdn** [ajaxorg/ace#4733]
Hi everyone,

I apologize if there is already an issue (or anything else) about it.
I currently use the editor for a project, and I discover that `__init__` (the "constructor" method for python class) keyword is not present in the mode-python file.

Is there a reason? Or it is just an oversight?

Best,

**Comment by andrewnester** [comment]
`__init__` is not really a keyword as per python spec https://docs.python.org/3/reference/lexical_analysis.html#keywords

So it's just a specially named function so we treat it just like as function

**Comment by jnthbdn** [comment]
In the link you sent, it is defined that `__*__` has a "special meaning". That's why I thought it could be added to the list of "keywords".
But I understand your point, thanks for answering this issue!
You make awesome work!
