### ISSUE TITLE
Cannot find module '../../token_iterator'

### ISSUE THREAD

**Issue by Adrian-Bielefeldt** [ajaxorg/ace#4734]
When I add ace-builds as a npm dependency to my project and import it with `import ace from "ace-builds";`, browserify failes with the following message:
` Error: Can't walk dependency graph: Cannot find module '../../token_iterator'`

This makes sense insofar as that there is indeed no such module in the ace-builds folder in my node_modules. However, I can see it in the main ace repository ([here](https://github.com/ajaxorg/ace/tree/master/lib/ace). Is it possible that this file is simply missing from the npm package?

**Comment by andrewnester** [comment]
Hi @Adrian-Bielefeldt ! I tried to reproduce the issue on latest ace-builds but couldn't. Could you please provide reproduction steps?
