### ISSUE TITLE
EventEmitter typescript type is missing removeAllListeners method

### ISSUE THREAD

**Issue by niairobi** [ajaxorg/ace#4737]
https://github.com/ajaxorg/ace-builds/blob/master/src/ace.js#L3555-L3559 Method declaration
https://github.com/ajaxorg/ace-builds/blob/master/ace.d.ts#L239-L248 Typescript type

Is this intended that `removeAllListeners` method is not present in the public typings?

**Comment by andrewnester** [comment]
Thanks for reporting, no, this is not intended and seems to be a miss on our side

**Comment by andrewnester** [comment]
Released in 1.9 version
