### ISSUE TITLE
Can we integrate this software into our own products and sell it?

### ISSUE THREAD

**Issue by Yuutakasan** [ajaxorg/ace#4746]
I read the license, and I understood that the product is uncompensated, that there is no warranty for damages, and that the license is displayed, but I didn't understand if it is available for commercial use.

**Comment by hyandell** [comment]
https://github.com/ajaxorg/ace/blob/master/LICENSE

This is the BSD-3-Clause license. We can't speak to your specific situation, but this license is commonly used in commercial products. 

Here are some popular websites regarding the BSD-3-Clause:

* [tldrlegal.com:BSD](https://tldrlegal.com/license/bsd-3-clause-license-(revised))
* [wikipedia.org:BSD](https://en.wikipedia.org/wiki/BSD_licenses#3-clause_license_(%22BSD_License_2.0%22,_%22Revised_BSD_License%22,_%22New_BSD_License%22,_or_%22Modified_BSD_License%22))
