### ISSUE TITLE
Textarea doesnt contain whole code which is shown

### ISSUE THREAD

**Issue by adaamz** [ajaxorg/ace#4747]
Hi,
I found out that Ace doesnt store whole code into internal textarea. This causes my main problem - only few lines are retrieved by `window.getSelection().toString()`.
Easy test case for this:
1) go to some page with ace editor (i used https://ace.c9.io/)
2) execute this script:
```js
$("textarea")[0].setSelectionRange(0, 99999);
window.getSelection().toString();
```
3) (fail) this should print the whole content of editor (but prints only last line)

**Comment by andrewnester** [comment]
Editor API is not a hack but the right way to interact with editor content. Relying on internal details of editor such as textarea is not reliable and as you can see does not produce expected results

**Comment by adaamz** [comment]
@andrewnester and what is proper way to get contents of editor?
