### ISSUE TITLE
Gherkin worker

### ISSUE THREAD

**Issue by mahdi943** [ajaxorg/ace#4751]
Hi,
I am using src-noconflict folder in my project. 
Everything works fine but the Gherkin syntax checker doesn't work (I mean the popup window that appears when there is a syntax error). 
How can I enable or fix it?

Mahdi.

**Comment by andrewnester** [comment]
We do not provide a syntax checker for Gherkin syntax, only syntax highlighting. We don't have plans to add specific workers but rather plan on general LSP support https://github.com/ajaxorg/ace/issues/3124
