### ISSUE TITLE
Shows warning for text-decoration-color property as unknown property.

### ISSUE THREAD

**Issue by bhargavavarma** [ajaxorg/ace#4754]
# Problem

It was showing warning when using text-decoration-color property.

![image](https://user-images.githubusercontent.com/54624935/107735471-c5855800-6d25-11eb-85d3-e9c95d91ddd2.png)

## Sample code to reproduce your issue

After looking into your Repo, i found out that in worker-css.js file you can add text-decoration-color property same as import below image.
![image](https://user-images.githubusercontent.com/54624935/107735653-3a589200-6d26-11eb-83c8-92ad158bb65c.png)

I guess this will solve my issue if you add text-decoration-color property same as import in above image or you can add it to setDisabledRules.

### Expected

Need to show error or warning message when using this property.

### versions
- v1.4.12(Latest)

**Comment by andrewnester** [comment]
This has been fixed in 1.15+ version
