### ISSUE TITLE
When using object spread property in Javascript mode, getting unexpected warning.

### ISSUE THREAD

**Issue by bhargavavarma** [ajaxorg/ace#4756]
![image](https://user-images.githubusercontent.com/54624935/107611088-34e94200-6c69-11eb-9218-5741f2d0afe8.png)
![image](https://user-images.githubusercontent.com/54624935/107611166-63671d00-6c69-11eb-9e75-92618d63fb78.png)

### Expected

No need of showing any warning here, spread operator is a valid syntax in javascript.

**Comment by InspiredGuy** [comment]
Now in [kitchen sink](https://ace.c9.io/build/kitchen-sink.html) it shows a different warning (but still a warning).
<img width="593" alt="image" src="https://user-images.githubusercontent.com/1381598/219723791-949bfe62-019c-4d7a-b020-ec18e33c7f02.png">

Possible fix would be to modify jshint config to use newer ECMAScript version, or maybe updating jshint version would help (last update happened in august 2022 according to [changelog](https://github.com/ajaxorg/ace/blob/master/CHANGELOG.md)).
