### ISSUE TITLE
Need to show error if body/html end tags are missing similar to other tags like div, h1.

### ISSUE THREAD

**Issue by bhargavavarma** [ajaxorg/ace#4757]
# Problem

Need to show error if body/html end tags are missing similar to other tags like div, h1.

![image](https://user-images.githubusercontent.com/54624935/107601545-0f4e3f80-6c4d-11eb-8bac-af8274ca4add.png)
Note: In this image i have removed end tag for div, it was showing an error. But if i remove head or body tag it was not showing any warning or error.

## Sample code to reproduce your issue

After looking into your Repo, i found out that in worker-html.js file for both html and body your stopping the error to display in gutter.
![image](https://user-images.githubusercontent.com/54624935/107602153-a7005d80-6c4e-11eb-82a0-4072d5476925.png)

### Expected

Need to show error or warning message when body or html end tag is missing.

### versions
- v1.4.12(Latest)

**Comment by akoreman** [comment]
Thanks for creating the issue. There is a to do comment in the [code you referenced](https://github.com/ajaxorg/ace/blob/master/lib/ace/mode/html/saxparser.js#L3658) for a similar issue. The code is this file originates from [another repository](https://github.com/aredridel/html5/). Looking at the main branch of that repository we see the [same to do comment](https://github.com/aredridel/html5/blob/master/lib/TreeBuilder.js#L1305). To resolve this we would have to implement this to do which would probably require significant effort.

**Comment by nightwing** [comment]
Now it is possible to use ace with https://github.com/mkslanc/ace-linters which greatly improves language services, and fixes this bug too.
