### ISSUE TITLE
2 empty lines are added after typing in a new line in IE11

### ISSUE THREAD

**Issue by velemas** [ajaxorg/ace#4762]
When I make a new line by pressing enter and start typing, 2 new additional lines are added in IE11.
I reproduced this with v1.4.3 and 1.4.12. Chrome/Firefox work fine.

![выява](https://user-images.githubusercontent.com/10437413/95750983-9b078d80-0ca6-11eb-8900-1a2504cd2d97.png)

**Comment by andrewnester** [comment]
We don't plan to make fixes for IE11
