### ISSUE TITLE
When Chrome devtools is open and Play button is Clicked the IDE hits a breakpoint

### ISSUE THREAD

**Issue by ghost** [ajaxorg/ace#4764]
https://github.com/ajaxorg/ace-builds/blob/53be42342df216d2d25dc60a12dfcb263c6f0592/demo/kitchen-sink/demo.js#L1258

When inspecting the Kitchen-Sink IDE and the play button is clicked there is a breakpoint that gets hit and stops the application as if it is being debugged. I'm not sure if that is intentional.

![image](https://user-images.githubusercontent.com/50460332/91229653-35604180-e6f8-11ea-9668-fa12913cd2a4.png)
![image](https://user-images.githubusercontent.com/50460332/91229706-4d37c580-e6f8-11ea-8498-5dfcb1451a64.png)

**Comment by NylePudding** [comment]
This still exists in _demo/kitchen-sink/dev/dev_util.js_ and it's for debugging the last test case I believe? Perhaps this issue can be closed? :)

**Comment by nightwing** [comment]
Yes, this is intentional to make debugging of generated script simpler.
