### ISSUE TITLE
Discrepancy between keywords used by mode-aql.js in the current version and the version used by arangodb.

### ISSUE THREAD

**Issue by rachitpsolanki** [ajaxorg/ace#4767]
Arango : keywords
[List of keywords used by arango](https://github.com/arangodb/arangodb/blob/devel/js/apps/system/_admin/aardvark/APP/react/public/assets/src/mode-aql.js#L91)
```
...
 var keywords = (
    "for|return|filter|search|sort|limit|let|collect|asc|desc|in|into|insert|update|remove|replace|upsert|options|with|and|or|not|distinct|graph|shortest_path|outbound|inbound|any|all|none|aggregate|like|k_shortest_paths|prune"
    );
...
```

Ace : mode-aql.js 
[List of keywords listed in ace-builds](https://github.com/ajaxorg/ace-builds/blob/master/src/mode-aql.js#L10)

```
...

var keywords = (         
"for|search|outbound|inbound|any|graph|prune|options|shortest_path|to|in|return|filter|sort|limit|let|collect|remove|update|replace|insers|upsert|with"
);

...
```
@nightwing  @jywarren @fjakobs @zefhemel

**Comment by andrewnester** [comment]
Fixed and released in version 1.11.1
