### ISSUE TITLE
Add Sublime Text Theme

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [ajaxorg/ace#4768]

**Comment by InspiredGuy** [comment]
Could you please send a link to a desired "Sublime Text" theme (that exact monokai interpretation), like a colour scheme? This would help a lot.

**Comment by Abdur-rahmaanJ** [comment]
@InspiredGuy highlightjs for example has the [monokai-sublime](https://highlightjs.org/static/demo/) theme.

**Comment by whazor** [comment]
That would be this theme: https://github.com/gerardroche/sublime-monokai-free

We have a [tmtheme tool](https://github.com/ajaxorg/ace/blob/master/tool/tmtheme.js) that can convert TextMate themes to an Ace theme, afterwards you can put it in the `src/theme/` folder and create a pull request. You can look at the [monokai.js/css](https://github.com/ajaxorg/ace/blob/master/src/theme/monokai.js) for inspiration.

Be sure to add screenshots to the pull request, for both light and dark, with clear code examples that correctly showcase all the colors.

**Comment by Abdur-rahmaanJ** [comment]
Ok give me a day or two
