### ISSUE TITLE
Firefox console warning with v1.4.x

### ISSUE THREAD

**Issue by leomp12** [ajaxorg/ace#4778]
Hello,
I'm getting the following warning message on Firefox:

>Will-change memory consumption is too high. Budget limit is the document surface area multiplied by 3 (392256 px). Occurrences of will-change over the budget will be ignored.

It happens only with new version (1.4.x), not with 1.3.x, I did not get more errors because I went back to the version 1.3.x.
I'm using Firefox Quantum 62.0 (64-bit) for Arch Linux.

**Comment by nightwing** [comment]
This is fixed in the current version of firefox.
