### ISSUE TITLE
Using ace-builds with webpack

### ISSUE THREAD

**Issue by komali2** [ajaxorg/ace#4782]
We are trying to use ace-builds with webpack. 

We have used the line 

`    var Ace = require('ace-builds/src/ace');`

```
ERROR  Failed to compile with 91 errors                                                                                            12:26:03

These relative modules were not found:

* ../../lib/lang in ./node_modules/ace-builds/src/ace.js
* ../../lib/oop in ./node_modules/ace-builds/src/ace.js
<snip>
```

We have tried many iterations of "using ace editor with webpack," further documented on the [master ace-editor repo. ](https://github.com/ajaxorg/ace/issues/3654)

We worked on this a long time before making an issue in either place, I am doing so now because I have been unable to find a definitive resource on using either ace, ace-builds, or brace with webpack on a repo that uses custom modes. 

What is the proper way to use ace-builds with webpack?

**Comment by SinnerAir** [comment]
I use webpack 5.74.0 with ESM modules. Not worked **ext-language_tools** . Output warnings **enableSnippets** is reported as misspelled option name

This helped me:
```
import ace from 'ace-builds/src-noconflict/ace.js';

import ext from 'ace-builds/src-noconflict/ext-language_tools.js';
import extSearch from 'ace-builds/src-noconflict/ext-searchbox.js';

ace.define('ace/ext/language_tools', null, ext);
ace.define('ace/ext/searchbox', null, extSearch);
```

**Comment by AidanWelch** [comment]
> You can try this:
> 
> ```
> npm i ace-builds
> ```
> 
> ```
> import 'ace-builds';
> import 'ace-builds/webpack-resolver';
> ```
> 
> ```
> ace.edit("editor", {
> 	mode: "ace/mode/html",
> 	theme: "ace/theme/dracula",
> 	maxLines: 50,
> 	minLines: 10,
> 	fontSize: 18
> });
> ```
> 
> ```
> <div id="editor"></div>
> ```

This relies on `file-loader` being installed, which is deprecated.

**Comment by nightwing** [comment]
Please see https://github.com/ajaxorg/ace-samples/tree/master/samples/ace-builds-webpack for a working version of ace-builds with webpack and language-tools

For new versions of webpack use `import 'ace-builds/esm-resolver'` https://github.com/ajaxorg/ace-builds/blob/master/esm-resolver.js which does not use file loader.

**Comment by TimChinye** [comment]
I'm confused, so what are we supposed to do if we loaded Ace in via cdnjs and not webpack or other?

**Comment by jbuddha** [comment]
> Please see https://github.com/ajaxorg/ace-samples/tree/master/samples/ace-builds-webpack for a working version of ace-builds with webpack and language-tools
> 
> For new versions of webpack use `import 'ace-builds/esm-resolver'` https://github.com/ajaxorg/ace-builds/blob/master/esm-resolver.js which does not use file loader.

This worked for me.
