### ISSUE TITLE
OnChange/KeyDown/Up on vim dialog

### ISSUE THREAD

**Issue by sizvix** [ajaxorg/ace#4783]
It could be cool to add an API for OnChange/KeyDown/Up on vim dialog , to implement autocomplete for files for example.

**Comment by whazor** [comment]
Hey, in the [Ace kitchen](https://ace.c9.io/build/kitchen-sink.html) if you enable 'Live Autocompletion' and VIM mode, then autocomplete actually shows up when typing. So it would make most sense for you to build your auto-completion functionality on top of the auto-completion functionality of Ace. [Here](https://plnkr.co/edit/6MVntVmXYUbjR0DI82Cr?p=preview&preview) is an example on how to add your own autocompleter.

For events, I think `onChange` and `changeSelection` should propagate as events. Let me know whether you really need keyboard down and up, as VIM mode is quite complicated and I would like to know why you would want to interfere with keyboard down/up.
