### ISSUE TITLE
The editor can be crashed by passing in `undefined` into the setValue method

### ISSUE THREAD

**Issue by prettydiff** [ajaxorg/ace#4784]
Passing in an undefined value into the setValue method breaks the editor and everything else.

**stack trace from Firefox**

* this.$detectNewLine
file:///c:/users/austincheney/prettydiff3/node_modules/ace-builds/src-min-noconflict/ace.js:1:143354
* this.insert
file:///c:/users/austincheney/prettydiff3/node_modules/ace-builds/src-min-noconflict/ace.js:1:145099
* this.setValue
file:///c:/users/austincheney/prettydiff3/node_modules/ace-builds/src-min-noconflict/ace.js:1:142991
* this.setValue
file:///c:/users/austincheney/prettydiff3/node_modules/ace-builds/src-min-noconflict/ace.js:1:232577
* my personal code that produced the error

This problem is encountered in the scenario:  `myEditor.setValue(undefined)`.  A safe mitigation is that if the argument is undefined simply process an empty string.

Convert
`this.$detectNewLine=function(e){var t=e.match(`

To:
`this.$detectNewLine=function(e){var t=(typeof e!=="string")?null:e.match(`

**Comment by andrewnester** [comment]
Fixed and released in version 1.11.1
