### ISSUE TITLE
Loading cross-origin worker is not allowed in Firefox

### ISSUE THREAD

**Issue by Fixer1008** [ajaxorg/ace#4786]
When I use 'ace' editor with turning on workers, it throws an error on initialization in Firefox:

"Failled to load worker script at ../ace-builds/src-min-noconflict/worker-javascript.js"

After the investigation I found out, that it happends because worker initialization in Firefox does not throw an error, so 'catch' block with blob URL building is missed (ace.js):
```
try
{
   this.$worker = new Worker(workerUrl);      // Chrome and IE throw an error, but Firefox not. So the 'catch' block is missing
} catch(e) {
  if (e instanceof window.DOMException) {
   var blob = this.$workerBlob(workerUrl);
   var URL = window.URL || window.webkitURL;
   var blobURL = URL.createObjectURL(blob);

    this.$worker = new Worker(blobURL);
    URL.revokeObjectURL(blobURL);
 } else {
    throw e;
  }
}
```
I was investigating current issue and found out one interesting thing. On Firefox 45 and later, a generic error event will be asynchronously fired once a new Worker instance is created, according to the latest spec. In order to deal with both cases, we have to use the worker’s onerror handler along with a try-catch statement:
```
try {
  var worker = new Worker(url);
  worker.addEventListener('error', function (event) {
    // Error: Failed to load script (nsresult = 0x805303f4)
    // Prevent the event from bubbling
    event.preventDefault();
    // Handle the cross-origin load error for newer browsers
    ...
  });
} catch (ex) {
  // SecurityError
  // Handle the cross-origin load error for older browsers
  ...
}
```

I think you can use this approach for preventing from other unexpected errors connected with workers. 

What do you think about it?
Thank you!

**Comment by andrewnester** [comment]
New version with the fix was published
