### ISSUE TITLE
postgresql highliter - annonymous code block

### ISSUE THREAD

**Issue by michalk-k** [ajaxorg/ace#4790]
Hello
I found, postgresql highlighter seems to be lost when a source code contains anonymous code block.
Such block can be defined by following constructs

```
DO $$
BEGIN
    -- some code
END
$$ LANGUAGE plpgsql;
```

or 

```
DO LANGUAGE plpgsql $$
BEGIN

END $$;
```

Other languages than plpgsql (like python etc) doen't require BEGIN-END commands.

In current version of highlighter any code existing after anonymous code block is treated as a comment (at least judging by colours). On the other side, SQLServer highlighter behaves properly.

Tested at: https://ace.c9.io/build/kitchen-sink.html

With regards

**Comment by andrewnester** [comment]
Released in 1.9 version
