### ISSUE TITLE
How it works? ext-linking.js 

### ISSUE THREAD

**Issue by balabesimple** [ajaxorg/ace#4796]
How it works? Even though I Included  ext-linking.js  and added below.
var editor = window.ace.edit(editorid);
        getAppController.setcurrentEditorObj(editorid, editor);

```
    /*set ace editor settings*/
    editor.setShowPrintMargin(false);
    editor.setTheme("ace/theme/eclipse");
    editor.setFontSize("14px");
    editor.setOptions({
        enableBasicAutocompletion: true,
        enableSnippets: true,
        enableLinking: true
    });
```

I used Ctrl+Click? - but no response.

**Comment by andrewnester** [comment]
> Is enableLinking:true the way I should use?
yes
