### ISSUE TITLE
(ace-builds): (TS error in VirtualRenderer interface)

### ISSUE THREAD

**Issue by artsiadi** [ajaxorg/ace#4808]
### Describe the bug

Getting the following error in version 1.5.3.

node_modules/react-ace/lib/types.d.ts:124:11 - error TS2430: Interface 'IRenderer' incorrectly extends interface 'VirtualRenderer'.
  Types of property 'scroller' are incompatible.
    Type 'HTMLDivElement | undefined' is not assignable to type 'HTMLElement'.
      Type 'undefined' is not assignable to type 'HTMLElement'.

124 interface IRenderer extends Ace.VirtualRenderer {
              ~~~~~~~~~

Found 1 error in node_modules/react-ace/lib/types.d.ts:124



### Expected Behavior

No TS errors.

### Current Behavior

Build fails.

### Reproduction Steps

Run build.

### Possible Solution

Downgrade to version 1.5.0.

### Additional Information/Context

_No response_

### Ace Version

10.1.0

**Comment by andrewnester** [comment]
It seems like types provided by react-ace are not correct comparing to types in ace.d.ts which were recently updated.

Please reach out to react-ace team so they update types accordingly

**Comment by andrewnester** [comment]
In particular this line should be removed
https://github.com/securingsincity/react-ace/blob/main/src/types.ts#L133

**Comment by jmc420** [comment]
It's not possible to 

> In particular this line should be removed https://github.com/securingsincity/react-ace/blob/main/src/types.ts#L133

this does not work but it can be fixed by changing line 677 of ace.d.ts in ace to

readonly scroller?: HTMLElement;

Can the change be made in ace rather than React Ace?
