### ISSUE TITLE
HTML Mode: Ability to set default InsertionMode to `body` or `head`

### ISSUE THREAD

**Issue by BenSouchet** [ajaxorg/ace#4811]
### Describe the feature

I would love getting the ability of specify the "parent" / "start" InsertionMode of the HTML tokenizer, So I can give it one of the currently available values like "body" or "head".

With that I could properly get an Ace editor parse and highlight the content of a `<body>` DOM element or a `<head>` DOM element.

### Use Case

I'm currently building a website where you can edit / manage the content of an iframe `<body>` with an Ace editor, but if I use the HTML mode I get an info annotation since the first line isn't a doctype.

After looking in the `worker-html.js` file I understood that at start the `startTokenization` process is set to `initial` (`this.setInsertionMode('initial');`)

Since my editor block reflect the content of a `<body>` DOM element not a full HTML document, the tokenization won't be accurate.

Currently as I "workaround" I use the xml mode but I don't get all the features and highlighting of the html mode.

### Proposed Solution

It's seems there is something called Fragment for the HTML mode and worker, but there isn't much info in the whole repo or/and in the whole Github.

I think I understand that I need to pass option to the HTML mode, according to this line in `mode-html.js`:
```javascript
this.fragmentContext = options && options.fragmentContext;
```
This is passed to the worker and then in `startTokenization` this fragment context will be use to create an HTML doctype and tag (`insertHtmlElement`), **BUT** after that we will be set in insertion mode `beforeHead`, not in `body` or `head`.

There is also element like `startTagOther` that seems a good direction to investigate.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### ACE version used

1.5.0

**Comment by BenSouchet** [comment]
I'm sure I'm not the first one to encounter this specific need but I didn't find anything to achieve the desired goal, I have looked at the Issues, and the implementations of people on Github without success.

**Comment by andrewnester** [comment]
Thanks for the feature request! Just to set realistic expectation, I don't think we as a team have a capacity to work on such feature requests at the moment. Our main focus is on addressing existing bugs and working on larger features such as LSP support or Wide character support.

But we always welcome contribution and would be happy to help with it :)

**Comment by BenSouchet** [comment]
@andrewnester Thanks for the precision it's perfectly understandable.

After more investigations, I think It's already possible to do what I want with few or no modifications to the existing code, I currently only have one question:

In the file `lib/ace/mode/html.js` line `49` : `var Mode = function(options) {`

**Do you know how can I pass `options`?**

Because If I successfully pass `{fragmentContext: 'body'}` or `{fragmentContext: 'head'}` this will produce exactly what I want, an HTML fragment editor in the scope of the context I passed (e.g. `body` or `head`).

**Comment by andrewnester** [comment]
Thanks, the PR was merged

**Comment by andrewnester** [comment]
Released in 1.6.0
