### ISSUE TITLE
Ace highlighting mode for Julia needs to be improved

### ISSUE THREAD

**Issue by Gabrielforest** [ajaxorg/ace#4813]
### Describe the bug

The syntax highlighting for Julia is wrong in Rstudio IDE 

### Expected Behavior

The syntax highlighting in Visual Studio Code works properly:
![image](https://user-images.githubusercontent.com/63704591/171488639-a3e97b37-a896-422a-a23c-cee3e849e571.png)

### Current Behavior

as you can see below:
![image](https://user-images.githubusercontent.com/63704591/171488127-32c6dcaa-2804-48a1-8228-fd22c9b56033.png)

This code shouldn't be green. 

### Reproduction Steps

The code provided is totally reproducible.

### Ace Version

Latest version of IDEs

**Comment by andrewnester** [comment]
![Screen Shot 2022-06-21 at 15 45 58](https://user-images.githubusercontent.com/2969996/174815089-d164d7b3-5b6b-4cdc-b8d3-71a1c4c2799d.png)

Julia code seems to be rendered correctly in Ace kitchen sink. Also it seems that in your example you have the code wrapped in "```" quotes, why is that? Can the issue be specific to RStudio IDE?

**Comment by Gabrielforest** [comment]
It is a chunk code format from the Quarto package, see at https://github.com/quarto-dev/quarto-cli/issues/991 
Indeed it is specific to Rstudio IDE.

**Comment by andrewnester** [comment]
Yes, please, I guess RStudio GitHub repo would be more appropriate for this issue
https://github.com/rstudio/rstudio
