### ISSUE TITLE
Overflow button does not show for long lines without spaces

### ISSUE THREAD

**Issue by Exaphis** [ajaxorg/ace#4817]
### Describe the bug

When a line has over 10000 characters and has no spaces, the click to see more button does not appear. Users cannot scroll to the end of the line.

### Expected Behavior

The click to see more button should appear.

### Current Behavior

The click to see more button does not appear.

### Reproduction Steps

Enter a line with 10050 consecutive a's. The end of the line is cut off.
Add a space into the line. The click to see more button appears.

### Possible Solution

In `lib/ace/layer/text.js`, the `screenColumn + value.length > this.MAX_LINE_LENGTH` check should occur for every token, not just the first. I will submit a PR for this.

### Ace Version

1.5.3

**Comment by andrewnester** [comment]
Released in 1.6.0
