### ISSUE TITLE
github clone: error message

### ISSUE THREAD

**Issue by David263** [ajaxorg/ace#4819]
### Describe the bug

This might just be due to a misconfiguration on my Windows computer, but an attempt to clone the Ace repo by using the instruction on page https://ace.c9.io/ resulted in the following error message:

C:\WINDOWS\system32>git clone git://github.com/ajaxorg/ace.git
Cloning into 'ace'...
fatal: unable to connect to github.com:
github.com[0: 140.82.113.4]: errno=Invalid argument

### Expected Behavior

I expected it to clone. I will solve this by cloning using the GitHub website.

### Current Behavior

See error message above.

### Reproduction Steps

See command above.

### Possible Solution

Not sure why git is failing; could be a misconfiguration on my computer.

### Ace Version

N/A

**Comment by andrewnester** [comment]
This is not an issue on Ace side, but something with either your local Git or Github setup
