### ISSUE TITLE
Wrong cursor pos on Android

### ISSUE THREAD

**Issue by danicaStarR** [ajaxorg/ace#4825]
### Describe the bug

https://user-images.githubusercontent.com/103302052/174423565-ed7ae676-f61e-41f3-8e4a-97f7b260a046.mp4

OS: Android 6.0.1
WebView Version: chromium 98.0.4758.101
Only displays in the correct location in older browsers(exp: chrome 54), not in newer browsers

### Expected Behavior

true pos

### Current Behavior

idk

### Reproduction Steps

1. open editor
2. edit

### Ace Version

1.6.0

**Comment by nightwing** [comment]
The issue happens because the font used in the editor is not monospaced.
