### ISSUE TITLE
[bug] Highlighter should support accents

### ISSUE THREAD

**Issue by fcrozatier** [ajaxorg/ace#4828]
### Describe the bug

In Python we can use accented variable names. The highlighter should correctly highlight these.

Here is a caption in Python mode with theme cobalt: 

<img width="389" alt="image" src="https://user-images.githubusercontent.com/48696601/175271178-5bae97da-d2c3-49f5-be16-d11f0fdbfcaf.png">

I haven't tried in other modes

### Expected Behavior

Accented variable names should be correctly highlighted

### Current Behavior

An accented variable name is only partially highlighted up to the accent

### Reproduction Steps

Just use Python mode for example

### Ace Version

1.6.0

**Comment by andrewnester** [comment]
Fixed and release in Ace 1.6.1
