### ISSUE TITLE
Add syntax highlighting for the BibTeX language

### ISSUE THREAD

**Issue by dbitouze** [ajaxorg/ace#4837]
### Describe the feature

It would be nice if Ace would support syntax highlighting for the BibTeX language, [a feature provided by Pygments](https://pygments.org/demo/?lexer=bibtex&style=default&formatter=html&code=%40book%7Btexbook%2C%0A++author+%3D+%7BDonald+E.+Knuth%7D%2C%0A++year+%3D+%7B1986%7D%2C%0A++title+%3D+%7BThe+%7B%5CTeX%7D+Book%7D%2C%0A++publisher+%3D+%7BAddison-Wesley+Professional%7D%0A%7D).

### Use Case

It would be useful for (La)TeX [tutorials](https://www.learnlatex.org/en/lesson-12) or FAQs.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### ACE version used

1.4.12 and 1.7.1

**Comment by andrewnester** [comment]
Fixed and released in 1.12.0
