### ISSUE TITLE
ace-builds: 1.8.0 contains broken CSS in theme cloud9_day

### ISSUE THREAD

**Issue by FredrikSeidl** [ajaxorg/ace#4850]
### Describe the bug

The output in the ace-builds repo contains a theme.css with broken CSS. The first line of cloud9_day.css ends with
```
}lid rgb(200, 200, 250);
```
Causing minifiers and postcss to break since the CSS is invalid. Could possibly create issues in browsers as well since the CSS is indeed broken

### Expected Behavior

The line should not have `lid rgb(200, 200, 250);` at the end

### Current Behavior

PostCSS complains about the broken CSS

### Reproduction Steps

Look at the build output in https://github.com/ajaxorg/ace-builds/blob/v1.8.0/css/theme/cloud9_day.css to see the issue

### Ace Version

1.8.0

**Comment by andrewnester** [comment]
Thanks for reporting, fixed in 1.8.1
