### ISSUE TITLE
[Feature request] disable warning (and/or error) icons on JS code

### ISSUE THREAD

**Issue by jonathaningram** [ajaxorg/ace#486]
I would like the ability to disable warning icons. Especially when in read-only mode, this most likely means that the JS code has been written and the warnings are acceptable.
@gissues:{"order":36.64596273291954,"status":"backlog"}

**Comment by iamgoodbytes** [comment]
Same here. I'm letting users enter HTML and JS snippets instead of full documents.

**Comment by voronianski** [comment]
wow, very old thread and still actual, @fjakobs PRs are welcome?

**Comment by nightwing** [comment]
Now it is possible to use `editor.session.$worker.call("setOptions", [{}])` to configure workers that [support](https://github.com/ajaxorg/ace/blob/master/lib/ace/mode/javascript_worker.js#L78) it. But it doesn't work well and for all modes.
@voronianski PRs are always welcome:)

**Comment by Guihgo** [comment]
> Now it is possible to use `editor.session.$worker.call("setOptions", [{}])` to configure workers that [support](https://github.com/ajaxorg/ace/blob/master/lib/ace/mode/javascript_worker.js#L78) it. But it doesn't work well and for all modes.
> @voronianski PRs are always welcome:)

thanks ! 

To sum with this issue:
i'm trying disable a rule ("unqualified-attributes") from CSSLint on [CSS Worker](https://github.com/ajaxorg/ace-builds/blob/0d62c26de7b2e1922d8dd95ba587c9845c018c51/src/worker-css.js#L8030)
so i use:
```js
editor.session.$worker.call('setDisabledRules', ["unqualified-attributes"]);
```
