### ISSUE TITLE
Style issue

### ISSUE THREAD

**Issue by mattymatty76** [ajaxorg/ace#4860]
### Describe the bug

In editor code, style changes when move/click on different item
For example: if I have a structure like this

```html
<style>
...
</style>

<div>
...
</div>
```
when I click on style tag, change all tags color: in a sort of faded mode
The theme that I use is theme-vibrant_ink and I have tested ace 1.7.1 and 1.8.1 with the same result.

### Expected Behavior

The color should remain the same independently what type of tag I click

### Current Behavior

When click on style tag, change color in style tag and others tag

### Reproduction Steps
```html
<style>
    /*form[data-id='1438'] input, textarea, select{ background-color: #fafafa!important; }*/
    .uppercase input{ text-transform: uppercase; }
</style>

<table id="sample-table" class="basic-table" border="1" data-resizable="true">
   <thead>
     <tr>
       <th>Id</th>
       <th>String MaxLength(10)</th>
       <th>Color Example</th>
       <th>Secret Value</th>
       <th>Data</th>
       <th>Number</th>
     </tr>
   </thead>
   <tbody>
       <tr><td>1</td><td>aaa</td><td>#05a</td><td>12345</td><td></td><td>1111</td></tr>
       <tr><td>2</td><td>bbb</td><td>#0cb</td><td>67891</td><td></td><td>2222</td></tr>
       <tr><td>3</td><td>ccc</td><td>#0fa</td><td>11121</td><td></td><td>3333</td></tr>
   </tbody>
</table>
```

### Additional Information/Context

![Screenshot_1](https://user-images.githubusercontent.com/56148940/180767406-a931924f-8c1b-42d8-a51d-6eb031dde298.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/56148940/180767409-f074ba7e-627a-4897-a50c-79566758c144.jpg)

### Ace Version

1.7.1 - 1.8.1

**Comment by nightwing** [comment]
Which browser are you using? Looks like it changes subpixel antialiasing mode when markers are rendered.

Does the same happen when selecting text, or when there are multiple instances of the same word and you select one of them?

**Comment by mattymatty76** [comment]
Hi Harutyun and thank you for your answer,
I'm using chrome and edge the latest version.
Looks like it changes subpixel antialiasing mode when markers are rendered.
Yes exactly, moreover it is as if the font come thinned
Does the same happen when selecting text, or when there are multiple
instances of the same word and you select one of them?
Yes, the first, when you select (more exactly when click) for example a
comment (in a different line //comment... ) or a style tag <style>, so it
happens and changes the other tags (not only the same tag)
I attached a video that it's more realistic than thousand of words...
Thank you very much anyway

Il giorno lun 25 lug 2022 alle ore 14:25 Harutyun Amirjanyan <
***@***.***> ha scritto:

**Comment by mattymatty76** [comment]
This shows the problem with the click on style tag and click on a comment:
for avoid (to exclude) problem about css included, I have removed the
resources previously imported like


<script src="js/jquery.tabledit.js"></script>
<link rel="stylesheet" href="css/jquery.resizableColumns.min.css">
<script src="js/jquery.resizableColumns.min.js"></script>
<script src="js/bootstrap-table-resizable.min.js"></script>

so now the video shows the issue just with html/css code without
interferences with other css file...

Thank you

Il giorno lun 25 lug 2022 alle ore 14:25 Harutyun Amirjanyan <
***@***.***> ha scritto:

**Comment by mattymatty76** [comment]
ok I will try in this manner...

https://www.veed.io/view/b46de5ab-c139-461e-82e9-e640aa1f6968

maybe now it's work, I hope...

**Comment by nightwing** [comment]
Could you please check if the same happens for you on https://ace.c9.io/build/kitchen-sink.html?theme=vibrant_ink, that will help to figure out if this is caused by something in the page you are creating (e.g. css transform or contain), or if this always happens.

**Comment by nightwing** [comment]
Could you show me the page where this happens, most likely explanation is that the modal window uses some css style that breaks antialiasing.

**Comment by mattymatty76** [comment]
It's a problem because the code being generated dynamically and it's a lot of code, but I will try to find a solution (just to understand what is it), the strange thing is that if I remove overflow:hidden from .ace_scroller{ ... }
in ace.js file, the issue disappears but in a modal is very terrible because now I have two vertical scrollbar...
But now it works :D
![Screenshot_1](https://user-images.githubusercontent.com/56148940/181802267-c72532c1-998f-4ac0-8827-ab59ea790a8f.jpg)

**Comment by mattymatty76** [comment]
Hi Harutyun, 
I have understood where is the problem: it's not a problem related to ace editor, but to summernote and exactly in summernote-bs4.css at the end of the file where is the following piece of code / rule
```
.note-btn-group .note-btn {
    border-color: #00000032;
    padding: 0.28rem 0.65rem;
    font-size: 13px;
}
```
I have removed `border-color: #00000032; ` and now it works very well
Thank you very much for your support my friend! :D

**Comment by mattymatty76** [comment]
ok I will try in this manner...

https://www.veed.io/view/b46de5ab-c139-461e-82e9-e640aa1f6968

maybe now it's work, I hope...

Il giorno lun 25 lug 2022 alle ore 17:16 Harutyun Amirjanyan <
***@***.***> ha scritto:
