### ISSUE TITLE
2 newline characters inserted before text in blank editor

### ISSUE THREAD

**Issue by ZeroVector518** [ajaxorg/ace#4878]
### Describe the bug

In Firefox only, embed an ACE editor and make sure that it has no text in it.  After the script to embed it, use the editor's focus API method.  After loading the page, the ace editor will be focused as expected but when typing a character, notice that 2 newline characters are placed before the text typed.  Firefox version is 103.0.1

### Expected Behavior

No newline characters are inserted before the text typed.

### Current Behavior

In Firefox only, 2 newline characters are inserted before the text typed.

### Reproduction Steps

Use the following HTML to reproduce the issue in Firefox.  This is the sample HTML file provided on the ACE homepage under the "Embedding Guide" section.  Remove the code in the editor div and call the focus method on the editor object in the embedded javascript.

![image](https://user-images.githubusercontent.com/82974188/182304928-93307163-a673-4234-9fe1-8918ac9c88e5.png)

### Ace Version

1.5.0

**Comment by NylePudding** [comment]
I've having trouble reproducing this, I'm not getting any new line characters for Firefox 103.0.1. 

Perhaps someone else can give this a try?

Here's a download to Firefox 103.0.1 (the latest version is 103.0.2).

https://ftp.mozilla.org/pub/firefox/releases/103.0.1/win64/en-GB/

**Comment by NylePudding** [comment]
To clarify, I can't reproduce this in version 1.5.0 or 1.5.3 of ACE in Firefox 103.0.1.
