### ISSUE TITLE
ACE is missing on pagecnd.

### ISSUE THREAD

**Issue by vrayv** [ajaxorg/ace#4882]
### Describe the bug

It seems pagecnd is missing the ace javascript files.

### Expected Behavior

...

### Current Behavior

...

### Reproduction Steps

...

### Ace Version

1.12

**Comment by nightwing** [comment]
Try reporting this to pageCDN, the listing on pageCDN was not created by us.

**Comment by praisedpk** [comment]
Issue resolved. See: 

https://github.com/ajaxorg/ace/issues/4903 
https://pagecdn.com/lib/ace
