### ISSUE TITLE
Improve accessibility of the editor by making the ID of the textarea configurable

### ISSUE THREAD

**Issue by dimovpetar** [ajaxorg/ace#4886]
### Describe the feature

Let me set the ID of the rendered `textarea` element, so that I can set it as the `for` attribute of a `<label>` element, so that I can fulfill accessibility requirements.
```html
<label id="editorLabel" for="???">Label for this editor:</label>
<div id="editor"></div>
<script>
    var editor = ace.edit("editor", {
        ...
    });
</script>
```

### Use Case

This feature is needed to comply with [accessibility standards](https://www.w3.org/WAI/standards-guidelines/aria/). A short sentence is also included in the documentation of the `textarea` element - https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea - "An id attribute to allow the <textarea> to be associated with a <label>(https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label) element for accessibility purposes"

### Proposed Solution

For example, provide a setting such as `textareaId` or `inputId`:
https://jsbin.com/qesekukuvi/5/edit?html

### Other Information

When you focus the `textarea`, the label should successfully be read out by assistive technologies, such as[ NVDA](https://www.nvaccess.org/) or [JAWS](https://www.freedomscientific.com/).

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### ACE version used

1.8.1

**Comment by nightwing** [comment]
Currently it is already possible to use
```js
editor.textInput.getElement().id = "editorTextarea"
```

**Comment by dimovpetar** [comment]
Nice :) than we can consider this as completed
