### ISSUE TITLE
Problems with ace v1.9.2

### ISSUE THREAD

**Issue by AgentSmith0** [ajaxorg/ace#4890]
### Describe the bug

There seem to be some problems with the latest version of the ace editor. Have a look at the kitchen sink: https://ace.c9.io/build/kitchen-sink.html

### Expected Behavior

Ace editor works.

### Current Behavior

Ace editor doesn't work.

### Reproduction Steps

See the examples

### Ace Version

1.9.2

**Comment by andrewnester** [comment]
@nightwing could you please take a look?

**Comment by nightwing** [comment]
Thank you for the report, 1.9.3 fixes this (may require clearing browser cache to load the new version).
