### ISSUE TITLE
Restrict built-in functions

### ISSUE THREAD

**Issue by web-veera** [ajaxorg/ace#4892]
### Describe the feature

Hi,
I'm veera . Now i'm working in online examination test conducting project. I need to restrict some built-in fucntions on code editor . I have searched about this in documentation and many blogs . But there is no feature to restrict some built-in functions in ace editor.

### Use Case

In my case i need to restrict some sorting and searching built-in functions in python. example : sorted, reversed. we are conducting a programe test. user can soleve in any programming language like c, c++, Java, python and etc. In c language user need to create own sorting algorithm to solve problem. this way we are testing user's efficiency. but when user using python's built-in function there is no efficiency and equality to participants. python known participant will solve easily when compared to c programmer. To preventing this just now i'm using regular expressions in javascript. but to many expressions may reduce my application performance.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### ACE version used

v1.9.3

**Comment by andrewnester** [comment]
Ace editor is just a code editor and we don't plan to support out of the box restriction for certain language features, this needs to be don on the application level which integrates Ace
