### ISSUE TITLE
ACE isn't loading in a Firefox content-script

### ISSUE THREAD

**Issue by royalmo** [ajaxorg/ace#4898]
### Describe the bug

I am using ACE in a browser extension. In a particular page, an embedded ace editor should show up to the user, so the contents of a file can be modified, ...

I am including ACE in a content-script (see reproduction steps). It works perfect when I try the extension on Google Chrome (and chromium-based browsers), but fails when I try it in a Firefox browser.

### Expected Behavior

Ace should load normally and `ace.edit('editor')` shouldn't throw any error.

### Current Behavior

Only `ace.require` and `ace.define` are loaded. So, it isn't possible to run ACE in a Firefox content-script.

### Reproduction Steps

Segment of the `manifest.json` (Manifest Version 2) that is including `ace.js`:

```json
"content_scripts" : 
    [
        {
            "matches": ["*://somewebsite.com/*"],
            "all_frames": true,
            "js": [
                "ace/ace.js",
                "myscript.js"
                ],
            "run_at": "document_end"
        }
    ]
```

In `ace/` you will find the entire build (I have tried both standard and no-conflict builds).

`myscript.js` contains a sample code:
```js
// checking if ace has been included correctly
console.log(ace);

// supose here we create and append a <div id="editor">hello world!</div> to the document

// this line breaks in Firefox but not in Chrome
ace.edit('editor');
```

### Additional Information/Context

I have included, as a test, `ace.js` as a page script (through `<srcipt>` tags) and it loaded correctly.
So it only fails when it's added in the content-script isolated world, and only in Firefox.

### Ace Version

1.9.5 (latest)

**Comment by royalmo** [comment]
After testing on older builds (with src-noconflict), I found out that the 9 Jun 2014 version ( https://github.com/ajaxorg/ace-builds/blob/966bcd1f02295f2b88d1528681976473f6209631/src-min-noconflict/ace.js ) is the latest in which ace.edit does not fail on Firefox content-script.

The next version after these one ( https://github.com/ajaxorg/ace-builds/blob/4b279a378e2d9eca9c9d715e814b0dba0426e7df/src-min-noconflict/ace.js ) fails.

I hope that this will help a little.

**Comment by nightwing** [comment]
Having the extension to debug would greatly help to save time on testing setup. Is https://github.com/royalmo/itic-copilot the extension for which you see this issue?

**Comment by royalmo** [comment]
Yes, partially. It's a feature I'm currently adding, but in that extension ACE is involved in a 'private' server (university credentials are needed).

I prefer giving you a simpler browser extension where ACE is placed at the bottom of https://example.com/ . It looks very ugly (in fact, nothing is displayed), but you will see in the console that in the FireFox browser the script stops (yes, the error isn't displayed due to https://bugzilla.mozilla.org/show_bug.cgi?id=1410932 , which doesn't help neither).

I made it the simpler I could. I hope it helps ;)
[ace-context-script-debug.zip](https://github.com/ajaxorg/ace/files/9354795/ace-context-script-debug.zip)

**Comment by nightwing** [comment]
the issue happens because in firefox globalThis and window are different. If you replace `ace.require(["ace/ace"], function(a) {...` in ace.js with a version that doesn't use window it seems to work

```js
                ace.require(["ace/ace"], function(a) {
                    if (a) {
                        a.config.init(true);
                        a.define = ace.define;
                    }
                    for (var key in a) if (a.hasOwnProperty(key))
                        ace[key] = a[key];
                    ace["default"] = ace;
                    if (typeof module == "object" && typeof exports == "object" && module) {
                        module.exports = ace;
                    }
                });
```

I'll make a pull request to change this in he next version.

**Comment by royalmo** [comment]
Worked first try! Thanks for the help, that was fast!
