### ISSUE TITLE
Three finger gestures don't work

### ISSUE THREAD

**Issue by Gozala** [ajaxorg/ace#49]
On FF on OSX three finger gesture up / down are shortcut for Home / End. Unfortunately gestures are ignored by ace, would've be nice if it was behaving as expected.
@gissues:{"order":93.78881987577643,"status":"backlog"}

**Comment by nightwing** [comment]
Seems like this didn't work because three finger gestures were sending home/end keyboard events which are bound to gotolinestart/end in Ace.
Closing the issue since these gestures are disabled by default on new versions of mac. 
If someone knows how to enable them, please comment.
