### ISSUE TITLE
Ace getCompletions return list have a lot of useless snippet

### ISSUE THREAD

**Issue by huashaoxu** [ajaxorg/ace#4901]
### Describe the bug

Ace getCompletions return list have a lot of useless snippet。input “create” return
![image](https://user-images.githubusercontent.com/35364039/185280235-eb9e391f-4a3f-473b-a453-fec122fd54e5.png)

### Expected Behavior

how to set whole word match otpions, 

### Current Behavior

over-participle

### Reproduction Steps

null

### Ace Version

9

**Comment by andrewnester** [comment]
@huashaoxu which language mode you used?

**Comment by huashaoxu** [comment]
language mode is sql.

**Comment by andrewnester** [comment]
I'm not able to reproduce it with Ace kitchen sink, could you please provide a repro steps to we can take a look?
https://ace.c9.io/build/kitchen-sink.html
