### ISSUE TITLE
pageCDN no longer working

### ISSUE THREAD

**Issue by bogusred** [ajaxorg/ace#4903]
### Describe the bug

Ace editor was working fine on my site using the pageCDN link
https://pagecdn.io/lib/ace/1.4.12/ace.min.js

### Expected Behavior

Load javascript from pageCDN
Show a list of available versions of ace on the pageCDN page

### Current Behavior

404 on the CDN causing a broken editor

![image](https://user-images.githubusercontent.com/8145300/185456810-c2f54f5f-1ae2-479d-b007-894dba5ae6b6.png)

### Reproduction Steps

1. Visit the ace.c9.io website and go to the embedding guide
2. Under Loading Ace from a CDN click on PageCDN which goes to here: https://pagecdn.com/lib/ace
3. We should see a list of available ace package versions, however the list of files is empty.
![image](https://user-images.githubusercontent.com/8145300/185456339-f3c001b4-c2ae-44f3-a4ab-d0972c35f218.png)

### Possible Solution

Reupload js assets to pageCDN OR remove pageCDN from the list of available CDNS on this documentation page 
https://ace.c9.io/#nav=embedding

### Additional Information/Context

If 1.4.12 is no longer available, I'm happy to upgrade but it looks like no versions are currently present on pageCDN.

### Ace Version

1.4.12

**Comment by praisedpk** [comment]
Please try now. Sorry for inconvenience. We are now using ace-builds. Previously we were loading from different source. This might have changed URLs a little. Please check: https://pagecdn.com/lib/ace

For version 1.4.12, please have a look here: https://pagecdn.com/lib/ace/1.4.12

**Comment by bogusred** [comment]
Thank you so much for the quick response! I went ahead and moved to cdnjs and upgraded to latest version since I wasn't sure how quick this would be addressed. Thank you again and have a lovely day.
