### ISSUE TITLE
ace_gutter and ace_scroller moving out of screen

### ISSUE THREAD

**Issue by lusol** [ajaxorg/ace#4925]
### Describe the bug

When typing out extremely long lines of text in a code editor, the ace_gutter and ace_scroller components move to the left and off screen.

When there is no text:
<img width="527" alt="Screen Shot 2022-09-13 at 1 20 46 PM" src="https://user-images.githubusercontent.com/9649910/189966692-3f0650d7-642c-45ce-9507-05ec38f5aeff.png">

When I type a lot of text on one line and it over flows:
<img width="524" alt="Screen Shot 2022-09-13 at 1 21 03 PM" src="https://user-images.githubusercontent.com/9649910/189966760-54bd47de-de2b-48db-a3ee-c9f299abbde1.png">

### Expected Behavior

The gutter should not be pushed off the screen and the entire ace_scroller component should not be shifted left.

### Current Behavior

Gutter disappears off screen to left, and the ace_scroller component is pushed left, limiting the viewable area with text.

### Reproduction Steps

I am also using a package react-ace.
this is my ace editor component
`<AceEditor
        value={code}
        ref={editorRef}
        mode="python"
        theme="cloud9_day"
        onChange={(value, e) => {
          const editor = editorRef.current.editor;
          console.log('xcxc editor', editor)
          setCode(value);
        }}
        onCursorChange={(value, e) => {
          // if (value.getCursor().row <= 2) {
          //   setIsReadOnly(true);
          //   if (code.split(/\r\n|\r|\n/).length <= 3) {
          //     setCode((value) => value + "\n");
          //     value.moveCursorFileEnd();
          //   }
          // } else {
          //   setIsReadOnly(false);
          // }
        }}
        name="editor"
        showPrintMargin={false}
        setReadOnly={false}
        fontSize={18}
        style={{
          height: "500px",
          width: "500px",
        }}
        enableBasicAutocompletion={true}
        enableLiveAutocompletion={true}
        enableSnippets={true}
        setOptions={{
          useSoftTabs: true,
        }}
        readOnly={isReadOnly}
      />`

This is my css:
`#editor {
   position: absolute;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
}`

### Ace Version

1.7.1

**Comment by andrewnester** [comment]
I wasn't able to reproduce it on the kitchen sink here https://ace.c9.io/build/kitchen-sink.html
@lusol could you please confirm if you can reproduce in our demo page above?
