### ISSUE TITLE
Gutter indicators for annotations

### ISSUE THREAD

**Issue by ArunPatal** [ajaxorg/ace#4931]
### Describe the issue

I am trying to use new feature indicators for annotations but am getting error.
In settings i added => customScrollbar: "renderer"

But i get following error => Cannot read properties of undefined (reading '$updateDecorators')

![error](https://user-images.githubusercontent.com/30784805/191866678-29c0eaf8-a4a9-4e02-840b-d9c9689ec179.png)

### Links

no link

**Comment by andrewnester** [comment]
You need to set `customScrollbar: true`  instead
