### ISSUE TITLE
Ubuntu 22.04 Firefox hangs when ctrl-s pressed in ace

### ISSUE THREAD

**Issue by eric-seppanen** [ajaxorg/ace#4932]
### Describe the bug

On Ubuntu 22.04 with default Firefox config, if I press ctrl-s with the Ace editor open in a browser window, it causes Firefox to hang: the file dialog opens but is flickering and unresponsive.

I am able to toggle between hanging/not-hanging by going into Tools->Page Info, then changing Permissions->Override Keyboard Shortcuts. Setting "Allow" and I get a hang with ctrl-s; Setting "Block" and I get a working file dialog instead.

### Expected Behavior

Not hang the browser window.

### Current Behavior

Browser window and file dialog are hung.

### Reproduction Steps

On Ubuntu 22.04 with default Firefox config:
1. Go to https://ace.c9.io/
2. Click in the editor window.
3. Press ctrl-s.
4. A file dialog pops up, but it is flickering and unresponsive. The dialog or the browser window can't be closed.

### Additional Information/Context

I first discovered this issue on the Rust Playground (https://play.rust-lang.org/), who are using Ace.

I have a fairly plain install of Ubuntu 22.04 with the default configuration (snap package) Firefox 105.0-2.

### Ace Version

Whatever's running on https://ace.c9.io/

**Comment by eric-seppanen** [comment]
@andrewnester can you clarify what is needed in terms of "needs-reproduction-steps"? I included those in the bug report.

**Comment by andrewnester** [comment]
sorry, should be pending-reproduction instead
