### ISSUE TITLE
PhpWorker: php 'use' statement complaint

### ISSUE THREAD

**Issue by ron4mac** [ajaxorg/ace#4942]
### Describe the bug

scanner erroneously complains when there are backslashes (\\) in the 'use' statement.

### Expected Behavior

no complaint

### Current Behavior

Flags statement with " Syntax error, unexpected T_STRING, expecting '{' "

### Reproduction Steps

Open .php file using php mode. Enter line similar to the following:

`use Joomla\CMS\Factory;`

### Ace Version

1.11.2

**Comment by andrewnester** [comment]
Fixed and released in 1.12.0
