### ISSUE TITLE
Replace CSS Lint with Stylelint

### ISSUE THREAD

**Issue by adamjimenez** [ajaxorg/ace#4946]
### Describe the feature

CSS Lint appears to be dead/ abandoned and doesn't support newer CSS syntax.
I suggest replacing it with [stylelint](https://stylelint.io/).

### Use Case

E.g. code like this is flagged incorrectly with errors

```
:root {
--menu-expanded: 200px;
--menu-collapsed: 50px;
}
```

### Proposed Solution

Replace CSS lint with Stylelint

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### ACE version used

1.11.2

**Comment by AlexanderMisel** [comment]
Hope this can be fixed soon.

**Comment by In1quity** [comment]
Users from Wikimedia waiting for this fix too :)
Downstream: https://phabricator.wikimedia.org/T253463

**Comment by andredcoliveira** [comment]
Looking at Wikimedia's thread, this was fixed by updating Ace: https://phabricator.wikimedia.org/T342387.

Closing this. Feel free to reopen or create a new issue if it still persists.

**Comment by In1quity** [comment]
Hello! Thank you, but do I understand correctly that there are no plans to get rid of the outdated and unsupported library?

**Comment by andredcoliveira** [comment]
I may have closed this too soon. Getting rid of CSSLint to use instead something maintained and up-to-date—be it Stylelint or otherwise—would be great.

While there are no scheduled plans to replace it right at this moment, contributions are greatly appreciated. :)

**Comment by andredcoliveira** [comment]
Are you still seeing syntax flagged as having errors incorrectly?

**Comment by In1quity** [comment]
> Are you still seeing syntax flagged as having errors incorrectly?

No, in fact this was fixed by the new version, although it’s not clear why :)

**Comment by JohnnySn0w** [comment]
To add a vocie, I am actually running into issues in another program that uses Ace, with custom CSS I would like to use. There have been many features added since the 5 years ago that CSSLint was last updated

**Comment by C-Ezra-M** [comment]
This issue should have been high priority because it affects the MediaWiki extension Code Editor, and I can tell people are complaining about this validating CSS like it was 2016.

**Comment by whazor** [comment]
Hi all, we recommend to have a look at [ace-linters](https://github.com/mkslanc/ace-linters) that offers CSS support via the [vscode-css-languageservice](https://github.com/Microsoft/vscode-css-languageservice).
