### ISSUE TITLE
keybindings: Ace is relying on deprecated keyCode KeyboardEvent property

### ISSUE THREAD

**Issue by sokomari** [ajaxorg/ace#4952]
### Describe the bug

Ace relies on [KeyboardEvent.keyCode](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode) to know which key combination a user pressed. Ace finds which command to execute for a given key binding inside of [hash_handler](https://github.com/ajaxorg/ace/blob/23208f2f19020d1f69b90bc3b02460bda8422072/src/keyboard/hash_handler.js#L194) from a [keyString](https://github.com/ajaxorg/ace/blob/23208f2f19020d1f69b90bc3b02460bda8422072/src/keyboard/keybinding.js#L110) variable created in [keys:keyCodeToString](https://github.com/ajaxorg/ace/blob/23208f2f19020d1f69b90bc3b02460bda8422072/src/lib/keys.js#L154). 

Maintaining this big dictionary inside of keys.js is no longer necessary as modern browsers use [KeyboardEvent.code](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code) and [KeyboardEvent.key](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key) properties.

Reason for switching from the deprecated property would be (besides the guideline that "this feature may cease to work at any time") that some newer libraries for mocking user interaction in the browser, such as [user-event](https://github.com/testing-library/user-event) which is a recommended interaction library for https://testing-library.com/, only use the modern properties, see [keyboard.ts](https://github.com/testing-library/user-event/blob/main/src/system/keyboard.ts#L110-L111). 
One could argue that this is a mistake on their end and not on Ace, as user-event is failing in mimicking actual browser behaviour but a counter-argument would be that it does not make sense to implement a deprecated property and allow consumers to rely on something that could stop working any day. 

The effort is not of technical nature but mostly that of manual effort as keys inside of [keys.js](https://github.com/ajaxorg/ace/blob/23208f2f19020d1f69b90bc3b02460bda8422072/src/lib/keys.js#L154) would need to be replaced with their accompanying KeyboardEvent.code values. 
A good resource to use for checking comparison is https://www.toptal.com/developers/keycode. 

I don't know how to prioritise this best among the other "deprecated" properties inside of Ace. 
I also don't know if this property will ever get really deprecated by the browsers or not.

### Expected Behavior

I would expect that Ace does not depend on deprecated properties.

### Current Behavior

See above.

### Reproduction Steps

None.

### Ace Version

1.9.5

**Comment by nightwing** [comment]
Implementing this will most likely break backwards compatibility of the keybinding api. Should we do that or should as a temporary measure implement a fallback for the case of missing keyCode, to fix the the issue for the users of testing-library, and cleanup the old code some time in the future.
