### ISSUE TITLE
Unicode Support 

### ISSUE THREAD

**Issue by PrathameshBhagat** [ajaxorg/ace#4953]
### Describe the feature

I expect/ask ACE developers to add unicode support in keyword search and regex uses so as to have extra character support this was not supposed to be an issue as java-script and regex both support unicode  but some how ACE doesn't seems supporting it.

### Use Case

`` var specialInteger ="(((?:0[x][\\d]+)))";``
in place of x I want to have a unicode character 
eg:[©] (obviously ,not this one it is just an example, I know it seems very silly but I need it and other might too would like to have unicode support).

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### ACE version used

1.11.2

**Comment by nightwing** [comment]
Is your question about syntax highlighters or the search feature?
As far as i can see `/[©]/` works in both cases, so more detailed description of the issue would be helpful.

**Comment by PrathameshBhagat** [comment]
Ya, there is a lot about the copy right character but devnagri characters pose issues (already not much reference available ) and in here ace takes characters with non space masking as space markings that is while printing characters it prints correctly but when spacing these characters the which should not be given spaces ace assigns them spaces. 
Example: 
 The character À is made of two characters(we can say) A and ` while printing/displaying it shows it as À but while considering the space it should takes it a single character. 
Similarly in devnagri characters like   “ी ” are supposed to printed with a character "ब"  as" बी"which ace does correctly (and not asब ि [inverted] ) , 
BUT it assigns बी a character space of two characters. 
This creates problem if (in java) we write this in a single line:

System.out.print("hello there ,आजी की  ऐसी की तैसे  is a rough word in hind please do not use such language in our messaging platform");

Then if you try to rewrite "word in"  as "word of" you would end up messing the characters you didn't even wanted to touch if you delete "n" then "i" is deleted and so on .
Live example:[ https://prathameshbhagat.000webhostapp.com/ace-issue.php
]
In this string only one character before cursor is messed up with but in other strings
it is able to mess with up to 5-10 characters before the cursor .Which makes devnagri useless in ace .(sorry for grammer mistakes and wrong selection of words ).
 
I am so sorry if I wrongly assumed that ace doesn't support Unicode(copyright is a unicode char which works fine) I thought the issue was because of that thing .

Also I ask you to clear my doubt on the issue I raised which you closed
I am using CDN and embedding ace through single script tag `<script src=https://cdn.cloud............ace.js>`
and I have a file with a ace mode file which run successfully on
https://ace.c9.io/tool/mode_creator.html 
but I found no way to use that file as ace is in cloud and my myjava.js file is in my local storage , you asked me to use 
`ace.define("myMode", Mode); editor.session.setMode("myMode") `
but I don't understand what is "myMode" and Mode .(I might be confused in which is a string referencing my mode file and which is the object ).
I have my mode file in same directorty named as myjava.js after searching I got to know to place it at ace/lib/mode if using nodes but I am using cdn   
so tried I embedding my mode file with   `<script src="myjava.js">`
then tried:
`ace.define("myjava", Mode); editor.session.setMode("myjava") `
which didn't work , console said "unable to find myjava.js ".
please help .
I think I need and example of custom mode without npm and using "CDN" /embedding etc.

THANKS FOR YOUR TIME
