### ISSUE TITLE
PhpWorker: syntax error, unexpected T_NS_SEPARATOR

### ISSUE THREAD

**Issue by masterWeber** [ajaxorg/ace#4957]
### Describe the bug

Scanner erroneously complains when '\\' is specified before the function call.

### Expected Behavior

No complaint

### Current Behavior

Flags statement with "Syntax error, unexpected T_NS_SEPARATOR"

![image](https://user-images.githubusercontent.com/47494224/196025298-d81551f4-7b78-4d9d-a2cd-7f280699ecc9.png)

### Reproduction Steps

Open .php file using php mode. Enter line similar to the following:

```php
<?php

\array_sum([1, 1]);
```

### Ace Version

1.12.0

**Comment by andrewnester** [comment]
seems like might be related to recent changes by @mkslanc . Any chance you can take a look?

**Comment by mkslanc** [comment]
It's reproducible on version before my changes, but I will take a look.

**Comment by masterWeber** [comment]
The previous version had the same problem. Any idea how to fix it, at least temporarily?

**Comment by masterWeber** [comment]
Maybe you can change the `T_NAME_FULLY_QUALIFIED` pattern to 
```regex
/^\\\w+(?:\\\w+)*/
```
?

**Comment by mkslanc** [comment]
@masterWeber not sure, if we could treat that case as `T_NAME_FULLY_QUALIFIED`. According to [official PHP manual](https://www.php.net/manual/en/tokens.php) `T_NAME_FULLY_QUALIFIED` is `\App\Namespace`. But that could work, I guess. Better implementation will be possible, when LSP would be implemented

**Comment by masterWeber** [comment]
New versions of PHP have adopted RFC https://wiki.php.net/rfc/namespaced_names_as_token

![image](https://user-images.githubusercontent.com/47494224/196141491-ca7ce72d-ce75-46ae-a705-8627d4317259.png)

**Comment by andrewnester** [comment]
Fixed and released in 1.12.1
