### ISSUE TITLE
Ace Editor: Editor is shifting when number of lines increase 99 -> 100 -> 1000

### ISSUE THREAD

**Issue by mateBe95** [ajaxorg/ace#4964]
### Describe the bug

Ace Editor: Editor is shifting when number of lines increase 99 -> 100 -> 1000. Which is annoying when someone is scrolling file and editing code while have hundreds line of code.

[DEMO](https://gfycat.com/pl/joyousreliableazurevasesponge)

### Expected Behavior

Not shifting whole editor code.

### Current Behavior

The editor is moving when get line of code from 99 -> 100 -> 1000

### Reproduction Steps

Scroll down between 99 - 100 line of code.

### Additional Information/Context

Recreated in official website: https://securingsincity.github.io/react-ace/

### Ace Version

9.5.0

**Comment by nightwing** [comment]
You can use `editor.setOption("fixedWidthGutter", true)` to disable this behavior.

**Comment by mateBe95** [comment]
@nightwing perfect, it works fine. Just thinking if that property should be by default on.
