### ISSUE TITLE
Custom Scrollbar: Introduced in v 1.11.0 breaks the useStrictCSP feature.

### ISSUE THREAD

**Issue by dmiskiew** [ajaxorg/ace#4966]
### Describe the bug

Version 1.11.0 introduced custom scrollbar, but the implementation triggers `dom.importCssString` before developer is able to set the useStrictCSP option. 

https://github.com/ajaxorg/ace/commit/4ad83b44b5189796acad20476400ac6740583e54#diff-1c4f80ea8a9d510f282e9604068f09da03b59661c446e494340737d018de9f23R8

### Expected Behavior

The `importCssString` in the custom scrollbar code should be postponed to the moment where the lib is fully loaded and configured by developer.

### Current Behavior

The `importCssString` in the custom scrollbar code is executed too early and it loads inline css even though useStrictCSP is set to true. See screenshots from the demo code from the ace-builds 1.11.0:

![image](https://user-images.githubusercontent.com/159009/196367713-223a47ab-1ea9-433d-8b83-006907201be0.png)

![image](https://user-images.githubusercontent.com/159009/196367830-bc116681-1723-4095-a22b-ac0ddb424543.png)

### Reproduction Steps

1. Checkout tag v1.11.0
2. Setup nginx to server ace-builds demo folder
3. Go to demo/csp.html
4. Check the dev console error:
```
ace.js:716 Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-kil1FKxYyh+wG/uCXP8XTsNpS3ZlhE2U+v9JRxk3q14='), or a nonce ('nonce-...') is required to enable inline execution.
```

### Possible Solution

Postpone calling the `importCssString` in the custom scrollbar code to the moment where the lib is fully loaded and configured by developer.

### Ace Version

1.11.0

**Comment by andrewnester** [comment]
Fixed and released in 1.12.2
