### ISSUE TITLE
Better bibtex language support

### ISSUE THREAD

**Issue by dbitouze** [ajaxorg/ace#4969]
### Describe the feature

The recent addition of `bibtex` as know language is nice but it could be better. E.g. with the default `bibtex` file on https://ace.c9.io/build/kitchen-sink.html:

```bibtex
@Comment{
  @Book{tes03,
    author =	 {John Smith},
    title =	 {Cooking},
    publisher =	 {Culinary Expert},
    year =	 1890
  }
}

@String(mar = "march")

@Book{sweig-42,
  Author =	 { Stefan Sweig },
  title =	 { The impossible book },
  publisher =	 { Dead Poet Society},
  year =	 1942,
  month =        mar
}

@String {firstname = "John"}
@String {lastname  = "Smith"}
@String {email      = firstname # "." # lastname # "@imag.en"}

@Article{key01,
  title = { The history of @ sign }
}

Everything " " outside {entries} is treated as comment in BibTeX.

@Article{key03,
  title = "A {bunch {of} braces {in}} title"
}

@preamble {"This bibliography was generated on \today"}
```

it would be nice for the attributes `author`, `title`, `publisher`, etc. (which precede the `=`) to be displayed with a different color than the one used for the values of these attributes.

Here is an example of the syntax highlighting of the same content with `Emacs`:

![emacs-bibtex](https://user-images.githubusercontent.com/1032633/196496985-cc32f59a-8a0b-42a3-a387-489b0edda5fb.png)

### Use Case

The different parts of (and roles inside) a `bibtex` file would be much more readable.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### ACE version used

1.12.3 I guess (tested on kitchen-sink)

**Comment by dbitouze** [comment]
@akoreman You're welcome! Here it is.
![Screenshot_20230509_204609](https://github.com/ajaxorg/ace/assets/1032633/10ef04bd-d500-4792-becc-1c4b60f28dc8)

**Comment by akoreman** [comment]
I fear I'm missing something. On your screenshot I see different colours being used for attributes and values. The one place I see this not happening is the first block which starts with `@Comment`, which is interpreted as a comment and therefore has no syntax colours applied to it.

**Comment by akoreman** [comment]
No problem, glad I could help.
