### ISSUE TITLE
json:worker-json.js requested in addition to worker-json.min.js

### ISSUE THREAD

**Issue by dougbreaux** [ajaxorg/ace#4978]
### Describe the bug

worker-json being requested despite worker-json.min being explicitly pulled

Source file has:
```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.12.5/ace.min.js" integrity="sha512-K7n6K4ZhcyKt/fNqbMfrWj1lj0/kwg2B0BoXnqWpyg3Pzr70hyVdCwQnaBXaVd1vyf6d174/vOuW+zdtuNv0xA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.12.5/mode-json.min.js" integrity="sha512-YXUz04sMmhEPQR5FLg4/6MFWcrTzZRobwv6cEVWsX9bfos1lm/Z5hfVz4WB3Z3XyhcVjWWUOvudJ+CCxecDI7Q==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.12.5/worker-json.min.js" integrity="sha512-8PeKq5s4wXW1hBlFs8iurh7aHffuwT8mZNN4eR4mL7Vl7kZV3bpcBY41NtxLJvfTcMj84eMYo9bRr+TJshS19Q==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
```
And:
```html
    <script>
    function createEditor() {
        var editor = ace.edit("jsonEditor", {
            mode: "ace/mode/json",
            selectionStyle: "text",
            minLines: 16,
            maxLines: 30
        });
        var textarea = $('textarea[name="document"]').hide();
        editor.session.setValue(textarea.val());
        editor.session.on('change', function(){
          textarea.val(editor.session.getValue());
        });
    }
    </script>
```

### Expected Behavior

This is sufficient for JSON editing

### Current Behavior

worker-json.js is also requested from our server, and, of course, not found

### Reproduction Steps

See above

### Additional Information/Context

Also, is there some clear documentation on how to use the minified source? I had to use trial and error to figure out which files I needed, then hit this 404. The editor actually seems to be working fine, but still requesting this non-included file.

### Ace Version

1.12.5

**Comment by nightwing** [comment]
`worker-*.js` files must be loaded into a webworker to work, so including the script in the page does not help.
What are you trying to achieve ny including it via script tag?

**Comment by dougbreaux** [comment]
Without it, I got a 404 from _that_ trying to be requested.

**Comment by Kat-Klauber** [comment]
> `worker-*.js` files must be loaded into a webworker to work, so including the script in the page does not help. What are you trying to achieve ny including it via script tag?

So then what are the recommended steps to a solution, if that's incorrect?

I am also having this problem and tried the same thing: putting the script tag for worker-json.min into my file. The editor works, and the error message changed in nature when I did that, but I can't get rid of the error altogether.

**Comment by nightwing** [comment]
It appears that cdnjs changes the file name of ace script which prevents automatic detection of basepath. Using
```js
ace.config.set("basePath", "https://cdnjs.cloudflare.com/ajax/libs/ace/1.15.2")
```
or loading `<script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.15.2/ace.js" ` would fix the issue.

here's an example that works:
```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.15.2/ace.min.js"   
 crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script> 
    ace.config.set("basePath", "https://cdnjs.cloudflare.com/ajax/libs/ace/1.15.2")
    var editor = ace.edit(null, {
      mode: "ace/mode/json",
      selectionStyle: "text",
      minLines: 16,
      maxLines: 30,
      value: "{json: 1}",
    });
    document.documentElement.appendChild(editor.container)
      
</script>
```

https://jsbin.com/nawodayafu/edit?html,output

**Comment by dougbreaux** [comment]
@nightwing Use 
`<script src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.15.2/ace.js"`
instead of the minified version, is that what you're saying? 

Or, if using the minified, use the basePath with it?

**Comment by nightwing** [comment]
ace.js is minified too not sure why cdnjs is generating the second file

But since v1.5.3 ace detects base path even if it is inserted with a renamed script, so it will work without basePath now.

btw when not working ace was displaying an error message in browser console saying `Unable to infer path to ace from script src, use ace.config.set('basePath', 'path') to enable dynamic loading of modes and themes or with webpack use ace/webpack-resolver` had you noticed that message, and was it of any help?
