### ISSUE TITLE
Multiple user with the line locking ability per user

### ISSUE THREAD

**Issue by SOG-web** [ajaxorg/ace#4984]
### Describe the feature

I want to make it possible to make a line read-only for one of the users typing on ace editor.

### Use Case

I have an app that uses ace editor for code collaboration with multiple users but, I dont want more than one user to be typing on the same line at a time

### Acknowledgements

- [X] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### ACE version used

1.4.12

**Comment by InspiredGuy** [comment]
hey @SOG-web , you want to make a certain line in the editor read-only, is my understanding correct? there are some proposed solutions for a similar problem in another issue https://github.com/ajaxorg/ace/issues/3634, for example https://stackoverflow.com/questions/39640328/how-to-make-multiple-chunk-of-lines-readonly-in-ace-editor.
