### ISSUE TITLE
Editor: Tilde input

### ISSUE THREAD

**Issue by maros** [ajaxorg/ace#4999]
### Describe the bug

Delting a "temporary" tilde character using backspace, deletes three additonal characters before the tilde

### Expected Behavior

Deleting a "temporary" tilde character deletes just the tilde, not anything else

### Current Behavior

It deletes three additonal characters before the tilde

### Reproduction Steps

1. Type '123456789'
2. Type '~' (it is now marked as "temporary" since it needs another keystroke to compose or actually write)
3. Hit 'Backspace'
4. It deletes the tilde, as well as '789', leaving only '123456'

### Ace Version

v1.13.1

**Comment by nightwing** [comment]
For which operating system, browser and language/keyboard does this happen?

**Comment by maros** [comment]
OSX: 12.6.1
Browser: All tested (Firefox 106, Safari 16.1 as well as Chromium)
Keyboard: All tested (British, German ...)

**Comment by ratulSharker** [comment]
Hi @maros,

I tried to re generate the issue by following the above steps, but could not generated it.

https://github.com/ajaxorg/ace/assets/5053324/f8ba8b63-3832-492c-8376-86796423f6d7

I think i didn't understood the step 2.

> Type '~' (it is now marked as "temporary" since it needs another keystroke to compose or actually write)

I just typed the character `~` (tilde).

My environment:
- Ace version: v1.32.1
- Safari: 16.6.1
- OSX: 11.7.10

**Comment by nightwing** [comment]
To reproduce us Firefox on mac and instead of `~` type `option-n` if you are using the default `ABC` keyboard layout. With other keyboard layouts you need to find characters that start text composition inserting symbols that add diacritics to letters.
