### ISSUE TITLE
Autocomplete/Language Tools: Potential issue with doc tooltip

### ISSUE THREAD

**Issue by dodgex** [ajaxorg/ace#5004]
### Describe the bug

I am working on a project using Ace and would love to utilize the Doc Tooltip in the autocompletion feature.

Unfortunately the Typescript definitions in `ace.d.ts` do not have the required definitions. As I have not found any documentation about this feature, I started to read the code to find how to implement that Tooltip for my completer. While reading the code I might have found some potential issues.

### Expected Behavior

Have proper Type Definitions and implementations to use Doc Tooltip in custom Completer.

### Current Behavior

In [autocomplete.js](https://github.com/ajaxorg/ace/blob/v1.13.1/src/autocomplete.js#L342-L346) the `updateDocTooltip()` uses [`.some()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some) to iterate over an array of `completers` to find a completer that has a `getDocTooltip()` and returns a value for the selected item. Either, the `getDocTooltip()` (currently the only one is defined in [language_tools.js](https://github.com/ajaxorg/ace/blob/v1.13.1/src/ext/language_tools.js#L60-L67)) should return a value (`string` or `{docHTML: string}` or `{docText: string}`) to truly utilize the `.some()` or it should be a `.forEach()` instead.

### Reproduction Steps
None.

### Possible Solution

I would love to have the [`Completion` in `ace.d.ts`](https://github.com/ajaxorg/ace/blob/v1.13.1/ace.d.ts#L313-L319) include the `docHTML?: string` and/or `docText?: string` fields that could be [used directly](https://github.com/ajaxorg/ace/blob/v1.13.1/src/autocomplete.js#L347-L348).

The `getDocTooltip()` should either be defined in the [`Completer` in `ace.d.ts`](https://github.com/ajaxorg/ace/blob/v1.13.1/ace.d.ts#L909-L917) too, or in theory it could be replaced with directly defining docHTML/docText in the Completition Item in `language_tools.js`.

### Ace Version / Browser / OS / Keyboard layout

1.13.1

**Comment by akoreman** [comment]
In version 1.17.0 type definitions for doc tooltips were added, see #5005 for more details.
