### ISSUE TITLE
CSS level4 :not() pseudo-element marked as error when it has a complex selector

### ISSUE THREAD

**Issue by bawolff** [ajaxorg/ace#5018]
### Describe the bug

per https://w3c.github.io/csswg-drafts/selectors/#negation starting in CSS level 4, `:not()` pseudo-classes can now contain complex selectors e.g. `:not(a,b)`. However ACE gives an "Expected LBRACE" error when you use this syntax

This is new in CSS4. in css3 `:not` was only allowed to have simple selectors

### Expected Behavior

ACE syntax highlight to accept the valid CSS syntax as valid.

### Current Behavior

error about expected LBRACE and unexpected token `)`

### Reproduction Steps

I tested this at https://ace.c9.io/build/kitchen-sink.html in CSS mode
```
:not(a, b) {   
    color:red;
}
```

### Additional Information/Context

* Official spec: https://w3c.github.io/csswg-drafts/selectors/#negation
* https://developer.mozilla.org/en-US/docs/Web/CSS/:not mdn docs
* https://caniuse.com/css-not-sel-list
* Originally reported at https://www.mediawiki.org/wiki/Topic:X8lmvrv27ymmfuog

### Ace Version / Browser / OS / Keyboard layout

Linux, firefox, US-english

**Comment by justcaldwell** [comment]
Just noting that complex selector support also extends to `:is()`, `where:()` and `has:()`. Maybe others, those are just what come to mind.

**Comment by akoreman** [comment]
Another similar feature request for CSS4 selector support was made in issue #5129.

**Comment by dpierangeli** [comment]
Has is now baseline, i find a lot of css with that.
It would be nice if it was supported.
