### ISSUE TITLE
(touchhandler): (toucstart judgment is incorrect)

### ISSUE THREAD

**Issue by jxs7754** [ajaxorg/ace#5019]
### Describe the bug

e.timeStamp  A negative number is returned in mobile safari,The touchstart judgment is incorrect

### Expected Behavior

can use  TimeStamp, but not e.tiemstamp

### Current Behavior

clisk event  become  dbclick event

### Reproduction Steps

in mobile safari

### Ace Version / Browser / OS / Keyboard layout

1.6

**Comment by andrewnester** [comment]
Could you please clarify in a bit more details what exactly are you doing and your expectation from Ace? code snippet can be useful too. Also please try it on the latest Ace version.
