### ISSUE TITLE
Automatic tab-space conversion mis-alignment

### ISSUE THREAD

**Issue by GaoOufan** [ajaxorg/ace#5021]
### Describe the bug

I am not sure if it is related to the Ace core engine or to the programming language mode itself, but there is misalignment in the way "tabs" are replaced to spaces - this happen in many languages like Javascript, Python, Perl, HTML, CSS, all have this issue, especially when exceeding 4 depth layers of indention. 

In general this not that much of a matter, but In Python, however, this is critical and causing script crash. 

Mybe it is related with the configuration, I am not sure, and I have no idea how to configure it, if so. 

You may have a try on large script, when indention exceeds 4 depth layers. 

### Expected Behavior

1 Tab is defined as 4 spaces. I expected it either remain as a "tab" character, either be converted to exactly 4 spaces.

### Current Behavior

In many cases, exceeding 4 depth layers of indention (requires 4 "tab" characters in a single row) the behaviour is confused and very misaligned: It may be some spaces and some remain "tab" characters. Then, text may get shifted by a character so the cursor is not pointing of the correct position (that is another issue perhaps related).
In Python, it is critical to keep indention even.

### Reproduction Steps

Whenever there is large code that requires more than 4 depth layers of indention.

### Possible Solution

Will be the best if can maintain constant indention way, either tab either spaces, configurable. 

### Ace Version / Browser / OS / Keyboard layout

Happened on different browsers (FF, Chrome, Edge, Safari), Ace v.1.4.14

**Comment by nightwing** [comment]
Could you please tell us more detailed steps to reproduce the issue, I was not able to reproduce it by indenting code in https://ace.c9.io/build/kitchen-sink.html?mode=python&doc=Python. Could you also try to turn on the showInvisibles option to see what combination of spaces is in editor initially.

**Comment by GaoOufan** [comment]
Hi; 



Yes, seems that I missing something: 

I am using it in a small <form&gt; (resizable), and with custom theme ("ef"), and maybe this affects, I would like to know why and how to fix this problem.


Attached here the theme structure I am using (in a ZIP file, as I cannot directly attach "js" files)


Thanks a lot




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ajaxorg/ace"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月13日(星期五) 晚上6:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ajaxorg/ace] Automatic tab-space conversion mis-alignment (Issue #5021)





 
Could you please tell us more detailed steps to reproduce the issue, I was not able to reproduce it by indenting code in https://ace.c9.io/build/kitchen-sink.html?mode=python&amp;doc=Python. Could you also try to turn on the showInvisibles option to see what combination of spaces is in editor initially.

**Comment by nightwing** [comment]
Sadly github did not allow the zip file you are talking about. Could you send it directly to me, or create a demo on jsbin?

**Comment by GaoOufan** [comment]
Ok, I am sending the theme file directly here as TXT file
[theme-ef.js.txt](https://github.com/ajaxorg/ace/files/10426481/theme-ef.js.txt)

This done from existing theme that been modified (just colors), so I suspect that maybe what could cause the issue is something in this theme...? 

Thank you

**Comment by akoreman** [comment]
Could you try whether you can reproduce this issue using one of the default Ace themes?
