### ISSUE TITLE
Selection invisible in Windows high-contrast mode

### ISSUE THREAD

**Issue by gtritchie** [ajaxorg/ace#5028]
### Describe the bug

On Microsoft Windows 10 or 11, using recent Chrome, Edge, or Firefox, load the Kitchen sink (https://ace.c9.io/build/kitchen-sink.html).

Select some text in the editor.

Turn on Windows high contrast mode with <kbd>Left Alt</kbd>+<kbd>Left Shift</kbd>+<kbd>Print Screen</kbd>. Can also enable via settings (search for High Contrast).

The browser updates to show the page in high-contrast / forced color mode.

### Expected Behavior

The editor should remain usable, including being able to see when text is selected.

### Current Behavior

There is no visual indication of selected text.

### Reproduction Steps

On Microsoft Windows 10 or 11, using recent Chrome, Edge, or Firefox, load the Kitchen sink (https://ace.c9.io/build/kitchen-sink.html).

Select some text in the editor.

Turn on Windows high contrast mode with <kbd>Left Alt</kbd>+<kbd>Left Shift</kbd>+<kbd>Print Screen</kbd>. Can also enable via settings (search for High Contrast).

The browser updates to show the page in high-contrast / forced color mode.

### Possible Solution

https://support.microsoft.com/en-us/windows/change-color-contrast-in-windows-fedc744c-90ac-69df-aed5-c8a90125e696
https://blogs.windows.com/msedgedev/2020/09/17/styling-for-windows-high-contrast-with-new-standards-for-forced-colors/
https://www.smashingmagazine.com/2022/03/windows-high-contrast-colors-mode-css-custom-properties/

### Ace Version / Browser / OS / Keyboard layout

Windows 10/11, Chrome/Edge/FireFox

**Comment by nightwing** [comment]
Should we simply add `forced-color-adjust: none` the way monaco does it, or should we try to get it to use the forced colors?

**Comment by bassettsj** [comment]
Encountering the same issue, I would be interested in contributing a fix if interested.
