### ISSUE TITLE
(module name): (short issue description) there is some issue of overlapping line and the text cursor is also stops when typing and some extra space taking

### ISSUE THREAD

**Issue by Achal4004** [ajaxorg/ace#5029]
### Describe the bug

<img width="485" alt="image" src="https://user-images.githubusercontent.com/51490652/213533212-f44429ac-7268-4902-a7c7-4962c03f6fca.png">

### Expected Behavior

Should work

### Current Behavior

Not working

### Reproduction Steps

there is some issue of overlapping line and the text cursor is also stops when typing and some extra space taking

### Ace Version / Browser / OS / Keyboard layout

"^1.14.0"

**Comment by andrewnester** [comment]
Please clarify the Expected and Current behaviour in more details so we can better triage, reproduce and work on the issue. Closing it until clarified
