### ISSUE TITLE
Some links to demos don't work

### ISSUE THREAD

**Issue by jamesdanielspassle** [ajaxorg/ace#5060]
### Describe the issue

Some of the link in this page don't work:
https://www.npmjs.com/package/ace-builds
For example, the links in this text:
To see ace in action go to [kitchen-sink-demo](http://ajaxorg.github.com/ace-builds/kitchen-sink.html), [scrollable-page-demo](http://ajaxorg.github.com/ace-builds/demo/scrollable-page.html) or [minimal demo](http://ajaxorg.github.com/ace-builds/editor.html)

### Links

https://www.npmjs.com/package/ace-builds

**Comment by InspiredGuy** [comment]
This should be fixed with [this PR to ace-builds repo](https://github.com/ajaxorg/ace-builds/pull/225)
