### ISSUE TITLE
Split long list to smaller list

### ISSUE THREAD

**Issue by JonnyLeiZhang** [ajaxorg/ace#5078]
### Describe the feature

We encounter one performance problem, when there's a super big array (amount around 30000), by default we'll fold it, but when we want to unfold it, it will take around 4 minutes to get response. So can we split it to several smaller ones?

### Use Case

to have a better experience when we have big array.

### Proposed Solution

Split into smaller ones like console does in browser. 
![image](https://user-images.githubusercontent.com/45590945/222683199-0400f736-7e89-426c-a6a2-76750fc90075.png)

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### ACE version used

1.4.12

**Comment by JonnyLeiZhang** [comment]
Hi @nightwing ,
Thanks for your quick reply, I have a try myself with the file, you're right, it doesn't have any problem, it can load quickly.
It's not a performance issue, sorry for the confusion.

And consider the ease of use, do you see any possibility to support this function? I mean if the array is too long, we can have a better way to locate the info we need. Split the array to chunks with length 'N'?

BR/Lei

**Comment by nightwing** [comment]
It depends on details of what exactly you want to achieve, it is already possible to add multiple  folds inside the big one, but i need more info about your usecase to tell something useful.

**Comment by JonnyLeiZhang** [comment]
Hi,
I cannot give a persuasive use case now, I'll close this.
Thanks for your support! Nice day!

BR/Lei
