### ISSUE TITLE
Autocomplete with project-wide variables

### ISSUE THREAD

**Issue by gabriel-fsa** [ajaxorg/ace#5096]
### Describe the feature

A way to export all variables types from a project to several files, to help with autocomplete.

### Use Case

Create or edit a file of an existing project, and when making imports, use of global variables the autocomplete knows how to do, for example the autocomplete of vscode.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### ACE version used

1.16.0

**Comment by akoreman** [comment]
The concept of projects doesn't currently exist within Ace and it probably makes most sense to implement project-like features as a layer on top of Ace (e.g. using something like LSP) and defining a custom Ace completer (for an example of that see the link in our relevant [wiki page](https://github.com/ajaxorg/ace/wiki/How-to-enable-Autocomplete-in-the-Ace-editor)).

**Comment by nightwing** [comment]
@gabriel-fsa https://github.com/mkslanc/ace-linters allows to use [LSP](https://microsoft.github.io/language-server-protocol/) like vscode, allowing to provide more flexible autocompletion.
