### ISSUE TITLE
ACE: Fails to import with Webpack

### ISSUE THREAD

**Issue by mryellow** [ajaxorg/ace#5099]
### Describe the bug

```
WARNING in ./node_modules/ace-code/src/config.js 135:21-40
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/ace-code/src/ace.js 28:0-36
...
```

### Expected Behavior

Should successfully provide the library on `ace`.

### Current Behavior

Fails.

### Reproduction Steps

`npm i ace-code`

`import ace from 'ace-code';`

### Ace Version / Browser / OS / Keyboard layout

1.16.0

**Comment by nightwing** [comment]
The warning here is a bit annoying, but it should not affect any of editor functionality. Does the editor not work for you or is this issue only about removing the annoying error?

**Comment by mryellow** [comment]
`ReferenceError: ace is not defined`

With either:

`import ace from 'ace-code';`
or
`import ace from 'ace-builds';`

Is there any documentation on using this as a module without requiring an external CDN provided build?

**Comment by nightwing** [comment]
https://github.com/ajaxorg/ace-samples/tree/master/samples has examples of using ace with different bundlers

**Comment by InspiredGuy** [comment]
hey @mryellow have you had a chance to check out samples for helpful information? if that doesn't work out, please send a minimal demo of using ace with your webpack config, so others would be able to reproduce the issue.

**Comment by mryellow** [comment]
I don't have time to really chase it down, just switching editors instead.

A bot hiding issues isn't helpful.

**Comment by InspiredGuy** [comment]
The fix will be included in the next release.
