### ISSUE TITLE
Formatting lost on copy with Safari 16.4 for Python and YAML

### ISSUE THREAD

**Issue by whazor** [ajaxorg/ace#5112]
### Describe the bug

When copying something from Ace and afterwards pasting somewhere else, the enters are lost.

### Expected Behavior

When copying lines with enters and pasting somewhere else, it should keep the enters.

For example, it should paste:
```
    try:
        fahrenheit=float(string.atoi(i))
    except string.atoi_error:
        print repr(i), "not a numeric value"
```

### Current Behavior

Now the enters are lost, resulting into:
```
try:        fahrenheit=float(string.atoi(i))    except string.atoi_error:        print repr(i), "not a numeric value"
```

### Reproduction Steps

1. Update to Safari 16.4
2. Open https://ace.c9.io/build/kitchen-sink.html
3. Switch to YAML/Python
4. Copy multiple lines (not whole file), make sure the lines have start with indentation 
5. Paste somewhere else
Result: `try:        fahrenheit=float(string.atoi(i))    except string.atoi_error:        print repr(i), "not a numeric value"`

### Additional Information/Context

So far this bug does not happen on other languages like Javascript, Typescript or Coffeescript, only with Python and YAML.

### Ace Version / Browser / OS / Keyboard layout

Safari 16.4 and Ace kitchen

**Comment by whazor** [comment]
When copying a YAML file to the JavaScript file, the problem still exists. So it is related to the kind of indenting of yaml/python text.

**Comment by whazor** [comment]
It seems to be a problem in the newest webkit, there are multiple bugs related to `clipboardData.setData`:
- https://bugs.webkit.org/show_bug.cgi?id=17645
- https://bugs.webkit.org/show_bug.cgi?id=22017
- https://bugs.webkit.org/show_bug.cgi?id=104179
- https://bugs.webkit.org/show_bug.cgi?id=142843

When testing, two scenarios:
```javascript
clipboardData.setData("text/plain", `test1\ntest2\ntest3`)
```
Results into:
```text
test1
test2
test3
```
And:
```javascript
clipboardData.setData("text/plain", `test: 1\ntest2\ntest3`)
```
Results into:
```
test: 1test2test3
```
Eating up all the enters

**Comment by nightwing** [comment]
This works in safari 15, so must be a very recent regression, which is not reported to webkit. Do you see the same issue with navigator.clipboard too, or does it affect only the event?

**Comment by whazor** [comment]
Sorry yeah, I missed the dates. Let me create a new ticket for it then.

This works fine indeed with `navigator.clipboard.writeText`.

**Comment by whazor** [comment]
Created a new ticket: https://bugs.webkit.org/show_bug.cgi?id=255150

I verified that this problem also exists in other editors.

**Comment by whazor** [comment]
In Safari Technology Preview 167 the issue is resolved.
