### ISSUE TITLE
Link to themes is broken (404)

### ISSUE THREAD

**Issue by pawamoy** [ajaxorg/ace#5122]
### Describe the issue

In https://ace.c9.io/#nav=howto, the link to the list of themes is broken: https://github.com/ajaxorg/ace/tree/master/lib/ace/theme.

I've found this instead, not sure how much up-to-date it is: https://gist.github.com/RyanNutt/cb8d60997d97905f0b2aea6c3b5c8ee0

### Links

https://ace.c9.io/#nav=howto

**Comment by nightwing** [comment]
Added a fix for this in https://github.com/ajaxorg/ace/pull/5118. 

The new link is https://github.com/ajaxorg/ace/tree/master/src/theme, and there is also https://github.com/ajaxorg/ace/blob/master/src/ext/themelist.js for getting the list of available themes programmatically.

**Comment by pawamoy** [comment]
Awesome, thanks! Let me know when it's merged so I close this issue :slightly_smiling_face: (or feel free to close it yourself if you have sufficient access!)
