### ISSUE TITLE
CSS level4 :has() & :is() pseudo-class fail to validate

### ISSUE THREAD

**Issue by andreiverzin** [ajaxorg/ace#5129]
### Describe the feature

per https://w3c.github.io/csswg-drafts/selectors/#relational and https://w3c.github.io/csswg-drafts/selectors/#matches CSS supports ;has() and :is() pseudo classes. But ACE shows validation error 🛑 while using them 

### Use Case

I need validation support for this pseudo-classes to use them in ace editor

### Proposed Solution

please add validation support ✅ for :has() and :is() pseudo classes to use them in editor

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### ACE version used

latest

**Comment by akoreman** [comment]
Thanks for raising the issue, a similar feature request for CSS4 selector support was made in issue #5018. I'll add a comment to that issue linking to this feature request and close this issue so that we have single place to track this feature request.
