### ISSUE TITLE
core: moduleUrl incorrect

### ISSUE THREAD

**Issue by kpalatzky** [ajaxorg/ace#5132]
### Describe the bug

Since version 1.17.0 our custom mode does not work anymore. The name of the mode is `ux/mode/custom`. 

In versions <1.17.0 it was loading the file `http://localhost:7070/ace/ux/mode-custom.js` but in the latest version it trys to load `http://localhost:7070/ace/lib/mode-custom.js` instead. 
Seems there were changes made in [this commit](https://github.com/ajaxorg/ace/commit/0f30e9c80786afe352247f2a7a97adae2a9c9a9e). 

Also moving the file to the incorrect location `http://localhost:7070/ace/lib/mode-custom.js` does not work as expected since the mode will be loaded correctly but not be used (`ace/mode/text` is used instead automatically) 

Therefor version 1.17.0 is currently unuseable for us.

### Expected Behavior

 A minor release should not change the behaviour/url. Loading of custom modes should still work. 

### Current Behavior

Incorrect module url is loaded and even with using the incorrect url the module does not get loaded correctly. 

### Reproduction Steps

1. Create a custom mode called `ux/mode/custom`
2. Configure mode `ux/mode/custom` 
3. Open ACE Editor.

### Possible Solution

May review changes of commit https://github.com/ajaxorg/ace/commit/0f30e9c80786afe352247f2a7a97adae2a9c9a9e (and depending commits)

### Ace Version / Browser / OS / Keyboard layout

1.17.0 / Chrome (latest) / Windows 10 / de-DE (German)

**Comment by nightwing** [comment]
This change would be a serious bug in any type of release not only major one.

Could you please help me to reproduce the issue. 

I have tried  to recreate something similar to what you describe in https://github.com/ajaxorg/ace-samples/blob/master/samples/ace-builds-cdn/cusom-mode-example/index.html#L13 but did not manage to replicate loading from lib behavior https://raw.githack.com/ajaxorg/ace-samples/master/samples/ace-builds-cdn/cusom-mode-example/index.html

Are you using ace-builds and `ace.config.setModuleUrl("ux/mode/custom", ...)` or something else?

**Comment by kpalatzky** [comment]
@nightwing 

TL;TR: False alert - It is my fault.

We already load the modules ourselves before and not via ace. Our custom module is also loaded correctly here, but we get an error during initialization.

We have our own SearchBox which inherits from `ace/ext/searchbox`. Here the private property `this.$searchBarKb` is accessed to add a command to the searchbox. It seems that this property was removed/will not be set in `1.17.0` and therefore we get an error during initialization and Ace tries to load the module again by itself. 

Since its a private property i will close this issue.

**Comment by nightwing** [comment]
Even thought it was a private property, the change was a mistake, i have made a pull request to restore the old behavior. Thanks for the report!
