### ISSUE TITLE
Wiki: Keyboard shortcut "Toggle comment"

### ISSUE THREAD

**Issue by halterc** [ajaxorg/ace#5140]
### Describe the issue

Hi,
using a Swiss Keyboard, the "Toggle comment" keyboard shortcut is not "Ctrl-/" as described in the [Wiki](https://github.com/ajaxorg/ace/wiki/Default-Keyboard-Shortcuts) but "Ctrl-§" instead (button with symbols "§" and "°" printed on it).

### Links

https://github.com/ajaxorg/ace/wiki/Default-Keyboard-Shortcuts

**Comment by oykuyilmaz** [comment]
Hi, this shortcuts page is for the default keyboard layout.
