### ISSUE TITLE
Autocomplete: when multiselect is disabled (enableMultiselect = false), applying suggested snippets results in an error

### ISSUE THREAD

**Issue by InspiredGuy** [ajaxorg/ace#5163]
### Describe the bug

When you have multiselect disabled with setting a flag (enableMultiselect = false) and select the snippet suggestion from autocomplete popup, which selects part of the snippet as a result of application, it results in an error.

```
multi_select.js:443 Uncaught TypeError: Cannot read properties of null (reading 'length')
    at Editor.forEachSelection (multi_select.js:443:1)
    at SnippetManager.insertSnippet (snippets.js:504:1)
    at CompletionProvider.insertMatch (autocomplete.js:569:1)
    at Autocomplete.insertMatch (autocomplete.js:259:1)
    at Object.Return [as exec] (autocomplete.js:488:1)
    at command_manager.js:18:1
    at EventEmitter._emit.EventEmitter._dispatchEvent (event_emitter.js:34:1)
    at CommandManager.exec (command_manager.js:45:1)
    at KeyBinding.$callKeyboardHandlers (keybinding.js:87:1)
    at KeyBinding.onCommandKey (keybinding.js:112:1)
```

### Expected Behavior

Autocomplete snippet is applied correctly and the selection is performed according to the snippet.

### Current Behavior

Newline is inserted and the error is thrown.

### Reproduction Steps

1. In Ace config, set enableMultiselect = false.
2. Have an autocomplete suggestion with a snippet, which selects part of the inserted text after applying the snippet.
3. When autocomplete popup is triggered, select the suggestion with a snippet from step 2.

### Ace Version / Browser / OS / Keyboard layout

ace-code v1.19.0

**Comment by nightwing** [comment]
It is not possible to correctly handle snippets without multiselect. Should we select only one instance of a placeholder when multiselect is disabled, or should we enable multiselect when snippet is inserted?

**Comment by nightwing** [comment]
maybe we should just keep the session change listener, because now enableMultiselect = false disables mouse handling and commands work on the first session of the editor, and throw errors on sessions added later.

**Comment by akoreman** [comment]
If I understand your PR correctly, after merging it, `enableMultiselect = true` would only disable the mouseDown handler which allows to manually create multiple cursors while leaving the functionality intact for features which rely on it (like snipper autocomplete). That sounds like a reasonable approach to me.
