### ISSUE TITLE
Objective-C: huge performance issue in Google Chrome on M1 Mac

### ISSUE THREAD

**Issue by alex-swiftify** [ajaxorg/ace#5178]
### Describe the bug

I want to report a bug with Objective-C highlighting theme.

In Google Chrome on M1 Mac (only), the processing speed is [around 7,500 ms](https://take.ms/X8VKO), and the browser completely stalls for that time period.

### Expected Behavior

The browser should remain responsive and the syntax highlighting should take a reasonable amount of time.

### Current Behavior

The browser completely stalls for at least 7.5 seconds.

### Reproduction Steps

- open https://ace.c9.io/tool/mode_creator.html
- select "Objective-C" on the left
- paste the default Objective-C code from https://swiftify.com/converter/code/ to the right window on your website
- press "measure speed"

### Possible Solution

Deleting the following code from mode-objectivec.js decreases the processing time to [~15 ms](https://take.ms/6aJuS):
```
{
    token: "punctuation.section.scope.begin.objc",
    regex: "\\[",
    next: "bracketed_content"
},
```

### Ace Version / Browser / OS / Keyboard layout

ACE 1.3.1 / Google Chrome (!) / macOS Ventura 13.3.1 (a), M1 Mac (!), English (U.S.)

**Comment by InspiredGuy** [comment]
Thank you for the report! Indeed, this is reproducible on Apple Silicon chip in Chrome, even on basic Objective-C document provided on the page (in the selector in top right corner). Firefox and Safari process it fine in ~20 ms on my machine. Seems like a Chrome bug. Unfortunately, the suggested fix breaks syntax highlighting - function names ([Object *function*:...]) are not recognised anymore, most probably since that regex is responsible for finding opening brackets, and content following those opening brackets is highlighted differently compared to out-of-brackets content. 

@nightwing do you think we could modify that `\\[` regex to achieve the same result without the performance issue? existing one is probably the simplest option

**Comment by alex-swiftify** [comment]
@InspiredGuy Thanks for so fast turnaround!

>Indeed, this is reproducible on Apple Silicon chip in Chrome, even on basic Objective-C document provided on the page (in the selector in top right corner). Firefox and Safari process it fine in ~20 ms on my machine. 

This exactly matches my findings. And it definitely happens only on Apple Silicon chip and only in Chrome.
At Swiftify, we discovered this more than 1 year ago and we are using a C/C++ highlighting scheme since then.

Of course, a proper solution would be very much appreciated.

**Comment by nightwing** [comment]
I am testing on M2 mac, and for me deleting the bracketed_content rule did not help. But removing large regexps from https://github.com/ajaxorg/ace/blob/master/src/mode/objectivec_highlight_rules.js#L111-L160 did. I have reported the issue to chrome here https://bugs.chromium.org/p/chromium/issues/detail?id=1447379, and will make a pull request converting these large regular expressions to keywordMapper, if you can confirm that removing them helps.

**Comment by alex-swiftify** [comment]
@nightwing Thanks for the fast turnaround on this!

On my M1 MacBook Pro, removing just the `\\[` regex definitely fixes the slowdown issue.
So, it looks like there's yet another issue on M2.
Thus, I suppose that we need to fix both the `\\[` regex and the large regular expressions that you have found.

If you need any testing done on M1, please ping me here.
I'll check if I have anybody else with M2 on our side to confirm your findings, not sure yet.

Would you follow up on https://bugs.chromium.org/p/chromium/issues/detail?id=1447379 yourself or do you need any help of mine?

**Comment by InspiredGuy** [comment]
> P.S. What's the proper contact to add Swiftify to [this page](https://ace.c9.io/#nav=production)?

@alex-swiftify  I think the fastest way for you would be to create a PR, similar to https://github.com/ajaxorg/ace/pull/5014. There are other examples of logos in the same file (people use links to png, svg logos etc.).

**Comment by alex-swiftify** [comment]
P.S. I just retested on M1 MacBook using the steps from the Summary.

1) With the unmodified Objective-C highlighting code, the processing time is always ~7,500 ms.

2) Removing the large regexps from dehttps://github.com/ajaxorg/ace/blob/master/src/mode/objectivec_highlight_rules.js#L111-L160 
first time decreased the processing time to ~383 ms (couldn't repeat that timing again), but on the subsequent retries, the processing time is [between 15 and 40 ms](https://take.ms/DtMGv).

3) Removing the `\\[` regex decreases the processing time to [either ~4700 ms or 15..25 ms](https://take.ms/NT1Hi).

Thus, I confirm that removing the large regex looks like a better fix.
Also, it looks like this could be the same issues on M1 and M2 rather than different ones.
