### ISSUE TITLE
Add Save As or Create Copy

### ISSUE THREAD

**Issue by TheOldMan2000** [ajaxorg/ace#5199]
### Describe the feature

When trying edit a file using an iPad there is no obvious way to Save As to save the current open file with a new file name. 

The Copy button unhelpfully refuses to save a copy in the same current folder with an alternative file name such as filename-copy.html etc. You must therefore copy to a different folder, rename the file and then move it to the original folder.

### Use Case

When editing an existing file (using the File Manager in Cpanel), it is often best practice to work on a copy or it’s useful to be able to make a copy in the same folder to work on or as a quick backup. 

If something goes wrong you have the original version. Sometimes you want to Save As to make a new file based on the first file before making changes or additions.

### Proposed Solution

Add a feature to Save As and accept a new filename.

Or when saving, if the file already exists create a new copy with the same filename and add a suitable suffix before the file extension, e.g. filename-copy.html

This may be an Cpanel suggestion rather than Ace suggestion: 
Allow files to be copied and/or moved to a different folder as present but make a copy similar to filename-cooy.html or offer to overwrite the existing destination filename.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### ACE version used

v1.22.0

**Comment by nightwing** [comment]
Both of these issues are not related to ace, as ace only provides the editor view component, it does not handle file names or saving in any way.

**Comment by TheOldMan2000** [comment]
Oops, my bad. Sorry for the misunderstanding. 😔
