### ISSUE TITLE
How to ignore some errors instead of disabling this feature

### ISSUE THREAD

**Issue by MrRjx** [ajaxorg/ace#5227]
### Describe the feature

I want to ignore or disabled some error prompt，not config useWorker to disabled this feature

like monaco-editor setDiagnosticsOptions config

### Use Case

for Example: 
![image](https://github.com/ajaxorg/ace/assets/30522502/57185593-fa87-4800-9326-c70d8c6cac95)

I don't need this prompt，I want to hide this prompt

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### ACE version used

ace-builds, verision: 1.20.0

**Comment by mkslanc** [comment]
Hi @MrRjx,
this is possible by using [Ace linters](https://github.com/mkslanc/ace-linters). 
If you want to use eslint as a JavaScript service, you can set your global options as follows:
```javascript
languageProvider.setGlobalOptions("javascript", {
    errorMessagesToIgnore: [
        /Strings\smust\suse\sdoublequote/
    ]
});
```
Alternatively, if you you want to use the TypeScript service for JavaScript files, you can set it like this:
```javascript
languageProvider.setGlobalOptions("typescript", {
    errorCodesToIgnore: [
        "Error code" //Replace this with your specific error code
    ]
});
```

Feel free to reach out if you have any further questions!

**Comment by MrRjx** [comment]
> Hi @MrRjx, this is possible by using [Ace linters](https://github.com/mkslanc/ace-linters). If you want to use eslint as a JavaScript service, you can set your global options as follows:
> 
> ```js
> languageProvider.setGlobalOptions("javascript", {
>     errorMessagesToIgnore: [
>         /Strings\smust\suse\sdoublequote/
>     ]
> });
> ```
> 
> Alternatively, if you you want to use the TypeScript service for JavaScript files, you can set it like this:
> 
> ```js
> languageProvider.setGlobalOptions("typescript", {
>     errorCodesToIgnore: [
>         "Error code" //Replace this with your specific error code
>     ]
> });
> ```
> 
> Feel free to reach out if you have any further questions!

It is not achieveing expected result，I want to config ignore some errors in my code

**Comment by mkslanc** [comment]
@MrRjx It's doing exactly, what you wanted. I created small example in playground to demonstrate it. Please, [look at it](https://mkslanc.github.io/ace-playground/?value=Ly9zYW1wbGVzL3R5cGVzY3JpcHQgbGFuZ3VhZ2Ugc2VydmljZQoKYWNlLnJlcXVpcmUoImFjZS9leHQvbGFuZ3VhZ2VfdG9vbHMiKTsKLy8gRWFzaWVzdCB3YXkgdG8gcnVuIEFDRSBlZGl0b3IgaW4gY29udGFpbmVyIHdpdGggaWQ9ImV4YW1wbGUiCmxldCBlZGl0b3IgPSBhY2UuZWRpdCgiZXhhbXBsZSIsIHsKICAgIHRoZW1lOiAiYWNlL3RoZW1lL3RleHRtYXRlIiwKICAgIG1vZGU6ICJhY2UvbW9kZS90eXBlc2NyaXB0IiwKICAgIHZhbHVlOiAiY29uc29sZS5sb2coJ0hlbGxvIHdvcmxkJyA7Igp9KTsKLy8gZW5hYmxlIGF1dG9jb21wbGV0aW9uIGFuZCBzbmlwcGV0cwplZGl0b3Iuc2V0T3B0aW9ucyh7CiAgICBlbmFibGVCYXNpY0F1dG9jb21wbGV0aW9uOiB0cnVlLAogICAgZW5hYmxlU25pcHBldHM6IHRydWUsCiAgICBlbmFibGVMaXZlQXV0b2NvbXBsZXRpb246IHRydWUKfSk7CgovL2NyZWF0ZSBMYW5ndWFnZSBQcm92aWRlciBmb3IganNvbiBkb2MgZnJvbSBhY2UgbGludGVycwoKbGV0IHByb3ZpZGVyID0gTGFuZ3VhZ2VQcm92aWRlci5mcm9tQ2RuKCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2FjZS1saW50ZXJzL2J1aWxkIik7CgovLyBSZWdpc3RlciB0aGUgZWRpdG9yIHdpdGggdGhlIGxhbmd1YWdlIHByb3ZpZGVyCnByb3ZpZGVyLnJlZ2lzdGVyRWRpdG9yKGVkaXRvcik7CgpsZXQgc3dpdGNoZXIgPSBmYWxzZTsKCnNldEludGVydmFsKCgpID0%2BIHsKICAgIHByb3ZpZGVyLnNldEdsb2JhbE9wdGlvbnMoInR5cGVzY3JpcHQiLCB7CiAgICAgICAgZXJyb3JDb2Rlc1RvSWdub3JlOiBbCiAgICAgICAgICAgIHN3aXRjaGVyID8gIjEwMDUiIDogIiIgLy9SZXBsYWNlIHRoaXMgd2l0aCB5b3VyIHNwZWNpZmljIGVycm9yIGNvZGUKICAgICAgICBdCiAgICB9KTsKICAgIAogICAgc3dpdGNoZXIgPSAhc3dpdGNoZXI7Cn0sIDEwMDApOwoKXDBcMDwhLS0gbG9hZCBhY2UgbGFuZ3VhZ2UgdG9vbHMgLS0%2BCjxzY3JpcHQgc3JjPSJodHRwczovL2NkbmpzLmNsb3VkZmxhcmUuY29tL2FqYXgvbGlicy9hY2UvMS4xNy4wL2V4dC1sYW5ndWFnZV90b29scy5taW4uanMiPjwvc2NyaXB0Pgo8IS0tIGxvYWQgYWNlIGxpbnRlcnMgLS0%2BCjxzY3JpcHQgc3JjPSJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2FjZS1saW50ZXJzIj48L3NjcmlwdD4KPGRpdiBpZD0nZXhhbXBsZScgc3R5bGU9ImhlaWdodDogMTAwJSI%2BPC9kaXY%2BCg%3D%3D#typescript-language-service). It's switching between two states - ignoring 1005 error and showing error

**Comment by MrRjx** [comment]
> @MrRjx It's doing exactly, what you wanted. I created small example in playground to demonstrate it. Please, [look at it](https://mkslanc.github.io/ace-playground/?value=Ly9zYW1wbGVzL3R5cGVzY3JpcHQgbGFuZ3VhZ2Ugc2VydmljZQoKYWNlLnJlcXVpcmUoImFjZS9leHQvbGFuZ3VhZ2VfdG9vbHMiKTsKLy8gRWFzaWVzdCB3YXkgdG8gcnVuIEFDRSBlZGl0b3IgaW4gY29udGFpbmVyIHdpdGggaWQ9ImV4YW1wbGUiCmxldCBlZGl0b3IgPSBhY2UuZWRpdCgiZXhhbXBsZSIsIHsKICAgIHRoZW1lOiAiYWNlL3RoZW1lL3RleHRtYXRlIiwKICAgIG1vZGU6ICJhY2UvbW9kZS90eXBlc2NyaXB0IiwKICAgIHZhbHVlOiAiY29uc29sZS5sb2coJ0hlbGxvIHdvcmxkJyA7Igp9KTsKLy8gZW5hYmxlIGF1dG9jb21wbGV0aW9uIGFuZCBzbmlwcGV0cwplZGl0b3Iuc2V0T3B0aW9ucyh7CiAgICBlbmFibGVCYXNpY0F1dG9jb21wbGV0aW9uOiB0cnVlLAogICAgZW5hYmxlU25pcHBldHM6IHRydWUsCiAgICBlbmFibGVMaXZlQXV0b2NvbXBsZXRpb246IHRydWUKfSk7CgovL2NyZWF0ZSBMYW5ndWFnZSBQcm92aWRlciBmb3IganNvbiBkb2MgZnJvbSBhY2UgbGludGVycwoKbGV0IHByb3ZpZGVyID0gTGFuZ3VhZ2VQcm92aWRlci5mcm9tQ2RuKCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2FjZS1saW50ZXJzL2J1aWxkIik7CgovLyBSZWdpc3RlciB0aGUgZWRpdG9yIHdpdGggdGhlIGxhbmd1YWdlIHByb3ZpZGVyCnByb3ZpZGVyLnJlZ2lzdGVyRWRpdG9yKGVkaXRvcik7CgpsZXQgc3dpdGNoZXIgPSBmYWxzZTsKCnNldEludGVydmFsKCgpID0%2BIHsKICAgIHByb3ZpZGVyLnNldEdsb2JhbE9wdGlvbnMoInR5cGVzY3JpcHQiLCB7CiAgICAgICAgZXJyb3JDb2Rlc1RvSWdub3JlOiBbCiAgICAgICAgICAgIHN3aXRjaGVyID8gIjEwMDUiIDogIiIgLy9SZXBsYWNlIHRoaXMgd2l0aCB5b3VyIHNwZWNpZmljIGVycm9yIGNvZGUKICAgICAgICBdCiAgICB9KTsKICAgIAogICAgc3dpdGNoZXIgPSAhc3dpdGNoZXI7Cn0sIDEwMDApOwoKXDBcMDwhLS0gbG9hZCBhY2UgbGFuZ3VhZ2UgdG9vbHMgLS0%2BCjxzY3JpcHQgc3JjPSJodHRwczovL2NkbmpzLmNsb3VkZmxhcmUuY29tL2FqYXgvbGlicy9hY2UvMS4xNy4wL2V4dC1sYW5ndWFnZV90b29scy5taW4uanMiPjwvc2NyaXB0Pgo8IS0tIGxvYWQgYWNlIGxpbnRlcnMgLS0%2BCjxzY3JpcHQgc3JjPSJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2FjZS1saW50ZXJzIj48L3NjcmlwdD4KPGRpdiBpZD0nZXhhbXBsZScgc3R5bGU9ImhlaWdodDogMTAwJSI%2BPC9kaXY%2BCg%3D%3D#typescript-language-service). It's switching between two states - ignoring 1005 error and showing error

I tried use it，but it not work.
![image](https://github.com/ajaxorg/ace/assets/30522502/9c5dcee0-50fc-44a3-9277-631b6729d6da)
![image](https://github.com/ajaxorg/ace/assets/30522502/32fc4478-82fd-49fa-a162-57c1ff7e05b0)
I don't know if my code not correctly

**Comment by mkslanc** [comment]
From this small snippet, I see you haven't registered editor `provider.registerEditor(editor);`. But maybe I wrong, could you create some test code anywhere and provide link to it? I could take a look

**Comment by MrRjx** [comment]
It‘s my wrong,I add register code, it’s ok；I have another problem：
editor mode is "ace/mode/javascript", I was write an object，I thought this is correct syntax，why it report these errors?
![image](https://github.com/ajaxorg/ace/assets/30522502/9681ca62-d841-4fc7-98af-be0cbca0fb7f)


> From this small snippet, I see you haven't registered editor `provider.registerEditor(editor);`. But maybe I wrong, could you create some test code anywhere and provide link to it? I could take a look

**Comment by MrRjx** [comment]
> From this small snippet, I see you haven't registered editor `provider.registerEditor(editor);`. But maybe I wrong, could you create some test code anywhere and provide link to it? I could take a look

It‘s my wrong,I add registerEditor code, it became useful. I have other issues want to ask you：
1、editor mode is "ace/mode/javascript", I was write an object，I thought this is correct syntax，why it report these errors?
![image](https://github.com/ajaxorg/ace/assets/30522502/c31e7dbb-c10d-4089-9a70-442c42147c84)
![image](https://github.com/ajaxorg/ace/assets/30522502/09db7a5e-3753-44bd-9a2b-1eb9ad6644c4)

2、I install ace-linters with npm，I don't want to use cdn，what can I replace this line code
![image](https://github.com/ajaxorg/ace/assets/30522502/541ebc83-164e-4ca9-a9fa-daf3b1a10bdb)

**Comment by mkslanc** [comment]
1. It's not correct syntax itself, you could use it like
```javascript
var a = {
	b: 123,
	c: 456
};
``` 
or 
```javascript
const outerObject = {
    a: {
        b: 123,
        c: 456
    }
};
```
2. For second one, please,  look to [readme section](https://github.com/mkslanc/ace-linters#ace-linters-ace-language-client). First example is describing exactly what you need, just add `setGlobalOptions` with errors you wanna exclude

**Comment by MrRjx** [comment]
> 

thank you very much
