### ISSUE TITLE
Acode: ANSI file with german special-characters is opened as UTF8

### ISSUE THREAD

**Issue by Micha-he** [ajaxorg/ace#5230]
### Describe the bug

As deadlyjack has requested, I'll forward my reported bug to this project:
[https://github.com/deadlyjack/Acode/issues/129#issuecomment-1250164041](url)

A local (on Android-smartphone) ANSI file with german special-characters (°äöüÄÖÜß) is always opened as UTF8.
If I switch manually to ANSI-Windows1252 encoding, additional characters are inserted (on each encoding-change).

According to deadlyjack, the error should come from the ace-component, that he's used in his Acode-editor.

### Expected Behavior

Open ANSI-files in ANSI-Mode.

### Current Behavior

ANSI-files are open in UTF-8.

### Reproduction Steps

Open any local ANSI-file with german umlauts on Android-Smartphone with Acode-editor.

### Ace Version / Browser / OS / Keyboard layout

Acode-Editor (any version) on Android

**Comment by Micha-he** [comment]
You can also reproduce the error, if you execute ('run code snippet') at the answer on this [page:](https://stackoverflow.com/questions/59004560/how-can-i-open-a-file-into-ace-text-editor)

Load a simple text-file with german umlauts in ANSI-format. The line-break-format is seemingly uninteresting.

**Comment by nightwing** [comment]
Ace does not handle file encoding in any way. It only displays javascript strings as everything else in a browser. To handle ANSI encoded files you need to use another library to convert these into utf and then convert back when saving
