### ISSUE TITLE
ace: searching whole words seems not to respect non-ASCII word boundaries

### ISSUE THREAD

**Issue by AnthonyMikh** [ajaxorg/ace#5232]
### Describe the bug

Using search functionality to look up whole words still finds query _inside_ words if query consists of cyrrilic letters (and presumably other non-ASCII characters as well).

### Expected Behavior

Given the following text (all letters are cyrrilic):

```
Т
ТТ
ТТТ
РЕДАКТОР
```

searching for whole word `Т` (U+0422 Cyrillic Capital Letter Te) correctly highlights only the first word in text, and searching for `ТТ` (two U+0422) correctly highlights only the second word.

### Current Behavior

Editor highlights every inclusion of `Т` and two inclusions of `ТТ`:

![изображение](https://github.com/ajaxorg/ace/assets/19252795/c7b301c0-9d72-4025-abd4-1a813075a510)

![изображение](https://github.com/ajaxorg/ace/assets/19252795/edfba90a-dea6-4f10-aba5-a7cde91e89e0)

Reproduced in latest versions of Firefox and Chrome.

### Reproduction Steps

1. Paste this text into editor:

```
Т
ТТ
ТТТ
РЕДАКТОР
```

2. Select first word/Select second word.
3. Hit `Ctrl+F`.
4. In search popup click `\b` icon ("Whole Word Search").

### Ace Version / Browser / OS / Keyboard layout

latest ace (27.06.23, I presume?)

**Comment by akoreman** [comment]
thanks for reporting the issue, the word boundary is checked [here](https://github.com/ajaxorg/ace/blob/master/src/search.js#L361) and does indeed not check for non-ASCII characters. We might be able to improve this by using the Javascript unicode aware regex.

**Comment by akoreman** [comment]
Will be included in the next ace release (1.24.0)
