### ISSUE TITLE
Prevent automatic full-stop insertion on double space on Mac OS

### ISSUE THREAD

**Issue by priand** [ajaxorg/ace#5240]
### Describe the bug

Pressing 'space' multiple times inserts a dot '.' in the text while the mode is sql.

### Expected Behavior

The '.' should not generated, it is not markdown.

### Current Behavior

n/a

### Reproduction Steps

Go to the kitchen sink, select SQL as the document. Put the caret right after `WHERE` and quickly press the space bar 2 times. Instead of inserting 2 spaces, it generates a dot  and a space `. ` like `WHERE.  group_name = 'salesman'`. If you type the 2 spaces with delay in between, then they are inserted properly.

### Ace Version / Browser / OS / Keyboard layout

Chrome [Version 114.0.5735.198 (Official Build) (x86_64)], Edge & Safari but not on Firefox. Reproduced on a Mac intel, in incognito mode (no extension enabled)

**Comment by akoreman** [comment]
hey, thanks for opening the issue. Are you sure it's not the Mac OS option to insert a period on a double space that you're seeing? That option is (was for me at least) enabled by default, if I disable it I cannot reproduce the issue.

**Comment by priand** [comment]
Interesting, thanks for the info. It worked when I disabled the option in the system settings.
That being said, it feels like it is the wrong behavior for a code editor. At least local apps (Sublime, Eclipse, VS Code...) don't do it. This is also true for some web editors, like the code mirror example, JS Fiddle,... while stackblitz or Github explorer have the issue (vs code based).
Do you know if there is a way to get it disabled? And then shouldn't it be the default for the component?

**Comment by akoreman** [comment]
I'm not sure whether this is something we can control, I'd need to look a bit deeper for that. In my quick check, It seems that both Ace and Monaco (the editor powering VS code) have this behavior where CodeMirror does not. The difference might be due to the underlying tech used, Ace and Monaco appear to the browser like a 'normal' textarea, which might result in the OS/browser trying to 'help' by inserting the full-stop.

**Comment by akoreman** [comment]
Looked around and it seems there is no way to opt-out HTML textarea's from this behavior (e.g. [here](https://stackoverflow.com/questions/44962941/html-text-input-element-disable-mac-double-space-to-insert-period) and [here](https://stackoverflow.com/questions/44962941/html-text-input-element-disable-mac-double-space-to-insert-period)). We can look into whether there is a good way to prevent this `<space><space>` -> `.<space>` behavior but that's more a feature request than a bug.

**Comment by priandsf** [comment]
Thank you for looking at the issue. I understand that this might not be an easy fix. This is unfortunate that they add features to the OS to help people but they are actually annoyances.
