### ISSUE TITLE
ace: spacebar duplicates the previous word (on Android)

### ISSUE THREAD

**Issue by good2see** [ajaxorg/ace#5242]
### Describe the bug

On Android device, spacebar is duplicating the previous word.

![Screenshot_20230706-161941](https://github.com/ajaxorg/ace/assets/71662079/148dca91-90ae-4791-9cf8-e8d2c80926fa)

![Screenshot_20230706_151453](https://github.com/ajaxorg/ace/assets/71662079/e6911956-5daa-4aa0-8c0b-175691593b00)

### Expected Behavior

When I click the spacebar, I just want a single space

### Current Behavior

When I click the spacebar, It adds a duplicate of previous word

### Reproduction Steps

An android device, nothing else

### Ace Version / Browser / OS / Keyboard layout

Latest version/Kiwi-Firefox/Android/Q Turkish-Logitech

**Comment by deadlyjack** [comment]
Because of autocorrect I guess. Temporarily you can disable autocorrect from keyboard settings to fix. Or if you are creating android app using ace, you set IME option to visible password to fix it permanently.

Most soft keyboard apps on Android ignore autocorrect, autocomplete option of textarea.

**Comment by good2see** [comment]
No, it is not related to autocorrect. It's already disabled.

**Comment by akoreman** [comment]
Thanks for reporting the issue. I tried to reproduce it on my Android device (Pixel 6A, Android 13, Swiftkey) but I don't see the reported issue (both with autocorrect on and off). Could you take a look at the text input debugger on the [kitchen-sink](https://ace.c9.io/build/kitchen-sink.html) (second to last option in the sidebar) and see which event is causing the insertion of the unwanted word?

**Comment by good2see** [comment]
On kiwi browser (with Swiftkey without autocorrection):

I typed "test":


{ _: "keydown", range: [0,0], value: "\n\n", key: { code: "", key:
"Unidentified", keyCode: 229}},
{ _: "input", data: "t", inputType: "insertText", range: [1,1], value:
"t\n\n"},
{ _: "keyup", range: [1,1], value: "t\n\n", key: { code: "", key:
"Unidentified", keyCode: 229}},
{ _: "keydown", range: [1,1], value: "t\n\n", key: { code: "", key:
"Unidentified", keyCode: 229}},
{ _: "input", data: "e", inputType: "insertText", range: [2,2], value:
"te\n\n"},
{ _: "keyup", range: [2,2], value: "te\n\n", key: { code: "", key:
"Unidentified", keyCode: 229}},
{ _: "keydown", range: [2,2], value: "te\n\n", key: { code: "", key:
"Unidentified", keyCode: 229}},
{ _: "input", data: "s", inputType: "insertText", range: [3,3], value:
"tes\n\n"},
{ _: "keyup", range: [3,3], value: "tes\n\n", key: { code: "", key:
"Unidentified", keyCode: 229}},
{ _: "keydown", range: [3,3], value: "tes\n\n", key: { code: "", key:
"Unidentified", keyCode: 229}},
{ _: "input", data: "t", inputType: "insertText", range: [4,4], value:
"test\n\n"},
{ _: "keyup", range: [4,4], value: "test\n\n", key: { code: "", key:
"Unidentified", keyCode: 229}},
{ _: "compositionstart", data: "", range: [4,4], value: "test\n\n"},
{ _: "keydown", range: [0,0], value: "", key: { code: "", key:
"Unidentified", keyCode: 229}},
{ _: "compositionstart", data: "", range: [0,0], value: ""},
{ _: "compositionupdate", data: "test", range: [0,0], value: ""},
{ _: "input", data: "test", inputType: "insertCompositionText", range:
[4,4], value: "test"},
{ _: "keyup", range: [4,4], value: "test", key: { code: "", key:
"Unidentified", keyCode: 229}},
{ _: "compositionend", data: "test", range: [4,4], value: "test"},
{ _: "keydown", range: [4,4], value: "test", key: { code: "", key:
"Unidentified", keyCode: 229}},
{ _: "input", data: " ", inputType: "insertText", range: [5,5], value:
"test "},
{ _: "keyup", range: [5,5], value: "test ", key: { code: "", key:
"Unidentified", keyCode: 229}},
{ _: "select", range: [9,9], value: "testtest \n\n"},

**Comment by deadlyjack** [comment]
Seems like sent by the keyboard. Which keyboard you are using?
