### ISSUE TITLE
Add project Web Tools to the list of projects using Ace on its website

### ISSUE THREAD

**Issue by justnixx** [ajaxorg/ace#5247]
### Project name

Web Tools

### Project link

https://nixx.dev

### Logo link

https://nixx.dev/static/hotlink-ok/logo-alt.png

### Additional information

Thank you. 🙏 

### Acknowledgements

- [X] I may be able to implement this request.

**Comment by akoreman** [comment]
I'm happy to add the logo to the website but when fetching the icon I get a `403 Forbidden` response, could you look into why that could be.

**Comment by justnixx** [comment]
Hello @akoreman , please use the following link: https://nixx.dev/static/hotlink-ok/logo-alt.png. 
I have also made changes to my initial comment.

**Comment by justnixx** [comment]
It's fine. @akoreman 
Thanks! 🙏
