### ISSUE TITLE
unqualified reference to `window` breaks usage in workers

### ISSUE THREAD

**Issue by AprilArcus** [ajaxorg/ace#5252]
### Describe the bug

I am building a Worker for my team's custom language, and I want to obtain ace modules from `ace-builds` inside a Worker like so:

```
import * as ace from 'ace-builds';
const { Mirror } = ace.require('ace/worker/mirror');
```

I understand that much of Ace only works on the UI thread, but some components are useful inside workers and it is preferable to rely on `ace-builds` a single source of truth rather than acquiring CommonJS sources from `ace-code`. In addition to de-duplicating shared code, this would prevent the version of `ace-builds` and `ace-code` from going out of sync as other developers take over this project.

However, the unqualified references to `window` as a free variable in the `exportAce` function in [`Makefile.dryice.js` ll. 792-798](https://github.com/ajaxorg/ace/blob/v1.23.3/Makefile.dryice.js#L792-L798) crashes the worker at module init time.

Notably, [`ace/build_support/mini_require.js` ll. 41-42](https://github.com/ajaxorg/ace/blob/v1.23.3/build_support/mini_require.js#L41-L42) and [`ace/lib/ace/loader_build.js` ll. 14-16](https://github.com/ajaxorg/ace/blob/v1.23.3/lib/ace/loader_build.js#L14-L16) do not suffer from this same problem, obtaining a reference to `global` in a worker-safe manner.

### Expected Behavior

`import * as ace from 'ace-builds'` and calling `ace.require()` should function correctly inside a Worker.

### Current Behavior

`import * as ace from 'ace-builds'` and calling `ace.require()` crashes with a `ReferenceError` at module load time when `window` is referenced as a free variable.

### Reproduction Steps

please @ me if you really need this :)

### Possible Solution

Replace references to `window` in `Makefile.dryice.js` with

```
(function () { return this || typeof window != "undefined" && window; })
```

to match `build_support/mini_require.js` and `lib/ace/loader_build.js`, or replace all three with [`globalThis`](https://github.com/tc39/proposal-global).

### Ace Version / Browser / OS / Keyboard layout

1.8.1 / Chrome / Linux / QWERTY

**Comment by akoreman** [comment]
Will be included in the next ace release (1.24.0)
