### ISSUE TITLE
Long tooltip

### ISSUE THREAD

**Issue by Anusuryadevi** [ajaxorg/ace#5267]
### Describe the bug

Hello,
  We are using long text in ace editor tooltip like below. Is there way to add a scroll bar here? because we are missing some text.  

![image](https://github.com/ajaxorg/ace/assets/17896883/248661c3-4830-4888-bf92-633674ee1895)

### Expected Behavior

![image](https://github.com/ajaxorg/ace/assets/17896883/248661c3-4830-4888-bf92-633674ee1895)
Looking for some scrollbar in the tooltip

### Current Behavior

![image](https://github.com/ajaxorg/ace/assets/17896883/248661c3-4830-4888-bf92-633674ee1895)
Missing some text.

### Reproduction Steps

Add a long text with new line (\n) in the tooltip and check.

### Possible Solution

Is there way to add a scroll bar here?

### Ace Version / Browser / OS / Keyboard layout

v1.4.13

**Comment by whazor** [comment]
Hi, can you please check whether the issue is reproducible on the latest version of Ace v1.23.4? We did some changes to the tooltips.

**Comment by Anusuryadevi** [comment]
Hi @whazor ,
I have verified it, same issue exist in v1.23.4 as well

Regards,
Selva

**Comment by akoreman** [comment]
Currently, we don't set the `max-height` or `overflow` CSS properties to tooltips, if you set a sensible number to `max-height` and `overflow: scroll` to the `ace_tooltip` class (or your own tooltip class if you set a different class to these tooltips) it allows you to have a scroll bar in the tooltip.

It might make sense for us to see whether it might make sense to an overflow behaviour by default for these tooltips.
