### ISSUE TITLE
Regular expression for Powersholl mode is not working propperly.

### ISSUE THREAD

**Issue by cmmv91** [ajaxorg/ace#5273]
Regular expression for `/src-noconflict/mode-powershell` is not working propperly. Powershell editors should be able to recognize '\\' as a character not as a scape char, so windows paths can be typed without the editor showing an error.

**Comment by andredcoliveira** [comment]
Thanks for reporting this issue!

I've approved & merged #5336 ffrom @mkslanc. Issue is no longer present with the new commit (see http://raw.githack.com/ajaxorg/ace/747317a6406f8abdde9df533dcb7a20221dc9412/kitchen-sink.html) and you should be able to consume the fix on a new Ace release.
