### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'splice')

### ISSUE THREAD

**Issue by hariharan605** [ajaxorg/ace#5276]
### Describe the bug

Using ace-build NPM package - Version 1.16.0

Use case 1 :

```
Uncaught TypeError: Cannot read properties of null (reading 'splice')
    at d.updateFoldWidgets (ace.js:1:147561)
    at r._signal (ace.js:1:12681)
    at d.onChange (ace.js:1:157237)
    at r._signal (ace.js:1:12681)
    at a.applyDelta (ace.js:1:123862)
    at a.insertMergedLines (ace.js:1:122174)
    at a.insert (ace.js:1:121014)
    at d.insert (ace.js:1:165721)
    at S.insert (ace.js:1:232021)
    at Object.exec (ace.js:1:205853)   
```

Whenever I try to delete a whole document and enter a new character, it gets printed twice and the above error displayed in console.

Use case 2 : 

```
Uncaught TypeError: Cannot read properties of null (reading 'splice')
    at e.updateFoldWidgets (ace.js:1:159940)
    at r._signal (ace.js:1:12681)
    at e.onChange (ace.js:1:169827)
    at r._signal (ace.js:1:12681)
    at e.applyDelta (ace.js:1:135373)
    at e.remove (ace.js:1:133834)
    at e.remove (ace.js:1:178455)
    at Object.exec (ace.js:1:215613)
    at ace.js:1:203425
    at r._emit.r._dispatchEvent (ace.js:1:12555)
```

Whenever I try to cut the code, the last two lines of the code gets copied to clipboard whereas other lines were gone and the above error displayed in console.

A help would be seriously appreciable as I struck in this for weeks and couldn't figure out what went wrong here.

    
    

### Expected Behavior

Use case 1 : 
No double character printing should happen.

Use case 2 : 
Cut operation should happen flawlessly.

### Current Behavior

Use case 1 : 
Whenever I try to delete a whole document and enter a new character, it gets printed twice and the above error displayed in console.

Use case 2 : 
Whenever I try to cut the code, the last two lines of the code gets copied to clipboard whereas other lines were gone and the above error displayed in console.

### Reproduction Steps

Use case 1 : 
Whenever I try to delete a whole document and enter a new character, it gets printed twice and the above error displayed in console.

Use case 2 : 
Whenever I try to cut the code, the last two lines of the code gets copied to clipboard whereas other lines were gone and the above error displayed in console.

### Ace Version / Browser / OS / Keyboard layout

ace : 1.16.0

**Comment by akoreman** [comment]
Thanks for reaching out, I'm trying to reproduce the issue. In the video I'm:

- selecting the entire file
- deleting it
- typing a new character

in the javascript mode. I don't the the reported issue here. Are there steps that reproduce the issue for you on the [kitchen-sink](https://ace.c9.io/build/kitchen-sink.html)?

https://github.com/ajaxorg/ace/assets/34573235/ab341cc6-b974-4d45-82ab-924a07ca9825
