### ISSUE TITLE
Add project (Acode) to the list of projects using Ace on its website

### ISSUE THREAD

**Issue by deadlyjack** [ajaxorg/ace#5290]
### Project name

Acode

### Project link

https://acode.foxdebug.com

### Logo link

https://acode.foxdebug.com/logo.svg

### Additional information

Acode is a open source code editor for android with over 1 million downloads. It utilizes Ace editors and provide user a experience of better and easy coding on mobile devices.

### Acknowledgements

- [X] I may be able to implement this request.

**Comment by InspiredGuy** [comment]
https://github.com/ajaxorg/ace/pull/5291 which adds Acode to the list of projects was merged, and will be available on the website with the next release.
