### ISSUE TITLE
Add project (project name) to the list of projects using Ace on its website

### ISSUE THREAD

**Issue by mikwakx** [ajaxorg/ace#5297]
### Project name

Htm color

### Project link

Htmcolor.com

### Logo link

https://htmcolor.com/wp-content/uploads/2023/08/1692613065983.png

### Acknowledgements

- [ ] I may be able to implement this request.

**Comment by rj2704** [comment]
Hi, I can fix this issue. You can assign it to me.

**Comment by InspiredGuy** [comment]
Thanks @rj2704 , to help you out there are examples of PRs that fixed similar issues (added projects to the website):
- https://github.com/ajaxorg/ace/pull/5222/files
- https://github.com/ajaxorg/ace/pull/5291/files
