### ISSUE TITLE
enable addMarker: range argument to be a simple js object rather than a 'Range' object

### ISSUE THREAD

**Issue by dhakehurst** [ajaxorg/ace#5310]
### Describe the feature

optionally allow the range argument to be a simple js object containing the constructor arguments.

### Use Case

I want to create Markers (or Range objects) without having to use the Range constructor (function)

My specific use case is w.r.t. a lib that add markers, but I don't want to have an explicit dependency on
Ace (or specific version of ace).

I can use known interfaces (as the ace editor on which I'm operating is passed in),
but currently the dependency is for creating Range objects

### Proposed Solution

allow the range argument to be 'any',
if it is a Range object..use it,
if not, try to construct a Range object from the properties of the passed in object

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### ACE version used

any recent

**Comment by whazor** [comment]
Thank you for your feedback. I agree this would simplify implementation of markers for integrators. 

However, properly supporting range as JS object in all the APIs from Ace would be a big addition. Only adding it to `addMarker` would make our public API inconsistent. I am of the opinion that the cost of complexity and maintainability for implementing range as JS object properly everywhere in Ace outweighs the benefit. In particular as the Ace API is not fully tested.

Therefore, I am closing the issue for now and leaving the issue open for discussion.

**Comment by dhakehurst** [comment]
disappointed,
hope this changes in the future.
I'll have to use a workaround !

**Comment by nightwing** [comment]
The support for passing plain js object already exists in other places like setSelection or removeText so it is already quite inconsistent. But maybe as a compromise we can add session.createRange or even expose the constructor as session.Range?
