### ISSUE TITLE
add changeAnnotation event to types of EditSession

### ISSUE THREAD

**Issue by snaptopixel** [ajaxorg/ace#5319]
### Describe the bug

`changeAnnotation` event is not listed in the types for `session.on` inside `ace.d.ts`

### Expected Behavior

When using typescript and writing `editor.session.on('changeAnnotation', fn)` not to get a typescript error

### Current Behavior

The following TypeError is raised
```
No overload matches this call.
  The last overload gave the following error.
    Argument of type '"changeAnnotation"' is not assignable to parameter of type '"changeTabSize"'.ts(2769)
```

### Reproduction Steps

When using typescript and write `editor.session.on('changeAnnotation', fn)` to get a typescript error

### Possible Solution

The types need to be updated to match all supported event names

### Ace Version / Browser / OS / Keyboard layout

TypeScript in VSCode

**Comment by marinsokol5** [comment]
Hey!
Thanks for the feedback. Indeed you are right that we are missing this type in `ace.d.ts`.  It's sort of a never ending battle for us to keep this file in sync with the actual implementation. 
We are right now working on auto-generating it based on JSDoc: https://github.com/ajaxorg/ace/pull/5318, in which case the current `ace.d.ts` will just be thrown away.

So I am hesitant to make a change for it right now, but let's keep this issue open in case we don't merge https://github.com/ajaxorg/ace/pull/5318 

I also don't really know yet how that implementation is going to pick up [events](https://github.com/ajaxorg/ace/blob/master/src/edit_session.js#L15-L95) but I am curious to try it.
