### ISSUE TITLE
Ace does not handle modern java features

### ISSUE THREAD

**Issue by bowbahdoe** [ajaxorg/ace#5338]
### Describe the bug

<img width="418" alt="image" src="https://github.com/ajaxorg/ace/assets/5004262/a6d46afb-beef-4653-9301-db9fde0b673a">

vs.

<img width="730" alt="image" src="https://github.com/ajaxorg/ace/assets/5004262/68df0965-8d02-4130-9d72-2ee30cf4b5ab">

### Expected Behavior

I'd expect things like `record` and multi-line string literals to be highlighted

### Current Behavior

`record` is not hightlighted and multi-line string literals are not recognized. Other things like patterns in switch statements or string templates might have similar issues

### Reproduction Steps

Make an editor in java mode, paste in newer code

### Ace Version / Browser / OS / Keyboard layout

1.2.8

**Comment by andredcoliveira** [comment]
This is likely a matter of updating https://github.com/ajaxorg/ace/blob/master/src/mode/java_highlight_rules.js

**Comment by bowbahdoe** [comment]
@andredcoliveira Not really... adding the `record` keyword would be about the cap of my ability to confidently do.

**Comment by bowbahdoe** [comment]
I made a PR for that easy stuff
