### ISSUE TITLE
Add project Next2D to the list of projects using Ace on its website

### ISSUE THREAD

**Issue by ienaga** [ajaxorg/ace#5347]
### Project name

Next2D

### Project link

https://tool.next2d.app

### Logo link

https://tool.next2d.app/assets/img/logo.svg

### Additional information

It is an authoring tool that runs on a Web browser. With its intuitive interface and rich functionality, it is easy for anyone to use. It allows users to create high-quality, engaging content by combining a variety of media formats, including text, images, audio, and video.

### Acknowledgements

- [x] I may be able to implement this request.

**Comment by oykuyilmaz** [comment]
Hey, @ienaga! We see you've ticked the "I may be able to implement this request.". If that's the case, here are a couple of examples on how to do this:

- https://github.com/ajaxorg/ace/pull/5014
- https://github.com/ajaxorg/ace/pull/5222

Feel free to open a PR 🙂

**Comment by ienaga** [comment]
@oykuyilmaz 

Thank you very much!
We have sent you a PR.

https://github.com/ajaxorg/ace/pull/5350

**Comment by InspiredGuy** [comment]
https://github.com/ajaxorg/ace/pull/5350 was merged, which resolves this issue. Thanks for handling it!
