### ISSUE TITLE
Modelist: A wrong mode detection

### ISSUE THREAD

**Issue by yy-en40p** [ajaxorg/ace#5357]
### Describe the bug

getModeForPath returns 'ace/mode/django' when an HTML file path as an argument is passed.
<img width="260" alt="getModeForPath" src="https://github.com/ajaxorg/ace/assets/82857709/69ceda4b-ba50-4d0b-96fb-f7b43f30c7f5">

### Expected Behavior

getModeForPath returns 'ace/mode/html' when an HTML file path as an argument is passed.

### Current Behavior

Django mode is applied to an HTML file.

### Reproduction Steps

```js
let modelist = ace.require('ace/ext/modelist');
let mode = modelist.getModeForPath('index.html').mode;
```

Check the value "mode".

### Possible Solution

This bug is a side effect by the commit "c4bae84". 

<img width="450" alt="chrome_Wrs18fmdCh" src="https://github.com/ajaxorg/ace/assets/82857709/1454d7bc-a05f-4e1d-bf01-2c297d818244">

Put back `Django: ["html"]` of `supportModes` in src/ext/modelist.js to the last, which is after `Zeek: ["zeek|bro"]`.

### Additional Information/Context

getModeForPath hits a mode by regex. The order of HTML should be before Django in `supportModes`.

### Ace Version / Browser / OS / Keyboard layout

ace-builds 1.30.0

**Comment by whazor** [comment]
This bug has been fixed by pr #5358 which will be release next version.
