### ISSUE TITLE
Theme: placeholder is not shown with theme monokai

### ISSUE THREAD

**Issue by CarterLi** [ajaxorg/ace#5361]
### Describe the bug

```js
var editor = ace.edit("editor");
editor.setOption("placeholder", "This text should be shown");
editor.setTheme("ace/theme/monokai");
```

### Expected Behavior

`This text should be shown` should be shown as the placeholder

### Current Behavior

No text is shown

### Reproduction Steps

https://codepen.io/CarterLi/pen/KKJPvQL

### Possible Solution

![WX20231020-143015@2x](https://github.com/ajaxorg/ace/assets/6134068/5865b014-bf1b-4be1-808f-1f7eeadf8933)

`.ace_active-line` covers `.ace_placehoder` with a non-transparent background.

<img width="1308" alt="image" src="https://github.com/ajaxorg/ace/assets/6134068/a31a767e-7fdd-439e-a7fb-96fc5d93961e">

Changing the background of `.ace_active-line` to some color with alpha channel fix this issue.

https://github.com/ajaxorg/ace/blob/c8379beca8988df59eb766f447a9ad461e6bc2d0/src/theme/monokai-css.js#L37-L39

### Additional Information/Context

This affects `monokai`, `github` and maybe other themes too, but not `chrome`.

### Ace Version / Browser / OS / Keyboard layout

1.30.0

**Comment by whazor** [comment]
I verified that this is indeed a problem for multiple dark themes like `tomorrow_night`, `terminal`, but not `twilight`.

Maybe the fix might be giving the `.ace_placeholder { z-index: 1; position: relative; }` like the text layer.

**Comment by CarterLi** [comment]
I suggest we should change the `background-color` of `ace_active-line`, instead of making `ace_placeholder` a different layer.

**Comment by CarterLi** [comment]
> In that case, every theme with the problem would need to be changed.

That's better than making `z-index` more complex

**Comment by InspiredGuy** [comment]
https://github.com/ajaxorg/ace/pull/5612 was merged, will be available in next release
