### ISSUE TITLE
HoverTooltip: Hover Tooltip does not show on first time hover if it is close to the right viewport border

### ISSUE THREAD

**Issue by oykuyilmaz** [ajaxorg/ace#5362]
### Describe the bug

A race condition. 

If I hover onto a token which is too close to the viewport border on the right (haven't tested the other cases), its hover tooltip doesn't show on first time hovering. See the pointer blink and the wrong position of the tooltip too in the video.

https://github.com/ajaxorg/ace/assets/12100596/f2d0ab70-1ea5-40aa-8e1f-a1fe34e647b9

### Expected Behavior

Hover tooltip should show in the correct position.

### Current Behavior

Hover tooltip is flaky. 

### Reproduction Steps

1. Enable ace-linters 
2. Make the editor narrower or tab the token until its close the the right viewport border
3. Hover onto the token

### Ace Version / Browser / OS / Keyboard layout

1.29.0, Chrome, MacOS

**Comment by InspiredGuy** [comment]
Fixed in https://github.com/ajaxorg/ace/pull/5397, will be available in the next release
