### ISSUE TITLE
Enable `ReadOnly` only for certain lines

### ISSUE THREAD

**Issue by sleep9** [ajaxorg/ace#5364]
### Describe the feature

It would be great if one could disable certain lines. Is this currently possible?

### Use Case

Node based editor implementation

### Proposed Solution

editor.disableLine(start,end);

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### ACE version used

1.30.0

**Comment by nightwing** [comment]
What would disabling the line do? Simply make it readonly?

**Comment by sleep9** [comment]
Yes.

**Comment by ArunPatal** [comment]
This feature would be great to have....
