### ISSUE TITLE
HoverTooltips: Tooltips are positioned at the start of the token even when the token is not visible

### ISSUE THREAD

**Issue by oykuyilmaz** [ajaxorg/ace#5379]
### Describe the bug

Tooltips are rendered at the start of the token even if the editor is scrolled to the right and the token starts outside of the editor, so you can’t see the tooltip for long lines.

### Reproduction Steps

1. Open JavaScript document in https://ace.c9.io/kitchen-sink.html with linters enabled
2. Paste a token with a length long enough to make the editor's horizontal scroll appear
3. Scroll to the very right and hover on the token

![Screenshot 2023-11-01 at 13 11 59](https://github.com/ajaxorg/ace/assets/12100596/69005c33-e484-4b2a-baac-ca2a1f380ad0)

**Comment by marinsokol5** [comment]
Thanks for the submission! 

Indeed it does look like the moment the line is longer than the screen the tooltip just becomes too messy, we should keep it in the editor and wrap the text. 

So for small lines the tooltip is gonna render nicely in the editor and we see everything.
<img width="598" alt="Screenshot 2023-11-02 at 10 52 10" src="https://github.com/ajaxorg/ace/assets/30181549/d303802e-b731-43c7-9779-1a02f0431a8f">

For big lines the tooltip is positioned outside and we don't see the entire message.
<img width="898" alt="Screenshot 2023-11-02 at 10 52 42" src="https://github.com/ajaxorg/ace/assets/30181549/7418d1cb-0f80-4550-9430-67c53dfd4f5f">

**Comment by marinsokol5** [comment]
Sorry, I misunderstood it. 

So the issue is in the tooltip on hover, not on the one on diagnostics. 
So if there is a big line, the user might not even see the tooltip:
![long_line_hover](https://github.com/ajaxorg/ace/assets/30181549/f07e3d5a-3364-451c-92ec-c4d0f9aff0d5)
