### ISSUE TITLE
Add project (project name) to the list of projects using Ace on its website

### ISSUE THREAD

**Issue by guiqui** [ajaxorg/ace#5381]
### Project name

K8Studio

### Project link

https://k8studio.io/

### Logo link

https://k8studio.io/static/images/logo.png

### Additional information

Elevate your Kubernetes development with K8Studio, the ultimate integrated environment. Enjoy a powerful code editor, simplified containerization, cluster management, and real-time debugging. Join our community and experience efficiency, all in one IDE.

### Acknowledgements

- [X] I may be able to implement this request.

**Comment by marinsokol5** [comment]
Hey, looks good, thanks for letting us know!

**Comment by marinsokol5** [comment]
We will update the website with your logo as soon as possible, we first have to deal with https://github.com/ajaxorg/ace/issues/5375
