### ISSUE TITLE
HoverTooltips: Scroll doesn't close tooltip

### ISSUE THREAD

**Issue by oykuyilmaz** [ajaxorg/ace#5386]
### Describe the bug

Hover tooltips stay at a fixed position when I scroll the editor. Please see the screen recording. That's also causing issues when we want to make this tooltip scrollable (because the tooltip text could be huge). Scrolling does not work for hover tooltip but editor. 

https://github.com/ajaxorg/ace/assets/12100596/17e50066-cce0-4459-bc75-b4bfeb69a338

### Expected Behavior

Hover tooltips closes if we scroll outside of the tooltip. But hover tooltips should be scrollable if the mouse is on top of them.

### Current Behavior

Hover tooltips stay open on scroll. Bad UX experience. 

### Reproduction Steps

1. Open JavaScript doc on https://ace.c9.io/kitchen-sink.html with linters enabled
2. Hover on the function name (`foo`)
3. Scroll after tooltips is open

### Ace Version / Browser / OS / Keyboard layout

1.31.1/Firefox/MacOS

**Comment by andredcoliveira** [comment]
On the fence on whether this should be `p1` or `p2`. Are tooltips with large amounts of text currently broken, or is it only a future feature that's affected, @oykuyilmaz?

**Comment by oykuyilmaz** [comment]
The tooltips with any amount of text are affected. They all stay open on editor scroll.
