### ISSUE TITLE
Add project (Html playground) to the list of projects using Ace on its website

### ISSUE THREAD

**Issue by mikwakx** [ajaxorg/ace#5387]
### Project name

Html playground

### Project link

Https://htmlplayground.online

### Logo link

https://htmlplayground.online/wp-content/uploads/2023/10/Logopit_1697790200715.png

### Acknowledgements

- [X] I may be able to implement this request.

**Comment by andredcoliveira** [comment]
Hi, @mikwakx! If indeed you are able to, feel free to open a Pull Request to include the project in Ace's website.

Here's an example:
- https://github.com/ajaxorg/ace/pull/5350
