### ISSUE TITLE
Add "#" as new possible Ctrl-Command (Ctrl-#)

### ISSUE THREAD

**Issue by uhu1333** [ajaxorg/ace#5388]
### Describe the feature

As user I want to use Ctrl-# for new Ace commands, e.g. toggleComment, to be inline with other editors

### Use Case

Then I could use Ctrl-' for addCommand

### Proposed Solution

In key.js add "#"  as PRINTABLE KEY

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### ACE version used

1.14.11

**Comment by nightwing** [comment]
It is already possible to bind to `Ctrl-#` by doing `editor.commands.bindKey("Ctrl-Shift-3", console.log)`. Does this not work for the keyboard layout you are using?

**Comment by uhu1333** [comment]
@andredcoliveira 
I'm using a German keyboard layout. So my "Ctrl-Shift-3" is a "§". Do you have other ideas?

**Comment by nightwing** [comment]
Ace uses value of [event.keyCode](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode) to recognize the keybinding. This means that for shortcuts containing modifiers and non-alphanumeric keys you need to write qwerty equivalent of the shortcut. 

For German keyboard `#` (at least on mac) corresponds to `Backslash` key, so bindKey with "Ctrl-\" should achieve what you want.

The reason why keyCode does not translate special characters, is that on other keyboards they can correspond to different kinds of key combinations, e.g. on French keyboard `#` is entered with `Option-Shift-\`, so it is unclear if binding for`Cmd-#` should be equivalent to `Cmd-Option-Shift-\` or not available at all.

Similar for `Cmd-/`, which we use for toggle comment, but which is not possible to enter on German keyboard.

This is related to https://github.com/ajaxorg/ace/issues/4952, as new key and code properties behave differently from keyCode.

**Comment by uhu1333** [comment]
This is, what I get from event/ event.keyCode 

keydown Control { target: body, key: "#", charCode: 0, keyCode: 163 }
​altKey: false
​bubbles: true
​cancelBubble: false
​cancelable: true
​charCode: 0
​code: "Backslash"
​composed: true
​ctrlKey: true
​currentTarget: null
​defaultPrevented: true
​detail: 0
​eventPhase: 0
​explicitOriginalTarget: <body>
​isComposing: false
​isTrusted: true
​key: "#"
​keyCode: 163
​layerX: 0
​layerY: 0
​location: 0
​metaKey: false
​originalTarget: <body>
​rangeOffset: 0
​rangeParent: null
​repeat: false
​returnValue: false
​shiftKey: false
​srcElement: <body>
​target: <body>
​timeStamp: 443110
​type: "keydown"
​view: Window https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode
​which: 163
​
Does this help?
