### ISSUE TITLE
vim: block mode indent not working correctly

### ISSUE THREAD

**Issue by gtritchie** [ajaxorg/ace#5392]
### Describe the bug

Visual block mode indentation in vim mode not behaving the same as vim.

### Expected Behavior

This is what vim (and Monaco) do:

```
12        345
ab        cde
```

### Current Behavior

It indents the entire lines:

```
    12345
    abcde
```

### Reproduction Steps

With vim mode enabled:

* <kbd>i</kbd> then type 12345[Return]abcde so it looks like this:

```
12345
abcde
```

* <kbd>Esc</kbd> for normal mode then move cursor to the `c` character
* <kbd>Ctrl</kbd>+<kbd>v</kbd> for visual block mode
* <kbd>k</kbd> to go up a line
* <kbd>&gt;</kbd> to indent

### Ace Version / Browser / OS / Keyboard layout

1.31.1 / Chrome / any OS / vim

**Comment by nlujjawal** [comment]
This issue is still reproducible.
