### ISSUE TITLE
ext/textarea: sets styles using 'style' attributes

### ISSUE THREAD

**Issue by dimovpetar** [ajaxorg/ace#5394]
### Describe the bug

Textarea extension sets inline styles via attribute: https://github.com/ajaxorg/ace/blob/0d425b39aa71b6b91e242b25999d0b82203d4647/src/ext/textarea.js#L92

### Expected Behavior

The styles are set in a CSP compliant way

### Current Behavior

`setAttribute("style", ...)` is used

### Reproduction Steps

- 

### Additional Information/Context

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/style-src

### Ace Version / Browser / OS / Keyboard layout

1.31.1

**Comment by nightwing** [comment]
The attached pull request should fix this. Btw are you using ext/textarea.js or just got a warning from a tool?

**Comment by dimovpetar** [comment]
Just got a warning from a tool.
