### ISSUE TITLE
YAML Mode: Throws unexpected error

### ISSUE THREAD

**Issue by MarketingPip** [ajaxorg/ace#5408]
### Describe the bug

Improper YAML throws errors. 

### Expected Behavior

Logs to not be outputted. 

### Current Behavior

Logs / error was thrown. 

```json
{
  "message": "Script error.",
  "data": null,
  "file": "",
  "line": 0,
  "col": 0,
  "stack": null
}
```

### Reproduction Steps

Set Ace Editor Mode to YAML &  use value

```yaml
---

---
```

### Ace Version / Browser / OS / Keyboard layout

Browser, V1.31.2

**Comment by akoreman** [comment]
hi, thanks for reporting the issue, it has been fixed in #5409 and should be included in the next Ace release.
