### ISSUE TITLE
popup.js:在有滚动条的输入提示上，操作鼠标时（滚轮）会报错

### ISSUE THREAD

**Issue by oirobot-github** [ajaxorg/ace#5420]
### Describe the bug

popup.renderer.on("afterRender", function () {
            var row = popup.getRow();
            /**@type {any}*/
            var t = popup.renderer.$textLayer;
            var selected = t.element.childNodes[row - t.config.firstRow];
            var el = document.activeElement; // Active element is textarea of main editor
            if (selected !== t.selectedNode && t.selectedNode) {
                dom.removeCssClass(t.selectedNode, "ace_selected");
                el.removeAttribute("aria-activedescendant");
                selected.removeAttribute("aria-selected");
                t.selectedNode.removeAttribute("id");
            }
            t.selectedNode = selected;
            if (selected) {
                dom.addCssClass(selected, "ace_selected");
                var ariaId = getAriaId(row);
                selected.id = ariaId;
                t.element.setAttribute("aria-activedescendant", ariaId);
                el.setAttribute("aria-activedescendant", ariaId);
                selected.setAttribute("role", userAgent.isSafari ? "menuitem" : "option");
                selected.setAttribute("aria-roledescription", nls("item"));
                selected.setAttribute("aria-label", popup.getData(row).value);
                selected.setAttribute("aria-setsize", popup.data.length);
                selected.setAttribute("aria-posinset", row + 1);
                selected.setAttribute("aria-describedby", "doc-tooltip");
                selected.setAttribute("aria-selected", "true");
            }
        });

### Expected Behavior

正常

### Current Behavior

在下面一行中 selected 为 undefined
selected.removeAttribute("aria-selected"); 

### Reproduction Steps

无

### Ace Version / Browser / OS / Keyboard layout

1.32.1

**Comment by marinsokol5** [comment]
Hey,

I don't understand the issue, could you rewrite it fully in English?

**Comment by oirobot-github** [comment]
When too much floating window content is entered, a scroll bar appears.
Use the mouse in the floating window to perform actions, such as wheel scrolling, and selected is undefined in the following example
"selected.removeAttribute("aria-selected");"
Code block in   popup.js
`if (selected !== t.selectedNode && t.selectedNode) {
dom.removeCssClass(t.selectedNode, "ace_selected");
el.removeAttribute("aria-activedescendant");
selected.removeAttribute("aria-selected");
t.selectedNode.removeAttribute("id");
}`

**Comment by marinsokol5** [comment]
Hey, we released the new version without this bug in 1.32.2

**Comment by oirobot-github** [comment]
Received, thank you
