### ISSUE TITLE
Add Ziglang support

### ISSUE THREAD

**Issue by bajrangCoder** [ajaxorg/ace#5428]
### Describe the feature

Zig is low level system language with simple syntax (https://ziglang.org)

Add a mode and syntax higlighting for this language

### Use Case

to be able to write zig in ace editor

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### ACE version used

latest

**Comment by vanillajonathan** [comment]
Sounds good, would you like to implement it?

You can look at some of the other syntax highlighters under [`/src/mode/`](https://github.com/ajaxorg/ace/tree/master/src/mode). It's not so difficult if you have some experience with regular expressions.

**Comment by bajrangCoder** [comment]
> Sounds good, would you like to implement it?
> 
> You can look at some of the other syntax highlighters under [`/src/mode/`](https://github.com/ajaxorg/ace/tree/master/src/mode). It's not so difficult if you have some experience with regular expressions.

Already implemented https://github.com/ajaxorg/ace/pull/5429

**Comment by vanillajonathan** [comment]
Good job!
