### ISSUE TITLE
hardcoder.xyz

### ISSUE THREAD

**Issue by hngts** [ajaxorg/ace#5433]
### Project name

Funcdown

### Project link

https://hardcoder.xyz/?mkp=fncd

### Logo link

https://hardcoder.xyz/favicon.ico

### Acknowledgements

- [ ] I may be able to implement this request.

**Comment by oykuyilmaz** [comment]
Hi @hngts, we see you've checked the label "I may be able to implement this request.". If so, here are some examples to include your project on Ace website:

- #5014
- #5222 
- #5350

Feel free to open a PR 🙂

**Comment by hngts** [comment]
Hi @oykuyilmaz, thanks for support. 

Yes, it was .. well, I maybe accidentally marked that checkbox. I am not sure whether I actually know how to implement my request .. saw those three links, but I would like some further help, if possible.
