### ISSUE TITLE
Enhance SQL Support

### ISSUE THREAD

**Issue by aersam** [ajaxorg/ace#5446]
### Describe the feature

SQL has lots of keywords but only very few are already added. I think all ANSI Keywords should be there: https://docs.databricks.com/en/sql/language-manual/sql-ref-reserved-words.html#ansi-reserved-words 

Also some dialects have additional data types, like `string` in Spark.

### Use Case

Just some nicer syntax highlighting

### Proposed Solution

I could do a PR do add the keywords/datatypes

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### ACE version used

v1.32.3

**Comment by InspiredGuy** [comment]
Hi @aersam, thank you for the request. To add new keywords for SQL, you would need to add them to https://github.com/ajaxorg/ace/blob/master/src/mode/sql_highlight_rules.js in appropriate places. As for dialects, it seems best to modify the language modes corresponding to those specific dialects, or create new language modes in case they are not present and there is a need for them to be added to the main repository. Your PR would be welcome!
