### ISSUE TITLE
Issue with style-src CSP

### ISSUE THREAD

**Issue by MartinezVillaresAdrian** [ajaxorg/ace#5452]
Hello, I have an issue that you might be able to help me with.

In my current project, I need to remove 'unsafe-inline' CSP header for the 'style-src' .

I've been reading a lot of comments in the ace repository and they all leave me to the next solution

`ace.config.set('useStrictCSP', true)`

I tried that and the errors from the CSP are gone, but the editors are not working, I guess that's because the styles are not being loaded anymore.

Have you ever faced that issue?, is it possible to set up a nonce for the editor ?

Regards

**Comment by marinsokol5** [comment]
Hey, yeah that's correct. 
So once the sctrictCSP is set, you need to load your CSS for the editor and the theme manually. So indeed 
```
<link rel="stylesheet" href="../css/ace.css">
<link rel="stylesheet" href="../css/theme/tomorrow_night_eighties.css">
```

Or a more modern import inside of JS if your bundle supports that.
