### ISSUE TITLE
SQLtest.online

### ISSUE THREAD

**Issue by rozhnev** [ajaxorg/ace#5457]
### Project name

SQLtest

### Project link

https://sqltest.online

### Logo link

https://sqltest.online/favicons/android-chrome-512x512.png

### Additional information

SQLtest - place where you can test your SQL knowledge for free

### Acknowledgements

- [X] I may be able to implement this request.

**Comment by whazor** [comment]
Hi! Nice project. Feel free to include your project on Ace website, you can do so by creating a PR like:

- #5014
- #5222 
- #5350
- #5442

**Comment by rozhnev** [comment]
Thank you. Just did this!
