### ISSUE TITLE
aceeditor:unable to add new key/value pairs in json mode editor.

### ISSUE THREAD

**Issue by Pa1sathvik** [ajaxorg/ace#5466]
### Describe the bug

I see a weird issue in AceEditor.
When i am trying to add new key,value in json mode editor, i see its not taking any value after entering key and moving back to initial state.

### Expected Behavior

I expect editor should take the content i type but here after entering key it is just going back to initial state staring in the editor.

### Current Behavior

I expect editor should take the content i type but here after entering key it is just going back to initial state staring in the editor.

### Reproduction Steps

``Initialise editor with json mode with below json in string format given to value attribute like below.

 ````
<Editor data-cy="ace-editor"
                            mode="json"
                            theme="github"
                            value={JSON.stringify({data:{},flow_params:{},
                              metadata:{}}, null, 4)}
                            onChange={json => onChangeFlowJSON(json)}
                            name="flow-editor"
                            editorProps={{ $blockScrolling: true }}
                   
                          />`
```

you can see below json in the editor.

```
{
    "data": {},
    "flow_params": {},
    "metadata": {}
}
```

When  you try to add new key / value pair , its not taking after entering key.

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### Ace Version / Browser / OS / Keyboard layout

1.4.13/Chrome/MAC

**Comment by nightwing** [comment]
Hi, what do you use for `Editor`.
If you are using [react-ace](https://www.npmjs.com/package/react-ace), the most likely issue is that you are resetting value of the editor with ` value={JSON.stringify({data:{},flow_params:{},metadata:{}}, null, 4)}` line. In this case try using  [defaultValue](https://mkslanc.github.io/ace-playground/?value=Ly9zYW1wbGVzL2hlbGxvIHdvcmxkCiAKCi8vIEVhc2llc3Qgd2F5IHRvIHJ1biBBQ0UgZWRpdG9yIGluIGNvbnRhaW5lciB3aXRoIGlkPSJleGFtcGxlIgovLyBhY2UuZWRpdCgiZXhhbXBsZSIsIHsKLy8gICAgIHRoZW1lOiAiYWNlL3RoZW1lL3RleHRtYXRlIiwKLy8gICAgIG1vZGU6ICJhY2UvbW9kZS9qYXZhc2NyaXB0IiwKLy8gICAgIHZhbHVlOiAiY29uc29sZS5sb2coJ0hlbGxvIHdvcmxkJyk7IgovLyB9KTtcMFwwPCEtLTxzY3JpcHQgc3JjPSJodHRwczovL3Jhdy5naXRoYWNrLmNvbS9hamF4b3JnL2FjZS9tYXN0ZXIvZGVtby9raXRjaGVuLXNpbmsvcmVxdWlyZS5qcyI%2BPC9zY3JpcHQ%2BLS0%2BCjxzY3JpcHQgc3JjPSJodHRwczovL3d3dy51bnBrZy5jb20vYWNlLWJ1aWxkc0BsYXRlc3Qvc3JjLW5vY29uZmxpY3QvYWNlLmpzIj48L3NjcmlwdD4KPHNjcmlwdCBzcmM9Imh0dHBzOi8vd3d3LnVucGtnLmNvbS9yZWFjdC1hY2VAMTAuMS4wL2Rpc3QvcmVhY3QtYWNlLmpzL21haW4uanMiPjwvc2NyaXB0Pgo8c2NyaXB0IHNyYz0iaHR0cHM6Ly91bnBrZy5jb20vcmVhY3RAMTgvdW1kL3JlYWN0LmRldmVsb3BtZW50LmpzIiBjcm9zc29yaWdpbj48L3NjcmlwdD4KPHNjcmlwdCBzcmM9Imh0dHBzOi8vdW5wa2cuY29tL3JlYWN0LWRvbUAxOC91bWQvcmVhY3QtZG9tLmRldmVsb3BtZW50LmpzIiBjcm9zc29yaWdpbj48L3NjcmlwdD4KPGRpdiBpZD0nZXhhbXBsZScgc3R5bGU9ImhlaWdodDogMTAwJSI%2BPC9kaXY%2BCjxzY3JpcHQ%2BCiAgICB2YXIgQWNlRWRpdG9yID0gUmVhY3RBY2UuZGVmYXVsdAogICAgdmFyIHJvb3QgPSBSZWFjdERPTS5jcmVhdGVSb290KGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3IoIiNleGFtcGxlIikpOwogICAgdmFyIGUgPSBSZWFjdC5jcmVhdGVFbGVtZW50OwogICAgcm9vdC5yZW5kZXIoZShBcHAsIHt2YWx1ZTogIjEifSkpOwogICAgCiAgICAKICAgIAogICAgZnVuY3Rpb24gQXBwKHt2YWx1ZX0pIHsKICAgICAgICByZXR1cm4gUmVhY3QuY3JlYXRlRWxlbWVudCgiZGl2Iiwge30sIGUoImRpdiIsIHt9LCB2YWx1ZSksIAogICAgICAgICAgICBSZWFjdC5jcmVhdGVFbGVtZW50KEFjZUVkaXRvciwgewogICAgICAgICAgICBtb2RlOiAianNvbiIsCiAgICAgICAgICAgIHRoZW1lOiAiZ2l0aHViIiwKICAgICAgICAgICAgZGVmYXVsdFZhbHVlOiBKU09OLnN0cmluZ2lmeSh7ZGF0YToiIixmbG93X3BhcmFtczp7fSwgbWV0YWRhdGE6e319LCBudWxsLCA0KSwKICAgICAgICAgICAgb25DaGFuZ2U6IChqc29uKSA9PiBvbkNoYW5nZUZsb3dKU09OKGpzb24pLAogICAgICAgIH0pKQogICAgfQogICAgCiAgICBmdW5jdGlvbiBvbkNoYW5nZUZsb3dKU09OKHh4KSB7CiAgICAgICAgdHJ5IHsKICAgICAgICAgICAgdmFyIHZhbHVlID0gSlNPTi5wYXJzZSh4eCkuZGF0YQogICAgICAgIH0gY2F0Y2goZSkgewogICAgICAgICAgICByZXR1cm4KICAgICAgICB9CiAgICAgICAgaWYgKHZhbHVlKQogICAgICAgICAgICByb290LnJlbmRlcihlKEFwcCwge3ZhbHVlOiB2YWx1ZX0pKTsKICAgIH0KPC9zY3JpcHQ%2BCgoK#hello-world)

**Comment by Pa1sathvik** [comment]
Thanks @nightwing  for the clarification.
