### ISSUE TITLE
标签的显示与隐藏

### ISSUE THREAD

**Issue by dollarm** [ajaxorg/ace#5469]
### Describe the feature

自定义一对标签，如< custom ></ custom >，在标签中输入内容，< custom >文本内容</ custom >，在编辑器中只显示【文本内容】而不显示标签【< custom ></ custom >】，在获取编辑框中的内容实，可以选择获取或者不获取自定义标签，例如：最后可以获取内容：1.< custom >文本内容</ custom >  或者2：文本内容

### Use Case

在进行编辑数据库操作的时候，往后台传入数据，需要这个标签，但是用户展示的时候不需要这个标签

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### ACE version used

0.0.15

**Comment by marinsokol5** [comment]
Hey, can you rewrite the request in English?

**Comment by sxw66** [comment]
> Hey, can you rewrite the request in English?
He wants to customize a pair of tags, such as < custom ></ custom >, enter the content in the tag, < custom > text content </ custom >, and display only the text content in the editor without displaying the label [< custom ></ custom >]. In the get edit box, you can choose to get or not get the custom label, for example: Finally, you can get the content: 1.< custom > text content </ custom > or 2: Text content when editing the database operation, to the background data, need this label, but the user does not need this label when displaying

**Comment by akoreman** [comment]
Thanks for the translation. Thanks for the feature-request, I think I get the request. I don't think this is a feature request we'll get to implement anytime soon, so I'll go ahead and close it.
