### ISSUE TITLE
BastifyAdd project (project name) to the list of projects using Ace on its website

### ISSUE THREAD

**Issue by ysilvela** [ajaxorg/ace#5482]
### Project name

Bastify

### Project link

https://www.bastify.com

### Logo link

https://panel.bastify.com/dist/images/logo.svg

### Acknowledgements

- [X] I may be able to implement this request.

**Comment by marinsokol5** [comment]
Hey, since you marked that you are able to submit a PR,
you can check out similar PRs in https://github.com/ajaxorg/ace/pull/5382 and https://github.com/ajaxorg/ace/pull/5374
