### ISSUE TITLE
(ace-code): Incorrect typings for 'ace-code/src/mode/swift_highlight_rules'

### ISSUE THREAD

**Issue by just-boris** [ajaxorg/ace#5511]
### Describe the bug

The typings for swift_highlight_rules do not match the actual behavior

```js
// import according to the types
import { SwiftHighlightRules } from "ace-code/src/mode/swift_highlight_rules";

// actual import, works in runtime, but broken in typescript
import { HighlightRules } from "ace-code/src/mode/swift_highlight_rules";
```

### Ace Version / Browser / OS / Keyboard layout

1.32.3

**Comment by andredcoliveira** [comment]
Hey, @just-boris! Is this something you could submit a PR for?

**Comment by just-boris** [comment]
I think there is a fundamental issue with your project, that such integrations are not tested properly. It is not something which an external contributor can fix.

For my tasks I already unblocked myself, see [the linked pr](https://github.com/cloudscape-design/code-view/pull/28), I could just remove the dependency on the problematic code.

**Comment by andredcoliveira** [comment]
In terms of the fundamental issue: Ace is a vanilla JavaScript project and we're adding type-checking capabilities to it incrementally to improve our testing posture.

In terms of this specific issue, despite [your mitigation](https://github.com/cloudscape-design/code-view/pull/28): does https://github.com/ajaxorg/ace/pull/5516 fix it?

**Comment by just-boris** [comment]
Yes, that works. Thanks
