### ISSUE TITLE
添加basic语言高亮

### ISSUE THREAD

**Issue by chen-xiaoxing** [ajaxorg/ace#5532]
### Describe the feature

添加basic语言高亮

### Use Case

添加basic语言高亮

### Proposed Solution

添加basic语言高亮

### Other Information

添加basic语言高亮

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### ACE version used

"ace-builds": "^1.32.7"+vue3+ts

**Comment by nightwing** [comment]
try using vbscript mode for basic https://github.com/ajaxorg/ace/blob/master/src/mode/vbscript.js

if it does not work well for your code, could you provide an example of such file?

**Comment by chen-xiaoxing** [comment]
这个可以，请问如何按需引入呢？我希望打包文件的时候ace包可以尽可能的小

**Comment by chen-xiaoxing** [comment]
这个vbscript可以，请问如何按需插入呢？我希望备份文件的时候ace包可以解决的小问题

**Comment by chen-xiaoxing** [comment]
这个可以，请问如何按需插入呢？我希望备份文件的时候ace包可以解决的小问题

**Comment by chen-xiaoxing** [comment]
这个可以，请问如何按需引入呢？我希望打包文件的时候ace包可以小一点

**Comment by marinsokol5** [comment]
Hey,

Let's switch the conversation to english, to be inclusive to both other developers looking at issues and us maintainers.

> This is OK. How can I introduce it on demand? I hope the ace package can be smaller when packaging files

Is it possible for you to lazily load just ace? The modes are already separate files loaded on demand, same as extensions. The file from https://github.com/ajaxorg/ace-builds/blob/master/src-min/ace.js is around 400KB, we cannot be much smaller than this right now sadly.

**Comment by marinsokol5** [comment]
Closing, since there doesn't seem to be any further action from our end. 
If it's reopened, please switch to English.

**Comment by chen-xiaoxing** [comment]
hi，vbscript is an upgraded version of basic language. When I used basic language to write in the editor, I found that the folding function cannot be used. Here is the syntax of basic language. The focus is on pages 22-24. You can add a syntax highlight of basic language here. ? Thanks.         

link: https://paladin-t.github.io/my_basic/MY-BASIC%20Quick%20Reference.pdf

**Comment by InspiredGuy** [comment]
You can create a [feature request](https://github.com/ajaxorg/ace/issues/new?assignees=&labels=feature-request%2Cneeds-triage&projects=&template=feature-request.yml&title=Add+language+support+for+Basic) for "Basic" language support, or [report an issue](https://github.com/ajaxorg/ace/issues/new?assignees=&labels=bug%2Cneeds-triage&projects=&template=bug-report.yml&title=vbscript%3A+folding+does+not+work+for+Basic) for folding not working for Basic documents in vbscript mode. Please describe your problem in English and attach an example of the code which does not behave in an expected way. You are also welcome to implement the language mode or fix the issue yourself :)
