### ISSUE TITLE
(nord_dark): (theme doesn't work)

### ISSUE THREAD

**Issue by propio155** [ajaxorg/ace#5541]
### Describe the bug

when i try to add the theme to caret there is no difference(the previous theme stays the same).

### Expected Behavior

The theme to change

### Current Behavior

No logs?I don't where those could be found.

### Reproduction Steps

`"defaultTheme": "nord_dark"` then CTRL+S.

### Additional Information/Context

I am using the caret text editor for chrome os

### Ace Version / Browser / OS / Keyboard layout

Chrome OS

**Comment by nightwing** [comment]
On which site do you see this problem? The json configuration `defaultTheme` is not a feature provided by ace itself.

**Comment by oykuyilmaz** [comment]
Hi, the theme "Nord Dark" works as expected on our side, you could try choosing the theme on the left "Theme" dropdown menu [here](https://ace.c9.io/kitchen-sink.html). Could it be an issue on Caret text editor side? I see they have a list of Ace themes defined [here](https://github.com/thomaswilburn/Caret/blob/0c6f26c4663d9a9ad66c79772fc7be60ac044b5e/config/ace.json#L2), do other themes work for you?
