### ISSUE TITLE
My coder Seven 

### ISSUE THREAD

**Issue by WhoappRoom** [ajaxorg/ace#5542]
### Project name

My Coder

### Project link

https://my-coder-seven.vercel.app/

### Logo image 

![l.png](https://github.com/ajaxorg/ace/assets/158821136/0ab0fc9b-35fa-4eeb-a8d5-5476023b7fb2)

### Additional information

<h1>About </h1>
<p>My coder is the web application you can edit html file and can publish your code in the app also you can use page paper to publish your html file to the internet in one click</p>
<div class="container">
    <img src="https://my-coder-seven.vercel.app/l.png" alt="My Coder Seven Logo" class="logo">
    <h1>About My Coder Seven</h1>
    <p>Welcome to My Coder Seven, your go-to platform for coding and collaboration! Our application is designed to empower developers like you to create, share, and collaborate on coding projects effortlessly.</p>
    <h2>Key Features:</h2>
    <ul>
        <li><strong>Secure Authentication:</strong> My Coder Seven employs Firebase Authentication to ensure secure sign-in using Google, GitHub, or Twitter accounts.</li><br>
        <li><strong>Code Snippet Management:</strong> Easily create, edit, and delete code snippets. Each snippet is associated with your profile for easy access.</li><br>
        <li><strong>Real-time Collaboration:</strong> Share your code snippets with other users and collaborate on projects in real-time.</li><br>
        <li><strong>Advanced Code Editor:</strong> Utilize our powerful code editor with syntax highlighting, auto-completion, and customizable themes to enhance your coding experience.</li><br>
        <li><strong>File Management:</strong> Upload, download, and manage HTML, CSS, and JavaScript files directly from the application.</li>
    </ul>
    <p>With My Coder Seven, you have the tools you need to bring your coding ideas to life and collaborate with fellow developers from around the world. Join us and start coding!</p>
    <p><strong>Developed by:</strong>Cabdi Waaxid Siciid from somalia.</p>
</div>

<a href="https://my-coder-seven.vercel.app/">Try it Now</a>
<h1>Use page paper to publish html file</h1>
<p>First go settings then click tight button button "Paper" then you will go directly to page you can publish your html single file Choose file from your device upload file when upload complete we automatically generate link directly to see your file copy link send your friends <a href="https://my-coder-seven.vercel.app/paper.html">Try it now</a></p>
### Acknowledgements

- [X] I may be able to implement this request.

**Comment by oykuyilmaz** [comment]
Hi @WhoappRoom, is there any other link to the logo which is permanent?

**Comment by WhoappRoom** [comment]
> Hi @WhoappRoom, is there any other link to the logo which is permanent? 

No!

**Comment by rahulkumarsingh73690** [comment]
A permanent logo means a logo hosted on your site. e.g - https://my-coder-seven.vercel.app/logo.png

**Comment by rahulkumarsingh73690** [comment]
It would be best if your website had some serious UI improvement. Additionally, showing a login page instead of a landing page is not ideal. Why would any user sign up without knowing about your product?

**Comment by WhoappRoom** [comment]
@rahulkumarsingh73690 yes hosted https://my-coder-seven.vercel.app/logo.png

**Comment by WhoappRoom** [comment]
@rahulkumarsingh73690 the user can get more info these linkes https://my-coder-seven.vercel.app/questions.html and https://my-coder-seven.vercel.app/About.html

**Comment by WhoappRoom** [comment]
> Hi @WhoappRoom, is there any other link to the logo which is permanent?

https://my-coder-seven.vercel.app/logo.png

**Comment by InspiredGuy** [comment]
Closing as a duplicate of https://github.com/ajaxorg/ace/issues/5614
