### ISSUE TITLE
Add project Techcopes to the list of projects using Ace on its website

### ISSUE THREAD

**Issue by rahulkumarsingh73690** [ajaxorg/ace#5552]
### Project name

Techcopes

### Project link

https://techcopes.com/

### Logo link

https://techcopes.com/logo.png

### Additional information

Using ace editor in code formatters 

### Acknowledgements

- [x] I may be able to implement this request.

**Comment by InspiredGuy** [comment]
Hey, I see you ticked the box that you could implement it yourself - feel free to do that, contributions are welcome. Here is an example of a PR which adds a different project to the website - https://github.com/ajaxorg/ace/pull/5546

**Comment by InspiredGuy** [comment]
https://github.com/ajaxorg/ace/pull/5553 was merged, will be available in next release
