### ISSUE TITLE
Editor can't enter a newline before a JSDoc comment

### ISSUE THREAD

**Issue by kungfooman** [ajaxorg/ace#5555]
### Describe the bug

Editor can't enter a newline before a JSDoc comment.

### Expected Behavior

![image](https://github.com/ajaxorg/ace/assets/5236548/45f9bc59-9e4d-4745-b961-79f7afca32ac)

### Current Behavior

![image](https://github.com/ajaxorg/ace/assets/5236548/30227817-737a-4052-a126-4116e9ba955e)

### Reproduction Steps

1) Go to https://ace.c9.io/
2) Move cursor to start of editor:
![image](https://github.com/ajaxorg/ace/assets/5236548/5441b230-2498-4448-9d6c-acd9bc98b4a8)
3) Press Enter.

### Ace Version / Browser / OS / Keyboard layout

1.33.2 / Chrome / Linux / German keyboard layout

**Comment by InspiredGuy** [comment]
https://github.com/ajaxorg/ace/pull/5571 with the fix was merged, will be available in the next release
