### ISSUE TITLE
CSS Mode support for CSS Nesting

### ISSUE THREAD

**Issue by TimChinye** [ajaxorg/ace#5556]
### Describe the feature

Pretty straight-forward, I want to be able to collapse rules.

As of now, the solution is just to use SCSS mode, but this may cause issues in the long run since it's not explicitly for CSS.

### Use Case

The current CSS mode is technically just broken now.

### Proposed Solution

Look how SCSS mode does it.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### ACE version used

Latest - 1.33.2

**Comment by whazor** [comment]
The CSS and SCSS highlight rules are defined here:
- https://github.com/ajaxorg/ace/blob/master/src/mode/css_highlight_rules.js
- https://github.com/ajaxorg/ace/blob/master/src/mode/scss_highlight_rules.js

**Comment by akoreman** [comment]
Hey, #5557 should fix the folding for nested rules, it will be included in the next Ace release after 1.32.2.
