### ISSUE TITLE
CSS Worker support for CSS Nesting

### ISSUE THREAD

**Issue by TimChinye** [ajaxorg/ace#5559]
### Describe the feature

Any code that uses the new Nesting feature of CSS gets a bunch of invalid errors.

![Valid CSS Code with a ton of errors due to this outdated worker](https://github.com/ajaxorg/ace/assets/150863066/1c93bcb9-0cf8-4994-a9b6-11b2bd4c7aa5)

### Use Case

It completely breaks the syntax validation for all code using CSS Nesting.

### Proposed Solution

I can just disable the worker, temporarily, until a fix comes using `<Ace>.getSession().setUseWorker(false);`.

### Other Information

Unlike the CSS Mode, this isn't a major issue as it's more of a visual bug.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### ACE version used

1.33.3

**Comment by nightwing** [comment]
Using https://github.com/mkslanc/ace-linters fixes this issue, see the playground example [here](https://mkslanc.github.io/ace-playground/?value=Ly9zYW1wbGVzL3R5cGVzY3JpcHQgbGFuZ3VhZ2Ugc2VydmljZQoKYWNlLnJlcXVpcmUoImFjZS9leHQvbGFuZ3VhZ2VfdG9vbHMiKTsKbGV0IGVkaXRvciA9IGFjZS5lZGl0KCJleGFtcGxlIiwgewogICAgdGhlbWU6ICJhY2UvdGhlbWUvY29iYWx0IiwKICAgIG1vZGU6ICJhY2UvbW9kZS9jc3MiLAogICAgdmFsdWU6IGA6cm9vdCB7CiAgLS1jc3MtdmFyOiBibHVlOwp9Ci5zZWxlY3RvciB7CiAgY29sb3I6IHZhcigtLWNzcy12YXIpOwp9Ci5vdGhlci1zZWxlY3RvciB7CiAgLS1jc3MtdmFyOiBncmVlbjsKfQoub3RoZXItc2VsZWN0b3IgLmNoaWxkIHsKICBjb2xvcjogdmFyKC0tY3NzLXZhcik7IC8qd291bGQgYmUgZ3JlZW4qLwp9CiogewoKfQpgCn0pOwovLyBlbmFibGUgYXV0b2NvbXBsZXRpb24gYW5kIHNuaXBwZXRzCmVkaXRvci5zZXRPcHRpb25zKHsKICAgIGVuYWJsZUJhc2ljQXV0b2NvbXBsZXRpb246IHRydWUsCiAgICBlbmFibGVTbmlwcGV0czogdHJ1ZSwKICAgIGVuYWJsZUxpdmVBdXRvY29tcGxldGlvbjogdHJ1ZQp9KTsKCi8vY3JlYXRlIExhbmd1YWdlIFByb3ZpZGVyIGZvciBlZGl0b3IKbGV0IHByb3ZpZGVyID0gTGFuZ3VhZ2VQcm92aWRlci5mcm9tQ2RuKCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2FjZS1saW50ZXJzL2J1aWxkIik7CgovLyBSZWdpc3RlciB0aGUgZWRpdG9yIHdpdGggdGhlIGxhbmd1YWdlIHByb3ZpZGVyCnByb3ZpZGVyLnJlZ2lzdGVyRWRpdG9yKGVkaXRvcik7CgpcMFwwPHNjcmlwdCBzcmM9Imh0dHBzOi8vd3d3LnVucGtnLmNvbS9hY2UtYnVpbGRzQGxhdGVzdC9zcmMtbm9jb25mbGljdC9hY2UuanMiPjwvc2NyaXB0Pgo8IS0tIGxvYWQgYWNlIGxhbmd1YWdlIHRvb2xzIC0tPgo8c2NyaXB0IHNyYz0iaHR0cHM6Ly93d3cudW5wa2cuY29tL2FjZS1idWlsZHNAbGF0ZXN0L3NyYy1ub2NvbmZsaWN0L2V4dC1sYW5ndWFnZV90b29scy5qcyI%2BPC9zY3JpcHQ%2BCjwhLS0gbG9hZCBhY2UgbGludGVycyAtLT4KPHNjcmlwdCBzcmM9Imh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vYWNlLWxpbnRlcnMiPjwvc2NyaXB0Pgo8ZGl2IGlkPSdleGFtcGxlJyBzdHlsZT0iaGVpZ2h0OiAxMDAlIj48L2Rpdj4K#typescript-language-service)

Perhaps we should also consider replacing old workers in ace-builds with the ones from ace-linters?

**Comment by TimChinye** [comment]
Highly agree, ace-linters works perfectly.

**Comment by akoreman** [comment]
Thanks for opening the issue. Given that ace-linters offers a way better experience here, I don't think we'll be addressing issues in the stale CSS worker code.
