### ISSUE TITLE
(lua):  '=' expected near '::'

### ISSUE THREAD

**Issue by VanSure-Big** [ajaxorg/ace#5562]
### Describe the bug

/
![图片1](https://github.com/ajaxorg/ace/assets/50132552/b9812ea9-153a-4630-a9df-c6bd63613812)

### Expected Behavior

In the lua language, '::' can be used, so there should be no error here

### Current Behavior

mode:'lua',
Use the '::' symbol to indicate an error

### Reproduction Steps

myLabel ::  

### Ace Version / Browser / OS / Keyboard layout

 "ace-builds": "^1.33.2",

**Comment by nightwing** [comment]
We use https://github.com/fstirlitz/luaparse to parse lua, 

But as far as i can tell the code
 ```lua
goto label
label::
```
 is not valid, (at least in lua 5.3)
https://onecompiler.com/lua/42e3u4h4g

https://stackoverflow.com/questions/34623542/what-is-the-purpose-of-double-colons-in-lua

it should be 
```lua
goto label
::label::
```

Could you please check with which version of lua does it work?
