### ISSUE TITLE
Desktop Safari: Editor background color doesn't update consistently after switching theme

### ISSUE THREAD

**Issue by jeffcompton** [ajaxorg/ace#5569]
### Describe the bug

I've noticed that themes always load correctly on initial render on Desktop Safari, however upon switching from dark > light theme or light > dark theme, the background color often doesn't render as expected.

This issue is reproducible by switching between any light mode and dark mode on Ace Kitchen Sink.

### Expected Behavior

Switching from the theme: Chrome > Molokai should have rendered a black background

### Current Behavior

Switching from the theme: Chrome > Molokai did not render a black background

### Reproduction Steps

On Desktop Safari, go to Ace Kitchen Sink and follow the steps I shared in this screen recording. It's also easily to reproduce by creating a simple sample project with just an editor, and a timer/dark mode observer to change the theme from light > dark or vice versa.

https://github.com/ajaxorg/ace/assets/1779141/1039526b-b72c-43bf-a3ae-8d8474532db3

### Ace Version / Browser / OS / Keyboard layout

Ace Version 1.34.2 / Safari 17.5 / QWERTY

**Comment by nightwing** [comment]
@akoreman since safari have not fixed this bug for a long time, should we add setTimeout workaround from https://github.com/ajaxorg/ace/issues/5226#issuecomment-1613883197 to our setTheme?

**Comment by InspiredGuy** [comment]
https://github.com/ajaxorg/ace/pull/5573 with a workaround was merged, will be available in the next release
