### ISSUE TITLE
(default_gutter_handler): showTooltip is CSP incompliant - assigns innerHTML

### ISSUE THREAD

**Issue by dimovpetar** [ajaxorg/ace#5575]
### Describe the bug

GutterTooltip#showTooltip uses `this.setHtml`, which results in `innerHTML=...`
https://github.com/ajaxorg/ace/blob/a3277eaef554bdf6393e3957d60f5420e1d7130f/src/mouse/default_gutter_handler.js#L227

### Expected Behavior

Tooltip is created in CSP compliant way

### Current Behavior

Tooltip is created in CSP incompliant way

### Reproduction Steps

1. Open any ace editor and type something invalid
2. Hover on the tooltip with the mouse

### Ace Version / Browser / OS / Keyboard layout

1.31.1

**Comment by dimovpetar** [comment]
@akoreman thanks for the fix. Is this issue ready to be closed now?

**Comment by akoreman** [comment]
Yeah this issue should be resolved now
