### ISSUE TITLE
touch_handler: Hide actions that are not available

### ISSUE THREAD

**Issue by whazor** [ajaxorg/ace#5579]
### Describe the bug

In mobile there is a touch handler bar, but when these commands are disabled the commands are still shown. The buttons currently say "Select All", "Paste", "Find", "Palette". But we don't want to use the 'palette' command for example, so it would be nice if that command is disabled, that it is also not shown.

<img width="432" alt="image" src="https://github.com/ajaxorg/ace/assets/184182/6aaf7bf6-cc46-4aa4-b517-2bacf0209070">

### Expected Behavior

When disabling command `openCommandPalette` or `find`, hide the action from [context menu](https://github.com/ajaxorg/ace/blob/a3277eaef554bdf6393e3957d60f5420e1d7130f/src/mouse/touch_handler.js#L30-L38).

### Current Behavior

Actions "Select All", "Paste", "Find", "Palette" are always shown, but not used.

### Reproduction Steps

1. disable "openCommandPalette" command
2. open Ace in mobile
3. click on the `...`
4. observe that Palette does not do anything anymore

### Possible Solution

For every action in the touch_handler, check whether the action/command is enabled before showing.

### Ace Version / Browser / OS / Keyboard layout

iOS/Android

**Comment by InspiredGuy** [comment]
https://github.com/ajaxorg/ace/pull/5580 with the fix was merged, will be available in the next release
