### ISSUE TITLE
Add project aFreetools to the list of projects using Ace on its website

### ISSUE THREAD

**Issue by afreravi** [ajaxorg/ace#5618]
### Project name

aFreetools

### Project link

https://afreetools.com

### Logo link

https://afreetools.com/wp-content/uploads/2024/04/logo-dark.png

### Additional information

Please add link for aFreetools to this list, this online tool uses Ace.js editor for development

### Acknowledgements

- [X] I may be able to implement this request.

**Comment by akoreman** [comment]
Hi, I see you ticked the 'I may be able to implement this request' box, here's an example PR of how you can add your project to the website #5608.

**Comment by afreravi** [comment]
Hi @akoreman, I cloned the repo and added the required changes in the new box. But when tried to push it gives an error 'dont have permission to push to this repo'

Can you help me on this.

**Comment by akoreman** [comment]
The way to contribute your code is by opening a [pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests), easiest way to do that is to create a [fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/fork-a-repo) of the Ace repository, push your changes to the fork and then [open a pull request from the fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork).

Let me know if you need more help 🙂

**Comment by afreravi** [comment]
Great! I created pull request. Thanks for quick response.
