### ISSUE TITLE
XSS Security Vulnerability when using Messaging with postMessage()

### ISSUE THREAD

**Issue by bsomeshwer** [ajaxorg/ace#5641]
Source:
https://github.com/ajaxorg/ace-builds/blob/cb4c7c3d105c92b04f45d78d329f5509b7098906/src/ace.js (line 2010)
Note: this file contains wildcard (*) usage with win.postMessage() which allows css attacks from unauthorized sources.

Function:
win.postMessage(messageName, "*");

Description:
TargetOrigin parameter for Messaging feature postMessage using a wildcard (*) in the below location: 
ace-builds/src/ace.js at line number 2010 and which allows the potential for cross site scripting attacks from unauthorized sources.

It is suggested by the OWASP CRV2 regarding Messaging to explicitly specify the intended target origin and do not use an open end-point / wildcard (*).

Please let me know if it is not a security concern.

### Expected Behavior

Please let me know if it is not a security concern.

### Current Behavior

TargetOrigin parameter for Messaging feature postMessage using a wildcard (*) in the below location: 
ace-builds/src/ace.js at line number 2010 and which allows the potential for cross site scripting attacks from unauthorized sources.

### Reproduction Steps

TargetOrigin parameter for Messaging feature postMessage using a wildcard (*) in the below location: 
ace-builds/src/ace.js at line number 2010 and which allows the potential for cross site scripting attacks from unauthorized sources.

### Possible Solution

It is suggested by the OWASP CRV2 regarding Messaging to explicitly specify the intended target origin and do not use an open end-point / wildcard (*).

### Ace Version / Browser / OS / Keyboard layout

latest version

**Comment by Ryex** [comment]
so... the line in question is posting a `"zero-timeout-message-"+ (postMessageId++)` message. there is no user provided data in the message. How does this present a XSS?

**Comment by bsomeshwer** [comment]
Could you please elaborate @Ryex?

**Comment by Ryex** [comment]
the site in question posts a  simple hard-coded string with an incremented number who's variable is locked inside a closure.
There is no opportunity for a XSS injection which the wildcard origin would allow.

What's more from my reading the wildcard origin is *necessary*  because there is no way to know the target origin form that library function.

**Comment by bsomeshwer** [comment]
Thank you @Ryex. Thank you for the information.
