### ISSUE TITLE
Add project Contao Open Source CMS to the list of projects using Ace on its website

### ISSUE THREAD

**Issue by leofeyer** [ajaxorg/ace#5650]
### Project name

Contao Open Source CMS

### Project link

https://contao.org

### Logo link

https://contao.org/files/images/contao-logo.svg

### Additional information

We ship ACE as a Contao component: https://github.com/contao-components/ace

### Acknowledgements

- [X] I may be able to implement this request.

**Comment by whazor** [comment]
Nice! Feel free to create a PR.

**Comment by leofeyer** [comment]
See #5653 then.
