### ISSUE TITLE
yaml validation - wrong line shown

### ISSUE THREAD

**Issue by gerbil** [ajaxorg/ace#5652]
### Describe the bug

I think line 11 should be highlighted in this case (not 12) -
![image](https://github.com/user-attachments/assets/8dcfefab-1b15-400b-9449-497911aaf9d5)

### Expected Behavior

I think line 11 should be highlighted in this case

### Current Behavior

Wrong line highlighted

### Reproduction Steps

- Open kitchen sink
- Switch to YAML mode
- Add something not so valid
- Observe

### Ace Version / Browser / OS / Keyboard layout

Any

**Comment by whazor** [comment]
Hi, this feature resides in [ace-linters](https://github.com/mkslanc/ace-linters/) not in ACE.

**Comment by gerbil** [comment]
In this case there were no linters enabled.

**Comment by whazor** [comment]
In that case, please consider using [ace-linters](https://github.com/mkslanc/ace-linters/) for your project. We don't actively maintain the old language workers from ACE anymore, except for [security issues](https://github.com/ajaxorg/ace/security).
