### ISSUE TITLE
Vue mode: some attributes display incorrectly and cause cursor/editing problems

### ISSUE THREAD

**Issue by skazantsev** [ajaxorg/ace#5669]
### Describe the bug

Our users observe an odd behavior when using the Vue syntax, the following displays inconsistently:

``` vue
<template v-slot:item.parentkey.subkey="{ value }"></template>
```
When pasted into a .vue file, it get's formatted as:

``` vue
<template v-slot:item.subkey="{ value }"></template>
```

With that, the cursor location becomes inconsistent for the rest of the line, making it confusing to edit.
This appears to be purely a visual thing with the syntax. If you copy and paste to another file, or swap to another syntax, it looks fine.
It also seems restricted to character keys, i.e. if instead of `parentkey.subkey` I said `key1.subkey`, `key1.key2` or `parentkey.key2`, it'd display as expected.

### Expected Behavior

N/A

### Current Behavior

Some attribute names are not displayed correctly and cause cursor/editing problems.

### Reproduction Steps

1. Paste `<template v-slot:item.parentkey.subkey="{ value }"></template>` into https://ace.c9.io/build/kitchen-sink.html.
2. Make sure the Vue mode is used.
3. Try to place the cursor in the end of the line and edit. Observe that `v-slot:item.parent` is displayed instead of `v-slot:item.parentkey.subkey`.

### Ace Version / Browser / OS / Keyboard layout

Latest ace version

**Comment by andredcoliveira** [comment]
Probably a buggy regex in the mode. We've had an issue with Vue in the same category as this one a while ago: #5585.

@mkslanc, since you added the mode and were able to fix the previous issue, would you be able to take a look at this one?

**Comment by InspiredGuy** [comment]
https://github.com/ajaxorg/ace/pull/5671 with the fix was merged, should be available in the next release.
