### ISSUE TITLE
Java: new ArrayList<> inserts a closing HTML tag

### ISSUE THREAD

**Issue by crummy** [ajaxorg/ace#5679]
### Describe the bug

In Java, it's common to declare lists like so:
```
List<String> strings = new ArrayList<>();
```
However, if I type that in Ace today (e.g. in https://ace.c9.io/build/kitchen-sink.html in Java mode), I get this:
```
List<String> strings = new ArrayList<></>();
```
I think the behaviour was introduced in https://github.com/ajaxorg/ace/pull/5479/. Ideally this autocomplete would be limited to JSX/TSX files only.

### Expected Behavior

I want to write `new ArrayList<>();` in Java without interference.

### Current Behavior

When I write new `ArrayList<>` in Java, I end up with `new ArrayList<></>`

### Reproduction Steps

1. Open https://ace.c9.io/build/kitchen-sink.html
2. Set language to Java
3. Enter text `<>`

### Possible Solution

Limit autoclosing of `<>` to JSX/TSX files

### Ace Version / Browser / OS / Keyboard layout

version 1.36.5

**Comment by nightwing** [comment]
Fixed by the attached pull request, thank you for the report!
