### ISSUE TITLE
howto remove empty lines from document

### ISSUE THREAD

**Issue by remco-pc** [ajaxorg/ace#5689]
### Describe the bug

Copying an empty line (\n char) and try to replace it with nothing does not work with crtl-h

### Expected Behavior

pasting a \n with ctrl-c arrow up from the editor and paste it in the search field and then replace it with nothing to remove blank lines from a document

### Current Behavior

cannot past it in the search and \n\n replace with \n does not work

### Reproduction Steps

see above

### Ace Version / Browser / OS / Keyboard layout

1.4.14 edge win11 us-int

**Comment by akoreman** [comment]
Thanks for raising this issue, line break characters (`\n`) do indeed currently not work in search and replace, we're tracking this issue in #5674. I'm closing this issue as a duplicate to centralize on that other issue.
