### ISSUE TITLE
editor.selection "changeCursor" is fired too often

### ISSUE THREAD

**Issue by nightwing** [ajaxorg/ace#596]
there are too many changeCursor events 
2 for typing single character and
8 for pasting multiline text block

some way for merging those events would be useful in other places too,
codemirror wraps everthing with special `operation` function for that, but it won't work well with ace
@gissues:{"order":17.391304347826377,"status":"backlog"}

**Comment by episodeyang** [comment]
completely agree. This gets even worse when using the vim key binding.

**Comment by bwl21** [comment]
I stumbled over the same thing again. When I change the selection I get two changeSelection events. One while deselecting the previous selection and one for the new one.

My solution (not very elegant) keep the latest editor selection range somewhere and return from the changeSelection handler, if the selection is the same as in the last call.
