### ISSUE TITLE
Entering text into Ace editor scrolls down whole page in Google Chrome

### ISSUE THREAD

**Issue by pigletto** [ajaxorg/ace#600]
To reproduce:
1. Create/visit page with Ace editor that has some conent above editor (example code attached below).
2. Resize your Chrome window so that after page (re)load Ace editor is not visible (you need to scroll down to see it)
3. Enter some text into Editor - you can see that whole page is scrolled down with every key pressed.

Issue is only visible when Ace editor field is not visible after page load.

``` html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>Editor</title>
  <style type="text/css">
      div.spacer{height:500px;}
  </style>
</head>
<body>
  Scroll down to <a href="#editorwindow">editor window</a>
  <div class="spacer"></div>
  <a name="editorwindow"></a>
  <div id="editor1" style="width:300px;height:200px;position:relative;"></div>

  <script src="https://raw.github.com/ajaxorg/ace/master/build/src/ace-noconflict.js" type="text/javascript" charset="utf-8"></script>
  <script>
    window.onload = function() {
      var editor = ace.edit("editor1");    
    };
  </script>
  <div class="spacer"></div>
  the end<br />
</body>
</html>
```

@gissues:{"order":15.527950310559294,"status":"backlog"}

**Comment by dogeincomm** [comment]
I am seeing a similar issue with multiple ace editors on the same page.  Is this still happening to anyone else?

**Comment by nightwing** [comment]
@dogeincomm please share a link to a page where this happens

**Comment by dogeincomm** [comment]
Sorry it was an unrelated css error.  False alarm.  Thanks for the quick response though.
