### ISSUE TITLE
worker-javascript.js not found if editor loaded using Ajax

### ISSUE THREAD

**Issue by abdulqadir** [ajaxorg/ace#655]
If the editor is loaded using Ajax, and Javascript mode is set, it tries to load worker-javascript.js from current_url/javascript-worker.js and fails.

I suspect this is because jQuery is appending additional data to the url when the script location is read in data obtained using an Ajax call, in my case

ace-0.2.0/src/mode-javascript.js/?_=1330443139088

when requesting the script files.

**Comment by apache-commons-exec** [comment]
Sift through this https://jqcode.space/questions/what-is-the-procedure-for-adding-a-url-path-in-jquery explanation
