### ISSUE TITLE
Text goes out of align with line numbers when editor scrolls when taking a new line

### ISSUE THREAD

**Issue by jpallen** [ajaxorg/ace#73]
Lines of text have their vertical positioning set incorrectly when pressing enter at the end of a document causes the editor window to scroll. See the screenshot here: http://i.imgur.com/4Ld3V.png . The numbers in the document correspond the to line they are on and are out of alignment with the line numbers.

To reproduce, open the latest editor demo and begin to press enter at the bottom of the file. As soon as enough new lines are taken to cause the editor window to scroll, the lines will start to go out of sync. I have tested this in Chrome 8.0.552.237 and Safari 5.0.3. The bug does not seem to appear in Firefox.

I think this may be an issue or subtlety with the rendering engine of WebKit. Using the DOM Inspector shows the div.ace_content element to be shifted to the wrong place (also visible in the screenshot). If I manually remove the 'position: absolute' property from div.ace_scroller and then add it back in then div.ace_content is updated to the correct position. This seems to suggest that Ace is setting up the correct CSS properties, but something is going wrong in the rendering of them. I'm afraid at this point I don't know how to proceed with investigating the problem.

Please let me know if I can provide any more information or if you have any suggestions on how to track down the root cause of this bug. I stumbled across the editor a while ago, but only tried it out today. It's an amazing piece of work, thank you.

**Comment by don-sergio** [comment]
I think there is the same problem with the width when i use the editor with flex !
I'm using the version 0.1.9 of ng2-ace-editor.
