### ISSUE TITLE
Handy method to autowrap text in embedded editors

### ISSUE THREAD

**Issue by MikeRatcliffe** [ajaxorg/ace#82]
I have created a simple method to attomatically wrap text to the size of the visible area on resize. It is very handy for embedded editors like Acebug. Maybe you may want to include in the editor? I guess I could have used xpath but I am lazy and the document is always almost empty ;o)

```
editor.session.setUseWrapMode(true);

editorWin.addEventListener("resize", function() {
    var editor = env.editor;
    var session = editor.session;

    if(session.getUseWrapMode()) {
        var characterWidth = editor.renderer.layerConfig.characterWidth;
        var contentWidth = editor.container.ownerDocument.getElementsByClassName("ace_scroller")[0].clientWidth;

        session.setWrapLimit(parseInt(contentWidth / characterWidth, 10));
    }
}, true);
```

**Comment by mattisback** [comment]
Is there an editor option for this?
Ie. something that would be listed here: https://github.com/ajaxorg/ace/wiki/Configuring-Ace
