### ISSUE TITLE
expose JSHint's options as a configurable setting

### ISSUE THREAD

**Issue by NodeGuy** [ajaxorg/ace#895]
Currently the options sent to JSHint are hardwired [within javascript_worker.js](https://github.com/ajaxorg/ace/blob/5a7bc873010f3199c9b7d5f3266dd97dbcbe3ad1/lib/ace/mode/javascript_worker.js#L81):

``` Javascript
lint(value, {undef: false, onevar: false, passfail: false});
```

Please make them available via the public API as a configurable setting.

**Comment by homam** [comment]
I hope it helps saving time: if you like to suppress specific error / warning codes use:
```
session.$worker.send("setOptions", [ { "-W095": false, "-W025": false }])
```

**Comment by hyusetiawan** [comment]
@homam tried using that line, but it's not working, it complains that $worker is undefined, any other way to expose the jshint options? or disable the linting process altogether?

**Comment by rocketinventor** [comment]
There should be a settings file.
The sublime version lets you edit the lint settings with a master settings file, as well as per-project setting file.

**Comment by homam** [comment]
@hyusetiawan this is what I'm using:

```
editor.session.on('changeMode', function(e, session){
  if ("ace/mode/javascript" === session.getMode().$id) {
    if (!!session.$worker) {
      session.$worker.send("setOptions", [{
        "-W095": false,
        "-W025": false
      }]);
    }
  }
});
```

**Comment by electron0zero** [comment]
i had to silence `<something> is not defined` warning so is modified @homam 's code like this 
```javascript 
editor.session.on('changeMode', function(e, session){
      if ("ace/mode/javascript" === session.getMode().$id) {
          if (!!session.$worker) {
              session.$worker.send("setOptions", [{
                  "-W117": false
              }]);
            console.log("worker is silenced");
          }
          console.log("changeMode");
      }
    }); 
```

here `W117` is warning code of  `<something> is not defined` warning which i looked up in `worker-javascript.js` file.

**Comment by yihchu** [comment]
hei, if i just want to ignore some keyword in '<something> is not defined', e.g, i just want to ignore 'dog' and 'cat', how can i do

**Comment by quinton-ashley** [comment]
For anyone wondering how to change esversion in the linter scroll to the end of this issue: #3160
