### ISSUE TITLE
Ability to define keybindings to non-ace commands

### ISSUE THREAD

**Issue by leolannenmaki** [ajaxorg/ace#91]
Example:
Add a keybinding for saving:

editor.setKeyboardHandler(
  new HashHandler({
    "save": "Cmd-S"
  });
);

editor.addCommand({
    name: "save",
    exec: function(env, args, request) { 
      MyBackend.saveSourceFile(env.editor.getSession().getValue());
   }
});

**Comment by harshapps** [comment]
```
editor.commands.addCommand({
                name: "myCommand",
                bindKey: { win: "Ctrl-L", mac: "Command-L" },                
                exec: function() {
                    editor.insert("Key binded!");
                }
});     
```
