### ISSUE TITLE
Please add some way to change either the text cursor or background colour

### ISSUE THREAD

**Issue by justinclift** [ajaxorg/ace#935]
At the moment, the cursor and background colours (as implemented on GitHub itself) are _so close_ I can't distinguish them.  (And no, I'm not colour blind. :>)

So, I have to click on exact spots with the mouse in order to insert text.  Not good. :(

**Comment by latch-admin** [comment]
finally figured it out...  you have to find the element and change the style with css

.ace-tm .ace_cursor {
    color: white;
}
