### ISSUE TITLE
Built version of ace is trying to load worker-javascript.js file

### ISSUE THREAD

**Issue by Gozala** [ajaxorg/ace#972]
I'm building ace with according to instructions:

``` sh
node -m -nc ./Makefile.dryice.js
```

Later I use generated `ace-min.js` to embed ace as follows:

``` js
var editor = ace.edit("editor")
editor.setTheme("ace/theme/ambiance")
editor.getSession().setMode("ace/mode/javascript")
```

Last line attempts to send GET request to `./worker-javascript.js` and fails with an error:
**Uncaught Error: DATA_CLONE_ERR: DOM Exception 25**

I would expect that minified version will not depend on external files.

**Comment by piecioshka** [comment]
:+1:
